### PR TITLE
FileStatusList: Avoid blocking check for Visual Studio

### LINKED ISSUE #10856: `VisualStudioIntegration.IsVisualStudioRunning` can dead lock the app
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.2.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.15
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0-preview.2.23128.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Invoking the context menu that contains "Open in Visual Studio" menu can dead lock the app and the only option is to hard kill the process.
https://github.com/gitextensions/gitextensions/blob/037cb04d3b1168d197643512b5bd2d1b506042e1/GitUI/UserControls/FileStatusList.cs#L1412

I've taken a memdump:
image

### Steps to reproduce

It's quite intermittent but I observed this issue few times over the months. In essence, it occurs whenever I right click on files in FormCommit dialog that I want to stage or reset.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10856

## Proposed changes

- Do not check for a running Visual Studio on every open of the FileStatusList context menu
- Check for installed MSVS on startup in background
- Open a new instance if no running instance has opened a project with this file instead of error popup

## Screenshot

unchanged

image

removed

image

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/UserControls/FileStatusList.cs [hunk 1]
```diff
@@ -1409,8 +1409,10 @@ private void FileStatusListView_ContextMenu_Opening(object sender, CancelEventAr
                 cm.Items.Add(_NO_TRANSLATE_openInVisualStudioMenuItem);
             }
 
-            _NO_TRANSLATE_openInVisualStudioMenuItem.Visible = _openInVisualStudioSeparator.Visible = VisualStudioIntegration.IsVisualStudioRunning;
-            _NO_TRANSLATE_openInVisualStudioMenuItem.Enabled = File.Exists(SelectedItemAbsolutePath);
+            bool fileExists = File.Exists(SelectedItemAbsolutePath);
+            _NO_TRANSLATE_openInVisualStudioMenuItem.Enabled = fileExists;
```
Comment (pmiossec) [inline GitUI/UserControls/FileStatusList.cs:1413]: A specific reason why you kept the 'Enabled' whereas the item won't be visible?

Comment (mstv) [reply GitUI/UserControls/FileStatusList.cs:1413]: Please see the following lines... (I have changed the sequence.)

Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs:1413]: Remove IsVisualStudioRunning too?

**Review by gerhardol — COMMENTED** [review]
+1
This kind of removes the motivation for the menu item.
But I have no better fix for VisualStudioIntegration.

**Comment by mstv** [comment]
> This kind of removes the motivation for the menu item.

Do you need an indication in GE whether MSVS is running (perhaps only with a different project)?
Then GE should rather start MSVS instead of the error popup.
The menu item should be hidden if MSVS is not installed.
I will leave these two for a follow-up PR.

**Comment by mstv** [comment]
> Then GE should rather start MSVS instead of the error popup.
The menu item should be hidden if MSVS is not installed.

Done with the help of SO.

> The core usability problem is still that the designer opens by default.

Yes, the Solution Explorer has the same caveat. MSVS should have an internal option whether to open the code or the designer by default.
A quick search did not reveal an alternative to "File.OpenFile".

File: GitUI/VisualStudioIntegration.cs [hunk 2]
```diff
@@ -1,15 +1,52 @@
...
     internal static class VisualStudioIntegration
     {
-        public static bool TryOpenFile(string filePath)
+        static VisualStudioIntegration()
         {
-            ThreadHelper.ThrowIfNotOnUIThread();
+            ThreadHelper.JoinableTaskFactory.RunAsync(async () =>
+            {
+                await TaskScheduler.Default;
+                Executable executable = new($@"{Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86)}\Microsoft Visual Studio\Installer\vswhere.exe");
```
Comment (mstv) [inline GitUI/VisualStudioIntegration.cs:18]: Needs to check yet whether `vswhere.exe` exists.

File: GitUI/UserControls/FileStatusList.cs (hunk 1 above)
Comment (mstv) [reply GitUI/UserControls/FileStatusList.cs]: > Remove IsVisualStudioRunning too?

turned into `IsVisualStudioInstalled`

> A specific reason why you kept the 'Enabled' whereas the item won't be visible?

I am used to set both because I am not sure whether `Visible = false` overrides `Enabled`.
In theory, mnemonics could still be active if the item is enabled but invisible.

**Review by RussKie — APPROVED** [review]
