### PR TITLE
RefreshGrid without revisions

### LINKED ISSUE #10720: [NBug] fatal: bad revision 'HEAD'
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.13
- DPI 96dpi (no scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --max-count=100000 --glob=refs/stas[h] HEAD --
Working directory: C:\work\repos\Activities\

```
GitExtUtils.ExternalOperationException: fatal: bad revision 'HEAD'
 ---> System.Exception: fatal: bad revision 'HEAD'
   --- End of inner exception stack trace ---
   at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+() => { }
   at async Task GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

fetch -> abort -> error

### Steps to reproduce

fetch origin
fetch taking too long -> abort
error appears

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #10720

## Proposed changes

If stashes a are shown, the first stash to show requires explicit handling for the Git default "Show only current branch" to show stashes in the grid.
This is not possible in repos without a current branch.

## Test methodology 

Updated tests

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — COMMENTED** [review]
Do we have a test that mimics the failure scenario?

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs [hunk 1]
```diff
@@ -475,6 +497,19 @@ private void GetBranchRevisionFilter(ArgumentBuilder filter)
                     filter.Add("--boundary");
                 }
             }
+
+            // Add the most recent stash to the grid (see also --all handling)
+            void addFirstStashRef()
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/FilterInfo.cs:502]: nit:
```suggestion
            void AddFirstStashRef()
```

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs [hunk 2]
```diff
@@ -425,8 +425,8 @@ private void GetBranchRevisionFilter(ArgumentBuilder filter)
             }
             else if (IsShowCurrentBranchOnlyChecked || (IsShowFilteredBranchesChecked && !string.IsNullOrWhiteSpace(BranchFilter)))
             {
-                // See handling for --all below, explicitly add most recent stash
-                if (AppSettings.ShowStashes)
+                // See handling for --all below, explicitly add only most recent stash
+                if (AppSettings.ShowStashes && (!IsShowCurrentBranchOnlyChecked || !string.IsNullOrWhiteSpace(currentBranch.Value)))
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/FilterInfo.cs:429]: Reuse `AddFirstStashRef()`?

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs [hunk 3]
```diff
@@ -449,6 +450,27 @@ private void GetBranchRevisionFilter(ArgumentBuilder filter)
...
+                }
+            }
+            else if (IsShowFilteredBranchesChecked && !string.IsNullOrWhiteSpace(BranchFilter))
+            {
+                addFirstStashRef();
+
+                // Show filtered branches only
+                // Do not add suffix /* to the filter
+                bool isSimpleBranchFilter = BranchFilter.IndexOfAny(new[] { '?', '*', '[' }) == -1;
+                filter.Add(isSimpleBranchFilter ? BranchFilter : $"--branches={BranchFilter}");
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/FilterInfo.cs:472]: This is too detailed for the Rule Of Three IMO, i.e factor out, please.

**Review by mstv — COMMENTED** [review]
First minor comments.

What are the STR? I think that a pure fetch cannot destroy HEAD as stated in the issue.

**Comment by gerhardol** [comment]
> What are the STR? I think that a pure fetch cannot destroy HEAD as stated in the issue.

* Bare or empty repo
* Stash is shown
* CurrentBranchOnly

**Comment by mstv** [comment]
Thank you for the STR.
There seems to be yet another special case:

image

**Comment by gerhardol** [comment]
> There seems to be yet another special case:

The branch must exist too. Will change this so `CurrentCheckout` in RevisionGrid is evaluated, so other Lazy functions.

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs:429]: I left a temp implementation, just for you to have something to comment on - or I forgot to remove it.

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs (hunk 3 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs:472]: See above...

**Comment by gerhardol** [comment]
> Do we have a test that mimics the failure scenario?

No relevant test.
I will add a unit test for the failure scenario in FilterInfo_GitNotes_Stashes() but that only covers some refactoring of that function, not the grid.

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs [hunk 4]
```diff
@@ -475,6 +472,19 @@ private void GetBranchRevisionFilter(ArgumentBuilder filter)
                     filter.Add("--boundary");
                 }
             }
+
+            // Add the most recent stash to the grid (see also --all handling)
+            void AddFirstStashRef()
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/FilterInfo.cs:477]:
```suggestion

            return;

            // Add the most recent stash to the grid (see also --all handling)
            void AddFirstStashRef()
```

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs [hunk 5]
```diff
@@ -423,32 +423,29 @@ private void GetBranchRevisionFilter(ArgumentBuilder filter)
...
             }
+            else if (IsShowFilteredBranchesChecked && !string.IsNullOrWhiteSpace(BranchFilter))
+            {
+                // Show filtered branches only
+                AddFirstStashRef();
+
+                // Simple branch filter without wildcards
+                // Git adds the suffix "/*" implicitly if there is no wildcard
+                bool isSimpleBranchFilter = BranchFilter.IndexOfAny(new[] { '?', '*', '[' }) == -1;
+                filter.Add(isSimpleBranchFilter ? BranchFilter : $"--branches={BranchFilter}");
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/FilterInfo.cs:447]: Should we really keep this check for simple filter? Has git changed its behavior? Could be changed here or in a follow-up.

image

**Review by mstv — APPROVED** [review]
You've left another nit for me :)

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs (hunk 5 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs:447]: https://git-scm.com/docs/git-log#Documentation/git-log.txt---branchesltpatterngt

I assume this is a branch filter.
This PR is only changing the behavior for currentbranchonly.
The same popup, but the branch names should be validated already in the form (toolbar or advanced, normally testing the cached gitrefs first) and give a feedback that the selection is invalid.
That is a separate PR.

Comment (mstv) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs:447]: > This PR is only changing the behavior for currentbranchonly.

As stated:

>> Could be changed ... in a follow-up.

My point is: The comment `'Git adds the suffix "/*" implicitly if there is no wildcard'` seems to be wrong or does not apply to how the arguments are added here.

Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs:447]: > My point is: The comment 'Git adds the suffix "/*" implicitly if there is no wildcard' seems to be wrong or does not apply to how the arguments are added here.

The wildcard is added with --branches, not as a ref on the command line. 
Clarification?

// Git adds the suffix "/*" implicitly if there is no wildcard for --branches argument

The same 'fix' that is used for refs/stas[h] could be used here too. Then the issue with invalid references for branches could be solved relatively simple. The drawback is that it is not possible to apply any ref (or option) in the branchbox, including multiple branches (multi could be split).
It is still possible to use messages with --init --exclude prefix (_messageAsGitOptions), but that is a special feature...

--branches=<currentbranch> is an alternative for currentbranchonly, no validation of the branch is needed (so solution is more similar to the first version).

Comment (mstv) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs:447]: Since we use `--branches=` only if the branch filter already contains wildcards, I do not see the relevance of the comment - although the proposed variant is clearer.
Or does it mean that we want to avoid adding `--branches=` in order to not get the implicit "/*" appended by git?
(I don't have a preference whether branch filters should be an exact match or not. I just want to understand the intention of the code.)

Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs:447]: I mean that `feature` could be added as `--branches=featur[e]` similar to refs/stash

Comment (mstv) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs]: > I mean that `feature` could be added as `--branches=featur[e]` similar to refs/stash

This stops git from returning errors. 👍
But it doesn't work for commit hashes and HEAD, etc. 🤔

Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs]: There were actually an error when a repo was empty and stashes was shown, so I changed to always use --branches for currentbranchonly.
Actually slightly simpler code.
(I thought I had tested that, I have updated Git since then, I doubt it is that though...)

To be clear, it is the Git error code we must avoid, the behavior in the app is the same. (Just to avoid the popup, no other improvement for the user.)

Filtered branches is a separate issue. It could be possible to use similar command as here, but maybe generic refs like commits should be allowed?

Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs]: @mstv Still OK with the latest changes?
If so I will merge this and look into filtered branches (probably evaluating when exiting the text box using the ref filter to verify before rev-parse)

**Review by mstv — APPROVED** [review]
> If so I will merge this

OK for me (with the updated comment).
I have tried out some cases but most likely not thoroughly.

> and look into filtered branches (probably evaluating when exiting the text box using the ref filter to verify before rev-parse)

Or else use `--branches=GetFilterRefName(BranchFilter)` if without wildcards, too.
`useSimpleBranchFilter` might need to be kept but check for "--" in order to still support manually entered filter arguments.

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs [hunk 6]
```diff
@@ -423,31 +423,27 @@ private void GetBranchRevisionFilter(ArgumentBuilder filter)
...
+            else if (IsShowFilteredBranchesChecked && !string.IsNullOrWhiteSpace(BranchFilter))
+            {
+                // Show filtered branches only
+
+                AddFirstStashRef();
+
+                // Simple branch filter without wildcards
+                // Git adds the suffix "/*" if there is no wildcard
+                bool isSimpleBranchFilter = BranchFilter.IndexOfAny(new[] { '?', '*', '[' }) == -1;
+                filter.Add(isSimpleBranchFilter ? BranchFilter : $"--branches={BranchFilter}");
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs:446]: [nit] Please don't wrap lines too short, 120-150 range is generally something worth striving for
``suggestion
                // If BranchFilter contains wildcards, "--branches=" must be prepended.
                // But use the simple branch filter if without wildcards in order to avoid git adding implicit /* to the "--branches=" filter then.
```

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs [hunk 7]
```diff
@@ -423,31 +423,27 @@ private void GetBranchRevisionFilter(ArgumentBuilder filter)
...
-                // See handling for --all below, explicitly add most recent stash
-                if (AppSettings.ShowStashes)
-                {
-                    // stash@{0} requires that the repo has commits and --glob=refs/stash is handled as refs/stash/*,
-                    // so this weird pattern must be used: "--glob=refs/stas[h]"
-                    filter.Add($"--glob={GitRefName.RefsStashPrefix.Remove(GitRefName.RefsStashPrefix.Length - 1, 1)}[h]");
-                }
+                // Git default, no option by default (stashes is special).
+                // Add as filter anyway as the branch must exist and the repo must contain commits
+                // otherwise Git will exit with errors.
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/FilterInfo.cs:430]: Ditto here

**Review by RussKie — APPROVED** [review]

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs:446]: > Please don't wrap lines too short, 120-150 range is generally something worth striving for

Avoid over 80 chars if possible, really exceptions if more than 120 chars. It is then possible to have several editors open side by side. Especially for Visual Studio, not great with multiple monitors.

Reworded slightly. This will likely be changed anyway, if a similar (but different) check is done for filtered branches.
The second line would have been 163 characters

                // If BranchFilter contains wildcards, "--branches=" must be prepended.
                // Use the simple branch filter if without wildcards (must be Git reference)
                // in order to avoid git adding implicit /* to the "--branches=" filter.

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs [hunk 8]
```diff
@@ -475,6 +471,28 @@ private void GetBranchRevisionFilter(ArgumentBuilder filter)
...
             }
+
+            return;
+
+            // git-log filters add implicit /* to the filters, unless there are wildcard characters in the ref name
+            // get around this by adding a filter, that matches the branch name
+            string GetFilterRefName(string gitRef)
+            {
+                return $"{gitRef.Substring(0, gitRef.Length - 1)}[{gitRef[^1]}]";
+            }
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs:482]: (I was expecting to get the auto suggestion here, not sure why it did not appear at first)

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (RussKie) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs:446]: 80?! Developers are generally constrained vertically rather than horizontally.

This is how 80 looks for me:
image

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs (hunk 7 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs:430]: That line would be 136 chars, too long in my opinion.
Rewrote that too (merged the comment below), which would have resulted in a 176 char comment.

File: GitUI/UserControls/RevisionGrid/FilterInfo.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/FilterInfo.cs]: Use several editors if you do not want to use move to other view in npp.
You get much more code on your screen with that.
(I use VSC or npp at work, only with GE I use VS)

VS has some OH, but two instances are OK
image

**Review by mstv — APPROVED** [review]

**Comment by gerhardol** [comment]
Squashed with an updated commit message.
The "filtered branches" should be fixed so there are more opportunities to comment on comments.
Merging
