### PR TITLE
Fix #7250:  Error when fetching pull requests from local branch

### LINKED ISSUE #7250: Error when fetching pull requests from repo without PRs
## Current behaviour

On a relatively virgin repo with only a few commits and no pull requests ever (open, nor closed), I get the following error when I use the "GitHub" menu and then "View pull requests..."

image

After the error, it does (correctly) show me an empty "View Pull Requests" screen:
image

## Expected behaviour

No error message, just showing the empty pull requests screen.

## Steps to reproduce

See above.

If you like, you can use the following repo to reproduce, though I expect PRs to start up there over the next week or so: https://github.com/PHPCSStandards/PHPCSUtils/

## Did this work in previous version of GitExtensions

Unknown. I only recently started using the option.

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by hieuxlu**
Fix #7250: Error when fetching pull requests from local branch

## Proposed changes
- Fallback to the first remote in the list when there's no current remote

### Before
image
image

### After
image

## Test methodology 

- Manual test

## Test environment(s) 

- Git Extensions 3.3.0
- Build 00aa8df55d65c3318f45870a29129aba79529e81 (Dirty)
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs [hunk 1]
```diff
@@ -155,8 +155,13 @@ private void SetPullRequestsData(IReadOnlyList<IPullRequestInformation> infos)
         private void SelectHostedRepositoryForCurrentRemote()
         {
             var currentRemote = Module.GetCurrentRemote();
+
+            // Local branches have no current remote, return value is empty string.
+            // In this case we fallback to the first remote in the list.
+            // Currently, local git repo with no remote will show error message and can not open this dialog.
+            // So there will always be at least 1 remote when this dialog is open
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs]: Are we sure about this?

**Comment by RussKie** [comment]
Thank you

**Comment by jrfnl** [comment]
Thank you @hieuxlu ! I look forward to seeing it work in the next release ;-)

**Comment by RussKie** [comment]
@jrfnl could you please grab a portable dev build and verify it is fixed for you?
In hindsight I should have asked before merging...

**Comment by jrfnl** [comment]
@Russkie Happy to, but won't have time to test this until tomorrow at the earliest.

**Comment by RussKie** [comment]
no rush at all ☺

**Comment by jrfnl** [comment]
Tested and found working on three different repos where I previously saw the error.

**Comment by RussKie** [comment]
Thank you for the follow up
