### PR TITLE
Auto-set GE as editor only in current environment

### LINKED ISSUE #11045: GitExtensions really should not be taking over git commands without user consent
### Environment

- GitExtensions version: I downloaded this zip - GitExtensions-Portable-4.1.0.16698-1fe52a137.zip
- GIT version: 2.41.0.windows.1
- OS version:  Windows 11
- .NET version: 6,0,1623,17311 @Commit: 1e620a42e71ca8c7efb033fd525f04be5fa701fe

### Issue description

I downloaded  GitExtensions-Portable-4.1.0.16698-1fe52a137.zip and used GitExtensions.exe from the unzipped dir. my intent was to just use the UI app that way. nothing more. I thought the way I'm using would achieve that. but apparently even running just that exe make GitExtensions take over the git commandlines itself so now if I do "git rebase" it becomes "GitExtensions.exe fileeditor c:;/myrepo/.git/rebase-merge/git-rebase-todo". so I deleted the unzipped dir and now rebase is giving me an error because it still tries to find GitExtensions -

```
hint: Waiting for your editor to close the file... "C:/GitExtensions/GitExtensions.exe" fileeditor: line 1: C:/GitExtensions/GitExtensions.exe: No such file or directory
error: There was a problem with the editor '"C:/GitExtensions/GitExtensions.exe" fileeditor'.
```

if I'm only using GitExtensions from an unzipped dir (instead of installing it with an .msi) it should never take over git commands like this and especially not in a way that it would actually break existing git commands if I deleted the directory. 

### Steps to reproduce

download .zip
unzip to a dir
use GitExtensions.exe from there - I clicked ok the first time GitExtensions UI came up. did NOT repair anything.
now in a cmd, try to do a git command and observe that it's running by GitExtensions.exe

### Did this work in previous version of GitExtensions?

didn't try

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11045

## Proposed changes

- Auto-set GE as editor only in the environment of the current process (and its children)
  and not in the global git config if unset

### Before

image

### After

image

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by vbjay** [comment]
Only if portable. If not portable it should be in global.

File: GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs [hunk 1]
```diff
@@ -41,7 +41,7 @@ private bool SolveEditor()
 
             if (string.IsNullOrEmpty(editor))
             {
-                GlobalConfigFileSettings.SetPathValue("core.editor", EditorHelper.FileEditorCommand);
+                Environment.SetEnvironmentVariable(CommonLogic.GitEditorEnv, EditorHelper.FileEditorCommand);
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs:44]: Is this the only value set automatically?
If "check at startup" is not set, is the environment value set? (i.e. when is the backup env var set?)

Comment (mstv) [reply GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs]: > If "check at startup" is not set, is the environment value set? (i.e. when is the backup env var set?)

I missed that. I am adding the missing call of `SolveEditor` (later today).

> Is this the only value set automatically?

Yes, the others are internal:

```
            bool valid = SolveGitCommand();
            valid = SolveLinuxToolsDir() && valid;
            valid = SolveGitExtensionsDir() && valid;
            valid = SolveEditor() && valid;
```

> Only if portable. If not portable it should be in global.

It is just another two clicks when you configure the merge tool (see screenshot).

**Comment by mstv** [comment]
I have set this PR to draft.

> Make it overridable by the core.editor setting (set by the settings page)

Does not work. The environment variables `EDITOR` and `VISUAL` are not evaluated in a usual setup because git configures "notepad" in the system config file.
GE's `CommonLogic` suffers from #10914, too, i.e. GE is too stupid to see that `core.editor` _is_ set.
Every occurrence of settings evaluation like 
```
            var repoDistGlobalSettings = RepoDistSettings.CreateGlobal(false);
            var repoDistPulledSettings = RepoDistSettings.CreateDistributed(module, false);
            var repoDistLocalSettings = RepoDistSettings.CreateLocal(module, false);
```
must be factored out and reworked! 😠

**Comment by mstv** [comment]
FormSettings displays more actual "effective" settings now. This PR is complete. Should anything be split to a dedicated PR?

File: GitUI/CommandsDialogs/SettingsDialog/ConfigFileSettingsPage.cs [hunk 2]
```diff
@@ -24,23 +24,23 @@ protected override ISettingsSource GetCurrentSettings()
 
         public void SetEffectiveSettings()
         {
-            if (ConfigFileSettingsSet is not null)
+            if (ConfigFileSettingsSet.EffectiveSettings is not null)
```
Comment (RussKie) [inline GitUI/CommandsDialogs/SettingsDialog/ConfigFileSettingsPage.cs:27]: Could you please help me understand what changed that now ensures `ConfigFileSettingsSet` is not a null?
Should it be?
```suggestion
            if (ConfigFileSettingsSet?.EffectiveSettings is not null)
```

File: GitCommands/Settings/ConfigFileSettings.cs [hunk 3]
```diff
@@ -7,45 +7,56 @@ namespace GitCommands.Settings
...
+                allowCache);
+        }
+
+        /// <summary>
+        /// Factory added just for accessing the ctor by GitModule.LocalConfigFile in its very special way.
+        /// </summary>
+        public static ConfigFileSettings CreateLocal(ConfigFileSettingsCache effectiveSettingsCache)
+        {
+            return new ConfigFileSettings(lowerPriority: null, effectiveSettingsCache, SettingLevel.Local);
         }
```
Comment (RussKie) [inline GitCommands/Settings/ConfigFileSettings.cs:30]: I'm having difficulties reconciling the xml-doc with the implementation - e.g., there's no obvious correlation between the implementation and `GitModule.LocalConfigFile`. Also, the summary should generally be about what the method does.
Also, is there a reason why this method is public and not internal?

File: GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs [hunk 4]
```diff
@@ -20,12 +22,13 @@ public sealed class CommonLogic : Translate
         public readonly ConfigFileSettingsSet ConfigFileSettingsSet;
         public readonly GitModule Module;
 
+        public ConfigFileSettings EffectiveGlobalSettings => ConfigFileSettingsSet.EffectiveSettings.LowerPriority;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs:25]: It would be great to add a comment explaining this.

**Review by RussKie — COMMENTED** [review]
Have you given any thoughts to how it can be tested? E.g., no config, run the app, assert config...

I'm happy to help with developing a test.

**Comment by vbjay** [comment]
> Have you given any thoughts to how it can be tested? E.g., no config, run the app, assert config...
> 
> I'm happy to help with developing a test.

See https://github.com/gitextensions/gitextensions/commit/715b2f510d5e384e7d69b1e996c72eacf6788f7e

**Comment by RussKie** [comment]
😲 👍

File: GitUI/CommandsDialogs/SettingsDialog/ConfigFileSettingsSet.cs [hunk 5]
```diff
@@ -2,20 +2,10 @@
...
-            LocalSettings = localSettings;
-            GlobalSettings = globalSettings;
-        }
-    }
+#pragma warning disable SA1313 // Parameter names should begin with lower-case letter
+    public readonly record struct ConfigFileSettingsSet(
+        ConfigFileSettings EffectiveSettings,
+        ConfigFileSettings LocalSettings,
+        ConfigFileSettings GlobalSettings);
+#pragma warning restore SA1313 // Parameter names should begin with lower-case letter
```
[the remark this answers is not in the document]
Comment (mstv) [reply GitUI/CommandsDialogs/SettingsDialog/ConfigFileSettingsSet.cs:10]: Need to rebase on #11056...

File: GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs [hunk 6]
```diff
@@ -10,6 +10,8 @@ namespace GitUI.CommandsDialogs.SettingsDialog
 {
     public sealed class CommonLogic : Translate
     {
+        internal const string LowestPrioGitEditorEnv = "EDITOR";
```
[the remark this answers is not in the document]
Comment (mstv) [reply GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs:13]: > [nit] don't abbreviate.

I agree.

> Why are you proposing `LowestPrio` prefix?

image

in order to

> Make it overridable by the core.editor setting (set by the settings page)

during runtime, i.e. without the need to restart GE.
In contrast to "GIT_EDITOR".

File: GitUI/CommandsDialogs/SettingsDialog/ConfigFileSettingsPage.cs (hunk 2 above)
Comment (mstv) [reply GitUI/CommandsDialogs/SettingsDialog/ConfigFileSettingsPage.cs:27]: I have turned `ConfigFileSettingsSet` into a `[record] struct`.

File: GitCommands/Settings/ConfigFileSettings.cs (hunk 3 above)
Comment (mstv) [reply GitCommands/Settings/ConfigFileSettings.cs:30]: I have declared the `ConfigFileSettings` ctor `private` in order to avoid misuse / wrong use in the future (and to find all usages).
To be honest, I do not fully understand the implementation of `GitModule.LocalConfigFile`. So I added this factory method with the same implementation as before.
`GitModule.LocalConfigFile` is unrelated to the original issue, and I hesitate to change this heavily used property.

File: GitUI/CommandsDialogs/SettingsDialog/ConfigFileSettingsPage.cs (hunk 2 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/SettingsDialog/ConfigFileSettingsPage.cs:27]: Makes sense 👍

File: GitCommands/Settings/ConfigFileSettings.cs (hunk 3 above)
Comment (RussKie) [reply GitCommands/Settings/ConfigFileSettings.cs:30]: Can we make this `internal`?

File: GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (RussKie) [reply GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs:13]: So we have `GIT_EDITOR` and `EDITOR` env variables. The changes to the former requires the app to restart, and to the latter doesn't, right? If so, should we define two consts: `GIT_EDITOR` --> `PresetGitEditorEnvVariableName` and `EDITOR` --> `AmbientGitEditorEnvVariableName`?

[the remark this answers is not in the document]
Comment (mstv) [reply GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs]: Done

> So we have `GIT_EDITOR` and `EDITOR` env variables. The changes to the former requires the app to restart, and to the latter doesn't, right?

Yes, if `GIT_EDITOR` were set, changes to `core.editor` would be ignored by git.

File: GitCommands/Settings/ConfigFileSettings.cs (hunk 3 above)
Comment (mstv) [reply GitCommands/Settings/ConfigFileSettings.cs]: Done

File: GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs (hunk 4 above)
Comment (mstv) [reply GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs]: I have created a function `ConfigFileSettings.GetEffectiveGlobalSettings()`.

**Comment by mstv** [comment]
> Have you given any thoughts to how it can be tested? E.g., no config, run the app, assert config...

Since the system-wide config would need to be setup in a controlled state, this may become complex (raised privileges or isolated usage of portable git installation).
Furthermore, it might difficult too to verify the new expected result "un/set EDITOR environment variable".
I have tested manually in a VM.

**Comment by vbjay** [comment]
We need to spell out the expectations for environment config and git config

My thoughts are git config system and global should apply and then environment should overwrite any common config... then repo level git config( distributed and down  should then override the environment.  We need to  treat environment as another hierarchy in the git config as it were with specific settings.

**Comment by mstv** [comment]
I do not get the point, Jay. GE cannot change the hierarchy of which editor git uses.

We just want to automatically add the GE editor if no editor is configured. This is a convenience feature.
So we need to check whether an editor is configured in the system or global git config or in the environment.
With this PR, we automatically set `EDITOR`, which has the lowest priority.
Hence every git config setting can override it (without the need to restart GE). Repo-specific configs should work well, too.

GE's own implementation of the git config is complex enough. We should not replicate more of the git logic, i.e. we should not attempt to additionally consider environment variables in the settings pages.

**Comment by vbjay** [comment]
> I do not get the point, Jay. GE cannot change the hierarchy of which editor git uses.
> 
> We just want to automatically add the GE editor if no editor is configured. This is a convenience feature.
> So we need to check whether an editor is configured in the system or global git config or in the environment.
> With this PR, we automatically set `EDITOR`, which has the lowest priority.
> Hence every git config setting can override it (without the need to restart GE). Repo-specific configs should work well, too.
> 
> GE's own implementation of the git config is complex enough. We should not replicate more of the git logic, i.e. we should not attempt to additionally consider environment variables in the settings pages.



I know this but we need to respect and read all of the config including system and we need to spell out somewhere exactly what the full hierarchy is. 

This needs to be defined and made clear in ui that environment wins or git config wins. Spell it out so that everyone understands and knows what is expected.

We need to read at the least system git config and we need to read environment values at the right level to match expectations. So document what is expected first.

**Comment by mstv** [comment]
> read all of the config including system

This is attained with this PR for all usages (I think; except for conditional includes).

> we need to spell out somewhere exactly what the full hierarchy is

duplicate request of https://github.com/gitextensions/gitextensions/issues/10914#issuecomment-1528101222
This is work in progress.

> This needs to be defined and made clear in ui that environment wins or git config wins. Spell it out so that everyone understands and knows what is expected.

I do not want to overload the settings pages with environment variables. For such edge details, the user shall read the only source of truth - the git manual (if not the git code).

Again, this PR is about a convenience feature (which misbehaved).
You can configure the editor as you want using the settings page. For the settings source "Effective", the system-wide git config is considered, too.

**Comment by vbjay** [comment]
> > Have you given any thoughts to how it can be tested? E.g., no config, run the app, assert config...
> > I'm happy to help with developing a test.
> 
> See [715b2f5](https://github.com/gitextensions/gitextensions/commit/715b2f510d5e384e7d69b1e996c72eacf6788f7e)

See https://github.com/gitextensions/gitextensions/pull/11060  which has an encoding fix and idea of where I am going with the Windows Sandbox feature to allow clean machine testing.

**Comment by mstv** [comment]
I have kept the actual fix only.
The evaluation of the system-wide git config remains open for later (existing ticket #10914).
This does not have an effect on this fix because it does not matter if GE sets `$EDITOR` although a `core.editor` is set in the - not evaluated - system-wide git config. `core.editor` takes precedence over `$EDITOR`.

**Review by RussKie — APPROVED** [review]
If this is fixing the issue

**Review by gerhardol — APPROVED** [review]
have not run
