### PR TITLE
SidePanel: Context menu at no selection

### LINKED ISSUE #10327: [NBug] Object reference not set to an instance of an object.
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 216dpi (225% scaling)

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.BranchTreePanel.RepoObjectsTree.contextMenu_Opening(Object sender, CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnOpening(CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ContextMenuStrip.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   at System.Windows.Forms.Control.WmContextMenu(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

Using left-hand column:
1. Turned on Stashes
2. Turned off Submodules and Tags
3. Clicked collapse all
4. Right-click empty space in the left-hand column
Error thrown

Playing around, this appears to occur if you turn off the currently selected node, e.g.
1. Click to highlight Branches
2. Click the button to hide Branches
3. Right-click empty space

I imagine the context menu is trying to adapt to the current selected node, but that is now hidden/removed, so a simple null check and return would fix this.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #10327

## Proposed changes

If nothing was selected (if branches/remotes/tags/submodules/stash), the context menu raised an exception.

The only required change is on line 213, the rest is cleanup for annotation.
A change like below is not really required as `isSingleSubmoduleSelected` is false (line 212 is not even required), but it limits the risk for future issues.

```diff
-            EnableMenuItems(isSingleSubmoduleSelected && !isBareRepository && submoduleNode.IsCurrent, mnubtnManageSubmodules, mnubtnSynchronizeSubmodules);
+            EnableMenuItems(isSingleSubmoduleSelected && !isBareRepository && submoduleNode?.IsCurrent is not null, mnubtnManageSubmodules, mnubtnSynchronizeSubmodules);
```

## Test methodology 

Manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

File: GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs [hunk 1]
```diff
@@ -72,17 +72,17 @@ private void EnableRemoteBranchContextMenu(bool hasSingleSelection, NodeBase sel
...
             bool isSingleRemoteRepoSelected = hasSingleSelection && selectedNode is RemoteRepoNode;
-            var remoteRepo = selectedNode as RemoteRepoNode;
+            RemoteRepoNode? remoteRepo = selectedNode as RemoteRepoNode;
             mnubtnManageRemotes.Enable(isSingleRemoteRepoSelected);
-            EnableMenuItems(isSingleRemoteRepoSelected && remoteRepo.Enabled, mnubtnFetchAllBranchesFromARemote, mnubtnDisableRemote, mnuBtnPruneAllBranchesFromARemote);
-            mnuBtnOpenRemoteUrlInBrowser.Enable(isSingleRemoteRepoSelected && remoteRepo.IsRemoteUrlUsingHttp);
-            EnableMenuItems(isSingleRemoteRepoSelected && !remoteRepo.Enabled, mnubtnEnableRemote, mnubtnEnableRemoteAndFetch);
+            EnableMenuItems(isSingleRemoteRepoSelected && remoteRepo?.Enabled is not null, mnubtnFetchAllBranchesFromARemote, mnubtnDisableRemote, mnuBtnPruneAllBranchesFromARemote);
+            mnuBtnOpenRemoteUrlInBrowser.Enable(isSingleRemoteRepoSelected && remoteRepo?.IsRemoteUrlUsingHttp is not null);
+            EnableMenuItems(isSingleRemoteRepoSelected && !remoteRepo?.Enabled is not null, mnubtnEnableRemote, mnubtnEnableRemoteAndFetch);
```
Comment (mstv) [inline GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs:82]: Rather `is true`?

Comment (gerhardol) [reply GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs:82]: yes, will follow up
