### PR TITLE
fix: NRE when trying to push

### LINKED ISSUE #3862: System.NullReferenceException when trying to push
Happens when trying to push, no matter how (Choosing push from Commands or toolbar, using push hotkey (ctrl+up), "Commit and Push" in commit window). Giving me "System.NullReferenceException: Object reference not set to an instance of an object." on "Void UpdateRemoteBranchDropDown() @ GitUI.CommandsDialogs.FormPush" by opening a crash report window.

The problem started after installing GitExtensions 2.50.01 (Git 2.10.0, Windows 10 version 1703 build 15063.483).
Redownloaded and reinstalled but no luck.

There are many graphical bugs too, some related to being incompatible with 4k resolution, which i don't know if i have to open issues for them or not.

### PR DESCRIPTION
**Pull request by RussKie**
An attempt to push when no remote defined would result in NRE.
Check for remotes before pushing. If no remotes available, show an error message and a prompt to
configure remotes.

Fixes #3862.

Screenshots before and after (if PR changes UI):
Before:
image

After:
image

Has been tested on (remove any that don't apply):
 - Windows 10 and above
- Ubuntu 17.04

### CODE REVIEW

File: GitUI/CommandsDialogs/FormPush.cs [hunk 1]
```diff
@@ -150,10 +153,40 @@ public DialogResult PushAndShowDialogWhenFailed()
...
 
+
+        private bool CheckRemotePresent()
+        {
+            if (_gitRemoteController.Remotes.Count < 1)
+            {
+                if (DialogResult.Yes == MessageBox.Show(this, _configureRemote.Text, _errorCaption.Text, MessageBoxButtons.YesNo, MessageBoxIcon.Error))
+                {
+                    // launch remote management dialog
+                    ManageRemotes(null);
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/FormPush.cs]: Rename to be more meaningfull (like `OpenRemoteDialogAndRefreshLIst`) and remove comment...

File: GitUI/CommandsDialogs/FormPush.cs [hunk 2]
```diff
@@ -150,10 +153,40 @@ public DialogResult PushAndShowDialogWhenFailed()
...
+                MessageBox.Show(this, _selectRemote.Text, _errorCaption.Text, MessageBoxButtons.OK, MessageBoxIcon.Error);
+                return false;
+            }
+            return true;
+        }
+
+        private void ManageRemotes(string selectedRemoteName)
+        {
+            // launch remote management dialog
+            UICommands.StartRemotesDialog(this, selectedRemoteName);
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/FormPush.cs]: Remove comment

File: GitUI/CommandsDialogs/FormPush.cs [hunk 3]
```diff
@@ -150,10 +153,40 @@ public DialogResult PushAndShowDialogWhenFailed()
...
+
+            // coming back from the dialog, update the remotes list
+            _gitRemoteController.LoadRemotes(false);
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/FormPush.cs]: Extract to method and remove comment

File: GitUI/CommandsDialogs/FormPush.cs [hunk 4]
```diff
@@ -690,13 +728,7 @@ private void AddRemoteClick(object sender, EventArgs e)
         {
             // store the selected remote name
             string selectedRemoteName = _selectedRemote.Name;
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/FormPush.cs]: Remove this useless variable (and comment), now

File: GitUI/CommandsDialogs/FormPush.cs [hunk 5]
```diff
@@ -150,10 +153,40 @@ public DialogResult PushAndShowDialogWhenFailed()
             return PushAndShowDialogWhenFailed(null);
         }
 
+
+        private bool CheckRemotePresent()
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/FormPush.cs]: `CheckIfRemotePresent`? `CheckIfRemoteExist`?

File: GitUI/CommandsDialogs/FormPush.cs [hunk 6]
```diff
@@ -70,6 +71,8 @@ public partial class FormPush : GitModuleForm
             new TranslationString("Force push may overwrite changes since your last fetch. Do you want to use the safer force with lease instead?");
         private readonly TranslationString _forceWithLeaseTooltips =
             new TranslationString("Force with lease is a safer way to force push. It ensures you only overwrite work that you have seen in your local repository");
+
+        private readonly TranslationString _errorCaption = new TranslationString("Error");
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/FormPush.cs]: Is it because that already exist? or should we use a more meaning full text ('No remotes configured'?).

Comment (RussKie) [reply GitUI/CommandsDialogs/FormPush.cs]: This a caption for a message box

File: GitUI/CommandsDialogs/FormPush.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormPush.cs]: what exactly needs extracting?

File: GitUI/CommandsDialogs/FormPush.cs (hunk 4 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormPush.cs]: umm what?

Comment (pmiossec) [reply GitUI/CommandsDialogs/FormPush.cs]: Now that you replaced all the code by a method, this `selectedRemoteName` var is useless (and the comment, too). Its name don't bring more information.
Replace by ` ManageRemotes(_selectedRemote.Name);`

File: GitUI/CommandsDialogs/FormPush.cs (hunk 3 above)
Comment (pmiossec) [reply GitUI/CommandsDialogs/FormPush.cs]: using comment is not a very good practice to describe what the code do (should be kept to explain why).
If needed, that's better to put the code in a method describing what is done (and let the compiler inline the code).
So, I think, that's better to put the 2 lines in a method (why not called `UpdateRemoteList()`?).

File: GitUI/CommandsDialogs/FormPush.cs (hunk 6 above)
Comment (pmiossec) [reply GitUI/CommandsDialogs/FormPush.cs]: yes, I see that. But I'm not always pleased when I see caption not meaningful and not helping at all.
I just would like to know if you did it by convenience because the translated string already exist? Or you introduced it?
It's not a big deal...
But someone it helps the user (to quickly understand because he is used to) when the popup is displayed often. But here, it should quite never happen.

File: GitUI/CommandsDialogs/FormPush.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormPush.cs]: I totally agree, comments should describe 'why' (if necessary), and not 'what'.

The comments were existing artifacts (which I have probably introduced originally... /facepalm )

File: GitUI/CommandsDialogs/FormPush.cs (hunk 6 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormPush.cs]: It is a valid point
I found [Windows design guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742471.aspx), I'll adjust the title accordingly
