### PR TITLE
FullPathResolver: Avoid exception for illegal characters

### LINKED ISSUE #7862: [NBug] Illegal characters in path.
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.Editor.FileViewer.ViewItemAsync(String fileName, Func`1 getImage, Func`1 getFileText, Func`1 getSubmoduleText, Action openWithDifftool)
   at GitUI.Editor.FileViewer.<>c__DisplayClass92_0.<ViewFileAsync>b__0()
   at GitUI.Editor.FileViewer.ShowOrDeferAsync(Int64 contentLength, Func`1 showFunc)
   at GitUI.Editor.FileViewer.ViewFileAsync(String fileName, Action openWithDifftool)
   at GitUI.CommandsDialogs.FormCommit.<SetSelectedDiffAsync>d__137.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.FormCommit.<>c__DisplayClass136_0.<<ShowChanges>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
cannot open file with illegal characters in path

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #8364: [NBug] Illegal characters in path.
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.FileStatusList.FileStatusListView_MouseMove(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.ExListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
In the commit window click Assume Unchanged on files then Open the commit window again, select Working directory changes -> Show Assumed Unchanged files. Select or right click any of the files.

## Environment
- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #8437: [NBug] Context menu > "Save remote" crashes in merge resolution dialog
## Current behaviour

Context menu > "Save remote" crashes on merge resolution dialog after switch branch with dirty workdir

## Expected behaviour
UI to save the remote file should work..

## Error Details
```
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.CommandsDialogs.FormResolveConflicts.SaveAs(String side)
   at GitUI.CommandsDialogs.FormResolveConflicts.ContextSaveRemoteAs_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4200.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #8571: [NBug] Illegal characters in path.
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.Editor.FileViewer.SetVisibilityDiffContextMenu(Boolean visibleTextFile, String fileName)
   at GitUI.Editor.FileViewer.ResetForText(String fileName)
   at GitUI.Editor.FileViewer.<>c__DisplayClass105_0.<ViewTextAsync>b__0()
   at GitUI.Editor.FileViewer.ShowOrDeferAsync(Int64 contentLength, Func`1 showFunc)
   at GitUI.Editor.FileViewer.<ViewTextAsync>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<ShowSelectedFileDiffAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<<DiffFiles_SelectedIndexChanged>b__36_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Created a github wiki page with the title
00-abc-"d"-e-f-g,h-(ij)-k&l-m;-n@o

Fetched updates from github, clicked on the newly-fetched commit, and clicked on the Diff tab in Git Extensions when this failure occurred.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.20.1.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #8571 
Fixes #8364 
Fixes #8437
Fixes #7862

## Proposed changes

FullPathResolver throws if a file name contains Windows illegal characters that could be OK in Git repos. 
As FullPathResolver is often used to check if a local file exists for instance to enable menu items, an exception
is normally not required and null can be returned instead. 
For instance `File.Exists(null) ==false`.

In some situations returning null will still cause a null exceptions instead.
Reviewed the usage of Resolve() to change situations where null should not be fatal. This review is best effort, there may be other situations that should be changed too. Most "null unhandled" are used in Process(), there are other PRs there.
Some handling already use try-catch, like Delete in FormCommit.

An alternative would be to add a new method like `bool TryResolve(string path)` or `bool Resolve(string path, bool throw = true)` and change the about 45 of 60 Resolve() call sites to explicitly not throw.

## Test methodology

Tests updated

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Git/GitRevisionTester.cs [hunk 1]
```diff
@@ -75,16 +75,7 @@ public bool AnyLocalFileExists(IEnumerable<GitItemStatus> selectedItemsWithParen
...
-            {
-                string filePath = _fullPathResolver.Resolve(item.Name);
-                if (_fileSystem.File.Exists(filePath))
-                {
-                    return true;
-                }
-            }
-
-            return false;
+            return items.Any(item => _fileSystem.File.Exists(_fullPathResolver.Resolve(item.Name)));
```
Comment (RussKie) [inline GitCommands/Git/GitRevisionTester.cs:78]: Keep it as `foreach` it has less overhead.

**Review by RussKie — COMMENTED** [review]
LGTM, though once we move to .NET most of this will be irrelevant. In .NET Core 2.1 System.IO has gone an extensive update, and a number of exceptions that were previously thrown aren't thrown any more.
Here's a blog post https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/system-io-in-net-core-2-1-sneak-peek

File: GitCommands/Git/GitRevisionTester.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Git/GitRevisionTester.cs]: reverted and rebased on master

**Comment by gerhardol** [comment]
> LGTM, though once we move to .NET most of this will be irrelevant. In .NET Core 2.1 System.IO has gone an extensive update, and a number of exceptions that were previously thrown aren't thrown any more.
> Here's a blog post https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/system-io-in-net-core-2-1-sneak-peek

Many of the changes in the second commit are still needed with Core 2.1.

I added one new commit, to be able to show the file in diff tab.
A repo to test with: git@github.com:gerhardol/tmp_test.git

RevTree does not work still, will be handled by the .NET Core 2.1 changes (some Path methods that throws when getting extensions etc. Should this be fixed here?)

**Comment by gerhardol** [comment]
Some corrections and more situations handled. 
I added a wrapper for Path.Combine() and Path.GetExtension() to handle Git manipulation with Path utilities, that could be replaced with .NET Core if the app is migrated.

It is now possible to view commits with illegal characters in the path, also in the revtree.
Such commits cannot be checked out in Git, so you cannot do much more than than to view in RevDiff and RevTree.
Also difftool cannot be opened. Most context menu items are as expected, but Git fails for instance to run difftool (also from command line). Some details could be improved, like you can "Save for diff later" also if the path is evaluated as empty, but that are edge cases.

There has been a number of similar cases in the past, this should prevent some to occur.

> LGTM, though once we move to .NET most of this will be irrelevant. In .NET Core 2.1 System.IO has gone an extensive update, and a number of exceptions that were previously thrown aren't thrown any more.
> Here's a blog post https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/system-io-in-net-core-2-1-sneak-peek

Note that the official API is still not updated, the blog post is the best source I found to describe the change.
I am a little surprised that there are so few mentions about this on the net...
The MS open issue about fixing the documentation:
https://github.com/dotnet/dotnet-api-docs/issues/1685

**Comment by RussKie** [comment]
> Note that the official API is still not updated, the blog post is the best source I found to describe the change.
> I am a little surprised that there are so few mentions about this on the net...

Aye! I had to ask questions internally to find this blog.

File: UnitTests/GitCommands.Tests/Config/ConfigFileTest.cs [hunk 2]
```diff
@@ -54,27 +54,16 @@ private static string GetDefaultConfigFileContent()
...
         {
             var args = new GitArgumentBuilder("config")
             {
                 "-f",
                 cfgFile.Quote(),
                 "--get",
-                key.Quote()
+
+                // Quote the key without unescaping internal quoutes (they will be lost in the shell)
+                "\"" + key + "\""
```
Comment (RussKie) [inline UnitTests/GitCommands.Tests/Config/ConfigFileTest.cs:66]:
```suggestion
                $"\"{key}\""
```

**Review by RussKie — APPROVED** [review]

File: GitCommands/StringExtensions.cs [hunk 3]
```diff
@@ -190,7 +190,7 @@ public static string Quote([CanBeNull] this string s, [NotNull] string quotation
                 return "";
             }
 
-            return quotationMark + s + quotationMark;
+            return quotationMark + s.Replace(quotationMark, "\\" + quotationMark) + quotationMark;
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/StringExtensions.cs]: A little too long expression to be really readable though.
I considered removing quotationMark  parameter (it is used in one call only) or shorten the name to 'q' to simplify.

[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/StringExtensions.cs]: That isn't a blocking comment, more a general suggestion.

**Comment by RussKie** [comment]
Merge at will

**Comment by RussKie** [comment]
Please fix the history and merge

**Comment by gerhardol** [comment]
> Please fix the history and merge

I have been a little busy and want ted to revise this again.
(We should not have so many open PRs in general.)

Some logic cleanups, and a resolve-stage revert
Unless there are protests, I will squash tomorrow and schedule a merge a day later.

**Comment by RussKie** [comment]
Just merge it. I think it has been open long enough for protests to surface
:)
