### PR TITLE
Set GIT_SSH only if path exists

### LINKED ISSUE #9112: SSH broken after upgrade to 3.5.0 (due to breaking setting change)
## Current behaviour

Any repo for which the remote is set as `git@github.com:....` can no longer communicate with remotes.

## Expected behaviour

That essential settings do not change value in a functionality breaking way when updating to a new minor.

## Steps to reproduce

1. Have GitExtensions 3.4.3
2. In Settings -> SSH -> make sure it is set to PuTTY
3. Have a repo set up with a `git@github.com:...` remote URL and a link to the Private key saved in the settings for the remote repository.
4. Upgrade to GitExtensions 3.5.0.
5. Try to `Fetch all` for the repo and see the below error message.
6. Go to Settings -> SSH and conclude that it is no longer set to PuTTY, but to the `ssh` command in the system `git` directory.
7. Change the setting back to PuTTY to get things working again.

## Screenshots

image

## Did this work in previous version of GitExtensions

Yup, worked fine in 3.4.3.

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 144dpi (150% scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #9112

Presentation handled in #9149
A second part separated to #9188 

Also for 3.5, but translation changes to be null

## Proposed changes

If the SSH path does not exist, do not set GIT_SSH env var. 
Git will then attempt to use OpenSSH included with Git.

In 3.4 or earlier, the OpenSSH path was set in the registry, even if it was supposed to be empty (handled in #9149).
If the OpenSSH path is corrupted (as reported and discussed in #9112 when upgrading GE) it will just be ignored.
This will also recover from issues if the Git installation is changed.

The settings will check and report an illegal path too.

Note that viewing the SSH setting will change the presented, then saved path if the path does not exist. A follow up PR will address this.

## Test methodology 

Modify the gitssh key in the registry and start GE and make sure that OpenSSH can still be used.

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Comment by gerhardol** [comment]
Added then removed cleanup of handling registry vs GIT_SSH env var. That part could be skipped for 3.5

**Comment by gerhardol** [comment]
@msftbot merge in 1 day

File: GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs [hunk 1]
```diff
@@ -27,8 +27,11 @@ public partial class ChecklistSettingsPage : SettingsPageWithHeader
         private readonly TranslationString _gitVersionFound =
             new TranslationString("Git {0} is found on your computer.");
 
-        private readonly TranslationString _unknownSshClient =
-            new TranslationString("Unknown SSH client configured: {0}.");
+        private readonly TranslationString _sshClientNotFound =
+            new TranslationString("SSH client not found: {0}.");
+
+        private readonly TranslationString _otherSshClient =
+            new TranslationString("Other SSH client configured: {0}.");
```
Comment (mstv) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs:34]: Nit:
```suggestion
        private readonly TranslationString _sshClientNotFound = new("SSH client not found: {0}.");

        private readonly TranslationString _otherSshClient = new("Other SSH client configured: {0}.");
```
Should we activate the regarding code analyzer?

**Review by mstv — APPROVED** [review]
LGTM, have not run

File: GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs]: Added a commit for IDE0090
https://github.com/gitextensions/gitextensions/pull/9095#issuecomment-840428715

This was on my mind, but it would have to be handled when rebasing c#9 new()
