### PR TITLE
Show branch name in dashboard and menus for reftable repos

### LINKED ISSUE #12628: A reftable repo's current branch name is shown as ".invalid" on the dashboard and in "recently used" lists
### Environment

- Git Extensions 33.33.33
- Build 32a51b64f950de734c291a91ab77bee7243ab80f
- Git 2.51.2.windows.1
- Microsoft Windows NT 10.0.26200.0
- .NET 9.0.10
- DPI 144dpi (150% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 8.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 8.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 9.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 10.0.0-rc.2.25502.107 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

### Issue description

This is a follow-up on #12491. The current branch name was not retrieved correctly for repos using the reftable backend since the HEAD file contains the name ".invalid" on such repos. This was fixed with #12498 by executing a git command to get the current branch if the HEAD file contains ".invalid".

The issue that is still open is the question of how to deal with reftable repos in the dashboard and in the "recently used" lists in the menu and toolbar. GitExtensions uses **only** `GetSelectedBranchFast` in those places. It does not fall back to the regular `GetSelectedBranch` function (which executes a git command) for performance reasons.

Some approaches were discussed in the other pull request but no decision was made. My understanding is that we could add a setting to show branch names of reftable repos in the dashboard and menus (by executing a git command via `GetSelectedBranch`.

There is a setting to show branch names in those places in general under `GitExtensions --> Appearance` already.

Image

We could add a "sub-setting" to this one that explicitly allows us to fall back to calling a git command in reftable repos while warning the user that it might noticeably affect performance?

Something like:

```
[ ] Also show current branch names for reftable repos (might affect performance)
```

I would like to implement a solution for this. But I would need a decision from the maintainers on which way to go. Would such a setting be okay? If yes, should it be default on or off? What alternatives do we have?

### Steps to reproduce

1. Create a git repository using the reftable backend (`git init --ref-format=reftable`)
2. Make any commit
3. Open the repository in GitExtensions
4. Open the recent repositories dropdown or go to the dashboard
    

Image

### Did this work in previous version of GitExtensions?

No

### Diagnostics

Not relevant

### PR DESCRIPTION
**Pull request by nikolaosginos**
Fixes #12628

## Proposed changes

- Make `GetSelectedBranchFast` private
- Inject GitModule into classes that previously used `GetSelectedBranchFast` directly
- If reading the HEAD file returns ".invalid" in a `GitModule` instance once, remember it and don't read it again the next time since we now know that we are in a reftable repo (see [#12642](https://github.com/gitextensions/gitextensions/issues/12642#issuecomment-3518291628))
- I also tried getting that information by using git config instead, but I felt like there was a noticeable delay in the recent repositories menu if I did that with 18 repos (about half of them reftable repos) (no measurements done)

### Before

image

### After

image

## Test methodology 

- Manual tests

## Test environment(s) 

- GIT 2.51.2
- Windows 11 25H2

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by nikolaosginos** [comment]
@gerhardol: Can you please test this in your repos and see how much of an impact this has on performance in your case?

As of this commit, we always create a `GitModule` instance to get the branch name. We did not do this before in the dashboard and menu. But we only actually execute a git command if the fast method does not work. So the effect should be less noticeable if you don't have any reftable repos.

The `GitModule` instance remembers it if it notices that it is in a reftable repo. So if we are in an open repo, we don't try the fast method again since we know it won't work. But this has no effect in the dashboard and menus since they get a new `GitModule` instance to check every time.

File: src/app/GitCommands/ServiceContainerRegistry.cs [hunk 1]
```diff
@@ -8,6 +8,6 @@ public static class ServiceContainerRegistry
 {
     public static void RegisterServices(ServiceContainer serviceContainer)
     {
-        serviceContainer.AddService<ISubmoduleStatusProvider>(new SubmoduleStatusProvider());
+        serviceContainer.AddService<ISubmoduleStatusProvider>(new SubmoduleStatusProvider((path) => new GitModule(path)));
```
Comment (RussKie) [inline src/app/GitCommands/ServiceContainerRegistry.cs]: [nit] I think the parens are unnecessary -> `...new SubmoduleStatusProvider(path => new GitModule(path))`

**Comment by gerhardol** [comment]
> @gerhardol: Can you please test this in your repos and see how much of an impact this has on performance in your case?
> 
> As of this commit, we always create a `GitModule` instance to get the branch name. We did not do this before in the dashboard and menu. But we only actually execute a git command if the fast method does not work. So the effect should be less noticeable if you don't have any reftable repos.
> 
> The `GitModule` instance remembers it if it notices that it is in a reftable repo. So if we are in an open repo, we don't try the fast method again since we know it won't work. But this has no effect in the dashboard and menus since they get a new `GitModule` instance to check every time.

I do not see any slowdowns, also with many repos. I had the intention to see why the dropdown is so unusable for me also with the "fast" path, but have not gotten there.
It would be interesting to see what the performance is with many reftable repos, but that is not something that have to be done here now.
Maybe the possibility to disable branch in the dropdown is good enough?

With #12660 the opening is just faster than exiting to the dashboard, but it seems slower as the "animation" is less visible.

Just a brief review. Seems fine. I just need to understand that the _getModule() handling is the way to go.

**Comment by nikolaosginos** [comment]
Thanks for the feedback. I only have about 5-10 reftable repos in my list and I did not feel like it was noticeably slower. Did not test it with more repos and actual measurement either though.

> I just need to understand that the _getModule() handling is the way to go.

I mainly did it like that due to [this comment](https://github.com/gitextensions/gitextensions/pull/12498#discussion_r2311933528). Hope I did not misunderstand it.

File: src/app/GitCommands/Git/GitModule.cs [hunk 2]
```diff
@@ -2931,11 +2933,18 @@ public static string GetSelectedBranchFast(string? repositoryPath, bool emptyIfD
...
+        if (!_isReftableRepo)
         {
-            return head;
+            string head = GetSelectedBranchFast(WorkingDir, emptyIfDetached);
+
+            if (head == ".invalid")
+            {
+                _isReftableRepo = true;
+            }
+            else if (!string.IsNullOrEmpty(head))
```
Comment (mstv) [inline src/app/GitCommands/Git/GitModule.cs]: just for clarity because `head` cannot be `null` here
```suggestion
            else if (head.Length > 0)
```

File: src/app/GitUI/RepositoryCurrentBranchNameProvider.cs [hunk 3]
```diff
@@ -18,14 +19,21 @@ public interface IRepositoryCurrentBranchNameProvider
 
 internal sealed class RepositoryCurrentBranchNameProvider : IRepositoryCurrentBranchNameProvider
 {
+    private readonly Func<string, IGitModule> _getModule;
+
+    public RepositoryCurrentBranchNameProvider(Func<string, IGitModule> getModule)
+    {
+        _getModule = getModule;
+    }
+
```
Comment (mstv) [inline src/app/GitUI/RepositoryCurrentBranchNameProvider.cs]: could be shortened to (but see comments below first):
```suggestion
internal sealed class RepositoryCurrentBranchNameProvider(Func<string, IGitModule> getModule) : IRepositoryCurrentBranchNameProvider
{
    private readonly Func<string, IGitModule> _getModule = getModule;
```

File: src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs [hunk 4]
```diff
@@ -272,10 +278,10 @@ private static string GetBranchNameSuffix(string repositoryPath, string noBranch
         return string.Empty;
     }
 
-    private static string GetModuleBranch(string path, string noBranchText)
+    private string GetModuleBranch(string path, string noBranchText)
     {
         // Note: This will fail for WSL symbolic links to .git directories
-        string branch = GitModule.GetSelectedBranchFast(path);
+        string branch = _getModule(path).GetSelectedBranch();
```
Comment (mstv) [inline src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs]: This creates (and GCs) a whole `GitModule` instance every time.
IMO we should factor out a more lightweight `GitExecutor` class. Its instances could and should be reused by means of a `GitExecutorProvider`, which could be registered in the `ServiceContainerRegistry`.

File: src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs [hunk 5]
```diff
@@ -40,9 +40,15 @@ internal sealed class SubmoduleStatusProvider : ISubmoduleStatusProvider
     private readonly CancellationTokenSequence _submodulesStructureSequence = new();
     private readonly CancellationTokenSequence _submodulesStatusSequence = new();
     private readonly Dictionary<string, SubmoduleInfo> _submoduleInfos = [];
+    private readonly Func<string, IGitModule> _getModule;
```
Comment (mstv) [inline src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs]: move to top for alphabetical order

File: src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs [hunk 6]
```diff
@@ -40,9 +40,15 @@ internal sealed class SubmoduleStatusProvider : ISubmoduleStatusProvider
...
     private DateTime _previousSubmoduleUpdateTime;
     private SubmoduleInfoResult? _submoduleInfoResult;
 
+    public SubmoduleStatusProvider(Func<string, IGitModule> getModule)
```
Comment (mstv) [inline src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs]: There is no need to inject the instance. This applies generally.
```suggestion
    public SubmoduleStatusProvider(Func<string, string> getSelectedBranch)
```

Comment (nikolaosginos) [reply src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs]: I did this because of @RussKie's comment here: https://github.com/gitextensions/gitextensions/pull/12498#discussion_r2311933528

But @gerhardol questioned the injection of getModule() here as well: https://github.com/gitextensions/gitextensions/pull/12659#issuecomment-3604207063

So what is the way to go? Might be irrevelant if we implement a separate `GitExecutor` as suggested above.

File: src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs (hunk 4 above)
Comment (nikolaosginos) [reply src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs]: You mean something like the [GitCommandRunner](https://github.com/gitextensions/gitextensions/blob/5ca6be8b81b1496ac13a2ff097314020468bf82a/src/app/GitCommands/Git/GitCommandRunner.cs)? `GitModule` has an instance of it. Should I create a `GitCommandRunnerProvider` or were you thinking of something else?

But since it is tied to a working directory via [IExecutable](https://github.com/gitextensions/gitextensions/blob/master/src/app/GitExtensions.Extensibility/IExecutable.cs), we would need to create an instance for every directory in order to show branch names in "recently used" lists. Which would at least not be as bad as a `GitModule` instance every time I guess?

Comment (mstv) [reply src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs]: I mean to extract everything needed for `GetSelectedBranch` from `IGitModule` to `IGitExecutor` (or the like) and `IGitModule` to inherit from / include `IGitExecutor`.
This includes functionality to determine the `gitExecutable`, (which would also be needed to instantiate a `GitCommandRunner`).

The creation of `[I]GitModule` is expensive. `[I]GitExecutor` would have a little less weight, but still too much for calling `path => new GitExecutor(path)` several times.

So, an `[I]GitModuleProvider`, which creates and caches instances might be the better approach. It could be registered in the `ServiceContainerRegistry`.
(In the meantime I realized that Registering module-dependent, i.e. repo-dependent, instance(s) in the `ServiceContainerRegistry` would not make much sense.)

File: src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs (hunk 6 above)
Comment (mstv) [reply src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs]: On the other hand, the `SubmoduleStatusProvider` does not need an `[I]GitModule` instance. I just needs a functor to call `GetSelectedBranch`. That this functor needs (some of) the functionality of `GitModule` should be transparent to `SubmoduleStatusProvider`. I.e. we should not introduce yet another dependency on `IGitModule`.

The `[I]GitModuleProvider` should be used by the creator of `SubmoduleStatusProvider`.

Comment (mstv) [reply src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs]: `SubmoduleStatusProvider` and `UserRepositoriesListController` do not need an `IGitModule` instance. They should use the - slightly generalized - `RepositoryCurrentBranchNameProvider` like `RepositoryHistoryUIService` does.

In https://github.com/gitextensions/gitextensions/pull/12659#issuecomment-3604207063, also @gerhardol is concerned about creating `GitModule` instances.
Most usages of `getModule` in GE look like `() => Module`, i.e. the *already created* `GitModule` instance is just made accessible. This is a different pattern, which does not apply here.
`RepositoryCurrentBranchNameProvider` should use a `GitModuleCache`.

File: src/app/GitUI/RepositoryCurrentBranchNameProvider.cs [hunk 7]
```diff
@@ -16,16 +17,18 @@ public interface IRepositoryCurrentBranchNameProvider
...
         if (!AppSettings.ShowRepoCurrentBranch)
         {
             return string.Empty;
         }
 
-        string branchName = GitModule.GetSelectedBranchFast(repositoryPath);
+        string branchName = _getModule(repositoryPath).GetSelectedBranch();
         if (string.IsNullOrWhiteSpace(branchName) || branchName == DetachedHeadParser.DetachedBranch)
         {
             branchName = $"({TranslatedStrings.NoBranch})";
```
Comment (mstv) [inline src/app/GitUI/RepositoryCurrentBranchNameProvider.cs]: Call `GetSelectedBranch` with the appropriate arguments instead of the preceding and trailing `if`, please.

**Comment by gerhardol** [comment]
@nikolaosginos release phase for 7.0 may start soon. Can you look at the comments?

**Comment by nikolaosginos** [comment]
Yes, sorry, I will take a look. I was unsure about the IGitExecutor extraction suggestions and additionally busy with other work. So this got lost a little on my side.

**Comment by nikolaosginos** [comment]
I have now extracted a lightweight GitExecutor from GitModule to use for getting the branch name. I have also added a GitExecutorProvider that caches the instances by repository path.

However, I just noticed that @mstv actually suggested to either extract a lightweigt GitExecutor or use a provider with caching for the GitModule instances. This was a little misunderstanding on my side. This solution now has a GitExecutor and a provider for the GitExecutor only, not for the GitModule. But I will leave it like that for now and wait for further feedback.

**Comment by nikolaosginos** [comment]
I have squashed and rebased now. Sorry I didn't look at the tests. I will check them next.

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 8]
```diff
@@ -0,0 +1,147 @@
...
+    protected readonly IExecutable _gitExecutable;
+    protected readonly IExecutable _gitWindowsExecutable;
+
+    protected bool _isReftableRepo;
+
+    /// <summary>
+    /// Name of the WSL distro for the GitExecutable, empty string for the app native Windows Git executable.
+    /// This can be seen as the Git "instance" identifier.
+    /// </summary>
+    protected readonly string WslDistro;
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutor.cs]: These should be `get; private init;` properties. There is no need for dedicated fields (since some C# revisions). And protected fields should be avoided anyway.

File: src/app/GitCommands/Git/GitExecutorProvider.cs [hunk 9]
```diff
@@ -0,0 +1,15 @@
...
+
+/// <summary>
+/// Creates and caches <see cref="GitExecutor"/> instances by repository path.
+/// </summary>
+public sealed class GitExecutorProvider : IGitExecutorProvider
+{
+    private readonly ConcurrentDictionary<string, IGitExecutor> _cache = new(StringComparer.OrdinalIgnoreCase);
+
+    public IGitExecutor GetExecutor(string repositoryPath)
+        => _cache.GetOrAdd(repositoryPath, static path => new GitExecutor(path));
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutorProvider.cs]: We might need a kind of forced update - in case a repo has been modified significantly.

File: src/app/GitCommands/Git/GitExecutorProvider.cs [hunk 10]
```diff
@@ -0,0 +1,15 @@
...
+using GitExtensions.Extensibility.Git;
+
+namespace GitCommands;
+
+/// <summary>
+/// Creates and caches <see cref="GitExecutor"/> instances by repository path.
+/// </summary>
+public sealed class GitExecutorProvider : IGitExecutorProvider
+{
+    private readonly ConcurrentDictionary<string, IGitExecutor> _cache = new(StringComparer.OrdinalIgnoreCase);
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutorProvider.cs]: At least in WSL, we have a case-significant file system.
If one uses different capitalization, it does not cost too much if the instance is not shared.

File: src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs [hunk 11]
```diff
@@ -58,7 +58,7 @@ public SelectedRepositoryItem(bool isFavourite, Repository repository)
     private Brush _hoverColorBrush = new SolidBrush(SystemColors.InactiveCaption);
     private ListViewItem? _hoveredItem;
     private readonly ListViewGroup _lvgRecentRepositories;
-    private readonly IUserRepositoriesListController _controller = new UserRepositoriesListController(RepositoryHistoryManager.Locals, new InvalidRepositoryRemover());
+    private readonly IUserRepositoriesListController _controller = new UserRepositoriesListController(RepositoryHistoryManager.Locals, new InvalidRepositoryRemover(), new GitExecutorProvider());
```
Comment (mstv) [inline src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs]: Rather get it from the service container.

File: src/app/GitCommands/Git/GitExecutor.cs (hunk 8 above)
Comment (RussKie) [reply src/app/GitCommands/Git/GitExecutor.cs]: I was about to write the same comment. All fields must be private.

Also, we should avoid statefulness - i.e., fields and properties that aren't initialised at the time of the object construction.

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 12]
```diff
@@ -0,0 +1,147 @@
...
+
+    protected IExecutable GitWindowsExecutable => _gitWindowsExecutable;
```
Comment (RussKie) [inline src/app/GitCommands/Git/GitExecutor.cs]: Please add xmldocs to all public and protected API

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 13]
```diff
@@ -0,0 +1,147 @@
...
+using GitExtUtils;
+
+namespace GitCommands;
+
+/// <summary>
+/// Provides a minimal git execution context for lightweight repository operations such as reading the current branch.
+/// </summary>
+public class GitExecutor : IGitExecutor
+{
+    private static readonly IGitDirectoryResolver GitDirectoryResolverInstance = new GitDirectoryResolver();
```
Comment (RussKie) [inline src/app/GitCommands/Git/GitExecutor.cs]: We should be able to retrieve this from the DI container.

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 14]
```diff
@@ -0,0 +1,147 @@
...
+    protected readonly string WslDistro;
+
+    protected IExecutable GitWindowsExecutable => _gitWindowsExecutable;
+    protected IGitCommandRunner GitWindowsCommandRunner { get; }
+
+    public static Encoding SystemEncoding => _systemEncoding ??= new SystemEncodingReader().Read();
+
+    public string WorkingDir { get; init; }
+    public IExecutable GitExecutable => _gitExecutable;
+    public IGitCommandRunner GitCommandRunner => _gitCommandRunner;
```
Comment (RussKie) [inline src/app/GitCommands/Git/GitExecutor.cs]: Please move all the properties after .ctor.

We follow this file organisation: https://learn.microsoft.com/archive/blogs/brada/internal-coding-guidelines#28-file-organization

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 15]
```diff
@@ -0,0 +1,147 @@
...
+using GitExtensions.Extensibility;
+using GitExtensions.Extensibility.Git;
+using GitExtUtils;
+
+namespace GitCommands;
+
+/// <summary>
+/// Provides a minimal git execution context for lightweight repository operations such as reading the current branch.
+/// </summary>
+public class GitExecutor : IGitExecutor
```
Comment (RussKie) [inline src/app/GitCommands/Git/GitExecutor.cs]: Should this type be public? IIUIC, an instance is obtained via `GitExecutorProvider`, so only the interface needs to be public.

File: src/app/GitCommands/Git/GitExecutorProvider.cs [hunk 16]
```diff
@@ -0,0 +1,15 @@
+using System.Collections.Concurrent;
+using GitExtensions.Extensibility.Git;
+
+namespace GitCommands;
+
+/// <summary>
+/// Creates and caches <see cref="GitExecutor"/> instances by repository path.
+/// </summary>
+public sealed class GitExecutorProvider : IGitExecutorProvider
```
Comment (RussKie) [inline src/app/GitCommands/Git/GitExecutorProvider.cs]: Same here - i don't believe this type should be public, only the interface. The type should be registered in the DI container.

File: src/app/GitCommands/Git/GitModule.cs [hunk 17]
```diff
@@ -26,12 +26,11 @@ namespace GitCommands;
 /// <summary>Provides manipulation with git module.
 /// <remarks>Several instances may be created for submodules.</remarks></summary>
 [DebuggerDisplay("GitModule ( {" + nameof(WorkingDir) + "} )")]
-public sealed partial class GitModule : IGitModule
+public sealed partial class GitModule : GitExecutor, IGitModule
```
Comment (RussKie) [inline src/app/GitCommands/Git/GitModule.cs]: Is it possible to avoid inheritance and use composition instead?

**Comment by mstv** [comment]
Errors from unreachable drives need to be ignored. The following exception pops up on opening the repo dropdown:

```
GitExtensions.Extensibility.ExternalOperationException: An error occurred trying to start process 'C:\Program Files\Git\bin\git.exe' with working directory 'w:\home\...\...\'. Der Verzeichnisname ist ungültig.
 ---> System.ComponentModel.Win32Exception (267): An error occurred trying to start process 'C:\Program Files\Git\bin\git.exe' with working directory 'w:\home\...\...\'. Der Verzeichnisname ist ungültig.
   at bool System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at new GitCommands.Executable+ProcessWrapper(string fileName, string prefixArguments, string arguments, string workDir, bool createWindow, bool redirectInput, bool redirectOutput, Encoding outputEncoding, bool useShellExecute, bool throwOnErrorExit, CancellationToken cancellationToken) in C:/build/ge/src/app/GitCommands/Git/Executable.cs:line 134
   --- End of inner exception stack trace ---
   at new GitCommands.Executable+ProcessWrapper(string fileName, string prefixArguments, string arguments, string workDir, bool createWindow, bool redirectInput, bool redirectOutput, Encoding outputEncoding, bool useShellExecute, bool throwOnErrorExit, CancellationToken cancellationToken) in C:/build/ge/src/app/GitCommands/Git/Executable.cs:line 156
   at IProcess GitCommands.Executable.Start(ArgumentString arguments, bool createWindow, bool redirectInput, bool redirectOutput, Encoding outputEncoding, bool useShellExecute, bool throwOnErrorExit, CancellationToken cancellationToken) in C:/build/ge/src/app/GitCommands/Git/Executable.cs:line 46
   at async Task<ExecutionResult> GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action<StreamWriter> writeInput, Encoding outputEncoding, CommandCache cache, string extraCacheKey, bool stripAnsiEscapeCodes, bool throwOnErrorExit, CancellationToken cancellationToken) in C:/build/ge/src/app/GitCommands/Git/ExecutableExtensions.cs:line 306
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<T>(Func<Task<T>> asyncMethod, JoinableTaskCreationOptions creationOptions) x 2
   at ExecutionResult GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action<StreamWriter> writeInput, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes, bool throwOnErrorExit, CancellationToken cancellationToken) in C:/build/ge/src/app/GitCommands/Git/ExecutableExtensions.cs:line 265
   at string GitCommands.GitExecutor.GetSelectedBranch(bool emptyIfDetached) in C:/build/ge/src/app/GitCommands/Git/GitExecutor.cs:line 81
   at string GitUI.RepositoryCurrentBranchNameProvider.GetCurrentBranchName(string repositoryPath) in C:/build/ge/src/app/GitUI/RepositoryCurrentBranchNameProvider.cs:line 30
   at async void GitUI.RepositoryHistoryUIService.AddRecentRepositories(ToolStripDropDownItem menuItemContainer, Repository repo, string caption, int number, bool anchored)+(?) => { } [1] in C:/build/ge/src/app/GitUI/RepositoryHistoryUIService.cs:line 72
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/build/ge/src/app/GitExtUtils/GitUI/TaskManager.cs:line 32
```

**Comment by nikolaosginos** [comment]
I tried to address all comments. I was unsure about the DI suggestions. In `UserRepositoriesList`, I was able to get the required service via `ServiceProvider`. In `GitExecutor` though, I don't know what the preferred way to get the object injected is. I added a parameter to the constructor that is called from `GitModule`. But `GitModule`'s constructor itself has roundabout 50 references? I would have to add a parameter to that constructor as well and update all references. Am I right? Please let me know how to proceed. I wanted to get your feedback before continuing.

File: tests/app/UnitTests/GitCommands.Tests/GitModuleTests.cs [hunk 18]
```diff
@@ -651,13 +651,15 @@ private static GitModule GetGitModuleWithExecutable(IExecutable executable, stri
...
+            .GetValue(module);
+        typeof(GitExecutor).GetProperty("GitExecutable", BindingFlags.Instance | BindingFlags.Public)
+            .SetValue(executor, executable);
+        typeof(GitExecutor).GetProperty("GitWindowsExecutable", BindingFlags.Instance | BindingFlags.Public)
+            .SetValue(executor, executable);
         GitCommandRunner cmdRunner = new(executable, () => GitModule.SystemEncoding);
-        typeof(GitModule).GetField("_gitCommandRunner", BindingFlags.Instance | BindingFlags.NonPublic)
-            .SetValue(module, cmdRunner);
+        typeof(GitExecutor).GetProperty("GitCommandRunner", BindingFlags.Instance | BindingFlags.Public)
+            .SetValue(executor, cmdRunner);
```
Comment (mstv) [inline tests/app/UnitTests/GitCommands.Tests/GitModuleTests.cs]: I think it is time to apply the `TestAccessor` pattern here, too.

File: src/app/GitCommands/Git/GitModule.cs [hunk 19]
```diff
@@ -422,25 +401,14 @@ public string GitCommonDirectory
...
     public bool IsBareRepository()
     {
-        return WorkingDir == GetGitDirectory();
+        return WorkingDir == _executor.GetGitDirectory();
     }
 
     public static bool IsBareRepository(string repositoryPath)
     {
-        return repositoryPath == GetGitDirectory(repositoryPath);
+        return repositoryPath == new GitDirectoryResolver().Resolve(repositoryPath);
```
Comment (mstv) [inline src/app/GitCommands/Git/GitModule.cs:421]: Rather use the instance inside `_executor`.

File: src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs [hunk 20]
```diff
@@ -58,12 +59,18 @@ public SelectedRepositoryItem(bool isFavourite, Repository repository)
...
     private bool _hasInvalidRepos;
     private ListViewItem? _rightClickedItem;
 
     public event EventHandler<GitModuleEventArgs>? GitModuleChanged;
 
+    private IUserRepositoriesListController Controller
+        => _controller ??= new UserRepositoriesListController(
+            RepositoryHistoryManager.Locals,
+            new InvalidRepositoryRemover(),
+            ServiceProvider.GetRequiredService<IGitExecutorProvider>());
```
Comment (mstv) [inline src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs:71]: Use `Lazy<>`?

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 21]
```diff
@@ -0,0 +1,184 @@
...
+        }
+    }
+
+    public GitExecutor(string? workingDir)
+        : this(new GitDirectoryResolver(), workingDir)
+    {
+    }
+
+    /// <inheritdoc/>
+    public IGitCommandRunner GitCommandRunner { get; private set; }
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutor.cs:48]: ❔
```suggestion
    public IGitCommandRunner GitCommandRunner { get; private init; }
```
several times

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 22]
```diff
@@ -0,0 +1,184 @@
...
+            if (result.ExitedSuccessfully)
+            {
+                return result.StandardOutput[GitRefName.RefsHeadsPrefix.Length..].TrimEnd();
+            }
+
+            return emptyIfDetached ? string.Empty : DetachedHeadParser.DetachedBranch;
+        }
+        catch (Exception)
+        {
+            return string.Empty;
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutor.cs]:
```suggestion
        catch (Exception ex)
        {
            Trace.WriteLine(ex);
            return "???";
```

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 23]
```diff
@@ -0,0 +1,184 @@
...
+        {
+            GitExecutable = GitWindowsExecutable;
+            GitCommandRunner = GitWindowsCommandRunner;
+        }
+    }
+
+    public GitExecutor(string? workingDir)
+        : this(new GitDirectoryResolver(), workingDir)
+    {
+    }
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutor.cs]:
```suggestion
```
because just used by GitModule

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 24]
```diff
@@ -0,0 +1,184 @@
...
+using GitCommands.Git;
+using GitExtensions.Extensibility;
+using GitExtensions.Extensibility.Git;
+using GitExtUtils;
+
+namespace GitCommands;
+
+/// <summary>
+/// Provides a minimal git execution context for lightweight repository operations such as reading the current branch.
+/// </summary>
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutor.cs:13]: indent with 2 chars (refer to `.github/copilot-instructions.md`)

```suggestion
/// <summary>
///  Provides a minimal git execution context for lightweight repository operations such as reading the current branch.
/// </summary>
```

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 25]
```diff
@@ -0,0 +1,184 @@
...
+    /// This can be seen as the Git "instance" identifier.
+    /// </summary>
+    internal string WslDistro { get; }
+
+    /// <summary>
+    /// Gets a value indicating whether this repository is using the reftable format.
+    /// </summary>
+    internal bool IsReftableRepo { get; set; }
+
+    /// <inheritdoc/>
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutor.cs]:
```suggestion
```
this is implicitly done which why we omit it

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 26]
```diff
@@ -0,0 +1,184 @@
...
+
+            return emptyIfDetached ? string.Empty : DetachedHeadParser.DetachedBranch;
+        }
+        catch (Exception)
+        {
+            return string.Empty;
+        }
+    }
+
+    /// <summary>Attempt to read the branch name from the HEAD file instead of calling a git command.</summary>
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutor.cs]:
```suggestion
    /// <summary>
    ///   Attempt to read the branch name from the HEAD file instead of calling a git command.
    /// </summary>
```

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 27]
```diff
@@ -0,0 +1,184 @@
...
+
+        if (!headFileContents.StartsWith(prefix))
+        {
+            return string.Empty;
+        }
+
+        return headFileContents[prefix.Length..].TrimEnd();
+    }
+
+    /// <summary>Gets the ".git" directory path.</summary>
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutor.cs]: ditto

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 28]
```diff
@@ -0,0 +1,184 @@
...
+    internal string GetGitDirectory()
+    {
+        return GetGitDirectory(WorkingDir);
+    }
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutor.cs]: no `internal` members (except `TestAccessor`), just the class
```suggestion
    public string GetGitDirectory() => GetGitDirectory(WorkingDir);
```

File: src/app/GitCommands/Git/GitExecutorProvider.cs [hunk 29]
```diff
@@ -0,0 +1,28 @@
...
+
+    public GitExecutorProvider(IGitDirectoryResolver gitDirectoryResolver)
+    {
+        _gitDirectoryResolver = gitDirectoryResolver;
+    }
+
+    public IGitExecutor GetExecutor(string repositoryPath)
+        => _cache.GetOrAdd(repositoryPath, path => new GitExecutor(_gitDirectoryResolver, path));
+
+    public IGitExecutor GetNewExecutor(string repositoryPath)
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutorProvider.cs:23]: To be used by some invokers of the `GitModule` ctor: when switching to another repo.

File: src/app/GitCommands/Git/GitExecutorProvider.cs [hunk 30]
```diff
@@ -0,0 +1,28 @@
...
+    {
+        _cache.TryRemove(repositoryPath, out _);
+        return _cache.GetOrAdd(repositoryPath, path => new GitExecutor(_gitDirectoryResolver, path));
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutorProvider.cs]:
```suggestion
        return GetExecutor(repositoryPath);
```

File: src/app/GitCommands/Git/GitModule.cs [hunk 31]
```diff
@@ -81,30 +75,12 @@ public sealed partial class GitModule : IGitModule
     /// Name of the WSL distro for the GitExecutable, empty string for the app native Windows Git executable.
     /// This can be seen as the Git "instance" identifier.
     /// </summary>
-    private readonly string _wslDistro;
-
     public GitModule(string? workingDir)
     {
-        WorkingDir = (workingDir ?? "").NormalizePath().NormalizeWslPath().EnsureTrailingPathSeparator();
-        WorkingDirGitDir = GitDirectoryResolverInstance.Resolve(WorkingDir);
+        _executor = new GitExecutor(workingDir);
```
Comment (mstv) [inline src/app/GitCommands/Git/GitModule.cs]: The `IGitExecutor` needs to be passed to this ctor - as you pointed out yourself.

File: src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs [hunk 32]
```diff
@@ -37,12 +37,18 @@ internal sealed class SubmoduleStatusProvider : ISubmoduleStatusProvider
     // Throttle updates triggered from status updates
     private const int MinRefreshInterval = 15;
 
+    private readonly IGitExecutorProvider _executorProvider;
```
Comment (mstv) [inline src/app/GitCommands/Submodules/SubmoduleStatusProvider.cs]:
```suggestion
internal sealed class SubmoduleStatusProvider(IGitExecutorProvider executorProvider) : ISubmoduleStatusProvider
{
// Throttle updates triggered from status updates
private const int MinRefreshInterval = 15;

    private readonly IGitExecutorProvider _executorProvider = executorProvider;
```

File: src/app/GitExtensions.Extensibility/Git/IGitExecutor.cs [hunk 33]
```diff
@@ -0,0 +1,35 @@
+﻿using System.Text;
+
```
Comment (mstv) [inline src/app/GitExtensions.Extensibility/Git/IGitExecutor.cs]: not needed

```suggestion
```

File: src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs [hunk 34]
```diff
@@ -59,20 +59,21 @@ public SelectedRepositoryItem(bool isFavourite, Repository repository)
...
-            new InvalidRepositoryRemover(),
-            ServiceProvider.GetRequiredService<IGitExecutorProvider>());
+    private IUserRepositoriesListController Controller => _controller.Value;
 
     public UserRepositoriesList()
     {
+        _controller = new Lazy<IUserRepositoriesListController>(() => new UserRepositoriesListController(
+            RepositoryHistoryManager.Locals,
+            new InvalidRepositoryRemover(),
+            ServiceProvider.GetRequiredService<IGitExecutorProvider>()));
```
Comment (mstv) [inline src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs]: init should work in place at definition

Comment (nikolaosginos) [reply src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs]: I'm not sure I understand. Are you asking to move this to the definition? It would not work since I cannot access the instance member `ServiceProvider` in an initializer.

**Comment by nikolaosginos** [comment]
> > I don't know what the preferred way to get the object injected is. I added a parameter to the constructor that is called from GitModule.
> 
> 👍
> 
> > But GitModule's constructor itself has roundabout 50 references? I would have to add a parameter to that constructor as well and update all references. Am I right?
> 
> 👍 Yes, it is necessary I think.

Most usages don't have access to a service provider so I would be doing new `GitModule(new GitExecutor())` in most places. Is this what you are asking for?

File: src/app/GitCommands/Git/GitExecutorProvider.cs (hunk 30 above)
Comment (nikolaosginos) [reply src/app/GitCommands/Git/GitExecutorProvider.cs]: You probably mean `new GitExecutor(_gitDirectoryResolver, repositoryPath)`? So no caching when we force getting a new instance?

File: src/app/GitCommands/Git/GitExecutor.cs (hunk 21 above)
Comment (nikolaosginos) [reply src/app/GitCommands/Git/GitExecutor.cs:48]: This was intentional for the Unit Tests. I thought reflection on the setter would not work with init but it did. But since I now refactored to use a TestAccessor instead of reflection, I need this to be set instead of init

File: src/app/GitCommands/Git/GitModule.cs (hunk 19 above)
Comment (nikolaosginos) [reply src/app/GitCommands/Git/GitModule.cs:421]: I cannot use `_executor` since this method is static. I would have to make this non-static and update the references to create a whole GitModule instead.

File: src/app/GitCommands/Git/GitExecutorProvider.cs (hunk 30 above)
Comment (mstv) [reply src/app/GitCommands/Git/GitExecutorProvider.cs]: No, `GetNewExecutor` shall not duplicate but _use_ the identical code in `GetExecutor` (after it has removed the old entry).

File: src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs (hunk 34 above)
Comment (mstv) [reply src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs]: You are right, unfortunately.

File: src/app/GitCommands/Git/GitExecutorProvider.cs (hunk 30 above)
Comment (nikolaosginos) [reply src/app/GitCommands/Git/GitExecutorProvider.cs]: Oh, I misread `GetExecutor` as `GitExecutor` and was wondering what you meant... Make sense now, sorry.

File: src/app/GitCommands/Git/GitExecutor.cs (hunk 21 above)
Comment (mstv) [reply src/app/GitCommands/Git/GitExecutor.cs:48]: OK, add a comment "set used just by TestAccessor", please.

File: src/app/GitCommands/Git/GitExecutor.cs [hunk 35]
```diff
@@ -0,0 +1,220 @@
...
+    internal TestAccessor GetTestAccessor() => new(this);
+
+    internal readonly struct TestAccessor
+    {
+        private readonly GitExecutor _executor;
+
+        public TestAccessor(GitExecutor executor)
+        {
+            _executor = executor;
+        }
```
Comment (mstv) [inline src/app/GitCommands/Git/GitExecutor.cs]: could use the new shorter syntax, too:

```suggestion
    internal readonly struct TestAccessor(GitExecutor executor)
    {
        private readonly GitExecutor _executor  = executor;
```

**Comment by gerhardol** [comment]
When using this PR I get a popup:
image

I believe I have cleaned before building (the behavior has changed for this call).
Occurs in several situations like opening Dashboard and settings (likely a plugin using that, the only external plugin I have is PluginManager).
Edit: Deleting PluginManager fixed the issue

Other than that it works fine, no noticable delay opening the Dashboard.
The Dropdown in Browse is still unusable, takes 10s the first time before failing, then 4s to open. I personally use a patch where branch names are removed, then it is down to 3s all the time (almost unusable too).

No comments on the code, when mstv approves, I will approve.

**Comment by mstv** [comment]
The extension of the `GitModule` ctor is still pending: `IGitExecutor` needs to be injected.

File: src/app/GitCommands/Git/GitModule.cs [hunk 36]
```diff
@@ -81,30 +76,13 @@ public sealed partial class GitModule : IGitModule
...
     /// This can be seen as the Git "instance" identifier.
     /// </summary>
-    private readonly string _wslDistro;
-
-    public GitModule(string? workingDir)
+    public GitModule(IGitExecutorProvider executorProvider, string? workingDir)
     {
-        WorkingDir = (workingDir ?? "").NormalizePath().NormalizeWslPath().EnsureTrailingPathSeparator();
-        WorkingDirGitDir = GitDirectoryResolverInstance.Resolve(WorkingDir);
+        _executorProvider = executorProvider;
```
Comment (mstv) [inline src/app/GitCommands/Git/GitModule.cs:81]: I guess there is no need to store it. Have not reviewed in detail yet.

File: src/app/GitCommands/Git/GitModule.cs [hunk 37]
```diff
@@ -81,30 +76,13 @@ public sealed partial class GitModule : IGitModule
...
+        _executor = (GitExecutor)executorProvider.GetExecutor(workingDir ?? "");
```
Comment (mstv) [inline src/app/GitCommands/Git/GitModule.cs]: This cast can be avoided by adding the public properties and methods to `IGitExecutor`.

File: src/app/GitCommands/Git/GitModule.cs (hunk 36 above)
Comment (mstv) [reply src/app/GitCommands/Git/GitModule.cs:81]: needed for `superprojectModule` and `GetSubmodule`

File: src/app/GitCommands/Git/SystemEncodingReader.cs [hunk 38]
```diff
@@ -17,16 +17,16 @@ public interface ISystemEncodingReader
...
 {
-    private readonly IGitModule _module;
+    private readonly IExecutable _gitExecutable;
 
-    public SystemEncodingReader(IGitModule? module)
+    public SystemEncodingReader(IGitModule module)
     {
-        _module = module ?? new GitModule("");
+        _gitExecutable = module.GitExecutable;
     }
```
Comment (mstv) [inline src/app/GitCommands/Git/SystemEncodingReader.cs]: Can be removed because not referenced any longer.

**Comment by nikolaosginos** [comment]
Sorry for pushing so frequently. I am done for today in case you want to add more comments.

File: src/app/GitUI/NBugReports/BugReportInvoker.cs [hunk 39]
```diff
@@ -428,7 +428,7 @@ void AddTrustRepoButton(string buttonText, string command, string workingDir)
 
             button.Click += (_, _) =>
             {
-                new GitModule(workingDir).GitExecutable.Start(command).WaitForExit();
+                new Executable(() => AppSettings.GitCommand, workingDir).Start(command).WaitForExit();
```
Comment (mstv) [inline src/app/GitUI/NBugReports/BugReportInvoker.cs]: This breaks it for WSL. Here we can afford to create a new `GitExecutor`.

File: tests/app/IntegrationTests/UI.IntegrationTests/UserControls/GitBlameParserTest.cs [hunk 40]
```diff
@@ -44,7 +44,7 @@ public void GetOriginalLineInPreviousCommit()
 
         string gitExtensionsRepoPath = Path.GetFullPath(@"..\..\..\..\..\..\..");
 
-        GitModule gitModule = new(gitExtensionsRepoPath);
+        GitModule gitModule = new(new GitCommands.GitExecutorProvider(new GitCommands.Git.GitDirectoryResolver()), gitExtensionsRepoPath);
```
Comment (mstv) [inline tests/app/IntegrationTests/UI.IntegrationTests/UserControls/GitBlameParserTest.cs]: We prefer `using` statements.
```suggest
        GitModule gitModule = new(new GitExecutorProvider(new GitDirectoryResolver()), gitExtensionsRepoPath);
```

**Comment by nikolaosginos** [comment]
No, I am not done. I broke it with the merge. It does not compile.

**Review by mstv — COMMENTED** [review]
> Sorry for pushing so frequently.

This progress is very welcome. The commits are well separated, which eases the review.

I think these are the final comments including my remaining changes from https://github.com/mstv/gitextensions/commit/91ad6561a8e410069ecd431f293f55a6605badca.

File: src/app/GitUI/NBugReports/UIReporter.cs [hunk 41]
```diff
@@ -112,7 +112,7 @@ void AddTrustRepoButton(string buttonText, string command, string workingDir)
 
             button.Click += (_, _) =>
             {
-                new GitModule(workingDir).GitExecutable.Start(command).WaitForExit();
+                new Executable(() => AppSettings.GitCommand, workingDir).Start(command).WaitForExit();
```
Comment (mstv) [inline src/app/GitUI/NBugReports/UIReporter.cs]: same issue with WSL as in BugReportInvoker.cs

---

I wonder why we have two trust repo buttons. It might be a left over from the recent refactoring, @RussKie.

**Comment by nikolaosginos** [comment]
> > Sorry for pushing so frequently.
> 
> This progress is very welcome. The commits are well separated, which eases the review.
> 
> I think these are the final comments including my remaining changes from [mstv@91ad656](https://github.com/mstv/gitextensions/commit/91ad6561a8e410069ecd431f293f55a6605badca).

I think I have now handled all comments and I have applied the changes from https://github.com/mstv/gitextensions/commit/91ad6561a8e410069ecd431f293f55a6605badca as well. Thank you for your extensive feedback and comments. I hope this pull request is fine now.

**Comment by mstv** [comment]
https://github.com/mstv/gitextensions/commit/7136cbf7bcc28517c06b65ef7000d300ab06c2dc
I am running this tomorrow.

File: src/app/GitUI/NBugReports/UIReporter.cs (hunk 41 above)
Comment (RussKie) [reply src/app/GitUI/NBugReports/UIReporter.cs]: Could you please elaborate?

Comment (nikolaosginos) [reply src/app/GitUI/NBugReports/UIReporter.cs]: > Could you please elaborate?

I think @mstv just reviewed my code before and after I merged main into my branch and therefore saw the same trust repo button code in `BugReporterInvoker` before my merge (and therefore your refactoring https://github.com/gitextensions/gitextensions/commit/4a7dae36c3a0de9a79364e3987f19c49c751a43b) and in `UIReporter` after my merge. So no real issue here.

Comment (mstv) [reply src/app/GitUI/NBugReports/UIReporter.cs]: > > Could you please elaborate?
> 
> I think @mstv just reviewed my code before and after I merged main into my branch and therefore saw the same trust repo button code in `BugReporterInvoker` before my merge (and therefore your refactoring [4a7dae3](https://github.com/gitextensions/gitextensions/commit/4a7dae36c3a0de9a79364e3987f19c49c751a43b)) and in `UIReporter` after my merge. So no real issue here.

👍 indeed

**Comment by mstv** [comment]
> [mstv@7136cbf](https://github.com/mstv/gitextensions/commit/7136cbf7bcc28517c06b65ef7000d300ab06c2dc)

Apply this cleanup commit yet, please

> I am running this tomorrow.

Worked well.

**Comment by nikolaosginos** [comment]
> > [mstv@7136cbf](https://github.com/mstv/gitextensions/commit/7136cbf7bcc28517c06b65ef7000d300ab06c2dc)
> 
> Apply this cleanup commit yet, please

Sorry, I missed this in your previous comment. Done now.
