### PR TITLE
fix(Jump List Buttons): Deactivate on modal dialog

### LINKED ISSUE #3128: Multiple push dialogs are opened if push called from taskBar
On mouse hover GitExtention intask bar preview appears with commit,pull and push buttons. If you press push button multiple times, multiple push dialogs are opened.

Please see attached screenshot
Environment:
Windows 7 SP1
.Net 4.5
push-bug

### PR DESCRIPTION
**Pull request by mstv**
Fixes #3128

## Proposed changes

- Disable Windows Jump List buttons if GE shows a modal dialog or has no valid wdir
- Bring GE to front on click of Windows Jump List button

## Test methodology 

- manual

## Test environment(s) 

- Windows 10

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -561,10 +561,20 @@ protected override void OnActivated(EventArgs e)
...
 
+            _windowsJumpListManager.EnableThumbnailToolbar(_dashboard?.Visible is not true && Module.IsValidGitWorkingDir());
+
             this.InvokeAndForget(OnActivate);
             base.OnActivated(e);
         }
 
+        protected override void OnDeactivate(EventArgs e)
+        {
+            bool applicationNotActivated = ActiveForm is null;
```
Comment (gerhardol) [inline src/app/GitUI/CommandsDialogs/FormBrowse.cs:572]: I would prefer to use applicationActivated (even if always negated)

File: src/app/GitUI/CommandsDialogs/FormBrowse.cs [hunk 2]
```diff
@@ -561,10 +561,20 @@ protected override void OnActivated(EventArgs e)
                         new WindowsThumbnailToolbarButton(_closeAll.Text, Images.DeleteFile, (s, e) => NativeMethods.PostMessageW(NativeMethods.HWND_BROADCAST, _closeAllMessage))));
             }
 
+            _windowsJumpListManager.EnableThumbnailToolbar(_dashboard?.Visible is not true && Module.IsValidGitWorkingDir());
```
Comment (gerhardol) [inline src/app/GitUI/CommandsDialogs/FormBrowse.cs:564]: Add a comment here or to the commit description, this is another fix (that I could not relate to the other)

**Review by gerhardol — APPROVED** [review]

File: src/app/GitUI/WindowsJumpListManager.cs [hunk 3]
```diff
@@ -205,7 +205,7 @@ void CreateTaskbarButtons(IntPtr handle, WindowsThumbnailToolbarButtons thumbBut
         /// <summary>
         /// Disables display of thumbnail toolbars.
```
[the remark this answers is not in the document]
Comment (mstv) [reply src/app/GitUI/WindowsJumpListManager.cs]: updated doc

File: src/app/GitUI/CommandsDialogs/FormBrowse.cs (hunk 1 above)
Comment (mstv) [reply src/app/GitUI/CommandsDialogs/FormBrowse.cs]: also renamed

File: src/app/GitUI/CommandsDialogs/FormBrowse.cs (hunk 2 above)
Comment (mstv) [reply src/app/GitUI/CommandsDialogs/FormBrowse.cs:564]: Return from modal dialog does not work without this.
But yes, it fixes the bug that the buttons must be disabled for the Dashboard (refer to PR description and to updated commit message).
