### PR TITLE
Fix leaking brushes

### LINKED ISSUE #9429: [NBug] An unexpected internal error occurred in the Win32 call: 80...
## Current behaviour

Program crashed sometime during the night.

## Expected behaviour

Shouldn't crash.

## Steps to reproduce

Leave the program running overnight.

## Error Details
```
System.ComponentModel.Win32Exception: An unexpected internal error occurred in the Win32 call: 8007007E ---> System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   --- End of inner exception stack trace ---
   at Microsoft.WindowsAPICodePack.Dialogs.NativeTaskDialog.NativeShow()
   at Microsoft.WindowsAPICodePack.Dialogs.TaskDialog.ShowCore()
   at GitUI.NBugReports.BugReportInvoker.Report(Exception exception, Boolean isTerminating)
   at GitExtensions.Program.<>c.<Main>b__1_3(Object s, ThreadExceptionEventArgs e)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

## Additional information
Left the program running overnight.

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.31.1.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by NikolayXHD**
Fixes #9429

## Proposed changes

1. Return brush wrapper in situations when brush consumer is not certain whether it should dispose the brush.
  wrapper.Dispose method will not touch the underlying brush if it is system brush.
2. Cache the native brushes returned by Win32 GetSysColorBrush override
3. Render text input backround explicitly, because 2. somehow breaks default system rendering.

## Test methodology

- run GitExtensions
- scroll revision grid back and forth, click on different revisions
- observe GDI objects count using [GDIView](https://www.nirsoft.net/utils/gdi_handles.html) (thank you @pmiossec)

## Test environment(s)

Windows 10

## Merge strategy

- Rebase merge

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitExtUtils/GitUI/Theming/BrushContainer.cs [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+using System.Drawing;
+
+namespace GitExtUtils.GitUI.Theming
+{
+    public class BrushContainer : IDisposable
+    {
+        private readonly bool _isSystemBrush;
+
+        public static BrushContainer ForSystemBrush(Brush brush) =>
+            new BrushContainer(brush, isSystemBrush: true);
```
Comment (gerhardol) [inline GitExtUtils/GitUI/Theming/BrushContainer.cs:11]: nit pick, IDE0090 (general)
A general conversion is done in master, suggest this is done here to give cleaner merge
Style preferences should be documented...
```suggestion
            new(brush, isSystemBrush: true);
```

**Review by gerhardol — COMMENTED** [review]
+1
Seem fine to me, I have only briefly run this.

**Comment by pmiossec** [comment]
>Return brush wrapper in situations when brush consumer is not certain whether it should dispose the brush.
wrapper.Dispose method will not touch the underlying brush if it is system brush.

Clever idea. I have checked with the portable version and from what I see with GdiView, it is working great and fix the issue.

Code seems good. I will give it another look later.

I was just wondering. On the project, do we prefer:

```
using(var foo = new Brush())
{}
```

or 

```
using var foo = new Brush();
```

**Comment by gerhardol** [comment]
> I was just wondering. On the project, do we prefer:
> 
> ```
> using(var foo = new Brush())
> {}
> ```
> 
> or
> 
> ```
> using var foo = new Brush();
> ```

The latter generally, but the case I checked here the first was still required (null check).

**Comment by RussKie** [comment]
I've started to review, but got caught up with work. Will complete this week.

File: GitUI/Theming/SystemBrushOverrides.cs [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+{
+    internal class SystemBrushOverrides
+    {
+        private readonly Dictionary<int, HandleRef> _cache = new();
+
+        public IntPtr GetBrush(int colorref)
+        {
+            if (!_cache.TryGetValue(colorref, out var handle))
+            {
+                var hbrush = NativeMethods.CreateSolidBrush(colorref);
```
Comment (RussKie) [inline GitUI/Theming/SystemBrushOverrides.cs:15]: ❗ `HBRUSH` must be disposed of when we no longer need it (e.g. when we uninstall the hook), otherwise we'll leak native handles.
https://docs.microsoft.com/windows/win32/api/wingdi/nf-wingdi-createsolidbrush#remarks

This is how we've wrapped (some) native handled in dotnet/winforms, may be you find it useful:
* https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.HBRUSH.cs
* https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.CreateBrushScope.cs

**Review by RussKie — CHANGES_REQUESTED** [review]
👍 with some comments

**Comment by RussKie** [comment]
@NikolayXHD I've made few tweaks, please have a look.

**Comment by NikolayXHD** [comment]
> @NikolayXHD I've made few tweaks, please have a look.

ok, meged the changes changes to respective commits.

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you!

**Comment by gerhardol** [comment]
Thanks!
Will this be merged to master too, even if themes are not possible yet with .NET5?
How should we remember this otherwise?

**Comment by NikolayXHD** [comment]
> Will this be merged to master too, even if themes are not possible yet with .NET5?

Sure thing :)
