### PR TITLE
fix: Theme loading error suppressions

### LINKED ISSUE #12590: v6.0.2 Launch Error
### Environment

- GitExtensions version:  6.0.2  (GitExtensions-x64-6.0.2.18262-f02a06bf5.msi)
- GIT version: git version 2.51.1.windows.1
- OS version: Windows 10 (updated)
- .NET version: ?

### Issue description

I installed v6.0.2 with the above .MSI file (GitExtensions-x64-6.0.2.18262-f02a06bf5.msi) over the top of the last v5 version.  When I attempted to launch it from the installed desktop icon, I got this error message.

Image

Then I uninstalled it completely, and attempted installation again with the same .MSI file and got the same error.

Am I missing some other software that this is relying upon?

Kind regards,
Vic

### Steps to reproduce

Simply install `GitExtensions-x64-6.0.2.18262-f02a06bf5.msi` on Windows 10 and attempt to run it.

### Did this work in previous version of GitExtensions?

Yes.  I uninstalled GitExtensions again and re-installed `GitExtensions-x64-5.2.1.18061-0d74cfdc3.msi` and it is now working fine again.

### Diagnostics

Image

### Existing Directories

This is the directory structure under `C:\Users\Vic\AppData\Roaming\`:

The creation date of the `Themes` folder here `C:\Users\Vic\AppData\Roaming\GitExtensions\GitExtensions\Themes` is 2025-07-30, roughly the same time I updated to v5.2.1.

Image

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #12590

Many user themes were migrated in GE 3 -> 4 and users do not remember or read the popup details

## Proposed changes

* Try loading a color from the invariant theme if not found in the current theme.
The explicit '@import url("invariant.css");' in user themes is then not required.

* Ignore the occurrence of color "Graph" in themes. The color was removed in 5.2.1 -> 6.0 and the themes are not explicitly migrated removing the user color.

* Limit the printout when a color cannot be parsed. The full traceback intimidates the user, the color should be printed on the first line.
The full traceback is still written to the trace.

## Screenshots 

css file is the following, which previously experienced all three problems
```
.Graph { color: #000000; }
.xxx { color: #000000; }
```

### Before

image

### After

image

## Test methodology 

Manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettings/ColorsSettingsPage.cs [hunk 1]
```diff
@@ -91,9 +92,12 @@ public bool IsChoosingVisualStyleEnabled
 
         public void ShowThemeLoadingErrorMessage(ThemeId themeId, string[] variations, Exception ex)
         {
+            Trace.WriteLine($"Failed to load theme {themeId.Name}: {ex}");
             string variationsStr = string.Concat(variations.Select(_ => "." + _));
             string identifier = new FormattedThemeId(themeId).ToString();
-            MessageBoxes.ShowError(this, $"Failed to load theme {identifier}{variationsStr}: {ex}");
+            string firstLine = ex.ToString().Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries)[0];
+            AppSettings.ThemeId = ThemeId.Default;
+            MessageBoxes.ShowError(this, $"Failed to load theme {identifier}{variationsStr}: {firstLine}");
```
Comment (RussKie) [inline src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettings/ColorsSettingsPage.cs]: Consider adding a link to our wiki or an issue that provides more details on how to fix the issue.

Comment (gerhardol) [reply src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettings/ColorsSettingsPage.cs]: That will be needed for closing issues (currently copy from previous issue explaining, mstv also added screenshots), when this PR is out very few will see the issues...

File: src/app/GitUI/Theming/ThemeModule.cs [hunk 2]
```diff
@@ -54,7 +56,8 @@ private static ThemeSettings LoadThemeSettings(IThemeRepository repository)
             catch (ThemeException ex)
             {
                 // Not good, ColorHelper needs actual InvariantTheme to correctly transform colors.
-                MessageBoxes.ShowError(null, $"Failed to load invariant theme: {ex}");
+                string firstLine = ex.ToString().Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)[0];
+                MessageBoxes.ShowError(null, $"Failed to load invariant theme: {firstLine}");
                 return ThemeSettings.Default;
```
[the remark this answers is not in the document]
Comment (mstv) [reply src/app/GitUI/Theming/ThemeModule.cs]: Could be factored out as `MessageBoxes.ShowErrorWithFirstLineOfException` including `Trace.WriteLine`.

[the remark this answers is not in the document]
Comment (gerhardol) [reply src/app/GitUI/Theming/ThemeModule.cs]: This is actually not needed, can use ex.Message

File: src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettings/ColorsSettingsPage.cs (hunk 1 above)
Comment (gerhardol) [reply src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettings/ColorsSettingsPage.cs]: Added a link, not clickable though. I believe that is good enough

Comment (gerhardol) [reply src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettings/ColorsSettingsPage.cs]: The wiki is updated

**Comment by frfancha** [comment]
I have the issue that this is supposed to fix - however I have never defined _any_ theme myself (I didn't even know that themes existed for Git Extensions).
Therefore the new message as described in the fix would be "better" than the current behaviour but still be an "error" of Git Extensions in the eyes of the user.
Sending a pop-up called "Error Theme" to users that only have installed V6 instead of previous version and never use the Theme feature in their life is incorrect.

**Comment by gerhardol** [comment]
As "Graph" is ignored, most users will never see any popup.

But if the theme is "migrated" then you have selected a theme, even if it was a long time ago.
