### PR TITLE
Fixed superproject, stash and pull ToolStripSplitButton closing issue

### LINKED ISSUE #3832: Annoying closing of menu from tool bar buttons
This is a **bug** report, with a fix proposal.

The current behavior is when I click the small black arrow of tool bar buttons and a contextual menu opens, the menu closes if the mouse leave the control. It happens with all `ToolStripSplitButton` controls. (Superproject, Stash and Pull ones)

_gitextensions_pr

I figured out this happens in a certain `Focus` configuration, when mouse overs the buttons and they render an emboss, this bug happens, however if the branch drop down or the filter text box is focused, the tool bar buttons do not render their emboss on mouse over, and in this focus configuration, the menu does not closes when the mouse exit its area.

I implemented a fix based on this workaround.

This issue is of course not related to Git but purely UI and happens even in `2.50.01`. So far I always encountered this issue, which really drives me nuts.

That said, I wonder if I'm the only one pissed off by this issue because I couldn't find any report of it.

I've read the contribution guidelines a bit too late and already implemented a fix, the commit can be reviewed here: https://github.com/TanukiSharp/gitextensions/commit/f4d2e5bd41660493392f227c15a817cb5b3c380f

The way I fixed it is by enforcing the focus to a control that prevent menu to close (branch drop down), only if it is not already focused (and if the filter text box is not focused either). I store the focused control in the button's `Tag` property in order to restore the focus when the `ToolStripSplitButton` closes. This may break something if the `Tag` property can be used for another feature.

This fix looks like a hack, but I couldn't find any other way around.

I implemented a solution based on constraining the mouse position (screen space) in order to ensure the mouse can only leave the control from top, left and bottom but never from the right. This works, but looks even more cheesy. We can talk about it.

Another solution would be to re-implement the `ToolStripSplitButton` based on a regular `Button` with a `ContextMenu` attach to it, but this is quite a lot of work.

### PR DESCRIPTION
**Pull request by TanukiSharp**
Fixes #3832

Changes proposed in this pull request:
 - Avoid `ToolStripSplitButton` menu to close unexpectedly
 
How did I test this code:
 - Click on `Superproject`, `Stash` of `Pull` button (the small black triangle)
 - Move the mouse 1 pixel out of the button or the left or on the right of the button
 - The context menu that just opened should close
 - The fix prevent the menu to close in such situation

Has been tested on (remove any that don't apply):
 - Windows 10 Pro

### CODE REVIEW

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -3335,9 +3335,31 @@ private void SubmoduleToolStripButtonClick(object sender, EventArgs e)
...
+            }
+        }
+
+        private void ToolStripSplitButtonDropDownClosed(object sender, EventArgs e)
+        {
+            var control = sender as ToolStripSplitButton;
+            control.DropDownClosed -= ToolStripSplitButtonDropDownClosed;
+            if (control.Tag != null)
+            {
+                ((Control)control.Tag).Focus();
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs]: this is inefficient and unsafe

```
var controlToFocus = control.Tag as Control;
if (controlToFocus == null) 
{
    return;
}
controlToFocus.Focus();
control.Tag = null;
```

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 2]
```diff
@@ -3335,9 +3335,31 @@ private void SubmoduleToolStripButtonClick(object sender, EventArgs e)
...
+            {
+                control.Tag = this.FindFocusedControl();
+                control.DropDownClosed += ToolStripSplitButtonDropDownClosed;
+                toolStripBranchFilterComboBox.Focus();
+            }
+        }
+
+        private void ToolStripSplitButtonDropDownClosed(object sender, EventArgs e)
+        {
+            var control = sender as ToolStripSplitButton;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs]: a possible NRE. please check for null and exit early

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 3]
```diff
@@ -3335,9 +3335,31 @@ private void SubmoduleToolStripButtonClick(object sender, EventArgs e)
...
+            {
+                ((Control)control.Tag).Focus();
+                control.Tag = null;
+            }
+        }
+
         private void toolStripButtonLevelUp_DropDownOpening(object sender, EventArgs e)
         {
             LoadSubmodulesIntoDropDownMenu();
+            PreventToolStripSplitButtonClosing((ToolStripSplitButton)sender);
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs]: here and other places, why do unsafe cast when you know exactly which toolstrip button should be actioned?

```
private void toolStripButtonLevelUp_DropDownOpening(object sender, EventArgs e)
{
    LoadSubmodulesIntoDropDownMenu();
    PreventToolStripSplitButtonClosing(toolStripButtonLevelUp);
}
```

The reason being - too often in the codebase handler get invoked prgrammatically, and not always with the necessary parameters.

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 4]
```diff
@@ -3335,9 +3335,31 @@ private void SubmoduleToolStripButtonClick(object sender, EventArgs e)
             }
         }
 
+        private void PreventToolStripSplitButtonClosing(ToolStripSplitButton control)
+        {
+            if (toolStripBranchFilterComboBox.Focused == false && toolStripRevisionFilterTextBox.Focused == false)
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs]: please invert if to reduce nesting

**Comment by TanukiSharp** [comment]
OK I will fix all your concerns.

About:
> why do unsafe cast when you know exactly which toolstrip button should be actioned?

This is because a better practice would be to centralize the subscription to `DropDownOpening` on all the controls to protect, to the same handler. In such a case, casting the sender is more future-proof. (I agree on the check for null after a safe cast is much better)

> too often in the codebase handler get invoked prgrammatically

In this case indeed it is unsafe (and I'll fix it), however this is a very bad practice and should be avoided.

I'll update this branch and keep you posted.

Thanks for your review and feedback.

**Comment by RussKie** [comment]
> This is because a better practice would be to centralize the subscription to DropDownOpening on all the controls to protect...

This is a fair point, in that case do it safely -
 `PreventToolStripSplitButtonClosing(sender as ToolStripSplitButton);`

> In this case indeed it is unsafe (and I'll fix it), however this is a very bad practice and should be avoided.

Amen. Sadly unless they are enforced we need to write fool-proof code.

**Comment by TanukiSharp** [comment]
Applied the fixes, should be ready for another review.

**Comment by TanukiSharp** [comment]
The commits have been squashed into a single one.
Thank you for your review.
