### PR TITLE
Fixup highlighted graph

### LINKED ISSUE #11098: Current branch line not fully colored when overlapping with other branches
### Environment

- Git Extensions 33.33.33
- Build 8b5eab531dcc849d00110df6f9797a096e68b500
- Git 2.35.1.windows.2 (recommended: 2.40.1 or later)
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.19
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

The line representing the current branch fails to get colored in certain circumstances when it overlaps with other branch lines.

Actual behavior
image

Expected behavior (version 4.1)
image

~~I have prepared a screenshot for the "Expected behavior", but I couldn't provide a screenshot for the "Actual behavior" as the reconfiguration of the development environment is still pending. I apologize for the inconvenience. I will provide the "Actual behavior" screenshot at a later date.~~

### Steps to reproduce

1. Create multiple branches.
2. Commit to each branch in a specific order.
3. Encounter a scenario where the line representing the current branch overlaps with other branch lines, causing some parts of the current branch line to remain uncolored.

### Did this work in previous version of GitExtensions?

Yes, it was working correctly in version 4.1.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11098
regressed in #10915

## Proposed changes

- Refactor: Simplify property `RevisionGraphColumnProvider.RevisionGraphDrawStyle`
- Avoid drawing the same graph curve twice only if unrelated branches are colored

### Before

image

### After

image

## Test methodology 

- manual

## Please do not squash merge

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
+1
Looks good, have not run

File: GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs [hunk 1]
```diff
@@ -38,24 +35,7 @@ public RevisionGraphColumnProvider(RevisionGraph revisionGraph, IGitRevisionSumm
...
-                if (AppSettings.RevisionGraphDrawNonRelativesGray)
-                {
-                    return RevisionGraphDrawStyleEnum.DrawNonRelativesGray;
-                }
-
-                return RevisionGraphDrawStyleEnum.Normal;
-            }
-            set { _revisionGraphDrawStyle = value; }
-        }
+        public RevisionGraphDrawStyle RevisionGraphDrawStyle;
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs:38]: This makes it a public field, which is discouraged.
```suggestion
        public RevisionGraphDrawStyle RevisionGraphDrawStyle { get; set; }
```

Comment (mstv) [reply GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs:38]: done
