### PR TITLE
fix(scripts): Do not quote {SelectedRelativePaths}

### LINKED ISSUE #11794: Value quoting behavior of {SelectedRelativePaths} doesn't match other parameters available through scripting
### Environment

- GitExtensions version: [master]

### Issue description

Script variables help says:
```
Use {option} for normal replacement.
Use {{option}} for quoted replacement.
```

but unlike other script variables `{SelectedRelativePaths}` quotes the path to selected commit blobs. This is due to this line https://github.com/gitextensions/gitextensions/blob/548902485d318d252c8d1d5a43b45d124be11bca/src/app/GitUI/CommandsDialogs/ScriptOptionsProvider.cs#L32
where the value is always quoted before even getting to the scripting engine.

### Steps to reproduce

Output taken from the Git Command Log dialog

Single file selected, configured script args: `{SelectedRelativePaths}; {sBranch}`
_Both variable values should be unquoted_
```
File name:   SelectedRelativePaths_demo
Arguments:   "src/app/GitUI/CommandsDialogs/FormCommit.cs"; gitextensions/master
Working dir: C:\Workplace\personal\gitextensions\
```

Multiple files selected, configured script args: `{SelectedRelativePaths}; {sBranch}`
_Both variable values should be unquoted_
```
File name:   SelectedRelativePaths_demo
Arguments:   "src/app/GitUI/CommandsDialogs/FormCommit.cs" "src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs"; gitextensions/master
Working dir: C:\Workplace\personal\gitextensions\
```

Single file selected, configured script args: `{{SelectedRelativePaths}}; {{sBranch}}`
_Actual blob path doesn't contain quotes in it, this value is incorrect_
```
File name:   SelectedRelativePaths_demo
Arguments:   "\"src/app/GitUI/CommandsDialogs/FormCommit.cs\""; "gitextensions/master"
Working dir: C:\Workplace\personal\gitextensions\
```

Multiple files selected, configured script args: `{{SelectedRelativePaths}}; {{sBranch}}`
_Actual blob path doesn't contain quotes in it, this value is incorrect_
```
File name:   SelectedRelativePaths_demo
Arguments:   "\"src/app/GitUI/CommandsDialogs/FormCommit.cs\" \"src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs\""; "gitextensions/master"
Working dir: C:\Workplace\personal\gitextensions\
```

### Did this work in previous version of GitExtensions?

No

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11794

## Proposed changes

- fix(scripts): Do not quote `{SelectedRelativePaths}`
- fix(scripts): Support multiple values in `IScriptOptionsProvider`
  each value quoted for `{{SelectedRelativePaths}}`

## Screenshots 

N/A

## Test methodology 

- extended test

## Please do not squash merge

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
LGTM Have not run

**Comment by mdonatas-trafi** [comment]
Before the changes were made for `SelectedFiles` to return a blob path rather than full-path I've been making changes so I could concat/replace/etc these variables via "Run on PowerShell" option and one of the problems I ran into is that this kind of escaping did not work.

So I went to see how `ProcessStartInfo` does it and it was different than current method. When I changed current method to what's used in the BCL, then the test-cases for WSL and Windows became identical. @mstv could you look at this commit to see what I mean: https://github.com/mdonatas/gitextensions/commit/768ca88c37ca98ef17e448db6656031eab9718c5

Basically I think we can unify these two methods esp. given that current method did not work when running with PowerShell mode.

File: src/app/GitCommands/StringExtensions.cs [hunk 1]
```diff
@@ -191,12 +191,12 @@ public static string Quote(this string? s, string q = "\"")
         }
 
         /// <summary>
-        /// Quotes and escapes this string for use as a command line argument.
+        ///  Escapes this string for use as a command line argument.
```
Comment (mdonatas-trafi) [inline src/app/GitCommands/StringExtensions.cs:194]: nit: Extra space before `Escapes`

File: tests/app/UnitTests/GitCommands.Tests/StringExtensionTests.cs [hunk 2]
```diff
@@ -131,22 +131,22 @@ public void SubstringAfterLast_string_works_as_expected(string str, string s, st
...
+        [TestCase("C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe", true, "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe")]
+        [TestCase("echo \"Hello world\"", false, "echo \\\"Hello world\\\"")]
+        [TestCase("echo \"Hello world\"", true, "echo \"\"Hello world\"\"")]
+        [TestCase("echo \'Hello world\'", false, "echo \\\'Hello world\\\'")]
+        [TestCase("echo \'Hello world\'", true, "echo \'Hello world\'")]
+        [TestCase("cmd /c \"echo \\\"Hello world\\\"\"", false, "cmd /c \\\"echo \\\\\\\"Hello world\\\\\\\"\\\"")]
+        [TestCase("cmd /c \"echo \\\"Hello world\\\"\"", true, "cmd /c \"\"echo \\\"\"Hello world\\\"\"\"\"")]
+        [TestCase("cmd /c \"echo \"\"Hello world\"\"\"", false, "cmd /c \\\"echo \\\"\\\"Hello world\\\"\\\"\\\"")]
+        [TestCase("cmd /c \"echo \"\"Hello world\"\"\"", true, "cmd /c \"\"echo \"\"\"\"Hello world\"\"\"\"\"\"")]
         public void QuoteForCommandLine_works_as_expected(string s, bool forWindows, string expected)
```
Comment (mdonatas-trafi) [inline tests/app/UnitTests/GitCommands.Tests/StringExtensionTests.cs:147]: Test name doesn't reflex the rename

File: src/app/GitCommands/StringExtensions.cs (hunk 1 above)
Comment (mstv) [reply src/app/GitCommands/StringExtensions.cs:194]: intended xmldoc style as requested by RussKie

**Comment by RussKie** [comment]
> Before the changes were made for `SelectedFiles` to return a blob path rather than full-path I've been making changes so I could concat/replace/etc these variables via "Run on PowerShell" option and one of the problems I ran into is that this kind of escaping did not work.
> 
> So I went to see how `ProcessStartInfo` does it and it was different than current method. When I changed current method to what's used in the BCL, then the test-cases for WSL and Windows became identical. @mstv could you look at this commit to see what I mean: [mdonatas@768ca88](https://github.com/mdonatas/gitextensions/commit/768ca88c37ca98ef17e448db6656031eab9718c5)
> 
> Basically I think we can unify these two methods esp. given that current method did not work when running with PowerShell mode.

I think that makes sense

File: src/app/GitCommands/StringExtensions.cs (hunk 1 above)
Comment (RussKie) [reply src/app/GitCommands/StringExtensions.cs:194]: It was found through trials and errors that extra space in xml-doc significantly increase readability of the docs.

**Comment by mstv** [comment]
> > Before the changes were made for `SelectedFiles` to return a blob path rather than full-path I've been making changes so I could concat/replace/etc these variables via "Run on PowerShell" option and one of the problems I ran into is that this kind of escaping did not work.
> > So I went to see how `ProcessStartInfo` does it and it was different than current method. When I changed current method to what's used in the BCL, then the test-cases for WSL and Windows became identical. @mstv could you look at this commit to see what I mean: [mdonatas@768ca88](https://github.com/mdonatas/gitextensions/commit/768ca88c37ca98ef17e448db6656031eab9718c5)
> > Basically I think we can unify these two methods esp. given that current method did not work when running with PowerShell mode.
> 
> I think that makes sense

Continue the discussion about escaping in  #11798, please.
This PR handles the quoting and is ready IMO.

**Comment by RussKie** [comment]
> > > Before the changes were made for `SelectedFiles` to return a blob path rather than full-path I've been making changes so I could concat/replace/etc these variables via "Run on PowerShell" option and one of the problems I ran into is that this kind of escaping did not work.
> > > So I went to see how `ProcessStartInfo` does it and it was different than current method. When I changed current method to what's used in the BCL, then the test-cases for WSL and Windows became identical. @mstv could you look at this commit to see what I mean: [mdonatas@768ca88](https://github.com/mdonatas/gitextensions/commit/768ca88c37ca98ef17e448db6656031eab9718c5)
> > > Basically I think we can unify these two methods esp. given that current method did not work when running with PowerShell mode.
> > 
> > 
> > I think that makes sense
> 
> Continue the discussion about escaping in #11798, please. This PR handles the quoting and is ready IMO.

If we'd go with [mdonatas@768ca88](https://github.com/mdonatas/gitextensions/commit/768ca88c37ca98ef17e448db6656031eab9718c5) would this change be needed at all? I'm genuinely curious.

@mdonatas since you encountered https://github.com/gitextensions/gitextensions/issues/11794 have you given any thoughts how it could get fixed?

**Comment by mstv** [comment]
> If we'd go with [mdonatas@768ca88](https://github.com/mdonatas/gitextensions/commit/768ca88c37ca98ef17e448db6656031eab9718c5) would this change be needed at all? I'm genuinely curious.

I strongly dislike joining multiple values using the pipe symbol `|` - refer to https://github.com/gitextensions/gitextensions/issues/11794#issuecomment-2192534089.
The blob paths need to be quoted each. The quoting is done by generic code just in dependency on single or double braces.
Hence, providing multiple values is necessary.

@mdonatas has already agreed to https://github.com/gitextensions/gitextensions/pull/11795#issuecomment-2209404912.

**Comment by mdonatas** [comment]
Sorry for a late reply, I am on vacation now so I don't get as much computer time as usual :)

I agree that a `|` is probably not the best option.

Lets see what scenarios could come up during scripting

- A: `program.exe -SingleItemParam {{SomeParam}}`. `SelectedRelativePaths` would not suite this scenario due to its "multiple params" nature as user could have several items selected, to solve this we'd need to add `First/LatestSelectedRelativePath`
- B: `(("https://github.com{cDefaultRemotePathFromUrl}/blob/{sHash}/{SelectedRelativePaths}").Replace("{WorkingDir}", "").Replace("\\", "/"))` I've had this PowerShell script while `SelectedRelativePaths` was still a physical path on disk but it illustrates potential way of using a variable, that is when it's used inside of a string. This PR enables it by not quoting values when single brace is used with `{SelectedRelativePaths}`, but is still "vulnerable" to crash when multiple files are selected.
- C: `FindAndOpenSolutionFile.exe -- {{SelectedRelativePaths}}` this PR enables this scenario too this would translate to `FindAndOpenSolutionFile.exe -- "src/file 1.cs" "src/file 2.cs"`
- D: `"""src/file 1.cs"" ""src/file 2.cs""".Split(@('" "', '"'), [StringSplitOptions]::RemoveEmptyEntries) | ForEach-Object { & DoSomethingWithFile.exe $_ }` this scenario is currently not possible and was the kind of use case I was thinking of when suggesting to join multiple values with `|` as it would be "separator" to separate multiple values. Script author _(I think)_ cannot write a script to do something like this now. For this, I am thinking, we would need a triple brace variable syntax which would mean "multiple values quoted".
  - `{SelectedRelativePaths}` -> `src/file 1.cs src/file 2.cs` not very helpful with multiple values esp. when values can contain spaces
  - `{{SelectedRelativePaths}}` -> `"src/file 1.cs" "src/file 2.cs"` suitable to pass as args to an executable
  - `{{{SelectedRelativePaths}}}` -> `"""src/file 1.cs"" ""src/file 2.cs"""` suitable for PowerShell scripting and could also cover `A` albeit with more complex PowerShell solution.

This PR covers cases `B` and `C` but due to braces and spaces having special meaning in cmd/PowerShell is not enough to enable `D`.

Did I miss something with listed cases above?

As for this PR I agree that it should be merged as is.

p.s. I've just realized that this comment makes more sense in https://github.com/gitextensions/gitextensions/issues/11794 as `{{{MultiParamsVariable}}}` syntax is a potential solution to it.

**Comment by mdonatas** [comment]
🤦 I've just realized that in PowerShell one can use `'` quotes to have `"` appear freely in a literal string.. just like in JS which means that `D` example would work like so `'{{SelectedRelativePaths}}'`. It seems all of the scenarios can be achieved unless someone has an example which could still not be achieved.

**Comment by mstv** [comment]
> TL;DR: As for this PR I agree that it should be merged as is.

Can I get reviews, please?

---

Regarding case `D` (which should be handled separately from this PR if really needed):

A workaround could be to use argument names (although it might not be parsed by a one-liner). I think of e.g.
`scriptname --paths {{SelectedRelativePaths}} --`

**Review by gerhardol — APPROVED** [review]
Have not run

File: src/app/GitUI/ScriptsEngine/IScriptOptionsProvider.cs [hunk 3]
```diff
@@ -11,6 +11,6 @@ public interface IScriptOptionsProvider
     ///  Retrieves the information for placeholders in script arguments.
     /// </summary>
     /// <param name="option">The option identifier which is to be replaced.</param>
-    /// <returns>The value to be used for the script argument.</returns>
-    string? GetValue(string option);
+    /// <returns>The value(s) to be used for the script argument.</returns>
+    IEnumerable<string> GetValue(string option);
```
Comment (RussKie) [inline src/app/GitUI/ScriptsEngine/IScriptOptionsProvider.cs:15]: If the return value is a set/collection, then the method name has to be pluralised
```suggestion
    IEnumerable<string> GetValues(string option);
```

This opens another question - should this API be an addition to the original? That is:
```diff
    string? GetValue(string option);
+   IEnumerable<string> GetValues(string option);
```

Comment (RussKie) [inline src/app/GitUI/ScriptsEngine/IScriptOptionsProvider.cs:15]: The original contract implied it could return a null, though looking at the implementation it never did. It's worth inspecting all callsites and remove null-handling operations, if any.

Comment (mstv) [reply src/app/GitUI/ScriptsEngine/IScriptOptionsProvider.cs]: > It's worth inspecting all callsites and remove null-handling operations, if any.

Former `null` values had already been converted to empty collections.
Since other options can return a single value, `IEnumerable<string>? newStrings` needs to be nullable inside `ParseScriptArguments`.

Comment (RussKie) [reply src/app/GitUI/ScriptsEngine/IScriptOptionsProvider.cs]: From the API design standpoint `IEnumerable<string>?` is rather undesirable - collection/set return value should never be a null but an empty collection/set.

Comment (mstv) [reply src/app/GitUI/ScriptsEngine/IScriptOptionsProvider.cs]: What do you mean, Igor?

image

Comment (RussKie) [reply src/app/GitUI/ScriptsEngine/IScriptOptionsProvider.cs]: I was replying to your earlier comment:

> Since other options can return a single value, IEnumerable<string>? newStrings needs to be nullable inside ParseScriptArguments.

...but appears I have misread it :)

**Review by RussKie — APPROVED** [review]
