### PR TITLE
Check if path exists before creating FileInfo

### LINKED ISSUE #8839: [NBug] The given path's format is not supported.
## Current behaviour

GitExtensions crashes when right click a file with a strange path in the Diff section.

## Expected behaviour

Don't crash and let make actions over that committed file.
## Steps to reproduce

Right click on a file with a path like: src/my-project/c:\temp\somefile.txt in the Diff section

## Error Details
```
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at GitUI.CommandsDialogs.BrowseDialog.FormBrowseUtil.FileOrParentDirectoryExists(String path)
   at GitUI.CommandsDialogs.RevisionDiffControl.UpdateStatusOfMenuItems()
   at GitUI.CommandsDialogs.RevisionDiffControl.DiffContextMenu_Opening(Object sender, CancelEventArgs e)
   at System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnOpening(CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ContextMenuStrip.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.ContextMenuStrip.ShowInternal(Control source, Point location, Boolean isKeyboardActivated)
   at System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   at System.Windows.Forms.Control.WmContextMenu(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.ExListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
A file is in a branch with a path like: src/my-project/c:\temp\somefile.txt
when I right click the file in the Diff tab it crashes saying "The given path's format is not supported."

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 120dpi (125% scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Will avoid exceptions for illegal characters etc

Fixes #8839

## Proposed changes

Use File.Exists(path) before FileInfo(path) to avoid exceptions.

Can be seen as a follow up to #8575 

## Test methodology 

review

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -2467,11 +2467,6 @@ public static void OpenContainingFolder(FileStatusList diffFiles, GitModule modu
             foreach (var item in diffFiles.SelectedItems)
             {
                 string filePath = PathUtil.Combine(module.WorkingDir, item.Item.Name.ToNativePath());
-                if (string.IsNullOrWhiteSpace(filePath))
-                {
-                    continue;
-                }
-
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs:2474]: All other changes make sense, but this change is surprising in the given context. Could you please elaborate on this?

**Review by RussKie — COMMENTED** [review]
LGTM with a question

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormBrowse.cs:2474]: null annotation is coming soon...
null is an acceptable input with the change so the caller do not need to check
