### PR TITLE
Throw on non-zero exit code and on stderror output

### LINKED ISSUE #6527: Generic handling of Git exit codes, errors and warnings
## Current behaviour

The exit code of Git as well as errors and warnings printed to the console by Git are not checked by every GE function.

## Expected behaviour

Git command errors are not silently ignored but handled correctly.
Git warnings and errors are displayed clearly, not only as an unhandled exception.

`GitCommand` shall check the Git exit code and throw a `GitFailException` unless the calling function indicates that it will handle the exit code itself. The `Exception.Message` shall contain all Git error messages ("error: ...", "fatal: ...") and all Git warning messages ("warning: ...").

A `GitErrorException` shall be thrown with all Git error and warning messages as the `Exception.Message`. These exceptions shall be caught by the calling function or form if applicable and as a fallback by `GitModuleForm`/`GitModuleControl`, which shall display the error message in a MessageBox.

`GitCommand` shall check for Git warning messages and display them in a MessageBox unless the calling function indicates that it will handle them itself.
Though I am not sure whether a MessageBox is really feasible in async and background tasks. If not, a `GitWarningException` should be thrown with all Git warning messages as the `Exception.Message`. The drawback of this exception would be that all functions which don't handle the warnings themselves would be canceled.

Git errors and warnings shall be logged in the `GitCommandLog`.

## Environment

- Git Extensions 3.1.0
- Build 3d5da22221203dbe14bdb53ff779799c1d8c5f09
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #8263: [NBug] Der Prozess kann nicht auf die Datei "C:\Projects\Tropico6\...
## Current behaviour

GitExtension crashed when trying to save over a file via "Save As" where a file lock is hold by another process

## Expected behaviour

Some error popup telling that GitExtensions could not save the file.

## Steps to reproduce

- Grab any file with a history
- Open another program that holds an write-exclusive lock on the file
- Try to use "Save as" on the file, attempting to overwrite it.

## Error Details
```
System.IO.IOException: Der Prozess kann nicht auf die Datei "C:\Projects\Tropico6\Tropico6\Source\Tropico6\Game\Building\T6Building.cpp" zugreifen, da sie von einem anderen Prozess verwendet wird.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   bei GitCommands.GitModule.SaveBlobAs(String saveAs, String blob)
   bei GitUI.CommandsDialogs.FormFileHistory.saveAsToolStripMenuItem_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
"Save as" from history on an older version over a file where another process holds an exclusive file lock.

I can understand, that GitExtension can't write over the file, but that isn't a reason to crash.. ;)

Note: I just got https://github.com/gitextensions/gitextensions/issues/8262 closed while I was editing the description text, so I hope that this here won't be closed as a duplicate of 8262.. lets see.

## Environment
- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.24.1.windows.2 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #8632: Show error message when Reset file fails
## Feature description

Related to #8630 

Due to the missing file, I tryied to reset the file to get it.

Of course, git fails but Git Extensions don't complain.

I suggest that GitModule.CheckoutFiles should return a bool and return the result of ``_gitExecutable.RunBatchCommand``. So caller (like ``RevisionDiffControl.ResetSelectedItemsTo``) should be able to display a MessageBox.

Are you okay before I implement it ?

## Environment

- Git Extensions 33.33.33
- Build 3737099926a138c34433f6cd1de29b5d9580968f
- Git 2.22.0.windows.1 (recommended: 2.28.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by mstv**
Fixes #6527
Fixes #8263
Fixes #8632
Closes #8906 as obsolete
Closes #8961 as obsolete

## Proposed changes

- Throw `ExternalOperationException` if a started process exits with a non-0 exit code or if the process printed output to `StandardError`
- Suppress this exception for commands whose errors are handled

## Test methodology 

- manual
- existing NUnit tests

## Test environment(s) 

- Git Extensions 33.33.33
- Build 3bed1c81024391ba2f58c2b005f915d6fac21260
- Git 2.27.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
There are some more situations where errors are handled, where IsGitErrorMessage() parses the output.
Those should be changed though
(as well as `ExitCode == 0` should be replaced with `ExitedSuccessfull`)

Some situations like "describe" and in RevParse() (that should have --quiet --verify and check status anyway) are handled in this PR.

```patch
diff --git a/GitCommands/Git/GitModule.cs b/GitCommands/Git/GitModule.cs
index 6aace..9124d 100644
--- a/GitCommands/Git/GitModule.cs
+++ b/GitCommands/Git/GitModule.cs
@@ -2507,14 +2507,12 @@ public IReadOnlyList<GitItemStatus> GetTreeFiles(ObjectId commitId, bool full)
             bool excludeAssumeUnchangedFiles = true, bool excludeSkipWorktreeFiles = true,
             UntrackedFilesMode untrackedFiles = UntrackedFilesMode.Default)
         {
-            var output = _gitExecutable.GetOutput(
-                GitCommandHelpers.GetAllChangedFilesCmd(excludeIgnoredFiles, untrackedFiles));
-
-            List<GitItemStatus> result = _getAllChangedFilesOutputParser.Parse(output).ToList();
-            if (IsGitErrorMessage(output))
+            var exec = _gitExecutable.Execute(GitCommandHelpers.GetAllChangedFilesCmd(excludeIgnoredFiles, untrackedFiles));
+            List<GitItemStatus> result = _getAllChangedFilesOutputParser.Parse(exec.StandardOutput).ToList();
+            if (!exec.ExitedSuccessfully)
             {
                 // No simple way to pass the error message, create fake file
-                result.Add(createErrorGitItemStatus(output));
+                result.Add(createErrorGitItemStatus(exec.StandardError));
             }
  
             if (!excludeAssumeUnchangedFiles || !excludeSkipWorktreeFiles)
```

File: GitCommands/Git/Executable.cs [hunk 1]
```diff
@@ -179,7 +203,7 @@ public StreamReader StandardError
                         throw new InvalidOperationException("Process was not created with redirected output.");
                     }
 
-                    return _process.StandardError;
+                    return _throwOnErrorOutput ? new StreamReader(new MemoryStream()) : _process.StandardError;
```
Comment (RussKie) [inline GitCommands/Git/Executable.cs:206]: Please verify we're not leaking memory here, I can't see where we're disposing the `StreamReader` created here. `_process` gets disposed, and it will dispose its `StandardError` reader, but the new will be left dangling.

File: GitCommands/Git/Executable.cs [hunk 2]
```diff
@@ -128,8 +138,22 @@ private void OnProcessExit(object sender, EventArgs eventArgs)
...
                             _logOperation.LogProcessEnd(exitCode);
+
+                            if (_throwOnErrorOutput)
+                            {
+                                string errorOutput = _process.StandardError.ReadToEnd().Trim();
+                                if (exitCode != 0 || errorOutput.Length > 0)
+                                {
+                                    ExternalOperationException ex
+                                        = new(command: _process.StartInfo.FileName, _process.StartInfo.Arguments, _process.StartInfo.WorkingDirectory,
+                                                new Exception($"exit code {exitCode}{Environment.NewLine}{errorOutput}"));
```
Comment (RussKie) [inline GitCommands/Git/Executable.cs:151]:
```suggestion
                                                new Exception($"Exit code: {exitCode}{Environment.NewLine}{errorOutput}"));
```

File: GitUI/BranchTreePanel/RepoObjectsTree.cs [hunk 3]
```diff
@@ -275,11 +276,20 @@ public void SelectionChanged(IReadOnlyList<GitRevision> selectedRevisions)
...
+                if (selectedGuid is not null)
+                {
+                    try
+                    {
+                        mergedBranches = (await Module.GetMergedBranchesAsync(includeRemote: true, fullRefname: true, commit: selectedGuid)).ToHashSet();
+                    }
+                    catch (ExternalOperationException)
+                    {
+                        // ignore not parsable "HEAD"
+                    }
```
Comment (RussKie) [inline GitUI/BranchTreePanel/RepoObjectsTree.cs:289]:
```suggestion
                HashSet<string> mergedBranches;
                if (selectedGuid is not null)
                {
                    try
                    {
                        mergedBranches = (await Module.GetMergedBranchesAsync(includeRemote: true, fullRefname: true, commit: selectedGuid)).ToHashSet();
                    }
                    catch (ExternalOperationException)
                    {
                        // ignore not parsable "HEAD"
                        mergedBranches = new();
                    }
```

**Review by RussKie — COMMENTED** [review]
👍 with few comments

File: GitCommands/Git/Executable.cs (hunk 1 above)
Comment (mstv) [reply GitCommands/Git/Executable.cs:206]: Done. But can't the GC do it? It is very unlikely that this code path is reached, since the exception already contains the consumed `StandardError` output.

File: GitCommands/Git/Executable.cs (hunk 2 above)
Comment (mstv) [reply GitCommands/Git/Executable.cs:151]: I will move the exit code to the `ExternalOperationException`. The user will not be interested very much in the specific value.

File: GitUI/BranchTreePanel/RepoObjectsTree.cs (hunk 3 above)
Comment (mstv) [reply GitUI/BranchTreePanel/RepoObjectsTree.cs:289]: `mergedBranches` shall not be nullable, and must be an empty `HashSet` if `selectedGuid is null`.

File: GitCommands/Git/GitModule.cs [hunk 4]
```diff
@@ -2467,9 +2473,9 @@ public IReadOnlyList<GitItemStatus> GetStashDiffFiles(string stashName)
             // shows untracked files
             var args = new GitArgumentBuilder("log")
             {
-                $"{stashName}^3",
                 "--pretty=format:\"%T\"",
-                "--max-count=1"
+                "--max-count=1",
+                $"-- {stashName}^3"
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs:2478]: -- separates paths, stashNane is a ref
The order is correct now though

File: GitCommands/Git/GitModule.cs [hunk 5]
```diff
@@ -2289,20 +2292,22 @@ public IReadOnlyList<GitStash> GetStashes(bool noLocks = false)
...
+            CommandCache? cache = cacheResult &&
                         !string.IsNullOrEmpty(secondRevision) &&
                         !string.IsNullOrEmpty(firstRevision) &&
                         !secondRevision.IsArtificial() &&
                         !firstRevision.IsArtificial()
                 ? GitCommandCache
                 : null;
 
-            var patch = _gitExecutable.GetOutput(
+            bool nonZeroGitExitCode = firstId == ObjectId.WorkTreeId && secondId is not null && !isTracked;
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs:2303]: Should not be here but at the caller (may check arguments).
!isTracked cannot use git-diff (regardless of first/second commit).

**Review by gerhardol — COMMENTED** [review]
+0
In general very much needed, good time to add this now.
Will use myself.
(only briely looked at the code now.)

File: GitCommands/Git/GitModule.cs (hunk 4 above)
Comment (mstv) [reply GitCommands/Git/GitModule.cs:2478]: The commit message contains the git error:

```
Fixup git arguments for GetStashDiffFiles

fatal: ambiguous argument 'stash@{0}^3': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
```

sounds a bit confusing to me; but works well

File: GitCommands/Git/GitModule.cs (hunk 5 above)
Comment (mstv) [reply GitCommands/Git/GitModule.cs:2303]: repro:
- create a new file (untracked)
- select `Working directory`, then `Ctrl`+`click` the checked out commit, which turns the added (exit code 0) into a removed file from this perspective (exit code 1)

**Comment by mstv** [comment]
> I get an exception now when starting up, some dashboard repo does not exist I assume

cannot reproduce

**Comment by mstv** [comment]
> Missing Working directory for exceptions

How did you get this?
Usually the directory is there (renamed to just "Directory":

exception with wdir

File: GitCommands/Git/GitModule.cs (hunk 5 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:2303]: The caller should not request this information, it is meaningless.

File: GitCommands/Git/GitModule.cs (hunk 4 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:2478]: stashName is not a path, so it should not be separated with `--`

Comment (mstv) [reply GitCommands/Git/GitModule.cs:2478]: Without "--", git outputs the above _fatal_ error with non-zero exit code.

**Comment by gerhardol** [comment]
Failure in repo without tags (similar to git-describe).
```
       public IReadOnlyList<IGitRef> GetRefs(GetRefsEnum getRef)
        {
            // We do not want to lock the repo for background operations.
            // The primary use of 'noLocks' is to run git-status the commit count as a background operation,
            // but to run the same in a foreground for FormCommit.
            //
            // Assume that all GetRefs() are done in the background, which may not be correct in the future.
            const bool noLocks = true;

            ArgumentString cmd = GitCommandHelpers.GetRefsCmd(getRef, noLocks, AppSettings.RefsSortBy, AppSettings.RefsSortOrder);
            ExecutionResult exec = _gitExecutable.Execute(cmd, throwOnErrorOutput: false);
            return !exec.ExitedSuccessfully
                ? ParseRefs(exec.StandardOutput)
                : new List<IGitRef>();
        }
```

File: GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs [hunk 6]
```diff
@@ -178,7 +178,7 @@ bool TestGitCommand(string command)
             {
                 try
                 {
-                    string output = new Executable(command).GetOutput();
+                    string output = new Executable(command).GetOutput(throwOnErrorOutput: false);
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs:181]: Avoid commands that fail when they do not have to
```suggestion
                    string output = new Executable(command).GetOutput(arguments: " --version");
```

File: GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs [hunk 7]
```diff
@@ -237,7 +237,7 @@ public static bool CheckIfFileIsInPath(string fileName)
 
         public bool CanFindGitCmd()
         {
-            return !string.IsNullOrEmpty(Module?.GitExecutable.GetOutput(""));
+            return !string.IsNullOrEmpty(Module?.GitExecutable.GetOutput(arguments: string.Empty, throwOnErrorOutput: false));
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs:240]:
```suggestion
            return !string.IsNullOrEmpty(Module?.GitExecutable.GetOutput(arguments: "--version"));
```

**Comment by gerhardol** [comment]
I have experienced a few more situations where Git exists with non-zero.
Pushed to a private branch, I believe you can pick them from there
(if you want a motivation let me know, I logged with stack trace while working today and have not investigated the details).

**Comment by mstv** [comment]
> I have experienced a few more situations where Git exists with non-zero.
Pushed to a private branch, I believe you can pick them from there

Thank you. I have cherry-picked them to my work branch `all`. I will look at the details later.

**Comment by mstv** [comment]
> (if you want a motivation let me know, I logged with stack trace while working today and have not investigated the details)

Yes, please, especially the exception text taken from `StandardError`. I find warnings or errors from these commands quite surprising.

**Comment by gerhardol** [comment]
One more push with a fix for git-diff with core.safecrlf

**Comment by gerhardol** [comment]
I still have an exception at startup. Just pushed a commit to be able to work.
 
The sidepanel is init without the working directory is set. That should be disallowed for basically all commands.
Have not found what causes this.

image

**Comment by mstv** [comment]
> The sidepanel is init without the working directory is set. That should be disallowed for basically all commands.

Good catch! This might also be the cause why some of the ROT tests work unstable (and have been disabled).

**Comment by mstv** [comment]
> > (if you want a motivation let me know, I logged with stack trace while working today and have not investigated the details)
> 
> Yes, please, especially the exception text taken from `StandardError`. I find warnings or errors from these commands quite surprising.

I could not reproduce these exceptions. Could you provide details for the first four `!fixup` commits, please?

**Comment by gerhardol** [comment]
Added two commits where error is OK (this was the remaining fatal: reference I saw too)
Maybe all GetOutputLines() should be ignored

The commit messages has descriptions

**Comment by gerhardol** [comment]
42e27c794fd4658502b303fd2c1f592b0cd20682

Line patches exit with error and error text if patches cannot be applied
To use Execute() instead of GetOutput() the input array need to be made to a stream.

**Comment by gerhardol** [comment]
git-mergetool can exit with error if user do not complete the merge
(pushed as well but my private branch is getting out of date)

```patch
diff --git a/GitCommands/Git/GitModule.cs b/GitCommands/Git/GitModule.cs
index e6ca8..6f2dd 100644
--- a/GitCommands/Git/GitModule.cs
+++ b/GitCommands/Git/GitModule.cs
@@ -880,7 +880,7 @@ public void RunMergeTool(string? fileName = "", string? customTool = null)
                 { !string.IsNullOrWhiteSpace(fileName), "--" },
                 fileName.ToPosixPath().QuoteNE()
             };
-            using var process = _gitExecutable.Start(args, createWindow: true);
+            using var process = _gitExecutable.Start(args, createWindow: true, throwOnErrorOutput: false);
             process.WaitForExit();
         }
 
```

**Review by RussKie — COMMENTED** [review]
👍

File: GitCommands/Git/GitModule.cs [hunk 8]
```diff
@@ -880,7 +880,7 @@ public void RunMergeTool(string? fileName = "", string? customTool = null)
                 { !string.IsNullOrWhiteSpace(fileName), "--" },
                 fileName.ToPosixPath().QuoteNE()
             };
-            using var process = _gitExecutable.Start(args, createWindow: true);
+            using var process = _gitExecutable.Start(args, createWindow: true, throwOnErrorOutput: false);
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:883]: In my tests, I could not see any errors from git.
How to reproduce, @gerhardol?

Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:883]: You need to set https://git-scm.com/docs/git-mergetool#Documentation/git-mergetool.txt-mergetoollttoolgttrustExitCode
The tool need to set the exit code too. At least Beyond Compare does that, not checked others.

Then you need to make a merge with a conflict and not resolve the conflict, but that part I am sure you follow.

Comment (mstv) [reply GitCommands/Git/GitModule.cs:883]: Thank you for the explanation.

**Review by gerhardol — COMMENTED** [review]
+1
I have reviewed before and used this PR for quite some time.
I doubt I will have many comments when reviewing again.
Just as I detected some commands that required an adjustment (as mstv had done before of course for many uses), other users will see new edge cases. This will depend on Git versions to some extent too.

So I recommend merge.

**Comment by gerhardol** [comment]
One more exclusion for throwing in #9413 
`git-log --follow` accepts exactly one argument only. Manual path filters may contain more arguments.
There are basic checks for more than one argument, but the final check is the Git command.

**Comment by mstv** [comment]
> git-log --follow accepts exactly one argument only. Manual path filters may contain more arguments.
There are basic checks for more than one argument, but the final check is the Git command.

Are these errors displayed?

**Comment by gerhardol** [comment]
> Are these errors displayed?

Not seen, handled by ignoring the output.
Not a problem before #9413 beacause rename detection is not implemented for Advanced filter and FileHistory always have only one argument.

File: GitCommands/Git/GitModule.cs (hunk 8 above)
Comment (mstv) [reply GitCommands/Git/GitModule.cs]: Since `RunMergeTool` does not check the results, I have reverted this from this PR.
If errors must really be ignored, I'd like to handle it in a dedicated PRs on principle.

I have not seen any popups when aborting the merge conflict resolution in BC - with `git config mergetool.bc.trustExitCode true`.

**Comment by mstv** [comment]
@msftbot merge in 5 days

**Review by gerhardol — APPROVED** [review]
Lets get this merged, there will be adjustments needed...
(Both due to incorrect GE code and to allow error exits)

File: GitCommands/Git/GitModule.cs (hunk 5 above)
Comment (RussKie) [reply GitCommands/Git/GitModule.cs:2304]: We need to have at least a comment explaining this. It is not obvious what this check is and why it is needed.

File: GitCommands/Git/Executable.cs [hunk 9]
```diff
@@ -33,7 +33,8 @@ public Executable(Func<string> fileNameProvider, string workingDir = "")
                               bool redirectInput = false,
                               bool redirectOutput = false,
                               Encoding? outputEncoding = null,
-                              bool useShellExecute = false)
+                              bool useShellExecute = false,
+                              bool throwOnErrorOutput = true)
```
Comment (RussKie) [inline GitCommands/Git/Executable.cs:37]: How many callsites with `throwOnErrorOutput = true` vs `throwOnErrorOutput = false` do we have?

File: GitCommands/Git/Executable.cs [hunk 10]
```diff
@@ -134,8 +147,25 @@ private void OnProcessExit(object sender, EventArgs eventArgs)
...
+                                    ExternalOperationException ex
+                                        = new(command: _process.StartInfo.FileName,
+                                              _process.StartInfo.Arguments,
+                                              _process.StartInfo.WorkingDirectory,
+                                              exitCode,
+                                              new Exception(errorOutput));
+                                    _logOperation.LogProcessEnd(ex);
+                                    _exitTaskCompletionSource.TrySetException(ex);
+                                }
+                            }
```
Comment (RussKie) [inline GitCommands/Git/Executable.cs:167]: Do we have tests for this?

**Comment by RussKie** [comment]
@msftbot forget everything I just told you

**Comment by RussKie** [comment]
I have few questions, disabling the auto-merge for now.

File: GitCommands/Git/Executable.cs (hunk 9 above)
Comment (gerhardol) [reply GitCommands/Git/Executable.cs:37]: 42 (and 18 tests) that do not throw. Some of those could probably be tightened to not return errors.
Other about 69 (and 22 plugin and 24 tests)

Comment (mstv) [reply GitCommands/Git/Executable.cs:37]: This is what this PR is about: Let the user see the errors *by default*.
I want to have a justification for all exceptions from this default.

File: GitCommands/Git/GitModule.cs (hunk 5 above)
Comment (mstv) [reply GitCommands/Git/GitModule.cs:2304]: > Should not be here but at the caller (may check arguments).
!isTracked cannot use git-diff (regardless of first/second commit).

> The caller should not request this information, it is meaningless.

Explain it in other words, please.

> It is not obvious what this check is and why it is needed.

Would you better understand it with `nonZeroGitExitCodeExpected`?
It is used once - in the next statement.

File: GitCommands/Git/Executable.cs (hunk 10 above)
Comment (mstv) [reply GitCommands/Git/Executable.cs:167]: This is an integration. What would be the focal point of this test?

**Review by RussKie — APPROVED** [review]

File: GitCommands/Git/Executable.cs (hunk 10 above)
Comment (RussKie) [reply GitCommands/Git/Executable.cs:167]: Now looking at it, I don't think it is correct.

I want to fail on "exit code != 0", but I don't want to fail on "errorOutput.Length > 0" because it contains warnings.
If anything it has to be 
```cs
if (exitCode != 0 || (_throwOnErrorOutput && errorOutput.Length > 0))
```

As far as a test goes, we have integration tests in `ExecutableExtensionsTests` that allow testing this functionality.

Comment (gerhardol) [reply GitCommands/Git/Executable.cs:167]: The intention with this PR is that errors and warnings should be handled, so checking the error output is in line with this.
In #9468 the throw will suppress both exit code and stderr, only show popup for exit code - could be popup on filtered stderr too.)
The origin of #9468 was that Git added printout to stderr in situations where the user did not expect them or see them before, so this should maybe be removed before a public release.
I suggest open an issue in milestone 3.6 for this and we catch warnings until then.

Comment (gerhardol) [reply GitCommands/Git/Executable.cs:167]: Throwing on only stderr could be a separate argument too.

Comment (RussKie) [reply GitCommands/Git/Executable.cs:167]: By fixing one thing we must not break existing working things.

And I maintain this implementation is not correct - "exit code=0" implies the operation completed successfully. `errorOutput` may contain warnings, but they are not fatal, otherwise they'd been made errors.

Comment (gerhardol) [reply GitCommands/Git/Executable.cs:167]: > By fixing one thing we must not break existing working things.

This PR **will** break functionality that happened to work before. See my conversation in this PR and PRs pointing to this as examples. (Of course, mstv fixed most problems in the PR but there is no history of that other than the code changes).

I find this breaking change important to find issues (at least during development), some to be suppressed, some to be suppressed, others to be fixed.
For production the popup could be suppressed (I currently want to have it enabled though.)

> And I maintain this implementation is not correct - "exit code=0" implies the operation completed successfully. errorOutput may contain warnings, but they are not fatal, otherwise they'd been made errors.

The warnings on stderr could be fatal, it is case by case. This could be yet another configuration.
But letting the caller make the choice is likely sufficient, similar to all other commands.

`throwOnErrorOutput` should not be allowed with `GetOutput*`, stderr should never be parsed as stdout.
Also, `includeErrorOutput` should be removed as these commands should fail.
This affects like 7 methods

`GetOutputLinesAsync` should be removed too (9 usages), will not be usable in #9476 anyway.
Not sure how the async yielding should be handled though.

Comment (gerhardol) [reply GitCommands/Git/Executable.cs:167]: Draft cleanup in 3d320d33b8987b522b12dc88ea492ebc7ed84e80
The only actual change is that stderr is not parsed as an output (except SystemEncodingReader where I was unsure).

`GetOutput` is the simple flow where neither error exit nor stderr is allowed. 
"Advanced" usage with `Execute`

Comment (mstv) [reply GitCommands/Git/Executable.cs:167]: > this implementation is not correct

No, it is. But the definition seems to be too strict.

> "exit code=0" implies the operation completed successfully. errorOutput may contain warnings, but they are not fatal, otherwise they'd been made errors.

I agree, this is a good definition.

Anyway, I want to get noticed of git warnings and non-fatal errors. They do not need to popup interrupting the command execution. The `ErrorOutput` should be added to the Git Command Log. New warnings should be indicated e.g. in the toolbar of FormBrowse or might be shown as Windows notifications. (Might need a configurable filter.)

PS: Regarding my status: It means tomorrow.

Comment (gerhardol) [reply GitCommands/Git/Executable.cs:167]: `GetOutput()` as a simple method could well fail on any error output. stderr should normally not be parsed in the expected output.
I reviewed the use of stderr/AllOuput in #9488.
If `GetOutput` is changed to not throw if error exit is set, the method should only return stderr, not merge it with stderr.
`GetOutput` could be replaced globally too.
