### PR TITLE
fix(blame previous): Remove restriction to availibility of the actual revision

### LINKED ISSUE #10946: "Blame previous revision" menu item always disabled
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

"Blame previous revision" menu item is always disabled in the Blame pane

### Steps to reproduce

1. Right-click on a file in the repository in Windows Explorer.
2. Select "File history" from the context menu.
3. In the File History window, right-click on a revision in the Blame pane.
4. A context menu will appear. The menu item "Blame previous revision" should be present.
5. Notice that this menu item is always disabled, even when there are previous revisions to the file.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10946

## Proposed changes

`BlameControl`
- Remove restriction to availibility of the actual revision
- Use visible previous revision instead

### Before

context menu item disabled

### After

context menu item enabled if there is shown a (virtual) parent

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
`GetActualRevision` feels kind of academic to me in the context of "Blame previous revision".
What information would it provide if it would be kept as an additional menu item?

File: src/app/GitUI/UserControls/BlameControl.cs [hunk 1]
```diff
@@ -644,16 +636,12 @@ private void blamePreviousRevisionToolStripMenuItem_Click(object sender, EventAr
...
             }
 
-            // Try get actual parent revision, get popup if it does not exist.
-            // (The menu should be disabled if previous is not in grid).
-            GitRevision selectedRevision = _revisionGridInfo!.GetActualRevision(blameInfo.selectedRevision);
-
             // Origin line of commit selected is final line of the previous blame commit
             int finalLineNumberOfPreviousBlame = _lastBlameLine!.OriginLineNumber;
-            int originalLineNumberOfPreviousBlame = _gitBlameParser.GetOriginalLineInPreviousCommit(selectedRevision, blameInfo.filename, finalLineNumberOfPreviousBlame);
+            int originalLineNumberOfPreviousBlame = _gitBlameParser.GetOriginalLineInPreviousCommit(blameInfo.selectedRevision, blameInfo.filename, finalLineNumberOfPreviousBlame);
```
Comment (gerhardol) [inline src/app/GitUI/UserControls/BlameControl.cs:641]: 0
This is the previous revision in grid.
I suggest this is separate or that the txt is changed.
Will not vote against though.

**Review by gerhardol — APPROVED** [review]
works fine, just suggest name changes

**Review by gerhardol — APPROVED** [review]
