### PR TITLE
Prevent clipping of environment info

### LINKED ISSUE #5666: FormAbout may clip text
**Do you want to request a *feature* or report a *bug*?**
layout regression

**What is the current behavior?**
image

**What is the expected behavior?**
All text is shown without clipping

**Environment you encounter the issue:**
master @ 970ea53081a782f6c6dedbf5b146a51c80fa1c7c
- Git Extensions 3.00.a1
- 970ea53081a782f6c6dedbf5b146a51c80fa1c7c  (Dirty)
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3163.0

**Did this work in previous version of GitExtensions (which)?**
yes

/cc: @vbjay - I think we can make the form slightly larger

### PR DESCRIPTION
**Pull request by vbjay**
Fixes #5666 

Changes proposed in this pull request:
- Removed exception because it blocked designer
- Added default info that fakes a sha and dirty status
- Resized form to not clip with sha and dirty status
 
Screenshots before and after (if PR changes UI):

image

image

What did I do to test the code and ensure quality:
- Ran program and made sure Dirty status with a sha would not wrap which caused clipping

Has been tested on (remove any that don't apply):

### CODE REVIEW

**Comment by vbjay** [comment]
Gee. Don't you think I might want to use valid data so anybody designing
the form would see the length of the string and see the clipping if they
resized the form.

File: GitUI/UserEnvironmentInformation.cs [hunk 1]
```diff
@@ -9,18 +9,13 @@ namespace GitUI
     public sealed class UserEnvironmentInformation
     {
         private static bool _alreadySet;
-        private static bool _dirty;
-        private static string _sha;
+        private static bool _dirty = true;
```
[the remark this answers is not in the document]
Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: Gee. Don't you think I might want to use valid data so anybody designing the form would see the length of the string and see the clipping if they resized the form. 
•••

[the remark this answers is not in the document]
Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: I actually do put some thought and why I do things. It sure seems like you doubt it. Yes. I do miss things sometimes. I do appreciate feedback but sometimes I think you and others don't believe it and act like we are idiots.

[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/UserEnvironmentInformation.cs]: For Designer specific, use specific tests:
https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.licensemanager.usagemode?redirectedfrom=MSDN&view=netframework-4.7.2#System_ComponentModel_LicenseManager_UsageMode

If you see a value like this, you wonder what the significance of the default value is. 
It is just hard to review.

[the remark this answers is not in the document]
Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: Reasons why I used those values
- Easy value to say hmmm  why am I seeing this value in runtime
- Includes Dirty state to include dirty status
- Includes characters and digits for font kerning issues.

[the remark this answers is not in the document]
Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: I chose not to do design checking because the control is loading the data from this source.  The source doesn't know about design time.  The source could be used in other places that don't know about design time.

[the remark this answers is not in the document]
Comment (drewnoakes) [reply GitUI/UserEnvironmentInformation.cs]: > Gee. Don't you think I might want to use valid data so anybody designing the form would see the length of the string and see the clipping if they resized the form.
>
> I actually do put some thought into why I do things. It sure seems like you doubt it. Yes. I do miss things sometimes. I do appreciate feedback but sometimes I think you and others don't believe it and act like we are idiots.

I think @gerhardol's question was reasonable. I see no indication that anyone is treating you disrespectfully Jay, and I feel others deserve that same respect from you. We are all here because we have chosen to be, so let's please keep it a nice place to hang out. Personally, I try to assume good intentions in others and am generally happier for it.

[the remark this answers is not in the document]
Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: I also didn't want a chance of changes to design checking to change the expected value. I expect the source to control the data always. If I did design checking we would have to maintain two sources. 

@drewnoakes sure. I get it. I just felt like he thought I  was just doing things half way or not thought out. Sometimes my implementation misses but I do try to come up with solutions that cover all the bases. 

@gerhardol. Sorry. I just felt like all my thought/work was just being treated as I just did some simple thing and wasn't thought out.

File: GitUI/UserEnvironmentInformation.cs [hunk 2]
```diff
@@ -9,18 +9,13 @@ namespace GitUI
...
+        private static string _sha = "9999999999999999999999999999999999abcdef";
 
         public static void CopyInformation() => Clipboard.SetText(GetInformation());
 
         public static string GetInformation()
         {
-            if (!_alreadySet)
```
Comment (RussKie) [inline GitUI/UserEnvironmentInformation.cs]: Let's keep the exception, but leverage `LicenseManager` and `IsUnitTestActive` constructs for design time and unit tests

https://github.com/gitextensions/gitextensions/blob/99e3c0f52da5cd79598d3ae4e8718390914dae01/GitUI/GitModuleForm.cs#L49-L56

Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: So to be clear. You want two sources of info. The design time check info and then the actual info from the info class.   So if the environment info class changes design time will show one thing and runtime another. I totally disagree and think it is foolish.

Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: I chose not to do design checking because the control is loading the data from this source.  The source doesn't know about design time.  The source could be used in other places that don't know about design time.

Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: Do you see the thought behind it now?  
image

As soon as you use design time checking you will now have two sources.  The code in UserEnvironmentInfo and then the design time code.  How about we not do that and have ONE source of info and be able to see the info so that when designing we know the form won't clip when resizing.

Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: If you ever see all 9's in runtime, then you know an issue has happened.  It's a red herring.

Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: Also.  Please try designing FormAbout in master.

Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: I altered the content of the source.  Added a new line   
image

If we used designtime checking the ui would still look the same in the design checked code because I didn't know there was another place to update the text for design.  With my way, as soon as gitgui is built designer will show the new info as it would come out in runtime.

Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: Right.  I need to resize form.  
image

Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: I think I just figured it out. I can have my cake and eat it too. 

```c#
If (design)
{
UserEnvironmentInformation.Initilise(redHerring,true);
}

```

Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: Trees meet forest. Ugh. I just didn't see how design checking was going to prevent duplicate sources. I'll get it fixed soon.

Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: Trees meet forest. Ugh. I just didn't see how design checking was going to prevent duplicate sources. I'll get it fixed soon.

**Comment by RussKie** [comment]
Thank you
