### PR TITLE
#4535 Reset folder in file tree regression in 2.51

### LINKED ISSUE #4535: "Restore to selected version" function is removed from 2.51
One of the most amazing features of Git extensions is removed from 2.51 version!

Previously in file tree I was able to do a right click on a folder and the first option was "Restore to selected version". For now there is no such feature.

I was urged to roll down to 2.50.2

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #4535

Changes proposed in this pull request:
Reset folder was not visible after #4165 and other PRs. In 2.50 it was possible to get various exceptions and irrelevant menu items.

Also, some other menu items were cleaned up in this PR

Screenshots before and after (if PR changes UI):
- 
image
image
image

image
image
image

What did I do to test the code and ensure quality:
 - Manual tests

Has been tested on (remove any that don't apply):
 - GIT 2.16
 - Windows 10

### CODE REVIEW

**Comment by pmiossec** [comment]
Please don't merge that. I disagree with the content and will try to find time tomorrow to comment (time to sleep at the moment ;-) and can't do it from smartphone)

**Comment by RussKie** [comment]
Sure, no probs
Thanks

File: GitUI/CommandsDialogs/RevisionFileTree.cs [hunk 1]
```diff
@@ -477,6 +477,7 @@ private void FileTreeContextMenu_Opening(object sender, System.ComponentModel.Ca
             var itemSelected = gitItem != null;
             var isFile = itemSelected && gitItem.ObjectType == GitObjectType.Blob;
             var isFolder = itemSelected && gitItem.ObjectType == GitObjectType.Tree;
+            var isFileOrFolder = isFile || isFolder;
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/RevisionFileTree.cs]: The items that are displayed are either files or folders, so, if you need this `File | Folder`, that means that the item should be always displayed.

File: GitUI/CommandsDialogs/RevisionFileTree.cs [hunk 2]
```diff
@@ -493,14 +494,13 @@ private void FileTreeContextMenu_Opening(object sender, System.ComponentModel.Ca
             }
 
             saveAsToolStripMenuItem.Visible = isFile;
-            resetToThisRevisionToolStripMenuItem.Visible = isFile && !Module.IsBareRepository();
-            toolStripSeparatorFileSystemActions.Visible = isFile;
+            resetToThisRevisionToolStripMenuItem.Visible = isFileOrFolder && !Module.IsBareRepository();
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/RevisionFileTree.cs]: ...so remove the `isFileOrFolder` here and everywhere.

File: GitUI/CommandsDialogs/RevisionFileTree.cs [hunk 3]
```diff
@@ -493,14 +494,13 @@ private void FileTreeContextMenu_Opening(object sender, System.ComponentModel.Ca
...
+            toolStripSeparatorFileSystemActions.Visible = isFileOrFolder;
 
-            fileHistoryToolStripMenuItem.Enabled = itemSelected;
             copyFilenameToClipboardToolStripMenuItem.Visible = itemSelected;
             fileTreeOpenContainingFolderToolStripMenuItem.Enabled = isExistingFileOrDirectory;
             fileTreeArchiveToolStripMenuItem.Enabled = itemSelected;
-            fileTreeCleanWorkingTreeToolStripMenuItem.Visible = isFolder;
+            fileTreeCleanWorkingTreeToolStripMenuItem.Visible = isFileOrFolder;
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/RevisionFileTree.cs]: either if I miss something but you could clean a working tree, lony if the item is a folder, no!?! So I think it is not good. You should keep `isFolder`.

File: GitUI/CommandsDialogs/RevisionFileTree.cs [hunk 4]
```diff
@@ -513,14 +513,13 @@ private void FileTreeContextMenu_Opening(object sender, System.ComponentModel.Ca
...
 
             toolStripSeparatorGitActions.Visible = isFile;
-            stopTrackingThisFileToolStripMenuItem.Visible = isFile;
-            stopTrackingThisFileToolStripMenuItem.Enabled = isExistingFileOrDirectory;
-            assumeUnchangedTheFileToolStripMenuItem.Visible = isFile;
-            assumeUnchangedTheFileToolStripMenuItem.Enabled = isExistingFileOrDirectory;
+            stopTrackingThisFileToolStripMenuItem.Visible = 
+                stopTrackingThisFileToolStripMenuItem.Enabled = isFile;
+            assumeUnchangedTheFileToolStripMenuItem.Visible = 
+                assumeUnchangedTheFileToolStripMenuItem.Enabled = isFile;
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/RevisionFileTree.cs]: this is wrong! The use of `assume unchanged` feature has only sense when the file has not changed. So what was done was good. Please revert.

File: GitUI/CommandsDialogs/RevisionFileTree.cs [hunk 5]
```diff
@@ -493,14 +494,13 @@ private void FileTreeContextMenu_Opening(object sender, System.ComponentModel.Ca
             }
 
             saveAsToolStripMenuItem.Visible = isFile;
-            resetToThisRevisionToolStripMenuItem.Visible = isFile && !Module.IsBareRepository();
-            toolStripSeparatorFileSystemActions.Visible = isFile;
+            resetToThisRevisionToolStripMenuItem.Visible = isFileOrFolder && !Module.IsBareRepository();
+            toolStripSeparatorFileSystemActions.Visible = isFileOrFolder;
 
-            fileHistoryToolStripMenuItem.Enabled = itemSelected;
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/RevisionFileTree.cs]: I don't understand the meaning of this change... Could you explain?

File: GitUI/CommandsDialogs/RevisionFileTree.cs [hunk 6]
```diff
@@ -513,14 +513,13 @@ private void FileTreeContextMenu_Opening(object sender, System.ComponentModel.Ca
             openFileWithToolStripMenuItem.Visible = isFile;
 
             toolStripSeparatorGitActions.Visible = isFile;
-            stopTrackingThisFileToolStripMenuItem.Visible = isFile;
-            stopTrackingThisFileToolStripMenuItem.Enabled = isExistingFileOrDirectory;
-            assumeUnchangedTheFileToolStripMenuItem.Visible = isFile;
-            assumeUnchangedTheFileToolStripMenuItem.Enabled = isExistingFileOrDirectory;
+            stopTrackingThisFileToolStripMenuItem.Visible = 
+                stopTrackingThisFileToolStripMenuItem.Enabled = isFile;
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/RevisionFileTree.cs]: Not good, too... If the file has been deleted or renamed, no need of this feature because that is done normally or more easily from the commit form.
You only want to use this feature if you want to keep the file (so don't see it in the commit form) and stop track it. So, you should keep the `isExistingFileOrDirectory` condition. So should be reverted.

File: GitUI/CommandsDialogs/RevisionFileTree.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionFileTree.cs]: Does not include submodules, so relevant

File: GitUI/CommandsDialogs/RevisionFileTree.cs (hunk 6 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionFileTree.cs]: ok

File: GitUI/CommandsDialogs/RevisionFileTree.cs (hunk 4 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionFileTree.cs]: ok

File: GitUI/CommandsDialogs/RevisionFileTree.cs (hunk 1 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/RevisionFileTree.cs]: We have submodules as well. Does it matter?

File: GitUI/CommandsDialogs/RevisionFileTree.cs (hunk 5 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionFileTree.cs]: Can revert. The check is not really needed, the other checks are to avoid exceptions when the menu is opening without selections (which could happen, not easy to reproduce).

File: GitUI/CommandsDialogs/RevisionFileTree.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionFileTree.cs]: For instance, clean on Submodules has no effect, is FileOrFolder does not apply there

File: GitUI/CommandsDialogs/RevisionFileTree.cs (hunk 3 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionFileTree.cs]: If you clean on a file, you clean the directory, so it works. Clean-on-files was working like that in 2.50 but I agree the functionality is weird.

**Comment by gerhardol** [comment]
@pmiossec Are you OK with the changes?

**Comment by pmiossec** [comment]
Sorry, didn't had the time to review it.
I hope to be able to do it tomorrow

**Comment by RussKie** [comment]
@gerhardol could you please send the same to 2.51 branch?
