### PR TITLE
Better exception presentation

### LINKED ISSUE #7795: Generic handling of failure to start a process
## Current behaviour

#7714 wraps `Process.Start` in `try { } catch (Exception ex) { MessageBox.Show() }`.

## Expected behaviour

We should replace all instances of `Process` with a generic wrapper -- at least all calls to `Process.Start`.
Related to #6527.
Abstraction for `MessageBox.Show` should be used: https://github.com/gitextensions/gitextensions/issues/7751#issuecomment-589867209.

### PR DESCRIPTION
**Pull request by RussKie**
Contributes to #7795

## Proposed changes

Trap and route as many exceptions as possible to the central handler.

For exceptions coming from the main thread it is possible to ignore those and continue the app's execution, but for unhandled exceptions coming from background threads the app will terminate.
The main focus of this work is to intercept exceptions originated from `Executable` (i.e. executing git commands, etc.), and user scripts. However it is not limited in this scope.

- An alternative simplified proposal for https://github.com/gitextensions/gitextensions/pull/8278.

### Before

grafik

### After

* Settings
image

* Script
image

* An arbitrary exception (reported in https://github.com/gitextensions/gitextensions/issues/8367)
image

* An arbitrary exception (reported in https://github.com/gitextensions/gitextensions/issues/8647)
image
Hitting "ignore" will close the app anyway, since the repo is gone. I'm not sure what the expect UX would be in this situation...

### CODE REVIEW

**Comment by RussKie** [comment]
@mstv pumping up on your radar, interested in your thoughts (when you have time).

**Comment by mstv** [comment]
I have not forgot this but been caught in recent discussions yet.

**Comment by mstv** [comment]
I haven't reviewed in detail because basic questions / comments arose quickly:

Which commits of my PR have you taken into account?

Which of my proposed changes do you disagree on?

I already gave the reasonable for starting an exception hierarchy:
> `ExecutableException` is derived from the new `ExternalOperationException` (planned to be used for file operations etc. in a follow-up PR)

Just give a short answer and let me rethink, please.

**Comment by RussKie** [comment]
> Which commits of my PR have you taken into account?
> 

I looked at your proposed changes, and certainly drawn an inspiration from those.

> Which of my proposed changes do you disagree on?

This changeset is significantly smaller, and IMO achieves the same outcome - i.e. traps failures and presents them to a user in a usable (or more useable than now) manner.
Certainly this change wasn't as exhaustive in terms of updating all `Executable` callsites, but even with those I expect the scope to still be smaller.

I don't like adding extra infra plumbing such as factories, and additional exception layers. At this stage I don't see any immediate need for those.

> `ExecutableException` is derived from the new `ExternalOperationException` (planned to be used for file operations etc. in a follow-up PR)

Let's do one step at a time please. In my experience quite often after making the first step things (like design or requirements) change, but the "future-proofed code" never gets removed.

**Comment by mstv** [comment]
> > Which commits of my PR have you taken into account?

> I looked at your proposed changes, and certainly drawn an inspiration from those.

That wasn't my question. See next point.

> > Which of my proposed changes do you disagree on?

> This changeset is significantly smaller, and IMO achieves the same outcome - i.e. traps failures and presents them to a user in a usable (or more useable than now) manner.

#7795: "We should replace **all** instances of `Process` with a generic wrapper".
Maybe this was not clear enough. This means "instead of bloating all the callsites with `try { }  catch { ShowError }`.

#8278: "show **every** `ExternalOperationException` to the user **when it is created** in order to avoid silent errors eaten by too generic `catch`"

(Special cases require exceptions / extensions of this rule: finding the git executable, script execution.)

> Certainly this change wasn't as exhaustive in terms of updating all `Executable` callsites, but even with those I expect the scope to still be smaller.

I want a generic solution. Every external operation can fail (process execution or just filesystem access). Usually this is not a bug of GE. So let's ensure the user gets the exact error message and avoid NBug reports.

> I don't like adding extra infra plumbing such as factories, and additional exception layers. At this stage I don't see any immediate need for those.

See above. In addition, `ExternalOperationException.Handled` is a different aspect than the process-specific context information (SRP). Though `Command` and `WorkingDirectory` could be re-used for filesystem errors. Or else we can create an `IContext` abstraction instead of an exception hierarchy -- of course only if necessary and in a follow-up PR.

> in a usable (or more useable than now) manner.

Regarding `TaskDialog`: We agreed on waiting for .Net Core 5 before replacing `MessageBox` with TD because of API changes (remember the discussion on magic numbers, which seem to be not needed anymore?).

File: GitCommands/Git/Executable.cs [hunk 1]
```diff
@@ -98,9 +98,16 @@ public ProcessWrapper(string fileName, string arguments, string workDir, bool cr
...
-
-                _logOperation.SetProcessId(_process.Id);
+                try
+                {
+                    _process.Start();
+                    _logOperation.SetProcessId(_process.Id);
+                }
+                catch (Exception ex)
+                {
+                    _logOperation.LogProcessEnd(ex);
```
Comment (wischi-chr) [inline GitCommands/Git/Executable.cs:108]: If an exception is thrown here the object is never initialized and thus Dispose won't happen. Disposing before rethrowing should fix that.

**Comment by ivangrek** [comment]
How about using status bar notifications instead of a dialog box?

image

As far as I understand, we provide an opportunity, not a necessity. The window causes rejection, the requirement to perform an action.

**Comment by RussKie** [comment]
That's an interesting idea.
It kind of crossed my mind few times.
Though I think it may create a somewhat disjoint UX. I wouldn't do it as
part of this PR, but certainly something to consider.

**Comment by ivangrek** [comment]
Pay attention to this method.
Should it catch all exceptions?

```
private bool InvokeEvent([CanBeNull] IWin32Window ownerForm, [CanBeNull] EventHandler<GitUIEventArgs> gitUIEventHandler)
{
    try
    {
        var e = new GitUIEventArgs(ownerForm, this);
        gitUIEventHandler?.Invoke(this, e);
        return !e.Cancel;
    }
    catch (Exception ex)
    {
        MessageBox.Show(ex.Message, "Exception", MessageBoxButtons.OK, MessageBoxIcon.Error);
    }

    return true;
}
```

**Comment by RussKie** [comment]
@mstv I've just discovered that the proposed "ignore and continue" won't work as one may expect - the app will be terminated if an exception has come from a non-UI thread, which is routed through [`AppDomain.CurrentDomain.UnhandledException`](https://docs.microsoft.com/dotnet/api/system.appdomain.unhandledexception#remarks):
image

This is easily reproducible in both your work and mine by going to Settings > Git > Paths and modifying the git path:
image
Choosing to "ignore" will kill the app.

There is no easy way out of this, we'll need to catch all exceptions occurring on non-UI thread, and marshal them to the main thread.

There's also another annoyance as well - exceptions thrown in the `AsyncLoader` aren't trappable nor they get routed to `AppDomain.CurrentDomain.UnhandledException`. I had a brief investigation but I couldn't see anything obvious.
An easy way to repro this is to modify "status" to "status 1" in `GetAllChangedFilesCmd` method, set the breakpoint as follows and open the `FormCommit`:
image
This exception will not surface in anyway, and the form will have an endless spinner...

I'm not expecting or proposing these issues to be addressed as part of this work, just wanted to raise them up.

**Comment by ivangrek** [comment]
Most likely we will have to forward async to the top or wrap the method call in ThreadHelper.JoinableTaskFactory.Run.

**Comment by ivangrek** [comment]
Maybe we should move ThreadHelper.JoinableTaskFactory.Run to the UI only.

**Comment by RussKie** [comment]
For now in unhandled exceptions situations (those that are coming from non-UI thread) I propose we do this:
image

And we'll gradually need to clean up the exceptions and their routing.

**Review by mstv — COMMENTED** [review]
This PR improves the behavior significantly and catches some important special cases, e.g. `IsTerminating`. 👍
But it does not solve #7795 completely. So please remove "fixes" from the PR description.

Furthermore, I do not share your opinion to trust the GE code: It has grown too much -- with the wrong attitude regarding error handling / swallowing.

I am still quite busy in RL. Though I could implement the changes requested by me if you like (and agree to them mainly 😉).

**Comment by gerhardol** [comment]
This PR has one big (small?) problem: The new popup is smaller than a terminal window.
Together with ConEmu pop-over (#6220) and something like #8658 it seems like GE is hanging when it it is just the modal popup waiting for input.
Maybe change the position for the popup?

Sidenote: I happen to believe that Git error handling was included in one of the error presentation PRs.
That is separate though. The Git handling do currently not check the output status, it also merges the stdout and stderr streams.

**Comment by RussKie** [comment]
I'm super busy at work, but I will read the feedback and respond as soon as
I can.

Thank you

File: GitCommands/Git/ExternalOperationException.cs [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+        /// <summary>
+        /// Initializes a new instance of the <see cref="ExternalOperationException"/> class with a specified parameters
+        /// and a reference to the inner exception that is the cause of this exception.
+        /// </summary>
+        /// <param name="command">The command that led to the exception.</param>
+        /// <param name="arguments">The command arguments.</param>
+        /// <param name="workingDirectory">The working directory.</param>
+        /// <param name="innerException">The exception that is the cause of the current exception.</param>
+        public ExternalOperationException(string command, string arguments, string workingDirectory, Exception innerException)
+            : base(null, innerException)
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/Git/ExternalOperationException.cs:22]: Good catch

File: GitUI/NBugReports/BugReporter.cs [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+                // Something happened either in the app - can submit the bug to GitHub
+                ReportAppException(externalException, isTerminating);
+                return;
+            }
+
+            // Report any other exceptions
+            ReportGenericException(ex, isTerminating);
+        }
+
+        private static void ReportAppException(ExternalOperationException ex, bool isTerminating)
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitUI/NBugReports/BugReporter.cs:31]: Used NRT annotations instead.

File: GitCommands/Git/UserExternalOperationException.cs [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+    {
+        /// <summary>
+        /// Initializes a new instance of the <see cref="UserExternalOperationException"/> class with a specified parameters
+        /// and a reference to the inner exception that is the cause of this exception.
+        /// </summary>
+        /// <param name="command">The command that led to the exception.</param>
+        /// <param name="arguments">The command arguments.</param>
+        /// <param name="workingDirectory">The working directory.</param>
+        /// <param name="innerException">The exception that is the cause of the current exception.</param>
+        public UserExternalOperationException(string command, string arguments, string workingDirectory, Exception innerException)
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/Git/UserExternalOperationException.cs:20]: I don't think we can do this without breaking the hierarchy: `public class UserExternalOperationException : ExternalOperationException`.
In order to initialise the exception we need to pass args to the base class, and we only use `context` we won't have information to pass.

Likewise in event where we use this exception, we no longer interested in the original `ExternalOperationException`, but interested in the underlying exception that triggered the sequence:
```cs
catch (ExternalOperationException ex)
{
    throw new UserExternalOperationException(ex.Command, ex.Arguments, ex.WorkingDirectory, ex.InnerException ?? ex);
}
```

File: GitUI/NBugReports/BugReporter.cs [hunk 5]
```diff
@@ -0,0 +1,141 @@
...
+                Cancelable = true,
+            };
+            var btnIgnoreOrClose = new TaskDialogCommandLink("IgnoreOrClose", isTerminating ? Strings.ButtonCloseApp : Strings.ButtonIgnore);
+            btnIgnoreOrClose.Click += (s, e) =>
+            {
+                dialog.Close();
+            };
+            dialog.Controls.Add(btnIgnoreOrClose);
+
+            dialog.Show();
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitUI/NBugReports/BugReporter.cs:87]: Refactored

**Comment by RussKie** [comment]
> Together with ConEmu pop-over (#6220) and something like #8658 it seems like GE is hanging when it it is just the modal popup waiting for input.
> Maybe change the position for the popup?

In the final version I have reworked owner form handling, so it should have a better chance of setting a popup as the top most window, and thus it shouldn't get lost.

**Comment by gerhardol** [comment]
> In the final version I have reworked owner form handling, so it should have a better chance of setting a popup as the top most window, and thus it shouldn't get lost.

It was harder to recreate #8658 now, maybe after #8679

**Review by gerhardol — COMMENTED** [review]
Changes work for me
I prefer to take this and move on, maybe adjust later
But I would like @mstv to approve

File: GitCommands/Git/UserExternalOperationException.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (mstv) [reply GitCommands/Git/UserExternalOperationException.cs:20]: The /  my goal is to avoid all those redundant lengthy `catch` blocks and to provide information about the top-level operation.

```
public UserExternalOperationException(string context, ExternalOperationException ex)
    : base(ex.Command, ex.Arguments, ex.WorkingDirectory, ex.InnerException)
{
    Context = context;
}

foo()
{
    try
    {
         ...
    }
    catch (ExternatlOperationException ex)
    {
        throw new UserExternalOperationException("context information", ex);
    }
}
```

**Comment by mstv** [comment]
This PR does not solve #7795 completely. So please remove "fixes" from the PR description.

The discussion about `UserExternalOperationException` and context information should be finished before the merge.

The other minor comments on nested exceptions, refactorings and the application to `MessageBoxes.FailedToRunShell` can be done in follow-up PRs.

**Comment by gerhardol** [comment]
> > Together with ConEmu pop-over (#6220) and something like #8658 it seems like GE is hanging when it it is just the modal popup waiting for input.
> > Maybe change the position for the popup?
> 
> In the final version I have reworked owner form handling, so it should have a better chance of setting a popup as the top most window, and thus it shouldn't get lost.

I could recreate it once, the popup was over the console in my scenario.

File: GitUI/Script/ScriptRunner.cs [hunk 6]
```diff
@@ -34,29 +34,29 @@ public static CommandStatus RunScript(IWin32Window owner, IGitModule module, str
...
 
-            var scriptInfo = ScriptManager.GetScript(scriptKey);
+            ScriptInfo scriptInfo = ScriptManager.GetScript(scriptKey);
             if (scriptInfo is null)
             {
-                showError("Cannot find script: " + scriptKey);
-                return false;
+                ThreadHelper.AssertOnUIThread();
+                throw new UserExternalOperationException($"{Strings.ScriptErrorCantFind}: '{scriptKey}'",
+                    new ExternalOperationException(command: null, arguments: null, module.WorkingDir, innerException: null));
```
Comment (RussKie) [inline GitUI/Script/ScriptRunner.cs:59]: ge-script-notfound

File: GitUI/Script/ScriptRunner.cs [hunk 7]
```diff
@@ -72,12 +72,15 @@ string optionDependingOnSelectedRevision
                                                                         && ScriptOptionsParser.Contains(arguments, option));
                 if (optionDependingOnSelectedRevision is object)
                 {
-                    showError($"Option {optionDependingOnSelectedRevision} is only supported when started with revision grid available.");
-                    return false;
+                    ThreadHelper.AssertOnUIThread();
+                    throw new UserExternalOperationException($"{Strings.ScriptText}: '{scriptKey}'{Environment.NewLine}'{optionDependingOnSelectedRevision}' {Strings.ScriptErrorOptionWithoutRevisionGridText}",
+                        new ExternalOperationException(scriptInfo.Command, arguments, module.WorkingDir, innerException: null));
```
Comment (RussKie) [inline GitUI/Script/ScriptRunner.cs:77]: ge-script-norg

File: GitUI/Script/ScriptRunner.cs [hunk 8]
```diff
@@ -86,8 +89,9 @@ string optionDependingOnSelectedRevision
             (string argument, bool abort) = ScriptOptionsParser.Parse(scriptInfo.Arguments, module, owner, revisionGrid);
             if (abort)
             {
-                showError($"There must be a revision in order to substitute the argument option(s) for the script to run.");
-                return false;
+                ThreadHelper.AssertOnUIThread();
+                throw new UserExternalOperationException($"{Strings.ScriptText}: '{scriptKey}'{Environment.NewLine}{Strings.ScriptErrorOptionWithoutRevisionText}",
+                    new ExternalOperationException(scriptInfo.Command, arguments, module.WorkingDir, innerException: null));
```
Comment (RussKie) [inline GitUI/Script/ScriptRunner.cs:94]: ge-script-norev

File: Directory.Build.props [hunk 9]
```diff
@@ -2,7 +2,7 @@
   <Import Project=".\scripts\sdk\Sdk.props" />
 
   <PropertyGroup>
-    <LangVersion>8</LangVersion>
+    <LangVersion>9</LangVersion>
```
Comment (gerhardol) [inline Directory.Build.props:5]: So support for C# 9.0 added
(Requires Visual Studio 16.8 which should be OK.)
Do you have a list what features that are supported with .NET 4 framework?

**Review by mstv — APPROVED** [review]
Thank you.

File: Directory.Build.props (hunk 9 above)
Comment (RussKie) [reply Directory.Build.props]: This actually not required, I was tinkering with something else.
Nullable annotations came with C# 8.0.
