### PR TITLE
Avoid obtaining locks for git-status in the background

### LINKED ISSUE #5066: Git-status in the background should use --no-optional-locks
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Git-status also running in the background can conflict with interactive commands.
The best solution would be to run git-status in only the background, but that will require some tweaking to the rules, so that interactive git-status can use the background status without too much delay.
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not easy to reproduce, requires that git-status is slow and interactive git-status is started while background command is running.

**What is the expected behavior?**
git-status in the background should not block interactive commands.
Git 2.15.2 adds support for --no-optional-locks

**Environment you encounter the issue:**

- GitExtensions version: all

**Did this work in previous version of GitExtensions (which)?**
no

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #5066
To be submitted for 2.51 too.

Changes proposed in this pull request:
- Use --no-optional-locks for git-status related to the commit count to avoid blocking interactive commands
 
Screenshots before and after (if PR changes UI):
- n/a

What did I do to test the code and ensure quality:
- Manual tests

Has been tested on (remove any that don't apply):
- GIT 2.17.1
- Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
Do we want to apply the same to 2.51 branch as well?

File: GitCommands/Git/GitCommandHelpers.cs [hunk 1]
```diff
@@ -677,10 +677,11 @@ public static string CleanUpCmd(bool dryrun, bool directories, bool nonignored,
             return args.ToString();
         }
 
-        public static string GetAllChangedFilesCmd(bool excludeIgnoredFiles, UntrackedFilesMode untrackedFiles, IgnoreSubmodulesMode ignoreSubmodules = IgnoreSubmodulesMode.None)
+        public static string GetAllChangedFilesCmd(bool excludeIgnoredFiles, UntrackedFilesMode untrackedFiles, IgnoreSubmodulesMode ignoreSubmodules = IgnoreSubmodulesMode.None, bool noLocks = false)
         {
             var args = new ArgumentBuilder
             {
+                { noLocks && VersionInUse.SupportNoOptionalLocks, "--no-optional-locks" },
```
Comment (RussKie) [inline GitCommands/Git/GitCommandHelpers.cs]: I would remove `VersionInUse.SupportNoOptionalLock` from here and move it to:
`string command = GitCommandHelpers.GetAllChangedFilesCmd(..., VersionInUse.SupportNoOptionalLocks);`

Comment (gerhardol) [reply GitCommands/Git/GitCommandHelpers.cs]: This is a guard to not include illegal options for a certain Git version, so it definetly belongs here.
Similar for other VersionInUse.

**Comment by gerhardol** [comment]
> Do we want to apply the same to 2.51 branch as well?

That is the plan

File: GitCommands/Git/GitCommandHelpers.cs (hunk 1 above)
Comment (RussKie) [reply GitCommands/Git/GitCommandHelpers.cs]: From SR principle POV, this is a command builder and should be agnostic of git version. The onus is on the caller to supply correct parameters.
This way we can test the implementation.

Comment (gerhardol) [reply GitCommands/Git/GitCommandHelpers.cs]: Then we need to add another layer above the command builder, to check that the arguments are OK for the Git version in use.
Changes need to be done to maybe 10 different places.

**Comment by RussKie** [comment]
Why? The parameter is driven by the "is supported" flag....

File: GitCommands/Git/GitCommandHelpers.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Git/GitCommandHelpers.cs]: > Why? The parameter is driven by the "is supported" flag....

I do not trust the client/application (in this case GitStatusMonitor) to only request valid options. This is extremely hard to review and test. (Is anyone explicitly testing older Git versions?) The server/command handler must check the arguments. This can be done outside the command builder, but still need to be done in GetAllChangedFilesCmd(). The argument builder can be moved to a separate function if that simplifies testing.
