### PR TITLE
GitRef: Remote may be as long as Name

### LINKED ISSUE #9338: [NBug] startIndex cannot be larger than length of string.Paramet...
## Current behaviour

I right click on commit 'git-svn' (321a14e6617ede932ecdffb4c9532eda67cc85c1) in repo: https://github.com/duralf/yabe.git and press 'Create new branch here' and get this exception.

## Expected behaviour
A popup shows up and allows for creating a branch.

## Steps to reproduce

See current behaviour. It may possibly be related to git svn.

## Error Details
```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at GitCommands.GitRef.get_LocalName()
   at GitUI.CommandsDialogs.FormCreateBranch..ctor(GitUICommands commands, ObjectId objectId, String newBranchNamePrefix)
   at GitUI.RevisionGridControl.<>c__DisplayClass173_0.<CreateNewBranchToolStripMenuItemClick>b__0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent, Func`1 action)
   at GitUI.RevisionGridControl.CreateNewBranchToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I right-clicked a commit and pressed create branch here. Crashes in version 3.5.1 as well

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #9338 

## Proposed changes

Check string length before using a substring.
Use full Name if not possible to remove the Remote prefix.

For the FormCreateBranch example, this may return an unexpected name, but that is just a suggestion for the user anyway.
Similar effects for a few other random usages I saw.
So this should be safe.

## Test methodology 

Code review

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]
👍 
Can you please add a regression test for this?

File: GitCommands/Git/GitRef.cs [hunk 1]
```diff
@@ -126,7 +126,7 @@ string ParseName()
 
         public bool IsOther => !IsHead && !IsRemote && !IsTag;
 
-        public string LocalName => IsRemote ? Name.Substring(Remote.Length + 1) : Name;
+        public string LocalName => IsRemote && Name.Length > Remote.Length + 1 ? Name.Substring(Remote.Length + 1) : Name;
```
Comment (mstv) [inline GitCommands/Git/GitRef.cs:129]: OK - but perhaps ❔
```suggestion
        public string LocalName => IsRemote && Name.StartsWith($"{Remote}/") ? Name.Substring(Remote.Length + 1) : Name;
```

Comment (gerhardol) [reply GitCommands/Git/GitRef.cs]: I thought about that too. A good enough reason is that the testcases and names were weird.
So I changed this instead of answering any issues tonight.

Unless there are objections, I plan to squash merge tomorrow or so.

**Review by mstv — APPROVED** [review]

File: GitCommands/Git/GitRef.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Git/GitRef.cs]: Renamed the testcases some more, no other changes
