### PR TITLE
Added multithreading test and fixed issues

### LINKED ISSUE #5703: System.ArgumentException when loading graph
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When openeing or refreshing a repo, NBug may popup with the following:
System.ArgumentException
An item with the same key has already been added.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Appears for a certain repo, not general

**What is the expected behavior?**
Load the graph normally

**Environment you encounter the issue:**

- Git Extensions 3.00.00.02-rc1
- 7990325547dd27e6a3fc1eaccee2607bbce66222  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3190.0

**Did this work in previous version of GitExtensions (which)?**
Appeared a few times last weeks in custom builds based on master+misc branches

### PR DESCRIPTION
**Pull request by spdr870**
Fixes #5703 

Changes proposed in this pull request:
- Added a brute-force multithreading unit test. It has parameters that can set to larger numbers to run locally. On the normal testruns it will do some smoke-tests.
- Fixed some threading issues. I added comments in the code where threading issues appeared and what the fix is.
 
What did I do to test the code and ensure quality:
- Unit testing
- Manual testing

Has been tested on (remove any that don't apply):
- GIT 2.18
- Windows 10

### CODE REVIEW

**Comment by sharwell** [comment]
I'd like to revisit the type in question along with its expected behavior in multi-threaded applications.

**Comment by spdr870** [comment]
> I'd like to revisit the type in question along with its expected behavior in multi-threaded applications.

I don't what you mean by this?

**Comment by sharwell** [comment]
@spdr870 I am hoping to come back and review this, but haven't had the chance yet. Since the issue concerns multithreaded code, one thing I like to do is code review the class and attempt to find race conditions in code review. I then compare my findings with the pull request to see if the concerns addressed by the pull request are the same or different.

**Comment by spdr870** [comment]
@sharwell Thanks!

**Comment by spdr870** [comment]
I did a small change to replace the boolean used to mark the rowcache as dirty. This is replaced by a runtime check. The runtime check is smarter, it knows when a rebuild is needed. Before a rebuild was always triggered if the order of any item was changed, even if it wasn't processed yet. This simplifies the logic a bit. Also, the cache is not rebuild as often anymore.

This can be done in a seperate PR, but since it might help for the review I pushed it here.

**Comment by spdr870** [comment]
At work I have seen ArgumentException multiple times. You need a repository that is fragmented, then hit f5 a couple of times. With this patch I cannot simulate it.
image

File: UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+using GitUI.UserControls.RevisionGrid.Graph;
+using GitUIPluginInterfaces;
+using NUnit.Framework;
+
+namespace GitUITests.UserControls.RevisionGrid
+{
+    // This is a brute force, worst case,  thread safety test. What is does:
+    // - Load revisions from git in a random order. No topo-order. To ensure the biggest possible threading issues.
+    // - Build revision graph in another thread. This will almost impossible, since the order of the revisions constantly changes.
+    // - Keep rendering all the stuff that is or isn't available. More threading horror.
```
Comment (RussKie) [inline UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs]: 🤣

File: UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+    [TestFixture]
+    public class RevisionGraphMultiThreadingTests
+    {
+        // Number of times to repeat the cycle. Each cycle, the number of revisions increases.
+        // It is usefull to repeat the threads, because it will make sure all threads are started at the same time.
```
Comment (RussKie) [inline UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs]:
```suggestion
        // It is useful to repeat the threads, because it will make sure all threads are started at the same time.
```

File: UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+        // Otherwise, the revision loading is long finished and the rendering is still running
+        // Advise: set this number to 50 for thread safety test
```
Comment (RussKie) [inline UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs]:
```suggestion
        // Advice: set this number to 50 for thread safety test
```

File: UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+        private const int _numberOfRepeats = 10;
+
+        // Increase this number to create a larger test set.
+        // Advise: set this number to 1000 for thread safety test
```
Comment (RussKie) [inline UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs]:
```suggestion
        // Advice: set this number to 1000 for thread safety test
```

File: UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs (hunk 1 above)
Comment (spdr870) [reply UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs]: 👍

**Comment by spdr870** [comment]
Just pushed code changes after review and squashed commits.

**Comment by RussKie** [comment]
@sharwell waiting for your signal.

File: GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs [hunk 5]
```diff
@@ -102,7 +103,7 @@ private void BuildSegmentLanes()
                         // Segment has not been assigned a lane yet
                         if (!added)
                         {
-                            newSegmentLanes.Add(segment, laneIndex);
+                            newSegmentLanes[segment] = laneIndex;
```
Comment (gerhardol) [inline GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs]: This has hit me a couple of times - fixed before I could report or investigate!

Comment (spdr870) [reply GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs]: This is not the cause of the problem. I fixed the cause in this PR. After the other changes, I never got an argument exception anymore. But this is ok. There are other guards that validate if something goes wrong.

**Comment by RussKie** [comment]
@sharwell I'm merging as is for RC2. 
If/when you have some time please let us know if anything needs changing.
