### PR TITLE
Commit: Unstage new files did not display the worktree file

### LINKED ISSUE #9280: Broken hunks stage/unstage for new files
## Current behaviour

It is not possible to stage/unstage selected lines for new files.

## Expected behaviour

It is possible to stage/unstage selected lines for new files.

## Steps to reproduce

1. Create a new file with content
2. Select few lines and try to stage
    \- or -
Stage the file, select few lines and try to unstage

## Screenshots

image

## Did this work in previous version of GitExtensions

Yes, 3.4
image

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.29.2.windows.2 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #9283: FormCommit: `FileStatusList` not refreshed correctly
## Steps to reproduce

In FormCommit:
- Stage lines of a new file (or change it after staging a draft)

grafik

- Unstage the file

### Current behaviour

File is shown as changed without contents.

grafik

## Expected behaviour

File is shown as new file with contents (as after refresh):

grafik

## Did this work in previous version of GitExtensions

?

## Environment

- Git Extensions 33.33.33
- Build eddb5e332bd8dc0cd483d2f17d874ecc1b4013a3 (current master)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 5.0.6
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #9283

## Proposed changes

The git status was not updated correctly for new files in the index
that also were changed in the worktree. The worktree file could therefore
not be displayed.

## Screenshots 

See issue

## Test methodology 

Manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 1]
```diff
@@ -1744,20 +1744,7 @@ private void Unstage(bool canUseUnstageAll = true)
...
-
-                        if (item.IsNew && !item.IsChanged && !item.IsDeleted)
-                        {
-                            item.IsTracked = false;
-                        }
-                        else
-                        {
-                            item.IsTracked = true;
-                        }
+                        item.IsTracked = item.IsNew && !item.IsChanged && !item.IsDeleted ? false : true;
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormCommit.cs:1747]:
```suggestion
                        item.IsTracked = !item.IsNew || item.IsChanged || item.IsDeleted;
```

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 2]
```diff
@@ -1744,20 +1744,7 @@ private void Unstage(bool canUseUnstageAll = true)
                             continue;
                         }
 
-                        var item2 = item;
-                        if (unstagedFiles.Exists(i => i.Name == item2.Name))
-                        {
-                            continue;
-                        }
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormCommit.cs:1751]: Just curious: What was the purpose of the cloned identifier `item2`, which was not used somewhere else?

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 3]
```diff
@@ -1778,7 +1765,16 @@ private void Unstage(bool canUseUnstageAll = true)
                         }
 
                         item.Staged = StagedStatus.WorkTree;
-                        unstagedFiles.Add(item);
+                        int index = unstagedFiles.FindIndex(i => i.Name == item.Name);
+
+                        if (index >= 0)
+                        {
+                            unstagedFiles[index] = item;
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormCommit.cs:1772]: This is not correct for the (constructed) opposite use case:
- change a file
- stage it
- delete it
- unstage

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormCommit.cs:1751]: Should probably have been removed in a refactoring...

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormCommit.cs:1747]: ok

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 3 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormCommit.cs:1772]: will need a change

Comment (gerhardol) [reply GitUI/CommandsDialogs/FormCommit.cs]: That case was not handled correctly before either. With the modification, the status is seemingly correct when unstaging, but the worktree status is still deleted.
The problem is in GitModule.cs BatchUnstageFiles()
Ignoring for the moment

Comment (mstv) [reply GitUI/CommandsDialogs/FormCommit.cs]: I agree, the remaining is a very minor issue, which is not worth fixing IMO because the diff is displayed correctly.

**Review by mstv — APPROVED** [review]
Thank you
