### PR TITLE
fix: Restrict settings to "global" when not in a repository

### LINKED ISSUE #11907: [NBug] Value cannot be null. (Parameter 'targetName')
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.ArgumentNullException: Value cannot be null. (Parameter 'targetName')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at GitExtensions.Extensibility.Settings.CredentialsManager.SetCredentials(SettingLevel settingLevel, String name, NetworkCredential value) in C:\projects\gitextensions\src\app\GitExtensions.Extensibility\Settings\CredentialsManager.cs:line 69
   at GitExtensions.Extensibility.Settings.CredentialsSetting.SaveValue(SettingsSource settings, String userName, String password) in C:\projects\gitextensions\src\app\GitExtensions.Extensibility\Settings\CredentialsSetting.cs:line 42
   at GitExtensions.Extensibility.Settings.CredentialsSetting.CredentialsControlBinding.SaveSetting(SettingsSource settings, CredentialsControl control) in C:\projects\gitextensions\src\app\GitExtensions.Extensibility\Settings\CredentialsSetting.cs:line 86
   at GitExtensions.Extensibility.Settings.SettingControlBinding`2.SaveSetting(SettingsSource settings) in C:\projects\gitextensions\src\app\GitExtensions.Extensibility\Settings\SettingControlBinding.cs:line 42
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.PageToSettings() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\SettingsPageBase.cs:line 123
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SaveSettings() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\SettingsPageBase.cs:line 110
   at GitUI.CommandsDialogs.FormSettings.Save() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 233
   at GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 324
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

Tentative de set de jira commit hint

### Steps to reproduce

Post update, I tried to use the jira plugin for the fist time and set some setting, to see it crash.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by pmiossec**
and so that settings file can't be saved in a "not existing" local repository.

Check that repo is valid and provide the information when creating pages

Fixes #11907 (at least prevent one way to reproduce it)

### Before

image

### After

image

## Test methodology 

- Manual (Opening settings from dashboard i.e. while no repo opened)

## Test environment(s) 

- GIT 
- Windows 

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).
(Will be squashed before merging)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
Seem to work.

Does this changes the plugin interface?

**Comment by mstv** [comment]
Do we really need to pass this flag to all settings pages? It does not apply to more than half of them.

**Review by RussKie — COMMENTED** [review]
This feels like a suboptimal way of implementing the flag. Is there a reason the flag can't be initialised by the base page?

**Comment by pmiossec** [comment]
> This feels like a suboptimal way of implementing the flag. Is there a reason the flag can't be initialised by the base page?

It can't because we don't have access to `IGitModule` in `SettingsPageBase`.

I discovered that we can get it through `ISettingsPageHost` (and so I pushed the beginning of a refactoring) but the property is set after and so the module is available later:
https://github.com/gitextensions/gitextensions/pull/11955/files#diff-f8be27a1112b9ef3c305709ea09203ee2a4f1c4cd3a37110498627d617607af0R70

I can continue the refactoring to require  `ISettingsPageHost` in the constructor but the result will be that all the constructor will be updated (taking  `ISettingsPageHost` instead of `bool canSaveInsideRepo`).

@RussKie I gave it a quick try in the last commit. Look if you find it better...

>Do we really need to pass this flag to all settings pages? It does not apply to more than half of them.

The constructors of all the setting pages has to be updated due to how they are instantiated.

>Does this changes the plugin interface?

I don't think so (and it seems to work without problem)

**Review by mstv — APPROVED** [review]
👍, have not run

**Review by gerhardol — APPROVED** [review]
A lot of changes, but hard to do in another way.
Have run briefly

**Comment by RussKie** [comment]
I'm planning to review this, hopefully before the EOW.

File: src/app/GitUI/CommandsDialogs/SettingsDialog/SettingsPageWithHeader.cs [hunk 1]
```diff
@@ -1,18 +1,22 @@
...
     {
         private SettingsPageHeader? _header;
+        private bool _canSaveInsideRepo;
 
-        public SettingsPageWithHeader(IServiceProvider serviceProvider)
-            : base(serviceProvider)
+        public SettingsPageWithHeader(IServiceProvider serviceProvider, ISettingsPageHost pageHost)
+            : base(serviceProvider, pageHost)
         {
+            _canSaveInsideRepo = pageHost.CheckSettingsLogic.CommonLogic.Module.IsValidGitWorkingDir();
```
Comment (RussKie) [inline src/app/GitUI/CommandsDialogs/SettingsDialog/SettingsPageWithHeader.cs:16]: What's the concrete type of `serviceProvider`? It's an instance of `GitUICommands`, which implements `IGitUICommands` and, thus, inherits from `IServiceProvider`.
image

Which makes this possible:
```cs
if (serviceProvider is IGitUICommands uiCommands)
{
    _canSaveInsideRepo = uiCommands.Module.IsValidGitWorkingDir();
}
```

It's a little hacky, but we some point I expect we'll have something like the following:
```cs
IGitUICommands uiCommands = serviceProvider.GetREquiredService<IGitUICommands>();
```

Comment (pmiossec) [reply src/app/GitUI/CommandsDialogs/SettingsDialog/SettingsPageWithHeader.cs:16]: > Which makes this possible:

I saw that but it was (too) hacky for me that's why I have not decided to go that way.
It's you to decide...

Comment (pmiossec) [reply src/app/GitUI/CommandsDialogs/SettingsDialog/SettingsPageWithHeader.cs:16]: In the end, `ISettingsPageHost`, that still need to be passed is now passed in the constructor to have it earlier than in a later call to do some initialization. It's indeed a lot of code changes but nothing silly...

Comment (RussKie) [reply src/app/GitUI/CommandsDialogs/SettingsDialog/SettingsPageWithHeader.cs:16]: The current change introduces a hard coupling, and this I'd like to avoid. 
Let's resolve from the service provider

Comment (pmiossec) [reply src/app/GitUI/CommandsDialogs/SettingsDialog/SettingsPageWithHeader.cs:16]: Done.

**Review by RussKie — APPROVED** [review]

**Review by mstv — APPROVED** [review]
