### PR TITLE
Fix Find button scaling in git-grep dialog

### LINKED ISSUE #12310: Dialog "Find in commit files using git-grep" is unusable under high scaling factor
### Environment

- GitExtensions version: master @ 6049c664555aba3a4e2adba2c80ecaf68eab1566
- OS version: Windows 11

### Issue description

This is the dialog under 200% scaling. Adding insult to injury is that it's also non-resizable

Image

### Steps to reproduce

_Scaling 200%_
1. Open "Find in commit files using git-grep"

### Did this work in previous version of GitExtensions?

Probably not

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mdonatas**
Fixes #12310

## Proposed changes

- Fix Find button scaling
- Fix watermark placement

### Before

At 200%
image

At 100%
image

### After

At 200%
image

At 150%
image

At 100%
image

## Test methodology 

- Manually at 100% 150% and 200% scaling

## Test environment(s) 

- Windows 11

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/Editor/FormFindInCommitFilesGitGrep.cs [hunk 1]
```diff
@@ -124,6 +125,8 @@ private void SetSearchWatermarkLabelVisibility()
         lblSearchCommitGitGrepWatermark.Visible = cboFindInCommitFilesGitGrep.Visible && !cboFindInCommitFilesGitGrep.Focused && string.IsNullOrEmpty(cboFindInCommitFilesGitGrep.Text);
         if (lblSearchCommitGitGrepWatermark.Visible)
         {
+            int nonTextHeight = (cboFindInCommitFilesGitGrep.ClientRectangle.Height - cboFindInCommitFilesGitGrep.Font.Height) / 2;
+            lblSearchCommitGitGrepWatermark.Top = cboFindInCommitFilesGitGrep.Top + nonTextHeight;
```
Comment (RussKie) [inline src/app/GitUI/Editor/FormFindInCommitFilesGitGrep.cs:129]: Any reason not to make the watermark the same size as the "owner" control?

We have other watermark controls, are we doing the same in those too?

Comment (mdonatas) [reply src/app/GitUI/Editor/FormFindInCommitFilesGitGrep.cs:129]: Owner control's size includes borders and the label would cover it. Setting transparent BackColor doesn't help, the "owner" control's border is simply not drawn where the label covers it even if it's transparent.

Tried some experiments
image

FileStatusList looks at other control's bottom to determine position https://github.com/gitextensions/gitextensions/blob/master/src/app/GitUI/UserControls/FileStatusList.cs#L451-L453
and here https://github.com/gitextensions/gitextensions/blob/master/src/app/GitUI/UserControls/FileStatusList.cs#L472-L475
This PR's approach of placing the label vertically in the center of "owner" control works well and looks consistently between different scaling factors.

Comment (mstv) [reply src/app/GitUI/Editor/FormFindInCommitFilesGitGrep.cs:129]: RussKie meant controls having something like `EditNetSpell.WatermarkText` I guess. I could not find other such UserControls in a quick search.
FileStatusList with its hand-made dock layout is a rather unlucky example.

> This PR's approach of placing the label vertically in the center of "owner" control works well and looks consistently between different scaling factors.

Yes, but not perfectly. Alignment of the text baseline is a wide-spread issue in GE.

image

Comment (RussKie) [reply src/app/GitUI/Editor/FormFindInCommitFilesGitGrep.cs:129]: The reason I asked - we have several watermarks in various controls, I just want to make sure we have a consistent implementation. (Perhaps, there's even an opportunity to unify/generalise the implementations?)

Comment (mdonatas) [reply src/app/GitUI/Editor/FormFindInCommitFilesGitGrep.cs:129]: I am going to remove the watermark commit and address it separately in another PR. I think there is a way to handle these drop-down watermarks in the same way as `EditNetSpell.WatermarkText`

**Review by mstv — APPROVED** [review]
have not run
