### PR TITLE
Avoid double quoting while showing File History dialog

### LINKED ISSUE #10537: File History is empty after switching from version 3.5.4 to 4.0.1
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

### Issue description

With version 3.5.4 I could open the File History of a file, and it showed the tree of commits filtered down to that particular file. For example, the File History of gitextensions\GitUI\GitUI.csproj used to look like this:

gitextension_3 5 4 12724

After switching to version 4.0.1 the tree view shows only to entries “Commit index” and “Working directory”, the actual history tree is missing:

gitextension_4 0 1 15887

The tree of the older gitextension seem to be the correct one, it matches the output of the git log --graph --all GitUI\GitUI.csproj

git_log

### Steps to reproduce

In the Windows File Explorer select a file in a repository, right click it to display the context menu and select the “Git Extensions/File History” item. The tree view shows only to entries “Commit index” and “Working directory”, the actual history tree is missing.

### Did this work in previous version of GitExtensions?

Yes, it did with this version:

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4515.0
- DPI 96dpi (no scaling)

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by RussKie**
#10438 introduced a regression by double quoting file names passed to the File History dialog. However, it didn't take an account that the File History is now primarily shown in Form Browse dialog, where the argument is quoted when it is passed to the filter,

Quote the argument now only for the File History dialog.

Resolves #10537

### CODE REVIEW

File: GitUI/GitUICommands.cs [hunk 1]
```diff
@@ -1755,8 +1756,10 @@ private bool RunFileHistoryCommand(IReadOnlyList<string> args, bool showBlame)
             }
             else
             {
+                // NOTE: fileHistoryFileName must be quoted.
+
                 ShowModelessForm(owner: null, requiresValidWorkingDir: true, preEvent: null, postEvent: null,
-                                 () => new FormFileHistory(commands: this, fileHistoryFileName, revision, filterByRevision, showBlame));
+                                 () => new FormFileHistory(commands: this, fileHistoryFileName.QuoteNE(), revision, filterByRevision, showBlame));
```
Comment (mstv) [inline GitUI/GitUICommands.cs:1762]: > fileHistoryFileName must be quoted.

... but not if has already been quoted (by whichever shell for whatever reason - I cannot reproduce it with neither value of `AppSettings.UseBrowseForFileHistory`)

```
                // NOTE: fileHistoryFileName must be quoted.
                if (!fileHistoryFileName.Contains('"'))
                {
                    fileHistoryFileName = fileHistoryFileName.QuoteNE();
                }
```

File: IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs [hunk 2]
```diff
@@ -184,6 +184,44 @@ public void Filters_should_behave_as_expected()
                 });
         }
 
+        [TestCase("", "file.txt")]
+        [TestCase("", "file with spaces.txt")]
```
Comment (mstv) [inline IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs:188]:
```suggestion
        [TestCase("", "file with spaces.txt")]
        [TestCase("", "\"file with spaces.txt\"")]
```

File: GitUI/GitUICommands.cs (hunk 1 above)
Comment (RussKie) [reply GitUI/GitUICommands.cs:1762]: This code is invoked from here:
https://github.com/gitextensions/gitextensions/blob/21345f29511f71fb1ca7cfd8ea128972b56863e4/GitUI/GitUICommands.cs#L1449-L1456

`fileHistoryFileName` comes from `arg[2]`. On a command prompt `foo` or `"foo"` are treated the same - `foo`. We don't supply `"\"foo\""` on a command line and; if a user does it explicitly - then it's user's doing.

To debug it, you'd need to start the app like this:
```json
    "FileHistory": {
      "commandName": "Project",
      "commandLineArgs": "filehistory \"\\\"GitExtensions.settings\\\"\" "
    }
```


I considered adding a method that would quote if no quotes present, however, it would require a deeper investigation, which I don't have time for.

File: IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs (hunk 2 above)
Comment (RussKie) [reply IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs:188]: ...actually we can't do that
```
System.IO.IOException : The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\appveyor\AppData\Local\Temp\1\tqbhkuu3.lkg\repo1\"file with spaces.txt"'
 [463](https://ci.appveyor.com/project/gitextensions/gitextensions/build/4.0.2.15936#L463)   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
 [464](https://ci.appveyor.com/project/gitextensions/gitextensions/build/4.0.2.15936#L464)   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
 [465](https://ci.appveyor.com/project/gitextensions/gitextensions/build/4.0.2.15936#L465)   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
 [466](https://ci.appveyor.com/project/gitextensions/gitextensions/build/4.0.2.15936#L466)   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
 [467](https://ci.appveyor.com/project/gitextensions/gitextensions/build/4.0.2.15936#L467)   at System.IO.File.WriteAllText(String path, String contents)
 [468](https://ci.appveyor.com/project/gitextensions/gitextensions/build/4.0.2.15936#L468)   at CommonTestUtils.GitModuleTestHelper.CreateFile(String parentDir, String fileName, String fileContent) in C:\projects\gitextensions\UnitTests\CommonTestUtils\GitModuleTestHelper.cs:line 77
 [469](https://ci.appveyor.com/project/gitextensions/gitextensions/build/4.0.2.15936#L469)   at CommonTestUtils.GitModuleTestHelper.CreateRepoFile(String fileRelativePath, String fileName, String fileContent) in C:\projects\gitextensions\UnitTests\CommonTestUtils\GitModuleTestHelper.cs:line 99
 [470](https://ci.appveyor.com/project/gitextensions/gitextensions/build/4.0.2.15936#L470)   at CommonTestUtils.ReferenceRepository.CreateCommitRelative(String fileRelativePath, String fileName, String commitMessage, String content) in C:\projects\gitextensions\UnitTests\CommonTestUtils\ReferenceRepository.cs:line 97
 [471](https://ci.appveyor.com/project/gitextensions/gitextensions/build/4.0.2.15936#L471)   at GitExtensions.UITests.CommandsDialogs.FormBrowseTests.File_history_should_behave_as_expected(String fileRelativePath, String fileName) in C:\projects\gitextensions\IntegrationTests\UI.IntegrationTests\CommandsDialogs\FormBrowseTests.cs:line 197
```

Comment (gerhardol) [reply IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs:188]: There should be a testcase that quotes the complete path, Add a parameter?

File: GitUI/GitUICommands.cs (hunk 1 above)
Comment (mstv) [reply GitUI/GitUICommands.cs:1762]: (I could not reproduce it before because the shell extension started the wrong version, although I re-registered the shell extension and restarted the TotalCommander.)
Using the command line, I can reproduce it now and have verified that this PR fixes the issue.

**Review by mstv — APPROVED** [review]
Thank you

File: IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs (hunk 2 above)
Comment (RussKie) [reply IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs]: Added a test for the main dialog. The same test can't apply to the History dialog - it leads to exceptions. I have no plans to investigate any further.

**Review by gerhardol — APPROVED** [review]
Not tested myself. This is good enough.

File: IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs [hunk 3]
```diff
@@ -184,6 +184,66 @@ public void Filters_should_behave_as_expected()
...
         }
 
+        [TestCase("", "file.txt", false)]
+        [TestCase("", "file with spaces.txt", false)]
+        [TestCase("Dir with spaces", "file.txt", false)]
+        [TestCase("Dir with spaces", "file with spaces.txt", false)]
+        [TestCase("", "file.txt", true)]
+        [TestCase("", "file with spaces.txt", true)]
+        [TestCase("Dir with spaces", "file.txt", true)]
+        [TestCase("Dir with spaces", "file with spaces.txt", true)]
```
Comment (mstv) [inline IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs:194]: > `fileHistoryFileName` comes from `arg[2]`. On a command prompt `foo` or `"foo"` are treated the same - `foo`. We don't supply `"\"foo\""` on a command line and; if a user does it explicitly - then it's user's doing.

> I considered adding a method that would quote if no quotes present, however, it would require a deeper investigation, which I don't have time for.

These testcases try to do what we don't want to support... and fail.

Comment (RussKie) [reply IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs]: Yes, I reverted those. For now these are good enough.

**Comment by TobiaMasss** [comment]
topo ragno nasconditi
