### PR TITLE
Expand settings tree to show found nodes

### LINKED ISSUE #5341: Search settings should expand the whole tree
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
It seems that no setting has been found if the search string appears on nested pages only:
grafik

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- open `Tools` | `Settings`
- type "multi" as text to find

**What is the expected behavior?**
The whole settings tree should be expanded in order to see which pages contain the search string.
(This is important because the search string is cleared when the search field loses the focus.)
The first settings page containing the search string should be shown.
grafik

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: (2.17.1.w.2-x64)
- OS version: (Windows 7)
- .NET version: (4.7)

**Did this work in previous version of GitExtensions (which)?**
Not in 2.51.02 which shows the number of hits at least.

### PR DESCRIPTION
**Pull request by mstv**
Fixes #5341

Changes proposed in this pull request:
- expand the settings tree so that all search hits are shown
 
Screenshots before and after (if PR changes UI):
- before
grafik
- after
grafik

What did I do to test the code and ensure quality:
- manual testing

Has been tested on (remove any that don't apply):
- GIT: (2.18.0.w.x64)
- Windows 7

### CODE REVIEW

File: GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs [hunk 1]
```diff
@@ -152,6 +152,10 @@ private void textBoxFind_TextChanged(object sender, EventArgs e)
             foreach (var node in _nodesFoundByTextBox)
             {
                 HighlightNode(node, true);
+                for (var parent = node.Parent; parent != null; parent = parent.Parent)
```
Comment (pmiossec) [inline GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs]: I think I found a `do/while` loop more understandable for a such case (and keep the 'for' loop for case where the length is known at the beginning)

Comment (mstv) [reply GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs]: The `for` loop has the big advantage that the loop variable is scope-limited.
I always use `for` if there's a loop variable and an iteration step for the loop variable.

Comment (RussKie) [reply GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs]: I personally would write it as `do..while` but for me this is not a deal breaker

Comment (RussKie) [inline GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs]: why can't we just call `node.EnsureVisible();` instead of looping through?

Comment (mstv) [reply GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs]: @RussKie, because I did not find it since the name has nothing to do with "expand".
It works well.
