### PR TITLE
#5331 FileStatusList: highlighted file name is too pale

### LINKED ISSUE #5331: FileStatusList: highlighted file name is too pale
**Do you want to request a *feature* or report a *bug*?**
bad ux

**What is the current behavior?**
The file name of the highlighted file in the commit dialog is displayed too pale.
grafik

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the commit dialog and select a modified or new file.

**What is the expected behavior?**
The font color for the file name should be pure black.

I appreciate the new feature to display the file's path in gray.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
pre v3-ux

### PR DESCRIPTION
**Pull request by NikolayXHD**
Fixes #5331

**Screenshots**

Selection rendering change when focused

image

Selection rendering change when non-focused

image

**Tested**

on Windows 7

### CODE REVIEW

File: GitUI/UserControls/ExListView.cs [hunk 1]
```diff
@@ -55,7 +55,7 @@ public enum ListViewGroupState : uint
         SubSetLinkFocused = 128
     }
 
-    internal class ExListView : NativeListView
+    internal class ExListView : ListView
```
Comment (RussKie) [inline GitUI/UserControls/ExListView.cs]: I'm not convinced this is a good fix as this essentially rolls back #4491

Comment (NikolayXHD) [reply GitUI/UserControls/ExListView.cs]: I managed to fix it without breaking NativeListView selection rendering

**Comment by NikolayXHD** [comment]
Used another approach. Current commits are ready to review.

**Comment by mstv** [comment]
Thank you!

File: GitExtensions.sln [hunk 2]
```diff
@@ -354,8 +354,8 @@ Global
 		{2B9B62FA-3E0C-45C5-9287-68B69413C5DF}.Debug|Any CPU.Build.0 = Debug|Any CPU
 		{2B9B62FA-3E0C-45C5-9287-68B69413C5DF}.Release|Any CPU.ActiveCfg = Release|Any CPU
 		{2B9B62FA-3E0C-45C5-9287-68B69413C5DF}.Release|Any CPU.Build.0 = Release|Any CPU
-		{2D18BE89-D210-49EB-A9DD-2246FBB3DF6D}.Debug|Any CPU.ActiveCfg = Release|Any CPU
-		{2D18BE89-D210-49EB-A9DD-2246FBB3DF6D}.Debug|Any CPU.Build.0 = Release|Any CPU
+		{2D18BE89-D210-49EB-A9DD-2246FBB3DF6D}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
+		{2D18BE89-D210-49EB-A9DD-2246FBB3DF6D}.Debug|Any CPU.Build.0 = Debug|Any CPU
```
Comment (RussKie) [inline GitExtensions.sln]: could you please clarify the nature of this change?

Comment (NikolayXHD) [reply GitExtensions.sln]: Before debugging Visual Studio blames about trying to debug Release configuration ICSharpCode.TextEditor

the same as that:
image

As this change is unrelated to pale selection, it's in a separate commit `fix solution configuration`

Comment (drewnoakes) [reply GitExtensions.sln]: PR looks good, though please revert the change to the configuration.

Comment (NikolayXHD) [reply GitExtensions.sln]: ok

**Comment by gerhardol** [comment]
Looks OK for me in Win7/10

**Comment by RussKie** [comment]
Thank you
