### PR TITLE
[#5499] Fix invisible row selection in the file status list control.

### LINKED ISSUE #5499: File selection is invisible at Commit dialog, v3.00.00 beta1
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
File selection is invisible at Commit dialog, v3.00.00 beta1 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just open Commit dialog and click on one the changed file

**What is the expected behavior?**
Selected file has dark-blue background.

**Environment you encounter the issue:**

- GitExtensions version: v3.00.00 beta1 
- GIT version: 2.18
- OS version: Win7_x64
- .NET version: 4.7.03062

**Did this work in previous version of GitExtensions (which)?**
2.52

default

### PR DESCRIPTION
**Pull request by vrubleg**
Fixes #5499. As a good addition, the look and feel of the selected row in this list is the same as in the commit list. It looks much better when both selected rows in different lists are in the same style. Tested on Windows 7 (with classic theme) and Windows 10 (with default theme). 

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by vrubleg** [comment]
## Windows 7 screenshots

### Before
image

### After
image

## Windows 10 screenshots

### Before
image

### After
image

**Comment by gerhardol** [comment]
I did not mind the existing highlighting in list, but this is same highlighting as in grid

Screenshots from dark, darksilver

image

image

With this the separate highlighting if the control is selected or not is lost

FileStatusList selected
image

FileViewer selected
image

File: GitUI/UserControls/FileStatusList.cs [hunk 1]
```diff
@@ -1411,18 +1416,18 @@ private void FileStatusListView_DrawSubItem(object sender, DrawListViewSubItemEv
 
                 if (!string.IsNullOrEmpty(prefix))
                 {
-                    DrawString(textRect, prefix, SystemColors.GrayText);
+                    DrawString(textRect, prefix, e.Item.Selected ? SystemColors.HighlightText : SystemColors.GrayText);
```
Comment (gerhardol) [inline GitUI/UserControls/FileStatusList.cs:1419]: Set textColor only once, use variable

Comment (vrubleg) [reply GitUI/UserControls/FileStatusList.cs:1419]: It won't work as expected because two different colors (`SystemColors.GrayText` and `SystemColors.ControlText`) are used for different parts of the text when the row is not selected.

Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs:1419]:
```
             var (image, prefix, text, suffix, prefixTextStartX, _, textMaxWidth) = FormatListViewItem(item, formatter, item.Bounds.Width);
 
-            if (e.Item.Selected)
+            if (item.Selected)
             {
                 e.Graphics.FillRectangle(SystemBrushes.Highlight, e.Bounds);
             }
@@ -1413,21 +1413,22 @@ private void FileStatusListView_DrawSubItem(object sender, DrawListViewSubItemEv
             if (!string.IsNullOrEmpty(text))
             {
                 var textRect = new Rectangle(prefixTextStartX, item.Bounds.Top, textMaxWidth, item.Bounds.Height);
+                var textColor = item.Selected ? SystemColors.HighlightText : SystemColors.GrayText;
 
                 if (!string.IsNullOrEmpty(prefix))
                 {
-                    DrawString(textRect, prefix, e.Item.Selected ? SystemColors.HighlightText : SystemColors.GrayText);
+                    DrawString(textRect, prefix, textColor);
                     var prefixSize = formatter.MeasureString(prefix);
                     textRect.Offset(prefixSize.Width, 0);
                 }
 
-                DrawString(textRect, text, e.Item.Selected ? SystemColors.HighlightText : SystemColors.ControlText);
+                DrawString(textRect, text, textColor);
 
                 if (!string.IsNullOrEmpty(suffix))
                 {
                     var textSize = formatter.MeasureString(text);
                     textRect.Offset(textSize.Width, 0);
-                    DrawString(textRect, suffix, e.Item.Selected ? SystemColors.HighlightText : SystemColors.GrayText);
+                    DrawString(textRect, suffix, textColor);
                 }
             }
 
```

Comment (vrubleg) [reply GitUI/UserControls/FileStatusList.cs:1419]: Please look closer to these lines:
```
DrawString(textRect, text, e.Item.Selected ? SystemColors.HighlightText : SystemColors.ControlText);
```
and
```
DrawString(textRect, suffix, e.Item.Selected ? SystemColors.HighlightText : SystemColors.GrayText);
```
Different colors are used for path and file name. It isn't introduced by me. These colors are used in the original code for not selected rows.

Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs:1419]: thanks!

**Comment by vrubleg** [comment]
Related to indication of focus. I think that dotted rectangle around selected row would be better than changing color. Current implementation of commit list also doesn't show focus. So, if we change this, it should be changed in both places for consistency.

**Comment by gerhardol** [comment]
The same way to show selected should also be used in the side panel, should be the same problem for "Classic" users (and inconsistent for others)?
Where more?
This or another PR?

> Related to indication of focus. I think that dotted rectangle around selected row would be better than changing color. Current implementation of commit list also doesn't show focus. So, if we change this, it should be changed in both places for consistency.

Yes - probably a separate PR

**Comment by vrubleg** [comment]
> should be the same problem for "Classic" users
No, there is no this problem in the tree lists. The selection is visible in tree lists when classic theme is used.
> (and inconsistent for others)
Yeah, style of tree lists is inconsistent with commit and diff lists. Another place where a tree list is used is the "File tree" tab. Makes sense to update all these controls to use consistent rendering of selection. But yeah, as for me, better consistency of tree lists is a separate issue.

**Comment by RussKie** [comment]
> Makes sense to update all these controls to use consistent rendering of selection. But yeah, as for me, better consistency of tree lists is a separate issue.

👍

**Review by RussKie — APPROVED** [review]
LGTM

File: contributors.txt [hunk 2]
```diff
@@ -139,4 +139,5 @@ YYYY/MM/DD, github id, Full name, email
 2020/09/09, adamshakhabov, Adam Shakhabov, theadamo86(at)gmail.com
 2020/09/13, hoborm, Mihaly Hobor, mail(at)hobor.xyz
 2020/07/11, blitzmann, Ryan Holmes, holmes.ryan.90(at)gmail.com
-2020/10/04, GintasS, Gintautas Švedas, svedgintas(at)gmail.com
\ No newline at end of file
+2020/10/04, GintasS, Gintautas Švedas, svedgintas(at)gmail.com
+2020/10/06, vrubleg, Evgeny Vrublevsky, me@veg.by
```
Comment (RussKie) [inline contributors.txt:143]: You may want to replace the `@` sign :)

**Comment by RussKie** [comment]
@NikolayXHD any concerns?

File: contributors.txt (hunk 2 above)
Comment (vrubleg) [reply contributors.txt:143]: As for me, using `(at)` makes no sense, because all crawlers which collect emails already know about popular substitutes of `@` and `.`. Spam filters are really good nowadays, so I always post my emails as is. One of my emails is public for almost 20 years, it is included probably in all possible spam lists. It was an issue 15 years ago, 20+ unfiltered spam messages per day, but now it is just a message in a month or so.

I (or you) can replace it to `(at)` for consistency with others if you wish, but there is another person who used `@` as is in their email also in the list.

Comment (RussKie) [reply contributors.txt:143]: No worries, wanted to make sure you did it consciously. 
...And our emails are public in the git history too :)

**Comment by NikolayXHD** [comment]
> @NikolayXHD any concerns?

I'd like to keep gray text for directory name vs black text for file name for selected rows.
image

On SystemColors.Highlight the SystemColors.GrayText is illegible
image

so it has to be adapted.
image

I added the necessary changes to a a PR above this one, see https://github.com/vrubleg/gitextensions/pull/1

File: GitUI/UserControls/FileStatusList.cs [hunk 3]
```diff
@@ -1411,18 +1416,18 @@ private void FileStatusListView_DrawSubItem(object sender, DrawListViewSubItemEv
 
                 if (!string.IsNullOrEmpty(prefix))
                 {
-                    DrawString(textRect, prefix, SystemColors.GrayText);
+                    DrawString(textRect, prefix, item.Selected ? SystemColors.HighlightText : SystemColors.GrayText);
```
Comment (NikolayXHD) [inline GitUI/UserControls/FileStatusList.cs:1419]: This change loses gray / black contrast between directory and file name

**Review by NikolayXHD — CHANGES_REQUESTED** [review]

File: GitUI/UserControls/FileStatusList.cs (hunk 3 above)
Comment (vrubleg) [reply GitUI/UserControls/FileStatusList.cs]: Merged.

**Comment by vrubleg** [comment]
Merged the proposed changes and rebased my branch on top of master.

**Comment by RussKie** [comment]
@msftbot merge if @NikolayXHD approves

**Review by NikolayXHD — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you all
