### PR TITLE
fix(RevisionGridControl): NRE on special stashes

### LINKED ISSUE #12706: [NBug] Object reference not set to an instance of an object.
### Environment

- Git Extensions 6.0.4.18366
- Build e162799e887f80199e122cc996fb304f5a96d165
- Git 2.52.0.windows.1
- Microsoft Windows NT 10.0.26200.0
- .NET 9.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.RevisionGridControl.<>c__DisplayClass150_0.<PerformRefreshRevisions>g__OnRevisionRead|6(IReadOnlyList`1 revisions) in C:\projects\gitextensions\src\app\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 1273
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 732
   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 680
   at System.Reactive.Concurrency.NewThreadScheduler.<>c__DisplayClass7_0`1.<ScheduleLongRunning>b__0() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/NewThreadScheduler.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

It happens when I'm trying to open the existing repository (right mouse click -> 'GitExt open repository'). Then the application suddenly exits. It doesn't allow doing any operation on the repository.

### Steps to reproduce

- Prepare a git repository. I can't provide you with the repo I'm working on. It's a personal repository. I'm not really sure what repo should be used to replicate the bug. On some other repositories, it works fine without error.
- Go to the repository directory
- open git extension
- click 'open repository'
- provide the path of the repository
- Right after those steps, the application exists with the error message

### Did this work in previous version of GitExtensions?

Yes, it worked previously, but I can't say on which version it worked.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #12706

## Proposed changes

`RevisionGridControl.PerformRefreshRevisions`:
- Properly handle exception by setting all stash related variables to `null`
  in order to avoid a race condition on `untrackedByStashId`
  The exception on this follow-up error did hide the initial exception.
- Do not rely on `ObjectId` of the untracked commit of stashes being unique

### Before

directly on app start
image

### After

Test exception can be ignored
image

## Test methodology 

- inject exception in detached async task

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 1]
```diff
@@ -1037,43 +1037,59 @@ public void PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> get
...
+
+                            // "untracked" commits to insert (parent to "stash" commits)
+                            Dictionary<ObjectId, ObjectId> untrackedIdByStashId = getStashRevs.Value
+                                .Where(stash => stash.ParentIds.Count >= 3)
+                                .Take(AppSettings.MaxStashesWithUntrackedFiles)
+                                .ToDictionary(stash => stash.ObjectId, stash => stash.ParentIds[2]);
+                            List<ObjectId> untrackedIds = [.. untrackedIdByStashId.Values.Distinct()];
+                            Dictionary<ObjectId, GitRevision> untrackedRevs = new RevisionReader(capturedModule)
+                                .GetRevisionsFromList(untrackedIds, cancellationToken)
+                                .ToDictionary(r => r.ObjectId);
```
Comment (mstv) [inline src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs]: BTW: `GetRevisionsFromList` has never returned revisions in my tests.

**Review by RussKie — COMMENTED** [review]
Is it possible to add a regression test?

File: src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 2]
```diff
@@ -1037,43 +1037,59 @@ public void PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> get
...
                             {
-                                stash.ParentIds = [stash.FirstParentId, stash.ParentIds[2]];
+                                if (!untrackedByStashId.ContainsKey(stash.ObjectId))
+                                {
+                                    stash.ParentIds = [stash.FirstParentId];
+                                }
+                                else
+                                {
+                                    stash.ParentIds = [stash.FirstParentId, stash.ParentIds[2]];
+                                }
```
[the remark this answers is not in the document]
Comment (mstv) [reply src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs]: This preexisting code was just indented. Though the inverse logic is worth changing.

**Comment by mstv** [comment]
> Is it possible to add a regression test?

We have existing integration tests for stashes.
The change enables the processing of a very special case, which is hard to create using git. I am not willing to mock everything and to extract functions for this.

File: src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 3]
```diff
@@ -1037,43 +1037,54 @@ public void PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> get
...
-                        stashesById = getStashRevs.Value.ToDictionary(r => r.ObjectId);
-
-                        // Git stores stashes in 2 or 3 commits. The (first) "stash" commit is listed by git-stash-list,
-                        // does not include untracked files, may be stored in the third "untracked" commit.
-                        // The second "index" commit are ignored (can be seen with reflog).
-                        // Git creates the "untracked" commit also if there are no changes, these are filtered (adds marginal time to getting revisions).
-                        // This command to list "untracked" commits is quite slow, why max number of "stash" commits
-                        // to evaluate for untracked files is limited.
-                        if (AppSettings.ShowReflogReferences)
+                        try
```
Comment (KarolBajkowski) [inline src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs]: One small nitpick
Isn't he nested try catch
```
try
{
    try
    {
        // do something...
    }
    catch
    {
        stashesById = null;
        stashesByParentId = null;
        untrackedByStashId = null;
        throw;
    }
}
finally
{
    // Allow add revisions to the grid
    semaphoreUpdateGrid.Release();
}
```

the same as the one below?
```
try
{
    // do something...
}
catch
{
    stashesById = null;
    stashesByParentId = null;
    untrackedByStashId = null;
    throw;
}
finally
{
    // Allow add revisions to the grid
    semaphoreUpdateGrid.Release();
}
```

The second version seems easier to read IMO because nested `try... catch...` is reduced

Comment (mstv) [reply src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs]: I forgot that this clearer syntax is supported by C#.
