### PR TITLE
FIX: Periodic Background Fetch was not automatically refreshing the UI after a successful fetch

### LINKED ISSUE #9643: Periodic Background Fetch is not doing anything at all
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.22000.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)

### Issue description

Configuration

git call stack

Manual git fetch all works

Note: I have minimum two GitExtensions windows open at any given time. 

[Similar issue !5971](https://github.com/gitextensions/gitextensions/issues/5971)

### Steps to reproduce

Enable periodic background fetch and wait the amount of seconds defined as interval. 

### Did this work in previous version of GitExtensions?

Yes, a few versions back. I don't remember exactly which one.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by RemiGaudin**
Fixes #9643

## Proposed changes

- In `BackgroundFetchPlugin.RecreateObservable()`: Retrieve both standard output and standard error from the fetch command because on some configurations the detailed info are written into the error stream.

## Test methodology

- I manually tested that the fix allow now the Periodic Background Fetch to automatically refresh the UI after a successful fetch.

## Test environment(s)

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: Plugins/BackgroundFetch/BackgroundFetchPlugin.cs [hunk 1]
```diff
@@ -126,7 +126,7 @@ private void RecreateObservable()
                                       string msg;
                                       try
                                       {
-                                          msg = _currentGitUiCommands.GitModule.GitExecutable.GetOutput(args);
+                                          msg = _currentGitUiCommands.GitModule.GitExecutable.Execute(args).AllOutput;
```
Comment (gerhardol) [inline Plugins/BackgroundFetch/BackgroundFetchPlugin.cs:129]: Anyone with info why stderr is used in this situation?
Generally, either stdout or stderr should be parsed. 
In this case it may be OK as "it is only a message" that is parsed, not data.

**Review by mstv — APPROVED** [review]
Thank you
have not run

File: Plugins/BackgroundFetch/BackgroundFetchPlugin.cs (hunk 1 above)
Comment (vbjay) [reply Plugins/BackgroundFetch/BackgroundFetchPlugin.cs:129]: https://github.com/git/git/commit/96890f4c428ed62cf52c11aba5773d364a8d6234#diff-a8ad3d92e86b1622eb617b0a241f2622911f8e868e3816aebb998a0f3e3bcf95R479

Comment (vbjay) [reply Plugins/BackgroundFetch/BackgroundFetchPlugin.cs:129]: https://lore.kernel.org/git/CAH74SFS3hFzYzJ6eb2YenJh4-Pf_VBzVTo8axnEtHDyaJUB-jw@mail.gmail.com/

Comment (gerhardol) [inline Plugins/BackgroundFetch/BackgroundFetchPlugin.cs:129]:
```suggestion
                                          msg = _currentGitUiCommands.GitModule.GitExecutable.Execute(args).StandardError;
```

**Review by gerhardol — COMMENTED** [review]
+1
Suggest limiting to stderr

File: Plugins/BackgroundFetch/BackgroundFetchPlugin.cs (hunk 1 above)
Comment (vbjay) [reply Plugins/BackgroundFetch/BackgroundFetchPlugin.cs:129]: Agreed. But one step more. We need to run through all use of all output and do the same. Does it need to be all output or std based on what we look for.  Look at the git source code to track what output we look for is written where. It would prevent confusion. Down the road to put good comments in the use of error to mention git writes blaa to error so we read error instead of std and such.

Comment (RemiGaudin) [reply Plugins/BackgroundFetch/BackgroundFetchPlugin.cs]: @gerhardol I just pushed and tested your suggestion, and I also added some comments.
To me this fix is enough to solve this specific issue. I'm not sure if you want to include the full review of all output use in the scope of this PR or not, because then I'm afraid I don't have enough expertise to do that.

**Review by gerhardol — APPROVED** [review]

File: Plugins/BackgroundFetch/BackgroundFetchPlugin.cs (hunk 1 above)
Comment (gerhardol) [reply Plugins/BackgroundFetch/BackgroundFetchPlugin.cs]: Good work, hanging on.
Now this is handled not just as a fix but with a known reason and explanation.
This could be included in a 4.0.3 (if there is one), a separate PR there later.

@vbjay Also thanks for hanging on. There were so many opinions that it was hard to find the core facts. (If I tried to get all data right before posting anything, a lot less would be done why asked in the issue as a question.)
There were some investigations before #9488, but a full check would take too much time.
In a community project like GE, the members need to be involved.

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
I wouldn't want to release 4.0.3, instead I propose we release 4.1.

**Comment by RussKie** [comment]
Thanks @RemiGaudin
