### PR TITLE
Have alternate merge strategies help button point to online manual

### LINKED ISSUE #9259: Help for alternative merge-strategy is closed to fast
## Current behaviour

The very big tool-tip for the alternative merge-strategy is closed after 4 or 5 seconds.

## Expected behaviour
Don't automatic close the tool tip
or increase the auto-close time
or find a better presentation for the many information (like a extra window).

## Steps to reproduce
1. Merge to braches
2. Activate `Alternative options`
2. Activate `Use alternative Merge strategy`
3. Hover over the `Help` link

## Screenshots

bla

## Did this work in previous version of GitExtensions

No

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by lhiginbotham**
Move merge strategies help tooltip to online documentation, open link on click

Fixes #9259

See proposed documentation changes here (and complete the doc PR prior to this PR):
https://github.com/gitextensions/GitExtensionsDoc/pull/144

## Proposed changes

- the help button next to the alternate merge strategies selector in the branch merge advanced options will now open the online documentation when clicked (rather than showing a length tooltip that fades in a relatively short amount of time)

### Before

image

### After

There is no longer a tooltip and clicking the Help link brings us to https://git-extensions-documentation.readthedocs.io/en/main/branches.html#advanced-merge-options

image

## Test methodology 

- tested the link to see if it goes to an appropriate URL, verified it will bring us to the correct URL once the doc page update goes in

## Test environment(s) 

- Windows 10

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by lhiginbotham** [comment]
FYI @RussKie @TobiasSekan - hopefully this is along the lines of what you were looking for

**Comment by lhiginbotham** [comment]
@RussKie should this be rebased onto origin/release/4.0? Or should both versions (3 and 4) get the fix?  If so, not sure how the docs update will go, never did a doc change before, let alone a version specific change.

**Comment by RussKie** [comment]
> should this be rebased onto origin/release/4.0? Or should both versions (3 and 4) get the fix?

v3 is officiall done. We'll service release/4.0 branch with this after the merge.

File: GitUI/CommandsDialogs/FormMergeBranch.cs [hunk 1]
```diff
@@ -144,7 +143,8 @@ private void NonDefaultMergeStrategy_CheckedChanged(object sender, EventArgs e)
 
         private void strategyHelp_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
         {
-            strategyToolTip.SetToolTip(strategyHelp, _strategyTooltipText.Text);
+            OsShellUtil.OpenUrlInDefaultBrowser(
+                UserManual.UserManual.UrlFor("branches", "advanced-merge-options"));
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormMergeBranch.cs:147]: This doesn't look pretty... Please use `using`.

**Review by RussKie — COMMENTED** [review]
🎉

File: GitUI/CommandsDialogs/FormMergeBranch.cs (hunk 1 above)
Comment (lhiginbotham) [reply GitUI/CommandsDialogs/FormMergeBranch.cs:147]: @RussKie I tried the following but was met with a compilation error:

image

image


My only guess is that since the namespace name is the same as the class name, the compiler is confused, thinking I am intending the namespace name instead.

Any suggestions here or just leave it alone?

File: GitUI/CommandsDialogs/FormMergeBranch.cs [hunk 2]
```diff
@@ -144,7 +143,8 @@ private void NonDefaultMergeStrategy_CheckedChanged(object sender, EventArgs e)
 
         private void strategyHelp_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
         {
-            strategyToolTip.SetToolTip(strategyHelp, _strategyTooltipText.Text);
```
[the remark this answers is not in the document]
Comment (lhiginbotham) [reply GitUI/CommandsDialogs/FormMergeBranch.cs:147]: @RussKie good catch - removed all references, thanks!

**Comment by vbjay** [comment]
Just my $0.02. I think the help should be offline first and a link to online can be in the offline help. Take a page from git help. Assume not online and should still be able to get the help. 

```bash
git log --help
```

**Comment by gerhardol** [comment]
> Just my $0.02. I think the help should be offline first and a link to online can be in the offline help. Take a page from git help. Assume not online and should still be able to get the help.
> 
> ```shell
> git log --help
> ```

The GE documentation need a serious refresh before something like that may be considered. There has not been many contributions, documentation is not always fun.
(I have spent considerable hours, the doc is still incomplete.)
Git doc is easier as it describes specific commands, where GE has more 'flows' with commands combined.

**Review by gerhardol — APPROVED** [review]
Add icon too?
Otherwise fine for me
image

File: GitUI/CommandsDialogs/FormMergeBranch.cs (hunk 1 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormMergeBranch.cs:147]: No worries then.

**Comment by lhiginbotham** [comment]
> Add icon too? Otherwise fine for me 
image

@gerhardol @RussKie 

There is a class `GotoUserManualControl` which seems to be a help icon followed by a help link to a parameterizable help manual URL.  Sadly, I cannot seem to use this here as I get this error when trying to insert it via the designer:
image


And if this is a problem while using the designer, my guess is that if I manually insert it via code (not sure all the properties that would need set if going this route) then the designer probably would still be broken.

We can a) leave it as is, b) insert a plain icon and keep the plain link, or c) I'll need some help from one of you in figuring out how to get the GotoUserManualControl to work with the designer.

What do you think?

**Review by mstv — COMMENTED** [review]
+0, (i.e. technically OK, no veto)
Luckily, the information can be found at the top of the destination page - in this case...
(Users must live with English explanation only - regardless of that I prefer development tools in English myself, since a company switched to automated translation. And one does not need to guess the English wording when searching for help or reporting issues.)

**Comment by gerhardol** [comment]
> We can a) leave it as is, b) insert a plain icon and keep the plain link, or c) I'll need some help from one of you in figuring out how to get the GotoUserManualControl to work with the designer.

For me it is OK if the designer cannot be used to configure the page, if the designer does not crash.
But for now, I suggest to leave it as is.

**Comment by RussKie** [comment]
> +0, (i.e. technically OK, no veto) Luckily, the information can be found at the top of the destination page - in this case... (Users must live with English explanation only - regardless of that I prefer development tools in English myself, since a company switched to automated translation. And one does not need to guess the English wording when searching for help or reporting issues.)

I thought we had the docs translated

**Comment by gerhardol** [comment]
> I had a look, and apparently, we don't translate the docs. It looks like it's [configurable](https://docs.readthedocs.io/en/stable/localization.html#project-with-multiple-translations), but I must be dumb as I can't understand what's required.

https://readthedocs.org/dashboard/git-extensions-documentation/translations/

There are no subprojects with translations defined, and no attempts to translate (branches in the gitextdoc repo?)
But the doc need to be more comprehensive first, it is not up to date.

**Comment by gerhardol** [comment]
Thanks
Including in vNext only for now. This affects the translations, even if just removing a string, but builds will raise warnings.
