### PR TITLE
FileStatusList: Reuse context menu separators

### LINKED ISSUE #11909: Double context-menu divider for FormCommit's workspace items
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.45.2.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 144dpi (150% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 9.0.0-preview.7.24405.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

image

### Steps to reproduce

In `FormCommit`, rIght-click a file in the workspace.

### Did this work in previous version of GitExtensions?

This was introduced with 5.0.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11909

## Proposed changes

1. There are used different ContextMenuStrips for files and for submodules.
The menu items are added on menu open - and automatically removed from the other menu.
When re-adding them, the separators must not be created anew (as it is done for `_openInVisualStudioSeparator`).

2. Set the visibility of `FormCommit.toolStripSeparatorScript` as in https://github.com/gitextensions/gitextensions/commit/844050a9fd4a5d3a93a4888a2f6e5d424d7e1ac0 (done for all usages of `AddUserScripts`).

### Before

see issue

### After

no multiple separators

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
Looks OK. I cannot reproduce in master though

File: src/app/GitUI/UserControls/FileStatusList.cs [hunk 1]
```diff
@@ -31,6 +33,8 @@ public sealed partial class FileStatusList : GitModuleControl
         private readonly ToolStripItem _openInVisualStudioSeparator = new ToolStripSeparator();
         private readonly ToolStripItem _NO_TRANSLATE_openInVisualStudioMenuItem;
         private readonly CancellationTokenSequence _reloadSequence = new();
+        private readonly ToolStripItem _showAllDifferencesSeparator = new ToolStripSeparator() { Name = _showAllDifferencesItemName + "Separator" };
```
Comment (RussKie) [inline src/app/GitUI/UserControls/FileStatusList.cs:36]:
```suggestion
        private readonly ToolStripItem _showAllDifferencesSeparator = new ToolStripSeparator() { Name = $"{_showAllDifferencesItemName}Separator" };
```

File: src/app/GitUI/UserControls/FileStatusList.cs [hunk 2]
```diff
@@ -22,6 +22,8 @@ namespace GitUI
 {
     public sealed partial class FileStatusList : GitModuleControl
     {
+        private const string _showAllDifferencesItemName = "ShowDiffForAllParentsText";
```
Comment (RussKie) [inline src/app/GitUI/UserControls/FileStatusList.cs:25]:
```suggestion
        private const string ShowAllDifferencesItemName = nameof(ShowDiffForAllParentsText);
```

**Review by RussKie — APPROVED** [review]

File: src/app/GitUI/UserControls/FileStatusList.cs (hunk 2 above)
Comment (mstv) [reply src/app/GitUI/UserControls/FileStatusList.cs]: I have followed the naming conventions for `private` constants:

image

image

---

There is no such identifier `ShowDiffForAllParentsText` except in `TranslatedStrings`.
I have aligned the moved / new identifiers as well.

File: src/app/GitUI/UserControls/FileStatusList.cs (hunk 1 above)
Comment (mstv) [reply src/app/GitUI/UserControls/FileStatusList.cs]: Why?
It is compile-time constant.
And I would expect that a single concatenation of two (constant) strings is cheaper than string formatting.

Comment (RussKie) [reply src/app/GitUI/UserControls/FileStatusList.cs]: This seems like a premature micro optimisation. I trust the compiler to do the best here.
Interpolated strings are preferred to string concatenations.

Comment (mstv) [reply src/app/GitUI/UserControls/FileStatusList.cs]: > This seems like a premature micro optimisation. I trust the compiler to do the best here.
> Interpolated strings are preferred to string concatenations.

1. I have just moved that code.
2. I was anticipating your performance argument with which you use to reason the switch to interpolated strings.
  Only in case of a simple concatenation, the `+` is slightly clearer to me than interpolation.

Though in order to have a simple coding rule, I have changed it as requested.

Comment (drewnoakes) [reply src/app/GitUI/UserControls/FileStatusList.cs]: Interpolation with constants does not have runtime overhead.

https://sharplab.io/#v2:C4LglgNgPgxg9gOwM7AAQAECMAGVTUC8qARABICmEEcxA3ALABQTWAdFgJwAUAJMQN5IAvgBpUAdzgAnCABMAhMQCUtIA===
