### PR TITLE
Parse patch header with escape sequences

### LINKED ISSUE #11630: Broken diff of removed binary file with space in filename
- broken in f201220e8b77f5ab218277f60fd3e008c1ee5041
- Git 2.42.0.windows.1

This seems to occur with larger binary files only, e.g. with 42d7ee388078f8e8c360e200939c3e6886874927.

```
System.FormatException: Change not parsed correctly: Binary files a/src/file with space in name.ext and /dev/null differ
   at Patch GitCommands.Patches.PatchProcessor.CreatePatchFromString(string[] lines, Lazy<Encoding> filesContentEncoding, ref int lineIndex) in F:/Build/gitextensions3/GitCommands/Patches/PatchProcessor.cs:line 183
   at IEnumerable<Patch> GitCommands.Patches.PatchProcessor.CreatePatchesFromString(string patchText, Lazy<Encoding> filesContentEncoding)+MoveNext() in F:/Build/gitextensions3/GitCommands/Patches/PatchProcessor.cs:line 59
   at new System.Collections.Generic.List<T>(IEnumerable<T> collection)
   at async Task<(Patch patch, string errorMessage)> GitCommands.GitModule.GetSingleDiffAsync(ObjectId firstId, ObjectId secondId, string fileName, string oldFileName, string extraDiffArguments, Encoding encoding, bool cacheResult, bool isTracked, bool useGitColoring, GitCommandConfiguration commandConfiguration, CancellationToken cancellationToken) in F:/Build/gitextensions3/GitCommands/Git/GitModule.cs:line 2235
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, int? line, string defaultText, Action openWithDiffTool, string additionalCommandInfo)+GetItemPatchAsync(?) in F:/Build/gitextensions3/GitUI/GitUIExtensions.cs:line 222
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, int? line, string defaultText, Action openWithDiffTool, string additionalCommandInfo)+GetSelectedPatchAsync(?) in F:/Build/gitextensions3/GitUI/GitUIExtensions.cs:line 202
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, int? line, string defaultText, Action openWithDiffTool, string additionalCommandInfo) in F:/Build/gitextensions3/GitUI/GitUIExtensions.cs:line 156
   at async Task GitUI.CommandsDialogs.RevisionDiffControl.ShowSelectedFileDiffAsync(bool ensureNoSwitchToFilter, int? line) in F:/Build/gitextensions3/GitUI/CommandsDialogs/RevisionDiffControl.cs:line 607
   at async void GitUI.TaskManager.InvokeAndForget(Control control, Func<Task> asyncAction, CancellationToken cancellationToken)+(?) => { } [1] in F:/Build/gitextensions3/GitExtUtils/GitUI/TaskManager.cs:line 119
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in F:/Build/gitextensions3/GitExtUtils/GitUI/TaskManager.cs:line 32
```

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #11630

## Proposed changes

Add tests for escape sequences.

Add check for additional escape sequences in Debug builds, to monitor changes in Git.

Removed unused property IsCombinedDiff

## Test methodology 

Added tests

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

File: GitCommands/Patches/PatchProcessor.cs [hunk 1]
```diff
@@ -71,71 +88,54 @@ public static IEnumerable<Patch> CreatePatchesFromString(string patchText, Lazy<
...
+            patchText.Append(ReaddEscapes(rawHeader, header, contentMatch));
             if (lineIndex < lines.Length - 1)
             {
                 patchText.Append('\n');
             }
 
+            PatchProcessorState state = PatchProcessorState.InHeader;
+            PatchChangeType changeType = PatchChangeType.ChangeFile;
+            PatchFileType fileType = PatchFileType.Text;
+            ReadOnlySpan<char> index = null;
```
Comment (mstv) [inline GitCommands/Patches/PatchProcessor.cs:124]:
```suggestion
            ReadOnlySpan<char>? index = null;
```

File: GitCommands/Patches/PatchProcessor.cs [hunk 2]
```diff
@@ -211,50 +203,50 @@ public static IEnumerable<Patch> CreatePatchesFromString(string patchText, Lazy<
...
                     {
-                        throw new FormatException("New filename not parsed correctly: " + line);
+                        throw new FormatException($"Invalid patch header: {line}");
                     }
                 }
 
-                patchText.Append(line);
-
+                // patchText.Append($"{rawLine[..lineMatch.Index]}{line}{rawLine[(lineMatch.Index + lineMatch.Length)..]}");
+                patchText.Append(ReaddEscapes(rawLine, line, lineMatch));
```
Comment (mstv) [inline GitCommands/Patches/PatchProcessor.cs:249]: ditto
```suggestion
                patchText.Append(rawLine);
```

File: GitCommands/Patches/PatchProcessor.cs [hunk 3]
```diff
@@ -71,71 +88,54 @@ public static IEnumerable<Patch> CreatePatchesFromString(string patchText, Lazy<
...
 
+            PatchProcessorState state = PatchProcessorState.InHeader;
+            PatchChangeType changeType = PatchChangeType.ChangeFile;
+            PatchFileType fileType = PatchFileType.Text;
+            ReadOnlySpan<char> index = null;
+
             bool done = false;
             int i = lineIndex + 1;
-
             for (; i < lines.Length; i++)
```
Comment (mstv) [inline GitCommands/Patches/PatchProcessor.cs:128]:
```suggestion
            // Process patch header
            for (; i < lines.Length; i++)
```

**Review by mstv — COMMENTED** [review]
just nits

File: GitCommands/Patches/PatchProcessor.cs [hunk 4]
```diff
@@ -71,71 +88,54 @@ public static IEnumerable<Patch> CreatePatchesFromString(string patchText, Lazy<
                 return null;
             }
 
-            string header = lines[lineIndex];
-
-            Match headerMatch = PatchHeaderRegex().Match(header);
-
+            string rawHeader = lines[lineIndex];
+            Match contentMatch = EscapeSequenceRegex().Match(rawHeader);
+            ReadOnlySpan<char> header = contentMatch.Groups["line"].ValueSpan;
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/Patches/PatchProcessor.cs:93]: This is for two occurrences only, for the other the span is preferred. (probably no major difference)
So the temporary variable is explicitly nulled after use

File: GitCommands/Patches/PatchProcessor.cs [hunk 5]
```diff
@@ -71,71 +88,54 @@ public static IEnumerable<Patch> CreatePatchesFromString(string patchText, Lazy<
...
+            string fileNameA = headerMatch.Groups["filenamea"].Value.Trim();
+            string? fileNameB = isCombinedDiff ? null : headerMatch.Groups["filenameb"].Value.Trim();
 
-            string? index = null;
-            PatchChangeType changeType = PatchChangeType.ChangeFile;
-            PatchFileType fileType = PatchFileType.Text;
             StringBuilder patchText = new();
 
-            patchText.Append(header);
+            patchText.Append(ReaddEscapes(rawHeader, header, contentMatch));
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/Patches/PatchProcessor.cs:115]: Because header is decoded (not needed for the escapes)

File: GitCommands/Patches/PatchProcessor.cs [hunk 6]
```diff
@@ -71,71 +88,54 @@ public static IEnumerable<Patch> CreatePatchesFromString(string patchText, Lazy<
...
             int i = lineIndex + 1;
-
             for (; i < lines.Length; i++)
             {
-                string line = lines[i];
-
-                if (IsStartOfANewPatch(line))
+                string rawLine = lines[i];
+                Match lineMatch = EscapeSequenceRegex().Match(rawLine);
+                ReadOnlySpan<char> line = lineMatch.Groups["line"].ValueSpan;
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/Patches/PatchProcessor.cs:132]: similar to above, but only one use of ToString, so no change

File: GitCommands/Patches/PatchProcessor.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Patches/PatchProcessor.cs:124]: not a type

File: GitCommands/Patches/PatchProcessor.cs (hunk 2 above)
Comment (gerhardol) [reply GitCommands/Patches/PatchProcessor.cs:249]: no, same as above

File: GitCommands/Patches/PatchProcessor.cs (hunk 1 above)
Comment (mstv) [reply GitCommands/Patches/PatchProcessor.cs:127]: So it is kind of a C# syntax / compiler issue!

**Review by mstv — APPROVED** [review]

File: GitCommands/Patches/PatchProcessor.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Patches/PatchProcessor.cs:127]: image

but the DEBUG assert below was incorrect, updating...

**Comment by gerhardol** [comment]
I changed the Span<> handling to string (there were review comments). It probably was no noticeable difference right now, so string is simpler (the GitModule encoding interface need to use Span natively to make a change).
Also, the DEBUG assert could fire (all OK, this could be ignored).
Plan to merge tomorrow.

File: GitCommands/Patches/PatchProcessor.cs [hunk 7]
```diff
@@ -71,71 +89,57 @@ public static IEnumerable<Patch> CreatePatchesFromString(string patchText, Lazy<
...
-            string header = lines[lineIndex];
-
-            Match headerMatch = PatchHeaderRegex().Match(header);
-
+            string rawHeader = lines[lineIndex];
+            Match contentMatch = StripWrappingEscapesSequenceRegex().Match(rawHeader);
+            string header = contentMatch.Groups["line"].Value;
+#if DEBUG
+            DebugHelpers.Assert(!CheckAnyEscapeSequenceRegex().IsMatch(header), "Git unexpectedly emits escape sequences in first header other than at start/end. line {i}:{rawHeader}");
+#endif
```
Comment (mstv) [inline GitCommands/Patches/PatchProcessor.cs:97]: `DebugHelpers.Assert` is already debug-only as `Debug.WriteLineIf`, too, which could be an alternative.
```suggestion
            DebugHelpers.Assert(!CheckAnyEscapeSequenceRegex().IsMatch(header), "Git unexpectedly emits escape sequences in first header other than at start/end. line {i}:{rawHeader}");
```

File: GitCommands/Patches/PatchProcessor.cs [hunk 8]
```diff
@@ -71,71 +89,57 @@ public static IEnumerable<Patch> CreatePatchesFromString(string patchText, Lazy<
...
-                string line = lines[i];
-
-                if (IsStartOfANewPatch(line))
+                string rawLine = lines[i];
+                Match lineMatch = StripWrappingEscapesSequenceRegex().Match(rawLine);
+                string line = lineMatch.Groups["line"].Value;
+#if DEBUG
+                DebugHelpers.Assert(line.StartsWith("@@") || !CheckAnyEscapeSequenceRegex().IsMatch(line),
+                    $"Git unexpectedly emits escape sequences in header other than at start/end. line {i}:{rawLine}");
+#endif
```
Comment (mstv) [inline GitCommands/Patches/PatchProcessor.cs:139]: ditto

**Review by mstv — APPROVED** [review]

File: GitCommands/Patches/PatchProcessor.cs (hunk 7 above)
Comment (gerhardol) [reply GitCommands/Patches/PatchProcessor.cs:97]: But `CheckAnyEscapeSequenceRegex()` is in DEBUG so this change will require that the Regex is included in Release builds (at least as a dummy returning false). I suggest to keep this as is.

Comment (mstv) [reply GitCommands/Patches/PatchProcessor.cs:97]: > But `CheckAnyEscapeSequenceRegex()` is in DEBUG so this change will require that the Regex is included in Release builds (at least as a dummy returning false). I suggest to keep this as is.

OK, I see now. It seems to be the week of unexpected limitations of C#.
