### PR TITLE
Make ExecuteAsync cancellable and kill canceled processes

### LINKED ISSUE #9418: Cancel unfinished/hanging `git log`
Most likely a git issue:
I have filtered with `Diff contains (SLOW)`. But the git command has not returned for almost 6 hours - I guess due to a child process `astextplain`. `pdf2text.exe` seems to block in conjunction with a pipe to `"C:\Program Files\Git\usr\bin\sed.exe" s/(\^M$)|(^\^L)//`.
After killing `pdf2text.exe`, another one is started for the next PDF.
These PDFs are stored in Git LFS. But the temp files have not been expanded.

This even blocks GE from switching repos.
I agree with @gerhardol: A yet running `git log` command should be canceled/killed when refreshing the RevisionGrid.

grafik

- Git Extensions 33.33.33
- Build 825d3803734c4ef29c94eb32feb42614c3f4d2f3
- Git 2.30.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 5.0.5
- DPI 96dpi (no scaling)

_Originally posted by @mstv in https://github.com/gitextensions/gitextensions/issues/9393#issuecomment-887565028_

### LINKED ISSUE #9818: Cancelation of a process leaves the process running
### Environment

- Git Extensions 33.33.33
- Build 406acbf9e4223d3587bc97dbf42907b931154602
- Git 2.34.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.13
- DPI 96dpi (no scaling)

### Issue description

#9522 introduced cancellation token support for executables, to exit the executable if the token is cancelled.
However, the corresponding process itself continues to run to exit.

Blaming in the file tree and switch files before git-blame is done will in master not cancel the executable, there can be several git-blame running simultaneously (git-blame can take a minute for en_pseudo.xlf in GE for example).
Cancellation as in #9816 will not really improve the situation, as git-blame continues to run.

It could be possible to kill the processes if the executable is canceled.

### Steps to reproduce

In master: 
* FileTree, Blame
* Repeatedly change file (for instance .xlf files)
* View running processes, see simultaneous Git processes increase

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #9818
Preparation for #9418

## Proposed changes

- `Executable`:
  - Kill the process on disposal if cancellation was requested
  - Factor out `HandleProcessExit` from `OnProcessExit`
- `GitCommandRunner`:
  - `RunDetached` with and without cancellation
  - log exit code
- Make cancellation of `ExecuteAsync(this IExecutable executable, ...)` work: await exit first, then await the output with cancellation
- `RevisionReader`: Start processes with cancellation

## Screenshots 

N/A

## Test methodology 

- add tests

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
I have finally found how to cancel started processes (including in tests). This is done by hard killing.
So I think this should not be integrated into the upcoming release yet.
But you could use it in your DI branch, @RussKie.

File: GitCommands/Git/Executable.cs [hunk 1]
```diff
@@ -220,6 +221,27 @@ public StreamReader StandardError
                 }
             }
 
+            /// <inheritdoc />
```
Comment (RussKie) [inline GitCommands/Git/Executable.cs:224]: [nit] This is not required, the intellisense is smart enough to look up the docs when inheriting.

File: GitCommands/Git/Executable.cs [hunk 2]
```diff
@@ -220,6 +221,27 @@ public StreamReader StandardError
...
+            public async Task TerminateAsync(bool entireProcessTree = true, bool tryCtrlC = true, int exitTimeoutMilliseconds = IProcess.DefaultExitTimeoutMilliseconds)
```
Comment (RussKie) [inline GitCommands/Git/Executable.cs:225]: Is there a scenario where `entireProcessTree = false`?

File: GitCommands/Git/Extensions/ProcessExtensions.cs [hunk 3]
```diff
@@ -1,40 +1,70 @@
...
+            if (!NativeMethods.AttachConsole(process.Id) && Marshal.GetLastWin32Error() != NativeMethods.AlreadyAttachedToConsole)
+            {
+                return false;
+            }
+
+            try
+            {
+                _ = NativeMethods.SetConsoleCtrlHandler(IntPtr.Zero, add: true);
+
+                return NativeMethods.GenerateConsoleCtrlEvent(0, 0);
```
Comment (RussKie) [inline GitCommands/Git/Extensions/ProcessExtensions.cs:29]: Why <kbd>CTRL+C</kbd> and not <kbd>CTRL+BREAK</kbd>?
image

File: GitCommands/Git/Extensions/ProcessExtensions.cs [hunk 4]
```diff
@@ -1,40 +1,70 @@
...
-                process.Kill();
             }
+
+            process.Kill(entireProcessTree: true);
         }
 
         private static class NativeMethods
         {
+            public const int ERROR_ACCESS_DENIED = 5;
+            public const int AlreadyAttachedToConsole = ERROR_ACCESS_DENIED; // https://learn.microsoft.com/en-us/windows/console/attachconsole
```
Comment (RussKie) [inline GitCommands/Git/Extensions/ProcessExtensions.cs:57]:
```suggestion
            // https://learn.microsoft.com/windows/console/attachconsole
            public const int AlreadyAttachedToConsole = ERROR_ACCESS_DENIED;
```

File: Plugins/GitUIPluginInterfaces/IProcess.cs [hunk 5]
```diff
@@ -10,6 +10,8 @@ namespace GitUIPluginInterfaces
     /// </remarks>
     public interface IProcess : IDisposable
     {
+        const int DefaultExitTimeoutMilliseconds = 500;
```
Comment (RussKie) [inline Plugins/GitUIPluginInterfaces/IProcess.cs:13]: Make it `ushort`?

**Review by RussKie — APPROVED** [review]
🚀 

I'm going to pull it in and try.

**Review by gerhardol — COMMENTED** [review]
+1

File: GitCommands/Git/Executable.cs (hunk 2 above)
Comment (mstv) [reply GitCommands/Git/Executable.cs:225]: > Is there a scenario where `entireProcessTree = false`?

I think we should call it with `false` in order to not kill e.g. a diff tool with unsaved user changes by mistake.
Since the other value is not used, I can remove the argument in the next fixup commit.

File: GitCommands/Git/Extensions/ProcessExtensions.cs (hunk 3 above)
Comment (mstv) [reply GitCommands/Git/Extensions/ProcessExtensions.cs:29]: Ctrl+Break kills the current process, too. Then f.i. the test runner is killed and does not yield test results.
I tried to intercept it by setting a handler using `SetConsoleCtrlHandler`. The handler was not called.

File: Plugins/GitUIPluginInterfaces/IProcess.cs (hunk 5 above)
Comment (mstv) [reply Plugins/GitUIPluginInterfaces/IProcess.cs:13]: Why? This is given to `Process.WaitForProcess(int milliseconds)`.

**Comment by RussKie** [comment]
@mstv I pulled your branch into https://github.com/gitextensions/gitextensions/pull/11142 and ran 21 iterations of the tests, and I couldn't get a failure whereas without your change it'd fail (hang) on a second or third iteration.
image

**Review by gerhardol — COMMENTED** [review]
+1
Seem fine, have not used it

**Comment by RussKie** [comment]
Merge?

**Comment by mstv** [comment]
I have generalized it for `Executable` instead of only for `ExecuteAsync` before.

#9418 should be fixed in a follow-up: `RevisionGridControl.PerformRefreshRevisions()` denies(!) to cancel the loading because `CanRefresh` is too restrictive.

File: Plugins/GitUIPluginInterfaces/IExecutable.cs [hunk 6]
```diff
@@ -32,6 +32,7 @@ public interface IExecutable
                        bool redirectOutput = false,
                        Encoding? outputEncoding = null,
                        bool useShellExecute = false,
-                       bool throwOnErrorExit = true);
+                       bool throwOnErrorExit = true,
+                       CancellationToken? cancellationToken = null);
```
Comment (RussKie) [inline Plugins/GitUIPluginInterfaces/IExecutable.cs:36]:
```suggestion
                       CancellationToken cancellationToken = default);
```

File: UnitTests/CommonTestUtils/MockExecutable.cs [hunk 7]
```diff
@@ -65,7 +65,15 @@ public void Verify()
...
-        public IProcess Start(ArgumentString arguments, bool createWindow, bool redirectInput, bool redirectOutput, Encoding outputEncoding, bool useShellExecute = false, bool throwOnErrorExit = true)
+        public IProcess Start(
+            ArgumentString arguments,
+            bool createWindow,
+            bool redirectInput,
+            bool redirectOutput,
+            Encoding outputEncoding,
+            bool useShellExecute = false,
+            bool throwOnErrorExit = true,
+            CancellationToken? cancellationToken = null)
```
Comment (RussKie) [inline UnitTests/CommonTestUtils/MockExecutable.cs:76]:
```suggestion
            CancellationToken cancellationToken = default)
```

File: GitCommands/Git/Executable.cs [hunk 8]
```diff
@@ -27,14 +27,14 @@ public Executable(Func<string> fileNameProvider, string workingDir = "", string
...
-        /// <inheritdoc />
         public IProcess Start(ArgumentString arguments = default,
                               bool createWindow = false,
                               bool redirectInput = false,
                               bool redirectOutput = false,
                               Encoding? outputEncoding = null,
                               bool useShellExecute = false,
-                              bool throwOnErrorExit = true)
+                              bool throwOnErrorExit = true,
+                              CancellationToken? cancellationToken = null)
```
[the remark this answers is not in the document]
Comment (mstv) [reply GitCommands/Git/Executable.cs]: I was too defensive - changed. Since `CancellationToken.None` is never canceled, we can be pretty sure that no process is killed by mistake.

File: GitCommands/Git/Executable.cs [hunk 9]
```diff
@@ -135,50 +139,56 @@ private sealed class ProcessWrapper : IProcess
...
+                                    _process.StartInfo.Arguments,
+                                    _process.StartInfo.WorkingDirectory,
+                                    exitCode,
+                                    new Exception(errorMessage));
+                        if (exitCode == NativeMethods.STATUS_CONTROL_C_EXIT)
                         {
-                            int exitCode = _process.ExitCode;
-                            _logOperation.LogProcessEnd(exitCode);
+                            ex = new OperationCanceledException("Ctrl+C pressed or console closed", ex);
+                        }
```
[the remark this answers is not in the document]
Comment (mstv) [reply GitCommands/Git/Executable.cs:162]: The EOE is used as inner exception of the OCE and should appear in the Git Command Log.
This exit code occurs only on user interaction.
(This code has just been moved and unindented.)

File: GitCommands/Git/Executable.cs [hunk 10]
```diff
@@ -243,11 +248,39 @@ public void Dispose()
...
 
                     _disposed = true;
-                }
 
-                _process.Exited -= OnProcessExit;
+                    if (!_exitHandlerRemoved)
+                    {
+                        // HandleProcessExit directly, do not rely on event execution
+                        _process.Exited -= OnProcessExit;
+                        _exitHandlerRemoved = true;
```
[the remark this answers is not in the document]
Comment (mstv) [reply GitCommands/Git/Executable.cs:256]: > Do we really need the flag?

`_exitHandlerRemoved` is also evaluated in `Dispose` in order to not call `HandleProcessExit` twice etc.

File: GitCommands/Git/Executable.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/Git/Executable.cs:162]: Oh, I totally missed that. Thank you for the clarification.

**Review by RussKie — APPROVED** [review]
🚀

**Comment by RussKie** [comment]
Can we merge this?
