### PR TITLE
working around context menu strip being positioned incorrectly on first open

### LINKED ISSUE #10165: Context menu on origin appears at top of screen
### Environment

- GitExtensions version: 4.0.0.15025
- GIT version: 2.37.1.windows.1
- OS version: Microsoft Windows NT 10.0.19042.0
- .NET version: 6.0.8

### Issue description

The first time the Context menu on Remotes-->origin is invoked by right-clicking, the context menu appears at the top of the screen:
image

Second and subsequent invocations of the Context menu on origin render the Context menu in the expected location:
image

### Steps to reproduce

1) Open GitExtensions
2) Select a repository
3) Right-click on origin under Remotes
4) Context menu is rendered at the top of the screen rather than near where the right-click was made.

### Did this work in previous version of GitExtensions?

Yes. Previous version of GitExtensions, v3.5.4.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by h0lg**
No idea why this happens. I found [this question on stackoverflow](https://stackoverflow.com/questions/15841863/why-does-my-menustrip-appear-in-the-incorrect-location-on-first-click) in which some folk suggest it may be a Windows Forms bug and how to work around it.
I didn't like the proposed work arounds much and think I've found a simpler one that works for me. Please try it and see if your mileage varies.

Fixes #10165

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — APPROVED** [review]
LGTM

**Comment by h0lg** [comment]
> it may be a Windows Forms bug

RussKie confirmed that suspicion in https://github.com/gitextensions/gitextensions/issues/10165#issuecomment-1250537805 .

**Review by RussKie — APPROVED** [review]
This looks good as a tactical fix 
Thank you

File: GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs [hunk 1]
```diff
@@ -245,9 +245,9 @@ private void contextMenu_Opening(object sender, CancelEventArgs e)
 
         private void contextMenu_Opened(object sender, EventArgs e)
         {
-            // Waiting for ContextMenuStrip (as the visual parent of its menu items) to be visible to
+            // Waiting for the ContextMenuStrip (as the visual parent of its menu items) to be visible to
             // toggle (depending on ToolStripItem.Visible) existing separators in between item groups as required.
-            (sender as ContextMenuStrip)?.ToggleSeparators();
+            menuMain.ToggleSeparators();
```
Comment (RussKie) [inline GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs:250]: Why did this change?

File: GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs [hunk 2]
```diff
@@ -244,9 +244,18 @@ private void contextMenu_Opening(object sender, CancelEventArgs e)
...
+            // Waiting for the ContextMenuStrip (as the visual parent of its menu items) to be visible to
+            // toggle (depending on ToolStripItem.Visible) existing separators in between item groups as required.
+            menuMain.ToggleSeparators();
+
+            // Working around the context menu strip being positioned incorrectly on first open - which may be a Windows Forms bug,
+            // see https://stackoverflow.com/q/15841863/2338036.
+            if (menuMain.Top != Cursor.Position.Y)
+            {
+                menuMain.Top = Cursor.Position.Y;
+            }
```
Comment (RussKie) [inline GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs:257]:
```suggestion
            if (sender is not ContextMenuStrip contextMenu)
            {
                return;
            }

            // Waiting for the ContextMenuStrip (as the visual parent of its menu items) to be visible to
            // toggle (depending on ToolStripItem.Visible) existing separators in between item groups as required.
            contextMenu.ToggleSeparators();

            // Working around the context menu strip being positioned incorrectly on first open - which may be a Windows Forms bug,
            // see https://stackoverflow.com/q/15841863/2338036.
            if (contextMenu.Top != Cursor.Position.Y)
            {
                contextMenu.Top = Cursor.Position.Y;
            }
```

File: GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs (hunk 1 above)
Comment (h0lg) [reply GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs:250]: To simplify and avoid gas-lighting developers into thinking this to be a generic Opened event handler that is used by context menus other than `menuMain`. Your more generic solution works for me tho!

**Review by RussKie — APPROVED** [review]
Thank you
