### PR TITLE
Check for empty language selection

### LINKED ISSUE #6726: ArgumentOutOfRangeException [not] selecting a language on first start
## Current behaviour / STR

Start a [portable] build for the first time.
Confirm the language selection with `Enter`.
Exception although `English` seems to be selected.

grafik

Not a duplicate of #6680.

## Expected behaviour

English does not need to be clicked or reselected by moving around with cursor keys.

## Error Details
```
System.ArgumentOutOfRangeException: InvalidArgument=Value mit dem Wert 0 ist für index ungültig.
Parametername: index
   bei System.Windows.Forms.ListView.SelectedListViewItemCollection.get_Item(Int32 index)
   bei GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation.lvTranslations_ItemActivate(Object sender, EventArgs e)
   bei System.Windows.Forms.ListView.OnItemActivate(EventArgs e)
   bei System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   bei System.Windows.Forms.ListView.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.2.0.5989
- Build c992852437f8ef975388a34002d321c72620df85 (Dirty)
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by mstv**
Fixes #6726

## Proposed changes

- use the `FormChooseTranslation`'s fallback in case of empty selection

## Test methodology 

- manual

## Test environment(s)

- Git Extensions 3.2.0
- Build 3972aa02f5e29c9a4256ff56d51eb42219a636ea
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/SettingsDialog/Pages/FormChooseTranslation.cs [hunk 1]
```diff
@@ -67,7 +67,13 @@ private void FormChooseTranslation_FormClosing(object sender, FormClosingEventAr
 
         private void lvTranslations_ItemActivate(object sender, EventArgs e)
         {
-            AppSettings.Translation = ((ListView)sender).SelectedItems[0].Tag.ToString();
+            var selectedItems = ((ListView)sender).SelectedItems;
+            if (selectedItems.Count > 0)
+            {
+                AppSettings.Translation = selectedItems[0].Tag.ToString();
+            }
+            //// else see fallback in FormChooseTranslation_FormClosing
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/FormChooseTranslation.cs]: nitpick: This is a comment rather than commented code, I suggest to use //
(apreciate the comment though)

Comment (mstv) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/FormChooseTranslation.cs]: Then StyleCop would enforce an empty line above the comment...

Comment (gerhardol) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/FormChooseTranslation.cs]: I would have put the comment after line 72
