### PR TITLE
Remember blame splitter position

### LINKED ISSUE #12225: Blame shows no content, only commits
### Environment

- Git Extensions 5.2.1.18061
- Build 0d74cfdc312df90114a0cf8d6c8a30ca4213e2ff
- Git 2.48.1.windows.1
- Microsoft Windows NT 10.0.26100.0
- .NET 8.0.13
- DPI 192dpi (200% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 9.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Image
File content next to commit markers is missing.

### Steps to reproduce

Image

### Did this work in previous version of GitExtensions?

Image

Started in  
- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.48.1.windows.1
- Microsoft Windows NT 10.0.26100.0
- .NET 8.0.13
- DPI 192dpi (200% scaling)
- Portable: True
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 9.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Image

Worked in 
- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.48.1.windows.1
- Microsoft Windows NT 10.0.26100.0
- .NET 6.0.36
- DPI 192dpi (200% scaling)
- Portable: True
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 9.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mdonatas**
Fixes #12225

## Proposed changes

- Save/remember BlameControl's splitter positions

One caveat is that without the user adjusting splitter's position at least once, the "broken" state will remain. I haven't found an easy and sensible way to set some kind of default for the splitter.

## Test methodology 

- Manual. I've been running custom build with this commit for a little bit over 1 year and didn't have a problem with Blame ever since.

## Test environment(s) 

- Windows 11 200% scaling

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by vbjay** [comment]
Detect less than x value for splitter width or height for each splitter and reset to reasonable value if detected. That way app auto fixes to at least show both sides. Make x small so that it doesn't reset when user wants it small. But example doesn't make sense to be 20 pixels wide for the code side. 

OR
Add menu to view menu that resets splitters to middle either width or height if vertical or horizontal. Then let user hit menu to autofit all splitters.

**Comment by mstv** [comment]
Did you want to comment to the orthogonal improvement by #12250, @vbjay?

File: src/app/GitUI/UserControls/BlameControl.cs [hunk 1]
```diff
@@ -82,6 +82,12 @@ public BlameControl()
             _gitBlameParser = new GitBlameParser(() => UICommands.Module);
         }
 
+        public void InitSplitterManager(SplitterManager splitterManager, string parentContainer)
+        {
+            splitterManager.AddSplitter(splitContainer1, $"{parentContainer}.BlameSplitContainer1");
+            splitterManager.AddSplitter(splitContainer2, $"{parentContainer}.BlameSplitContainer2");
```
Comment (mstv) [inline src/app/GitUI/UserControls/BlameControl.cs:88]:
```suggestion
        public void InitSplitterManager(SplitterManager splitterManager, string parentContainerPrefix)
        {
            string containerPrefix = $"{parentContainerPrefix}{Name}.";     
            splitterManager.AddSplitter(splitContainer1, $"{containerPrefix }{nameof(splitContainer1)}");
            splitterManager.AddSplitter(splitContainer2, $"{containerPrefix }{nameof(splitContainer1)}");
```

File: src/app/GitUI/CommandsDialogs/RevisionFileTreeControl.cs [hunk 2]
```diff
@@ -163,6 +163,7 @@ public void ExpandToFile(string filePath, int? line, bool requestBlame)
         public void InitSplitterManager(SplitterManager splitterManager)
         {
             splitterManager.AddSplitter(FileTreeSplitContainer, "FileTreeSplitContainer");
+            BlameControl.InitSplitterManager(splitterManager, "RevisionFileTree");
```
Comment (mstv) [inline src/app/GitUI/CommandsDialogs/RevisionFileTreeControl.cs:166]: There is no need to adapt this because the `RevisionFileTreeControl` class will be deleted when it will be replaced with `RevisionDiffControl` in the near future.

**Comment by vbjay** [comment]
> Did you want to comment to the orthogonal improvement by #12250, @vbjay?

Yes. Sorry. Just saw this pr.

File: src/app/GitUI/CommandsDialogs/RevisionFileTreeControl.cs (hunk 2 above)
Comment (mdonatas) [reply src/app/GitUI/CommandsDialogs/RevisionFileTreeControl.cs]: Doesn't hurt though :)

**Comment by mdonatas** [comment]
Addressed comments. Commit `Use parent container Names rather than custom values`
Also, added default value initialization, which really helps!

Here are the screenshots with 100% and 200% scaling when opening GE with splitter settings not yet saved

`100%`
image

`200%`
image

File: src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 3]
```diff
@@ -346,6 +346,7 @@ public void InitSplitterManager(SplitterManager splitterManager)
         {
             splitterManager.AddSplitter(DiffSplitContainer, nameof(DiffSplitContainer));
             splitterManager.AddSplitter(LeftSplitContainer, $"{nameof(RevisionDiffControl)}.{nameof(LeftSplitContainer)}");
+            BlameControl.InitSplitterManager(splitterManager, parentContainerPrefix: Name);
```
Comment (mstv) [inline src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs:349]: `parentContainerPrefix: Name` may work for this PR. But it is not exactly what is meant. The _prefix_ shall contain the trailing dot - in order to apply this as generic pattern in a follow-up PR.

File: src/app/GitUI/SplitterManager.cs [hunk 4]
```diff
@@ -99,6 +99,10 @@ public void RestoreFromSettings(SettingsSource settings)
                         }
                     }
                 }
+                else if (_defaultDistance.HasValue)
+                {
+                    SetSplitterDistance(_defaultDistance.Value);
```
Comment (mstv) [inline src/app/GitUI/SplitterManager.cs:104]: I think this change will make it impossible to persist the collapsed state, e.g. of the Left Panel IIRC.

Comment (mdonatas) [reply src/app/GitUI/SplitterManager.cs:106]: I've changed this to also check for whether there hasn't been a setting saved before. By the way, this overload is not used anywhere else at the moment.

File: src/app/GitUI/UserControls/BlameControl.cs [hunk 5]
```diff
@@ -6,6 +6,7 @@
 using GitExtensions.Extensibility.Git;
 using GitExtensions.Extensibility.Plugins;
 using GitExtUtils;
+using GitExtUtils.GitUI;
```
Comment (mstv) [inline src/app/GitUI/UserControls/BlameControl.cs:9]: MSVS was hyperactive most likely.
```suggestion
```

File: src/app/GitUI/UserControls/BlameControl.cs [hunk 6]
```diff
@@ -82,6 +83,13 @@ public BlameControl()
             _gitBlameParser = new GitBlameParser(() => UICommands.Module);
         }
 
+        public void InitSplitterManager(SplitterManager splitterManager, string parentContainerPrefix)
+        {
+            string containerPrefix = $"{parentContainerPrefix}{Name}.";
+            splitterManager.AddSplitter(splitContainer1, $"{containerPrefix}{splitContainer1.Name}", defaultDistance: splitContainer1.Panel1MinSize + 1);
+            splitterManager.AddSplitter(splitContainer2, $"{containerPrefix}{splitContainer2.Name}", defaultDistance: splitContainer2.Panel1MinSize + 1);
```
Comment (mstv) [inline src/app/GitUI/UserControls/BlameControl.cs:90]: What is the clue behind `+ 1`?

**Review by mstv — COMMENTED** [review]
👍
final nits

**Comment by mstv** [comment]
`verified` files need an update yet.

File: src/app/GitUI/UserControls/BlameControl.cs (hunk 6 above)
Comment (mdonatas) [reply src/app/GitUI/UserControls/BlameControl.cs:90]: There is a validation in a `SplitterManager` where this has to be true. https://github.com/mdonatas/gitextensions/blob/remember-blame-splitter-pos/src/app/GitUI/SplitterManager.cs#L147-L150

I suppose the logic is that the splitter can't occupy the same position as `panel1` at it's smallest size as that would require it to get even smaller to leave space for the splitter and it can't.

File: src/app/GitUI/UserControls/BlameControl.cs (hunk 5 above)
Comment (mstv) [reply src/app/GitUI/UserControls/BlameControl.cs:9]: superfluous addition

Comment (mdonatas) [reply src/app/GitUI/UserControls/BlameControl.cs]: Oops, removed

**Review by mstv — APPROVED** [review]

**Comment by mdonatas** [comment]
Added several tests for SplitterManager to cover default value bahavior

**Comment by mstv** [comment]
I have squashed, resolved the MC and made use of `NestedSplitterManager`: mstv/remember-blame-splitter-pos: 00ee78a5ab8b2ce00d9c8638905cd41e2b5bea33.
mstv/remember-blame-splitter-pos-before_squash: 77cd75eb46be6336fa804d45066aa18d9fc3d8ec
mstv/remember-blame-splitter-pos-squashed: 90ce5920be3c1e224bd22a82b7193fa47eb43fbb

**Comment by mstv** [comment]
> I have squashed, resolved the MC and made use of `NestedSplitterManager`: mstv/remember-blame-splitter-pos: [00ee78a](https://github.com/gitextensions/gitextensions/commit/00ee78a5ab8b2ce00d9c8638905cd41e2b5bea33).
> mstv/remember-blame-splitter-pos-before_squash: [77cd75e](https://github.com/gitextensions/gitextensions/commit/77cd75eb46be6336fa804d45066aa18d9fc3d8ec)
> mstv/remember-blame-splitter-pos-squashed: [90ce592](https://github.com/gitextensions/gitextensions/commit/90ce5920be3c1e224bd22a82b7193fa47eb43fbb)

friendly nudge, @mdonatas

**Comment by mdonatas** [comment]
> > I have squashed, resolved the MC and made use of `NestedSplitterManager`: mstv/remember-blame-splitter-pos: [00ee78a](https://github.com/gitextensions/gitextensions/commit/00ee78a5ab8b2ce00d9c8638905cd41e2b5bea33).
> > mstv/remember-blame-splitter-pos-before_squash: [77cd75e](https://github.com/gitextensions/gitextensions/commit/77cd75eb46be6336fa804d45066aa18d9fc3d8ec)
> > mstv/remember-blame-splitter-pos-squashed: [90ce592](https://github.com/gitextensions/gitextensions/commit/90ce5920be3c1e224bd22a82b7193fa47eb43fbb)
> 
> friendly nudge, @mdonatas

Thanks for the nudge and sorry for my absence.. life is getting in the way of coding 😅

I've gone and rebased the branch, also made use of the `NestedSplitterManager` like you have in `mstv/remember-blame-splitter-pos` branch. Now this and your `mstv/remember-blame-splitter-pos` don't have splitter related differences.

I've done some manual testing again and blame splitter position is persisted.

**Review by mstv — APPROVED** [review]

**Review by mstv — APPROVED** [review]
Thank you

**Review by RussKie — APPROVED** [review]
