### PR TITLE
Check that directory (still) exists

### LINKED ISSUE #6812: [NBug] Erreur lors de la lecture du répertoire I:\gitLabCloud\clara\.
## Current behaviour
application crashes

## Expected behaviour
git project is expected to be closed

## Steps to reproduce

Open a git project located in an external hard drive. Disconnect external hard drive and this error will occur

## Error Details
```
System.IO.FileNotFoundException: Erreur lors de la lecture du répertoire I:\gitLabCloud\clara\.
   à System.IO.FileSystemWatcher.StartRaisingEvents()
   à GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.Update()
   à System.Windows.Forms.Timer.OnTick(EventArgs e)
   à System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
external hard drive disconnected

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.3801.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
before renabling the the FileWatcher for GitStatusMonitor

Fixes #6812

## Proposed changes

FileSystemWatcher is deactivated when the need for an update is determined and restarted when the timer fires and GE is to start a new git-status.
When (re)activating FileSystemWatcher the control raises an exception if the directory does not exist.
This change skips starting file system watcher (and git-status) and relies on the periodic 5 minute timer retry. (Normally, if a directory is no longer available the user should know about it and refresh if necessary.) 

## Test methodology

Manual (see the issue).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs [hunk 1]
```diff
@@ -198,8 +198,16 @@ private GitStatusMonitorState CurrentStatus
...
                         {
                             _timerRefresh.Start();
-                            _workTreeWatcher.EnableRaisingEvents = true;
-                            _gitDirWatcher.EnableRaisingEvents = !_gitDirWatcher.Path.StartsWith(_workTreeWatcher.Path);
+                            if (Directory.Exists(_workTreeWatcher.Path))
+                            {
+                                _workTreeWatcher.EnableRaisingEvents = true;
+                            }
+
+                            if (!Directory.Exists(_gitDirWatcher.Path))
```
Comment (mstv) [inline GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: I have not digged into the details. Shall this really be done only if the directory does not exist yet?

Comment (gerhardol) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: remains of my testing....

**Comment by RussKie** [comment]
The status monitor looks arcane to me... I've looked at the changes, they seem ok, but I don't really understand what's going on (likely I haven't spent enough time going through the code).

The fact that it is an important piece of functionality and we do not have any tests for it worries me greatly.

**Comment by gerhardol** [comment]
Squashed and rebased. This PR should not be controversial, any follow up can be done in #6844 
Merging tomorrow if not someone else does it before me.
