### PR TITLE
Consider non-existent config setting for remote branch

### LINKED ISSUE #12355: [NBug] Object reference not set to an instance of an object.
### Environment

- Git Extensions 33.33.33
- Build c87ff370c18756d176adc83c78644db1645eb19d (Dirty)
- Git 2.47.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 9.0.4
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitCommands.GitModule.GetLocalTrackingBranchName(String remoteName, String branch) in C:\Users\Pavel\Projects\GitExtensions\src\app\GitCommands\Git\GitModule.cs:line 3941
   at GitUI.CommandsDialogs.FormCheckoutBranch.Branches_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\Pavel\Projects\GitExtensions\src\app\GitUI\CommandsDialogs\FormCheckoutBranch.cs:line 456
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at GitUI.CommandsDialogs.FormCheckoutBranch..ctor(IGitUICommands commands, String branch, Boolean remote, IReadOnlyList`1 containRevisions) in C:\Users\Pavel\Projects\GitExtensions\src\app\GitUI\CommandsDialogs\FormCheckoutBranch.cs:line 70
   at GitUI.GitUICommands.<>c__DisplayClass76_0.<StartCheckoutBranch>b__0() in C:\Users\Pavel\Projects\GitExtensions\src\app\GitUI\GitUICommands.cs:line 352
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\Users\Pavel\Projects\GitExtensions\src\app\GitUI\GitUICommands.cs:line 323
   at GitUI.GitUICommands.StartCheckoutBranch(IWin32Window owner, String branch, Boolean remote, IReadOnlyList`1 containRevisions) in C:\Users\Pavel\Projects\GitExtensions\src\app\GitUI\GitUICommands.cs:line 350
   at GitUI.GitUICommands.StartCheckoutRemoteBranch(IWin32Window owner, String branch) in C:\Users\Pavel\Projects\GitExtensions\src\app\GitUI\GitUICommands.cs:line 364
   at GitUI.RevisionGridControl.<>c__DisplayClass180_4.<ContextMenuOpening>b__11(Object <p0>, EventArgs <p1>) in C:\Users\Pavel\Projects\GitExtensions\src\app\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 2083
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### Steps to reproduce

In the revision grid, open the context menu on a remote branch which does not have a local tracking branch and click Checkout branch.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by crypto-rsa**
Fixes #12355.

## Test methodology 

- Manual

## Test environment(s) 

- GIT 2.47.0.windows.2
- Windows 10

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by crypto-rsa** [comment]
@RussKie what do I need to do to get the PR merged? The AppVeyor build has failed (though it seems for an unrelated reason) and as per the note here I'm not authorized to push to the `master` branch.

File: src/app/GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -3941,7 +3941,7 @@ public override string ToString()
                 (string section, string? subsection, string name) = IGitConfigSettingsGetter.SplitSetting(setting);
                 if (section == "branch" && name == "remote" && value == remoteName)
                 {
-                    string remoteBranch = localGitConfigSettings.GetValue($"{section}.{subsection}.merge").Replace("refs/heads/", string.Empty);
+                    string remoteBranch = localGitConfigSettings.GetValue($"{section}.{subsection}.merge")?.Replace("refs/heads/", string.Empty);
```
Comment (gerhardol) [inline src/app/GitCommands/Git/GitModule.cs]:
```suggestion
                    string? remoteBranch = localGitConfigSettings.GetValue($"{section}.{subsection}.merge")?.Replace("refs/heads/", string.Empty);
```
```suggestion
                    string remoteBranch = localGitConfigSettings.GetValue($"{section}.{subsection}.merge")?.Replace("refs/heads/", string.Empty);
```

**Review by mstv — APPROVED** [review]
