### PR TITLE
Fix "Delete all" context action on branch folder in left panel

### LINKED ISSUE #6068: Delete All no longer works - "not selectable"
## Current behaviour

When you have some branches that begin with the same prefix followed by a "/", such as "feature/abc" and "feature/cba", right clicking the directory icon in the branches pane and clicking "Delete all", the resulting command gives an error: "Branch "feature/cba," is not selectable, this branch has been removed from the selection. The command will only delete the last branch in the list. Removing all the commas from the text field before clicking Delete fixes the problem.

## Expected behaviour

The text field should not contain commas, so that the command succeeds without manual editing being necessary.

## Screenshots

Delete All plus error message

## Did this work in previous version of GitExtensions

Yes, this worked in GitExtensions 2.51 using Git 1.9.4. I upgraded to Git 2.20 in order to use GitExtensions 3, and this introduced this problem for me.

## Environment

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.20.0.rc1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3130.0
- DPI X:100,00 % Y:100,00 %

### PR DESCRIPTION
**Pull request by amaiorano**
FormDeleteBranch expects a space-separated list of branches, not comma-separated.
Also opportunistically modified call to UICommands.StartDeleteBranchDialog to use overload that takes a single branch.

Fixes #6068

### Before

image

### After

image

## Test methodology 

- Manual testing
- Made sure Delete All, then Delete and Select multiple branches functionality in FormDeleteBranch work as expected.

## Test environment(s) 

- GIT 2.19.1.windows.1
- Windows 10

### CODE REVIEW

**Comment by drewnoakes** [comment]
Can we change the "Select branches" text on that form to read "Enter branches, separated by spaces". This makes it explicit.

**Comment by amaiorano** [comment]
> Can we change the "Select branches" text on that form to read "Enter branches, separated by spaces". This makes it explicit.

I think this is a good idea, but one thing to note is that you can click on that button to the right to actually select branches, which is what I think this label text is alluding to (highlighted):

image

Also note that the FormDeleteRemoteBranch has the same label, and same layout:

image

Maybe we should just make the edit box in both forms readonly?

**Comment by gerhardol** [comment]
> Maybe we should just make the edit box in both forms readonly?

No, this is using completion when typing. For instance when invoked from commands, the box is empty

**Comment by amaiorano** [comment]
Then I suggest we leave it as is.

File: GitUI/CommandsDialogs/FormDeleteBranch.cs [hunk 1]
```diff
@@ -55,7 +55,7 @@ private void FormDeleteBranchLoad(object sender, EventArgs e)
 
             if (_defaultBranches != null)
             {
-                Branches.SetSelectedText(_defaultBranches.Join(", "));
+                Branches.SetSelectedText(_defaultBranches.Join(" "));
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/FormDeleteBranch.cs]: Should the names be quoted?

Comment (amaiorano) [reply GitUI/CommandsDialogs/FormDeleteBranch.cs]: I don't think so, since branch names can't have spaces in them, right?

Comment (gerhardol) [reply GitUI/CommandsDialogs/FormDeleteBranch.cs]: Leave it now
There are a number of characters that could be interpreted as a space character by the shell but not by Git. At least space and tab is correctly handled
https://git-scm.com/docs/git-check-ref-format

Comment (vbjay) [reply GitUI/CommandsDialogs/FormDeleteBranch.cs]: Correct.  Have fun with

```bash
git checkout branch name with spaces
```

Now if you want to be evil you could use a non breaking space  (Don't do this.)
