### PR TITLE
fix: Thread exhaustion by commit info data load

### LINKED ISSUE #6319: [Blocker] Thread exhaustion
## Current behaviour

Scrolling the revision graph (with attached debugger) is very slow and jerky. 
It looks like we are firing too many background threads and this leads to thread exhaustion
image
image

Obviously our threading flows are far from efficient or performant.
The main problem seems to be `StartAsyncDataLoad`:
https://github.com/gitextensions/gitextensions/blob/1d889787237a7c6f46bd7ca7d8b6c3a1a8cac127/GitUI/CommitInfo/CommitInfo.cs#L228-L259

## Expected behaviour

The scroll is fast and smooth. No excessive use of blocked thread.

## Steps to reproduce

* Open and run GE solution in VS
* Scroll the graph by pressing and holding the <kbd>&darr;</kbd> or rapidly scroll down for mouse-scroll

## Did this work in previous version of GitExtensions

Yes, v2 didn't exhibit as bad perf.

## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #6319

## Proposed changes

- Combine all async calls that load commit information into a single background call that reduces the number of used threads.

Overall the app feels snappier. I made a number of tests but couldn't replicate hung up or blocked threads anymore.

### Before

image

### After

image

## Test methodology 

- manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by sharwell** [comment]
The original bug is caused by our process executor not being async-all-the-way-down (we block while waiting for git calls to complete). This pull request mitigates (does not fix) the issue by sequencing one set of such calls instead of running them in parallel.

File: GitUI/CommitInfo/CommitInfo.cs [hunk 1]
```diff
@@ -277,6 +280,8 @@ async Task LoadLinksForRevisionAsync(GitRevision revision)
                     }
 
                     await this.SwitchToMainThreadAsync(cancellationToken);
+                    cancellationToken.ThrowIfCancellationRequested();
```
Comment (sharwell) [inline GitUI/CommitInfo/CommitInfo.cs]: 📝 This is handled already by the extension method on the previous line.

```suggestion
```

File: GitUI/CommitInfo/CommitInfo.cs [hunk 2]
```diff
@@ -318,10 +326,12 @@ async Task LoadSortedRefsAsync()
 
                 async Task LoadAnnotatedTagInfoAsync(IReadOnlyList<IGitRef> refs)
                 {
-                    await TaskScheduler.Default.SwitchTo(alwaysYield: true);
+                    await TaskScheduler.Default;
                     var annotatedTagsMessages = GetAnnotatedTagsMessages();
 
                     await this.SwitchToMainThreadAsync(cancellationToken);
+                    cancellationToken.ThrowIfCancellationRequested();
```
Comment (sharwell) [inline GitUI/CommitInfo/CommitInfo.cs]:
```suggestion
```

File: GitUI/CommitInfo/CommitInfo.cs [hunk 3]
```diff
@@ -380,17 +390,22 @@ async Task LoadAnnotatedTagInfoAsync(IReadOnlyList<IGitRef> refs)
...
                 async Task LoadTagInfoAsync(ObjectId objectId)
                 {
-                    await TaskScheduler.Default.SwitchTo(alwaysYield: true);
+                    cancellationToken.ThrowIfCancellationRequested();
+                    await TaskScheduler.Default;
+
                     var tags = Module.GetAllTagsWhichContainGivenCommit(objectId).ToList();
 
                     await this.SwitchToMainThreadAsync(cancellationToken);
+                    cancellationToken.ThrowIfCancellationRequested();
```
Comment (sharwell) [inline GitUI/CommitInfo/CommitInfo.cs]:
```suggestion
```

File: GitUI/CommitInfo/CommitInfo.cs [hunk 4]
```diff
@@ -402,16 +417,22 @@ async Task LoadBranchInfoAsync(ObjectId revision)
                     var branches = Module.GetAllBranchesWhichContainGivenCommit(revision, getLocal, getRemote).ToList();
 
                     await this.SwitchToMainThreadAsync(cancellationToken);
+                    cancellationToken.ThrowIfCancellationRequested();
```
Comment (sharwell) [inline GitUI/CommitInfo/CommitInfo.cs]:
```suggestion
```

File: GitUI/CommitInfo/CommitInfo.cs [hunk 5]
```diff
@@ -402,16 +417,22 @@ async Task LoadBranchInfoAsync(ObjectId revision)
...
 
                 async Task LoadDescribeInfoAsync(ObjectId commitId)
                 {
+                    cancellationToken.ThrowIfCancellationRequested();
                     await TaskScheduler.Default;
+
                     var info = GetDescribeInfoForRevision();
 
                     await this.SwitchToMainThreadAsync(cancellationToken);
+                    cancellationToken.ThrowIfCancellationRequested();
```
Comment (sharwell) [inline GitUI/CommitInfo/CommitInfo.cs]:
```suggestion
```

**Comment by RussKie** [comment]
> The original bug is caused by our process executor not being async-all-the-way-down (we block while waiting for git calls to complete). This pull request mitigates (does not fix) the issue by sequencing one set of such calls instead of running them in parallel.

Yes, I considered reworking the code to pass cancellation token in each individual method, but it felt like more work for relatively low value or no value at all.
Each git command is executed in sequence, so spawning multiple threads that get queued anyway probably causes more harm than good.

File: GitUI/CommitInfo/CommitInfo.cs (hunk 1 above)
Comment (RussKie) [reply GitUI/CommitInfo/CommitInfo.cs]: Thank you

File: GitUI/CommitInfo/CommitInfo.cs [hunk 6]
```diff
@@ -229,34 +229,36 @@ void StartAsyncDataLoad()
             {
                 var cancellationToken = _asyncLoadCancellation.Next();
 
-                ThreadHelper.JoinableTaskFactory.RunAsync(() => LoadLinksForRevisionAsync(_revision)).FileAndForget();
```
Comment (jbialobr) [inline GitUI/CommitInfo/CommitInfo.cs]: It seems that LoadLinksForRevisionAsync does not block, so it could remain async.

File: GitUI/CommitInfo/CommitInfo.cs [hunk 7]
```diff
@@ -229,34 +229,36 @@ void StartAsyncDataLoad()
...
-
-                if (_refsOrderDict == null)
+                ThreadHelper.JoinableTaskFactory.RunAsync(async () =>
                 {
-                    ThreadHelper.JoinableTaskFactory.RunAsync(() => LoadSortedRefsAsync()).FileAndForget();
-                }
+                    await LoadLinksForRevisionAsync(_revision);
 
-                // No branch/tag data for artificial commands
+                    if (_refsOrderDict == null)
```
Comment (jbialobr) [inline GitUI/CommitInfo/CommitInfo.cs]: `_refsOrderDict ` should be wrapped in AsyncLazy and not called here at all.

File: GitUI/CommitInfo/CommitInfo.cs [hunk 8]
```diff
@@ -267,6 +269,7 @@ async Task LoadLinksForRevisionAsync(GitRevision revision)
                         return;
                     }
 
+                    cancellationToken.ThrowIfCancellationRequested();
```
Comment (jbialobr) [inline GitUI/CommitInfo/CommitInfo.cs]: I think that all these `cancellationToken.ThrowIfCancellationRequested()`
should be directly in `StartAsyncDataLoad`. When we get to the state that all the execution is async-all-the-way-down then it will be clear that `cancellationToken.ThrowIfCancellationRequested()` are to be removed from `StartAsyncDataLoad`.
Putting `cancellationToken.ThrowIfCancellationRequested()` here brings the risk that they will stay here.

Comment (RussKie) [reply GitUI/CommitInfo/CommitInfo.cs]: I am afraid I don't quite understand what you're trying to say, sorry.

The way I understand it is as follows.
At the top of `StartAsyncDataLoad` we provision a new cancellation token. A previously issued token (if any) is cancelled, and aborts any pending operations. To achieve this we need `cancellationToken.ThrowIfCancellationRequested()` calls and pass the token to `this.SwitchToMainThreadAsync()` calls.

File: GitUI/CommitInfo/CommitInfo.cs (hunk 6 above)
Comment (RussKie) [reply GitUI/CommitInfo/CommitInfo.cs]: Yes and no. It isn't executing a git operation, you're right; but he parser may be reading definitions from the filesystem.
I'll update it.

File: GitUI/CommitInfo/CommitInfo.cs (hunk 7 above)
Comment (RussKie) [reply GitUI/CommitInfo/CommitInfo.cs]: Perhaps you're right, however it seems like a bigger change than I can afford allocate time for.
If it is left as-is for now we could query refs few extra times, anything else?

Comment (jbialobr) [reply GitUI/CommitInfo/CommitInfo.cs]: >anything else?

No, only that.

File: GitUI/CommitInfo/CommitInfo.cs (hunk 8 above)
Comment (jbialobr) [reply GitUI/CommitInfo/CommitInfo.cs]: What I am trying to say is that after your change `LoadAnnotatedTagInfoAsync` knows that it will be called in sequence.
Which I think it should not. Only the caller should know that, and it is its job to call `cancellationToken.ThrowIfCancellationRequested()`. If `LoadAnnotatedTagInfoAsync` was called in parallel then it would not be much sense to call `cancellationToken.ThrowIfCancellationRequested()` at the beginning, since we know that no cancellation could occur.
In addition there is a big chance that someone who makes it parallel again (when all the execution is async-all-the-way-down) will not remove this `cancellationToken.ThrowIfCancellationRequested()` at the beginning of `LoadAnnotatedTagInfoAsync`. The same applies to the other methods.

File: GitUI/CommitInfo/CommitInfo.cs (hunk 7 above)
Comment (jbialobr) [reply GitUI/CommitInfo/CommitInfo.cs]: I created a PR for this: https://github.com/gitextensions/gitextensions/pull/6335
It turned out that once loaded the sortedRefs were never refreshed on repository change.

**Comment by jbialobr** [comment]
>Yes, I considered reworking the code to pass cancellation token in each individual method, but it felt like more work for relatively low value or no value at all.

It will not help for cancelling the token will not stop the running git command. The only we can do is as @sharwell said make it async-all-the-way-down to not block background threads, but even then we will be spawning multiple git processes.

>Each git command is executed in sequence, so spawning multiple threads that get queued anyway probably causes more harm than good.

Why do you think so? Is it done by git or is GE sequencing them?

**Comment by RussKie** [comment]
> > Each git command is executed in sequence, so spawning multiple threads that get queued anyway probably causes more harm than good.
> 
> Why do you think so? Is it done by git or is GE sequencing them?

For some reason I was under impression we had them sequenced... 
I guess I was wrong. 😕

**Comment by RussKie** [comment]
> It will not help for cancelling the token will not stop the running git command.

It won't, no. But it would prevent new commands from being issued, wouldn't it?

File: GitUI/CommitInfo/CommitInfo.cs (hunk 8 above)
Comment (RussKie) [reply GitUI/CommitInfo/CommitInfo.cs]: I disagree, each method doesn't have a notion of the order it is called; the composition is still the function of `StartAsyncDataLoad`.

I am working on an update to the commit info control (though it is a glacial progress given my load) and planning to refactor/rework how data is populated and displayed to the user.

**Comment by RussKie** [comment]
@jbialobr I understand you'd like to see a better change how I currently don't have capacity to rewrite the code in a "proper all-the-way-down-async". 
We need to address the immediate problem however and avoid exhausting available threads. This issue must be resolved for the 3.1.0 release, which we should ship pretty soon.

Would you like to take over and provide a better fix?

File: GitUI/CommitInfo/CommitInfo.cs (hunk 8 above)
Comment (jbialobr) [reply GitUI/CommitInfo/CommitInfo.cs]: I am afraid you still do not know what I am trying to say.

**Comment by jbialobr** [comment]
>@jbialobr I understand you'd like to see a better change how I currently don't have capacity to rewrite the code in a "proper all-the-way-down-async".
We need to address the immediate problem however and avoid exhausting available threads. This issue must be resolved for the 3.1.0 release, which we should ship pretty soon.
Would you like to take over and provide a better fix?

You took me wrong. I just wanted you to be aware where the problem is. I read your answer to @sharwell 's comment and had impression that you are talking about sth totally different than @sharwell said. Thus I wanted to clarify it. I never wanted (and even thought) you to make it all-the-way-down-async.

File: GitUI/CommitInfo/CommitInfo.cs (hunk 8 above)
Comment (jbialobr) [reply GitUI/CommitInfo/CommitInfo.cs]: I am not talking here about the order. I am talking about parallel vs sequential invocation. Putting cancellationToken.ThrowIfCancellationRequested() at the beginning of LoadAnnotatedTagInfoAsync makes only sense when `LoadAnnotatedTagInfoAsync ` knows it be invoked in a sequential way.

**Comment by vbjay** [comment]
A custom task scheduler would allow full async and prevent thread exhaustion.

File: GitUI/CommitInfo/CommitInfo.cs (hunk 8 above)
Comment (jbialobr) [reply GitUI/CommitInfo/CommitInfo.cs]: Saying this in other words:
Lets assume I did the all-the-way-down-async and now I am changing StartAsyncDataLoad that it calls all the Load* functions in parallel. Does it make sense to leave `cancellationToken.ThrowIfCancellationRequested();` at the beginning of Load* functions? Or should them be removed?

Comment (RussKie) [reply GitUI/CommitInfo/CommitInfo.cs]: Updated

File: GitUI/CommitInfo/CommitInfo.cs [hunk 9]
```diff
@@ -274,29 +274,36 @@ void StartAsyncDataLoad()
...
+                    if (AppSettings.CommitInfoShowContainedInBranches)
+                    {
+                        await LoadBranchInfoAsync(_revision.ObjectId);
+                    }
 
-                if (AppSettings.CommitInfoShowContainedInTags)
-                {
-                    ThreadHelper.JoinableTaskFactory.RunAsync(() => LoadTagInfoAsync(_revision.ObjectId)).FileAndForget();
-                }
+                    if (AppSettings.ShowAnnotatedTagsMessages)
```
Comment (jbialobr) [inline GitUI/CommitInfo/CommitInfo.cs]: cancellationToken.ThrowIfCancellationRequested();

File: GitUI/CommitInfo/CommitInfo.cs [hunk 10]
```diff
@@ -274,29 +274,36 @@ void StartAsyncDataLoad()
...
+                    {
+                        await LoadAnnotatedTagInfoAsync(_revision.Refs);
+                    }
 
-                if (AppSettings.CommitInfoShowTagThisCommitDerivesFrom)
-                {
-                    ThreadHelper.JoinableTaskFactory.RunAsync(() => LoadDescribeInfoAsync(_revision.ObjectId)).FileAndForget();
-                }
+                    if (AppSettings.CommitInfoShowContainedInTags)
```
Comment (jbialobr) [inline GitUI/CommitInfo/CommitInfo.cs]: cancellationToken.ThrowIfCancellationRequested();

File: GitUI/CommitInfo/CommitInfo.cs [hunk 11]
```diff
@@ -274,29 +274,36 @@ void StartAsyncDataLoad()
...
+                    {
+                        await LoadTagInfoAsync(_revision.ObjectId);
+                    }
+
+                    if (AppSettings.CommitInfoShowTagThisCommitDerivesFrom)
```
Comment (jbialobr) [inline GitUI/CommitInfo/CommitInfo.cs]: cancellationToken.ThrowIfCancellationRequested();

File: GitUI/CommitInfo/CommitInfo.cs (hunk 9 above)
Comment (RussKie) [reply GitUI/CommitInfo/CommitInfo.cs]: But then `cancellationToken.ThrowIfCancellationRequested();` should be as the first line in `LoadAnnotatedTagInfoAsync`.

Comment (jbialobr) [reply GitUI/CommitInfo/CommitInfo.cs]: We have awaited `LoadBranchInfoAsync` and now we want to make sure no cancellation was requested. `LoadBranchInfoAsync` does not know there was an async call before, hence we should do the check here.

Comment (RussKie) [reply GitUI/CommitInfo/CommitInfo.cs]: updated

**Comment by RussKie** [comment]
Thank you
