### PR TITLE
Fix RepoObjectsTree (left panel) remaining blank when ReloadAsync is …

### LINKED ISSUE #5778: ROT remains blank when spamming refresh toolbar button
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you spam the Refresh toolbar button, after a while, the ROT (left panel) will remain blank.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Open a repo
* Start spamming the refresh button; maybe after 10 times or so, the ROT will remain blank.

**What is the expected behavior?**
The ROT refreshes and shows its nodes.

**Environment you encounter the issue:**
- GitExtensions version: 3.0 RC2

**Did this work in previous version of GitExtensions (which)?**
Not happening on 3.0 beta 1

### PR DESCRIPTION
**Pull request by amaiorano**
…cancelled (e.g. by spamming refresh)

Problem is that if during ReloadAsync, a System.OperationCanceledException is thrown due to cancellation, we cannot use token anymore in the finally block to switch to main thread. Doing so causes another exception to be thrown, and we never end up executing the code below, which includes "treeMain.EndUpdate()" required to restore rendering of the tree view.

Fixes #5778

### CODE REVIEW

**Comment by amaiorano** [comment]
This is to fix #5778. I think this is the right fix - not to use 'token' after CancellationException is thrown.

File: GitUI/BranchTreePanel/RepoObjectsTree.cs [hunk 1]
```diff
@@ -167,7 +167,7 @@ public async Task ReloadAsync()
             }
             finally
             {
-                await this.SwitchToMainThreadAsync(token);
+                await this.SwitchToMainThreadAsync();
```
Comment (RussKie) [inline GitUI/BranchTreePanel/RepoObjectsTree.cs]: Please move `var token = CancelBackgroundTasks();` from 158 to 163.

**Comment by amaiorano** [comment]
Amended the commit with your suggeston @RussKie

File: GitUI/BranchTreePanel/RepoObjectsTree.cs [hunk 2]
```diff
@@ -155,19 +155,19 @@ public async Task ReloadAsync()
...
                 var tasks = _rootNodes.Select(r => r.ReloadAsync(token)).ToArray();
                 await Task.WhenAll(tasks).ConfigureAwait(false);
             }
             finally
             {
-                await this.SwitchToMainThreadAsync(token);
+                await this.SwitchToMainThreadAsync();
                 Enabled = true;
 
                 var selectedNode = treeMain.AllNodes().FirstOrDefault(n =>
```
Comment (jbialobr) [inline GitUI/BranchTreePanel/RepoObjectsTree.cs]: The token protection has to only be excluded for `EndUpdate` the rest has to remain unchanged.

```csharp

        public async Task ReloadAsync()
        {
            var currentBranch = Module.GetSelectedBranch();
            await this.SwitchToMainThreadAsync();

            var token = CancelBackgroundTasks();
            Enabled = false;

            try
            {
                treeMain.BeginUpdate();
                var tasks = _rootNodes.Select(r => r.ReloadAsync(token)).ToArray();
                await Task.WhenAll(tasks).ConfigureAwait(false);
            }
            finally
            {
                await this.SwitchToMainThreadAsync();
                if (!token.IsCancellationRequested)
                {
                    Enabled = true;
                    var selectedNode = treeMain.AllNodes().FirstOrDefault(n =>
                        _rootNodes.Any(rn => $"{rn.TreeViewNode.FullPath}{treeMain.PathSeparator}{currentBranch}" == n.FullPath));
                    if (selectedNode != null)
                    {
                        _rootNodes.ForEach(t => t.IgnoreSelectionChangedEvent = true);
                        treeMain.SelectedNode = selectedNode;
                        _rootNodes.ForEach(t => t.IgnoreSelectionChangedEvent = false);
                        treeMain.SelectedNode.EnsureVisible();
                    }
                }

                treeMain.EndUpdate();
            }
        }
```

Comment (amaiorano) [reply GitUI/BranchTreePanel/RepoObjectsTree.cs]: Yes, that makes sense @jbialobr. At first I wondered if we should include Enabled = true next to treeMain.EndUpdate, but I suppose it's fine since cancelling means another update is in flight. So during the time between cancelling and the next update, we'll see the tree's contents disabled. I'll upload an amendment with this version.

**Comment by RussKie** [comment]
Thank you all
