### PR TITLE
Use git argument builder

### LINKED ISSUE #5479: Use GitArgumentBuilder to generate git commands in all git calls
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
We have calls to git not using the GitArgumentBuilder which means it can't provide the fixes that class was designed to do.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Some cmd calls will fail if the right configurations are not set.  
**What is the expected behavior?**
All RunGitCmd calls and other ways of running git commands use GitArgumentBuilder
**Environment you encounter the issue:**

- GitExtensions version:Master
- GIT version: NA
- OS version: NA
- .NET version: NA

**Did this work in previous version of GitExtensions (which)?**
No

### PR DESCRIPTION
**Pull request by vbjay**
Fixes #5479 

Changes proposed in this pull request:
- [x] Use GitArgumentBuilder for ALL RunGitCmd... calls
- [x] Use GitArgumentBuilder for ALL _gitExecutable.Execute calls
- [x] Replace Git arguments created by using ArgumentBuilder with GitArgumentBuilder
- [x] Use GitArgumnentBuilder for all other ways of running git comands not found yet.

Screenshots before and after (if PR changes UI):

What did I do to test the code and ensure quality:
Not there yet
Has been tested on (remove any that don't apply):
- GIT 2.19 and above

### CODE REVIEW

**Comment by vbjay** [comment]
@drewnoakes can you look at the poccess.  I am not done by any means but would like feedback before I go further.

File: GitCommands/Git/GitCommandHelpers.cs [hunk 1]
```diff
@@ -164,17 +168,29 @@ public static ArgumentString RevertCmd(ObjectId commitId, bool autoCommit, int p
 
         public static ArgumentString ResetSoftCmd(string commit)
         {
-            return "reset --soft \"" + commit + "\"";
+            return new GitArgumentBuilder("reset")
+            {
+                "--soft",
+                commit?.QuoteNE()
```
Comment (RussKie) [inline GitCommands/Git/GitCommandHelpers.cs]: null check is unnecessary, `QuoteNE` handles `null`s
the same applies to other instances

File: GitCommands/Git/GitCommandHelpers.cs [hunk 2]
```diff
@@ -417,10 +441,12 @@ public static ArgumentString CleanUpCmd(bool dryRun, bool directories, bool nonI
 
         public static ArgumentString GetAllChangedFilesCmd(bool excludeIgnoredFiles, UntrackedFilesMode untrackedFiles, IgnoreSubmodulesMode ignoreSubmodules = IgnoreSubmodulesMode.None, bool noLocks = false)
         {
-            return new ArgumentBuilder
+            return new GitArgumentBuilder(
+                noLocks && GitVersion.Current.SupportNoOptionalLocks
+                    ? new ArgumentBuilder() { "--no-optional-locks", "status" }.ToString()
```
Comment (RussKie) [inline GitCommands/Git/GitCommandHelpers.cs]: Is `ArgumentBuilder` really necessary here? 
We'd be doing a number of allocations which can be mitigated with a simple `"--no-optional-locks status"`

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 3]
```diff
@@ -1184,7 +1199,12 @@ private void StageFile(string filename)
             void ProcessStart(FormStatus form)
             {
                 form.AddMessageLine(string.Format(_stageFilename.Text, filename));
-                string output = Module.RunGitCmd("add -- \"" + filename + "\"");
+                GitArgumentBuilder args = new GitArgumentBuilder("add")
+                    {
+                        "--",
+                        filename?.QuoteNE()
+                    };
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormResolveConflicts.cs]: mis-indented

File: GitUI/CommandsDialogs/FormVerify.LostObject.cs [hunk 4]
```diff
@@ -22,15 +22,40 @@ private enum LostObjectType
 
         private sealed class LostObject
         {
+            private static GitArgumentBuilder _LogBuilder;
+            private static GitArgumentBuilder _TagBuilder;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormVerify.LostObject.cs]: These should be `_logBuilder` and `_tagBuilder`

File: Plugins/BackgroundFetch/BackgroundFetchPlugin.cs [hunk 5]
```diff
@@ -81,16 +82,27 @@ private void RecreateObservable()
...
                                       {
-                                          _currentGitUiCommands.GitModule.RunGitCmd("submodule foreach --recursive git fetch --all");
+                                          args = new GitArgumentBuilder("submodule")
+                                        {
+                                            "foreach",
+                                            "--recursive",
+                                            "git",
+                                            "fetch",
+                                            "--all"
+                                        };
```
Comment (RussKie) [inline Plugins/BackgroundFetch/BackgroundFetchPlugin.cs]: mis-indented

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs [hunk 6]
```diff
@@ -112,7 +118,16 @@ private static IEnumerable<string> GetObsoleteBranchNames(RefreshContext context
             var regex = string.IsNullOrEmpty(context.RegexFilter) ? null : new Regex(context.RegexFilter, options);
             bool regexMustMatch = !context.RegexDoesNotMatch;
 
-            string[] branches = context.Commands.RunGitCmd("branch" + (context.IncludeRemotes ? " -r" : "") + (context.IncludeUnmerged ? "" : " --merged " + context.ReferenceBranch))
+            // { context.IncludeRemotes, "-r" },
+            // { !context.IncludeUnmerged, "--merged" },
```
Comment (RussKie) [inline Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: is this needed?

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs [hunk 7]
```diff
@@ -162,19 +177,29 @@ private void Delete_Click(object sender, EventArgs e)
...
                     // TODO: use GitCommandHelpers.PushMultipleCmd after moving this window to GE (see FormPush as example)
                     var remoteBranchNameOffset = remoteBranchPrefix.Length;
-                    var remoteBranchNames = string.Join(" ", remoteBranches.Select(branch => ":" + branch.Name.Substring(remoteBranchNameOffset)));
-                    _gitCommands.RunGitCmd($"push {remoteName} {remoteBranchNames}");
+
+                    args = new GitArgumentBuilder("push")
+                    {
+                        remoteName,
+                        remoteBranches.Select(branch => $":{branch.Name.Substring(remoteBranchNameOffset)}")
+                };
```
Comment (RussKie) [inline Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: mis-indented

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs (hunk 6 above)
Comment (vbjay) [reply Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: No. I was having issues and finally fixed it. Did not remove comment.

File: GitCommands/Git/GitCommandHelpers.cs (hunk 1 above)
Comment (vbjay) [reply GitCommands/Git/GitCommandHelpers.cs]: Ok.  I saw it in other places.

File: GitUI/CommandsDialogs/FormResolveConflicts.cs (hunk 3 above)
Comment (vbjay) [reply GitUI/CommandsDialogs/FormResolveConflicts.cs]: Don't worry about code formatting yet.  Not ready to go through that part of the code.  Although, VS wasn't complaining.

File: GitUI/CommandsDialogs/FormVerify.LostObject.cs (hunk 4 above)
Comment (vbjay) [reply GitUI/CommandsDialogs/FormVerify.LostObject.cs]: Sure.

File: GitCommands/Git/GitCommandHelpers.cs (hunk 2 above)
Comment (vbjay) [reply GitCommands/Git/GitCommandHelpers.cs]: No.  I guess not.

File: GitUI/CommandsDialogs/FormResolveConflicts.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormResolveConflicts.cs]: I have a stylecop installed in my head, it sets off when I see things 😆

Comment (vbjay) [reply GitUI/CommandsDialogs/FormResolveConflicts.cs]: LMAO!

**Comment by RussKie** [comment]
Curious, do we have any consumers of `ArgumentBuilder` left after this change?

**Comment by vbjay** [comment]
Not sure. I can run a bit grep later on.

**Comment by vbjay** [comment]
Yes.  The ones that should be GitArgumentBuilder, I'll change.

**Comment by drewnoakes** [comment]
Looks good @vbjay. I agree with @RussKie's comments. I'd use `var` for declarations initialised with `new`, but it's not a big deal.

> do we have any consumers of ArgumentBuilder 

IIRC we use it for calling other executables such as plink, puttygen and probably others. I don't think we will get rid of it. They work well together IMO.

**Comment by vbjay** [comment]
So I found an issue I am going to fix with this pull request.   The issue is that command should be validated like it is now but we can't add git option flags like --no-optional-locks and what have you.  

I am going to add to the GitArgumentBuilder constructor an optional parameter of ArgumentBuilder that will only have the options like mentioned.  

Rough Example.

```c#
GitArgumentBuilder args = new GitArgumentBuilder("status", GitOptions: new ArgumentBuilder(){"--no-optional-locks"})
```
This will allow us to add other options later on if needed.

**Comment by RussKie** [comment]
The only thing I'd be conscious is extra allocations

**Comment by vbjay** [comment]
It's only done when we have
git --blaaa cmd
Vs
git cmd

**Comment by RussKie** [comment]
But if the command `git --blaaa cmd` is run on a regular basis (which I presume `git status` is), then it puts unnecessary memory pressure

**Comment by vbjay** [comment]
Sure. I'll try to optimize it to not allocate each time. Maybe a static
where it just creates one instance or a shared method that does the
processing and returns the string. I'll think on it. I still want some kind
of handling instead of the user worrying about spaces and quotes.

**Comment by gerhardol** [comment]
Git-status runs at most every third second so no mayor issue

**Comment by drewnoakes** [comment]
If you use `ArgumentString` for the `options` and only have a single argument then you can avoid any extra allocation.

Eg:

```c#
var args = new GitArgumentBuilder("status", options: "--no-optional-locks");
```

I was curious about other `git` options. They're documented here: https://git-scm.com/docs/git

**Comment by vbjay** [comment]
It's possible for multiple options. You know, ArgumentString makes sense.
Would love to still have that collection initialization syntax but I'm not
stuck on it. Thanks.

**Comment by drewnoakes** [comment]
> It's possible for multiple options.

If you need multiple (and they can't be specified in a single string literal) then you would pass an `ArgumentBuilder` or whatever to the `ArgumentString`.

**Comment by vbjay** [comment]
ArgumentString is in GitUIPluginInterfaces  Should I move it to GitextUtils and refactor the uses?

**Comment by vbjay** [comment]
Looks like NSubstitute Returns won't work with my change.  Thoughts?

**Comment by RussKie** [comment]
Can you please elaborate?

**Comment by vbjay** [comment]
image
The failing tests are failing because the Returns call is setting the result in the actual side.  

Same arguments but not to NSubstitute.  

image

**Comment by RussKie** [comment]
It appears you are not arranging the mock correctly, and that causes the mock not being executed:
` _module().RunGitCmd(args).Returns(returnString);` will never execute as the code under test passes a different instance of `ArgumentString` class than the test.
Here's a tweak to get it working:

```diff
diff --git a/UnitTests/GitCommandsTests/Git/Gpg/GitGpgControllerTests.cs b/UnitTests/GitCommandsTests/Git/Gpg/GitGpgControllerTests.cs
index 31187cb81..087515e85 100644
--- a/UnitTests/GitCommandsTests/Git/Gpg/GitGpgControllerTests.cs
+++ b/UnitTests/GitCommandsTests/Git/Gpg/GitGpgControllerTests.cs
@@ -108,13 +108,15 @@ public void Validate_GetCommitVerificationMessage(string returnString)
         {
             var objectId = ObjectId.Random();
             var revision = new GitRevision(objectId);
-            GitArgumentBuilder args = new GitArgumentBuilder("log")
+            var args = new GitArgumentBuilder("log")
             {
                 "--pretty=\"format:%GG\"",
                 "-1",
-                objectId
+                objectId.ToString()
             };
-            _module().RunGitCmd(args).Returns(returnString);
+
+            _module().RunGitCmd(Arg.Is<ArgumentString>(arg => arg.Arguments.Equals(args.ToString())))
+                .Returns(x => returnString);
 
             var actual = _gpgController.GetCommitVerificationMessage(revision);
```

There's also a bug in `GitGpgController`:
```diff
diff --git a/GitCommands/Git/GitGpgController.cs b/GitCommands/Git/GitGpgController.cs
index 08c378179..80d2a8b60 100644
--- a/GitCommands/Git/GitGpgController.cs
+++ b/GitCommands/Git/GitGpgController.cs
@@ -205,7 +205,7 @@ public string GetCommitVerificationMessage(GitRevision revision)
             var module = GetModule();
             GitArgumentBuilder args = new GitArgumentBuilder("log")
             {
-                "--pretty =\"format:%GG\"",
+                "--pretty=\"format:%GG\"",
                 "-1",
                 revision.Guid
             };
```

And the operator implementation in `ArgumentString` is not watertight, I got a number of NRE while trying to fix the test:
```
public static implicit operator ArgumentString(ArgumentBuilder args) => new ArgumentString(args.ToString());
```

**Comment by vbjay** [comment]
I'm working on the operators. Thanks for the tweak. That is what I was
looking for. Appreciate the help.

**Comment by vbjay** [comment]
OK.  Tests are green again.  I'll check the operators and move to the other steps in this pull request.

**Comment by RussKie** [comment]
Awesome!

File: GitExtUtils/GitArgumentBuilder.cs [hunk 8]
```diff
@@ -177,8 +178,14 @@ public override string ToString()
 
             // 7 = "-c " + "=" + " " + 2 (for possible quotes of value)
             var capacity = _configItems.Sum(i => i.Key.Length + i.Value.Length + 7) + _command.Length + 1 + arguments.Length;
+            capacity += (_gitArgs?.Length ?? -1) + 1;
 
             var str = new StringBuilder(capacity);
+            if ((_gitArgs?.Length ?? 0) > 0)
```
Comment (RussKie) [inline GitExtUtils/GitArgumentBuilder.cs]: `_gitArgs?.Length ?? ` construct is used twice, worth reconciling it once then reuse the result

```
var gitArgsLength = _gitArgs?.Length ?? -1;
capacity += gitArgsLength + 1;

if (gitArgsLength > 0)
{
    ...
```

File: GitUI/CommandsDialogs/FormResolveConflicts.cs (hunk 3 above)
Comment (vbjay) [reply GitUI/CommandsDialogs/FormResolveConflicts.cs]: image

image

File: Plugins/BackgroundFetch/BackgroundFetchPlugin.cs (hunk 5 above)
Comment (vbjay) [reply Plugins/BackgroundFetch/BackgroundFetchPlugin.cs]: image

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs (hunk 7 above)
Comment (vbjay) [reply Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: image

**Comment by vbjay** [comment]
Visual Studio says nothing about the indention.  I don't see a problem.

File: GitExtUtils/GitArgumentBuilder.cs [hunk 9]
```diff
@@ -174,12 +175,20 @@ public void Add(GitConfigItem configItem)
         public override string ToString()
         {
             var arguments = base.ToString();
+            var gitArgsLength = _gitArgs?.Length;
```
Comment (RussKie) [inline GitExtUtils/GitArgumentBuilder.cs]: why not `_gitArgs?.Length ?? -1`, this saves from doing the null check twice below

File: GitUI/CommandsDialogs/FormResolveConflicts.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormResolveConflicts.cs]: This just looks untidy and inconsistent

File: Plugins/BackgroundFetch/BackgroundFetchPlugin.cs (hunk 5 above)
Comment (RussKie) [reply Plugins/BackgroundFetch/BackgroundFetchPlugin.cs]: The screenshot shows a different piece of code.
The code above looks untidy and inconsistent

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs (hunk 7 above)
Comment (RussKie) [reply Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: This looks untidy and inconsistent. 
Why are you expecting someone to fix it for you in subsequent PRs?

Comment (vbjay) [reply Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: I'm not.  It is a WIP pull request.  I didn't see the indent issue. I don't mind the reviews and think they are helpful.  I am not focused on code formatting at this point and time.  Right now I am focused on functionality.

**Comment by vbjay** [comment]
> And the operator implementation in ArgumentString is not watertight, I got a number of NRE while trying to fix the test:
That's because Arguments can be null.  I changed the tests to use ToString which forces it to be a "" if null.  I am also altering the string operator to use ToString.  That way it will always be an empty string instead of null in teh conversion.  As I go through the code I plan on finding Arguments and replace with ToString.  Possibly changing the scope of Arguments too.  
```c#
        public static implicit operator ArgumentString(string args) => new ArgumentString(args);
        public static implicit operator ArgumentString(ArgumentBuilder args) => new ArgumentString(args.ToString());

        public static implicit operator string(ArgumentString args) => args.ToString();
        public override string ToString() => Arguments ?? "";
```

Makes it so that the operators never return a null object,

File: GitExtUtils/ArgumentString.cs [hunk 10]
```diff
@@ -1,24 +1,23 @@
...
 using JetBrains.Annotations;
 
-namespace GitUIPluginInterfaces
+namespace GitCommands
 {
     [DebuggerDisplay("{" + nameof(Arguments) + "}")]
     public readonly struct ArgumentString
     {
         [CanBeNull] public string Arguments { get; }
+        public int? Length { get => Arguments?.Length; }
```
Comment (RussKie) [inline GitExtUtils/ArgumentString.cs]: Suggest `public int Length => Arguments?.Length ?? 0;`, as from API stand point, a nullable length is quite unexpected.
`get => ` is unnecessary, it gets added under the cover.

**Comment by vbjay** [comment]
Sure.

File: GitExtUtils/ArgumentString.cs [hunk 11]
```diff
@@ -1,24 +1,23 @@
...
 
-        private ArgumentString([NotNull] string arguments)
+        private ArgumentString([CanBeNull] string arguments)
```
Comment (drewnoakes) [inline GitExtUtils/ArgumentString.cs]: Why do you allow null here?

File: GitExtUtils/GitArgumentBuilder.cs [hunk 12]
```diff
@@ -115,16 +114,18 @@ public sealed class GitArgumentBuilder : ArgumentBuilder
...
         /// <summary>
         /// Initialises a new <see cref="GitArgumentBuilder"/> for the given <paramref name="command"/>.
         /// </summary>
         /// <param name="command">The git command this builder is compiling arguments for.</param>
         /// <param name="commandConfiguration">Optional source for default command configuration items. Pass <c>null</c> to use the Git Extensions defaults.</param>
+        /// <param name="gitOptions">Optional arguments that are for the git command.  EX: git --no-optional-locks status </param>
         /// <exception cref="ArgumentNullException"><paramref name="command"/> is <c>null</c>.</exception>
         /// <exception cref="ArgumentException"><paramref name="command"/> is an invalid string.</exception>
-        public GitArgumentBuilder([NotNull] string command, [CanBeNull] GitCommandConfiguration commandConfiguration = null)
+        public GitArgumentBuilder([NotNull] string command, [CanBeNull] GitCommandConfiguration commandConfiguration = null, [CanBeNull] ArgumentString? gitOptions = null)
```
Comment (drewnoakes) [inline GitExtUtils/GitArgumentBuilder.cs]: I think you can avoid making this nullable, and make the default value `default`.

**Comment by vbjay** [comment]
Thanks Good catch. I was getting tired so I just wip it and decided to get
back to it another time.

File: GitExtUtils/GitArgumentBuilder.cs (hunk 12 above)
Comment (vbjay) [reply GitExtUtils/GitArgumentBuilder.cs]: Nope. To allow git options to be optional, I had to allow it.

File: GitExtUtils/ArgumentString.cs (hunk 11 above)
Comment (vbjay) [reply GitExtUtils/ArgumentString.cs]: Because the tostring will turn it to a "". I'm thinking of changing the scope of Arguments too. Really should only have one way to get the string back.

File: GitCommands/Git/GitModule.cs [hunk 13]
```diff
@@ -1090,8 +1166,14 @@ string ProcessDiffNotes(int startIndex)
 
         public IReadOnlyList<ObjectId> GetParents(ObjectId commitId)
         {
+            var args = new GitArgumentBuilder("log")
+            {
+                "-n 1",
+                "--format=format:%P",
+                commitId.ToString().QuoteNE()
```
[the remark this answers is not in the document]
Comment (vbjay) [reply GitCommands/Git/GitModule.cs]: Ok.

[the remark this answers is not in the document]
Comment (vbjay) [reply GitCommands/Git/GitModule.cs]: Ok.

File: GitCommands/Git/GitModule.cs [hunk 14]
```diff
@@ -807,34 +855,54 @@ public IReadOnlyList<string> GetSortedRefs()
...
+                {
+                    "--sort=-committerdate",
+                    "--format=\"%(objectname) %(refname)\"",
+                    { AppSettings.ShowSuperprojectBranches, "refs/heads/" },
+                    { AppSettings.ShowSuperprojectTags, " refs/tags/" }
+                };
             }
 
-            return null;
+            return "";
```
[the remark this answers is not in the document]
Comment (vbjay) [reply GitCommands/Git/GitModule.cs]: Sure. Yes. It is a needed change.

File: GitUI/CommandsDialogs/FormVerify.LostObject.cs [hunk 15]
```diff
@@ -22,15 +22,40 @@ private enum LostObjectType
...
+                    {
+                        "-n1",
+                        "--pretty=format:\"%aN, %e, %s, %ct, %P\" {0}"
+                    };
+                    return _logBuilder;
+                }
+            }
 
-            private const string TagCommandArgumentsFormat = "cat-file -p {0}";
+            private static GitArgumentBuilder TagCommandArgumentsFormat
```
Comment (drewnoakes) [inline GitUI/CommandsDialogs/FormVerify.LostObject.cs]: Maybe something like:

```c#
private static readonly string TagCommandArgumentsFormat = new GitArgumentBuilder("cat-file") { "-p", "{0}" }.ToString();
```

There's no reason to hold the mutable builder that I can see. You can remove the field too. Same applies to `LogCommandArgumentsFormat`.

File: Plugins/BackgroundFetch/BackgroundFetchPlugin.cs [hunk 16]
```diff
@@ -1,12 +1,13 @@
...
 using System.Collections.Generic;
 using System.ComponentModel.Composition;
+using System.Linq;
 using System.Reactive.Concurrency;
 using System.Reactive.Linq;
 using BackgroundFetch.Properties;
+using GitCommands;
 using GitUIPluginInterfaces;
 using ResourceManager;
-
```
Comment (drewnoakes) [inline Plugins/BackgroundFetch/BackgroundFetchPlugin.cs]: Formatting.

File: GitCommands/Git/GitModule.cs [hunk 17]
```diff
@@ -807,34 +855,54 @@ public IReadOnlyList<string> GetSortedRefs()
         }
 
         [CanBeNull]
```
Comment (drewnoakes) [inline GitCommands/Git/GitModule.cs]: This attribute is incorrect after this change.

File: GitExtUtils/ArgumentString.cs (hunk 11 above)
Comment (drewnoakes) [reply GitExtUtils/ArgumentString.cs]: It is not valid to pass null here. I would not change the attribute or validation. Note that because this is a struct you _can_ end up with a null field internally, but that's only possible if using `default(ArgumentString)` or similar which doesn't use the ctor. We should not be changing this code path as it could hide errors.

File: GitExtUtils/GitArgumentBuilder.cs (hunk 12 above)
Comment (drewnoakes) [reply GitExtUtils/GitArgumentBuilder.cs]: I meant that you can use `ArgumentString gitOptions = default`. It doesn't have to be `ArgumentString?`.

File: GitCommands/Git/GitModule.cs [hunk 18]
```diff
@@ -828,7 +828,8 @@ public IReadOnlyList<string> GetSortedRefs()
             {
                 "--sort=-committerdate",
                 "--sort=-taggerdate",
-                "--format=\"%(refname)\" refs/"
+                "--format=\"%(refname)\"",
+                refs/"
             };
```
Comment (vbjay) [inline GitCommands/Git/GitModule.cs]: Did this on purpose so I could find it and review in VS.

File: GitExtUtils/ArgumentString.cs (hunk 11 above)
Comment (vbjay) [reply GitExtUtils/ArgumentString.cs]: I did this to fix an issue with VS fussing about the conversion in the optional parameter.  It looks like VS was yelling for nothing.  I'll revert this.

File: Plugins/BackgroundFetch/BackgroundFetchPlugin.cs (hunk 16 above)
Comment (vbjay) [reply Plugins/BackgroundFetch/BackgroundFetchPlugin.cs]: fixed in next push

File: GitUI/CommandsDialogs/FormVerify.LostObject.cs (hunk 15 above)
Comment (vbjay) [reply GitUI/CommandsDialogs/FormVerify.LostObject.cs]: Fixed in next push

File: GitCommands/Git/GitModule.cs (hunk 13 above)
[the remark this answers is not in the document]
Comment (vbjay) [reply GitCommands/Git/GitModule.cs]:
```c#
    .GetOutput($"log -n 1 --format=format:%P \"{commitId}\"")
```

Preserved the functionality.  \"value\"= value.QuoteNE with an added check for null or empty.

File: GitCommands/Git/GitModule.cs [hunk 19]
```diff
@@ -781,9 +824,14 @@ public List<ConflictData> GetConflicts(string filename = "")
 
         public IReadOnlyList<string> GetSortedRefs()
         {
-            const string command = "for-each-ref --sort=-committerdate --sort=-taggerdate --format=\"%(refname)\" refs/";
+            var args = new GitArgumentBuilder("for-each-ref")
+            {
+                "--sort=-committerdate",
+                "--sort=-taggerdate",
+                "--format=\"%(refname)\" refs/"
```
[the remark this answers is not in the document]
Comment (vbjay) [reply GitCommands/Git/GitModule.cs]: fixed

File: GitExtUtils/GitArgumentBuilder.cs (hunk 12 above)
Comment (vbjay) [reply GitExtUtils/GitArgumentBuilder.cs]: fixed

File: GitCommands/Git/GitModule.cs (hunk 13 above)
[the remark this answers is not in the document]
Comment (drewnoakes) [reply GitCommands/Git/GitModule.cs]: I see. The quotes aren't needed though, so you can avoid a few allocations here.

**Comment by RussKie** [comment]
Checking on the progress. I'm planning to do another cut soon.

**Comment by vbjay** [comment]
Sorry. Work had me running ragged. I'm planning on getting it done this
weekend. I've done some work.

**Comment by vbjay** [comment]
Replacing all ArgumentBuilder with GitArgumentBuilder. Ready for review so far.  I'll push the replacement commit soon.

File: Plugins/BackgroundFetch/BackgroundFetchPlugin.cs (hunk 5 above)
Comment (vbjay) [reply Plugins/BackgroundFetch/BackgroundFetchPlugin.cs]: Each red mark is one indention  
image

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 20]
```diff
@@ -2260,8 +2258,14 @@ private void generateListOfChangesInSubmodulesChangesToolStripMenuItem_Click(obj
...
             foreach (var (path, name) in modules)
             {
-                string diff = Module.RunGitCmd(
-                     string.Format("diff --cached -z -- {0}", name));
+                var args = new GitArgumentBuilder("diff")
+                {
+                    "--cached",
+                    "-z",
+                    "--",
+                    name
```
[the remark this answers is not in the document]
Comment (vbjay) [reply GitUI/CommandsDialogs/FormCommit.cs]: Yes. Thanks. I'll fix it.

**Comment by vbjay** [comment]
Rebased.

**Comment by RussKie** [comment]
Thank you
