### PR TITLE
fix(File tree): Avoid split folders

### LINKED ISSUE #12585: Split folder in File tree view
### Environment

- Git Extensions 6.0.2.18262
- Build f02a06bf5366bcee241c3273951de3a132020b48
- Git 2.51.0.windows.1
- Microsoft Windows NT 10.0.26100.0
- .NET 9.0.9
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 8.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 9.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

### Issue description

Since upgrade from GitExtensions 5 to 6, I see several entries in File tree having the same name but not the same content.

In GitExtensions 5 I had : 
Lib\
|_FolderA\
|_FolderB\
|_catch.hpp
|_Fixtures.h

In GitExtensions 6 I have : 
Lib\
|_FolderA\
|_FolderB\
Lib\
|_catch.hpp
|_Fixtures.h

As if inside 'Lib', all files in '.' were put aside.

### Steps to reproduce

It's systematic in my repository, I work on Windows on a Dev drive (ReFS partition). git console client behavior is normal, no folders are splitted.

### Did this work in previous version of GitExtensions?

Yes, it worked in all previous versions, never had this problem.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #12585

## Proposed changes

`PathFirstComparer`:
- Distinguish folders having same start in order to avoid displaying a folder twice
- Do not ignore case

### Before

image

### After

image

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -3262,12 +3262,10 @@ public IEnumerable<IObjectGitItem> GetTree(ObjectId? commitId, bool full, string
...
-            if (isArtificial && !GitVersion.SupportUpdateRefs)
-            {
-                return _gitTreeParser.ParseLsFiles(result.StandardOutput);
-            }
-
-            return _gitTreeParser.Parse(result.StandardOutput);
+            IEnumerable<IObjectGitItem> tree = isArtificial && !GitVersion.SupportUpdateRefs
+                ? _gitTreeParser.ParseLsFiles(result.StandardOutput)
+                : _gitTreeParser.Parse(result.StandardOutput);
+            return tree.OrderBy(item => item.Name);
```
Comment (gerhardol) [inline src/app/GitCommands/Git/GitModule.cs]: I would prefer to avoid the variable here, others may not...

**Review by gerhardol — APPROVED** [review]
This could be tested by reordering items in tests/app/UnitTests/GitCommands.Tests/Git/GitTreeParserTests.cs

Otherwise seem to be complete

**Comment by mstv** [comment]
> This could be tested by reordering items in `tests/app/UnitTests/GitCommands.Tests/Git/GitTreeParserTests.cs`

I checked that these tests do not involve `GetTree`. They test functionality below it.
I hesitate to setup similar tests just in order to prevent somebody from removing the `.OrderBy`.

**Comment by mstv** [comment]
@Xavier-OM & @RussKie, could you please confirm the fix (https://ci.appveyor.com/api/buildjobs/ire2dyj4i11lonyt/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-6.1.0.18305-430cb6b01.zip)? Thanks

**Comment by Xavier-OM** [comment]
> @Xavier-OM & @RussKie, could you please confirm the fix (https://ci.appveyor.com/api/buildjobs/ire2dyj4i11lonyt/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-6.1.0.18305-430cb6b01.zip)? Thanks

I still see duplicated 'Lib' folder with this version.

**Comment by mstv** [comment]
Thanks for testing, @Xavier-OM.

I can reproduce it now. It is caused by the new code shared with the Diff tab. I need to debug `StatusSorter` and to add testcases.

File: src/app/GitUI/UserControls/FileStatusList.StatusSorter.cs [hunk 2]
```diff
@@ -147,10 +147,16 @@ private static int CompareNonNull(GitItemStatus l, GitItemStatus r)
...
-                    -1 => r.Path.Value.StartsWith(l.Path.Value, StringComparison.InvariantCultureIgnoreCase) ? 1 : -1,
-                    1 => l.Path.Value.StartsWith(r.Path.Value, StringComparison.InvariantCultureIgnoreCase) ? -1 : 1,
+                    -1 => StartsWith(r.Path, l.Path) ? 1 : -1,
+                    1 => StartsWith(l.Path, r.Path) ? -1 : 1,
                     _ => StringComparer.InvariantCultureIgnoreCase.Compare(l.Name, r.Name)
                 };
+
+                static bool StartsWith(RelativePath longPath, RelativePath shortPath)
+                {
+                    return longPath.Value.StartsWith(shortPath.Value, StringComparison.InvariantCultureIgnoreCase)
```
Comment (RussKie) [inline src/app/GitUI/UserControls/FileStatusList.StatusSorter.cs]: I have a split mind about this. Git is case sensitive, so even on Windows I feel we ought to be differentiating between "test" and "Test" folders. So, the comparison should be case sensitive.

Comment (mstv) [reply src/app/GitUI/UserControls/FileStatusList.StatusSorter.cs]: > I have a split mind about this.

Me, too, f.i.
image
will have "TranslationApp" first then.
This is just a matter of habit / convenience.

We will be on the safe side with case-sensitive comparison. Changing.

**Comment by mstv** [comment]
Does it work for you, @RussKie?

**Comment by RussKie** [comment]
Apologies, I have been very busy. I'll check next time I see this bug with the official version.
