### PR TITLE
Let RTB extension `GetPlainText` ignore links

### LINKED ISSUE #9726: `Copy commit info` with tons of links
### Environment

- Git Extensions 33.33.33
- Build fac6b8222c9606ec84e913631c89ecfad5d2440b
- Git 2.33.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 5.0.12
- DPI 96dpi (no scaling)

### Issue description

**Actual**
`RichTextBoxXhtmlSupportExtension.GetPlainText` returns
```
Author:		Gerhard Olsson <6248932+gerhardol@users.noreply.github.com>|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com|||mailto:6248932+gerhardol@users.noreply.github.com
Date:		9 hours ago (13.11.2021 12:29:52)
Committer:	GitHub <noreply@github.com>|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com|||mailto:noreply@github.com
Commit hash:	fac6b8222c9606ec84e913631c89ecfad5d2440b
Child:		Commit index|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222|||gitext://gotocommit/2222222222222222222222222222222222222222
Parent:		db1f24ae|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8|||gitext://gotocommit/db1f24ae4c5e8599cc8b9a0b92d9493f69ab80f8

TweakPng for some icons (#9719)

Remove pHYs attribute for scaling
Related links: View on GitHub|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b|||https://github.com/gitextensions/gitextensions/commit/fac6b8222c9606ec84e913631c89ecfad5d2440b, Issue 9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687|||https://github.com/gitextensions/gitextensions/issues/9687, Issue 9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719|||https://github.com/gitextensions/gitextensions/issues/9719
Contained in branches:
fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links|||gitext://gotobranch/fix/9687_commit_info_links
upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master|||gitext://gotobranch/upstream/master
upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD|||gitext://gotobranch/upstream/HEAD
Contained in no tag

Derives from no tag
```

**Expected**
no links (or else only non-GE-internal link only once)

```
Author:		Gerhard Olsson <6248932+gerhardol@users.noreply.github.com>
Date:		11 hours ago (13.11.2021 12:29:52)
Committer:	GitHub <noreply@github.com>
Commit hash:	fac6b8222c9606ec84e913631c89ecfad5d2440b
Child:		d71a4f53
Parent:		db1f24ae

TweakPng for some icons (#9719)

Remove pHYs attribute for scaling
Related links: View on GitHub, Issue 9719
Contained in branches:
fix/commit_info_links
upstream/master
upstream/HEAD
mstv/fix/commit_info_links
Contained in no tag

Derives from no tag
```

### Steps to reproduce

`Copy Commit info` using context menu from

image

### Did this work in previous version of GitExtensions?

I guess before .NET 5
*not* caused by switching the link separator from "#" to "|||"

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #9726

## Proposed changes

- Let `RichTextBoxXhtmlSupportExtension.GetPlainText` ignore links, which are returned multiple times (string length of link?)

## Screenshots 

see issue

## Test methodology 

- manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build d71a4f5344ecf5a5f119b4c9e18485de6366eeab
- Git 2.33.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 5.0.12
- DPI 96dpi (no scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs [hunk 1]
```diff
@@ -1076,7 +1076,11 @@ public static string GetPlainText(this RichTextBox rtb, int from, int to)
                 {
                     // select one character
                     rtb.Select(i, 1);
-                    text.Append(rtb.SelectedText);
+                    string selectedText = rtb.SelectedText;
+                    if (!selectedText.StartsWith(LinkSeparator))
```
Comment (gerhardol) [inline GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs:1080]: LinkSeparator is 3 bytes and only one is selected, how can this work?
Comment?

Comment (mstv) [reply GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs:1082]: I have added a comment.

Comment (gerhardol) [reply GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs:1082]: I would have preferred to see the comment on line 1077, now I have to read back and forward
```
//  Try to select one visible character (RichTextBox returns a string, may contain more than what is visible)
```
But approving a merge

**Review by gerhardol — APPROVED** [review]

File: GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs [hunk 2]
```diff
@@ -1074,9 +1074,15 @@ public static string GetPlainText(this RichTextBox rtb, int from, int to)
                 //--------------------------------
                 for (int i = from; i < to; i++)
                 {
-                    // select one character
+                    // try to select one visible character (RichTextBox returns a string, can be empty, may contain more than what is visible)
```
Comment (RussKie) [inline GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs:1077]:
```suggestion
                    // Try to select one visible character (RichTextBox returns a string, can be empty, may contain more than what is visible)
```

Comment (mstv) [reply GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs]: done, for the comment above, too

**Comment by RussKie** [comment]
:+1:
