### PR TITLE
Fix FormRemotes color label size

### LINKED ISSUE #12303: Color label is not in its place with higher scaling
### Environment

- GitExtensions version: master @ c40280f38b3fde418ecf73add681308aabd2916a
- OS version: Win11 with 200% scaling

### Issue description

UI looks like a mess due to huge label padding/marding

Image

### Steps to reproduce

- Display settings with scaling > 100%
- Open Remotes dialog

### Did this work in previous version of GitExtensions?

Doubt it..

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mdonatas**
Fixes #12303

## Proposed changes

- `AutoSize = true` for labels
- Prevent `btnRemoteColorReset` from blinking out part of a second after being shown

### Before

At 200%
image

### After

At 200%
image

At 100%
image

## Test methodology 

- Manully at 100% and 200% scaling

## Test environment(s) 

- Windows 11

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/CommandsDialogs/FormRemotes.cs [hunk 1]
```diff
@@ -113,6 +113,9 @@ public FormRemotes(IGitUICommands commands)
             // Set the minimum height of the color button to be the same as the reset button
             btnRemoteColor.MinimumSize = new Size(DpiUtil.Scale(60), btnRemoteColorReset.Height);
 
+            // Prevent btnRemoteColorReset from blinking out soon after form loads
+            btnRemoteColorReset.Visible = false;
```
Comment (RussKie) [inline src/app/GitUI/CommandsDialogs/FormRemotes.cs:117]: Set in the designer file please.

**Review by RussKie — APPROVED** [review]
Thank you

File: src/app/GitUI/CommandsDialogs/FormRemotes.cs (hunk 1 above)
Comment (mdonatas) [reply src/app/GitUI/CommandsDialogs/FormRemotes.cs]: The reason it wasn't set in a designer is that a few lines above its height is used to set `MinimumSize` of `btnRemoteColor` and if it's invisible during component initialization it has a wrong height.

I've changed the `MinimumSize` calculation of `btnRemoteColor` to use its own height as this is before index change event happens and this button's props are changed.
