### PR TITLE
fix(PatchProcessor): Fixup encoding for diff text

### LINKED ISSUE #12066: Inconsistent Encoding inside diff
### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.46.2.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET 8.0.11
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Image
Image

Lines deleted do not use Encoding setting of the diff viewer.

### Steps to reproduce

Change Encoding setting in Diff Viewer.

### Did this work in previous version of GitExtensions?

Yes.
Worked in [v4.2.1](https://github.com/gitextensions/gitextensions/releases/tag/v4.2.1)

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #12066

## Proposed changes

- `PatchProcessor.StartOfContentsRegex`: Move `'-'` to first position inside `"[ -+@]"` in order to avoid special meaning in regex.
  This made `CreatePatchFromString` choose the wrong encoding for removed line.

### Before

image

### After

image

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]
Do we have any tests coving this regression?

**Review by gerhardol — APPROVED** [review]
Good catch!
A weird range is still a range

File: src/app/GitCommands/Patches/PatchProcessor.cs [hunk 1]
```diff
@@ -39,7 +39,7 @@ private enum PatchProcessorState
         [GeneratedRegex(@$"(---|\+\+\+) [""]?[^/\s]+/(?<filename>.*)[""]?", RegexOptions.ExplicitCapture)]
         private static partial Regex FileNameRegex();
 
-        [GeneratedRegex(@$"^({_escapeSequenceRegex})?[ -+@]", RegexOptions.ExplicitCapture)]
+        [GeneratedRegex(@$"^({_escapeSequenceRegex})?[-+@ ]", RegexOptions.ExplicitCapture)]
```
Comment (gerhardol) [inline src/app/GitCommands/Patches/PatchProcessor.cs:42]: To further clarify

```suggestion
        [GeneratedRegex(@$"^({_escapeSequenceRegex})?[\-+@ ]", RegexOptions.ExplicitCapture)]
```

I searched for other occurrences, found one other, with no importance.
Also some testcases.
Pushed to private branch, suggest it is included

**Review by gerhardol — APPROVED** [review]
