### PR TITLE
fix(Jump List): Use unique name for recent repos

### LINKED ISSUE #10845: Don't overwrite recent repositories (%appdata%\...\Recent\.gitext) with the same name
## The Good
When you open a repository in Git Extensions on Windows, a `.gitext` file will be written in `%appdata%\GitExtensions\GitExtensions\Recent`. The contents of this file is a single line of text, representing the path of the opened repository. This `.gitext` file will then show up under "Recent" when right-clicking the app's icon, and you can pin repos that way:

context menu for Git Extensions icon on Windows

I like to open my pinned/favorite repositories this way - I also apply this to directories in Explorer, solutions in Visual Studio, files in Word, and so on.

## The Bad
These files however will only take the name of the rightmost directory of the path. So if you first open the repository at `C:\Dev\Foo\Bar` and then later `C:\Dev\TotallyOtherRepo\Bar`, the `Bar.gitext` file in the `Recent` directory will be updated with the latter path.

This means the path the pinned file points to will change, and reopening the pinned repository will open a different repository than pinned.

## The Ugly
This is especially confusing with submodules. I have:

* A library I'm developing under `C:\Dev\MyLib`
* An application I'm developing under `C:\Dev\MyApp`
  * With a submodule to the former, under `C:\Dev\MyApp\lib\MyLib`

And every time I open the submodule from within `MyApp`, the `MyLib.gitext` file will change to the latter path, and my pinned `MyLib` repo will open the repository in the submodule, instead of the "root" version at `C:\Dev\MyLib`. This is confusing and has caused me multiple times to start working in the wrong directory.

## The Requests
I see multiple solutions: 

0. Me paying more attention to which directory I'm in, but that won't fix pinning.
1. Me copying the `.gitext` file, renaming it (for example to `MyLib-root` or `MyLib-lib`) to prevent it from being overwritten, pinning that one. (This is my current workflow.)
2. Git Extensions not overwriting `.gitext` files when opening submodules.
3. Git Extensions not overwriting `.gitext` files whose path still exists, but instead adding a _new_ recent file with an earlier part of the path (`lib-MyLib`, `MyApp-lib-MyLib`, `MyOtherApp-lib-MyLib`), or add a suffix (`MyLib (2)`).
4. Create subdirectories within the Recent directory, like `Recent\C\Dev\MyLib.gitext`.
5. A combination of the above.

### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.15
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10845

## Proposed changes

- `WindowsJumpListManager` / `RepositoryDescriptionProvider`: Use unique name for recent repos
  descriptive name with full path appended

### Before

image

with

`repo.gitext` containing
`D:\Downloads\super\submodule2\repo\`
or
`D:\Downloads\super\submodule1\repo\`

### After

image   image

with `.git/description` containing:
- "super_repo"
- "sm1_repo"
- "sm2_repo"

## Test methodology 

- manual 

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs [hunk 1]
```diff
@@ -65,6 +77,34 @@ public string Get(string repositoryDir)
             return dirInfo.Name;
         }
 
+        public string GetDescriptiveUnique(string repositoryDir)
+        {
+            string unique = GetUnique(repositoryDir);
+
+            ReadOnlySpan<char> path = repositoryDir.AsSpan();
```
Comment (gerhardol) [inline src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs:84]: If .git/description exists, it must be used, set in line 91
Maybe no duplicate check even, use the name the user wants?

```suggestion
            string descName = Get(repositoryDir;
            ReadOnlySpan<char> path = repositoryDir.AsSpan();
```

File: src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs [hunk 2]
```diff
@@ -65,6 +77,34 @@ public string Get(string repositoryDir)
             return dirInfo.Name;
         }
 
+        public string GetDescriptiveUnique(string repositoryDir)
+        {
+            string unique = GetUnique(repositoryDir);
```
Comment (gerhardol) [inline src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs:82]: path set as `C__` when :\ is replaced in the filename. Maybe explicit rename here to avoid two __

Comment (gerhardol) [inline src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs:82]: I mostly have unique names of my superrepos, with the worktree name (often short like ge_1, ge_2 etc). This is mostly kept here, just with a suffix (I guess I get used to that).

If a supermodule has a description, it should be used for the unique part.

If no description, then the important part is often deeper in the path, I see many that keep structures like gitclones/project1, gitclones/project2. This will then keep the unique part just visible in the tooltip so the main benefit is just being unique.

**Review by gerhardol — COMMENTED** [review]
I see the current handling as a feature, it limits the number of submodules in the jumplist. Half the list will now be like "ICSharp" for me. But maybe better for others.

File: src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs (hunk 2 above)
Comment (gerhardol) [reply src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs]: OK, except the name for submodules. Will use some before approving.

Comment (mstv) [reply src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs]: > so the main benefit is just being unique.

That is what this PR is about.

> If a supermodule has a description, it should be used for the unique part.

This should be applied to `RepositoryDescriptionProvider.Get` and not only if there is a description file. Then the application title would benefit from this, too.
I think of "submodule - parentmodule (branch) - Git Extensions".
In the Jump List it would appear as "submodule - parentmodule (D_path_to_parent_subfolder_submodule)".
I would add just one level of super module.

Or else:

> Half the list will now be like "ICSharp" for me.

Perhaps we should add submodules to the GE-internal MRU list only, but not to the Jump List.

Comment (gerhardol) [reply src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs]: > > so the main benefit is just being unique.
> 
> That is what this PR is about.

There are many unique "ICSharp" that cannot be differentiated in a simple way as the diff is far right.
Just one "ICSharp"  is more a feature for me than in general, not objecting.

> > If a supermodule has a description, it should be used for the unique part.
> 
> This should be applied to `RepositoryDescriptionProvider.Get` and not only if there is a description file. Then the application title would benefit from this, too. I think of "submodule - parentmodule (branch) - Git Extensions". In the Jump List it would appear as "submodule - parentmodule (D_path_to_parent_subfolder_submodule)". I would add just one level of super module.

Yes, that seem fine. 
Supermodule instead of parent? (all levels will be too much)
It will not handle (slightly worse even) the the multiple clones, you cannot get it all.

> > Half the list will now be like "ICSharp" for me.
> 
> Perhaps we should add submodules to the GE-internal MRU list only, but not to the Jump List.

Exclude from both if implemented.
I have considered this for some years, but seen it as a setting that would be for primarily myself.

Comment (pmiossec) [reply src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs]: > I have considered this for some years, but seen it as a setting that would be for primarily myself.

Interested by that also : I've started to implement it long ago but there are some edge cases on currently opened submodule repo a little hacky to fix 🫤

**Review by gerhardol — APPROVED** [review]
comment
I like the text as in the title that was just added, mostly descriptive and could be used in addition to this detailed text.
If the path could be seen in the tooltip as for VS Code would be even better but then the .gitext file have to moved.

File: src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs [hunk 3]
```diff
@@ -92,6 +105,24 @@ string GetShortName(DirectoryInfo dirInfo)
...
+            int endOfLineIndex = descriptive.IndexOfAny(Delimiters.LineFeedAndCarriageReturnAndNull);
+            int descriptiveEnd = endOfLineIndex >= 0 ? endOfLineIndex : descriptive.Length;
+            descriptiveEnd = Math.Min(descriptiveEnd, maxDescriptiveLength);
+            ReadOnlySpan<char> shortName = descriptive.AsSpan(0, descriptiveEnd).Trim();
+
+            string unique = GetUnique(repositoryDir);
+            return shortName.Length == 0 ? unique : $"{shortName} ({unique})";
+        }
+
+        public string GetUnique(string repositoryDir)
```
[the remark this answers is not in the document]
Comment (mstv) [reply src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs:121]: for future use (I have nothing in mind)

File: src/app/GitUI/WindowsJumpListManager.cs [hunk 4]
```diff
@@ -107,6 +107,7 @@ public void AddToRecent(string workingDir)
 
                 // sanitise
                 StringBuilder sb = new(repositoryDescription);
+                sb.Replace(@":\", "_");
```
Comment (gerhardol) [inline src/app/GitUI/WindowsJumpListManager.cs:110]: discussion: 
It would be nize to have / instead of _ in the name, but this is a filename
Similar, I would like to replace \\wsl$ with /wsl or so but very minor diff anyway

File: src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (gerhardol) [reply src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs:121]: suggest to remove from public api

**Review by gerhardol — APPROVED** [review]

**Review by RussKie — COMMENTED** [review]
👍
