### PR TITLE
Feature/worktree fixes

### LINKED ISSUE #12322: Add keyboard shortcuts and navigation keys to Manage Worktree dialog
### Feature description

Propose to add shortcuts to Worktree dialog. Default is Alt+W
Image

Default focused control when opening Manage Worktree dialog is the git worktrees grid, so that keyboard input for arrow up | arrow down is possible without clicking in it or tabbing to focus it.
Image

Functionality for not being able to open currently active worktree is kept. 

Pressing enter or double clicking on a selected worktree presents the optional dialog to open it.
Image

Add possibility to enter keyboard shortcut in settings
Image

PS. I'm new contributor and don't have access to create PR:s, so i would like to get the access and push my suggestions.

### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

### PR DESCRIPTION
**Pull request by borzag**
Fixes #12322

## Proposed changes
See issue #12322 for details and more screenshots about the changes.
- Adds shortcut `Ctrl+Alt+W` key to open Repository->Manage Worktrees
- Adds possibility to change the shortcut in settings->Hotkeys->Browse->Manageworktrees.
- Sets the Worktrees datagrid focused when opening the Manage Worktrees form, so that it accepts navigating by up/down arrows immediately without having to focus it first.
- Enables enter key as default to open the selected worktree.
- Enables double click to open selected worktree.
- Supports optional question dialog to open selected worktree, as originally implemented, for all implemented events/eventhandlers.

### Before
image
image

### After
image
image

## Test methodology 
- Tested by running the app manually and seeing that the fixed issues worked.

## Merge strategy
I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
I was finding `Alt+W` a little strange as a shortcut (potentially conflicting with access keys), but looking at the PR, it seems `Ctrl+Alt+W` which probably makes more sens.

Could you clarify the point and fix the one that is wrong?

**Review by pmiossec — APPROVED** [review]

File: src/app/GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -1961,9 +1964,10 @@ internal enum Command
             OpenCommitsWithDifftool = 35,
             ToggleBetweenArtificialAndHeadCommits = 36,
             GoToChild = 37,
-            GoToParent = 38
+            GoToParent = 38,
 
             /* deprecated: RotateApplicationIcon = 14, */
+            ManageWorkTrees = 50,
```
Comment (mstv) [inline src/app/GitUI/CommandsDialogs/FormBrowse.cs:1970]:
```suggestion
            ManageWorkTrees = 49,
```
and move up to section "// REPOSITORY menu", please.

File: src/app/GitUI/CommandsDialogs/FormBrowse.cs [hunk 2]
```diff
@@ -1016,6 +1016,8 @@ private void InternalInitialize()
                     applyPatchToolStripMenuItem.Enabled = !bareRepository;
                 }
 
+                manageWorktreeToolStripMenuItem.ShortcutKeys = Keys.ControlKey | Keys.Alt | Keys.W;
+
```
Comment (mstv) [inline src/app/GitUI/CommandsDialogs/FormBrowse.cs:1020]: This is not necessary.

File: src/app/GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs [hunk 3]
```diff
@@ -188,7 +189,25 @@ private void buttonDeleteSelectedWorktree_Click(object sender, EventArgs e)
...
+            OpenSelectedWorktree();
+        }
+
+        private void Worktrees_KeyDown(object? sender, KeyEventArgs e)
+        {
+            if (e.KeyCode == Keys.Enter)
+            {
+                OpenSelectedWorktree();
+            }
+        }
```
Comment (mstv) [inline src/app/GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs:206]: Rather make the "Open" button the form's default button.

File: src/app/GitUI/Hotkey/HotkeySettingsManager.cs [hunk 4]
```diff
@@ -269,7 +269,8 @@ public IReadOnlyList<HotkeySettings> CreateDefaultSettings()
                     Hk(FormBrowse.Command.StashPop, Keys.Control | Keys.Alt | Keys.Down),
                     Hk(FormBrowse.Command.StashStaged, Keys.Control | Keys.Shift | Keys.Alt | Keys.Up),
                     Hk(FormBrowse.Command.ToggleBetweenArtificialAndHeadCommits, Keys.Control | Keys.OemBackslash),
-                    Hk(FormBrowse.Command.ToggleLeftPanel, Keys.Control | Keys.Alt | Keys.C)),
+                    Hk(FormBrowse.Command.ToggleLeftPanel, Keys.Control | Keys.Alt | Keys.C),
+                    Hk(FormBrowse.Command.ManageWorkTrees, Keys.Control | Keys.Alt | Keys.W)),
```
Comment (mstv) [inline src/app/GitUI/Hotkey/HotkeySettingsManager.cs:273]: These entries should be sorted alphabetically.

**Review by mstv — COMMENTED** [review]
nitpicks

File: src/app/GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs (hunk 3 above)
Comment (borzag) [reply src/app/GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs:206]: Unfortunately, that does not seem to work. It may have something to do with that pressing enter on current worktree (which is not possible to select and open), makes the selection focus on next worktree. Pressing that one (that is not the current one), does nothing. Probably the default button behavior in the form is overridden by the movement of selectable worktree.

**Comment by borzag** [comment]
> I was finding `Alt+W` a little strange as a shortcut (potentially conflicting with access keys), but looking at the PR, it seems `Ctrl+Alt+W` which probably makes more sens.
> 
> Could you clarify the point and fix the one that is wrong, please?

This is now set to 'Ctrl+Alt+W'.  Setting shortcut explicitly via
`manageWorktreeToolStripMenuItem.ShortcutKeys = Keys.ControlKey | Keys.Alt | Keys.W;' `
Makes it to 'Alt+W' for some reason??? This line is now removed and the shortcut is set by the HotkeySettingsManager.

**Comment by mstv** [comment]
> This is now set to 'Ctrl+Alt+W'. Setting shortcut explicitly via
> `manageWorktreeToolStripMenuItem.ShortcutKeys = Keys.ControlKey | Keys.Alt | Keys.W;' `
> Makes it to 'Alt+W' for some reason??? This line is now removed and the shortcut is set by the HotkeySettingsManager.

The assigned hotkeys are stored in your GitExtensions.settings file. I guess you had run it with the default "Alt+W" once. Just assign the new default manually in the settings page.

File: src/app/GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs (hunk 3 above)
Comment (mstv) [reply src/app/GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs:206]: OK

**Comment by borzag** [comment]
Sorry closed the PR by mistake. Wanted to close a comment.

**Comment by borzag** [comment]
> > This is now set to 'Ctrl+Alt+W'. Setting shortcut explicitly via
> > `manageWorktreeToolStripMenuItem.ShortcutKeys = Keys.ControlKey | Keys.Alt | Keys.W;' `
> > Makes it to 'Alt+W' for some reason??? This line is now removed and the shortcut is set by the HotkeySettingsManager.
> 
> The assigned hotkeys are stored in your GitExtensions.settings file. I guess you had run it with the default "Alt+W" once. Just assign the new default manually in the settings page.

I think it work as expected now.

File: src/app/GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs (hunk 3 above)
Comment (mstv) [reply src/app/GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs:206]: You could assign `AcceptButton` anyway to let the user know what hitting `Enter` causes.

**Comment by pmiossec** [comment]
> This is now set to 'Ctrl+Alt+W'.

@borzag 👍
I was more thinking about fixing the description (I did it) and the screenshots ( it would be best if you do it) according to the source code so that it is clear that is was on purpose and matching what we review.

**Comment by mstv** [comment]
Open:
- You could assign `AcceptButton` anyway to let the user know what hitting `Enter` causes.
- We need your sign-off in `contributors.txt`.

**Comment by borzag** [comment]
> Open:
> 
> * You could assign `AcceptButton` anyway to let the user know what hitting `Enter` causes.
> * We need your sign-off in `contributors.txt`.

1. Done
2. Added. Is it ok to be part of the PR?

**Comment by borzag** [comment]
> > This is now set to 'Ctrl+Alt+W'.
> 
> @borzag 👍 I was more thinking about fixing the description (I did it) and the screenshots ( it would be best if you do it) according to the source code so that it is clear that is was on purpose and matching what we review.

Fixed the screenshots to show before after!

**Review by mstv — APPROVED** [review]
Thank you

**Comment by borzag** [comment]
> Thank you

Thank you for all feedback!

**Comment by borzag** [comment]
I think the PR is finished now and could be merged.
Thank you all for the feedback!

**Review by gerhardol — APPROVED** [review]
