### PR TITLE
FormCommit: No summary  for deleted submodules

### LINKED ISSUE #8315: [NBug] Der Wert darf nicht NULL sein.Parametername: key
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: key
   bei System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   bei System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   bei GitUI.CommandsDialogs.FormCommit.generateListOfChangesInSubmodulesChangesToolStripMenuItem_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
wanted to create a list of messages of all subrepos. among normal commits, a new subrepo was added and an old one removed.

## Environment
- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #8316: [NBug] Die Sequenz enthält kein übereinstimmendes Element.
## Current behaviour

git extensions crashes when trying to create a list of changes in submodules (staged changes contain a new submodule and another that shall be removed).

## Expected behaviour

create a list of changes in submodules and do not crash

## Steps to reproduce

Win10,
create a repo with several subrepos/submodules. Then try to add another subrepo and remove a different one.
Then stage them in the commit dialog and try to create a list of changes in submodules (Commit message).

## Error Details
```
System.InvalidOperationException: Die Sequenz enthält kein übereinstimmendes Element.
   bei System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   bei GitUI.CommandsDialogs.FormCommit.generateListOfChangesInSubmodulesChangesToolStripMenuItem_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
create a repo with several subrepos/submodules. Then try to add another subrepo and remove a different one.
Then stage them in the commit dialog and try to create a list of changes in submodules (Commit message).

## Environment
- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #8315
Fixes #8316

## Proposed changes

Check if a submodule exists on the filesystem before trying to create a summary.
Note that deleted submodules are ignored in the summary.

## Test methodology 

See the issue

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 1]
```diff
@@ -2397,7 +2397,7 @@ private void generateListOfChangesInSubmodulesChangesToolStripMenuItem_Click(obj
             }
 
             Dictionary<string, string> modules = stagedFiles
-                .Where(item => item.IsSubmodule)
+                .Where(item => item.IsSubmodule && Directory.Exists(_fullPathResolver.Resolve(item.Name)))
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/FormCommit.cs:2400]: Depending on feedback to #8315 this should maybe be written as 
```
.Where(item => item.IsSubmodule && item.Name != null && Directory.Exists(_fullPathResolver.Resolve(item.Name)))
```
But I see no reason for Name to be null here

Comment (gerhardol) [reply GitUI/CommandsDialogs/FormCommit.cs]: Another change was needed, pushed.

**Comment by RussKie** [comment]
Merge at will
