### PR TITLE
fix: Migrate core.editor settings from GE x86 path

### LINKED ISSUE #11819: [vNext] Version targets x64 but tries access x86 paths
### Environment

- Git Extensions 4.3.0.17872-mbjjveco
- Build 70184a4c7252b263427ed627f5004e288e51b4bb (Dirty)
- Git 2.45.2.windows.1

### Issue description

Since https://github.com/gitextensions/gitextensions/pull/11625 we now publish platform-specific artifacts. The app is now being installed under `C:\Program Files\GitExtensions` instead of `C:\Program Files (x86)\GitExtensions`.
The app also has baked in paths in configs that must be updated.

image

```
"C:\Program Files\Git\bin\git.exe" -c rebase.autoSquash=false rebase -i --autosquash "7a328a52066bcee2f5396d3d01af3d189fe90a69"
hint: Waiting for your editor to close the file... "C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor: line 1: C:/Program Files (x86)/GitExtensions/GitExtensions.exe: No such file or directory
error: there was a problem with the editor '"C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor'
Done
```

### Steps to reproduce

1. Install **GitExtensions-x64-4.3.0.17872-70184a4c7.msi** from https://ci.appveyor.com/project/gitextensions/gitextensions/builds/50328130/artifacts
2. Try to interactively rebase

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #11819

## Proposed changes

Migrate editor settings if GE was installed in 'Program Files (x86)' before 4.3.
Only check and update global Git settings in Windows, the only set by GE.
Guess previous, migrate to current path (i.e. the first usage).

When running in debug, migration is not automatic as the debug path is probably not what should be used.

## Test methodology 

Manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitCommands/Settings/AppSettings.cs [hunk 1]
```diff
@@ -1649,6 +1684,7 @@ public static void LoadSettings()
             {
                 // Set environment variable
                 GitSshHelpers.SetGitSshEnvironmentVariable(SshPath);
+                MigrateEditorSettings();
```
Comment (RussKie) [inline src/app/GitCommands/Settings/AppSettings.cs:1687]: We need to check the bitness - we'll only building and publishing x64 version (now?) but it's possible to build x86 (and arm64) version. With this, we only need to migrate if the current version isn't x86 version.


...or does it matter?

**Review by RussKie — APPROVED** [review]

File: src/app/GitCommands/Settings/AppSettings.cs (hunk 1 above)
Comment (gerhardol) [reply src/app/GitCommands/Settings/AppSettings.cs:1687]: If we build x86, the settings will be overwritten with x86 again, so no major issue.
For other than x64 this is should not be necessary, but should not matter.

So it is better to check. What should we check? Platform?
(and if you run this without installing the 4.3 alpha installer, the migration will be to early, but that can be seen as a feature.)

File: src/app/GitCommands/Settings/AppSettings.cs [hunk 2]
```diff
@@ -2051,6 +2087,12 @@ public static bool GitAsyncWhenMinimized
             get => GetBool("GitAsyncWhenMinimized", false);
         }
 
+        public static bool IsEditorSettingsMigrated
+        {
+            get => GetBool("Git.IsEditorSettingsMigrated", false);
+            set => SetBool("Git.IsEditorSettingsMigrated", value);
+        }
+
```
Comment (mstv) [inline src/app/GitCommands/Settings/AppSettings.cs:2095]:
```suggestion
        private static readonly SettingsPath HiddenSettingsPath = new AppSettingsPath("Hidden");
        private static readonly SettingsPath MigrationSettingsPath = new AppSettingsPath(HiddenSettingsPath, "Migration");

        public static ISetting<bool> IsEditorSettingsMigrated { get; } = Setting.Create(MigrationSettingsPath, nameof(IsEditorSettingsMigrated), false);
```

File: tests/app/UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs [hunk 3]
```diff
@@ -376,6 +376,7 @@ static IEnumerable<(PropertyInfo property, object defaultValue, bool isNullable,
                 yield return (properties[nameof(AppSettings.BlameShowAuthorAvatar)], true, false, false);
                 yield return (properties[nameof(AppSettings.AutomaticContinuousScroll)], false, false, false);
                 yield return (properties[nameof(AppSettings.AutomaticContinuousScrollDelay)], 600, false, false);
+                yield return (properties[nameof(AppSettings.IsEditorSettingsMigrated)], false, false, false);
```
Comment (mstv) [inline tests/app/UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs:379]:
```suggestion
                yield return (properties[nameof(AppSettings.IsEditorSettingsMigrated)], false, isNotNullable, isISetting);
```

File: src/app/GitCommands/Settings/AppSettings.cs [hunk 4]
```diff
@@ -722,6 +722,41 @@ private static void MigrateSshSettings()
...
+        /// <summary>
+        /// Migrate editor settings if GE was installed in 'Program Files (x86)' before 4.3.
+        /// Only check and update global Git settings in Windows, the only set by GE.
+        /// Guess previous, migrate to current path (i.e. the first usage).
+        /// </summary>
+        private static void MigrateEditorSettings()
+        {
+            // Only run this once
+            bool isMigrated = IsEditorSettingsMigrated;
+            if (isMigrated)
```
Comment (mstv) [inline src/app/GitCommands/Settings/AppSettings.cs:734]:
```suggestion
            if (IsEditorSettingsMigrated)
```

File: src/app/GitCommands/Settings/AppSettings.cs [hunk 5]
```diff
@@ -722,6 +722,41 @@ private static void MigrateSshSettings()
...
+            {
+                return;
+            }
+
+            EnvironmentConfiguration.SetEnvironmentVariables();
+            ConfigFileSettings configFileGlobalSettings = ConfigFileSettings.CreateGlobal(false);
```
Comment (mstv) [inline src/app/GitCommands/Settings/AppSettings.cs:740]:
```suggestion
            ConfigFileSettings configFileGlobalSettings = ConfigFileSettings.CreateGlobal(useSharedCache: false);
```

File: src/app/GitCommands/Settings/AppSettings.cs [hunk 6]
```diff
@@ -722,6 +722,41 @@ private static void MigrateSshSettings()
...
+
+            string path = configFileGlobalSettings.GetValue("core.editor");
+            if (!path.Contains("Program Files (x86)/GitExtensions", StringComparison.CurrentCultureIgnoreCase))
+            {
+                return;
+            }
+
+#if DEBUG
+            // avoid setting, this may be in the debugger
+            DebugHelpers.Fail($"Update the core.editor path {path} in {configFileGlobalSettings}");
```
Comment (mstv) [inline src/app/GitCommands/Settings/AppSettings.cs:750]: Please throw a normal exception in order to not risk a hard termination of the app.

File: src/app/GitCommands/Settings/AppSettings.cs (hunk 2 above)
Comment (gerhardol) [reply src/app/GitCommands/Settings/AppSettings.cs:2095]: set is needed though, otherwise adding

File: src/app/GitCommands/Settings/AppSettings.cs (hunk 4 above)
Comment (gerhardol) [reply src/app/GitCommands/Settings/AppSettings.cs:734]: Missed to add back the migration check!

```suggestion
            bool isMigrated = IsEditorSettingsMigrated;
            IsEditorSettingsMigrated = true;
            if (isMigrated)
```

File: src/app/GitCommands/Settings/AppSettings.cs [hunk 7]
```diff
@@ -2087,11 +2089,9 @@ public static bool GitAsyncWhenMinimized
             get => GetBool("GitAsyncWhenMinimized", false);
         }
 
-        public static bool IsEditorSettingsMigrated
-        {
-            get => GetBool("Git.IsEditorSettingsMigrated", false);
-            set => SetBool("Git.IsEditorSettingsMigrated", value);
-        }
+        private static readonly SettingsPath HiddenSettingsPath = new AppSettingsPath("Hidden");
+        private static readonly SettingsPath MigrationSettingsPath = new AppSettingsPath(HiddenSettingsPath, "Migration");
```
Comment (mstv) [inline src/app/GitCommands/Settings/AppSettings.cs:2093]: move to top, please. There are defined other paths.

File: src/app/GitCommands/Settings/AppSettings.cs [hunk 8]
```diff
@@ -2087,11 +2089,9 @@ public static bool GitAsyncWhenMinimized
...
+        public static ISetting<bool> IsEditorSettingsMigrated { get; set; } = Setting.Create(MigrationSettingsPath, nameof(IsEditorSettingsMigrated), false);
```
Comment (mstv) [inline src/app/GitCommands/Settings/AppSettings.cs:2094]: It is an helper instance with the actual property (refer to other usages).
```suggestion
        public static ISetting<bool> IsEditorSettingsMigrated { get; } = Setting.Create(MigrationSettingsPath, nameof(IsEditorSettingsMigrated), false);
```

**Review by mstv — APPROVED** [review]
have not run

File: src/app/GitCommands/Settings/AppSettings.cs (hunk 1 above)
Comment (gerhardol) [reply src/app/GitCommands/Settings/AppSettings.cs:1691]: no ifdef added now
