### PR TITLE
Fix for #8030 URL in "Edit Remote Details"is case insensitive

### LINKED ISSUE #8030: URL in "Edit Remote Details" is case insensitive when checking for modifications
## Current behaviour

When changing a remote's url (eg migrating a repo from one server to another) it checks if the url has changed before saving. This check is not case sensitive. So if the url is case sensitive and changes only the casing, it will not save the change.

## Expected behaviour

Check the URL in a case sensitive manner.

## Steps to reproduce

Change Url Casing and click "Save Changes".

## Screenshots
image

## Did this work in previous version of GitExtensions

N/A

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

## Diagnostics

N/A

## PR Incoming
I should have time after work today to put together a PR for this. I have not looked at the code yet, but I can't imagine this would be a major change.  Is there any reason this should not always be case-insensitive?

### PR DESCRIPTION
**Pull request by digitalcoyote**
Fixes #8030

## Proposed changes

- Change SaveRemote to consider case when deciding if the url text has changed
- Override Autocomplete behavior in ComboBox to prevent it from resetting case-only changes

## Test methodology

- Manually tested by changing the url by 1,2 and 3 letters.
- Manually verified that autocomplete still works

## Test environment(s)

- GIT  2.26.2
- Windows 10 latest update

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by digitalcoyote** [comment]
Can someone review that build result? It seems like it should not be related my change.

> Command executed with exception: Cannot find path 'C:\projects\gitextensions\artifacts\tests\' because it does not exist.

**Comment by pmiossec** [comment]
Why did you create your commits from a very old commits?

Try rebase on the updated upstream `master` branch to see if that solve the problem (because a lot has changed since, especially on how translation is handled).

PS: FYI, on GitHub, creating a PR from a `master` branch is a bad practice. I advise you to not do it again...

**Comment by digitalcoyote** [comment]
Will do, I thought I pulled before starting. Thank You!

**Comment by digitalcoyote** [comment]
I have not retested since I did a pull and rebase. I'll try to get that done ASAP

**Comment by digitalcoyote** [comment]
Seems to still work as expected.

File: GitUI/CommandsDialogs/FormRemotes.cs [hunk 1]
```diff
@@ -703,5 +705,84 @@ private void ShowSeparatePushUrl(bool visible)
                 ? _labelUrlAsFetch.Text
                 : _labelUrlAsFetchPush.Text;
         }
+
+        public class ComboBox : System.Windows.Forms.ComboBox
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormRemotes.cs:709]: One class per file, please, i.e. move to `GitUI\UserControls`.

File: GitUI/CommandsDialogs/FormRemotes.cs [hunk 2]
```diff
@@ -703,5 +705,84 @@ private void ShowSeparatePushUrl(bool visible)
...
+        {
+            private AutoCompleteMode _autoCompleteMode = AutoCompleteMode.SuggestAppend;
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormRemotes.cs:711]: `const` or `readonly`?

File: GitUI/CommandsDialogs/FormRemotes.cs [hunk 3]
```diff
@@ -703,5 +705,84 @@ private void ShowSeparatePushUrl(bool visible)
...
+                }
+
+                return -1;
+            }
+
+            private void NotifyAutoComplete()
+            {
+                var text = Text;
+                var flag1 = text != _lastTextChangedValue;
+                var flag2 = false;
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormRemotes.cs:760]: Give them speaking names, please.

File: GitUI/CommandsDialogs/FormRemotes.cs [hunk 4]
```diff
@@ -703,5 +705,84 @@ private void ShowSeparatePushUrl(bool visible)
...
+                int stringIgnoreCase;
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormRemotes.cs:761]: Better name?

File: GitUI/CommandsDialogs/FormRemotes.cs (hunk 3 above)
Comment (digitalcoyote) [reply GitUI/CommandsDialogs/FormRemotes.cs]: Renamed to reflect the equivalent naming in ComboBox reference source

File: GitUI/CommandsDialogs/FormRemotes.cs (hunk 4 above)
Comment (digitalcoyote) [reply GitUI/CommandsDialogs/FormRemotes.cs]: Renamed to reflect the equivalent naming in ComboBox reference source

File: GitUI/CommandsDialogs/FormRemotes.cs (hunk 2 above)
Comment (digitalcoyote) [reply GitUI/CommandsDialogs/FormRemotes.cs]: Made const.

File: GitUI/CommandsDialogs/FormRemotes.cs (hunk 1 above)
Comment (digitalcoyote) [reply GitUI/CommandsDialogs/FormRemotes.cs]: Moved and renamed. It's no longer a subclass of FormRemotes. Not sure why I didn't do that to begin with since it's a general use Combobox replacement with case sensitive autocomplete.

**Comment by digitalcoyote** [comment]
Rebased on the latest commit while I was at it. Thank you for the detailed review.

**Comment by digitalcoyote** [comment]
> Since the sequence of the following commands seems to matter, add NUnit tests, please:
> 
> ```
>                     base.OnTextChanged(e);
>                     _lastTextChangedValue = text;
> ```

I don't believe the order should matter for these. `base.OnTextChanged(e);` alters `ComboBox._lastTextChangedValue` but this is a different variable than `CaseSensitiveComboBox._lastTextChangedValue` both are `private` fields

File: GitUI/UserControls/CaseSensitiveComboBox.cs [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+                    return;
+                }
+
+                base.OnTextChanged(e);
+                _lastTextChangedValue = text;
+            }
+            else
+            {
+                base.OnTextChanged(e);
+            }
```
Comment (mstv) [inline GitUI/UserControls/CaseSensitiveComboBox.cs:42]: If the sequence does not matter, this can be simplified:
```suggestion
                _lastTextChangedValue = text;
            }

            base.OnTextChanged(e);
```

File: GitUI/UserControls/CaseSensitiveComboBox.cs [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+        }
+
+        private int FindStringExactCase(string s)
+        {
+            for (int i = 0; i < Items.Count; i++)
+            {
+                if (((Repository)Items[i]).Path.Equals(s, StringComparison.Ordinal))
```
Comment (mstv) [inline GitUI/UserControls/CaseSensitiveComboBox.cs:49]: This should be generalized. Perhaps it suffices to compare the item text.

File: GitUI/CommandsDialogs/FormRemotes.cs [hunk 7]
```diff
@@ -2,6 +2,7 @@
 using System.Collections.Generic;
 using System.Drawing;
 using System.Linq;
+using System.Security.Principal;
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormRemotes.cs:5]: This can be removed, too.

**Comment by RussKie** [comment]
I plan to review this as soon as I can get my head above water.
I'm surprised the ComboBox control needs to be subclassed to achieve the desired.

**Comment by mstv** [comment]
> I'm surprised the ComboBox control needs to be subclassed to achieve the desired.

Perhaps it could be done using a decorator like `NativeTreeViewExplorerNavigationDecorator` or `NativeTreeViewDoubleClickDecorator`.

**Comment by digitalcoyote** [comment]
> Perhaps it could be done using a decorator like NativeTreeViewExplorerNavigationDecorator or NativeTreeViewDoubleClickDecorator.

Unless I'm mistaken about how that works, I don't believe that is an option. I'm specifically avoiding some of ComboBox's private methods that cause problems. `NotifyAutoComplete()` ends up calling `FindStringIgnoreCase()` and then sets the selected index (which causes the case change to be reverted).

**Comment by RussKie** [comment]
Thank you
