### PR TITLE
Exception for combined diff in CommitInfo

### LINKED ISSUE #5815: Exception showing combined diff on merge commit
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Double clicking a merge commit in the grid, then click the entry for 'combined diff'. The right hand side is populated with a stack trace:

```text
Unsupported file: 

System.ArgumentOutOfRangeException: CombinedDiff artificial commit cannot be explicitly compared: 3333333333333333333333333333333333333333, 16825d36221ab278d265ca4e2293a439074e14ba
Parameter name: firstRevision
Actual value was 3333333333333333333333333333333333333333.
   at GitCommands.Git.RevisionDiffProvider.GetInternal(String firstRevision, String secondRevision, String fileName, String oldFileName, Boolean isTracked)
   at GitCommands.GitModule.GetSingleDiff(String firstRevision, String secondRevision, String fileName, String oldFileName, String extraDiffArguments, Encoding encoding, Boolean cacheResult, Boolean isTracked)
   at GitUI.GitUIExtensions.GetItemPatch(GitModule module, GitItemStatus file, ObjectId firstRevision, ObjectId secondRevision, String diffArgs, Encoding encoding)
   at GitUI.GitUIExtensions.GetSelectedPatch(FileViewer diffViewer, ObjectId firstRevision, ObjectId secondRevision, GitItemStatus file)
   at GitUI.GitUIExtensions.<>c__DisplayClass3_0.<ViewChangesAsync>b__0()
   at GitCommands.AsyncLoader.<>c__DisplayClass11_0`1.<LoadAsync>b__0(CancellationToken token)
   at GitCommands.AsyncLoader.<LoadAsync>d__12`1.MoveNext()
```

This seems to happen for every merge commit. I just tested on 16825d36221ab278d265ca4e2293a439074e14ba and it happened:

image

**Environment you encounter the issue:**

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI X:150.00% Y:150.00%

**Did this work in previous version of GitExtensions (which)?**

Don't know.

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #5815

## Proposed changes
The artificial commit for combined difference must be specially handled in diffs.
This was not done for FileHistory CommitInfo

## Screenshots 
See issue for the exception

## Test methodology 
Manual, see the issue for an explanation

## Test environment(s)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/UserControls/CommitDiff.cs [hunk 1]
```diff
@@ -76,14 +77,30 @@ private async void DiffText_ExtraDiffArgumentsChanged(object sender, EventArgs e
             }
         }
 
+        // Partly the same as RevisionDiffControl.cs ShowSelectedFileDiffAsync()
```
Comment (gerhardol) [inline GitUI/UserControls/CommitDiff.cs]: The code change is based on RevisionDiffControl.cs ShowSelectedFileDiffAsync()
The diff handling should be updated, this is not adding much extra maintenance
(the primary alternative should be to keep the exception)

**Comment by gerhardol** [comment]
Merging tomorrow unless protests (rebased without changes)
