### PR TITLE
Delete temp files from settings tests

### LINKED ISSUE #9209: Settings tests leave files in `TEMP`
## Current behaviour

Settings tests leave a few thousend files in `%TEMP%`.
After several runs, tests fail because files already exist.

## Expected behaviour

Tests cleanup temp files

## Screenshots

image

## Did this work in previous version of GitExtensions

I think so

## Environment

- Git Extensions 33.33.33
- Build e91787fa894037581d678b16fa015c92543e1daf
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 5.0.6
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by mstv**
Fixes #9209

## Proposed changes

- Delete temp files from `AppSettingsTests` and `SettingTests`
- Dispose `GitExtSettingsCache` in all `AppSettingsTests` and in `OneTimeTearDown` of `SettingTests`
- Create `SettingTests._settingContainer` only once

## Test methodology 

- run NUnit tests

## Test environment(s) 

- Git Extensions 33.33.33
- Build 28814ce7ba5f63f1b557bbbd6f33616b5d016a45
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 5.0.6
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: UnitTests/CommonTestUtils/TempFileDeleter.cs [hunk 1]
```diff
@@ -0,0 +1,53 @@
+﻿using System;
+using System.Collections.Generic;
+using System.Diagnostics;
+using System.IO;
+
+namespace CommonTestUtils
+{
+    public sealed class TempFileDeleter : IDisposable
```
Comment (gerhardol) [inline UnitTests/CommonTestUtils/TempFileDeleter.cs:8]: Why not use something like https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.tempfilecollection?view=net-5.0

Comment (RussKie) [reply UnitTests/CommonTestUtils/TempFileDeleter.cs:8]: I think this will suffice https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/TestUtilities/TempFile.cs

File: UnitTests/GitCommands.Tests/Settings/SettingTests.cs [hunk 2]
```diff
@@ -13,17 +14,28 @@ internal sealed class SettingTests
...
-            _settingContainer = new RepoDistSettings(null, GitExtSettingsCache.Create(_settingFilePath), SettingLevel.Unknown);
+            _gitExtSettingsCache = GitExtSettingsCache.Create(_settingFilePath);
+            _settingContainer = new RepoDistSettings(null, _gitExtSettingsCache, SettingLevel.Unknown);
+        }
+
+        [OneTimeTearDown]
+        public void OneTimeTearDown()
+        {
+            _gitExtSettingsCache.Dispose();
+            _tempFileDeleter.DeleteAll();
```
Comment (RussKie) [inline UnitTests/GitCommands.Tests/Settings/SettingTests.cs:38]:
```suggestion
            _tempFileDeleter.Dispose();
```

File: UnitTests/CommonTestUtils/TempFileDeleter.cs (hunk 1 above)
Comment (mstv) [reply UnitTests/CommonTestUtils/TempFileDeleter.cs]: Thank you, I searched myself - but too focused on tests. `TempFileCollection` is the almost perfect match.

File: UnitTests/GitCommands.Tests/Settings/SettingTests.cs (hunk 2 above)
Comment (mstv) [reply UnitTests/GitCommands.Tests/Settings/SettingTests.cs]: done

**Review by gerhardol — APPROVED** [review]
Seem OK to me

**Review by RussKie — APPROVED** [review]
