### PR TITLE
#5125 RevisionGrid Graph: Nearest branch in tooltip

### LINKED ISSUE #4450: Commit branch name in commits list
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
"Revision graph" doesn't show hint in which branch we have "Dot" (commit). Commits list also doesn't show this information. User have to use Details panel / Commit tab, or double click on commit.

**What is the expected behavior?**
One or few from next list:
- On mouse hover on graph line, output hint about branch name
- On mouse hover on graph commit dot, output hint about commit hash AND branch name
- Possibility to turn on commits list column where user can see branch name

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.16.1
- OS version: Windows 10 1709 b16299.214

**Did this work in previous version of GitExtensions (which)?**
no

### LINKED ISSUE #5125: RevisionGrid Graph: Show more informative tooltips
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

tooltip with commit hash of wrong lane
grafik

**What is the expected behavior?**

commit hash, [*later:* branches contained in / being at] and commit heading of lane under mouse
grafik
grafik
grafik

**Environment you encounter the issue:**

- GitExtensions version: v3-ux, master
- GIT version: N/A (2.17.windows.2)
- OS version: N/A (Windows 7)
- .NET version: N/A

**Did this work in previous version of GitExtensions (which)?**

PR #5017 but with high load by firing git.exe for display of branch info

### PR DESCRIPTION
**Pull request by mstv**
Fixes #5125.
Fixes #4450.
Supersedes #5436 (adapted to new Revision Graph model).

#### Changes proposed in this pull request:
- Show nearest branch in tooltip of Revision Graph

#### Screenshots before and after (if PR changes UI):
- before
grafik
- after
grafik
grafik

#### What did I do to test the code and ensure quality:
- Add NUnit tests

#### Has been tested on (remove any that don't apply):
- Git Extensions 3.00.rc2
- 15258628f2415e635a998f32489bb44b9759b258 
- Git 2.19.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI X:100,00% Y:100,00%

### CODE REVIEW

**Comment by mstv** [comment]
It's WIP and that's why I described the current state, Jay.

**Comment by vbjay** [comment]
Gotya. It won't apply until merged. So it's ok to use fixes and closes.
Just making sure you knew.

File: GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs [hunk 1]
```diff
@@ -157,16 +136,16 @@ private bool FindBranch([NotNull] Node node)
...
-            /// (used for the decision whether the node belongs the first or second branch of the merge)
+            /// <param name="parent">
+            /// the node's parent in the branch which is currently descended
+            /// (used for the decision whether the node belongs to the first or second branch of the merge)
             /// </param>
-            private bool CheckForMerge([NotNull] Node node, [CanBeNull] Junction descJunction)
+            private bool CheckForMerge([NotNull] RevisionGraphRevision node, [CanBeNull] RevisionGraphRevision parent)
             {
-                bool isTheFirstBranch = descJunction == null || node.Ancestors.Count == 0 || node.Ancestors.First() == descJunction;
+                bool isTheFirstBranch = parent == null || node.Parents.Count == 0 || node.Parents.First() == parent;
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs]: The sequence of Parents is not "1st destination branch, 2nd merged branch(es)" for the optimized graph anymore.
It depends on the attempt to reduce the crossing of branches now. That's why my approach does not work anymore.
@spdr870, is the information which is the destination branch of a merge, stored somewhere?
If not, could you give me a hint where to add it?

Comment (spdr870) [reply GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs]: I was looping at the code and noticed you use the stattsegments and endsegments collections. Those are unordered. You probably do not want to use those. You should only use the parents and child collections. The parents collection is ordered. The first parent is the branch where the other parents are merged into. I do not change the parent order,  it is I  the same order as git returned it.

I'd you want I could fake a closer look at your code.

Comment (spdr870) [reply GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs]: Ignore my last commit... The parents are not ordered. They are stored in a concurrentbag. The startsegments are ordered. If you need the parents to be ordered, you can probably change the type ConcurrentBag into SynchonizedCollection.

File: GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+                    var segmentsForLane = row.GetSegmentsForIndex(lane);
+                    if (segmentsForLane.Count() > 0)
+                    {
+#if DEBUG
+                        var firstParent = segmentsForLane.First().Parent;
+                        foreach (var segment in segmentsForLane)
+                        {
+                            if (segment.Parent != firstParent)
+                            {
+                                throw new System.Exception(string.Format("All segments for a lane should have the same parent.\n"
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs]: Please use `using`
No need to translate the message.

File: GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+                                                                         + "Not fulfilled for rowIndex {0} lane {1} with {2} segments.",
+                                                                         rowIndex, lane, segmentsForLane.Count()));
+                            }
+                        }
+#endif
+                        return (segmentsForLane.First().Parent, isAtNode: false);
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs]: Please reuse `firstParent`

File: GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+                    {
+                        return (row.Revision, isAtNode: true);
+                    }
+
+                    var segmentsForLane = row.GetSegmentsForIndex(lane);
+                    if (segmentsForLane.Count() > 0)
+                    {
+#if DEBUG
+                        var firstParent = segmentsForLane.First().Parent;
+                        foreach (var segment in segmentsForLane)
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs]: I'm pretty sure this can be converted into a linq, something like 
```
if (segmentsForLane.Any(segment => segment.Parent != firstParent)) 
{
    throw(...)
}
```

File: GitUI/UserControls/RevisionGrid/RevisionGridToolTipProvider.cs [hunk 5]
```diff
@@ -56,6 +56,15 @@ string GetToolTipText()
                         provider.TryGetToolTip(e, revision, out var toolTip) &&
                         !string.IsNullOrWhiteSpace(toolTip))
                     {
+                        int lineCount = 0;
+                        for (int pos = 0; pos < toolTip.Length; ++pos)
+                        {
+                            if (toolTip[pos] == '\n' && ++lineCount == 30)
+                            {
+                                return toolTip.Substring(0, pos + 1) + ">>> TOOLTIP TRUNCATED <<<";
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/RevisionGridToolTipProvider.cs]: Should we use ellipses instead? We don't need to translate them and it is consistent with all other truncations we use.

File: UnitTests/GitUITests/UserControls/RevisionGrid/Graph/LaneNodeLocatorTests.cs [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+                                                    + "Not fulfilled for rowIndex {0} lane {1} with {2} segments.",
+                                                    row, lane, 2));
+            }
+#else
+            }
+            catch
+            {
+                throw;
+            }
+#endif
```
Comment (RussKie) [inline UnitTests/GitUITests/UserControls/RevisionGrid/Graph/LaneNodeLocatorTests.cs]: I find it overly confusing... What are we trying to achieve here?

File: GitUI/UserControls/RevisionGrid/RevisionGridToolTipProvider.cs (hunk 5 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionGridToolTipProvider.cs]: Ellipses should be used consistently. Separate issue and pr?

**Comment by RussKie** [comment]
I can agree to that

File: GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs [hunk 7]
```diff
@@ -0,0 +1,59 @@
...
+        {
+            _revisionGraphRowProvider = revisionGraphRowProvider;
+        }
+
+        public (RevisionGraphRevision, bool isAtNode) FindPrevNode(int rowIndex, int lane)
+        {
+            if (rowIndex < 0 || lane < 0)
+            {
+                // as unlikely as it may be...
+                // don't throw, just pretend we couldn't find it
```
[the remark this answers is not in the document]
Comment (mstv) [reply GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs]: It does not increase the number of code branches. But the non-trivial fallback return statement `return (null, false)` would have to be repeated several times.

File: GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs (hunk 1 above)
Comment (spdr870) [reply GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs]: In tests I did earlier I noticed that in many situations the SynchronizedCollection is even faster then the ConcurrentBag. Only in situations where many threads are used, the concurrentbag is faster. In our case, there usually is 1 thread and exceptionally max 2.

The EndSegments and StartSegments are mainly meant to be used for the graph itself. For your usage, I prefer only to use the Parents and Children. I might even remove the StartSegments from the revision class, since it is not needed there. It can easily be created later.

File: GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (RussKie) [reply GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs]: That's correct, the cyclomatic complexity (i.e. number of code paths) stay the same.
However it makes it easier to reason about the code. 
It is not uncommon, after such refactors it becomes easier to see how to minimise the number of code paths.

> But the non-trivial fallback return statement `return (null, false)`

That's fine

File: GitUI/UserControls/RevisionGrid/RevisionGridToolTipProvider.cs (hunk 5 above)
Comment (RussKie) [reply GitUI/UserControls/RevisionGrid/RevisionGridToolTipProvider.cs]: I'm ok with that.

**Comment by mstv** [comment]
The CodeCov upload fails very often with "The remote server returned an error: (403) Forbidden."

**Comment by RussKie** [comment]
> The CodeCov upload fails very often with "The remote server returned an error: (403) Forbidden."

Yes, it is been happening for past month or so now... 😞

**Comment by RussKie** [comment]
I had a very quick look over the code, it looked good. I'll review it properly in near future.

**Comment by mstv** [comment]
This PR resolves several wrong tooltips for the current graph, e.g.
grafik
should be
grafik

At least my changes regarding `segmentsForLane.Count() == 1` in the new file `LaneNodeLocator.cs` should be applied to the RC.

**Comment by RussKie** [comment]
@spdr870  @gerhardol @mstv are we all happy with the PR?

**Comment by spdr870** [comment]
I would like to test if there are performance issues in the linux repo. With full history. Just to make sure it's ok. I could imagine that we need some kind of guard that we do not travel to many commits. It's late here, will do it tomorrow. 

Just a side note; this would be a lot easier and faster in my lane info branch. It's not completely tested,  but should be ok. But that's something for later.

File: GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs [hunk 8]
```diff
@@ -11,6 +11,8 @@ namespace GitUI.UserControls.RevisionGrid.Graph
     internal sealed class LaneInfoProvider
     {
         private static readonly TranslationString NoInfoText = new TranslationString("Sorry, this commit seems to be not loaded.");
+        private static readonly TranslationString MergedWithText = new TranslationString("merged with");
```
Comment (gerhardol) [inline GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs]: The string should probably be "merged with {0}" to support right-to-left languages - but there are many issues anyway...
Or is it even required to parse correctly? (regexp on line 85?)

**Comment by RussKie** [comment]
> this would be a lot easier and faster in my lane info branch. It's not completely tested, but should be ok. But that's something for later.

@mstv @spdr870 perhaps it is worth for you to collaborate and see this through to completion.

File: GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs (hunk 8 above)
Comment (mstv) [reply GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs]: Good point, changed it.
Parsing works independently. Though if Git's merge messages can be internationalized, then the regexp must be adapted, too.

**Comment by mstv** [comment]
Just now and yesterday, Git 2.20.0.windows.1 failed quite often because of the `index.lock` file (git.exe was called from the Commit dialog to selectively revert changes and to commit).
`Repository | Git maintenance | Delete index.lock` did not help since the file does not exist.
It did not happen with 2.19.1 with the same GE build. Should I open a GE issue regardless it is most likely a Git issue?

**Comment by mstv** [comment]
The `index.lock` issue might be caused by an update of the anti-virus SW because 2.19.1 is affected, too, now.

**Comment by vbjay** [comment]
Which av? I have uploaded all the git binaries to virus total as a zip to
help with new git deployments. Also why do don't upgrade right when it gets
released.

**Comment by mstv** [comment]
I use my own *extended* build with several pending PRs merged in.
I did not say that the AV would complain about GE. Kaspersky seems to be just too slow "checking" the `index.lock` which makes it exist longer than Git expects.

**Comment by mstv** [comment]
@spdr870, which information from `LaneInfo.cs` should make the search for the nearest branch easier?
The direction of this search is only *upwards* the tree (children), not downwards (parents).

(Maybe `LaneInfo.StartRevision` could be used to improve or simplify the `LaneNodeLocator`, which will not be changed by this PR.)

**Comment by spdr870** [comment]
I tested the branch. Its fast, even on the linux repo on the last commit with all commits loaded. 

I have some concerns;
- The method FindBranchRecursively is recursive. We recently had some issues with stack overflows in other places. This is a candidate for such issues. Especially since the recursion can go very deep. The commit message is parsed and it is possible that this message is not there. Not sure if git could use other languages, but users could change it. I would like either a recursion limit or a rewrite to use a stack instead of recursion. A limit is better in my opinion. We could even get rid of this function, see comment below.
- If the 'LaneInfo' branch on my fork is used, the merge commit is known. This would remove the need of searching for the merge commit. Its not a requirement, but for this feature this will really help. The laneInfo class has a property 'StartRevision' which is the merge commit. The regex is still needed to get the branch name, but not for finding the correct commit. We can simplify a lot and remove the _visitedMergeNodes probably.
- Just a note; The change from ConcurrentBag to SynchronizedCollection will cause locking and many context switches. In #5899 another, faster, list type is used. Not a problem, because its also an ordered list and both PR's are compatible. 

Problem with the laneinfo branch is that I want to make sure it has no performance penalty. So, we could opt for just adding a recursion guard and nothing else. When I am ready with the laneinfo goodness, I can make the optimalizations.

**Comment by mstv** [comment]
Thank you for the clarification and the hints, Henk. I forgot that you look at the tree in the opposite direction. A merge is rather the end than the start to me from the logical aspect (in constrast to drawing).
I agree: If the search would check only for merge commits, the use of the property `LaneInfo.StartRevision` would avoid to visit all the non-merge nodes. Though the search shall stop on found refs, too (refer to the function `BranchFinder.FindBranch`).

Usually, there will be some branch information even when the search follows only the first child. Hence the recursion can be replaced with a simple loop. Then only for theoretical branch trees like in the test case `GetLaneInfo_should_display_only_the_branch_from_detected_merge_node_in_a_tree`, no branch will be displayed. Now when searching the branch information for the node "real", the node "merge" would not be visited and no branch would be found:
```
artificial
|  merge
|  |     \
|  inner  (omitted)
| /
undetected merge
|               \
real             (omitted)
```
I think this will be no substantial drawback.
(The main focus of this test case is different. That's why I will adapt it so that the merge to be found is located in the path of the first children.)

For this PR, I would keep using the already existing `SynchronizedCollection`. Of course, it should be replaced when the PR #5899 will be ready.

**Comment by mstv** [comment]
I have adapted it to the reverse order of `Children` and `Parents` because they are stored in `ImmutableStack`s now.

This PR is ready IMO.
Later(?), it could be extended to display more precise information for multi-branch merges and for merges of tags how (both seen in the Linux repo).

File: UnitTests/GitUITests/UserControls/RevisionGrid/Graph/LaneInfoProviderTests.cs [hunk 9]
```diff
@@ -43,17 +117,61 @@ public void Setup()
...
 
-        private void GetLaneInfo_should_display(RevisionGraphRevision node, string prefix = "", string suffix = "")
+        private void GetLaneInfo_should_display(RevisionGraphRevision node,
+            string branch = null, string mergedWith = null,
+            string prefix = "", string suffix = "")
         {
             _infoProvider.GetLaneInfo(0, 0).Should()
-                .Be(string.Format("{0}{1}{2}{2}{3}{4}",
+                .Be(string.Format(branch == null ? "{0}{1}{2}{2}{6}{7}"
+                                                 : "{0}{1}{2}\n{3}: {4}{5}{2}{6}{7}",
```
Comment (gerhardol) [inline UnitTests/GitUITests/UserControls/RevisionGrid/Graph/LaneInfoProviderTests.cs]: Why mix \n and Environment.NewLine?

**Comment by gerhardol** [comment]
No slowdowns seen in for instance Linux repo

**Comment by RussKie** [comment]
Thank you, a massive effort

**Comment by mstv** [comment]
Thank you for maintaining GE and for the review hints. They are really necessary and helpful.

File: UnitTests/GitUITests/UserControls/RevisionGrid/Graph/LaneInfoProviderTests.cs (hunk 9 above)
Comment (mstv) [reply UnitTests/GitUITests/UserControls/RevisionGrid/Graph/LaneInfoProviderTests.cs]: Will be resolved by PR #6237.
