### PR TITLE
Do not deregister from Application.ThreadException between tests

### LINKED ISSUE #7684: Catch unhandled exceptions popped up by test runner
## Current behaviour

Although `nunit3-console.exe` is [configured](https://github.com/nunit/nunit-console/blob/dfd07ef27cac9082c9728f0e55b84d1237830605/src/NUnitConsole/nunit3-console/app.config#L16-L17) to catch all exceptions, some exceptions do popup

grafik

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<GetOutputAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.Git.AheadBehindDataProvider.GetData(Encoding encoding, String branchName)
   at GitCommands.Git.AheadBehindDataProvider.GetData(String branchName)
   at GitUI.BranchTreePanel.RepoObjectsTree.BranchTree.FillBranchTree(IEnumerable`1 branches, CancellationToken token)
   at GitUI.BranchTreePanel.RepoObjectsTree.BranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass40_0.<<AddTree>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
nunit.framework
    Assembly Version: 3.10.1.0
    Win32 Version: 3.10.1.0
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/nunit.framework.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
nunit.engine
    Assembly Version: 3.7.0.0
    Win32 Version: 3.7.0.0
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/nunit.engine.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
UITests
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/UITests.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
GitCommands
    Assembly Version: 4.0.0.8061
    Win32 Version: 4.0.0.8061
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/GitCommands.DLL
----------------------------------------
Microsoft.VisualStudio.Threading
    Assembly Version: 16.4.0.0
    Win32 Version: 16.4.33.6023
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/Microsoft.VisualStudio.Threading.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
GitUIPluginInterfaces
    Assembly Version: 4.0.0.8061
    Win32 Version: 4.0.0.8061
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/GitUIPluginInterfaces.DLL
----------------------------------------
GitUI
    Assembly Version: 4.0.0.8061
    Win32 Version: 4.0.0.8061
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/GitUI.DLL
----------------------------------------
ResourceManager
    Assembly Version: 4.0.0.8061
    Win32 Version: 4.0.0.8061
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/ResourceManager.DLL
----------------------------------------
CommonTestUtils
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/CommonTestUtils.DLL
----------------------------------------
System.IO.Abstractions
    Assembly Version: 2.0.0.144
    Win32 Version: 2.0.0.144
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/System.IO.Abstractions.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
ApprovalTests
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.13
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/ApprovalTests.DLL
----------------------------------------
GitExtUtils
    Assembly Version: 4.0.0.8061
    Win32 Version: 4.0.0.8061
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/GitExtUtils.DLL
----------------------------------------
Microsoft.VisualStudio.Validation
    Assembly Version: 15.3.0.0
    Win32 Version: 15.3.15.16354
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/Microsoft.VisualStudio.Validation.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
FluentAssertions
    Assembly Version: 5.2.0.0
    Win32 Version: 5.2.0.0
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/FluentAssertions.DLL
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
SmartFormat
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/SmartFormat.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Reactive
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0.1
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/System.Reactive.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
LibGit2Sharp
    Assembly Version: 0.25.0.0
    Win32 Version: 0.25.0.84
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/LibGit2Sharp.DLL
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.3.3
    Win32 Version: 1.1.3.3
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.ApplicationInsights
    Assembly Version: 2.10.0.0
    Win32 Version: 2.10.0.24102
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/Microsoft.ApplicationInsights.DLL
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/System.Collections.Immutable.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ICSharpCode.TextEditor
    Assembly Version: 4.0.0.8061
    Win32 Version: 4.0.0.8061
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/ICSharpCode.TextEditor.DLL
----------------------------------------
Ben.Demystifier
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.4.21
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/Ben.Demystifier.DLL
----------------------------------------
Microsoft.VisualStudio.Composition
    Assembly Version: 15.6.0.0
    Win32 Version: 15.6.36.41634
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/Microsoft.VisualStudio.Composition.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.3.3
    Win32 Version: 1.1.3.3
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.DirectoryServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ConEmuWinForms
    Assembly Version: 4.0.0.8061
    Win32 Version: 4.0.0.8061
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/ConEmuWinForms.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 1.4.2.0
    Win32 Version: 4.6.25519.03
    CodeBase: file:///C:/projects/gitextensions/IntegrationTests/UITests/bin/Release/net461/System.Reflection.Metadata.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

Perhaps the test assemblies would need their own `app.config`.

_Originally posted by @mstv in #7628_

## Expected behaviour

All exceptions thrown during test execution are catched and traced.

## Steps to reproduce

- trigger AppVeyor builds

## Did this work in previous version of GitExtensions

not for quite a long time

## Environment

- AppVeyor
- Windows 10

### PR DESCRIPTION
**Pull request by mstv**
Fixes #7684

## Proposed changes

Do not deregister from `Application.ThreadException` _between_ tests in order to catch all exceptions while running tests

## Test environment(s) 

- AppVeyor
- Windows 10

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs [hunk 1]
```diff
@@ -21,12 +21,15 @@ public sealed class ConfigureJoinableTaskFactoryAttribute : Attribute, ITestActi
 
         public ActionTargets Targets => ActionTargets.Test;
 
+        public ConfigureJoinableTaskFactoryAttribute()
+        {
+            Application.ThreadException += HandleApplicationThreadException;
```
Comment (RussKie) [inline UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs]: That's probably better.
We did find a bug in WinForms implementation that under heavy load led to race conditions and overall instability
https://github.com/dotnet/winforms/pull/2713
