### PR TITLE
Git 2.39 bugs out for fetch --jobs=0

### LINKED ISSUE #10514: Unable to run git commands from Git Extensions
### Environment

- GitExtensions version: 4.0.0.15569
- GIT version: 2.39.0
- OS version: Windows 11 22H2 (22621.819)
- .NET version: 6.0.11

### Issue description

This is a new Git Extensions install on a new computer.
I have some cloned repositories but whenever i try to do a fetch or pull from Git Extensions it fails.
Pull:
image

Fetch:
image

Git complains about the --jobs=0 option.
If I run the same command in Git Bash, it has the same error, but if I remove the --jobs=0 option, it works fine in Git Bash

I can't find a way to control that option from Git Extensions

### Steps to reproduce

Clone any repository
Perform a Fetch or Pull from Git Extensions

### Did this work in previous version of GitExtensions?

I don't have the problem on another computer running Git Extensions 3.5.3.12551 and Git 2.33.0

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #10514

## Proposed changes

Provide the options as Git config options instead

If user hast set fetch.parallel or submodule.fetchJobs is set, do not set the options

## Test methodology 

Test updated

## Test environment(s) 

- GIT 2.38, 2.39

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -3,6 +3,7 @@
 using System.Diagnostics.CodeAnalysis;
 using System.Net.Mail;
 using System.Security;
+using System.Security.Policy;
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:6]: I guess this is not necessary.

**Review by mstv — APPROVED** [review]
👍 works for Git 2.38.1

File: GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs]: Reverted, force pushed (also fixed some tests).

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you
