### PR TITLE
fix: NRE

### LINKED ISSUE #3787: NRE when attempting to resolve merge conflicts with unconfigured merge tool
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Merge tool isn't correctly configured, an attempt to resolve merge conflicts results in NRE

**What is the expected behavior?**
User-friendly prompt to configure the merge tool

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
2.49.03, current dev branch

### PR DESCRIPTION
**Pull request by RussKie**
Currently it throws a NRE when attempting to resolve merge conflicts with unconfigured merge tool.
The fix checks for the merge tool configuration and if the tool is not configured it prompts the user to configure the tool first.

Fixes #3787

 
Before:
image

After:
image

### CODE REVIEW

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 1]
```diff
@@ -499,39 +506,50 @@ private static void DeleteTemporaryFiles(string[] filenames)
...
                 {
-                    _mergetoolPath = _mergetoolCmd.Substring(0, idx + executablePattern.Length + 1).Trim(new[] { '\"', ' ' });
-                    _mergetoolCmd = _mergetoolCmd.Substring(idx + executablePattern.Length + 1);
+                    MessageBox.Show(this, noMergeToolConfigured.Text);
+                    return false;
+                }
+
+                if (!EnvUtils.IsMonoRuntime())
+                {
+                    //This only works when on Windows....
```
Comment (jbialobr) [inline GitUI/CommandsDialogs/FormResolveConflicts.cs]: If it only works on windows, should not it be used `RunningOnWindows`?

Comment (RussKie) [inline GitUI/CommandsDialogs/FormResolveConflicts.cs]: I don't think it is material, but I'll change it
