### PR TITLE
Fix copying RichTextBox text and restore context menu for CommitInfoHeader

### LINKED ISSUE #6045: Copy Commit Info distorts the Commit Info display
## Current behaviour / Steps to reproduce

- The context menu is not available in the `CommitInfoHeader` of GE 3.0.0 (regression from 2.51.05)
- copying the commit info:
grafik
- removes all the links:
grafik
- after copying again, the commit info is not redrawn:
grafik
- clicking others commits shows links but with distorted layout:
grafik
## Expected behaviour
Copying is a read-only operation. The Commit Info display shall not change.

## Did this work in previous version of GitExtensions

don't know

## Environment

- Git Extensions 2.51.02, 2.51.05 and 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.10.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by mstv**
Fixes #6045

## Proposed changes

- restore symmetry, i.e. do not touch `rtb.HideSelection` at all
- invalidate RichTextBox after `EndUpdate`
- assign context menu to CommitInfoHeader, too

### After

grafik

## Test methodology

- manual testing

## Test environment

- Git Extensions 3.01.00.0
- Build 4d1f476ec202a5a2ee08ce4a96b5bb3daf83a05f
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

### CODE REVIEW

File: GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs [hunk 1]
```diff
@@ -1142,8 +1142,8 @@ public static string GetPlainText(this RichTextBox rtb, int from, int to)
                 rtb.SelectionLength = nEnd;
 
                 rtb.EndUpdate(oldMask);
-                rtb.HideSelection = false;
-
+                rtb.Invalidate();
+                ////rtb.HideSelection = false
```
Comment (RussKie) [inline GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs]: Please remove, if this is no longer required

Comment (mstv) [reply GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs]: I have removed the commented out code.
