### PR TITLE
fix-9085 Change DialogResult only after saving before closing

### LINKED ISSUE #9085: FormSettings: `Apply` closes the dialog
## Current behaviour

The `Apply` button of FormSettings closes the dialog
because `DialogResult = DialogResult.OK` was moved to method `Save` in #9025.

## Expected behaviour

Dialog not closed by `Apply`.

## Did this work in previous version of GitExtensions

3.5 RC1

## Environment

- Git Extensions 33.33.33
- Build 85eebb2ed6d7289e848acc272d89d0be5325af39
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by ivangrek**
Fixes #9085

## Proposed changes

- Change DialogResult only after saving before closing

### Before

Settings dialog is closed

### After

Settings dialog is not closed

## Test methodology 

- manually

## Test environment(s) 

- Git Extensions 33.33.33
- Build f840a0ab83a461035f816951fe39c752a92abc4c
- Git 2.30.2.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — COMMENTED** [review]
This does not suffice: Consider "Apply", "Cancel" => GE not refreshed.
It might be easier to use a new dedicated `Changed` property than `DialogResult` in order too avoid the side effect of closing the Form on assignment.

File: GitUI/CommandsDialogs/FormSettings.cs [hunk 1]
```diff
@@ -252,8 +253,6 @@ private bool Save()
                 // TODO: this method has a generic sounding name but only saves some specific settings
                 AppSettings.SaveSettings();
 
-                DialogResult = DialogResult.OK;
-
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormSettings.cs:256]: Why not `_saved = true` here - single place?

**Review by mstv — APPROVED** [review]
Thank you
