### PR TITLE
fix: use posix path on FormBrowse.InitMenusAndToolbars

### LINKED ISSUE #10479: File History of repo root items in \\wsl$ works, but fails for non-root items
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22623.0
- .NET 6.0.11
- DPI 192dpi (200% scaling)

## File history working with `\\wsl.localhost`

Animation

## File history failing with `\\wsl$`

Animation2

### Steps to reproduce

Just open a WSL repo file `\\wsl$` (so that the git in WSL is used)

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by pedrolamas**
Fixes #10479

## Proposed changes

Ensure we call `.ToPosixPath()` on the filename before calling `FormBrowse.InitMenusAndToolbars()` method.

## Test methodology 

- Manual run to check everything worked as expected in both WSL2 and non-WSL2 repos.

## Test environment(s) 

- GIT 2.39.2.windows.1 (Windows), 2.34.1 (Ubuntu in WSL2)
- Windows 11 (latest insider release)

## Merge strategy

- Squash merge (maintainer to decide merge message, PR submitter should cleanup commits/messages at PR approval).

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/GitUICommands.cs [hunk 1]
```diff
@@ -1168,8 +1168,8 @@ public bool StartBrowseDialog(IWin32Window? owner, BrowseArguments? args = null)
 
         public void StartFileHistoryDialog(IWin32Window? owner, string fileName, GitRevision? revision = null, bool filterByRevision = false, bool showBlame = false)
         {
-            string arguments = AppSettings.UseBrowseForFileHistory.Value ? $"browse {PathFilterArg}={fileName.Quote()} -commit={revision?.ObjectId}"
-                : $"{(showBlame ? BlameHistoryCommand : FileHistoryCommand)} {fileName.Quote()} {revision?.ObjectId} {(filterByRevision ? FilterByRevisionArg : string.Empty)}";
+            string arguments = AppSettings.UseBrowseForFileHistory.Value ? $"browse {PathFilterArg}={fileName.ToPosixPath().Quote()} -commit={revision?.ObjectId}"
```
Comment (gerhardol) [inline GitUI/GitUICommands.cs:1171]: This could also be done in FormBrowse.cs:278
```
InitMenusAndToolbars(args.RevFilter, args.PathFilter.ToPosixPath());
```

**Review by gerhardol — COMMENTED** [review]
+1

File: GitUI/GitUICommands.cs (hunk 1 above)
Comment (pedrolamas) [reply GitUI/GitUICommands.cs:1171]: @gerhardol Happy to change it if that is best place! 🙂

Comment (pedrolamas) [reply GitUI/GitUICommands.cs]: Updated!

**Review by gerhardol — APPROVED** [review]

**Comment by pmiossec** [comment]
Rebasing my custom branch, I saw that I had this fix locally since some times (I have not upstreamed it because I was not sure if it was solving a real issue or a bug introduced by me elsewhere) but I had a null check before calling `.ToPosixPath()` (with `args.PathFilter?.ToPosixPath()`) and even if I don't remember, I'm tend to think that I have not put it without reason...

@pedrolamas Are you sure it could never be null?

**Comment by pedrolamas** [comment]
> @pedrolamas Are you sure it could never be null?

In all honesty, I did not... I blindly followed @gerhardol suggestion as it made sense and just copy-pasted it in... apologies, that was poor coding from my part.

Having said that, `ToPosixPath` extension method has a null check inside, so there shouldn't be any risk of this blowing up:

https://github.com/gitextensions/gitextensions/blob/f5a55ca6d7566d0d393f8fbd4e87d3958733701c/GitCommands/PathUtil.cs#L19-L23

**Comment by pmiossec** [comment]
@pedrolamas Forget my comment. I had a look and we ensure that the value is `string.Empty` and not `null`.
The variable declaration is just misleading...

**Comment by pmiossec** [comment]
I posted my last comment before seeing your answer @pedrolamas : It's ok. Everything is fine in fact. Thanks for the fix.

**Comment by gerhardol** [comment]
...and the separate path for the standalone FormFileHistory does not need the change.

The modified way handles some other potential situations.
