### PR TITLE
Fixup GetAllBranchesWhichContainGivenCommit

### LINKED ISSUE #10819: CommitInfo: "Contained in branches" splits branch name at '+' character
### Environment

- GitExtensions version: 4.0.2

### Issue description

branch names containing "+" character(s) are incorrectly split in the CommitInfo panel at least

### Steps to reproduce

Create branches named "a", "b", merge them to "a+b"
Select "a"; look at "Contained in branches:
actual: "a, a, b"
expected: "a, a+b"

### Did this work in previous version of GitExtensions?

I doubt it

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10819

## Proposed changes

- correctly split git output, i.e. only at line ends
- remove first two columns only if in expected format "* ", "+ " or "  "

## Screenshots 

n/a

## Test methodology 

- extended existing testcase

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -3141,12 +3141,12 @@ public IReadOnlyList<string> GetAllBranchesWhichContainGivenCommit(ObjectId obje
                 return Array.Empty<string>();
             }
 
-            var result = exec.StandardOutput.Split(new[] { '\r', '\n', '*', '+' }, StringSplitOptions.RemoveEmptyEntries);
+            string[] result = exec.StandardOutput.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs:3144]: It would be good to add a comment explaining what information git may provide and what transformation we do.
IIRC, `*` denotes the current branch, but I can't remember what `+` may be used for...

**Review by RussKie — APPROVED** [review]

File: GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:3144]: @RussKie  that would be a link to Git documentation
Documentation is poor, does not statate that the line starts with two chars before branch
So something should be added below (this line is fine).

https://git-scm.com/docs/git-branch#_description

+ is used for linked work trees, similar to *

File: GitCommands/Git/GitModule.cs [hunk 2]
```diff
@@ -3141,12 +3141,12 @@ public IReadOnlyList<string> GetAllBranchesWhichContainGivenCommit(ObjectId obje
...
 
             // Remove symlink targets as in "origin/HEAD -> origin/master"
-            for (var i = 0; i < result.Length; i++)
+            for (int i = 0; i < result.Length; i++)
             {
-                var item = result[i].Trim();
+                string item = Regex.Replace(result[i], @"^[*+ ] ", "");
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs:3149]: This should maybe be trimmed with code instead, or we should increase the static regex cache (15 entries)
I do not request changes though

As discussed above, a comment about the format should be added.

**Review by gerhardol — APPROVED** [review]

File: GitCommands/Git/GitModule.cs (hunk 2 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs]: All good changes

**Review by gerhardol — APPROVED** [review]
