### PR TITLE
Bugfix for #5065 and #5083: hotkeys 'B' and 'H' in RevisionDiff.

### LINKED ISSUE #5065: Typing 'b' or 'h' into the Diff Filter Files text box doesn't insert the character
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Typing either "b" or "h" as a character in the "Diff" "Filter files..." text box causes the "Blame" or "History" windows to appear. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open a repo
1. Select a commit with a parent
1. Go to the "Diff" tab in the bottom panel
1. Place the text entry cursor into the "Filter files..." text box
1. Type "b" or "h"

**What is the expected behavior?**
It should let me type the "b" and "h" as characters in the filter string.

**Environment you encounter the issue:**

- GitExtensions version: master fa860cdfda35d663a90d0a9955a6f95854191ba6
- GIT version: git-for-windows 2.17.1.windows.2
- OS version: Windows 10 (1703)

**Did this work in previous version of GitExtensions (which)?**
No idea, sorry.

### LINKED ISSUE #5083: NRE on 'b' or 'h' in FileStatusList filtered to no items
**Do you want to request a *feature* or report a *bug*?**

Bug.

Relates to #5065.

**What is the current behavior?**

Typing `b` or `h` into the _Diff_ tab's file list when no items exist in the list (due to filtering) causes a NRE 

> Void fileHistoryDiffToolstripMenuItem_Click(System.Object, System.EventArgs) @ GitUI.CommandsDialogs.RevisionDiff

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

image

In the browse form, select a commit, then the diff tab, enter filter text until no files are shown, give the list focus, press 'h' or 'b'.

**What is the expected behavior?**

No exception. Nothing else should happen.

**Environment you encounter the issue:**

- GitExtensions version: master a3695217a2671cafec9043f083e57ec47224f3b1

**Did this work in previous version of GitExtensions (which)?**

Don't know.

### PR DESCRIPTION
**Pull request by mstv**
Fixes #5065, fixes #5083.

Changes proposed in this pull request:
- ignore the hotkey if the DiffFiles.FilterComboBox is focused and the hotkey is a normal character
- ignore the hotkey if no item is selected in DiffFiles
 
Screenshots before and after (if PR changes UI):
N/A

What did I do to test the code and ensure quality:
- manual testing

Has been tested on (remove any that don't apply):
- Windows 7

### CODE REVIEW

File: GitUI/CommandsDialogs/RevisionDiff.cs [hunk 1]
```diff
@@ -99,6 +99,15 @@ public bool ExecuteCommand(Command cmd)
 
         protected override bool ExecuteCommand(int cmd)
         {
+            if (DiffFiles.FilterFocused)
+            {
+                Keys key = GetShortcutKeys(cmd);
+                if ((key >= Keys.A && key <= Keys.Z) || (key >= Keys.D0 && key <= Keys.D9))
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/RevisionDiff.cs]: Should not all keys be accepted in the filter?

File: ResourceManager/GitExtensionsUserControl.cs [hunk 2]
```diff
@@ -127,6 +127,37 @@ protected virtual bool ExecuteCommand(int command)
...
+                case Keys.Right:
+                case Keys.Home:
+                case Keys.End:
+                return true;
+
+                case Keys.Up:
+                case Keys.Down:
+                case Keys.PageUp:
+                case Keys.PageDown:
+                return multiLine;
```
Comment (RussKie) [inline ResourceManager/GitExtensionsUserControl.cs]: [nit] `return` statements mis-indented

**Comment by RussKie** [comment]
Yes, it can be a bit annoying ☺

**Comment by RussKie** [comment]
Thank you
