### PR TITLE
fix(Submodules): Allow spaces in folder name

### LINKED ISSUE #11891: [NBug] An error occurred trying to start process 'C:\Program Files...
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.45.1.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Command: C:\Program Files\Git\bin\git.exe
Arguments: -c diff.ignoreSubmodules=none status -s
Working directory: D:\Code\Unity\borbeli\Assets\Standard Assets\FootballEngine b\Assets\Standard\

```
GitExtensions.Extensibility.ExternalOperationException: An error occurred trying to start process 'C:\Program Files\Git\bin\git.exe' with working directory 'D:\Code\Unity\borbeli\Assets\Standard Assets\FootballEngine b\Assets\Standard\'. The directory name is invalid.
 ---> System.ComponentModel.Win32Exception (267): An error occurred trying to start process 'C:\Program Files\Git\bin\git.exe' with working directory 'D:\Code\Unity\borbeli\Assets\Standard Assets\FootballEngine b\Assets\Standard\'. The directory name is invalid.
   at bool System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at new GitCommands.Executable+ProcessWrapper(string fileName, string prefixArguments, string arguments, string workDir, bool createWindow, bool redirectInput, bool redirectOutput, Encoding outputEncoding, bool useShellExecute, bool throwOnErrorExit, CancellationToken cancellationToken) in C:/projects/gitextensions/src/app/GitCommands/Git/Executable.cs:line 124
   --- End of inner exception stack trace ---
   at new GitCommands.Executable+ProcessWrapper(string fileName, string prefixArguments, string arguments, string workDir, bool createWindow, bool redirectInput, bool redirectOutput, Encoding outputEncoding, bool useShellExecute, bool throwOnErrorExit, CancellationToken cancellationToken) in C:/projects/gitextensions/src/app/GitCommands/Git/Executable.cs:line 140
   at IProcess GitCommands.Executable.Start(ArgumentString arguments, bool createWindow, bool redirectInput, bool redirectOutput, Encoding outputEncoding, bool useShellExecute, bool throwOnErrorExit, CancellationToken cancellationToken) in C:/projects/gitextensions/src/app/GitCommands/Git/Executable.cs:line 46
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/src/app/GitCommands/Git/ExecutableExtensions.cs:line 105
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<T>(Func<Task<T>> asyncMethod, JoinableTaskCreationOptions creationOptions) x 2
   at string GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/src/app/GitCommands/Git/ExecutableExtensions.cs:line 45
   at string GitCommands.GitModule.GetStatusText(bool untracked) in C:/projects/gitextensions/src/app/GitCommands/Git/GitModule.cs:line 2347
   at string ResourceManager.LocalizationHelpers.ProcessSubmoduleStatus(IGitModule module, GitSubmoduleStatus status, bool moduleIsParent, bool limitOutput) in C:/projects/gitextensions/src/app/ResourceManager/LocalizationHelpers.cs:line 265
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, int? line, string defaultText, Action openWithDiffTool, string additionalCommandInfo)+GetSelectedPatchAsync(?) in C:/projects/gitextensions/src/app/GitUI/GitUIExtensions.cs:line 223
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, int? line, string defaultText, Action openWithDiffTool, string additionalCommandInfo) in C:/projects/gitextensions/src/app/GitUI/GitUIExtensions.cs:line 182
   at async void GitUI.TaskManager.InvokeAndForget(Control control, Func<Task> asyncAction, CancellationToken cancellationToken)+(?) => { } [1] in C:/projects/gitextensions/src/app/GitExtUtils/GitUI/TaskManager.cs:line 119
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/src/app/GitExtUtils/GitUI/TaskManager.cs:line 32
```

"borbeli" is folder where my main repo is cloned, and it has submodule in "borbeli/Assets/Standard Assets/FootballEngine/" folder. And there is no folder "borbeli/Assets/Standard Assets/FootballEngine b/" at all. This problem started happening as soon as I updated to Git Extensions v5, and it happens when I open Commit window for main repo while I have local changes in my submodule repo.

### Steps to reproduce

"borbeli" is folder where my main repo is cloned, and it has submodule in "borbeli/Assets/Standard Assets/FootballEngine/" folder. And there is no folder "borbeli/Assets/Standard Assets/FootballEngine b/" at all. This problem started happening as soon as I updated to Git Extensions v5, and it happens when I open Commit window for main repo while I have local changes in my submodule repo.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11891

## Proposed changes

- Fixup `SubmoduleHelpers.DiffCommandRegex` to support spaces in folder names of super repo
- Add test for `CreatePatchFromString` which uses a similar regex (not changed because it has a more generic scope)

## Test methodology 

- extend tests

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

File: src/app/GitCommands/Git/SubmoduleHelpers.cs [hunk 1]
```diff
@@ -7,7 +7,7 @@ namespace GitCommands.Git
 {
     public static partial class SubmoduleHelpers
     {
-        [GeneratedRegex(@"diff --git [^/\s]+/(?<filenamea>.+)\s[^/\s]+/(?<filenameb>.+)", RegexOptions.ExplicitCapture)]
+        [GeneratedRegex(@"diff --git\s+[ab]/(?<filenamea>.+)\s+[ba]/(?<filenameb>.+)", RegexOptions.ExplicitCapture)]
```
Comment (gerhardol) [inline src/app/GitCommands/Git/SubmoduleHelpers.cs:10]: Something like the following can still fail:
diff --git a/path/with a/space/ b/another/path

Comment (mstv) [reply src/app/GitCommands/Git/SubmoduleHelpers.cs:10]: of course
I decided: Who wants to shoot themself in the foot, shall do!
