### PR TITLE
kdiff3: Incorrect merge cmd

### LINKED ISSUE #4364: GitExtensions ignores "Mergetool command" setting for KDiff3
**Do you want to request a *feature* or report a *bug*?**
Hello. I want report about a bug.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Go Menu -> Tools -> Settings -> Git Extensions -> Git Config
2) Set "Mergettol"="KDiff3"
3) Set "Mergetool command"=
"C:/Program Files (x86)/KDiff3/kdiff3.exe" "$BASE" "$REMOTE" "$LOCAL" -m
4) Press OK
5) Start any merge with conflict
6) Select file to resolve conflict in KDiff3

**What is the current behavior?**
KDiff3 displays:
1) BASE as A (in left)
2) **LOCAL** as B (in center)
3) **REMOTE** as C (in right)

**What is the expected behavior?**
KDiff3 displays:
1) BASE as A (in left)
2) **REMOTE** as B (in center)
3) **LOCAL** as C (in right)

If I run KDiff3 in command line with arguments:
kdiff3.exe  BASE_FILE  REMOTE_FILE  LOCAL_FILE  -m
where BASE_FILE, REMOTE_FILE, LOCAL_FILE are paths to files then I see what I wrote in _expected behavior_

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.15.1
- OS version: Windows 7 Pro
- KDiff3 version: 0.9.97

**Did this work in previous version of GitExtensions (which)?**
2.50.01

============================
May be I just write incorrect "Mergetool command"?

### LINKED ISSUE #7544: Regression: Conflicts no longer open properly in kdiff3
## Current behaviour

After clicking "Merge" in the Resolve merge conflicts window, kdiff3 opens with no files selected.

## Expected behaviour

kdiff3 opens with the base, local, and remote versions of the conflicted file.

## Steps to reproduce

Start with GitExtensions v3.2 installed; upgrade to v3.3 using the built-in upgrade functionality; try to perform a merge between branches which have conflicts. Choose to resolve conflicts; select a conflicted file in the Resolve merge conflicts window; then click Merge.

I have not evaluated whether this applies when GitExtensions v3.3 is installed from scratch, as either way this is a bug. However, I have reverted to v3.2, observed this working properly, then upgraded again and observed the same problem.

## Screenshots

kdiff3 window opened by GitExtensions v3.3
image

## Did this work in previous version of GitExtensions

Yes, in v3.2.

## Environment

- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3460.0
- DPI 192dpi (200% scaling)

## Diagnostics

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #7544

## Proposed changes

Correct the default arguments for kdiff3 merge tool
http://kdiff3.sourceforge.net/doc/documentation.html

kdiff3 merge commands were not set in settings.
When pressing mergetool, the Git defaults were used 
When pressing "open kdiff3", the arguments were hardcoded in FormResolveConflicts (that happened to be the same as for Git)

## Test methodology 

Manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/DiffMergeTools/Kdiff3.cs [hunk 1]
```diff
@@ -7,6 +7,9 @@ internal class Kdiff3 : DiffMergeTool
         /// <inheritdoc />
         public override string ExeFileName => "kdiff3.exe";
 
+        /// <inheritdoc />
+        public override string MergeCommand =>  \"$BASE\" \"$REMOTE\" "\"$LOCAL\" -o \"$MERGED\"";
```
Comment (mstv) [inline GitCommands/DiffMergeTools/Kdiff3.cs]:
```suggestion
        public override string MergeCommand =>  "\"$BASE\" \"$REMOTE\" \"$LOCAL\" -o \"$MERGED\"";
```

Comment (gerhardol) [reply GitCommands/DiffMergeTools/Kdiff3.cs]: Are you suggesting the PR should have correct syntax?
I have a fever and my brain is only partially working...

Comment (mstv) [reply GitCommands/DiffMergeTools/Kdiff3.cs]: Yes, as you already have force-pushed.
Beterschap!

**Comment by gerhardol** [comment]
@msftbot merge in 1 day
