### PR TITLE
Detect and display Git warning on broken refs

### LINKED ISSUE #6442: ArgumentException on startup
## Current behaviour

Start GE, opens the last repo (GE) automatically --> AE "duplicate key in dictionary".

## Expected behaviour

no crash

## Screenshots

exception

## Did this work in previous version of GitExtensions

yes

## Environment

- Git Extensions 3.1.0
- Build 259c501a27db6de9723fbcddbdd40638a9498f24
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

## Diagnostics

```
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at GitUI.CommitInfo.CommitInfo.<LoadSortedRefsAsync>g__ToDictionary|53_0(IReadOnlyList`1 list) in F:\Build\gitextensions\GitUI\CommitInfo\CommitInfo.cs:line 218
   at GitUI.CommitInfo.CommitInfo.<LoadSortedRefsAsync>d__53.MoveNext() in F:\Build\gitextensions\GitUI\CommitInfo\CommitInfo.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommitInfo.CommitInfo.<<RefreshSortedRefs>b__47_0>d.MoveNext() in F:\Build\gitextensions\GitUI\CommitInfo\CommitInfo.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext() in F:\Build\gitextensions\GitExtUtils\GitUI\ThreadHelper.cs:line 101
```

### PR DESCRIPTION
**Pull request by mstv**
Fixes #6442.

## Proposed changes

- detect the Git warning returned by the command "for-each-ref" (although the exit code is 0)
- cancel loading refs
- display the warning

### Before

exception

### After

warning

## Test methodology 

- manually

## Test environment(s) 

- Git Extensions 3.1.0
- Build 400b68461b38c7d51a9bee8b1d15bd751bb97a87
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -757,7 +765,12 @@ public IReadOnlyList<string> GetSortedRefs()
                 "refs/"
             };
 
-            var tree = _gitExecutable.GetOutput(args);
+            string tree = _gitExecutable.GetOutput(args);
+            int warningPos = tree.IndexOf("warning:");
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs]: is this ever localized? Anyone that has checked Git source for this?

File: GitCommands/Git/GitModule.cs [hunk 2]
```diff
@@ -747,6 +747,14 @@ public async Task<List<ConflictData>> GetConflictsAsync(string filename = "")
             return list;
         }
 
+        public class RefsWarningException : Exception
+        {
+            public RefsWarningException(string message)
+            : base(message)
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs]: Mis indented
```suggestion
                : base(message)
```

File: GitCommands/Git/GitModule.cs [hunk 3]
```diff
@@ -747,6 +747,14 @@ public async Task<List<ConflictData>> GetConflictsAsync(string filename = "")
             return list;
         }
 
+        public class RefsWarningException : Exception
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs]: Please move it out to own file (similar to `FileDeleteException`)

File: GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (RussKie) [reply GitCommands/Git/GitModule.cs]: We use the same literal in at least one other place in the code, so I presume it is safe to use.
However it won't hurt to check

File: GitUI/CommitInfo/CommitInfo.cs [hunk 4]
```diff
@@ -206,11 +206,22 @@ private async Task LoadSortedRefsAsync()
...
+                var refsOrderDict = ToDictionary(Module.GetSortedRefs());
+
+                await this.SwitchToMainThreadAsync();
+                _refsOrderDict = refsOrderDict;
+                UpdateRevisionInfo();
+            }
+            catch (GitModule.RefsWarningException ex)
+            {
+                await this.SwitchToMainThreadAsync();
+                MessageBox.Show(this, new TranslationString("The repository refs seem to be broken:").Text + Environment.NewLine + Environment.NewLine + ex.Message,
```
Comment (RussKie) [inline GitUI/CommitInfo/CommitInfo.cs]: ⚠️ Please move the translation string to the top with the rest of definitions.
Also please don't use `+` to concat strings, at least use string interpolation.

Comment (mstv) [reply GitUI/CommitInfo/CommitInfo.cs]: Adding static TranslationStrings for this message and title that will be displayed hardly ever is heavy-handed in my opinion.

**Comment by RussKie** [comment]
it is a matter of consistency

File: GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (mstv) [reply GitCommands/Git/GitModule.cs]: "ignoring broken ref %s" is localized but not "warning: ":
```c
static void warn_builtin(const char *warn, va_list params)
{
	vreportf("warning: ", warn, params);
}
```

**Comment by mstv** [comment]
Applied the requested changes and prepared an exception hierarchy
Exception <- GitException <- RepoException <- RefsWarningException

File: GitCommands/Git/GitExceptions.cs [hunk 5]
```diff
@@ -0,0 +1,43 @@
+using System;
+
+namespace GitCommands.Git
+{
+    public class GitException : Exception
```
Comment (RussKie) [inline GitCommands/Git/GitExceptions.cs]: One class per file please

**Comment by RussKie** [comment]
> prepared an exception hierarchy
> Exception <- GitException <- RepoException <- RefsWarningException

We have only 2 custom exceptions (that I am aware of) at the moment `FileDeleteException` and `RefsWarningException`, a hierarchy is an overkill.
Let's not introduce it until we have significantly more exceptions.

**Comment by mstv** [comment]
Specific exceptions should be part of a well designed contract, not only interfaces.
These exceptions should be used when splitting up GitModule.
I'm afraid there are more Git commands whose errors and warnings have not been handled correctly yet.

**Comment by RussKie** [comment]
Totally agree, but it should be a separate piece of work.

File: GitCommands/Git/GitModule.cs [hunk 6]
```diff
@@ -757,7 +757,12 @@ public IReadOnlyList<string> GetSortedRefs()
                 "refs/"
             };
 
-            var tree = _gitExecutable.GetOutput(args);
+            string tree = _gitExecutable.GetOutput(args);
+            int warningPos = tree.IndexOf("warning:");
+            if (warningPos >= 0)
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs]: Should the check for "warning" start on the first position i.e. "== 0"?

Comment (mstv) [reply GitCommands/Git/GitModule.cs]: No, that won't work because the output is sorted which makes the warnings appearing last.

Comment (mstv) [reply GitCommands/Git/GitModule.cs]: It should be safe: The colon is no valid character for refs. Isn't it?

**Comment by mstv** [comment]
Removed RepoException.

**Comment by mstv** [comment]
Build failed due to unavailable test runner.

File: GitCommands/Git/GitModule.cs (hunk 6 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs]: Correct

**Comment by RussKie** [comment]
@mstv could you please add tests for your change.
You can see how to mock `IExecutable` in `AheadBehindDataProviderTests`

**Comment by mstv** [comment]
Thank you for the jigsaw piece, @RussKie. I did not realize before that GitModule works with such little mocking.
