### PR TITLE
Fix git command for unmerged obsolete branches

### LINKED ISSUE #9293: Delete obsolete branches: 'Include unmerged branches' not working
## Current behaviour

When I check the 'Include unmerged branches' and then press 'Search branches':

- Case 1: If the reference branch has any value, the grid is empty.
- Case 2: If the reference branch has no value, the grid contains all branches that meet the criteria (which is OK)

## Expected behaviour

When I check the 'Include unmerged branches' and then press 'Search branches', the grid should contain all branches that meet the criteria, irrespective of their merge status relative to the reference branch (the 'Delete branches fully merged' textbox)

## Steps to reproduce

1. Have a repository with (at least) 3 branches. You could do it with just 2 branches if you make sure thate the 'Delete branches fully merged into branch' contains the name of your current branch.
2. Go to Plugins/Delete obsolete branches menu
3. Set 'Delete branches older than x days' to 0
4. Uncheck all options
5. Set 'Delete branches fully merged into branch' to any valid branch name
6. Check 'Include unmerged branches'
7. Press 'Search branches'

The grid should have at least one row for a branch that is neither the current one nor the reference one.

## Screenshots

2021-06-17 21_58_25-Git Command Log

It seems that when the 'Include unmerged branches' is selected, the reference branch name is still passed to Git. In this case git inteprets it as the 'pattern' argument because there is neither a '--merged' nor '--no-merged' argument. So it returns only the reference branch, which is later filtered by the plugin code, leading to an empty grid.

2021-06-17 22_40_42-Delete obsolete branches

## Did this work in previous version of GitExtensions

Not that I know.

## Environment

- GitExtensions version: 3.4.3.9999 and commit 8587c71 in branch 'release/3.5'
- GIT version: 2.29.2
- OS version: Win 10.0.19043.0
- .NET version: 4.8.4360

## Possible solution

Don't pass the reference branch to git when 'Include unmerged branches', so that it returns all existing branches to the plugin code for it to apply its filters.

### PR DESCRIPTION
**Pull request by matthiaslischka**
Fixes #9293

In the "delete obsolete branches" plugin, when including unmerged branches, the list of branches was always empty.

## Proposed changes

Git command for listing of branches must not contain reference branch when including unmerged.
The command executed when including unmerged was `git branch --list HEAD` and had no results.
With this change it is now `git branch --list` for including unmerged branches and `git branch --list --merged HEAD` for only including branches merged into `HEAD`

## Test environment(s) 

- GIT git version 2.39.0.windows.1
- Windows 10 Pro 22H2

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]
Looks sensible. Haven't tested.

**Comment by RussKie** [comment]
@darkcamper @hieuxlu please confirm the fix.
 https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45996739/artifacts

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs [hunk 1]
```diff
@@ -126,8 +126,7 @@ private IEnumerable<string> GetObsoleteBranchNames(RefreshContext context, strin
             {
                  "--list",
                  { context.IncludeRemotes, "-r" },
-                 { !context.IncludeUnmerged, "--merged" },
-                 context.ReferenceBranch
+                 { !context.IncludeUnmerged, "--merged " + context.ReferenceBranch }
```
Comment (mstv) [inline Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs:129]:
```suggestion
                 { !context.IncludeUnmerged, $"--merged {context.ReferenceBranch}" }
```

**Review by mstv — COMMENTED** [review]
Looks sensible, have not run.
