### PR TITLE
Use native methods instead of recursion for resolving correct path casing

### LINKED ISSUE #5963: Improve performance of TryGetExactPath; used to fix wrong casing in recent repositories.
**Do you want to request a *feature* or report a *bug*?**
🐛 
As requested by @drewnoakes in pr #5887, this issue is about improving the method (or usage of) TryGetExactPath. It currently causes performance issues and it is now disabled. The method is left in the code to be fixed in this issue.

**What is the current behavior?**
- Loading GE is slow, due to path casing fixes in TryGetExactPath

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- I cannot simulate the issue itself. Example issue: #5954

**What is the expected behavior?**
- It should be lightning fast

**Environment you encounter the issue:**
- See #5954
- I cannot simulate

### PR DESCRIPTION
**Pull request by spdr870**
Fixes #5963

## Proposed changes
- Use native methods (from FileHistory code) to find proper casing for path.
- The method is not used for recentrepositories. This PR only merges the 2 existing methods for resolving path casing.

## Test methodology

- Unit tests
- No manual testing done

## Test environment(s)

- Git Extensions 3.00.00.4429
- Build c15bad2784fbfc0261427b371fda07348acc52c5
- Git 2.19.2.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3221.0
- DPI 120dpi (125% scaling)

### CODE REVIEW

File: GitUI/Native.cs [hunk 1]
```diff
@@ -93,12 +93,6 @@ internal struct COLORREF
         internal static extern bool ShowCaretAPI(
             IntPtr hwnd);
 
-        [DllImport("kernel32.dll", CharSet = CharSet.Auto, SetLastError = true)]
```
Comment (gerhardol) [inline GitUI/Native.cs]: Why change this? 
There is at least a hope that GE can be multi platform again

**Comment by RussKie** [comment]
Pushed my refactor in.

The main reasons:
* I'd like to keep all OS-specific interops at the UI layer, `GitCommands` assembly should be x-plat and OS agnostic.
* `FormFileHistory` is the only one using `TryGetExactPath` method so I moved the method closer to the call site.
* To facilitate testability and separate UI and logic I added a controller class, which should deal with non-UI concerns.

**Comment by RussKie** [comment]
There is likely more clean up for us to do, but I don't think we should
create more work for us.

File: GitUI/CommandsDialogs/FormFileHistoryController.cs [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+        /// <param name="exactPath">The full path using the correct case if the path exists.  Otherwise, null.</param>
+        /// <returns>True if the exact path was found.  False otherwise.</returns>
+        /// <remarks>
+        /// This supports drive-lettered paths and UNC paths, but a UNC root
+        /// will be returned in lowercase (e.g., \\server\share).
+        /// </remarks>
+        [ContractAnnotation("=>false,exactPath:null")]
+        [ContractAnnotation("=>true,exactPath:notnull")]
+        [ContractAnnotation("path:null=>false,exactPath:null")]
+        public bool TryGetExactPath(string path, out string exactPath)
```
Comment (drewnoakes) [inline GitUI/CommandsDialogs/FormFileHistoryController.cs]: I don't think this method belongs on a class called `FormFileHistoryController`. Can we move it to [`PathUtil`](https://github.com/gitextensions/gitextensions/blob/master/GitCommands/PathUtil.cs)?

Comment (RussKie) [reply GitUI/CommandsDialogs/FormFileHistoryController.cs]: > I don't think this method belongs on a class called `FormFileHistoryController`.

Given that the form is the only one consumer of the method the controller is kind of logical place for it. At the same time I share your sentiment (to a degree).

> Can we move it to [`PathUtil`](https://github.com/gitextensions/gitextensions/blob/master/GitCommands/PathUtil.cs)?

I'm not sure how... This feels like a chicken and an egg problem - for GitCommands project to stay OS-agnostic it shouldn't have this method.

Suggestions?

Comment (RussKie) [reply GitUI/CommandsDialogs/FormFileHistoryController.cs]: I suppose we can do what Xamarin always suggested - have platform-specific projects that have OS-specific dependencies and provide implementations in OS-specific way.
This way our code won't be peppered with `if (Windows) { ... } else if (Linux) { ... }`

Comment (RussKie) [reply GitUI/CommandsDialogs/FormFileHistoryController.cs]: Merging as is, we can revisit this in the future.
