### PR TITLE
Split the reordering and rebuilding of the graph.

### LINKED ISSUE #5658: RevisionGrid: Quick search is broken
**Do you want to request a *feature* or report a *bug*?**
bug, regression

**What is the current behavior?**
quick search doesn't find commits anymore

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1.
  - check out master and select b7960d7
  - type `b` `c`
  - "bc" is displayed and the non-matching commit e4cd7e9 is selected

2.
  - select a newer commit from a different branch 
  - type `b` `c`
  - "bc" is displayed but the selection doesn't change

**What is the expected behavior?**
quick search finds the first matching commit seaching top down

**Environment you encounter the issue:**

- Git Extensions 3.00.a1
- b7960d79e0f1342064a18546108d21297398df64 
- Git 2.18.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0

**Did this work in previous version of GitExtensions (which)?**
yes, earlier master and 2.5

### PR DESCRIPTION
**Pull request by spdr870**
Rebuilding the graph is expensive, and is usually not needed. Minor fix. I did not refactor the cache to minimize impact of this PR.

Fixes #5658

Changes proposed in this pull request:
- Split the reordering and rebuilding of the graph. (reordering is fast, rebuilding is slow)
- Because the graph rows are rebuild less often, this results in better performance while the revisions are still being loaded. There was some flickering I wanted to solve.
 
What did I do to test the code and ensure quality:
- Manual testing

Has been tested on (remove any that don't apply):
- GIT 2.19
- Windows 10

### CODE REVIEW

File: GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs [hunk 1]
```diff
@@ -17,12 +17,15 @@ public class RevisionGraph
...
+        // The nodecache is an ordered list with the nodes. This is used to be able to draw commits before the graph is completed.
         private List<RevisionGraphRevision> _orderedNodesCache = null;
+        private bool _reorder = true;
+        private int _orderedUntillScore = -1;
+
+        // The orderedrowcache contains the rows with the segments stored in lanes.
         private List<RevisionGraphRow> _orderedRowCache = null;
-        private int _cachedUntillScore = -1;
+        private bool _rebuild = true;
+        private int _buildUntillScore = -1;
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs]: [nit] typo - `until`

Comment (spdr870) [reply GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs]: Fixed

**Comment by RussKie** [comment]
I got a notification that you've merged https://github.com/spdr870/gitextensions/pull/2 into this branch, yet I don't see the changes here.
You haven't accidentally overwritten them, have you?

**Comment by spdr870** [comment]
I did merge it by accident. So pushed it out again. I didn't notice the pr yet. I will merge it. Nice to see you working on the graph code. Is it becoming more clear how it works?

**Comment by RussKie** [comment]
I'm more exploring at the moment, trying to get a good mental picture of how it all hangs together. Given that I am constantly switching contexts I haven't made any serious progress (which is disappointing). 
I'm trying these little refactors in attempt to make the code more modular, easier to test and understand.

**Comment by RussKie** [comment]
Do you think we can squash this PR?

**Comment by spdr870** [comment]
Rebased an squashed. Better?
