### PR TITLE
Do not cache current GetRevision data

### LINKED ISSUE #10223: cBranch and cLocalBranch are empty, cHash has wrong value
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4515.0

### Issue description

I use the `cBranch` variable in my GitExt Scripts and it worked fine in version 3.4.3.
After upgrading to 3.5.4 the variable is always empty :(
I tryed `cLocalBranch` then, but it is also empty.
I then tryed `cHash` but it strangely returns a hash of some other commit.

### Steps to reproduce

Create a Script that echos cBranch, cLocalBranch or cHash

### Did this work in previous version of GitExtensions?

3.4.3.9999

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10223

## Proposed changes

- Do not cache the git output if querying the current checkout, i.e. let `GetRevision` use the cache only if an `ObjectId` is specified

## Screenshots 

N/A

## Test methodology 

- manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build 22636a7d67522cb59de51fd9e38ec9145eeeeb30
- Git 2.35.2.windows.1 (recommended: 2.37.1 or later)
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.9
- DPI 96dpi (no scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — APPROVED** [review]

File: GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -970,7 +970,7 @@ public GitRevision GetRevision(ObjectId? objectId = null, bool shortFormat = fal
                 objectId
             };
 
-            var revInfo = _gitExecutable.GetOutput(args, cache: GitCommandCache, outputEncoding: LosslessEncoding);
+            var revInfo = _gitExecutable.GetOutput(args, cache: objectId is null ? null : GitCommandCache, outputEncoding: LosslessEncoding);
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs:973]: A comment here would be helpful for any future references.

Comment (mstv) [reply GitCommands/Git/GitModule.cs]: comment and variable added

File: GitCommands/Git/GitModule.cs [hunk 2]
```diff
@@ -970,7 +970,10 @@ public GitRevision GetRevision(ObjectId? objectId = null, bool shortFormat = fal
                 objectId
             };
 
-            var revInfo = _gitExecutable.GetOutput(args, cache: GitCommandCache, outputEncoding: LosslessEncoding);
+            // cache output only if revision is specified
+            CommandCache? cache = objectId is null ? null : GitCommandCache;
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs:974]: Related: Cache would not be valid if called with an artificial commit, but the command will then fail anyway, so no check needed here...
Do not suggest a check in the method

**Review by gerhardol — APPROVED** [review]
