### PR TITLE
Git config

### LINKED ISSUE #4389: GitExtensions rewrites .gitconfig
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
GitExtensions destroys carefully-crafted .gitconfig files by rewriting all settings lines (w/o comments).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use a .gitconfig file with, eg, a comment explaining a setting.
Install and start GitExtensions, open a repo, close GitExtensions.
The comment line in .gitconfig is gone.

**What is the expected behavior?**
GitExtensions adds or changes settings only upon explicit request by the user, leaving the rest of the file alone.  The command line 'git config' seems to get this right.

**Environment you encounter the issue:**
- GitExtensions version: 2.50.02
- GIT version: 2.16.0.windows.2
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Never worked.  My primary reason to not use or recommend GitExtensions.

### PR DESCRIPTION
**Pull request by mstv**
Fixes #4389

## Proposed changes

- Remove `IConfigFileSettings` including its implementation so that GE does not rewrite git config files any longer
- Instead, use "git config" commands (with caching) for reading and writing git config settings
  using `IGitModule`:
  - `GetEffectiveSetting`
  - `GetEffectiveSetting<T>`
  - `GetSettings(string setting)` (for multi-value settings, kept existing sub-optimal name)
  - `SetSetting`
  - `UnsetSetting`
- Provide new API in `IGitModule`:
  - `GetAllLocalSettings`
  - `InvalidateGitSettings`
  - `RemoveConfigSection`
- Remove API:
  - from `IGitModule`:
    - `GetSetting` (kept, but declared "deprecated", redirected to `GetEffectiveSetting`)
    - `GetSetting<T>` (unused)
    - `GetGitSetting`
    - `GetEffectiveGitSetting`
    - `EffectiveConfigFile`
    - `LocalConfigFile`
  - from`IGitRef`
    - `GetTrackingRemote` & `GetMergeWith` (redundant to existing properties)

(Review commit by commit is recommended.)

## Screenshots 

N/A

## Test methodology 

- existing tests (with adaptations)
- tested with WSL

## Please do not squash merge

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -4131,9 +4124,20 @@ string GetDateParameter(string param, DateTime? date)
...
+            if (settingLevel == GitSettingLevel.Local)
+            {
+                LocalGitConfigSettings.Invalidate();
+            }
+        }
+
+        public TestAccessor GetTestAccessor() => new(this);
 
-        internal readonly struct TestAccessor
+        public readonly struct TestAccessor
```
Comment (RussKie) [inline src/app/GitCommands/Git/GitModule.cs:4140]: Why?

**Review by RussKie — COMMENTED** [review]
Not a deep review, but I think this is a good change.
How good is the test coverage?

File: src/app/GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (mstv) [reply src/app/GitCommands/Git/GitModule.cs:4140]: because otherwise, `CommonTestUtils.GitModuleTestHelper` cannot access it

---

Test coverage is high IMO. This PR is "just" a refactoring. There are many tests, particularly for the most affected functionality "management of remotes".

Comment (RussKie) [reply src/app/GitCommands/Git/GitModule.cs:4140]: > because otherwise, `CommonTestUtils.GitModuleTestHelper` cannot access it

Is it IVT'ed to CommonTestUtils?

**Review by RussKie — APPROVED** [review]

**Comment by vbjay** [comment]
More a point of concern to keep an eye out for is your (with caching) point. 

Maybe a test could be added 
1. Generate random number
1 git config test.number number here 
1. Read test.number
1. Confirm got expected value 
1. New number and save to config
1. Read one more time and confirm not cached value. 

My concern is the cache may hold onto values that have been changed and annoy people. I love the use of git config. Maybe a watcher on the git config files to invalidate the cache may be needed.

**Comment by vbjay** [comment]
Makes sense. Then maybe a force refresh config button to handle the case of config being altered outside of app.

**Comment by mstv** [comment]
> Then maybe a force refresh config button to handle the case of config being altered outside of app.

Just hit the `Windows` key twice (in order to trigger `OnApplicationActivated`) if one really changed git config without GE but not leaving GE.

**Comment by vbjay** [comment]
I'm thinking more along the lines of say Visual Studio changes a config or whatnot.  The app calls on git config to get needed settings often and if stale and used cache it will be out of sync. I'd imagine it would be a pain to load settings page to force invalidating cache. If cache had a clock on it that self invalidates after 10 minutes then ok. I'm just saying the cache invalidation needs to be considered.
