### PR TITLE
Fix #5605 Statistics plugin line stats broken

### LINKED ISSUE #5605: Statistics plugin Broken
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
image

image

image

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open statistics plugin and look at tabs.
**Settings**
*.c;*.cpp;*.cc;*.h;*.hpp;*.inl;*.idl;*.asm;*.inc;*.cs;*.xsd;*.wsdl;*.xml;*.htm;*.html;*.css;*.vbs;*.vb;*.sql;*.aspx;*.asp;*.php;*.nav;*.pas;*.py;*.rb;*.js

\Debug;\Release;\obj;\bin;\lib

**What is the expected behavior?**
Showing actual stats.
**Environment you encounter the issue:**

- GitExtensions version: Master : 8f739f0054e5b87da70d5753251f3de00242803d
- GIT version: 2.19.1
- OS version: Win 10
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**

### PR DESCRIPTION
**Pull request by vbjay**
Running 'git ls-tree -z -r ' fails to return anything

Fixes #5605 

Changes proposed in this pull request:
- Pass in ObjectID that represents head
Screenshots before and after (if PR changes UI):

What did I do to test the code and ensure quality:
Ran program and looked at line tabs
Has been tested on (remove any that don't apply):
- GIT 2.19.1 and above

### CODE REVIEW

File: Plugins/GitUIPluginInterfaces/IGitModule.cs [hunk 1]
```diff
@@ -29,6 +29,14 @@ public interface IGitModule
         /// <param name="remoteName">The current remote name.</param>
         /// <param name="newName">The new remote name.</param>
         string RenameRemote(string remoteName, string newName);
+
+        /// <summary>
+        /// Parses the revisionExpression as a git reference and returns an <see cref="ObjectId"/>./>
+        /// </summary>
+        /// <param name="revisionExpression">An expression like HEAD or commit hash that can be parsed as a git reference.</param>
```
Comment (gerhardol) [inline Plugins/GitUIPluginInterfaces/IGitModule.cs]: Git names this as commit-ish. https://git-scm.com/docs/gitglossary#gitglossary-aiddefcommit-ishacommit-ishalsocommittish

I suggest the following:
A Git commit (commit-ish: object name hash or expression like HEAD)

**Comment by vbjay** [comment]
Sure.

File: Plugins/GitUIPluginInterfaces/IGitModule.cs [hunk 2]
```diff
@@ -29,6 +29,14 @@ public interface IGitModule
...
+        /// <returns>An ObjectID representing that git reference</returns>
+        ObjectId RevParse(string revisionExpression);
```
Comment (drewnoakes) [inline Plugins/GitUIPluginInterfaces/IGitModule.cs]: Move `[CanBeNull]` from implementation to interface.

https://github.com/gitextensions/gitextensions/blob/de336b7f62c78725c198274de62267590b4b8694/GitCommands/Git/GitModule.cs#L3560-L3574

If you change the name of the param as per @gerhardol's comment, update it in both places.

File: Plugins/Statistics/GitStatistics/FormGitStatistics.cs [hunk 3]
```diff
@@ -190,7 +190,7 @@ public void LoadLinesOfCode()
             void LoadLinesOfCodeForModule(IGitModule module)
             {
                 var filesToCheck = module
-                    .GetTree(null, full: true)
+                    .GetTree(module.RevParse("HEAD"), full: true)
```
Comment (drewnoakes) [inline Plugins/Statistics/GitStatistics/FormGitStatistics.cs]: If `GetTree` never returns anything for `null`, perhaps it should throw.

Or, `null` means `HEAD` and you move the `RevParse` call inside `GetTree`. I'm guessing this is what used to happen before the regression.

File: Plugins/GitUIPluginInterfaces/IGitModule.cs (hunk 2 above)
Comment (vbjay) [reply Plugins/GitUIPluginInterfaces/IGitModule.cs]: Ok.

File: Plugins/Statistics/GitStatistics/FormGitStatistics.cs (hunk 3 above)
Comment (vbjay) [reply Plugins/Statistics/GitStatistics/FormGitStatistics.cs]: I think it should just not return a result.  I did it this way for a few reasons:

- It's clear what ObjectID we are sending in.
- Plugins SHOULD be able to call revparse.  

I disagree and did it with readability in mind and adding the revparse as a feature for any use of IGitModule.

Comment (vbjay) [reply Plugins/Statistics/GitStatistics/FormGitStatistics.cs]:
```bash
git ls-tree -z -r
git ls-tree -z
```
both return usage.  The commit is required.

null objectid should be reserved for invalid and not represent a valid objectid.

Comment (vbjay) [reply Plugins/Statistics/GitStatistics/FormGitStatistics.cs]: No.  Before it was "head"  It was changed it to null when it was switched to objectid but null was never figured out to what it was.  I noticed I couldn't use module.revparse from the interface and thought that was a a missing feature.

Comment (gerhardol) [reply Plugins/Statistics/GitStatistics/FormGitStatistics.cs]: Supporting, both as to avoid null as implicit and to extend rev-parse for plugins

Comment (vbjay) [reply Plugins/Statistics/GitStatistics/FormGitStatistics.cs]: Because.  It is not an exception.  It is an empty result.  If the parse of head say on a fresh repo with no commits it would be a valid empty set.  

image

Comment (vbjay) [reply Plugins/Statistics/GitStatistics/FormGitStatistics.cs]: WELL that's a bug.  The commit tab should be empty after creating a new repo and opening that repo.

Comment (vbjay) [reply Plugins/Statistics/GitStatistics/FormGitStatistics.cs]: Of course that is beta 1.  Not sure if master has the same issue.

Comment (RussKie) [reply Plugins/Statistics/GitStatistics/FormGitStatistics.cs]: I think that it is a bug. Please file an issue for it.

Comment (vbjay) [reply Plugins/Statistics/GitStatistics/FormGitStatistics.cs]: Sure. I am as going to check master to see if it is still a bug. I'll file one if it is.

**Comment by vbjay** [comment]
Rebased.

**Comment by RussKie** [comment]
Drew, are you ok with this?

**Comment by drewnoakes** [comment]
Yes it looks like it fixes the bug. I still don't understand why we wouldn't want a null arg to raise an exception, but it't not a big issue.

**Comment by vbjay** [comment]
I explained it. Think rev-parse gets a null ObiectID for new repo. The result of calling ls-tree with no commit ref returns ussage. Run it in console. See how it returns usage. We read it as an empty set which is completely valid. It is not an exception.
