### PR TITLE
Handle start with dashboard explicitly

### LINKED ISSUE #4860: Open GE from GE context menu opens empty Browse
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Open GE for a submodule from GE will not open the submodule repo.
Open can be done by double clicking in Tree window or menu in Diff (it is a bug that double clicking opens File History when double clicking in Diff though).

image
image

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
image

**Environment you encounter the issue:**

- GitExtensions version: master, maybe #3693 was the cause
- GIT version: n/a
- OS version: win10

**Did this work in previous version of GitExtensions (which)?**
all before some week(s) ago

### PR DESCRIPTION
**Pull request by gerhardol**
This is an update of #4870 See that PR for original motivation and why this is opened as a separate PR.
Fixes #4860 

The first commit tried to always resolve the current working directory when starting GE.
That broke the Dashboard handling, that was set to start if there were no directory supplied and GE was configured to not use last used repo. The dashboard must be explicitly handled for the change to work.

What did I do to test the code and ensure quality:
- Manual tests

Has been tested on (remove any that don't apply):
- Windows 10

### CODE REVIEW

**Comment by gerhardol** [comment]
@drewnoakes Please review/comment if you have the possibility

**Comment by gerhardol** [comment]
I will change this PR to only include the "dashboard start" changes, basically the first commit to have a clearer PR history. (So reviews of this PR will still apply to this PR and #4870).

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -542,38 +545,41 @@ private void InternalInitialize(bool hard)
...
                 else
                 {
+                    // Consume the startup arguments, no specific directory was requested
+                    _startWithDashboard = false;
                     ShowDashboard();
                 }
 
+                bool bareRepository = Module.IsBareRepository();
+                bool isDashboard = _dashboard != null && _dashboard.Visible;
+                bool validBrowseDir = Module.IsValidGitWorkingDir() && !isDashboard;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs]: I would invert it, checking for `!isDashboard` is faster than executing the function

Comment (gerhardol) [reply GitUI/CommandsDialogs/FormBrowse.cs]: !isDashboard is almost always true (if we start with dashboard it is false once).
IsValidGitWorkingDir() is almost always true too.
So no performance change that we care about.
Can change.

**Comment by drewnoakes** [comment]
Changes look good to me, in the browser at least. Thanks for picking this one up @gerhardol. I was completely offline for a few weeks and am pretty busy at the moment. I'll devote time to GE as soon as possible.

**Comment by gerhardol** [comment]
Separated the dashboard start changes. I will merge this PR, then #4860
