### PR TITLE
Follow file names in merge commits and all refs

### LINKED ISSUE #10970: File history not working due to double-quoting
### Environment

- Git Extensions 33.33.33
- Build 58078a2fcc4a24758f9b56bcc4f311738ece0e7f
- Git 2.40.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

The File History command launched from `RevisionDiffControl` or `RevisionFileTreeControl` does not show details of many revisions (though for some of them, it does). I think it is due to double-quoting of the file name. This has been fixed in some places (see #10546) but not in `GitUICommands.StartFileHistoryDialog` where the File History dialog is launched from.
Curiously, for some revisions it works. Namely, it's for those for which `FormFileHistory.GetFileNameForRevision` returns a non-null value, though I don't know what are the necessary conditions for this to happen.

### Steps to reproduce

0. Configure _Full history_ in Advanced filter (or FormFileHistory).
1. In the GE repository, select revision 43c1e19d8272818afb5dc02a78af27c824a8c033
2. In the diff control, double click on the (only) file `README.md`
3. File History dialog opens
4. Activate the View tab
5. Select commit ca5a2f841b50eef85ba4523d700f16c6b72a24c5 (_Merge tag 'v4.0.1'_) or 87a1459fafc5343a6fd59069afc9f42ad8f91e2c (_Merge remote-tracking branch 'upstream/release/4.0' into release/3.5.4_)
6. The View tab shows a message _Cannot get treeId from Git for "README.md" for commit &lt;hash&gt;_
7. Select commit 9f9ce47d3c88d2d3d5589fdc5e01e85e679aa698 (_Update Transifex image_)
8. The file contents is now properly displayed

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by crypto-rsa**
Fixes #10970.

## Proposed changes

- Added `-m` and `--all` options to `git log` operation in the `BuildPathFilter` method in order to get the file name for all displayed commits in the File History dialog

## Test methodology 

- Manual (tested the FH dialog in various repositories - the Diff and View tabs show correct content in all commits)

## Test environment(s) 

- GIT  2.42.0.windows.2
- Windows 10

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
What is the impact on performance?

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 1]
```diff
@@ -1164,6 +1164,8 @@ string BuildPathFilter(string? path)
                     $"--format=\"{startOfObjectId}%H\"",
                     "--name-only",
                     "--follow",
+                    "--all",
+                    "-m",
```
Comment (gerhardol) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1168]: Probably need `--diff-merges=separate` too, if the user do not use default config
https://git-scm.com/docs/git-log#Documentation/git-log.txt--m

**Comment by crypto-rsa** [comment]
> What is the impact on performance?

Good point. I tried showing the history of `GitUI\UserControls\RevisionGrid\RevisionGridControl.cs` which I think is one the most heavily edited file in this repo. The dialog shows over 2200 revisions, many of them merges. On `master` the `git log` command takes about 350 ms, in this branch about 700. In relative terms, it sounds quite bad (100% slowdown) but in absolute terms it's 200-300 ms and for the majority of files the difference would be a lot smaller. Is that acceptable or not?

**Comment by gerhardol** [comment]
> Is that acceptable or not?

350 ms is maybe annoying (this will block before anything happens), but probably OK. Detect rename is configurable.
Filtering is a specific use case, ot affecting everything.

How is it in for instance Linux repo?
(No good example of file to use.)

**Comment by gerhardol** [comment]
I get worse numbers
A third configuration may be too much

Opinions, use this anyway?

$ time git log --format=%H  --name-only --follow --all --diff-merges=separate HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > t.t

real    0m15,552s
user    0m0,000s
sys     0m0,000s

$ wc t.t
  3495   8904 118956 t.t

$ time git log --format=%H  --name-only --follow HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > t.t

real    0m2,429s
user    0m0,000s
sys     0m0,046s

$ wc t.t
  864  1469 27191 t.t

**Comment by crypto-rsa** [comment]
Hmm, your timings are suspiciously bad. When I run just the `git log` command without writing to a file, i. e.
`$ time git log --format=%H --name-only --follow --all --diff-merges=separate HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null`
I get
```
real    0m0.574s
user    0m0.000s
sys     0m0.015s
```

and `wc` outputs `2043    1362   57546`.

You have presumably more remote branches so like 70% more commits but I don't understand why it takes almost 30 times longer to execute the command.

**Comment by crypto-rsa** [comment]
Could you try `--diff-merges=first-parent` instead? It seems to work correctly in the File History dialog and should have better performance.

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 2]
```diff
@@ -1164,6 +1164,8 @@ string BuildPathFilter(string? path)
                     $"--format=\"{startOfObjectId}%H\"",
                     "--name-only",
                     "--follow",
+                    "--all",
+                    "--diff-merges=separate",
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1168]: Can/should these be conditioned on something? E.g., add those only if necessary. Are these always required?

Comment (crypto-rsa) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1168]: Do you mean some kind of setting? Otherwise I am not really sure. I can imagine that checking _whether_ the flags would be relevant in the first place (i. e. whether there are any commits in unmerged branches and any merge commits) could take longer time than simply using them directly.

Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1168]: We have a setting on "follow" already (and one for only rename). This is a next level and would be a third setting which would be confusing.

Comment (crypto-rsa) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1168]: So should we include the `--diff-merges` option under the _Follow renames in file history_ setting? The `--all` option is kind of separate and doesn't cause such a big performance regression.

**Comment by gerhardol** [comment]
--all is not a major difference, first-parent slightly better
I probably have more branches than most (partly for these scenarios...), but it could add several seconds also for others.

If `--all --diff-merges=first-parent` is OK, I would prefer that only to be added by default (rather than having a setting). --all could be excluded for current branch only, but do not bother

Repo with few branches

$ time git log --format=%H --name-only --follow --all --diff-merges=separate HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null

real    0m2.350s

$ time git log --format=%H --name-only --follow --all --diff-merges=first-parent HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null

real    0m1.738s

$ time git log --format=%H --name-only --follow --diff-merges=first-parent HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null

real    0m0.795s

$ time git log --format=%H --name-only --follow HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null

real    0m0.572s

Repo with many branches

$ time git log --format=%H --name-only --follow --all --diff-merges=separate HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null

real    0m13.391s

$ time git log --format=%H --name-only --follow --all --diff-merges=first-parent HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null

real    0m6.444s

$ time git log --format=%H --name-only --follow --diff-merges=first-parent HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null

real    0m5.823s

$ time git log --format=%H --name-only --follow HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null

real    0m2.140s

**Comment by vbjay** [comment]
> --all is not a major difference, first-parent slightly better I probably have more branches than most (partly for these scenarios...), but it could add several seconds also for others.
> 
> If `--all --diff-merges=first-parent` is OK, I would prefer that only to be added by default (rather than having a setting). --all could be excluded for current branch only, but do not bother
> 
> Repo with few branches
> 
> $ time git log --format=%H --name-only --follow --all --diff-merges=separate HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null
> 
> real 0m2.350s
> 
> $ time git log --format=%H --name-only --follow --all --diff-merges=first-parent HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null
> 
> real 0m1.738s
> 
> $ time git log --format=%H --name-only --follow --diff-merges=first-parent HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null
> 
> real 0m0.795s
> 
> $ time git log --format=%H --name-only --follow HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null
> 
> real 0m0.572s
> 
> Repo with many branches
> 
> $ time git log --format=%H --name-only --follow --all --diff-merges=separate HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null
> 
> real 0m13.391s
> 
> $ time git log --format=%H --name-only --follow --all --diff-merges=first-parent HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null
> 
> real 0m6.444s
> 
> $ time git log --format=%H --name-only --follow --diff-merges=first-parent HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null
> 
> real 0m5.823s
> 
> $ time git log --format=%H --name-only --follow HEAD -- GitUI/CommandsDialogs/RevisionDiffControl.cs > /dev/null
> 
> real 0m2.140s

if first parent used then I think it needs to be reflected in the history window ui with first-parent toolbar item checked.

**Comment by gerhardol** [comment]
> if first parent used then I think it needs to be reflected in the history window ui with first-parent toolbar item checked.

https://github.com/gitextensions/gitextensions/issues/10970#issuecomment-1763822376
As @crypto-rsa wrote, this step is just a matter of finding all possible filenames, a few extra commits is probably not a bad thing.
`--all` could be replaced with the actual revision filter, just slower. Maybe `--reflog` need to be added if reflogs are shown.
To make a series of checks would be a solution too, but slower.

@vbjay When you were working with this, what was your approach?

**Comment by crypto-rsa** [comment]
> Maybe `--reflog` need to be added if reflogs are shown.

Yes, this occurred to me, too. It all boils down to the functionality vs. performance tradeoff. Personally, I prefer the former - to see the diff of each commit in the file's history is the reason I am opening the FH dialog in the first place.

**Comment by gerhardol** [comment]
I do not allow slowdowns, but could approve --diff-merges=first-parent
Would like to have some simple way to deactivate --follow though...

> Yes, this occurred to me, too.

Reflog should be handled, otherwise keep --all (-all could be added only for current branch only, minor improvement)

**Comment by crypto-rsa** [comment]
I couldn't get a single `git log` command to quickly retrieve just the revisions needed for the history list. Either it was too slow or missed some (even with `--diff-merges=first-parent`). So I took a different approach - I left the initial `git log` intact but then whenever a file name is requested for a revision which is not yet stored in the revision-path map, another `git log` command is run. I has the `--diff-merges=separate` option so works correctly for merge commits. And it is very fast because it only looks at a single revision (it takes a few tens of milliseconds).
I did a couple of tests and performance seems to be unaffected. The delay when first asking for a revision file name is imperceptible. Moreover, the result is stored in the revision-path map so it is reused next time.

**Review by gerhardol — COMMENTED** [review]
+1
Seem to work for me. I added Full History to the config requirement.
Will probably approve this tomorrow, merge in some days. (It could be included in 4.2, but then someone else must be supporting it - I do not FormFileHistory myself.)

Just to confirm: Any reason for the problem to appear in Browse too?

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 3]
```diff
@@ -1170,41 +1170,10 @@ string BuildPathFilter(string? path)
...
 
                 HashSet<string?> setOfFileNames = new();
-                ExecutionResult result = Module.GitExecutable.Execute(args, outputEncoding: GitModule.LosslessEncoding, throwOnErrorExit: false);
-                var lines = result.StandardOutput.LazySplit('\n');
 
-                // TODO Check the exit code and warn the user that rename detection could not be done.
-
-                ObjectId currentObjectId = null;
-                foreach (var line in lines.Select(GitModule.ReEncodeFileNameFromLossless))
+                foreach (var item in ParseFileNames(args, startOfObjectId))
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1174]: MC
```suggestion
                foreach (string item in ParseFileNames(args, startOfObjectId))
```

File: GitUI/CommandsDialogs/FormFileHistory.cs [hunk 4]
```diff
@@ -226,7 +226,12 @@ private void LoadFileHistory()
 
             ObjectId objectId = rev.IsArtificial ? RevisionGrid.CurrentCheckout : rev.ObjectId;
 
-            return RevisionGrid.FilePathByObjectId.TryGetValue(objectId, out string? path) ? path : null;
+            if (!RevisionGrid.FilePathByObjectId.TryGetValue(objectId, out string? path))
+            {
+                path = RevisionGrid.GetRevisionFileName(FileName, objectId.ToString());
+            }
+
+            return path;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormFileHistory.cs:234]: This feels like we're leaking implementation details. Can we refactor it so that the caller has to do a single call?
```suggestion
            return RevisionGrid.GetRevisionFileName(FileName, objectId);
```

**Review by RussKie — COMMENTED** [review]
Can you add tests for the new functionality please?

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 5]
```diff
@@ -1521,6 +1490,69 @@ static IEnumerable<ObjectId> TryGetParents(GitModule module, FilterInfo filterIn
...
+
+            GitArgumentBuilder args = new("log")
+            {
+                // --name-only will list each filename on a separate line, ending with an empty line
+                // Find start of a new commit with a sequence impossible in a filename
+                $"--format=\"{startOfObjectId}%H\"",
+                "--name-only",
+                "--follow",
+                "--diff-merges=separate",
+                FindRenamesAndCopiesOpts(),
```
Comment (gerhardol) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1505]: reflog if configured, also for the "standard" call
Add a comment where this is used (may be put elsewhere if you refactoe according to RussKie suggestions

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs (hunk 3 above)
Comment (crypto-rsa) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1174]: `ParseFileNames` no longer returns a `string` but a pair of strings. Should I deconstruct it like
`foreach ((_, string fileName) in ParseFileNames(args, startOfObjectId))`?

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs (hunk 5 above)
Comment (crypto-rsa) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1505]: I am not sure what you mean by the "standard" call. This method is only used in the File History dialog and because the actual revision ID is provided, we don't need to specify `--reflog` (or `--all` for that matter).

**Comment by crypto-rsa** [comment]
> Can you add tests for the new functionality please?

I am struggling with a bit. Do you mean a full integration test which creates a dummy repository, shows the file history dialog and checks whether the file content is correct in the View tab?

**Comment by RussKie** [comment]
> I am struggling with a bit. Do you mean a full integration test which creates a dummy repository, shows the file history dialog and checks whether the file content is correct in the View tab?
> 
> EDIT: Actually, I sort of succeeded in creating the test but programmatically creating the repository (with merge commits and/or conflicts) is proving to be difficult. Is there a way to use an existing repository in a test?

`GetRevisionFileName` can be tested as a unit test with `Module.GitExecutable.Execute` call stubbed. We have multiple examples for this, e.g.:
https://github.com/gitextensions/gitextensions/blob/8e5ffcf465b544d7c00d41c1e263fe3f773297a8/UnitTests/GitCommands.Tests/GitModuleTests.cs#L321-L332

It'd be good to have integration tests as well which would run actual git against a real repo.
* Integration tests for the `RevisionGridControl` are located here:
https://github.com/gitextensions/gitextensions/blob/8e5ffcf465b544d7c00d41c1e263fe3f773297a8/IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs#L14-L16
* Integration tests for the `FormFileHistory` are located here (though, for this PR the tests for the `RevisionGridControl` are appropriate):
https://github.com/gitextensions/gitextensions/blob/8e5ffcf465b544d7c00d41c1e263fe3f773297a8/IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormFileHistoryTests.cs#L10-L11

**Comment by crypto-rsa** [comment]
I finally got around to updating the branch. I've added both a unit test and an integration test. However, I have some issues with them:
* The unit test depends on mocking the **exact** `git log` arguments that are used in `GetFileNameForRevision()` (including the _double space_ before `--find-renames`). Some of the arguments also depend on the user settings. Is this the correct way to implement the unit test?
* In the integration test, I was unable to programmatically create a repository where a file would be both renamed and slightly altered in the same commit which would be the ultimate test for the new functionality. So there are currently just simple rename commits which don't change the file contents.

**Comment by gerhardol** [comment]
>  Some of the arguments also depend on the user settings. Is this the correct way to implement the unit test?

If a test depends on a setting it must be set and restored in the test.

>     * In the integration test, I was unable to programmatically create a repository where a file would be both renamed and slightly altered in the same commit which would be the ultimate test for the new functionality. So there are currently just simple rename commits which don't change the file contents.

Can yousee that altering the file is essential?
I believe this is covering the problem, so it should be sufficient.

**Comment by crypto-rsa** [comment]
> If a test depends on a setting it must be set and restored in the test.

✔️

**Comment by crypto-rsa** [comment]
> Can you see that altering the file is essential?

Not essential, just nice to have - but I suppose given that the `RevisionGrid` can now get the correct file name for a revision, it can also get its contents.

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1180]: Yes, please

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 6]
```diff
@@ -1537,6 +1506,82 @@ static IEnumerable<ObjectId> TryGetParents(GitModule module, FilterInfo filterIn
...
+        }
+
+        private IEnumerable<(string revision, string fileName)> ParseFileNames(GitArgumentBuilder args, string startOfObjectId)
+        {
+            ExecutionResult result = Module.GitExecutable.Execute(args, outputEncoding: GitModule.LosslessEncoding, throwOnErrorExit: false);
+            LazyStringSplit lines = result.StandardOutput.LazySplit('\n');
+
+            // TODO Check the exit code and warn the user that rename detection could not be done.
+
+            ObjectId currentObjectId = null;
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1550]:
```suggestion
            ObjectId? currentObjectId = null;
```

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 7]
```diff
@@ -1537,6 +1506,82 @@ static IEnumerable<ObjectId> TryGetParents(GitModule module, FilterInfo filterIn
...
+
+            foreach (string? line in lines.Select(GitModule.ReEncodeFileNameFromLossless))
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1552]: How can `line` be `null`?

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 8]
```diff
@@ -1537,6 +1506,82 @@ static IEnumerable<ObjectId> TryGetParents(GitModule module, FilterInfo filterIn
...
+                        || !ObjectId.TryParse(line, offset: startOfObjectId.Length, out currentObjectId))
+                    {
+                        // Parse error, ignore
+                        currentObjectId = null;
+                    }
+
+                    continue;
+                }
+
+                if (currentObjectId == null)
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1572]:
```suggestion
                if (currentObjectId is null)
```

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 9]
```diff
@@ -1537,6 +1506,82 @@ static IEnumerable<ObjectId> TryGetParents(GitModule module, FilterInfo filterIn
...
+                {
+                    // Parsing has failed, ignore
+                    continue;
+                }
+
+                // Add only the first file to the dictionary
+                FilePathByObjectId?.TryAdd(currentObjectId, line);
+
+                yield return (currentObjectId.ToString(), line);
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1581]: Why are we reallocating `currentObjectId` as a string? In the callsite we reallocating another ObjectId instace as a string to make a comparison.

File: IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormFileHistoryTests.cs [hunk 10]
```diff
@@ -39,6 +39,47 @@ public void File_history_should_behave_as_expected(string fileRelativePath, stri
             }, Path.Combine(fileRelativePath, fileName), commands);
     }
 
+    [Test]
+    public void File_history_should_display_contents_in_all_revisions()
+    {
+        const string text = "This text will appear in a file that shall be renamed";
+
+        using ReferenceRepository referenceRepository = new(createCommit: false);
```
Comment (RussKie) [inline IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormFileHistoryTests.cs:47]: Currently there's only one test in this class, so the current implementation suffices. However, in a test class with more than one test using `ReferenceRepository` we should be doing this:
```cs
        // Created once for the fixture
        private ReferenceRepository _referenceRepository;

        // Created once for each test
        private GitUICommands _commands;

        [SetUp]
        public void SetUp()
        {
            ReferenceRepository.ResetRepo(ref _referenceRepository);
            _commands = new GitUICommands(GlobalServiceContainer.CreateDefaultMockServiceContainer(), _referenceRepository.Module);
        }

        [OneTimeTearDown]
        public void OneTimeTearDown()
        {
            _referenceRepository.Dispose();
        }

```

File: UnitTests/GitUI.Tests/UserControls/RevisionGrid/RevisionFileNameTests.cs [hunk 11]
```diff
@@ -0,0 +1,78 @@
...
+    /// <returns>The GitModule</returns>
+    private static GitModule GetGitModuleWithExecutable(IExecutable executable)
+    {
+        GitModule? module = new(null);
+
+        typeof(GitModule).GetField("_gitExecutable", BindingFlags.Instance | BindingFlags.NonPublic)?.SetValue(module, executable);
+        GitCommandRunner cmdRunner = new(executable, () => GitModule.SystemEncoding);
+        typeof(GitModule).GetField("_gitCommandRunner", BindingFlags.Instance | BindingFlags.NonPublic)?.SetValue(module, cmdRunner);
+
+        return module;
```
Comment (RussKie) [inline UnitTests/GitUI.Tests/UserControls/RevisionGrid/RevisionFileNameTests.cs:76]: Is there any reason not to use `MockExecutable`?
https://github.com/gitextensions/gitextensions/blob/eeaf3c13e644a15178686af70bf362547943daa6/UnitTests/GitCommands.Tests/Git/Gpg/GitGpgControllerTests.cs#L16-L25

File: IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormFileHistoryTests.cs [hunk 12]
```diff
@@ -39,6 +39,47 @@ public void File_history_should_behave_as_expected(string fileRelativePath, stri
...
+                bool textLoaded;
+
+                WaitForRevisionsToBeLoaded(form);
+                form.GetTestAccessor().SelectViewTab();
+                form.GetTestAccessor().FileViewer.TextLoaded += (_, _) => textLoaded = true;
+
+                textLoaded = false;
+                form.GetTestAccessor().RevisionGrid.SetSelectedRevision(ObjectId.Parse(initialRevision)).Should().BeTrue();
+                UITest.ProcessUntil("Loading file text", () => textLoaded);
+                form.GetTestAccessor().FileViewer.GetTestAccessor().FileViewerInternal.GetTestAccessor().TextEditor.Text.Should().Be(text);
```
Comment (RussKie) [inline IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormFileHistoryTests.cs:69]: 💭  This is repeated several times, may worth considering refactoring this block as a local function.

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 13]
```diff
@@ -1537,6 +1506,82 @@ static IEnumerable<ObjectId> TryGetParents(GitModule module, FilterInfo filterIn
...
+        /// Returns the name of a file in a specific revision (following renames and merge commits)
+        /// </summary>
+        public string? GetRevisionFileName(string path, ObjectId? objectId)
+        {
+            if (FilePathByObjectId is null || objectId is null)
+            {
+                return null;
+            }
+
+            if (FilePathByObjectId.TryGetValue(objectId, out string? fileName))
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1519]: This unnecessary restriction can be removed:
```suggestion
            if (objectId is null)
            {
                return null;
            }

            if (FilePathByObjectId?.TryGetValue(objectId, out string? fileName) is true)
```

**Review by mstv — COMMENTED** [review]
Do we need a similar approach when filtering in FormBrowse?
Should we backport this for 4.2.1?

**Comment by gerhardol** [comment]
> Do we need a similar approach when filtering in FormBrowse? 

No, FormBrowse shows the info for the commit, not just a specific filename.
FormFileHistory shows all data in the commit tab similar to in Diff (just with less features).

> Should we backport this for 4.2.1?

I do not think so.

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs (hunk 5 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1534]: You can still activate Reflog in FileHistory.

But this is just FileHistory, let us just try to finalize this.

File: UnitTests/GitUI.Tests/UserControls/RevisionGrid/RevisionFileNameTests.cs (hunk 11 above)
Comment (crypto-rsa) [reply UnitTests/GitUI.Tests/UserControls/RevisionGrid/RevisionFileNameTests.cs:76]: I tried but I cannot get it through the whole hierarchy of mock objects. Specifically, I need a `GitUICommands` instance (**not** `IGitUiCommands`) for the `IGitUICommandsSource.UICommands` property. But the constructor of `GitUICommands` takes a `GitModule` (**not** `IGitModule`) as a parameter.

Comment (mstv) [reply UnitTests/GitUI.Tests/UserControls/RevisionGrid/RevisionFileNameTests.cs:76]: `IGitModule` has been completed. Perhaps, the needed things become available after resolving the MC.

Comment (RussKie) [reply UnitTests/GitUI.Tests/UserControls/RevisionGrid/RevisionFileNameTests.cs:76]: Please rebase on top of the latest master. Since https://github.com/gitextensions/gitextensions/pull/11269 all public API use `IGitModule`.

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1180]: A gentle ping

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 14]
```diff
@@ -1537,6 +1506,82 @@ static IEnumerable<ObjectId> TryGetParents(IGitModule module, FilterInfo filterI
             }
         }
 
+        /// <summary>
+        /// Returns the name of a file in a specific revision (following renames and merge commits)
+        /// </summary>
+        public string? GetRevisionFileName(string path, ObjectId? objectId)
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1512]: Please add xml-docs for the parameters and the return.

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 15]
```diff
@@ -1537,6 +1506,82 @@ static IEnumerable<ObjectId> TryGetParents(IGitModule module, FilterInfo filterI
...
+
+            return ParseFileNames(args, startOfObjectId).FirstOrDefault(i => i.revision.Equals(objectId)).fileName;
+        }
+
+        private IEnumerable<(ObjectId revision, string fileName)> ParseFileNames(GitArgumentBuilder args, string startOfObjectId)
+        {
+            ExecutionResult result = Module.GitExecutable.Execute(args, outputEncoding: GitModule.LosslessEncoding, throwOnErrorExit: false);
+            LazyStringSplit lines = result.StandardOutput.LazySplit('\n');
+
+            // TODO Check the exit code and warn the user that rename detection could not be done.
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1548]: What are the plans for this TODO?

Comment (crypto-rsa) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1548]: I don't really know what are the "plans" - I just extracted the existing code to a dedicated method. But IMO if the git command did not execute successfully, the only thing we could do is just return early from this method (i. e. not return any file names).

**Comment by gerhardol** [comment]
> > The remainning comment I have is that reflog is not searched
> 
> I am not sure what you mean - reflog revisions work correctly. We don't need to pass the `--reflog` parameter to `git log` because we are passing the actual revision to it.

If you havefiles renamed in reflog branches, the names will not be included.
But revisions like what was missing for merges will be loaded.
Not requesting changes.

**Review by gerhardol — APPROVED** [review]

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 16]
```diff
@@ -1537,6 +1506,89 @@ static IEnumerable<ObjectId> TryGetParents(IGitModule module, FilterInfo filterI
...
+            GitArgumentBuilder args = new("log")
+            {
+                // --name-only will list each filename on a separate line, ending with an empty line
+                // Find start of a new commit with a sequence impossible in a filename
+                $"--format=\"{startOfObjectId}%H\"",
+                "--name-only",
+                "--follow",
+                "--diff-merges=separate",
+                FindRenamesAndCopiesOpts(),
+                $"{objectId}^1..{objectId}",
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1538]: Might the following be more efficient?
```suggestion
                $"{objectId}",
                "--max-count=1"
```

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 17]
```diff
@@ -1537,6 +1506,89 @@ static IEnumerable<ObjectId> TryGetParents(IGitModule module, FilterInfo filterI
...
+                "--",
+                path,
+            };
+
+            return ParseFileNames(args, startOfObjectId).FirstOrDefault(i => i.revision.Equals(objectId)).fileName;
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1543]: Do you expect output with different object id's?

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 18]
```diff
@@ -1537,6 +1506,89 @@ static IEnumerable<ObjectId> TryGetParents(IGitModule module, FilterInfo filterI
...
+        }
+
+        private IEnumerable<(ObjectId revision, string fileName)> ParseFileNames(GitArgumentBuilder args, string startOfObjectId)
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1546]: If the above does not need the ObjectId, it should be removed, i.e.
```suggestion
        private IEnumerable<string> ParseFileNames(GitArgumentBuilder args, string startOfObjectId)
```
Else an `ObjectId` is not a `GitRevision`, i.e.
```suggestion
        private IEnumerable<(ObjectId objectId, string fileName)> ParseFileNames(GitArgumentBuilder args, string startOfObjectId)
```

**Review by mstv — COMMENTED** [review]
just nits

**Review by mstv — COMMENTED** [review]
just nits

**Comment by crypto-rsa** [comment]
Many of the comments here are related to code which I didn't write myself in this PR but merely extracted to a dedicated method `ParseFileNames` in the first commit. I can try to address them as suggested.

**Review by gerhardol — APPROVED** [review]
I believe the comments are adressed

**Review by mstv — APPROVED** [review]
Thank you

**Comment by mstv** [comment]
If we go for a 4.2.2, we should backport this. I have got complaints from colleagues, too.

**Comment by RussKie** [comment]
If you think it's necessary, we can do 4.2.2

**Comment by mstv** [comment]
> If you think it's necessary, we can do 4.2.2

It is not urgent - if necessary at all since #11440 has been closed. Let's wait 1-2 weeks.

**Comment by crypto-rsa** [comment]
Is there anything else needed from me in order to merge the branch?

**Comment by RussKie** [comment]
Thank you

**Comment by crypto-rsa** [comment]
Phew, that took a while! But thanks to all for your comments and suggestions.
