### PR TITLE
Stash pop/apply: Refresh grid if command was successful

### LINKED ISSUE #9121: Stash pop is not refreshing the window
## Current behaviour

The window is not being refresh after a stash pop operation and so still shows the previous stashed code, even when it is not there anymore.

## Expected behaviour

The window should be refreshed after a stash pop operation

## Steps to reproduce

1. Stash some code
2. Observe that the window shows the stashed code with the other commits
3. Do a stash pop directly via menu option on toolbar
4. Observe commits in window

## Did this work in previous version of GitExtensions

Yes, this was working fine just on previous stable version to current 3.5.0.11713

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4341.0
- DPI 192dpi (200% scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #9121

## Proposed changes

Refresh revision grid after Stash pop.
Also changed after stash-apply, but that makes no practical difference as the command is only invoked from FormStash (and not update the grid...)

Regression, to be cherry-picked for 3.5

## Test methodology 

See the issue. Stash, stash-pop and see that the grid refreshes.

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by ivangrek** [comment]
Why update if merge conflicts are false?

**Comment by gerhardol** [comment]
> Why update if merge conflicts are false?

The stash commit is popped, no longer visible in the grid.

File: GitUI/GitUICommands.cs [hunk 1]
```diff
@@ -202,7 +202,12 @@ public bool StashPop(IWin32Window? owner)
             bool Action()
             {
                 bool success = FormProcess.ShowDialog(owner, process: null, arguments: "stash pop", Module.WorkingDir, input: null, useDialogSettings: true);
-                return success && MergeConflictHandler.HandleMergeConflicts(this, owner, false, false);
+                if (success)
+                {
+                    MergeConflictHandler.HandleMergeConflicts(this, owner, false, false);
```
Comment (RussKie) [inline GitUI/GitUICommands.cs:207]: So what happens if conflicts aren't resolved?

Comment (gerhardol) [reply GitUI/GitUICommands.cs:207]: The merge conflict banner is shown similar to if a patch cannot be applied, rebase conflicts etc.
The grid needs to be updated regardless

The old handling (always run HandleMergeConflicts(), return true to always refresh the grid) was safer, I believe this is OK though.

Comment (mstv) [reply GitUI/GitUICommands.cs:207]: I must have missed these two when approving #8303. Since we cannot know how much git had done before the error, we should always request a refresh, i.e. always `return true`, please.

**Review by mstv — COMMENTED** [review]
Applies to `StashSave`, `StashDrop`, too.

**Comment by gerhardol** [comment]
> I must have missed these two when approving #8303. Since we cannot know how much git had done before the error, we should always request a refresh, i.e. always return true, please.

I choose to make the update for the likely change, but if the other situations already makes the change unconditionally I will revert the behavior to prior #8303

File: GitUI/GitUICommands.cs [hunk 2]
```diff
@@ -227,13 +228,10 @@ public bool StashApply(IWin32Window? owner, string stashName)
         {
             bool Action()
             {
-                bool success = FormProcess.ShowDialog(owner, process: null, arguments: $"stash apply {stashName.Quote()}", Module.WorkingDir, input: null, useDialogSettings: true);
-                if (success)
-                {
-                    MergeConflictHandler.HandleMergeConflicts(this, owner, false, false);
-                }
+                FormProcess.ShowDialog(owner, process: null, arguments: $"stash apply {stashName.Quote()}", Module.WorkingDir, input: null, useDialogSettings: true);
+                MergeConflictHandler.HandleMergeConflicts(this, owner, false, false);
```
Comment (RussKie) [inline GitUI/GitUICommands.cs:232]: Please add a comment explaining why we can't chain the operations like we did.

File: GitUI/GitUICommands.cs [hunk 3]
```diff
@@ -217,7 +216,9 @@ public bool StashDrop(IWin32Window? owner, string stashName)
         {
             bool Action()
             {
-                return FormProcess.ShowDialog(owner, process: null, arguments: $"stash drop {stashName.Quote()}", Module.WorkingDir, input: null, useDialogSettings: true);
+                FormProcess.ShowDialog(owner, process: null, arguments: $"stash drop {stashName.Quote()}", Module.WorkingDir, input: null, useDialogSettings: true);
+
+                return true;
```
Comment (RussKie) [inline GitUI/GitUICommands.cs:221]: ditto here

File: GitUI/GitUICommands.cs [hunk 4]
```diff
@@ -201,13 +203,10 @@ public bool StashPop(IWin32Window? owner)
...
-                if (success)
-                {
-                    MergeConflictHandler.HandleMergeConflicts(this, owner, false, false);
-                }
+                FormProcess.ShowDialog(owner, process: null, arguments: "stash pop", Module.WorkingDir, input: null, useDialogSettings: true);
+                MergeConflictHandler.HandleMergeConflicts(this, owner, false, false);
 
-                return success;
+                return true;
             }
```
Comment (RussKie) [inline GitUI/GitUICommands.cs]: ditto

File: GitUI/GitUICommands.cs [hunk 5]
```diff
@@ -191,7 +191,9 @@ public bool StashSave(IWin32Window? owner, bool includeUntrackedFiles, bool keep
             bool Action()
             {
                 var arguments = GitCommandHelpers.StashSaveCmd(includeUntrackedFiles, keepIndex, message, selectedFiles);
-                return FormProcess.ShowDialog(owner, process: null, arguments, Module.WorkingDir, input: null, useDialogSettings: true);
+                FormProcess.ShowDialog(owner, process: null, arguments, Module.WorkingDir, input: null, useDialogSettings: true);
+
+                return true;
```
Comment (RussKie) [inline GitUI/GitUICommands.cs:196]: ditto

**Review by RussKie — APPROVED** [review]

File: GitUI/GitUICommands.cs [hunk 6]
```diff
@@ -191,7 +191,10 @@ public bool StashSave(IWin32Window? owner, bool includeUntrackedFiles, bool keep
             bool Action()
             {
                 var arguments = GitCommandHelpers.StashSaveCmd(includeUntrackedFiles, keepIndex, message, selectedFiles);
-                return FormProcess.ShowDialog(owner, process: null, arguments, Module.WorkingDir, input: null, useDialogSettings: true);
+                FormProcess.ShowDialog(owner, process: null, arguments, Module.WorkingDir, input: null, useDialogSettings: true);
+
+                // git-stash may have changed commits also if aborted, the grid must be refereshed
```
Comment (mstv) [inline GitUI/GitUICommands.cs:196]:
```suggestion
                // git-stash may have changed commits also if aborted, the grid must be refreshed
```

**Review by mstv — APPROVED** [review]
Would you fix the typo in all comments?

**Comment by gerhardol** [comment]
@msftbot merge in 24 hours
