### PR TITLE
fix: show recent destination directories on clone

### LINKED ISSUE #11760: Destination directory on clone not remembered
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.30
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When you clone a repo, you get to decide where it should be cloned. This is a textbox with a dropdown, but both stay empty.

image

Prior versions of Git Extensions (at least v3) remembered earlier-chosen destination directories. 

### Steps to reproduce

1. Click Start -> Clone repository...
2. Paste repository URL (e.g. "https://github.com/gitextensions/gitextensions.git")
3. Enter a destination (e.g. "G:\Git\gitextensions")
4. Clone
5. Restart application
6. Start to clone another repo (steps 1 and 2)
7. See the "Destination" field being empty again, the dropdown also not showing previously used locations

### Did this work in previous version of GitExtensions?

I think v3 did this properly. 

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by nikolaosginos**
Fixes #11760

## Proposed changes

- When showing the clone window, fill the destination path combo box with the parent directories of the recent repository destination's
- Use the same logic as on the general settings page's default location combo box

### Before

image

### After

image

## Test methodology 

- Manual testing only

## Test environment(s) 

- GIT 2.51
- Windows 11 24H2

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Thank you

File: src/app/GitCommands/UserRepositoryHistory/Repository.cs [hunk 1]
```diff
@@ -38,6 +38,22 @@ public string Path
             set => _path = value;
         }
 
+        public string GetParentPath()
+        {
+            if (Path.StartsWith(@"\\") || !Directory.Exists(Path))
```
Comment (gerhardol) [inline src/app/GitCommands/UserRepositoryHistory/Repository.cs:43]: This will not work in WSL (or Linux if that is resurrected). I do not recall the name, it may be Path.IsPathRooted()

There may be a function to get this directly too

File: src/app/GitUI/CommandsDialogs/FormClone.cs [hunk 2]
```diff
@@ -55,6 +55,12 @@ protected override void OnRuntimeLoad(EventArgs e)
             _NO_TRANSLATE_From.DataSource = repositoryHistory;
             _NO_TRANSLATE_From.DisplayMember = nameof(Repository.Path);
 
+            IList<Repository> localsHistory = ThreadHelper.JoinableTaskFactory.Run(RepositoryHistoryManager.Locals.LoadRecentHistoryAsync);
```
Comment (gerhardol) [inline src/app/GitUI/CommandsDialogs/FormClone.cs:58]: What is a typical delay for this?

**Review by gerhardol — COMMENTED** [review]
+1

File: src/app/GitUI/CommandsDialogs/FormClone.cs (hunk 2 above)
Comment (nikolaosginos) [reply src/app/GitUI/CommandsDialogs/FormClone.cs:58]: To be honest, I mostly copied the code from `GeneralSettingsPage` and extracted common functionality in this commit. So I did not think it would be a performance issue if it is the same way as in the settings.

I did some quick manual tests with the `Stopwatch` class and it was consistently less that 0.3 milliseconds.

File: src/app/GitCommands/UserRepositoryHistory/Repository.cs (hunk 1 above)
Comment (nikolaosginos) [reply src/app/GitCommands/UserRepositoryHistory/Repository.cs:43]: I extracted this from `GeneralSettingsPage`. So this is existing code from Git Extensions. It does not check if the path is rooted since there are two backslashes. I guess it checks if it is a UNC path to a network share but I do not know why. It is probably not relevant on Linux or WSL since a network share would be mounted to a regular directory and therefore not use this `\\server-name\share-name\` syntax anyway.

File: src/app/GitUI/CommandsDialogs/FormClone.cs (hunk 2 above)
Comment (RussKie) [reply src/app/GitUI/CommandsDialogs/FormClone.cs:58]: @gerhardol this should be consistent with what we already have with the repo dropdown in the main form. Given this is a standalong dialog, this shouldn't be an issue at all.

File: src/app/GitCommands/UserRepositoryHistory/Repository.cs (hunk 1 above)
Comment (RussKie) [reply src/app/GitCommands/UserRepositoryHistory/Repository.cs:43]: Given this is a port of the existing functionality we can take it as is. 
A check to confirm WSL-compatibility would be a bonus though.

File: src/app/GitUI/CommandsDialogs/FormClone.cs [hunk 3]
```diff
@@ -55,6 +55,12 @@ protected override void OnRuntimeLoad(EventArgs e)
...
+            string[] historicPaths = localsHistory.Select(x => x.GetParentPath())
+                                                      .Where(x => !string.IsNullOrEmpty(x))
+                                                      .Distinct(StringComparer.CurrentCultureIgnoreCase)
+                                                      .ToArray();
```
Comment (RussKie) [inline src/app/GitUI/CommandsDialogs/FormClone.cs:62]: Please align dots like this

Image

File: src/app/GitUI/CommandsDialogs/FormClone.cs (hunk 2 above)
Comment (gerhardol) [reply src/app/GitUI/CommandsDialogs/FormClone.cs:58]: The repo dropdown menu is unusable for me, but I have 150 repos (I would like to use more).
I have privately removed branches there to have something working (I still want branches in the dashboard).
It may be OK here though.

File: src/app/GitCommands/UserRepositoryHistory/Repository.cs (hunk 1 above)
Comment (mstv) [reply src/app/GitCommands/UserRepositoryHistory/Repository.cs:43]: I guess the check for UNC was added in order to avoid long delays by `Directory.Exists` in case the server is unreachable.

Side note: `SshPathLocator` does something similar: `Directory.GetParent(Path.RemoveTrailingPathSeparator())`
but not exactly. The handling of root folders is worse than here - though pretty hidden and unexpected. The method name may be OK for a private method but not for a public one.

I hesitate to let this become a method of `Repository` because the functionality is not really specific to a repository.
It might rather be added as an extension method, e.g. `PathUtil.GetParentDirOrRootIfLocalAndExists` or the like - with XML docs.

File: src/app/GitUI/CommandsDialogs/FormClone.cs (hunk 2 above)
Comment (RussKie) [reply src/app/GitUI/CommandsDialogs/FormClone.cs:58]: > The repo dropdown menu is unusable for me, but I have 150 repos (I would like to use more). I have privately removed branches there to have something working (I still want branches in the dashboard). It may be OK here though.

This is an existing implementation, and in this dialog it shouldn't be a big deal. And we can certainly entertain an option to make this functionality more performant, if possible (e.g., not loading branches).

File: src/app/GitCommands/UserRepositoryHistory/Repository.cs (hunk 1 above)
Comment (RussKie) [reply src/app/GitCommands/UserRepositoryHistory/Repository.cs:43]: > I guess the check for UNC was added in order to avoid long delays by `Directory.Exists` in case the server is unreachable.

I vaguely remember discussions about this some years ago, but I can't recall any specific details.

File: src/app/GitUI/CommandsDialogs/FormClone.cs (hunk 2 above)
Comment (gerhardol) [reply src/app/GitUI/CommandsDialogs/FormClone.cs:58]: I do not think this will be a big problem performance wise. The branch menu closes a few times, then it can kindof be used.
clone is not so frequent.
I do not block merge, I just have not approved it.

**Comment by RussKie** [comment]
Thank you
