### PR TITLE
fix(settings): Ignore non-boolean advanced git config settings

### LINKED ISSUE #11939: [NBug] Git setting 'pull.rebase': failed to convert value 'merges' into type 'System.Boolean'
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
GitExtensions.Extensibility.Settings.GitConfigFormatException: Git setting 'pull.rebase': failed to convert value 'merges' into type 'System.Boolean'
   at GitCommands.Settings.ConfigFileSettings.ConvertValue[T](String value, String setting) in C:\projects\gitextensions\src\app\GitCommands\Settings\ConfigFileSettings.cs:line 103
   at GitCommands.Settings.ConfigFileSettings.GetValue[T](String setting) in C:\projects\gitextensions\src\app\GitCommands\Settings\ConfigFileSettings.cs:line 86
   at GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigAdvancedSettingsPage.SettingsToPage() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Pages\GitConfigAdvancedSettingsPage.cs:line 44
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\SettingsPageBase.cs:line 103
   at GitUI.CommandsDialogs.FormSettings.LoadSettings() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 69
   at GitUI.CommandsDialogs.FormSettings.FormSettings_Shown(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 275
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

I have pull.rebase set to 'merges', but when I opened the settings interface, I got this exception.

### Steps to reproduce

Manually set pull.rebase=merges in git config file.
Open repository where this config file is in effect in Git Extensions.
Open Tools -> Settings.

### Did this work in previous version of GitExtensions?

I don't know, I just changed the setting in my gitconfig file a day or two ago.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11939

## Proposed changes

GitConfigAdvancedSettingsPage:
- display git config without value or with non-boolean value as indeterminate 
- do not overwrite such settings

### Before

image

### After

image

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

File: src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.cs [hunk 1]
```diff
@@ -41,7 +41,12 @@ protected override void SettingsToPage()
             Validates.NotNull(CurrentSettings);
             foreach (GitSettingUiMapping gitSetting in _gitSettings)
             {
-                gitSetting.MappedCheckbox.Checked = CurrentSettings.GetValue<bool>(gitSetting.GitSettingKey) is true;
+                gitSetting.MappedCheckbox.CheckState = CurrentSettings.GetValue(gitSetting.GitSettingKey) switch
+                    {
+                        "true" => CheckState.Checked,
```
Comment (gerhardol) [inline src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.cs:46]: https://git-scm.com/docs/git-config#Documentation/git-config.txt-boolean
```suggestion
                        "true" or "yes" or "on" or "1" => CheckState.Checked,
```

File: src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.cs [hunk 2]
```diff
@@ -41,7 +41,12 @@ protected override void SettingsToPage()
...
+                        "false" => CheckState.Unchecked,
```
Comment (gerhardol) [inline src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.cs:47]:
```suggestion
                        "false" or "no" or "off" or "0" or "" => CheckState.Unchecked,
```

**Review by gerhardol — APPROVED** [review]

**Review by gerhardol — APPROVED** [review]
