### PR TITLE
Fix #7937 Reflog form : index was out of range.

### LINKED ISSUE #7937: [NBug] Index was out of range. Must be non-negative and less than ...
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewSelectedCellCollection.get_Item(Int32 index)
   at GitUI.CommandsDialogs.FormReflog.<GetShaOfRefLine>g__GetSelectedRow|12_0()
   at GitUI.CommandsDialogs.FormReflog.GetShaOfRefLine()
   at GitUI.CommandsDialogs.FormReflog.copySha1ToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
No idea

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 192dpi (200% scaling)

### PR DESCRIPTION
**Pull request by bansan85**
Fixes #7937 

## Proposed changes

In the Reflog form, when the popup are shown, if no row or cell are selected, use the current row.

### Before

An exception are shown.

### After

Use the commit in the current row.

## Test methodology 

I tried to copy a SHA with a line deselected. It crashes without my patch. It works with my patch.

## Test environment(s)

- Git Extensions 3.3.1.7897
- Git 2.25.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormReflog.cs [hunk 1]
```diff
@@ -125,9 +125,18 @@ private ObjectId GetShaOfRefLine()
...
+                    return gridReflog.SelectedRows[0];
+                }
+                else if (gridReflog.SelectedCells.Count > 0)
+                {
+                    return gridReflog.Rows[gridReflog.SelectedCells[0].RowIndex];
+                }
+                else
+                {
+                    return gridReflog.CurrentRow;
+                }
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/FormReflog.cs:139]:
```suggestion
                if (gridReflog.SelectedRows.Count > 0)
                {
                    return gridReflog.SelectedRows[0];
                }
                
                if (gridReflog.SelectedCells.Count > 0)
                {
                    return gridReflog.Rows[gridReflog.SelectedCells[0].RowIndex];
                }
                
                return gridReflog.CurrentRow;
```

**Comment by bansan85** [comment]
Fine. I changed the coding style.

**Comment by RussKie** [comment]
Thank you
