### PR TITLE
Remove unused `TreeGuid`

### LINKED ISSUE #9378: [NBug] Unable to parse object ID "".
:warning: Review existing issues to see whether someone else has already reported your issue.
- Sorry, I didnt have time.

## Current behaviour
- An Error Infobox pops up. GitExtensions closes aftwerward.
- Rebase stops with merge conflicts, but with no reference to the cherry picked commits (yet). 
- Aborting the rebase works.

## Expected behaviour
Rebase completes as usual or prompts about merge conflicts.

## Steps to reproduce
- Created orphan commit
- merged unrelated histories into it
- Added branching commits* after this
- later Cherry picked the merge commits onto the Orphan
- Finally, tried to Rebase the *branching commits onto the cherry picked commits using "preserve merges". This is when the error occured. Without "preserve merges" this error does not seem to occur. 

## Error Details
```
System.FormatException: Unable to parse object ID "".
   bei GitUIPluginInterfaces.ObjectId.Parse(String s)
   bei GitCommands.CommitDataManager.CreateFromFormattedData(String data)
   bei GitCommands.CommitDataManager.GetCommitData(String commitId, String& error, Boolean cache)
   bei GitCommands.GitModule.GetInteractiveRebasePatchFiles()
   bei GitUI.PatchGrid.GetPatches()
   bei GitUI.PatchGrid.Initialize()
   bei GitUI.CommandsDialogs.FormRebase.OkClick(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I was just trying out a bunch of stuff, not sure what is the cause. Could just as well be an issue with Git. I cannot provide the specific Repo I used. Hope I'm not wasting your time.

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.1
- Microsoft Windows NT 10.0.21354.0
- .NET Framework 4.8.4360.0
- DPI 120dpi (125% scaling)

### PR DESCRIPTION
**Pull request by mstv**
Fixes #9378
I hope

## Proposed changes

Remove the unused `CommitDataManager.TreeGuid` and do not attempt to parse this *optional* value.

## Screenshots 

N/A

## Test methodology 

- adapted testcases

## Test environment(s) 

- Git Extensions 33.33.33
- Build a9241924a70caa8d687e8be477587f68f8718455
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.3
- DPI 96dpi (no scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/CommitDataManager.cs [hunk 1]
```diff
@@ -135,7 +135,7 @@ internal CommitData CreateFromFormattedData(string data)
             var guid = ObjectId.Parse(lines[0]);
 
             // TODO: we can use this to add more relationship info like gitk does if wanted
-            var treeGuid = ObjectId.Parse(lines[1]);
+            ObjectId? treeGuid = string.IsNullOrWhiteSpace(lines[1]) ? null : ObjectId.Parse(lines[1]);
```
Comment (gerhardol) [inline GitCommands/CommitDataManager.cs:138]: TryParse()?
```suggestion
            ObjectId.TryParse(lines[1], out ObjectId? treeGuid);
```

**Review by gerhardol — APPROVED** [review]
One suggestion though

File: GitCommands/CommitDataManager.cs (hunk 1 above)
Comment (mstv) [reply GitCommands/CommitDataManager.cs:138]: `TryParse` was my first thought (refer to the branch name).
Though it would hide errors.
The bug report was about an empty string.

Comment (gerhardol) [reply GitCommands/CommitDataManager.cs:138]: Personally, I would prefer the simpler code and ignore malformed ids (like error messages accidentally here)

Comment (mstv) [reply GitCommands/CommitDataManager.cs:138]: > Personally, I would prefer the simpler code and ignore malformed ids (like error messages accidentally here)

`TryParse` would hide errors.
It *is* worth to make all expectations explicit.
If an exception from this rule is made, I want to have a good, written reason. I have seen "This error cannot happen" nevertheless occurring too often.
Either this line is empty or it contains a valid id.
Rather I would remove this unused property than `TryParse` it.

Comment (mstv) [reply GitCommands/CommitDataManager.cs:138]: Or else add a method `ParseOptional` - perhaps with a nicer name.

Comment (mstv) [reply GitCommands/CommitDataManager.cs:138]: Shall I remove the unused property `CommitData.TreeGuid`?
Or else, shall I add a method `ObjectId.ParseIfNotEmpty`?

Comment (gerhardol) [reply GitCommands/CommitDataManager.cs:138]: > Shall I remove the unused property `CommitData.TreeGuid`?

Yes, if needed it can be added again.
CommitInfo currently have no need of the commit contents

Comment (mstv) [reply GitCommands/CommitDataManager.cs]: Removed the property `CommitData.TreeGuid` and updated the PR title and description.

File: GitCommands/CommitDataManager.cs [hunk 2]
```diff
@@ -134,8 +134,7 @@ internal CommitData CreateFromFormattedData(string data)
 
             var guid = ObjectId.Parse(lines[0]);
 
-            // TODO: we can use this to add more relationship info like gitk does if wanted
-            var treeGuid = ObjectId.Parse(lines[1]);
+            // lines[1] contains the optional treeGuid
```
Comment (gerhardol) [inline GitCommands/CommitDataManager.cs:137]: Remove from git-log - affect all test cases

**Review by gerhardol — COMMENTED** [review]
-1
If removing the property, the info should no longer be retrieved

**Review by RussKie — APPROVED** [review]

File: GitCommands/CommitDataManager.cs [hunk 3]
```diff
@@ -107,9 +107,9 @@ internal CommitData CreateFromFormattedData(string data)
 
             var module = GetModule();
 
-            // $ git log --pretty="format:%H%n%T%n%P%n%aN <%aE>%n%at%n%cN <%cE>%n%ct%n%e%n%B%nNotes:%n%-N" -1
+            // $ git log --pretty="format:%H%n%n%P%n%aN <%aE>%n%at%n%cN <%cE>%n%ct%n%e%n%B%nNotes:%n%-N" -1
             // 4bc1049fc3b9191dbd390e1ae6885aedd1a4e34b
-            // a59c21f0b2e6f43ae89b76a216f9f6124fc359f8
+            // removed %T but kept newline: a59c21f0b2e6f43ae89b76a216f9f6124fc359f8
```
Comment (gerhardol) [inline GitCommands/CommitDataManager.cs:112]:
```suggestion
            // (comment: used to contain %T, kept newline)
```

**Review by gerhardol — APPROVED** [review]

**Review by gerhardol — APPROVED** [review]

**Review by RussKie — APPROVED** [review]
