### PR TITLE
AppVeyor: Handle v2 tokens

### LINKED ISSUE #8828: AppVeyor build integration does not work with v2 tokens
## Current behaviour

v2 tokens require another api path, https://ci.appveyor.com/api-keys
```
Below is a new user-level API key (v2) that allows working with any account user has access to.
API calls must be prepended with /api/account/<account-name>/ part to choose account to work with. 
```

Initial tests indicates that there is something more as well.

v1 (and no token at all??) has base /api/. However, I have no v1 key and cannot get no key working (not completely sure that should work) so the status is unclear.
The focus of this issue is on v2 tokens, as that is the path forward.

## Expected behaviour

Build status shown

## Steps to reproduce

* Open Git Extensions repo, pre configured for Appveyour
* Add username to settings
* Generate a v2 key https://ci.appveyor.com/api-keys
* Add the key to the configuration
 
Build status should be visible in the status column 

## Screenshots

image

should be

image

(for a Jenkins repo, some problems in a separate repo)

## Did this work in previous version of GitExtensions

v2 tokens cannot have worked in GE

unsure when I had a working setup, but I had something working in 3.4 this summer (v2 token was older though)

## Environment

- Git Extensions 33.33.33
- Build db4a7087e673733daa25e1026f7b5cab603a74d1
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #8828 

## Proposed changes

v2 tokens require that the account is prepended to the request..
This apparently is only required for quering repos for an account,
not normal info.

* Only query for project names for a configured account if no
account/repo at all is specified
Illegal repos will not report any builds anyway.
This allows a AppVeyor username/token at the same time as multiple
repos are used. For instance can gitextensions/gitextensions builds
be seen at the same time as user private builds

* Allow configuring of  account/repo also if accountName is set

* Less aggressive requery of running AppVeyor jobs

* Refactor
  * remove static variables/functions
  * Handle projectId (and name) as account/repo consistently
  * Use local functions (and inline code)
  * Remove internal data class Project (the module global is no longer needed)

## Test methodology 

Tests updated
Manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs [hunk 1]
```diff
@@ -75,151 +73,93 @@ internal class AppVeyorAdapter : IBuildServerAdapter
...
+            // accountName may be any accessible project (for instance upstream)
+            // if AppVeyorAccountName is set, projectNamesSetting may exclude the accountName part
+            string projectNamesSetting = config.GetString("AppVeyorProjectName", "");
+            var projectNames = _buildServerWatcher.ReplaceVariables(projectNamesSetting)
+                .Split(new[] { '|' }, StringSplitOptions.RemoveEmptyEntries)
+                .Where(p => p.Contains("/") || !string.IsNullOrEmpty(accountName))
+                .Select(p => p.Contains("/") ? p : accountName.Combine("/", p))
+                .ToList();
+
+            if (projectNames.Count() == 0
```
Comment (RussKie) [inline Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs:94]:
```suggestion
            if (projectNames.Count == 0
```

File: Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs [hunk 2]
```diff
@@ -75,151 +73,93 @@ internal class AppVeyorAdapter : IBuildServerAdapter
...
+                && (string.IsNullOrWhiteSpace(accountName) || string.IsNullOrWhiteSpace(accountToken)))
             {
-                projectNames = _buildServerWatcher.ReplaceVariables(projectNamesSetting)
-                    .Split(new[] { '|' }, StringSplitOptions.RemoveEmptyEntries);
+                // No projectIds in settings and no possibility to query
```
Comment (RussKie) [inline Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs:97]:
```suggestion
                // No projectIds in settings, nothing to query
```

File: Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs [hunk 3]
```diff
@@ -75,151 +73,93 @@ internal class AppVeyorAdapter : IBuildServerAdapter
...
+                return;
             }
 
-            if (Projects.Count == 0 ||
-                (!useAllProjects && Projects.Keys.Intersect(projectNames).Count() != projectNames.Length))
+            if (projectNames.Count() == 0)
             {
```
Comment (RussKie) [inline Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs:102]:
```cs
            if (projectNames.Count == 0) {
                if (string.IsNullOrWhiteSpace(accountName) || string.IsNullOrWhiteSpace(accountToken)) { return; }

                // No settings, query projects for this account
                ThreadHelper.JoinableTaskFactory.Run(...
```

**Comment by RussKie** [comment]
If it works - :shipit:

File: Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs (hunk 2 above)
Comment (gerhardol) [reply Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs:97]: // No projectIds in settings, cannot query

**Comment by gerhardol** [comment]
> 
> 
> If it works - :shipit:

I cannot test with v1 tokens, but v1 tokens have the same api so it should be the same.
It is of course possible that the cleanup logic breaks something, but I cannot think of any lost functionality (for accountName vs account/repo).
Some use cases are added though.

Plan to squash and initiate a merge tomorrow.
This should be considered for 3.5 too.

**Comment by gerhardol** [comment]
will squash and rebase tonight

**Comment by gerhardol** [comment]
@msftbot merge in 24h

**Comment by gerhardol** [comment]
@msftbot merge in 24 hours
