### PR TITLE
Browse Diff lost: Handle must be created prior to insertion

### LINKED ISSUE #4955: There is no Diff tab
**Do you want to request a *feature* or report a *bug*?**

:bug:

**What is the current behavior?**

There is no Diff tab
gitext

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Enable https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#detailed-browse-repository-window-show-revision-details-next-to-the-revision-list
2. Close GE
3. Open GE

**What is the expected behavior?**

Diff tab should be visible

**Environment you encounter the issue:**

- GitExtensions version: b3f168d30fc9cdc20e880db7d7eb0b269c03757a

**Did this work in previous version of GitExtensions (which)?**
Yes. 2.51

### PR DESCRIPTION
**Pull request by gerhardol**
Closes #4955

Changes proposed in this pull request:
Diff tab was lost if Commit info was shown in RevisionTree
The DiffTab is lost when inserted to the left.
This is related to the Dashboard changes that seem to restructure loading, the handle to the tabcontrol must be created to inserting:
https://social.msdn.microsoft.com/Forums/windows/en-US/5d10fd0c-1aa6-4092-922e-1fd7af979663/tabpagesinsert-bug?forum=winforms
 
Screenshots before and after (if PR changes UI):
- No tab lost

What did I do to test the code and ensure quality:
- Manual

Has been tested on (remove any that don't apply):
- Windows 10

### CODE REVIEW

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -284,6 +284,9 @@ public FormBrowse(GitUICommands commands, string filter)
 
         private void LayoutRevisionInfo()
         {
+            // Handle must be created prior to insertion
+            IntPtr h = CommitInfoTabControl.Handle;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs]: Do we want to do it in the .ctor?
I would also add the link you found to the comment (https://social.msdn.microsoft.com/Forums/windows/en-US/5d10fd0c-1aa6-4092-922e-1fd7af979663/tabpagesinsert-bug?forum=winforms)

**Comment by RussKie** [comment]
Wow, such a subtly bug. Thank you for fixing it

**Comment by RussKie** [comment]
Does it raise the event if handle is created in the ctor?

**Comment by jbialobr** [comment]
No, it is called from the BrowseLoad event.
```
System.NullReferenceException
  HResult=0x80004003
  Message=Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
  Source=GitUI
  Ślad stosu:
   at GitUI.CommandsDialogs.RevisionFileTree.LoadRevision(GitRevision revision) in D:\projekty\GitExt\GitUI\CommandsDialogs\RevisionFileTree.cs:line 135
   at GitUI.CommandsDialogs.FormBrowse.FillFileTree() in D:\projekty\GitExt\GitUI\CommandsDialogs\FormBrowse.cs:line 1085
   at GitUI.CommandsDialogs.FormBrowse.CommitInfoTabControl_SelectedIndexChanged(Object sender, EventArgs e) in D:\projekty\GitExt\GitUI\CommandsDialogs\FormBrowse.cs:line 1534
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.set_SelectedIndex(Int32 value)
   at System.Windows.Forms.TabControl.ControlCollection.Remove(Control value)
   at GitUI.GitUIExtensions.RemoveIfExists(TabControl tabControl, TabPage page) in D:\projekty\GitExt\GitUI\GitUIExtensions.cs:line 129
   at GitUI.CommandsDialogs.FormBrowse.LayoutRevisionInfo() in D:\projekty\GitExt\GitUI\CommandsDialogs\FormBrowse.cs:line 296
   at GitUI.CommandsDialogs.FormBrowse.BrowseLoad(Object sender, EventArgs e) in D:\projekty\GitExt\GitUI\CommandsDialogs\FormBrowse.cs:line 420
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at ResourceManager.GitExtensionsFormBase.OnLoad(EventArgs e) in D:\projekty\GitExt\ResourceManager\GitExtensionsFormBase.cs:line 92
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e) in D:\projekty\GitExt\GitUI\GitExtensionsForm.cs:line 201
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormBrowse.cs]: I added the link. 
This could have been fixed by restructuring in some way to, so the handle is created implicitly but I did not find any way when playing around briefly.
As the bug/limitation occurs for Insert and this the only place we insert tabs, I suggest to keep it here.
