### PR TITLE
Limit number of diff revisions

### LINKED ISSUE #8097: App crash showing diffs for multi selection
## Current behaviour

image

## Expected behaviour

Get the diff

## Steps to reproduce

1. Clone https://github.com/RussKie/MSBuildStructuredLog.git
2. Open repo
2. Ensure to have switch to [Diff] tab (from [Commit] tab)
2. Select the following commits in the order:
	* a7ecbe179cdf22028e8c30a24462269d7b04e4cd
	* eda3a98d1523670c02f43b6bbef7c59cc28c06ca
	* 20152f44ec377c73dca7c50ce3dce8c2f2478201
    image

3. Observe NBug form

## Error Details
```
System.ArgumentOutOfRangeException: capacity was less than the current size.
Parameter name: value
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at GitUI.FileStatusList.SetDiffs(IReadOnlyList`1 revisions, Func`2 getRevision)
   at GitUI.CommandsDialogs.RevisionDiffControl.SetDiffs(IReadOnlyList`1 revisions)
   at GitUI.CommandsDialogs.RevisionDiffControl.DisplayDiffTab()
   at GitUI.CommandsDialogs.FormBrowse.FillDiff()
   at GitUI.CommandsDialogs.FormBrowse.CommitInfoTabControl_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at GitUI.CommandsDialogs.FullBleedTabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.4.0.9378
- Build 85ab13ae47d7f68deae8135694ef2c622e2b498b
- Git 2.16.1.windows.4 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4150.0
- DPI 144dpi (150% scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #8097

## Proposed changes

Avoid creating the revisions instead of shrinking the list

## Test methodology 

Manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/UserControls/FileStatusList.cs [hunk 1]
```diff
@@ -654,11 +654,15 @@ public void SetDiffs(IReadOnlyList<GitRevision> revisions, Func<ObjectId, GitRev
...
                 {
                     // Get the parents for the selected revision
-                    tuples.AddRange(selectedRev.ParentIds?.Select(parentId =>
-                        ((GitRevision, GitRevision, string, IReadOnlyList<GitItemStatus>))(new GitRevision(parentId),
-                            selectedRev,
-                            _diffWithParent.Text + GetDescriptionForRevision(parentId),
-                            Module.GetDiffFilesWithSubmodulesStatus(parentId, selectedRev.ObjectId, selectedRev.FirstParentGuid))));
+                    var multipleParents = AppSettings.ShowDiffForAllParents ? selectedRev.ParentIds.Count : 1;
+                    tuples.AddRange(selectedRev
+                        .ParentIds?
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs:659]: ❗ This will throw, if `ParentIds == null`
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.addrange?view=netframework-4.6.1#exceptions

**Comment by RussKie** [comment]
I ran it locally and observed no crashes 👍 
Please fix the possible NRE, and it is good to go

File: GitUI/UserControls/FileStatusList.cs (hunk 1 above)
Comment (mstv) [reply GitUI/UserControls/FileStatusList.cs:659]: Though line 640 should be:
` var selectedRev = revisions?.FirstOrDefault();`

Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs:659]: I do not think that revisions can be null on line 640, but there is no harm in adding that.

**Comment by gerhardol** [comment]
@msftbot merge in 24 hours
