### PR TITLE
Fix blocking UI when drawing superproject refs

### LINKED ISSUE #5166: Browsing submodule repo can introduce UI pauses
**Do you want to request a *feature* or report a *bug*?**

Bug, following #5087.

**What is the current behavior?**

Opening a submodule's repo in GE `FormBrowse` results in a very slow experience if you show superproject references in the grid via these settings:

image

To show these references, we run `git ls-tree ...` for each such reference. These still run in the background, but it appears that the UI now blocks waiting for them to complete.

<details>
<summary>Details of the command log when browsing the `GitExtensionsDoc` submodule of this repo.</summary>

```
12:36:42.388    67ms UI git rev-parse --git-common-dir
12:36:42.464    73ms UI git config --get ą
12:36:42.598    60ms UI git --version
12:36:42.901    60ms UI git rev-parse HEAD
12:36:42.977  1290ms    git submodule status --cached GitExtensionsDoc
12:36:42.991    67ms UI git show-ref --dereference
12:36:43.097 running    git log -z --pretty=format:"%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b" --date-order --all --boundary --not --glob=notes --not  --max-count="100000" --
12:36:43.125    76ms    git for-each-ref --sort=-committerdate refs/heads/ --format="%(objectname) %(refname)"
12:36:43.223    83ms    git for-each-ref --sort=-committerdate refs/heads/ --format="%(objectname) %(refname)"
12:36:43.230    99ms    git rev-list --date-order --max-count="100000"  6bd3b036fc5718a51a0d27cde134c7019798c3ce
12:36:43.366    83ms    git ls-files -z --unmerged
12:36:43.391   136ms    git rev-parse --git-common-dir
12:36:43.391   120ms    git rev-parse --git-common-dir
12:36:43.391   139ms    git rev-parse --git-common-dir
12:36:43.394   117ms    git rev-parse --git-common-dir
12:36:43.452   132ms    git rev-parse --git-common-dir
12:36:43.516   412ms    git -c diff.submodule=short -c diff.noprefix=false diff --no-color  -- "Externals/Git.hub"
12:36:43.520   438ms    git -c diff.submodule=short -c diff.noprefix=false diff --no-color  -- "Externals/conemu-inside"
12:36:43.529   365ms    git -c diff.submodule=short -c diff.noprefix=false diff --no-color  -- "Externals/ICSharpCode.TextEditor"
12:36:43.531   383ms    git -c diff.submodule=short -c diff.noprefix=false diff --no-color  -- "Externals/NBug"
12:36:43.586   398ms    git -c diff.submodule=short -c diff.noprefix=false diff --no-color  -- "GitExtensionsDoc"
12:36:43.906   148ms    git for-each-ref --sort=-committerdate refs/heads/ --format="%(objectname) %(refname)"
12:36:43.914   143ms    git show-ref --dereference
12:36:44.058    64ms    git remote show
12:36:44.270    77ms    git for-each-ref --sort=-committerdate --format="%(objectname) %(refname)" refs/
12:36:44.352    71ms    git ls-tree v3-ux "GitExtensionsDoc"
12:36:44.437    77ms    git ls-tree upstream/master "GitExtensionsDoc"
12:36:44.514    74ms    git ls-tree origin/master "GitExtensionsDoc"
12:36:44.588    75ms    git ls-tree master "GitExtensionsDoc"
12:36:44.664    66ms    git ls-tree looooooooooooooooooooooooooooooooooooooooooooong "GitExtensionsDoc"
12:36:44.730    67ms    git ls-tree origin/v3-ux "GitExtensionsDoc"
12:36:44.798    78ms    git ls-tree upstream/configdata "GitExtensionsDoc"
12:36:44.877    77ms    git ls-tree upstream/feature/graphperformance "GitExtensionsDoc"
12:36:44.955    64ms    git ls-tree remove-commit-per-user "GitExtensionsDoc"
12:36:45.019    79ms    git ls-tree upstream/release/2.51 "GitExtensionsDoc"
12:36:45.099    71ms    git ls-tree spelling "GitExtensionsDoc"
12:36:45.171    68ms    git ls-tree mstv/fix/manage_stashes "GitExtensionsDoc"
12:36:45.239    66ms    git ls-tree mstv/gitext_browse_icon "GitExtensionsDoc"
12:36:45.326    67ms    git ls-tree RussKie/fix_formremote_hdpi "GitExtensionsDoc"
12:36:45.393    64ms    git ls-tree upstream/fix_build "GitExtensionsDoc"
12:36:45.457    71ms    git ls-tree RussKie/fix_5084_dashboard_categories_cant_collapse "GitExtensionsDoc"
12:36:45.529    67ms    git ls-tree tidy "GitExtensionsDoc"
12:36:45.596    66ms    git ls-tree 2.53.99 "GitExtensionsDoc"
12:36:45.663    73ms    git ls-tree RussKie/fix_4830_inconsistent_branch_ordering "GitExtensionsDoc"
12:36:45.736    66ms    git ls-tree mstv/feature/revisiongrid-tooltips "GitExtensionsDoc"
12:36:45.803    66ms    git ls-tree RussKie/left_panel_tweaks "GitExtensionsDoc"
12:36:45.870    63ms    git ls-tree RussKie/fix_GitExtensionsSettingsPage_layout_alignment "GitExtensionsDoc"
12:36:45.933    66ms    git ls-tree git-executable "GitExtensionsDoc"
12:36:45.999    64ms    git ls-tree origin/git-executable "GitExtensionsDoc"
12:36:46.064    67ms    git ls-tree origin/revision-graph "GitExtensionsDoc"
12:36:46.131    71ms    git ls-tree RussKie/fix_4949_settings_rendering_tweaks "GitExtensionsDoc"
12:36:46.202    74ms    git ls-tree RussKie/Start_page_rebased "GitExtensionsDoc"
12:36:46.277    61ms    git ls-tree RussKie/fix_AddAsMostRecentAsync_should_add_new_path_as_top_entry "GitExtensionsDoc"
12:36:46.338    75ms    git ls-tree sharwell/master "GitExtensionsDoc"
12:36:46.414    63ms    git ls-tree RussKie/Migrate_categorised_local_repositories "GitExtensionsDoc"
12:36:46.478    64ms    git ls-tree RussKie/fix_4855_Init_wrong_folder2 "GitExtensionsDoc"
12:36:46.542    72ms    git ls-tree RussKie/fix_4855_Init_wrong_folder "GitExtensionsDoc"
12:36:46.615    73ms    git ls-tree mstv/master "GitExtensionsDoc"
12:36:46.689    64ms    git ls-tree sharwell/vsix-commands "GitExtensionsDoc"
12:36:46.753    66ms    git ls-tree origin/various "GitExtensionsDoc"
12:36:46.820    74ms    git ls-tree various "GitExtensionsDoc"
12:36:46.894    69ms    git ls-tree sharwell/async-commands "GitExtensionsDoc"
12:36:46.963    65ms    git ls-tree sharwell/multiline-processing "GitExtensionsDoc"
12:36:47.029    65ms    git ls-tree sharwell/vs-threading "GitExtensionsDoc"
12:36:47.094    64ms    git ls-tree RussKie/Ribbon "GitExtensionsDoc"
12:36:47.159    68ms    git ls-tree origin/plugins "GitExtensionsDoc"
12:36:47.228    67ms    git ls-tree plugins "GitExtensionsDoc"
12:36:47.296    64ms    git ls-tree RussKie/Update_readme "GitExtensionsDoc"
12:36:47.360    72ms    git ls-tree sharwell/appveyor-results "GitExtensionsDoc"
12:36:47.433    66ms    git ls-tree sharwell/wildcard-includes "GitExtensionsDoc"
12:36:47.500    67ms    git ls-tree sharwell/checkpoint/vs-threading "GitExtensionsDoc"
12:36:47.567    69ms    git ls-tree fix-4516 "GitExtensionsDoc"
12:36:47.637    67ms    git ls-tree async "GitExtensionsDoc"
12:36:47.704    65ms    git ls-tree 2.52 "GitExtensionsDoc"
12:36:47.769    66ms    git ls-tree 2.51 "GitExtensionsDoc"
12:36:47.836    71ms    git ls-tree mstv/release/2.51 "GitExtensionsDoc"
12:36:47.907    70ms    git ls-tree mstv/revert-4474-avoid-new-threads "GitExtensionsDoc"
12:36:47.977    67ms    git ls-tree origin/language-features "GitExtensionsDoc"
12:36:48.045    69ms    git ls-tree language-features "GitExtensionsDoc"
12:36:48.114    64ms    git ls-tree origin/release/2.51 "GitExtensionsDoc"
12:36:48.179    65ms    git ls-tree release/2.51 "GitExtensionsDoc"
12:36:48.244    70ms    git ls-tree RussKie/4458_unable_build_VSIX_projects "GitExtensionsDoc"
12:36:48.314    67ms    git ls-tree origin/configdata "GitExtensionsDoc"
12:36:48.382    67ms    git ls-tree mstv/configdata "GitExtensionsDoc"
12:36:48.449    75ms    git ls-tree RussKie/LayoutRenderers "GitExtensionsDoc"
12:36:48.524    69ms    git ls-tree v2.51.RC2 "GitExtensionsDoc"
12:36:48.593    68ms    git ls-tree v2.51.RC1 "GitExtensionsDoc"
12:36:48.661    69ms    git ls-tree RussKie/patch5 "GitExtensionsDoc"
12:36:48.730    69ms    git ls-tree RussKie/refactor_RevisionGrid.RevisionsCellPainting "GitExtensionsDoc"
12:36:48.800    66ms    git ls-tree RussKie/fix_IGitModule_injections "GitExtensionsDoc"
12:36:48.866    70ms    git ls-tree RussKie/refactor_move_state_out_gitmodule "GitExtensionsDoc"
12:36:48.937    68ms    git ls-tree RussKie/move_toolbar-related_code_from_FormBrowse "GitExtensionsDoc"
12:36:49.005    64ms    git ls-tree RussKie/update_readme "GitExtensionsDoc"
12:36:49.070    70ms    git ls-tree RussKie/rework_toolbars "GitExtensionsDoc"
12:36:49.140    67ms    git ls-tree 2.50.99.19 "GitExtensionsDoc"
12:36:49.207    67ms    git ls-tree RussKie/3897_commit_message_template_file_not_found "GitExtensionsDoc"
12:36:49.275    66ms    git ls-tree upstream/release/2.50 "GitExtensionsDoc"
12:36:49.342    70ms    git ls-tree origin/release/2.50 "GitExtensionsDoc"
12:36:49.412    63ms    git ls-tree mstv/release/2.50 "GitExtensionsDoc"
12:36:49.476    68ms    git ls-tree v2.50.02 "GitExtensionsDoc"
12:36:49.544    75ms    git ls-tree RussKie/feat_start_page_Mono "GitExtensionsDoc"
12:36:49.619    70ms    git ls-tree RussKie/add_and_refactor_diffmerge_tools "GitExtensionsDoc"
12:36:49.690    66ms    git ls-tree sharwell/package-restore "GitExtensionsDoc"
12:36:49.756    68ms    git ls-tree RussKie/refactor_AppSettings "GitExtensionsDoc"
12:36:49.824    67ms    git ls-tree v2.50.01 "GitExtensionsDoc"
12:36:49.892    65ms    git ls-tree RussKie/commit_info_layout "GitExtensionsDoc"
12:36:49.957    70ms    git ls-tree v2.50 "GitExtensionsDoc"
12:36:50.028    67ms    git ls-tree 2.50.99.17 "GitExtensionsDoc"
12:36:50.095    66ms    git ls-tree v2.50RC2 "GitExtensionsDoc"
12:36:50.162    70ms    git ls-tree 2.50.99.16 "GitExtensionsDoc"
12:36:50.232    67ms    git ls-tree v2.50RC1 "GitExtensionsDoc"
12:36:50.300    64ms    git ls-tree 2.50.99.14 "GitExtensionsDoc"
12:36:50.364    70ms    git ls-tree upstream/release/2.49 "GitExtensionsDoc"
12:36:50.434    68ms    git ls-tree origin/release/2.49 "GitExtensionsDoc"
12:36:50.503    70ms    git ls-tree mstv/release/2.49 "GitExtensionsDoc"
12:36:50.573    72ms    git ls-tree 2.50.99.13 "GitExtensionsDoc"
12:36:50.646    67ms    git ls-tree 2.49.99.12 "GitExtensionsDoc"
12:36:50.712    68ms    git ls-tree 2.49.99.11 "GitExtensionsDoc"
12:36:50.781    77ms    git ls-tree upstream/DPIAware "GitExtensionsDoc"
12:36:50.859    67ms    git ls-tree origin/DPIAware "GitExtensionsDoc"
12:36:50.926    62ms    git ls-tree mstv/DPIAware "GitExtensionsDoc"
12:36:50.989    72ms    git ls-tree RussKie/master "GitExtensionsDoc"
12:36:51.062    64ms    git ls-tree v2.49.03 "GitExtensionsDoc"
12:36:51.126    62ms    git ls-tree v2.49.02 "GitExtensionsDoc"
12:36:51.189    67ms    git ls-tree v2.49.01 "GitExtensionsDoc"
12:36:51.256    67ms    git ls-tree upstream/mono "GitExtensionsDoc"
12:36:51.323    62ms    git ls-tree origin/mono "GitExtensionsDoc"
12:36:51.385    66ms    git ls-tree mstv/mono "GitExtensionsDoc"
12:36:51.452    68ms    git ls-tree 2.49.99.10 "GitExtensionsDoc"
12:36:51.520    63ms    git ls-tree RussKie/fix_cancel_reload_settings "GitExtensionsDoc"
12:36:51.583    70ms    git ls-tree RussKie/fix_optimise_settings_page_load "GitExtensionsDoc"
12:36:51.654    66ms    git ls-tree 2.49.99.9b "GitExtensionsDoc"
12:36:51.721    64ms    git ls-tree 2.49.99.8 "GitExtensionsDoc"
12:36:51.785    67ms    git ls-tree sharwell/release/2.49 "GitExtensionsDoc"
12:36:51.853    69ms    git ls-tree upstream/addin_installer "GitExtensionsDoc"
12:36:51.922    62ms    git ls-tree origin/addin_installer "GitExtensionsDoc"
12:36:51.984    64ms    git ls-tree mstv/addin_installer "GitExtensionsDoc"
12:36:52.048    68ms    git ls-tree 2.49.99.7 "GitExtensionsDoc"
12:36:52.117    63ms    git ls-tree 2.49.99.6 "GitExtensionsDoc"
12:36:52.180    74ms    git ls-tree 2.49.99.6RC "GitExtensionsDoc"
12:36:52.254    70ms    git ls-tree upstream/release/2.48 "GitExtensionsDoc"
12:36:52.324    65ms    git ls-tree origin/release/2.48 "GitExtensionsDoc"
12:36:52.389    64ms    git ls-tree mstv/release/2.48 "GitExtensionsDoc"
12:36:52.454    72ms    git ls-tree origin/feature/left-panel "GitExtensionsDoc"
12:36:52.526    65ms    git ls-tree mstv/feature/left-panel "GitExtensionsDoc"
12:36:52.591    67ms    git ls-tree 2.49.99.5 "GitExtensionsDoc"
12:36:52.659    70ms    git ls-tree 2.49.99.4 "GitExtensionsDoc"
12:36:52.729    65ms    git ls-tree 2.49.99.3 "GitExtensionsDoc"
12:36:52.794    64ms    git ls-tree 2.49.99.2 "GitExtensionsDoc"
12:36:52.858    75ms    git ls-tree 2.49.99.1 "GitExtensionsDoc"
12:36:52.935    73ms    git ls-tree 2.49a1_MOD "GitExtensionsDoc"
12:36:53.008    63ms    git ls-tree sharwell/consolidate-solutions "GitExtensionsDoc"
12:36:53.072    68ms    git ls-tree sharwell/vsix-updates "GitExtensionsDoc"
12:36:53.141    68ms    git ls-tree RussKie/release/2.48 "GitExtensionsDoc"
12:36:53.209    65ms    git ls-tree upstream/PR_PerformanceFix "GitExtensionsDoc"
12:36:53.275    71ms    git ls-tree origin/PR_PerformanceFix "GitExtensionsDoc"
12:36:53.346    70ms    git ls-tree mstv/PR_PerformanceFix "GitExtensionsDoc"
12:36:53.416    65ms    git ls-tree RussKie/PR_PerformanceFix "GitExtensionsDoc"
12:36:53.482    70ms    git ls-tree RussKie/configdata "GitExtensionsDoc"
12:36:53.552    72ms    git ls-tree upstream/feature/LibGit2SharpPerformance "GitExtensionsDoc"
12:36:53.625    69ms    git ls-tree origin/feature/LibGit2SharpPerformance "GitExtensionsDoc"
12:36:53.695    67ms    git ls-tree mstv/feature/LibGit2SharpPerformance "GitExtensionsDoc"
12:36:53.762    70ms    git ls-tree RussKie/feature/LibGit2SharpPerformance "GitExtensionsDoc"
12:36:53.833    65ms    git ls-tree upstream/LibGit2Sharp "GitExtensionsDoc"
12:36:53.899    65ms    git ls-tree origin/LibGit2Sharp "GitExtensionsDoc"
12:36:53.964    66ms    git ls-tree mstv/LibGit2Sharp "GitExtensionsDoc"
12:36:54.030    64ms    git ls-tree RussKie/LibGit2Sharp "GitExtensionsDoc"
12:36:54.095    62ms    git ls-tree RussKie/feature/left-panel "GitExtensionsDoc"
12:36:54.158    69ms    git ls-tree upstream/feature/left-panel-filter "GitExtensionsDoc"
12:36:54.227    62ms    git ls-tree origin/feature/left-panel-filter "GitExtensionsDoc"
12:36:54.289    66ms    git ls-tree mstv/feature/left-panel-filter "GitExtensionsDoc"
12:36:54.356    69ms    git ls-tree RussKie/feature/left-panel-filter "GitExtensionsDoc"
12:36:54.425    62ms    git ls-tree upstream/feature/spellchecker "GitExtensionsDoc"
12:36:54.488    64ms    git ls-tree origin/feature/spellchecker "GitExtensionsDoc"
12:36:54.552    72ms    git ls-tree mstv/feature/spellchecker "GitExtensionsDoc"
12:36:54.625    66ms    git ls-tree RussKie/feature/spellchecker "GitExtensionsDoc"
12:36:54.691    64ms    git ls-tree 2.47.3 "GitExtensionsDoc"
12:36:54.756    66ms    git ls-tree 2.47.2 "GitExtensionsDoc"
12:36:54.822    65ms    git ls-tree 2.47.1 "GitExtensionsDoc"
12:36:54.887    62ms    git ls-tree 2.47 "GitExtensionsDoc"
12:36:54.950    61ms    git ls-tree upstream/feature/perMonitorDPI "GitExtensionsDoc"
12:36:55.011    78ms    git ls-tree origin/feature/perMonitorDPI "GitExtensionsDoc"
12:36:55.089    68ms    git ls-tree mstv/feature/perMonitorDPI "GitExtensionsDoc"
12:36:55.157    66ms    git ls-tree RussKie/feature/perMonitorDPI "GitExtensionsDoc"
12:36:55.224    67ms    git ls-tree sharwell/configdata "GitExtensionsDoc"
12:36:55.291    64ms    git ls-tree sharwell/gh-pages "GitExtensionsDoc"
12:36:55.356    66ms    git ls-tree 2.46 "GitExtensionsDoc"
12:36:55.422    67ms    git ls-tree 2.45 "GitExtensionsDoc"
12:36:55.490    66ms    git ls-tree 2.44 "GitExtensionsDoc"
12:36:55.556    71ms    git ls-tree 2.43 "GitExtensionsDoc"
12:36:55.627    69ms    git ls-tree 2.42 "GitExtensionsDoc"
12:36:55.696    66ms    git ls-tree 2.41 "GitExtensionsDoc"
12:36:55.763    66ms    git ls-tree 2.40 "GitExtensionsDoc"
12:36:55.829    69ms    git ls-tree 2.33 "GitExtensionsDoc"
12:36:55.898    66ms    git ls-tree 2.32 "GitExtensionsDoc"
12:36:55.965    64ms    git ls-tree 2.31 "GitExtensionsDoc"
12:36:56.029    64ms    git ls-tree 2.30 "GitExtensionsDoc"
12:36:56.094    63ms    git ls-tree 2.29 "GitExtensionsDoc"
12:36:56.157    61ms    git ls-tree 2.28 "GitExtensionsDoc"
12:36:56.218    61ms    git ls-tree 2.27 "GitExtensionsDoc"
12:36:56.279    66ms    git ls-tree 2.25 "GitExtensionsDoc"
12:36:56.346    64ms    git ls-tree 2.24 "GitExtensionsDoc"
12:36:56.410    62ms    git ls-tree 2.23 "GitExtensionsDoc"
12:36:56.473    64ms    git ls-tree 2.22 "GitExtensionsDoc"
12:36:56.539    71ms    git ls-tree 2.17 "GitExtensionsDoc"
12:36:56.611    65ms    git ls-tree 2.16 "GitExtensionsDoc"
12:36:56.676    63ms    git ls-tree 2.15 "GitExtensionsDoc"
12:36:56.740    66ms    git ls-tree 2.12 "GitExtensionsDoc"
12:36:56.806    68ms    git ls-tree 2.11 "GitExtensionsDoc"
12:36:56.874    76ms    git ls-tree 2.10 "GitExtensionsDoc"
12:36:56.951    68ms    git ls-tree master_Net2.0 "GitExtensionsDoc"
12:36:57.020    63ms    git ls-tree 2.08 "GitExtensionsDoc"
12:36:57.083    70ms    git ls-tree 2.07 "GitExtensionsDoc"
12:36:57.154    73ms    git ls-tree 2.06 "GitExtensionsDoc"
12:36:57.227    66ms    git ls-tree 2.05 "GitExtensionsDoc"
12:36:57.293    64ms    git ls-tree 2.04 "GitExtensionsDoc"
12:36:57.357    70ms    git ls-tree 2.03 "GitExtensionsDoc"
12:36:57.428    64ms    git ls-tree 2.02 "GitExtensionsDoc"
12:36:57.493    65ms    git ls-tree 2.01 "GitExtensionsDoc"
12:36:57.558    75ms    git ls-tree 2.00 "GitExtensionsDoc"
12:36:57.634    64ms    git ls-tree 1.99 "GitExtensionsDoc"
12:36:57.698    67ms    git ls-tree 1.98 "GitExtensionsDoc"
12:36:57.765    71ms    git ls-tree 1.97 "GitExtensionsDoc"
12:36:57.836    65ms    git ls-tree 1.96 "GitExtensionsDoc"
12:36:57.902    68ms    git ls-tree 1.95 "GitExtensionsDoc"
12:36:57.970    71ms    git ls-tree 1.93 "GitExtensionsDoc"
12:36:58.041    65ms    git ls-tree 1.92 "GitExtensionsDoc"
12:36:58.107    66ms    git ls-tree 1.91 "GitExtensionsDoc"
12:36:58.174    70ms    git ls-tree 1.90 "GitExtensionsDoc"
12:36:58.244    65ms    git ls-tree 1.89 "GitExtensionsDoc"
12:36:58.310    67ms    git ls-tree 1.88 "GitExtensionsDoc"
12:36:58.377    72ms    git ls-tree 1.87 "GitExtensionsDoc"
12:36:58.449    66ms    git ls-tree 1.86 "GitExtensionsDoc"
12:36:58.516    69ms    git ls-tree 1.85 "GitExtensionsDoc"
12:36:58.585    77ms    git ls-tree 1.84 "GitExtensionsDoc"
12:36:58.662    66ms    git ls-tree 1.83 "GitExtensionsDoc"
12:36:58.728    65ms    git ls-tree 1.82 "GitExtensionsDoc"
12:36:58.794    66ms    git ls-tree 1.77 "GitExtensionsDoc"
12:36:58.861    64ms    git ls-tree 1.75 "GitExtensionsDoc"
12:36:58.925    67ms    git ls-tree 1.74 "GitExtensionsDoc"
12:36:58.992    74ms    git ls-tree 1.73 "GitExtensionsDoc"
12:36:59.066    65ms    git ls-tree 1.72 "GitExtensionsDoc"
12:36:59.132    64ms    git ls-tree 1.71 "GitExtensionsDoc"
12:36:59.196    79ms    git ls-tree 1.70 "GitExtensionsDoc"
12:36:59.275    65ms    git ls-tree 1.69 "GitExtensionsDoc"
12:36:59.340    68ms    git ls-tree 1.68 "GitExtensionsDoc"
12:36:59.409    64ms    git ls-tree 1.67 "GitExtensionsDoc"
12:36:59.473    68ms    git ls-tree 1.65 "GitExtensionsDoc"
12:36:59.541    71ms    git ls-tree 1.64 "GitExtensionsDoc"
12:36:59.612    72ms    git ls-tree 1.63 "GitExtensionsDoc"
12:36:59.685    71ms    git ls-tree 1.62 "GitExtensionsDoc"
12:36:59.757    67ms    git ls-tree 1.61 "GitExtensionsDoc"
12:36:59.824    65ms    git ls-tree 1.60 "GitExtensionsDoc"
12:36:59.890    69ms    git ls-tree 1.59 "GitExtensionsDoc"
12:36:59.959    67ms    git ls-tree 1.58 "GitExtensionsDoc"
12:37:00.026    65ms    git ls-tree 1.57 "GitExtensionsDoc"
12:37:00.091    71ms    git ls-tree 1.56 "GitExtensionsDoc"
12:37:00.162    64ms    git ls-tree 1.55 "GitExtensionsDoc"
12:37:00.228    65ms    git ls-tree 1.54 "GitExtensionsDoc"
12:37:00.293    69ms    git ls-tree 1.53 "GitExtensionsDoc"
12:37:00.362    64ms    git ls-tree 1.52 "GitExtensionsDoc"
12:37:00.427    66ms    git ls-tree 1.51 "GitExtensionsDoc"
12:37:00.494    74ms    git ls-tree 1.50 "GitExtensionsDoc"
12:37:00.569    68ms    git ls-tree 1.49 "GitExtensionsDoc"
12:37:00.637    68ms    git ls-tree 1.48 "GitExtensionsDoc"
12:37:00.705    70ms    git ls-tree 1.46 "GitExtensionsDoc"
12:37:00.776    65ms    git ls-tree 1.45 "GitExtensionsDoc"
12:37:00.841    68ms    git ls-tree 1.44 "GitExtensionsDoc"
12:37:00.909    69ms    git ls-tree 1.43 "GitExtensionsDoc"
12:37:00.978    67ms    git ls-tree 1.42 "GitExtensionsDoc"
12:37:01.045    68ms    git ls-tree 1.41 "GitExtensionsDoc"
12:37:01.113    70ms    git ls-tree 1.40 "GitExtensionsDoc"
12:37:01.184    66ms    git ls-tree 1.38 "GitExtensionsDoc"
12:37:01.250    65ms    git ls-tree 1.37 "GitExtensionsDoc"
12:37:01.316    73ms    git ls-tree 1.36 "GitExtensionsDoc"
12:37:01.390    69ms    git ls-tree 1.35 "GitExtensionsDoc"
12:37:01.459    63ms    git ls-tree 1.30 "GitExtensionsDoc"
12:37:01.522    66ms    git ls-tree 1.28 "GitExtensionsDoc"
12:37:01.589    71ms    git ls-tree 1.27 "GitExtensionsDoc"
12:37:01.660    64ms    git ls-tree 1.26 "GitExtensionsDoc"
12:37:01.724    67ms    git ls-tree 1.25 "GitExtensionsDoc"
12:37:01.792    68ms    git ls-tree 1.21 "GitExtensionsDoc"
12:37:01.860    68ms    git ls-tree 1.08 "GitExtensionsDoc"
12:37:01.928    67ms    git ls-tree 1.06 "GitExtensionsDoc"
12:37:01.996    71ms    git ls-tree 0.92 "GitExtensionsDoc"
12:37:02.067    65ms    git ls-tree 0.90 "GitExtensionsDoc"
12:37:02.133    65ms    git ls-tree first-commit "GitExtensionsDoc"
12:37:02.198    69ms    git ls-tree v2.51.04 "GitExtensionsDoc"
12:37:02.267    65ms    git ls-tree v2.51.03 "GitExtensionsDoc"
12:37:02.332    65ms    git ls-tree v2.51.02 "GitExtensionsDoc"
12:37:02.397    68ms    git ls-tree v2.51.01 "GitExtensionsDoc"
12:37:02.466    66ms    git ls-tree v2.51 "GitExtensionsDoc"
12:37:02.532    88ms    git ls-tree v2.49RC2 "GitExtensionsDoc"
12:37:02.620   104ms    git ls-tree v2.49RC1 "GitExtensionsDoc"
12:37:02.725    80ms    git ls-tree v2.49 "GitExtensionsDoc"
12:37:02.805    62ms    git ls-tree v2.48RC1 "GitExtensionsDoc"
12:37:02.868    67ms    git ls-tree v2.48.05 "GitExtensionsDoc"
12:37:02.935    69ms    git ls-tree v2.48.04 "GitExtensionsDoc"
12:37:03.005    65ms    git ls-tree v2.48.03 "GitExtensionsDoc"
12:37:03.070    67ms    git ls-tree v2.48.02 "GitExtensionsDoc"
12:37:03.138    66ms    git ls-tree v2.48 "GitExtensionsDoc"
12:37:03.204    66ms    git ls-tree 2.09 "GitExtensionsDoc"
12:37:03.529   103ms    git ls-files -z --unmerged
12:37:03.537    95ms    git rev-parse --git-common-dir
12:37:03.537   164ms    git rev-parse --git-common-dir
12:37:03.537   152ms    git rev-parse --git-common-dir
12:37:03.537   134ms    git rev-parse --git-common-dir
12:37:03.537   125ms    git rev-parse --git-common-dir
12:37:03.632   205ms    git -c diff.submodule=short -c diff.noprefix=false diff --no-color  -- "Externals/conemu-inside"
12:37:03.663   221ms    git -c diff.submodule=short -c diff.noprefix=false diff --no-color  -- "GitExtensionsDoc"
12:37:03.671   207ms    git -c diff.submodule=short -c diff.noprefix=false diff --no-color  -- "Externals/NBug"
12:37:03.689   202ms    git -c diff.submodule=short -c diff.noprefix=false diff --no-color  -- "Externals/ICSharpCode.TextEditor"
12:37:03.702   200ms    git -c diff.submodule=short -c diff.noprefix=false diff --no-color  -- "Externals/Git.hub"
12:37:04.003    80ms    git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none --ignored
12:37:04.028    81ms    git for-each-ref --sort=-committerdate --sort=-taggerdate --format="%(refname)" refs/
12:37:04.102   135ms    git branch --contains 6bd3b036fc5718a51a0d27cde134c7019798c3ce
12:37:04.105   112ms    git tag --contains 6bd3b036fc5718a51a0d27cde134c7019798c3ce
12:37:04.108   109ms    git describe --tags --first-parent --abbrev=40 6bd3b036fc5718a51a0d27cde134c7019798c3ce
```
</details>

(Aside: I am doing a general review of locking between the threads that collaborate to load and display revisions which will address this problem and others like it.)

**What is the expected behavior?**

The UI does not block.

**Environment you encounter the issue:**

- GitExtensions version: master after #5087.

### PR DESCRIPTION
**Pull request by drewnoakes**
Fixes #5166

Refactor in ef2e4794cad2b755a984c6bb592027c17b6cf966 broke this. There was a missing `!`. This change reuses an existing extension method to keep things simple.
 
What did I do to test the code and ensure quality:
- Manual testing

Has been tested on (remove any that don't apply):
- GIT 2.18
- Windows 10

### CODE REVIEW

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 1]
```diff
@@ -1227,18 +1227,12 @@ private void OnGridViewMouseDown(object sender, MouseEventArgs e)
             }
         }
 
+        [ContractAnnotation("=>false,spi:null")]
+        [ContractAnnotation("=>true,spi:notnull")]
         internal bool TryGetSuperProjectInfo(out SuperProjectInfo spi)
         {
-            if (_superprojectCurrentCheckout.Task.IsCompleted)
```
Comment (drewnoakes) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs]: This condition should have been negated. `CompletedOrDefault` has equivalent implementation.
