### PR TITLE
Fix "Current unstaged changes" and "Commit index"

### LINKED ISSUE #5127: A number of changed files on Commit button is always '2'
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

A number of changed files on Commit button is always '2' irrespective whether you have them or not.

commit

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

In my case it reproduces in every repository I have. I tried to reset settings by deleting C:\Users\<User>\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings but the issue is still there.

**What is the expected behavior?**

A number of changed files on Commit button should reflect an actual number of changed files in repository.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.03
- GIT version: 2.18
- OS version: Windows 10 x64
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

2.51.02

### PR DESCRIPTION
**Pull request by mjpap**
Fixes #5127 

The previous commit of this file introduced the bug that the status command was omitted from the command string if the --no-optional-locks option was added. This resulted in wrong counts of "Current unstaged changes" and "Commit index" (always 1).

### CODE REVIEW

File: GitCommands/Git/GitCommandHelpers.cs [hunk 1]
```diff
@@ -857,7 +857,7 @@ public static string CleanUpCmd(bool dryrun, bool directories, bool nonignored,
         public static string GetAllChangedFilesCmd(bool excludeIgnoredFiles, UntrackedFilesMode untrackedFiles, IgnoreSubmodulesMode ignoreSubmodules = IgnoreSubmodulesMode.None, bool noLocks = false)
         {
             StringBuilder stringBuilder = new StringBuilder( 
-                noLocks && VersionInUse.SupportNoOptionalLocks ? "--no-optional-locks" : ""
+                (noLocks && VersionInUse.SupportNoOptionalLocks ? "--no-optional-locks " : "")
```
Comment (gerhardol) [inline GitCommands/Git/GitCommandHelpers.cs]: Normally, we do not want extra spaces like this, but this is done better in master, using the ArgumentBuilder.

**Comment by RussKie** [comment]
The test build https://ci.appveyor.com/api/buildjobs/m4nmwfcjscrmxo8v/artifacts/GitExtensions-2.51.01.2909-Mono.zip
I plan to publish 2.51.04 within few weeks

**Comment by RussKie** [comment]
@dmjanssen please provide more info: _Help > About > Copy_ env info and what exactly you are seeing

**Comment by RussKie** [comment]
Please raise a new issue if you believe what you're experiencing is a bug

**Comment by dmjanssen** [comment]
See https://github.com/gitextensions/gitextensions/issues/5947
