### PR TITLE
CommitInfo: Do not try to parse commit-hash look-alike inside e-mail address

### LINKED ISSUE #10736: Selecting commit runs `git rev-parse` for every `Co-authored-by` in a commit message
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.2.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.14
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

### Issue description

In the GitHub repo I work in, merges often contain many commits, and merge commit messages can be large. These messages typically include a lot of [GitHub's `Co-authored-by` specifiers](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). In many cases, when inserted by GitHub during certain GitHub actions, the email address in a `Co-authored-by` begins with a numeric GitHub ID. The full line looks like:

`Co-authored-by: Some Person <123456789+username@users.noreply.github.com>`

What I'm seeing is that when I select a commit in the UI, the Git Command Log shows an instance of `git rev-parse --verify --quiet 123456789^{commit}` being run for every such line in the commit message. They all run serially and take ~50-200 ms a piece as indicated by the log. Relatively large merge commit messages in the repo I work in thus hang the UI for a full minute or two every time I select them.

### Steps to reproduce

Select a commit in the UI with a message containing a large number of GitHub `Co-authored-by` lines with numeric-prefix email address values. The main window will become unresponsive for a long period of time.

### Did this work in previous version of GitExtensions?

Not sure.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10736

## Proposed changes

- `Sha1HashShortRegex`: Do not match e-mail address
- CommitInfo: Parse commit hashes in commit message asynchronously, namely the call `commitDataBodyRenderer.Render()`

## Test methodology 

- improve and extend existing testcase

## Test environment(s) 

- Git Extensions 33.33.33
- Build 8f4b36162c134ceb0a493a000e5d3a400da40aa2
- Git 2.39.2.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — COMMENTED** [review]
May we add some tests?

File: Plugins/GitUIPluginInterfaces/GitRevision.cs [hunk 1]
```diff
@@ -19,7 +19,7 @@ public sealed class GitRevision : IGitItem, INotifyPropertyChanged
         public const string CombinedDiffGuid = "3333333333333333333333333333333333333333";
 
         public static readonly Regex Sha1HashRegex = new(@"^[a-f\d]{40}$", RegexOptions.Compiled);
-        public static readonly Regex Sha1HashShortRegex = new(@"\b[a-f\d]{7,40}\b", RegexOptions.Compiled);
+        public static readonly Regex Sha1HashShortRegex = new(@"\b[a-f\d]{7,40}\b(?![^@ \t\r\n]*@)", RegexOptions.Compiled);
```
Comment (gerhardol) [inline Plugins/GitUIPluginInterfaces/GitRevision.cs:22]: Same change should be applied to `Sha1HashRegex` (there is not even a check for boundary after 40 chars there).
the regexes should be merged too (result to check the length).
 ```suggestion
        public static readonly Regex Sha1HashShortRegex = new(@"\b[a-f\d]{7,40}\b(?![^@\s]*@)", RegexOptions.Compiled);
```

**Review by gerhardol — COMMENTED** [review]
+1
Good job

File: Plugins/GitUIPluginInterfaces/GitRevision.cs (hunk 1 above)
Comment (mstv) [reply Plugins/GitUIPluginInterfaces/GitRevision.cs]: I took over the simplification `\s`.

> Same change should be applied to Sha1HashRegex (there is not even a check for boundary after 40 chars there).

Though `Sha1HashRegex` checks the entire string already: `^...$`.

**Review by RussKie — APPROVED** [review]
Looks sensible. Haven't run.
