### PR TITLE
Rebase: fix accuracy of data in list of commits displayed

### LINKED ISSUE #11179: Rebase dialog shows skipped commits as "pick"
### Environment

- GitExtensions version: 4.1

### Issue description

image

### Steps to reproduce

- interactively rebase a branch with conflicts
- drop first commits (or skip them by deleting the lines)
image

### Did this work in previous version of GitExtensions?

I guess no

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by pmiossec**
by using "done" file for commits already processed
and "git-rebase-todo" for what will be **really** done next.

because "git-rebase-todo.backup" content is not accurate
(it contains what was presented to user in interactive rebase
**before** user choose which actions to do on commits)

it fixes "action" column value that was not accurate
and commits that was reordered.

fixes #11179

### Before

See reporting issue #11179 

### After

image

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build f0a4b7d360bbaae54b0d9ea7680e7866c85df53b
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.21
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
Only last commit belong to the PR...

File: GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -2143,42 +2144,53 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
-                string? currentCommitShortHash = File.Exists(CurrentFilePath) ? File.ReadAllText(CurrentFilePath).Trim() : null;
-                var isCurrentFound = false;
-                foreach (string todoCommit in todoCommits)
-                {
-                    if (todoCommit.StartsWith(commentChar))
-                    {
-                        continue;
-                    }
+            string doneFile = DoneFilePath;
+            string[]? doneCommits = File.Exists(doneFile) ? File.ReadAllText(doneFile).Trim().Split(Delimiters.LineFeedAndCarriageReturn, StringSplitOptions.RemoveEmptyEntries) : Array.Empty<string>();
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:2153]:
```suggestion
            string[] doneCommits = (File.Exists(doneFile)
                ? File.ReadAllText(doneFile).Trim().Split(Delimiters.LineFeedAndCarriageReturn, StringSplitOptions.RemoveEmptyEntries)
                : null)
                ?? Array.Empty<string>();
```

**Review by mstv — APPROVED** [review]
👍 The implementation looks easier than feared.

File: GitCommands/Git/GitModule.cs [hunk 2]
```diff
@@ -2148,12 +2149,15 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
+
             string commentChar = EffectiveConfigFile.GetString("core.commentChar", "#");
 
             // Filter comment lines and keep only lines containing at least 3 columns
             // (action, commit hash and commit subject -- that could contains space and be cut in more --)
             // ex: pick e0d861716540aa1ac83eaa2790ba5e79988b9489 this is the commit subject
-            string[][] todoCommitsInfos = todoCommits.Where(l => !l.StartsWith(commentChar))
+            string[][] commitsInfos = doneCommits.Concat(todoCommits).Where(l => !l.StartsWith(commentChar))
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs:2160]: This should probably be l.Trim() to remove whitespace

**Review by gerhardol — COMMENTED** [review]
+1

File: GitCommands/Git/GitModule.cs [hunk 3]
```diff
@@ -2131,15 +2131,15 @@ private string GetNextRebasePatch()
...
+        private string RebaseTodoFilePath => GetRebaseDir() + "git-rebase-todo";
         private string CurrentFilePath => GetRebaseDir() + "stopped-sha";
 
         public bool InTheMiddleOfInteractiveRebase() => File.Exists(RebaseTodoFilePath);
 
         public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
         {
-            string todoFile = RebaseTodoFilePath;
-            string[]? todoCommits = File.Exists(todoFile) ? File.ReadAllText(todoFile).Trim().Split(Delimiters.LineFeedAndCarriageReturn, StringSplitOptions.RemoveEmptyEntries) : null;
+            string[]? todoCommits = ReadCommitsDataFromRebaseFile(RebaseTodoFilePath);
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:2142]:
```suggestion
            string[] todoCommits = ReadCommitsDataFromRebaseFile(RebaseTodoFilePath);
```

File: GitCommands/Git/GitModule.cs [hunk 4]
```diff
@@ -2148,12 +2148,14 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
                 return patchFiles;
             }
 
+            string[] doneCommits = ReadCommitsDataFromRebaseFile(DoneFilePath) ?? Array.Empty<string>();
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:2151]:
```suggestion
            string[] doneCommits = ReadCommitsDataFromRebaseFile(DoneFilePath);
```

File: GitCommands/Git/GitModule.cs [hunk 5]
```diff
@@ -2212,6 +2214,11 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
             }
 
             return patchFiles;
+
+            string[]? ReadCommitsDataFromRebaseFile(string filePath) =>
+                File.Exists(filePath)
+                ? File.ReadAllText(filePath).Trim().Split(Delimiters.LineFeedAndCarriageReturn, StringSplitOptions.RemoveEmptyEntries)
+                : null;
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:2221]:
```suggestion
            string[] ReadCommitsDataFromRebaseFile(string filePath) =>
                File.Exists(filePath)
                ? File.ReadAllText(filePath).Trim().Split(Delimiters.LineFeedAndCarriageReturn, StringSplitOptions.RemoveEmptyEntries)
                :  Array.Empty<string>();
```

**Review by mstv — APPROVED** [review]

**Review by gerhardol — APPROVED** [review]

**Comment by pmiossec** [comment]
done.

**Review by RussKie — COMMENTED** [review]
👍 
 Any tests we can add?

**Comment by pmiossec** [comment]
> 👍 Any tests we can add?

2 integration tests added. They are complex. Tell me if the intent is clear or if I should put more comment.

File: IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs [hunk 6]
```diff
@@ -0,0 +1,101 @@
...
+            // Create a branch with contents that will conflict on rebase
+            refRepo.CreateBranch("branch2", initialCommit.Hash);
+            refRepo.CheckoutBranch("branch2");
+            string otherFile = "other_file.txt";
+            var commitDone = CreateCommit("branch2: commit that will apply successfully", "other_line1", otherFile);
+            var commitApplying = CreateCommit("branch2: commit that will fail to rebase", "a content that will create a conflict", mainFile);
+            var commitToDo = CreateCommit("branch2: commit todo", "foobar", otherFile);
+
+            // Real git rebase to ensure git rebase file format has not changed
+            var execResult = gitModule.GitExecutable.Execute($"rebase master", throwOnErrorExit: false);
```
Comment (gerhardol) [inline IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs:37]: Should we start preparing for renaming master by using branch1 instead of master?

File: IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs [hunk 7]
```diff
@@ -0,0 +1,101 @@
...
+            content += "line2" + Environment.NewLine;
+            CreateCommit("main: commit2", content, mainFile);
+            content += "line3" + Environment.NewLine;
+            CreateCommit("main: commit3", content, mainFile);
+
+            // Create a branch with contents that will conflict on rebase
+            refRepo.CreateBranch("branch2", initialCommit.Hash);
+            refRepo.CheckoutBranch("branch2");
+            string otherFile = "other_file.txt";
+            var commitDone = CreateCommit("branch2: commit that will apply successfully", "other_line1", otherFile);
```
Comment (gerhardol) [inline IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs:32]: Should we avoid var also in testcases?

**Review by gerhardol — APPROVED** [review]
tests OK for me

**Review by mstv — APPROVED** [review]

File: IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs (hunk 7 above)
Comment (pmiossec) [reply IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs]: Fixed. It was a reamining of an early where I was using a tuple

File: IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs (hunk 6 above)
Comment (pmiossec) [reply IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs]: I used the commit hash instead.

**Review by RussKie — APPROVED** [review]
🚀
