### PR TITLE
FileStatusList handling of parents and selected revision

### LINKED ISSUE #4561: FileStatusList handling of parents and selected revision
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
FileStatusList is use for instance in the Browse Diff tab. The control has support for selected revision and parent, but those are not mandatory set. Also the guid are stored instead instead of GitRevisions (the GitRevision will be needed in a later stage, to get the parents).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Consistently set the selected revision and parent, the FileStatusList users should use that instead of assuming parents from RevisionGrid.GetSelectedRevisions().
This is an refactoring to solve issues like #4387 #4396, also #4485 would have been prevented.
The changes will remove code too.

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
no

### PR DESCRIPTION
**Pull request by gerhardol**
Resolves #4561
Refactoring to consistently use Revision and Parents in FileStatusList
FileStatusList forms should use that instead of assuming parents from RevisionGrid.GetSelectedRevisions().
The changes will remove code too.

Note: This commits enables corrections for #4387 and #4396 etc too.

Changes proposed in this pull request:
 - Refactoring

What did I do to test the code and ensure quality:
 - Manual tests.

Has been tested on (remove any that don't apply):
 - GIT 2.16
 - Windows 10

### CODE REVIEW

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 1]
```diff
@@ -748,8 +748,8 @@ private void LoadUnstagedOutput(IList<GitItemStatus> allChangedFiles)
                 else
                     unStagedFiles.Add(fileStatus);
             }
-            Unstaged.GitItemStatuses = unStagedFiles;
-            Staged.GitItemStatuses = stagedFiles;
+            Unstaged.SetDiffs(new GitRevision(GitRevision.UnstagedGuid), new GitRevision(GitRevision.IndexGuid), unStagedFiles);
+            Staged.SetDiffs(new GitRevision(GitRevision.IndexGuid), new GitRevision("HEAD"), stagedFiles);
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormCommit.cs]: I think we can created static instances for these:
* `new GitRevision(GitRevision.UnstagedGuid)`
* `new GitRevision(GitRevision.IndexGuid)`
* `new GitRevision("HEAD")` (can we?)

This way we can simplify the API.

I've been working on getting all behaviors out of GitRevision and having it as an immutable POCO. So in the target state, once initialised they can't be changed.

Something like the following maybe?

```
    public sealed class GitRevision : IGitItem, INotifyPropertyChanged
    {
        public static readonly GitRevision EmptyRevision = new GitRevision("");
        public static readonly GitRevision HeadRevision = new GitRevision("HEAD");
        public static readonly GitRevision IndexRevision = new GitRevision(IndexGuid);
        public static readonly GitRevision UnstagedRevision = new GitRevision(UnstagedGuid);

```

File: GitUI/UserControls/FileStatusList.cs [hunk 2]
```diff
@@ -17,7 +17,8 @@
 
 namespace GitUI
 {
-    using GitItemsWithParents = IDictionary<string, IList<GitItemStatus>>;
+    //Parents is used as the "first selected" (not always the parent) for GitItemStatus
+    using GitItemsWithParents = IDictionary<GitRevision, IList<GitItemStatus>>;
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]: this doesn't seem to be consistently used, perhaps remove it completely

File: GitUI/UserControls/FileStatusList.cs [hunk 3]
```diff
@@ -552,12 +553,12 @@ public GitItemStatus SelectedItem
...
         [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
         [Browsable(false)]
-        public string SelectedItemParent
+        public GitRevision SelectedItemParent
         {
             get
             {
                 foreach (ListViewItem item in FileStatusListView.SelectedItems)
-                    return (string)item.Group?.Tag;
+                    return (GitRevision)item.Group?.Tag;
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]: I am not sure this is completely safe cast
Perhaps this is better: `return item.Group?.Tag as GitRevision;`?

File: GitUI/UserControls/FileStatusList.cs [hunk 4]
```diff
@@ -570,7 +571,7 @@ public IEnumerable<string> SelectedItemParents
             {
                 return FileStatusListView.SelectedItems.Cast<ListViewItem>()
                     .Where(i => i.Group != null)
-                    .Select(i => (string)i.Group.Tag);
+                    .Select(i => ((GitRevision)i.Group.Tag)?.Guid);
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]: I am not sure this is completely safe cast.
Perhaps the following is better?

```
                return FileStatusListView.SelectedItems.Cast<ListViewItem>()
                     .Where(i => i.Group != null && i.Group.Tag as GitRevision != null)
                     .Select(i => ((GitRevision)i.Group.Tag).Guid);
```

File: GitUI/UserControls/FileStatusList.cs [hunk 5]
```diff
@@ -581,7 +582,7 @@ public IEnumerable<GitItemStatusWithParent> SelectedItemsWithParent
             get
             {
                 return FileStatusListView.SelectedItems.Cast<ListViewItem>()
-                    .Select(i => new GitItemStatusWithParent((GitItemStatus)i.Tag, (string)i.Group?.Tag));
+                    .Select(i => new GitItemStatusWithParent((GitItemStatus)i.Tag, (GitRevision)i.Group?.Tag));
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]: Are we confident these casts are safe?

File: GitUI/UserControls/FileStatusList.cs [hunk 6]
```diff
@@ -1040,91 +1013,85 @@ private int SelectFiles(Regex selctionFilter)
             }
         }
 
-        public void SetDiffs(List<GitRevision> revisions)
+        public void SetDiffs(GitRevision selectedRev=null, GitRevision parentRev=null, IList<GitItemStatus> items=null)
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]: missing spaces, these will create extra noise in StyleCop PRs

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormCommit.cs]: With #4556 we probably should get the GitRevision from RevisionGrid and not create new objects.
(In the current version of #4556, new GitRevision("HEAD") is not permitted.)

File: GitUI/UserControls/FileStatusList.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: This PR enables the possibility to use the parent, not always set before. The use of the parent is in follow up PRs.
I tried to make the PRs possible to review but submitted the complete solution as "wip".

File: GitUI/UserControls/FileStatusList.cs (hunk 3 above)
Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: TAG is (currently) just set as a GitRevision, now always set. But I agree the cast should be changed, it was just a carry over.

File: GitUI/UserControls/FileStatusList.cs (hunk 4 above)
Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: Can change all casts for Tag to be something like this

File: GitUI/UserControls/FileStatusList.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/UserControls/FileStatusList.cs]: As unlikely as it may be, if in some usecase Tag is set to something else - it will break but it may not be apparent straight away...

File: GitUI/UserControls/FileStatusList.cs (hunk 2 above)
Comment (RussKie) [reply GitUI/UserControls/FileStatusList.cs]: My comment was about the type alias `GitItemsWithParents` - in other places in the code `IDictionary<GitRevision, IList<GitItemStatus>>` is still widely used

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 1 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormCommit.cs]: /cc: @drewnoakes thoughts?

File: GitUI/UserControls/FileStatusList.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: Can change to consistently use GitItemsWithParents, IGitItemsWithParents (will have to add that). Or should the alias be removed?

Comment (RussKie) [reply GitUI/UserControls/FileStatusList.cs]: I don't mind either way - as long as it consistent :)

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormCommit.cs]: RevisionGrid is not available for FormCommit right now, will not change now.

**Comment by gerhardol** [comment]
Will rebase and squash if/when approved (then rebase the follow up PRs)

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 1 above)
Comment (drewnoakes) [reply GitUI/CommandsDialogs/FormCommit.cs]: With respect to #4556 restricting GitRevision to ObjectId, it seems like from @gerhardol's comments there that such a change is too restrictive, and I defer to the judgement of those with more experience. My intent is to introduce ObjectId only where it is completely non-controversial to do so, and then see whether it adds any value overall.

Comment (RussKie) [reply GitUI/CommandsDialogs/FormCommit.cs]: I like the idea in general, I think it is a move in a right direction
