### PR TITLE
Let git deny the commit if committer is not specified

### LINKED ISSUE #11366: [NBug] 'C:\Users\mbarry\AppData\Local\Programs\Git\bin\git.exe config --includes --get user.name' returned non-zero exit code.
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.24
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

Exit code: 1
Command: C:\Users\mbarry\AppData\Local\Programs\Git\bin\git.exe
Arguments: config --includes --get user.name
Working directory: C:\Git\DevApps\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 129
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<T>(Func<Task<T>> asyncMethod, JoinableTaskCreationOptions creationOptions) x 2
   at string GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 43
   at string GitCommands.GitModule.GetEffectiveGitSetting(string setting, bool cache) in C:/projects/gitextensions/GitCommands/Git/GitModule.cs:line 2421
   at async void GitUI.CommandsDialogs.FormCommit.UpdateAuthorInfo()+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCommit.cs:line 2726
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

update

### Steps to reproduce

bug after update

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### LINKED ISSUE #11368: Continuous popup if email/name is not set in Commit form
### Environment

- Git Extensions 4.2.0.17539
- Build d3b383c77a3cda85b835c7e6325c0ebb146a8be9
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Follow up to #11366 etc
If email or name is not set when opening GE, you should get a notification in settings. This will not occur if the email/name is set for the repo first opened but not a later repo.

This info is just for info in bottom left and is on activation of the form.
The info was changed in #10843 to show git-log info (not at all or GE config before). Should be included in 4.1.

image

The popup is a normal NBug. As the git-log command is on activation of the form, the popup appears immediately if you Ignore it.
You have to exit the application in NBug (which may be hidden) or task manager.
There are reports that this is a GE error, all NBug are seen as GE issues for some users, all text is not read properly.

* git-log should only get email/name on opening the form, not on activation. The status is only expected to be changed when FormCommit is closed.
* The NBug popup should be replaced with a special popup or rather hide the issue (no email/name is often shown when starting GE and definitely when actually committing so an extra popup is not needed in my opinion).

----

Exit code: 1
Command: wsl
Arguments: -d Ubuntu-22.04 git config --includes --get user.name
Working directory: \\wsl$\Ubuntu-22.04\home\ejgo\gc\GitExtensionsDoc\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 129
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<T>(Func<Task<T>> asyncMethod, JoinableTaskCreationOptions creationOptions) x 2
   at string GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 43
   at string GitCommands.GitModule.GetEffectiveGitSetting(string setting, bool cache) in C:/projects/gitextensions/GitCommands/Git/GitModule.cs:line 2420
   at async void GitUI.CommandsDialogs.FormCommit.UpdateAuthorInfo()+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCommit.cs:line 2725
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

### Steps to reproduce

* Remove user.email and user.name fro global .gitconfig, not in repo config
* Open Commit
* Dismiss the popup

### Did this work in previous version of GitExtensions?

"git-log" added to 4.1 (?)

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11366
Fixes #11368

## Proposed changes

- Let git deny the commit if committer is not specified
  - Let `GetEffectiveGitSetting` return ``null` if the setting is not set
  - Remove `FormCommit.OnActivated` in order to avoid repeated exception popups from the only called function `UpdateAuthorInfo`

### Before

Exception (repeated exceptions unless repeating `Esc`)

### After

image

## Test methodology 

- manual
- adapt affected testcase

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 1]
```diff
@@ -2713,14 +2713,29 @@ private void UpdateAuthorInfo()
             ThreadHelper.FileAndForget(async () =>
                 {
                     // Do not cache results in order to update the info on FormActivate
-                    string userName = Module.GetEffectiveGitSetting(SettingKeyString.UserName, cache: false);
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/FormCommit.cs:2716]: Do not try-catch if the reason is known - in this case git-log return 0 is OK
This is the part of #11146 I approved (the rest of the discussion there just got me loose motivation for GE and a dev in general though).

Could be an option to GetEffectiveGitSetting, but this is currently the only caller.

It is also not necessary to call UpdateAuthorInfo() in OnActivate.

[0001-Do-not-throw-for-git-log-no-key-exists.patch](https://github.com/gitextensions/gitextensions/files/13401403/0001-Do-not-throw-for-git-log-no-key-exists.patch)

**Review by gerhardol — COMMENTED** [review]
-1

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 1 above)
Comment (mstv) [reply GitUI/CommandsDialogs/FormCommit.cs:2716]: Thank you for the patch. I did not think of its availability when I decided to not touch the `ExecutableExtensions.GetOutput()` chain.

> It is also not necessary to call UpdateAuthorInfo() in OnActivate.

The setting could be changed using another app (instance).
But removing `OnActivate` was the easiest way to get rid of repeated exception popups.

**Review by gerhardol — APPROVED** [review]

File: GitCommands/Git/GitModule.cs [hunk 2]
```diff
@@ -2136,10 +2136,19 @@ public string GetEffectiveSetting(string setting)
...
-            return GitExecutable.GetOutput(args, cache: cache ? GitCommandCache : null).Trim();
+            ExecutionResult result = GitExecutable.Execute(args, cache: cache ? GitCommandCache : null, throwOnErrorExit: false);
+
+            // Handle no value set, is error code 1: https://git-scm.com/docs/git-config#_description
+            const int ConfigKeyInvalidOrNotSet = 1;
+            return result.ExitCode switch
+            {
+                ExecutionResult.Success => result.StandardOutput.Trim(),
+                ConfigKeyInvalidOrNotSet => null,
+                _ => throw new ExternalOperationException("git", args.ToString(), WorkingDir, result.ExitCode, new InvalidOperationException("Error getting config value"))
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs:2150]: We'll need to loc the error message.

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 3]
```diff
@@ -2713,8 +2703,8 @@ private void UpdateAuthorInfo()
...
-                    string userEmail = Module.GetEffectiveGitSetting(SettingKeyString.UserEmail, cache: false);
+                    string userName = Module.GetEffectiveGitSetting(SettingKeyString.UserName, cache: false) ?? "USER NOT CONFIGURED";
+                    string userEmail = Module.GetEffectiveGitSetting(SettingKeyString.UserEmail, cache: false) ?? "E-MAIL NOT CONFIGURED";
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormCommit.cs:2707]: I'm not a fan of the screaming strings. Maybe something like this?
```suggestion
                    string userName = Module.GetEffectiveGitSetting(SettingKeyString.UserName, cache: false) ?? "<username not configured>";
                    string userEmail = Module.GetEffectiveGitSetting(SettingKeyString.UserEmail, cache: false) ?? "<email not configured>";
```

**Review by RussKie — APPROVED** [review]

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 1 above)
Comment (vbjay) [reply GitUI/CommandsDialogs/FormCommit.cs:2716]: Look at  the status bar. On activate is on purpose so that the commiter and author info is updated when user activates window because git config could have been executed. It is to make sure user sees up to date info.

File: GitCommands/Git/GitModule.cs (hunk 2 above)
Comment (mstv) [reply GitCommands/Git/GitModule.cs:2150]: I do not think it would be worth to add translation to GitCommands.dll. Anyway, this should be are very rare exception.

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 3 above)
Comment (mstv) [reply GitUI/CommandsDialogs/FormCommit.cs]: changed, but using "/" instead of "<>" which occurs in the e-mail address.

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 1 above)
Comment (mstv) [reply GitUI/CommandsDialogs/FormCommit.cs:2716]: >  It is to make sure user sees up to date info.

As said it is not worth it. If users use another app / instance for changing the settings, they can reopen FormCommit if they wonder whether the settings are in effect or not. That's not that unusual.

File: GitCommands/Git/GitModule.cs (hunk 2 above)
Comment (RussKie) [reply GitCommands/Git/GitModule.cs:2150]: As we're seeing it's not as uncommon :)
But I'm not going to force this, especially, if we want to backport this back to 4.0

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 1 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormCommit.cs:2716]: I agree with @mstv, it's not worth it.

**Comment by RussKie** [comment]
Backport to release/4.0?

**Comment by mstv** [comment]
> Backport to release/4.0?

done

**Comment by RussKie** [comment]
Thank you
