### PR TITLE
Resize also the backup/default avatar image

### LINKED ISSUE #8241: Blame view author avatar column shows black artifacts
## Current behaviour

Blame view author avatar column has strange black artifacts.
The black "wedges" look like some clipped graphical elements.
They resemble to distorted/clipped "inserted block" margin markers of some GUI diff tools.

## Expected behaviour

The black artifacts should not be shown.
If they have a real purpose then they should be displayed correctly, optionally with some tooltips about what they are or at least they should be documented somewhere in the user guide.

## Steps to reproduce

- Select a file with a history containing multiple edits, inserts and deletes by different authors in the "Diff" tab of a commit . The changes should contain hunks of at least 4-5 contiguous lines.
- Open the blame view (using either hotkey "B" or context menu on the file in the list of files of the commit).
- Observe the author avatar column on the left. There are black artifacts present, similar to the ones shown in the attached screenshot.

## Screenshots

blame-view-black-artifacts-in-avatar-column

## Did this work in previous version of GitExtensions

Not checked.

## Environment

Pasted from "About" dialog:

- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.25.0.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by pmiossec**
and keep them in a cache.

Fixes #8241

### Before

image

### After

image

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build 28d1a6ad94bbf5fa375a780931d14c4107e54ce7
- Git 2.25.0.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4180.0
- DPI 168dpi (175% scaling)

### CODE REVIEW

File: GitUI/Avatars/BackupAvatarProvider.cs [hunk 1]
```diff
@@ -29,15 +29,33 @@ public async Task<Image> GetAvatarAsync(string email, string name, int imageSize
...
-                return await _inner.GetAvatarAsync(email, name, imageSize) ?? _backupImage;
+                return await _inner.GetAvatarAsync(email, name, imageSize) ?? BackupImageResized();
             }
             catch
             {
-                return _backupImage;
+                return BackupImageResized();
+            }
+
+            Image BackupImageResized()
```
Comment (RussKie) [inline GitUI/Avatars/BackupAvatarProvider.cs:39]: To confirm, this is always invoked on the main thread, right?
Because if it isn't, we'll need to synchronise it.

Comment (pmiossec) [reply GitUI/Avatars/BackupAvatarProvider.cs:39]: I thought it was because it is the case in the application code. But not in the Gource plugin...
Anyway, fixed.
