### PR TITLE
fix: commit gpgSign Git defaults

### LINKED ISSUE #11931: Commit option "Do not sign commit" commits with git's default setting which could force signing.
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When creating a commit, the Options drop down has 3 options for signing a commit `Do not sign commit`, `Sign with default GPG`, and `Sign with specific GPG`. The default option of `Do not sign commit` actually signs it if git is configured to sign commits by default.

### Steps to reproduce

1. Configure git to sign commits by default. In my configuration this is with `user.signingkey` set to my GPG key, and `commit.gpgsign` set to true.
2. Create a new commit.
3. Check the options and ensure that it is set to "Do not sign commit"
4. Note that the new commit ends up signed.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #11931

## Proposed changes

Commit dialogue "Do not sign commit" should explicitly not set GPG key.
The default is set to "Git default", using the git-config settings.

## Screenshots 

Adding the first option in the dropdown
image

## Test methodology 

tests updated

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — DISMISSED** [review]
LGTM, have not run

File: src/app/GitUI/CommandsDialogs/FormCommit.cs [hunk 1]
```diff
@@ -1408,7 +1408,7 @@ void DoCommit()
                         _commitMessageManager.CommitMessagePath,
                         Module.GetPathForGitExecution,
                         noVerifyToolStripMenuItem.Checked,
-                        gpgSignCommitToolStripComboBox.SelectedIndex > 0,
+                        gpgSignCommitToolStripComboBox.SelectedIndex == 0 ? null : gpgSignCommitToolStripComboBox.SelectedIndex > 0,
```
Comment (mstv) [inline src/app/GitUI/CommandsDialogs/FormCommit.cs:1411]:
```suggestion
                        gpgSignCommitToolStripComboBox.SelectedIndex == 0 ? null : gpgSignCommitToolStripComboBox.SelectedIndex > 1,
```

**Review by mstv — APPROVED** [review]

**Review by RussKie — APPROVED** [review]

**Comment by gerhardol** [comment]
Rephrased the text for the first option
Plan to merge this tomorrow

**Review by mstv — APPROVED** [review]
