### PR TITLE
`RevisionGraph`: Retry `Sort` if it stumbled upon rewritten `Score`

### LINKED ISSUE #10706: [NBug] Unable to sort because the IComparer.Compare() method retur...
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.13
- DPI 216dpi (225% scaling)

### Issue description

```
System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Comparison`1[GitUI.UserControls.RevisionGrid.Graph.RevisionGraphRevision]'.
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   at GitUI.UserControls.RevisionGrid.Graph.RevisionGraph.BuildOrderedNodesCache(Int32 currentRowIndex)
   at GitUI.UserControls.RevisionGrid.Graph.RevisionGraph.GetNodeForRow(Int32 row)
   at GitUI.RevisionGridToolTipProvider.OnCellMouseMove(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellMouseMove(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.UpdateMouseEnteredCell(HitTestInfo hti, MouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I pulled from my repo, which seemed OK, but when I then clicked OK on the final dialog the error came up. Probably related to GitExtensions refreshing the UI for the new content.

I would recommend writing unit tests for the affected comparator code, to ensure strict weak ordering is preserved.

### Steps to reproduce

* open existing working copy of my repo. it shows all remote branches, 3 of which also exist locally for active work.
* press "pull and rebase button" to get the currently checked out and active branch up-to-date with the remote origin. I have no local changes at this point, so nothing actually needs rebasing
* the process runs through and fetches all branches, and pulls changes from my active branch and updates to the branch head
* the dialog stays open, so I need to confirm by clicking OK
* I click OK.
* The exception appears.

This could not be replicated again by following the same steps. Most likely because the second time there was nothing to fetch/pull.

### Did this work in previous version of GitExtensions?

It worked OK in the same version before and after. So the error only occurrs sometimes.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10706

## Proposed changes

- Add a workaround to `RevisionGraph`: Retry `Array.Sort` if it stumbled upon rewritten `Node.Score`

## Screenshots 

N/A

## Test methodology 

- existing unit tests

## Test environment(s) 

- Git Extensions 33.33.33
- Build ad4f39aaeefd9757adeccdfc891d37b9672f8707 (Dirty)
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
@PeterSchuebel, I think this workaround handles the valid exception in a sensible manner. It is built directly based on v4.0.2. So you could use the binaries built by AppVeyor with very low risk - when the CI build is repaired:

@RussKie, you know better which changes have to be overtaken from the master branch to the release/4.0 branch in order to be able to build hotfix PRs again. For errors, refer to https://ci.appveyor.com/project/gitextensions/gitextensions/builds/46202939.

**Comment by RussKie** [comment]
I'll try to have a look over the weekend or early next week.

File: GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs [hunk 1]
```diff
@@ -504,9 +504,20 @@ private RevisionGraphRevision[] BuildOrderedNodesCache(int currentRowIndex)
...
+            // But the scores of the referenced nodes can still be rewritten as a last step.
+            // So if Sort complains, try again.
+            RevisionGraphRevision[] localOrderedNodesCache = _nodes.ToArray();
+            try
+            {
+                Array.Sort(localOrderedNodesCache, (x, y) => x.Score.CompareTo(y.Score));
+            }
+            catch (ArgumentException ex) when (ex.Message.Contains("IComparer.Compare()"))
+            {
+                localOrderedNodesCache = _nodes.ToArray();
```
Comment (pmiossec) [inline GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs:517]: Is it worth to introduce a local function to remove the duplication? It took me some seconds to check if it was really a code duplication...

Comment (mstv) [reply GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs]: I was aware of this and followed the [Rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)).
Though I have found a clearer (no duplication) and safer (cope with multiple rewrites, too) implementation.

**Comment by mstv** [comment]
AppVeyor has built binaries: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/46206117/artifacts

File: GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs [hunk 2]
```diff
@@ -499,21 +499,34 @@ private RevisionGraphRevision[] BuildOrderedNodesCache(int currentRowIndex)
...
-            // rebuilding it.
-            _orderedUntilScore = int.MinValue;
-            _reorder = false;
-
-            // Use a local variable, because the cached list can be reset
-            var localOrderedNodesCache = _nodes.ToArray();
-            Array.Sort(localOrderedNodesCache, (x, y) => x.Score.CompareTo(y.Score));
-            _orderedNodesCache = localOrderedNodesCache;
-            if (localOrderedNodesCache.Length > 0)
+            // The Score of the referenced nodes can still be rewritten.
```
Comment (gerhardol) [inline GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs:502]:
```suggestion
            // The Score of the referenced nodes can be rewritten by another thread.
```

**Review by gerhardol — APPROVED** [review]

**Review by RussKie — APPROVED** [review]
