### PR TITLE
fix(DiffMergeTools): path for diff/merge command

### LINKED ISSUE #11741: Empty path to executable in DiffMergeTool setting
### Environment

- GitExtensions version: 4.2.1.17611 (b0c0b284876b63c52c77195ada82a85bfadbb083)
- GIT version: 2.45.1.windows.1
- OS version: Microsoft Windows NT 10.0.19045.0
- .NET version: 6.0.30

### Issue description

If the `diff`/`merge` tool is NOT in the expected location, the [DiffMergeToolConfigurationManager](https://github.com/gitextensions/gitextensions/blob/fce1fd0e50d87de0ebaabb3ce0c419e5247994bb/GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs#L162) creates an invalid configuation (empty executable string).

A pre-existing command path for that tool `difftool.<tool>.path` should (as far as I understand [Git settings](https://git-scm.com/docs/git-difftool#Documentation/git-difftool.txt---toollttoolgt)) be akin to a [user-supplied path](https://github.com/gitextensions/gitextensions/blob/fce1fd0e50d87de0ebaabb3ce0c419e5247994bb/GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs#L158), not an extension of the default [search path](https://github.com/gitextensions/gitextensions/blob/fce1fd0e50d87de0ebaabb3ce0c419e5247994bb/GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs#L162).

### Steps to reproduce

Have any tool selected that is NOT installed at the [expected locations](https://github.com/gitextensions/gitextensions/blob/fce1fd0e50d87de0ebaabb3ce0c419e5247994bb/GitCommands/DiffMergeTools/BeyondCompare4.cs#L12).

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by astos-marcb**
Fixes #11741

## Proposed changes

- treat `difftool.<tool>.path` as (absolute) executable path (see [difftool doc](https://git-scm.com/docs/git-difftool#Documentation/git-difftool.txt---toollttoolgt))
- add last resort fallback to avoid empty string as command path

## Test methodology 

- Verify the _empty path_ mentioned in #11741 is now set correctly

## Test environment(s) 

- GIT 2.45.2.windows.1
- Windows 10.0.19045.4529

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](/gitextensions/gitextensions/blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs [hunk 1]
```diff
@@ -159,8 +159,23 @@ public DiffMergeToolConfiguration LoadDiffMergeToolConfig(string toolName, strin
             }
             else
             {
-                IEnumerable<string> pathsToSearch = new[] { UnquoteString(GetToolSetting(diffTool.Name, DiffMergeToolType.Merge, "path")) }.Union(diffTool.SearchPaths);
-                fullPath = _findFileInFolders(diffTool.ExeFileName, pathsToSearch);
+                // query config for defined fullPath to executable
+                string? command = GetToolSetting(diffTool.Name, DiffMergeToolType.Merge, "path");
```
Comment (mstv) [inline src/app/GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs:163]:
```suggestion
                string? command = UnquoteString(GetToolSetting(diffTool.Name, DiffMergeToolType.Merge, "path"));
```

**Review by mstv — COMMENTED** [review]
Looks sensible
Add your sign-off to `contributors.txt`, please.

**Review by mstv — APPROVED** [review]
Thank you
have not run

File: src/app/GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs [hunk 2]
```diff
@@ -159,8 +159,23 @@ public DiffMergeToolConfiguration LoadDiffMergeToolConfig(string toolName, strin
             }
             else
             {
-                IEnumerable<string> pathsToSearch = new[] { UnquoteString(GetToolSetting(diffTool.Name, DiffMergeToolType.Merge, "path")) }.Union(diffTool.SearchPaths);
-                fullPath = _findFileInFolders(diffTool.ExeFileName, pathsToSearch);
+                // query config for defined fullPath to executable
```
Comment (gerhardol) [inline src/app/GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs:162]:
```suggestion
                // query static settings for defined fullPath to executable
```

**Review by gerhardol — APPROVED** [review]
