### PR TITLE
Fix "selection only" text search on Diff view (#7784)

### LINKED ISSUE #7784: [NBug] 0 <= offset < 9631. Parameter name: offset.
## Current behaviour

I simply navigate and search between files in a previous commit (File tree). A new search "Find next" give me this error.

## Expected behaviour
Search the text (highlight text and jump to the location)

## Steps to reproduce

I don't know how to reproduce now. Previous searches work fine.

## Error Details
```
System.ArgumentOutOfRangeException: 0 <= offset < 9631
Parameter name: offset
Actual value was 75480.
   at ICSharpCode.TextEditor.Document.GapTextBufferStrategy.GetCharAt(Int32 offset)
   at GitUI.TextEditorSearcher.FindNextIn(Int32 offset1, Int32 offset2, Boolean searchBackward)
   at GitUI.TextEditorSearcher.FindNext(Int32 beginAtOffset, Boolean searchBackward, Boolean& loopedAround)
   at GitUI.FindAndReplaceForm.<FindNextAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.FindAndReplaceForm.<btnFindNext_Click>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

## Additional information
I simply navigate and search between files in a previous commit (File tree). A new search "Find next" give me this error.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.19.1.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by realkompot**
Fixes #7784

## Proposed changes

- Turn off "selection only" mode in Find dialog if a new text is assigned to the file viewer (see comments in the issue).
- Prevent Diff view from iterating over the files if "selection only" search is being conducted (see isMultiFileSearch in the PR).

## Test methodology 

- Unit tests
- Manual testing of Find dialog on Diff, File tree, File history views.

## Test environment(s) 

- GIT 2.18
- Windows 10 Pro 

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/Editor/FindAndReplaceForm.cs [hunk 1]
```diff
@@ -401,11 +408,58 @@ protected override void Dispose(bool disposing)
...
+
+                return this;
+            }
+
+            public TestAccessor SetFileLoader(GetNextFileFnc fileLoader)
+            {
+                _control.SetFileLoader(fileLoader);
+
+                return this;
+            }
```
Comment (RussKie) [inline GitUI/Editor/FindAndReplaceForm.cs:451]: This doesn't look needed, `SetFileLoader` is marked as `internal` so it should be accessible in tests directly.

File: GitUI/Editor/FindAndReplaceForm.cs [hunk 2]
```diff
@@ -401,11 +408,58 @@ protected override void Dispose(bool disposing)
...
+        internal readonly struct TestAccessor
+        {
+            private readonly FindAndReplaceForm _control;
+
+            public TestAccessor(FindAndReplaceForm control)
+            {
+                _control = control;
+            }
+
+            public TestAccessor SetCriteria(string lookFor, bool matchCase = false, bool matchWholeWordOnly = false)
```
Comment (RussKie) [inline GitUI/Editor/FindAndReplaceForm.cs:423]: The idea behind `TestAccessor` was provide access to private type members without increasing their access level, and not really act as a wrapper type. This is so we can easily replace and remove this implementation with another (which is coming) without (significant) changes to tests.

Let's change this to be something like:
```cs
public TextEditorSearcher _search => _control._search;
public TextBox txtLookFor => _control.txtLookFor;
public CheckBox chkMatchCase => _control. chkMatchCase;
public CheckBox chkMatchWholeWord => _control.chkMatchWholeWord;
```

File: GitUI/Editor/FindAndReplaceForm.cs (hunk 1 above)
Comment (realkompot) [reply GitUI/Editor/FindAndReplaceForm.cs]: Removed.

File: GitUI/Editor/FindAndReplaceForm.cs (hunk 2 above)
Comment (realkompot) [reply GitUI/Editor/FindAndReplaceForm.cs]: Got it. Done.

File: GitUI/Editor/FindAndReplaceForm.cs [hunk 3]
```diff
@@ -503,14 +535,18 @@ public void SetScanRegion(int offset, int length)
...
         }
 
         public void ClearScanRegion()
         {
             if (_region != null)
             {
                 _document.MarkerStrategy.RemoveMarker(_region);
+                _document.TextContentChanged -= DocumentOnTextContentChanged;
                 _region = null;
+                ScanRegionChanged?.Invoke(this, null);
```
Comment (RussKie) [inline GitUI/Editor/FindAndReplaceForm.cs:549]: Never send `null` for event args, this may lead to NRE
```suggestion
                ScanRegionChanged?.Invoke(this, EventArgs.Empty);
```

File: GitUI/Editor/FindAndReplaceForm.cs [hunk 4]
```diff
@@ -503,14 +535,18 @@ public void SetScanRegion(int offset, int length)
             _region = new TextMarker(offset, length, TextMarkerType.SolidBlock,
                                      Globals.HalfMix(bkgColor, Color.FromArgb(160, 160, 160)));
             _document.MarkerStrategy.AddMarker(_region);
+            _document.TextContentChanged += DocumentOnTextContentChanged;
+            ScanRegionChanged?.Invoke(this, null);
```
Comment (RussKie) [inline GitUI/Editor/FindAndReplaceForm.cs:539]: ditto

File: GitUI/Editor/FindAndReplaceForm.cs [hunk 5]
```diff
@@ -401,11 +408,36 @@ protected override void Dispose(bool disposing)
...
+            public CheckBox ChkMatchCase => _control.chkMatchCase;
+            public CheckBox ChkMatchWholeWord => _control.chkMatchWholeWord;
+
+            public TextEditorControl Editor
+            {
+                set
+                {
+                    _control.Editor = value;
+                }
+            }
```
Comment (RussKie) [inline GitUI/Editor/FindAndReplaceForm.cs:434]: Set-only properties are a code smell, in this case please use the same approach as for the other members:
```suggestion
            public TextEditorControl Editor => _control.Editor;
```

File: UnitTests/GitUI.Tests/Editor/FindAndReplaceFormTests.cs [hunk 6]
```diff
@@ -0,0 +1,319 @@
...
+        }
+
+        [TearDown]
+        public void TearDown()
+        {
+            _findAndReplaceForm.Dispose();
+            _textEditorControl.Dispose();
+        }
+
+        [Test, TestCaseSource(typeof(FindAndReplaceTestData), nameof(FindAndReplaceTestData.MatchCaseCases))]
```
Comment (RussKie) [inline UnitTests/GitUI.Tests/Editor/FindAndReplaceFormTests.cs:37]: Can you please restructure the tests slightly to have the test data defined above each test, similar to how we have it for `TestGetStagedStatus` and `DeleteWithExtremePrejudice_should_return_true_for_empty_input_or_absent_folders`.
This way it is easier to grasp what we're testing and keep the context in your head.

File: GitUI/Editor/FindAndReplaceForm.cs (hunk 5 above)
Comment (realkompot) [reply GitUI/Editor/FindAndReplaceForm.cs:434]: Suggested code introduces a get-only property which is not needed. The reason this property is set-only is that the underlying _control.Editor is a set-only property (test accessor is supposed to be dumb as you explained and should just elevate access level). I agree that it smells :) my first thought was not to change the original code. I'll convert that underlying FindAndReplaceForm.Editor to be a method named SetEditor if you don't mind and it'll become a method here as well.

**Comment by RussKie** [comment]
Sounds good

File: GitUI/Editor/FindAndReplaceForm.cs (hunk 3 above)
Comment (realkompot) [reply GitUI/Editor/FindAndReplaceForm.cs]: Done

File: GitUI/Editor/FindAndReplaceForm.cs (hunk 4 above)
Comment (realkompot) [reply GitUI/Editor/FindAndReplaceForm.cs]: Done

File: UnitTests/GitUI.Tests/Editor/FindAndReplaceFormTests.cs (hunk 6 above)
Comment (realkompot) [reply UnitTests/GitUI.Tests/Editor/FindAndReplaceFormTests.cs]: Restructured. I also tried to pick better test data so that tests are easier to understand. Please see if it's any better.

File: GitUI/Editor/FindAndReplaceForm.cs (hunk 5 above)
Comment (realkompot) [reply GitUI/Editor/FindAndReplaceForm.cs]: Done

**Comment by RussKie** [comment]
Awesome work!
Please squash and it is good to go.

**Comment by realkompot** [comment]
Thanks. Squashed.

**Comment by RussKie** [comment]
Thank you
