### PR TITLE
Generate GitHub OAuth token with github api

### LINKED ISSUE #4800: Internet Explorer is unsupported for GitHub integration
**Workaround**
ℹ️  For workaround, see https://github.com/gitextensions/gitextensions/issues/3712#issuecomment-313185605
image

-----

I was not able to find an [open](https://github.com/gitextensions/gitextensions/issues?q=is%3Aopen) or [closed](https://github.com/gitextensions/gitextensions/issues?q=is%3Aclosed) issue matching what I'm seeing
Yes

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
GE retrieves a GitHub token for the GitHub integration using the embedded IE browser. This will soon no longer be supported.

image

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Revoke the GE GitHub application
image

Delete the GE GitHub token

Create a new GitHub token

**What is the expected behavior?**
Being able to create GH tokens without IE

**Environment you encounter the issue:**

- GitExtensions version: master
- OS version: Win10

### PR DESCRIPTION
**Pull request by pmiossec**
Fixes #4800

Need some more work on the UI side.

## Proposed changes

- Remove use of a Web browser component to generate the GitHub oauth token. Use the GitHub api instead.

### After

image

## Test methodology 

- Manual

## Test environment(s) 

- GIT 
- Windows 

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: Plugins/GitHub3/UserInputPrompt.cs [hunk 1]
```diff
@@ -0,0 +1,32 @@
+﻿using System;
+using System.Windows.Forms;
+
+namespace GitHub3
+{
+    public partial class UserInputPrompt : Form
+    {
+        public string UserInput { get; private set; } = "";
+
+        public UserInputPrompt(string title, string label, bool isPassword = false)
```
Comment (RussKie) [inline Plugins/GitHub3/UserInputPrompt.cs]: I struggle to find where it used. Could you please point me to it?

File: Plugins/GitHub3/GitHub3.csproj [hunk 2]
```diff
@@ -78,6 +84,10 @@
       <Name>GitCommands</Name>
       <Private>False</Private>
     </ProjectReference>
+    <ProjectReference Include="..\..\GitExtUtils\GitExtUtils.csproj">
```
[the remark this answers is not in the document]
Comment (pmiossec) [reply Plugins/GitHub3/GitHub3.csproj]: It was for a quick test. I planned to remove it but I don't know at the moment how to fix that.

It is for `ThreadHelper.JoinableTaskFactory.RunAsync()` to call an async on an not async method.

File: Plugins/GitHub3/GitHubCredentialsPrompt.cs [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+
+        private void btn_OK_Click(object sender, EventArgs e)
+        {
+            var tokenTask = ThreadHelper.JoinableTaskFactory.RunAsync(() => GenerateOAuthTokenAsync(txtGitHubLogin.Text, txtGitHubPassword.Text, txtSecondFactor.Text));
+            var token = tokenTask.Join();
+            if (!string.IsNullOrWhiteSpace(token))
+            {
+                GitHubLoginInfo.OAuthToken = token;
+
+                MessageBox.Show(this, "Successfully retrieved OAuth token.", "GitHub Authorization");
```
[the remark this answers is not in the document]
Comment (pmiossec) [reply Plugins/GitHub3/GitHubCredentialsPrompt.cs]: I know. planned.

File: Plugins/GitHub3/GitHubCredentialsPrompt.cs [hunk 4]
```diff
@@ -0,0 +1,127 @@
...
+        }
+
+        private async Task<string> GenerateOAuthTokenAsync(string login, string password, string secondFactorOtp)
+        {
+            // https://developer.github.com/v3/auth/#using-the-oauth-authorizations-api-with-two-factor-authentication
+            const string otpHeaderKey = "X-GitHub-OTP";
+            const string githubScopesJson = "{\"scopes\":[\"repo\", \"public_repo\"],\"note\":\"Token for Git Extensions\"}";
+            using (var httpClient = new HttpClient())
+            {
+                using (var request = new HttpRequestMessage(new HttpMethod("POST"), "https://api.github.com/authorizations"))
```
[the remark this answers is not in the document]
Comment (pmiossec) [reply Plugins/GitHub3/GitHubCredentialsPrompt.cs]: I thought about that for begin of the support of GitHub enterprise.

File: Plugins/GitHub3/UserInputPrompt.cs (hunk 1 above)
Comment (pmiossec) [reply Plugins/GitHub3/UserInputPrompt.cs]: That is no more used and planned to be removed but kept it for the moment because it could be a configurable replacement of https://github.com/gitextensions/gitextensions/blob/master/GitUI/Script/SimplePrompt.cs

File: Plugins/GitHub3/GitHubCredentialsPrompt.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (RussKie) [reply Plugins/GitHub3/GitHubCredentialsPrompt.cs]: Yesterday I visited my former colleagues and they use GHE. They'd love this

File: Plugins/GitHub3/GitHub3.csproj (hunk 2 above)
[the remark this answers is not in the document]
Comment (RussKie) [reply Plugins/GitHub3/GitHub3.csproj]: @mast-eu this is something we'll want to migrate/make part of https://github.com/gitextensions/gitextensions.extensibility package
I had a look at the API in GitExtUtils project and I think they can be useful for both GE and plugins.

File: Plugins/GitHub3/GitHubCredentialsPrompt.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (pmiossec) [reply Plugins/GitHub3/GitHubCredentialsPrompt.cs]: >They'd love this

I hope they will be able to provide some time to test the build because I don't have access to GHE. 


In fact, I think that it is not too difficult to achieve once this PR is done.

The 2 things missing:

* add the URL in the settings (easy and I already done it, even if I think we must revamp the settings for a good UX)
* we need a method in the plugin interface that is called when the repository is changed to switch from GH to GHE (or the opposite) if needed depending on the repository settings.

**Comment by pmiossec** [comment]
Most things should be in place...

**Comment by pmiossec** [comment]
>Seem and works OK for me

May I ask you if you have 2nd factor Auth enabled?
And which one? SMS or app?

And for the others that will test, if you could also give me this information.

**Comment by gerhardol** [comment]
> May I ask you if you have 2nd factor Auth enabled?

App

**Comment by gerhardol** [comment]
> And for the others that will test, if you could also give me this information.

I tried switching to SMS. First time it failed, I do not remember what I did - maybe it was the GH switch.
After that it was OK regardless if I clicked 2factor link or not.

Maybe the description should be changed from "Enter a 2nd factor code from an authenticator app" (why is that not in the .xlf file, build is OK?) as it works with SMS, but is not mandatory to select the link. (Maybe "Enter a two-factor code from an authenticator app or SMS".)

If you have selected the 2-factor link, there is no possibility to go back other than Cancel and retry. No major issue.

**Comment by pmiossec** [comment]
>why is that not in the .xlf file, build is OK?

I noticed it some weeks ago. I think it is plugins strings that are not translated, but I'm not sure. I thought I have created an issue for that but it seems that was just a comment that I can't find. 

>Maybe the description should be changed from "Enter a 2nd factor code from an authenticator app"

The word 'application' was there for that but maybe it's not enough clear. 
I will think about it. 

> as it works with SMS, but is not mandatory to select the link. (Maybe "Enter a two-factor code from an authenticator app or SMS".)

I have to test and confirm it but I think that when you have SMS 2nd factor configured, you have to do a failing call to trigger the send of the SMS. That's why SMS are not mentioned in the beginning. 

And after, the label is updated with the type of 2nd factor code you should enter ('app' or 'SMS'). 

>If you have selected the 2-factor link, there is no possibility to go back other than Cancel and retry. No major issue.

Indeed, I didn't feel the need. Clearing the 2nd factor field is equivalent to the initial state.
Perhaps there's a need but I don't know how to do it. A 'reset' button?

Another thing. I don't know if it's a good idea but I imagine that some people will not be very confident to enter there password with fear of what we will do with it. So I'd like to add a link 'I don' t trust you' that will copy in the clipboard the curl command to generate the token.
That way the user could enter himself it's credential in a command window and he will have to file the token field with the result.

What do you think of this idea?

**Comment by gerhardol** [comment]
> A 'reset' button?

"No two-factor authentication" link?
As my other comments, this was more a discussion point than a request.

> What do you think of this idea?

Sounds good.

**Comment by RussKie** [comment]
A UI comment. 
Most of our dialogs have right aligned buttons, and we don't provide a cancel button because it is the same as closing the dialog
https://github.com/gitextensions/gitextensions/issues/6183

**Comment by RussKie** [comment]
Apologies, I should have noticed this earlier. Few UI comments. 
Please refer to https://github.com/gitextensions/gitextensions/issues/6183

1. Most of our dialogs have right aligned buttons, and we don't provide a cancel button because it is the same as closing the dialog
2. Labels are to be positioned to the left of input controls
3. Labels are to end with `:`

Suggest shortening the labels:
* `Username:`
* `Password:`
* `2FA code:`

File: Plugins/GitHub3/GitHub3Plugin.cs [hunk 5]
```diff
@@ -76,11 +69,17 @@ public static string OAuthToken
     [Export(typeof(IGitPlugin))]
     public class GitHub3Plugin : GitPluginBase, IRepositoryHostPlugin
     {
+        public static string GitHubAuthorizationRelativeUrl = "authorizations";
         public static string UpstreamConventionName = "upstream";
+        public readonly StringSetting GitHubApiEndpoint = new StringSetting("GitHub (Enterprise) api endpoint", "https://api.github.com");
```
Comment (RussKie) [inline Plugins/GitHub3/GitHub3Plugin.cs]:
```suggestion
        public readonly StringSetting GitHubApiEndpoint = new StringSetting("GitHub (Enterprise) API endpoint", "https://api.github.com");
```

Comment (pmiossec) [reply Plugins/GitHub3/GitHub3Plugin.cs]: I didn't had the time to test the last changes I made. I pushed it in case I eventually found some time over the weekendtto test it on my personal computer. 

So, please wait a little more before merging it.

**Comment by pmiossec** [comment]
I have tested it and all should be good now...

File: Plugins/GitHub3/GitHubCredentialsPrompt.cs [hunk 6]
```diff
@@ -0,0 +1,152 @@
...
+            public string token { get; set; }
+        }
+
+        private async Task<string> GenerateOAuthTokenAsync(string login, string password, string secondFactorOtp)
+        {
+            // https://developer.github.com/v3/auth/#using-the-oauth-authorizations-api-with-two-factor-authentication
+            const string otpHeaderKey = "X-GitHub-OTP";
+            string note = $"Token for Git Extensions on {Environment.MachineName} at {DateTime.Now:g}";
+            string githubScopesJson = "{\"scopes\":[\"repo\", \"public_repo\"],\"note\":\"" + note + "\"}";
+            using (var httpClient = new HttpClient())
```
Comment (RussKie) [inline Plugins/GitHub3/GitHubCredentialsPrompt.cs]: This is an antipattern, `HttpClient` shouldn't be used like this. This was a very unfortunate design decision made by the team.
More info https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

Comment (pmiossec) [reply Plugins/GitHub3/GitHubCredentialsPrompt.cs]: Listen, you will laugh!
I am fully aware of that problem: I fix this issue on the different company projects I work on and two of my most upvoted answers on Stackoverflow are about that advice: https://stackoverflow.com/a/40707446/717372

The only explanation was that did it temporarily when doing my proof of concept and forget about fixing it 😭  (it should have not been a big deal because the httpclient is used to do a maximum of 2 calls)

Anyway, fixed.

Comment (RussKie) [reply Plugins/GitHub3/GitHubCredentialsPrompt.cs]: Mate, you're a legend 💯
