### PR TITLE
Make the Debug build debuggable

### LINKED ISSUE #9743: [NBug] Could not find a part of the path 'C:\Program Files\dotnet\...
### Environment

- Git Extensions 33.33.33
- Build 42c30a2656b7846ac48d233c74fd471066a0cb12
- Git 2.32.0.windows.1 (recommended: 2.33.0 or later)
- Microsoft Windows NT 10.0.22000.0
- .NET 5.0.9
- DPI 96dpi (no scaling)

### Issue description

image

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\dotnet\Themes'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.EnumerateFiles(String searchPattern, SearchOption searchOption)
   at GitUI.Theming.ThemeRepository.GetBuiltinThemeIds() in D:\Development\gitextensions\GitUI\Theming\ThemeRepository.cs:line 69
   at GitUI.Theming.ThemeRepository.GetThemeIds() in D:\Development\gitextensions\GitUI\Theming\ThemeRepository.cs:line 55
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ColorsSettingsPageController.ShowThemeSettings() in D:\Development\gitextensions\GitUI\CommandsDialogs\SettingsDialog\Pages\ColorsSettings\ColorsSettingsPageController.cs:line 33
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ColorsSettingsPage.SettingsToPage() in D:\Development\gitextensions\GitUI\CommandsDialogs\SettingsDialog\Pages\ColorsSettings\ColorsSettingsPage.cs:line 127
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings() in D:\Development\gitextensions\GitUI\CommandsDialogs\SettingsDialog\SettingsPageBase.cs:line 96
   at GitUI.CommandsDialogs.FormSettings.LoadSettings() in D:\Development\gitextensions\GitUI\CommandsDialogs\FormSettings.cs:line 81
   at GitUI.CommandsDialogs.FormSettings.FormSettings_Shown(Object sender, EventArgs e) in D:\Development\gitextensions\GitUI\CommandsDialogs\FormSettings.cs:line 280
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

### Steps to reproduce

* Running the latest master locally
* Upon the app start go to Settings

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by RussKie**
An addendum to #9704.

## Proposed changes

- The .NET bootstrap created a .NET Framework entry point. This tricks the debugger, and it doesn't see the app as a .NET process, and, thus, unable to hit any breakpoints. 
To mitigate this, only apply the bootstrap to the Release configuration.
- Correct path to our executable under DotnetRuntimeBootstrapper.
Resolves #9743

### CODE REVIEW

**Comment by gerhardol** [comment]
Can this be changed to allow tests in Debug too?
(comment in #9745 that fixed another test issue in Debug)

**Comment by RussKie** [comment]
Bugger! Let's pull the debug assert. If you can make a PR and merge -
that'd be great. I'll see if I can come up fix a better was to assert later.

**Comment by gerhardol** [comment]
Disabling privately for now, there must be a better way.
I had expected that `#if !TEST` would work but the application libs are not built with that define.
Some mocking could be used, but all affected tests will have to be updated.

**Comment by gerhardol** [comment]
There are also random "Unhandled exception" popups that hang tests (occurred before this change).
In that change there should not be a popup but fail immediately.

The reason for the illegal directory is unknown.

File: GitCommands/Settings/AppSettings.cs [hunk 1]
```diff
@@ -61,7 +61,11 @@ public static class AppSettings
         public static readonly string ApplicationId = ApplicationName.Replace(" ", "");
         public static readonly string SettingsFileName = ApplicationId + ".settings";
         public static readonly string UserPluginsDirectoryName = "UserPlugins";
-        private static string _applicationExecutablePath = Application.ExecutablePath;
+
+        // Under DotnetRuntimeBootstrapper this points to C:\Program Files\dotnet\dotnet.exe
+        // whereas we need our executable
+        private static string _applicationExecutablePath = Assembly.GetEntryAssembly().Location.Replace(".dll", ".exe");
```
Comment (Tyrrrz) [inline GitCommands/Settings/AppSettings.cs:67]: Note: it's safer to use `Path.ChangeExtension(...)` :)
