### PR TITLE
Serialize submodules info loading

### LINKED ISSUE #6357: UI freezes when updating submodule status
## Current behaviour

When the submodule status are updated for the drop down (or side panel in master), the UI can freeze and stop to respond.

Note: There are several issues reported that are related to this already. However, most are quite generic and have been partly fixed (or a workaround applied). This issue is a fresh start to describe a (the core?) problem.

## Expected behaviour

The UI responding.

## Steps to reproduce

This is described for master, can be reproduced in a similar way for 3.0, but master (3.1) (~~even better with #6349, now merged to master~~) has better visual clues (status in left panel). In 3.0 the submodule structure and status is calculated immediately, in 3.1 the structure is calculated immediately but the status is evaluated when commit-count reports that submodules are dirty or changed.

The more submodules there is in a repo, the easier it is to reproduce. I find it easier to reproduce if I add GE as a submodule to itself 4 times. It can be reproduced with fewer and more reliably occurs with more clones, but the freeze is annoying...
The following add a clone to an existing local directory, repeat four times:
```
$ git submodule add ../gitextensions subtest/x001
```
To create many:
```
for i in `seq 1 100`; do git submodule add ../gitextensions subtest/x$i; done
```

 * Enable submodule status (require commit status) (GE 3.0 do not require commit status, submodule status queried instantly).

 * Change revision or make a submodule dirty (to initiate the submodule status when commit status sees changes)
$ touch GitExtensionsDoc/t.t

 * Show the Git Command log

View the Diff tab (to get GE to create Git commands).
View artificial commits
Reload (F5)

Watch the command log to emit updates every second (instead of many per second). If no freeze when the status markers appears (~~use #6349, now merged~~), refresh again until the problem appear.

To see that the "slow log update" is actually a problem:
When Commit button changes from gray to yellow switch between Worktree and Index artificial commits until the UI freezes. 
Note: It is easier to recreate by selecting commits, but the command cache requires that you scroll to get new commits at each try.

## Screenshots

One recording, first try experiences the problem, the second not
ge_subm
[ge_subm.txt](https://github.com/gitextensions/gitextensions/files/2948880/ge_subm.txt)

## Did this work in previous version of GitExtensions

Working fine in 2.51

To recreate the same scenario in GE2.51:
Wait 15 s (the menu structure/status is evaluated at Browse activation, throttled)
Activate Browse, select the submodule menu

Note that the menu is sluggish and the background work due to all submodule calculations is quite high as the structure and status is often recreated.

## Environment

- Git Extensions 3.1.0
- Build 6c6885ef067b3a12cf5ab28b495d14c0826490da
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by jbialobr**
Fixes #6357

## Proposed changes

- Load submodules info with async api. It was not enough, the lag was smaller but still significant.
- Load submodules info sequentially - this helped.

### Before

image

### After

image

## Test methodology 

- Manual tests

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Git/ExecutableExtensions.cs [hunk 1]
```diff
@@ -226,6 +225,27 @@ string ComposeOutput()
...
+        /// <returns>An enumerable sequence of lines that yields lines as they become available. Lines from standard output are returned first, followed by lines from standard error.</returns>
+        [MustUseReturnValue("If output lines are not required, use " + nameof(RunCommand) + " instead")]
+        public static async Task<IEnumerable<string>> GetOutputLinesAsync(
+            this IExecutable executable,
+            ArgumentString arguments = default,
+            Action<StreamWriter> writeInput = null,
+            Encoding outputEncoding = null,
+            bool stripAnsiEscapeCodes = true)
+        {
+            var result = await executable.ExecuteAsync(arguments, writeInput, outputEncoding, stripAnsiEscapeCodes);
```
Comment (jbialobr) [inline GitCommands/Git/ExecutableExtensions.cs]: It is not an async stream, but at least is non blocking.

File: GitCommands/Submodules/SubmoduleStatusProvider.cs [hunk 2]
```diff
@@ -170,12 +168,15 @@ private async Task GetSubmoduleStatusAsync(bool updateStatus, SubmoduleInfo info
                 return;
             }
 
+            // sequential prefetching FilesEncoding in a parent thread
+            var foo = supermodule.FilesEncoding;
```
Comment (jbialobr) [inline GitCommands/Submodules/SubmoduleStatusProvider.cs]: After this PR it is at least responsive, but there is no GitModules caching. On every refersh GitModules are created for each submodule and have to load the same data (like git dir) again and again. I think we should observe submodules for modifications and refresh only these submodules which have changed. The same way as we use file system watchers. Otherwise if there is a lots of submodules the refresh action queries for changes for each submodule causing overall system overloading and cpu/hdd wasting.

Comment (gerhardol) [reply GitCommands/Submodules/SubmoduleStatusProvider.cs]: File status reloading: #6359 (will not handle the case when all submodules are changed)
Diff loading: See #5769 Git-status already provides information about which submodules that are changed. Has been awaiting the other submodule changes, sidepanel etc

**Comment by gerhardol** [comment]
Thanks!
Works OK for me. There is still a little lag selecting commits while loading, but no "hanging" seen. 2.51 is still snappier loading the data, but 2.51 starts show the revision graph later, so there are other cons.
Would like to see this with #6359 that fixed my real life problem (but not the extreme setup)

File: GitCommands/Submodules/SubmoduleStatusProvider.cs (hunk 2 above)
Comment (jbialobr) [reply GitCommands/Submodules/SubmoduleStatusProvider.cs]: Thanks for referencing the issues, my knowledge about the project is little outdated.

Comment (gerhardol) [reply GitCommands/Submodules/SubmoduleStatusProvider.cs]: It is great to have you around, of course I have tried to do this myself too but it takes me quite some time to get into this.

**Comment by jbialobr** [comment]
>For c62d4f9, I prefer #6359 instead
👍 

>There are quite some changes otherwise, mostly seem fine. I would like to see the outcome of the discussion in #6357 (comment) before merging.

Even if we go for a dedicated task scheduler for background tasks, running tens of background tasks simultaneously will degrade the overall system performance.

File: GitCommands/Git/GitModule.cs [hunk 3]
```diff
@@ -2611,41 +2611,41 @@ public bool IsDirtyDir()
...
             return GetPatch(patches, fileName, oldFileName);
         }
 
         [CanBeNull]
-        private string GetFileContents(string path)
+        private async Task<string> GetFileContentsAsync(string path)
         {
             var args = new GitArgumentBuilder("show") { $"HEAD:{path.ToPosixPath().Quote()}" };
-            var result = _gitExecutable.Execute(args);
+            var result = await _gitExecutable.ExecuteAsync(args).ConfigureAwaitRunInline();
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs]: Could you please explain how you chose when to use `ConfigureAwaitRunInline()` and when `ConfigureAwait(false)` calls?

I've found https://github.com/Microsoft/vs-threading/pull/292 (via https://github.com/dotnet/project-system/pull/3662), however it is not clear to me why we aren't using one or the other.

File: GitCommands/Submodules/SubmoduleStatusProvider.cs [hunk 4]
```diff
@@ -170,12 +168,15 @@ private async Task GetSubmoduleStatusAsync(bool updateStatus, SubmoduleInfo info
...
+
             info.Detailed = new AsyncLazy<DetailedSubmoduleInfo>(async () =>
             {
-                await TaskScheduler.Default;
                 cancelToken.ThrowIfCancellationRequested();
 
-                var submoduleStatus = GitCommandHelpers.GetCurrentSubmoduleChanges(supermodule, submoduleName, noLocks: true);
+                var submoduleStatus = await GitCommandHelpers.GetCurrentSubmoduleChangesAsync(supermodule, submoduleName, noLocks: true)
+                .ConfigureAwait(false);
```
Comment (RussKie) [inline GitCommands/Submodules/SubmoduleStatusProvider.cs]: [nit] seems mis-indented, maybe worth keeping on the line above

File: GitCommands/Git/GitModule.cs (hunk 3 above)
Comment (jbialobr) [reply GitCommands/Git/GitModule.cs]: I use `ConfigureAwait(false)` when I don't want the continuation to be executed on the main thread.
I use `ConfigureAwaitRunInline` when I know it is safe to continue on the thread that completed the awaited task (regarding both: accessing variables and continuation's duration time).

**Comment by RussKie** [comment]
Thank you

**Comment by gerhardol** [comment]
How to continue this?
In everyday use #6359 is solving most issues for me. However, with just a few more submodules than what I use (or something else changed), the problem will occur.

This PR goes after the core problem even if there may be some issues left. From what I can tell, the changes are improvements anyway. Should this be merged anyway?
(At least first commit seem necessary.)

@jbialobr @RussKie 
How to proceed?

I rebased and removed one change in c62d4f940a7349aef375099df19a4ba472f2f061 (rest of the commit is probably OK):
https://github.com/gerhardol/gitextensions/tree/jbialobr/_jb/fix%236357
Builds here:
https://ci.appveyor.com/project/gerhardol/gitextensions/builds/23473927/artifacts

There are other ways to limit job (#6373 to minor extent, some suggestions in #5369) too, but that will not handle situations with many submodule changes.

**Comment by RussKie** [comment]
I don't currently work with any repos that have submodules (other than GE), so I have no skin in the game.
The changes look sensible to me, hence my approval.

If you're happy with the changes, let's merge them.

**Comment by gerhardol** [comment]
> If you're happy with the changes, let's merge them.

There are roughly three parts to this PR (partly from the PR description):

1. Load submodules info with async api. It was not enough, the lag was smaller but still significant.
First half, except 2nd commit

Good from what I know about async handling, but I am not the expert here, the existing GE code is my reference. If I were the maintainer, I would have squash merged these commits.

2. Pre-load module encoding. 
2nd commit

Not needed after #6359. At least one line should be removed, maybe the other are an improvement.

3. Load submodules info sequentially
Second half of the commits

Probably OK change, no need to make massive starts of background requests.
However, the change should not be needed according to the discussions in #6357, but if it is an improvement, it should be merged.

@jbialobr @sharwell @drewnoakes @spdr870 @RussKie 
How to proceed?

**Comment by jbialobr** [comment]
>I would have squash merged these commits.

I see no value in squashing commits. It was already discussed.

>Pre-load module encoding.
2nd commit

It is no longer a part of this PR.

>However, the change should not be needed according to the discussions in #6357, but if it is an improvement, it should be merged.

In my opinion this change is not needed only if we implement refreshing those submodules which actually  have changed. Otherwise querying for all the submodules at once puts an unnecessary pressure on the system resources.

File: GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs [hunk 5]
```diff
@@ -263,9 +263,28 @@ private async Task<Nodes> LoadNodesAsync(SubmoduleInfoResult info, CancellationT
...
             private async Task LoadNodeDetailsAsync(CancellationToken token, Nodes loadedNodes)
             {
+                await TaskScheduler.Default;
+                foreach (var node in loadedNodes.DepthEnumerator<SubmoduleNode>())
+                {
+                    token.ThrowIfCancellationRequested();
+                    await node.LoadDetailsAsync(token).ConfigureAwaitRunInline();
+                }
+
+                await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
```
Comment (sharwell) [inline GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs]:
```suggestion
                await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync(token);
```

File: UnitTests/GitCommandsTests/GitModuleTest.cs [hunk 6]
```diff
@@ -534,9 +538,12 @@ public void GetSuperprojectCurrentCheckout()
                 moduleTestHelperSuper.Module.GitExecutable.GetOutput(@"commit -am ""Update submodule ref""");
 
                 // Assert
-                (char code, ObjectId commitId) = moduleSub.GetSuperprojectCurrentCheckout();
-                Assert.AreEqual(32, code);
-                Assert.AreEqual(commitRef, commitId.ToString());
+                ThreadHelper.JoinableTaskFactory.Run(async () =>
```
Comment (sharwell) [inline UnitTests/GitCommandsTests/GitModuleTest.cs]: 💭 Why not just make the containing test method asynchronous?

File: GitCommands/Git/ExecutableExtensions.cs (hunk 1 above)
Comment (sharwell) [reply GitCommands/Git/ExecutableExtensions.cs]: What kind of stream is it? What would it take to make it properly asynchronous?

Comment (jbialobr) [reply GitCommands/Git/ExecutableExtensions.cs]: I believe it is https://docs.microsoft.com/pl-pl/dotnet/api/system.collections.generic.iasyncenumerable-1?view=netcore-3.0

File: GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs (hunk 5 above)
Comment (jbialobr) [reply GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs]: In the line below already is `token.ThrowIfCancellationRequested();` and it can not be removed. We can pass the token here as well to emphasize that it is not enough to pass it here and we have to recheck if cancellation was requested.

File: UnitTests/GitCommandsTests/GitModuleTest.cs (hunk 6 above)
Comment (jbialobr) [reply UnitTests/GitCommandsTests/GitModuleTest.cs]: I don't know. Is doing so compatible with JTF?

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs [hunk 7]
```diff
@@ -335,11 +335,9 @@ private void Update()
                     {
                         try
                         {
-                            await TaskScheduler.Default;
-
                             var cmd = GitCommandHelpers.GetAllChangedFilesCmd(true, UntrackedFilesMode.Default,
                                 noLocks: true);
-                            var output = module.GitExecutable.GetOutput(cmd);
+                            var output = await module.GitExecutable.GetOutputAsync(cmd).ConfigureAwait(false);
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: This change causes git-status to run on the UI thread. Is this really necessary?

Comment (jbialobr) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Do you observe any issues related to this? This is an async call and does not block the UI.

Comment (gerhardol) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: No problem seem, just confused by it.
