### PR TITLE
Store the commit message in the correct file

### LINKED ISSUE #6244: Commit message not stored after reverting a commit
## Current behaviour

A manually adapted commit message is not stored during an unfinished merge.

I know that there are reasons and test cases which ensure this behavior. Though there are valid use cases where this does not make very much sense.

## Steps to reproduce

- `Revert this commit...` with `Automatically create a commit` unchecked
- optional: modify the restored code
- enter an adapted commit message in the Commit dialog
- close the (modal!) Commit dialog (e.g. to lookup something in another commit)
- reopen the Commit dialog
- --> frustration

Even worse:
- try to revert a commit of a different branch
- no changes
- but the commit message 'Revert "..."' is sticky

## Expected behaviour

A manually entered commit message must not be discarded.

## Did this work in previous version of GitExtensions

No.

## Environment

- Git Extensions 3.1.0
- Build 4ebb916d67f24b09e4d8cc2213bae9be8b2cecfd
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by mstv**
Fixes #6244
I'd like to have this bug fixed in 3.1.1.

## Proposed changes

- store the commit message in the correct(!) file (either MERGE_MSG or COMMITMESSAGE)
  - refactor `CommitHelper` into `CommitMessageManager`
- disable changing the commit message and amending a commit unless `CommitKind.Normal`
- replace the commit message in an undo-able way when recent messages or commit templates are applied etc.

### After

Commit message, message menus and `Amend` button disabled for *fixup* and *squash* commits
fixup

## Test methodology

- manual tests
- NUnit tests for `CommitMessageManager`

## Test environment(s)

- Git Extensions 3.1.0
- Build 82f125d435dc966b877c8bf63eb1ecdd882fc627
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
I'd like to have this bug fixed in 3.1.1, @RussKie.

**Comment by RussKie** [comment]
There are few things I'd like to change, I'm not particularly happy with
the statefulness and concerned it may lead to obscure bugs.
We can push it out in 3.1.2

**Comment by mstv** [comment]
> I'm not particularly happy with the statefulness and concerned it may lead to obscure bugs.

I have not added any state. I just made it work correctly. Loading  and storing of the message is symmetrical now.
Maybe the whole commit message handling should be reworked. Then we should open an additional issue for it.

**Comment by RussKie** [comment]
I'll find sometime to share my thoughts with you

File: GitCommands/CommitMessageManager.cs [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+        {
+        }
+
+        private CommitMessageManager(string workingDirGitDir, Encoding commitEncoding, IFileSystem fileSystem)
+        {
+            _fileSystem = fileSystem;
+            _commitEncoding = commitEncoding;
+            _amendSaveStatePath = GetFilePath(workingDirGitDir, "GitExtensions.amend");
+            _commitMessagePath = GetFilePath(workingDirGitDir, "COMMITMESSAGE");
+            _mergeMessagePath = GetFilePath(workingDirGitDir, "MERGE_MSG");
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/CommitMessageManager.cs]: 🤔  Perhaps it is worth to use an instance of `IFullPathResolver` here constructed as
```
var resolver = new FullPathResolver(() => workingDirGitDir)
```

File: GitCommands/CommitMessageManager.cs [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+            }
+            set
+            {
+                if (AppSettings.RememberAmendCommitState && value)
+                {
+                    _fileSystem.File.WriteAllText(_amendSaveStatePath, true.ToString());
+                }
+                else
+                {
+                    _fileSystem.File.Delete(_amendSaveStatePath);
```
Comment (RussKie) [inline GitCommands/CommitMessageManager.cs]: 🤔 Would it no fail if the file doesn't exist or otherwise inaccessible?

File: GitCommands/CommitMessageManager.cs [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+            set
+            {
+                _fileSystem.File.WriteAllText(GetMergeOrCommitMessagePath().FilePath, value ?? string.Empty, _commitEncoding);
+            }
+        }
+
+        public void ResetCommitMessage()
+        {
+            _fileSystem.File.Delete(_commitMessagePath);
+            _fileSystem.File.Delete(_amendSaveStatePath);
```
Comment (RussKie) [inline GitCommands/CommitMessageManager.cs]: ditto

File: GitCommands/CommitMessageManager.cs (hunk 2 above)
Comment (mstv) [reply GitCommands/CommitMessageManager.cs]: It does not fail if the file does not exist (idempotent function).
If the file is not accessible, it should throw an exception because this should not happen with a GE-private file and I am opposed to silently ignore real errors regardless of their severity.

File: GitCommands/CommitMessageManager.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (mstv) [reply GitCommands/CommitMessageManager.cs]: I understand your point.
Though that's where you guided me to: https://github.com/gitextensions/gitextensions/pull/6530#pullrequestreview-233799973. A lambda `Func<string> getWorkingDirGitDir` would have the same problem and is less visible IMO.
And I think, a change of the repo needs consideration everywhere in GE at all. The lifetime of the instance is bound to FormCommit and it's not very likely to be used in a different manner.

If you insist, I would always create new instances of the `CommitMessageManager` and hide this behind a static interface (facade).

> Perhaps it is worth to use an instance of IFullPathResolver.

(There are two known bugs, which shouldn't have a negative effect on accessing files in the `.git` folder.)
My main concern is that the lambda will be hidden even more.

[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/CommitMessageManager.cs]: This isn't a blocking comment, more like a discussion point. I'm always looking at how we can reduce a duplication of the code, especially when we have existing implementations already tested.
Perhaps I worry too much :) and you're right, the _current_ context is scoped to `FormCommit`, so your implementation is fine.

My original suggestion was about not passing an instance of `IGitModule`, as it may lead to operating on a different repo to what a user may be currently in.

File: GitCommands/CommitMessageManager.cs (hunk 2 above)
Comment (RussKie) [reply GitCommands/CommitMessageManager.cs]: Fair point, however we need to be mindful of a UX - we shouldn't crash the app because of that.
