### PR TITLE
Force commit info to clear on module change

### LINKED ISSUE #5624: Commit Tab does not clear on init of new repo
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
image

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open GE repo. 
2. Use start menu in GE to create a new repo
3. Notice the commit tab still has GE commit info

**What is the expected behavior?**
Commit tab to be empty on an empty repo.
**Environment you encounter the issue:**

- GitExtensions version:master
- GIT version: 2.19.1
- OS version: Microsoft Windows [Version 10.0.17763.55]
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**

### PR DESCRIPTION
**Pull request by vbjay**
Fixes #5624 

Changes proposed in this pull request:
- Force CommitInfo to clear on module change.
 
Screenshots before and after (if PR changes UI):

What did I do to test the code and ensure quality:
- Opened GE Repo.
- Created a new repo by using start menu in GE.
- Verified the commit info from GE did not show in the new repo.

Has been tested on (remove any that don't apply):

### CODE REVIEW

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -1876,6 +1876,7 @@ private void SetGitModule(object sender, GitModuleEventArgs e)
 #endif
 
                 HideDashboard();
+                RevisionInfo.SetRevisionWithChildren(null, Enumerable.Empty<ObjectId>().ToList().AsReadOnly());
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs]: Please use `Array.Empty<ObjectId>()` it is a faster and cheaper

**Comment by RussKie** [comment]
Thank you
