### PR TITLE
Browse Diff Untracked: Delete and Edit menu items are not enabled

### LINKED ISSUE #4316: Browse Diff Untracked: Delete and Edit menu items are not enabled
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Functionality enabled in 2.51 #4031 is not enabled due to an incorrect check introduced in #4208 9f5fe413

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
 - View Unstaged commits
 - Edit and Delete menu items are not available

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
Not in any released version

### PR DESCRIPTION
**Pull request by gerhardol**
New functionality in 2.50.02 #4031, regression from #4208 9f5fe413

Fixes #4316

Changes proposed in this pull request:
 - Functionality enabled in 2.51 #4031 is not enabled due to an incorrect check introduced in #4208 9f5fe41
 
Screenshots before and after (if PR changes UI):
- after
image

What did I do to test the code and ensure quality:
 -   View Unstaged commits
 -   Edit and Delete menu items are available

Has been tested on (remove any that don't apply):
 - GIT 2.10 and above
 - Windows 7 and above

### CODE REVIEW

File: GitUI/CommandsDialogs/RevisionDiff.cs [hunk 1]
```diff
@@ -226,7 +226,7 @@ private ContextMenuSelectionInfo GetSelectionInfo()
             var isCombinedDiff = isExactlyOneItemSelected && DiffFiles.CombinedDiff.Text == DiffFiles.SelectedItemParent;
             var selectedItemStatus = DiffFiles.SelectedItem;
             bool isBareRepository = Module.IsBareRepository();
-            bool singleFileExists = isExactlyOneItemSelected && File.Exists(DiffFiles.SelectedItem.Name); 
+            bool singleFileExists = isExactlyOneItemSelected && File.Exists(FormBrowseUtil.GetFullPathFromGitItemStatus(Module, DiffFiles.SelectedItem));
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionDiff.cs]: Similar to https://github.com/gitextensions/gitextensions/pull/4317#discussion_r160849662 I would prefer `IFullPathResolver`.

Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiff.cs]: Can we do this in a separate PR instead and apply a similar change for all similar usages?

**Comment by RussKie** [comment]
Sure, no probs
