### PR TITLE
Delete files if resetting new, not yet committed files

### LINKED ISSUE #10542: [NBug] fatal: pathspec 'GGClient/Assets/AdditiveHands-ForRegularMa...
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.33.0.windows.2 (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.11
- DPI 144dpi (150% scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: rm -- "GGClient/Assets/AdditiveHands-ForRegularMan.anim" "GGClient/Assets/AdditiveHands-ForRegularMan.anim.meta"
Working directory: D:\WORK\REPOS\GG\

```
GitExtUtils.ExternalOperationException: fatal: pathspec 'GGClient/Assets/AdditiveHands-ForRegularMan.anim' did not match any files
 ---> System.Exception: fatal: pathspec 'GGClient/Assets/AdditiveHands-ForRegularMan.anim' did not match any files
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetBatchOutput(IExecutable executable, ICollection`1 batchArguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.RemoveFiles(IReadOnlyList`1 files, Boolean force)
   at GitUI.CommandsDialogs.RevisionDiffControl.ResetSelectedItemsTo(Boolean actsAsChild)
   at GitUI.CommandsDialogs.RevisionDiffControl.ResetSelectedFilesWithConfirmation()
   at GitUI.CommandsDialogs.RevisionDiffControl.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsControl.ProcessHotkey(Keys keyData)
   at GitUI.CommandsDialogs.RevisionDiffControl.ProcessHotkey(Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

### Steps to reproduce

Hi guys, thanks for your work <3
I tried to reset working copy files. It had added files and chenged. I sellected both.

### Did this work in previous version of GitExtensions?

yes, it is a new crash

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10542

## Proposed changes

- Always confirm reset of selected items using `FormResetChanges` (added for subitems of context menu) 
- Also delete files if resetting new, not yet committed files
- Always call `RequestRefresh()`, i.e. also on exception
- Factor out `DeleteFromFilesystem()` from `DeleteSelectedFiles()`

### Before

exception when trying to reset a new file from Artificial Commits

image

### After

file deleted on hotkey `R` after confirmation

image

## Test methodology 

- manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build 844531512de4c3b4d1acd0bcf2ecda491afcc8de
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
I was leaning into ignoring new files instead, to not change the behavior.
If this is changed, the popup should be changed to the Command->Reset behavior.

image

**Comment by mstv** [comment]
> I was leaning into ignoring new files instead, to not change the behavior. If this is changed, the popup should be changed to the Command->Reset behavior.

Yes, we can emphasize more, that reset is a dangerous operation for all uncommitted changes - always.
Though I do not see the difference between new files and files that have been committed before. I want to restore a previous state. Both could contain significant work.

**Comment by gerhardol** [comment]
Can the Command->Reset dialog be extended?

**Comment by mstv** [comment]
Isn't FormResetChanges good enough as it is - refer to updated PR description.

**Comment by RussKie** [comment]
Do we know what changed in v4.x that led to the issues we're observing?

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 1]
```diff
@@ -485,49 +482,64 @@ private void RequestRefresh()
...
                 {
-                    var itemsToCheckout = selectedItems
-                        .Where(item => !item.Item.IsNew && item.FirstRevision?.ObjectId == parentId)
-                        .Select(item => item.Item.Name).ToList();
-                    Module.CheckoutFiles(itemsToCheckout, parentId, force: false);
+                    // Reset to parent revision
+
+                    // If file is new to the parent or is copied, it has to be deleted or removed if un/committed, respectively
+                    IEnumerable<FileStatusItem> addedItems = selectedItems.Where(item => item.Item.IsAdded);
+                    if (selectedItems.First().Item.IsUncommitted)
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:518]: `selectedItems.First()` would throw if the enumeration was empty.

Comment (mstv) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:518]: Would but cannot. There is an `if (!any) return` at the entry of the function.

**Comment by mstv** [comment]
> Do we know what changed in v4.x that led to the issues we're observing?

It is `throwOnErrorExit`. Before, the error was swallowed and the user needed to realize that nothing was done by git.

File: GitUI/CommandsDialogs/RevisionDiffControl.cs (hunk 1 above)
Comment (mstv) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:518]: Nope, selected is either the WorkTree *or* the Index *or* a real commit. All files of a diff belong to the same artificial or real commit.

Comment (vbjay) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:518]: Ok the way it reads it seems like each value in selecteditems is one file.

**Comment by gerhardol** [comment]
I consider this a change of functionality and want a reworded popup.

Also, if reset is performed for new&&changed, it should be possible on new only.

**Comment by mstv** [comment]
> I consider this a change of functionality and want a reworded popup.

What do you think of?
 
> Also, if reset is performed for new & changed, it should be possible on new only.

This does not belong to this PR but to `Commands | Reset changes`. This PR operates on the selection. If users need help for adapting the selection, we should rather implement filters.
I still do not see a real difference between "new" and "changed". I have agreed to emphasize that new files are affected. But why should we make it even more complex?

**Review by RussKie — COMMENTED** [review]
:shipit:

**Review by gerhardol — COMMENTED** [review]
+1

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 2]
```diff
@@ -1118,7 +1130,7 @@ private void openWithDifftoolToolStripMenuItem_DropDownOpening(object sender, Ev
 
         private void resetFileToolStripMenuItem_Click(object sender, EventArgs e)
         {
-            ResetSelectedItemsTo(sender == resetFileToSelectedToolStripMenuItem);
+            ResetSelectedItemsTo(sender == resetFileToSelectedToolStripMenuItem, deleteUncommittedAddedItems: true);
```
[the remark this answers is not in the document]
Comment (mstv) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:1133]: The submenuitems have not had a confirmation dialog.

[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:1133]: I do not oppose merging, but this or changes the functionality why the missing pop-up should be added. 
Otherwise this is well done.

[the remark this answers is not in the document]
Comment (mstv) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:1133]: So, I will add the confirmation dialog for both `Reset` sub-items unconditionally. (Currently, we reset without any confirmation popup - dangerous anyway.)

image

File: GitCommands/Git/GitItemStatus.cs [hunk 3]
```diff
@@ -182,6 +182,25 @@ private void SetFlag(bool isSet, Flags flag)
 
         #endregion
 
+        #region Derived Flags
+
+        /// <summary>
+        /// True if the Git item is added in the (artificial or real) commit.
```
Comment (RussKie) [inline GitCommands/Git/GitItemStatus.cs:188]:
```suggestion
        ///  Indicates whether the Git item was added in the (artificial or real) commit.
```

File: GitCommands/Git/GitItemStatus.cs [hunk 4]
```diff
@@ -182,6 +182,25 @@ private void SetFlag(bool isSet, Flags flag)
...
+        /// </summary>
+        public bool IsAdded
+            => IsNew || IsCopied;
+
+        /// <summary>
+        /// True if Staged is set and the commit is artificial.
```
Comment (RussKie) [inline GitCommands/Git/GitItemStatus.cs:194]:
```suggestion
        ///  Indicates whether <see cref="Staged"/> was set and the commit is artificial.
```

I don't believe "artificial" is part of the standard git lingo. Can we use something more git-ish? Like "commit index", "working tree", etc...
Maybe something like this?
```suggestion
        ///  Indicates whether the Git item is yet to be committed; that is it belongs to either... or....
```

File: GitCommands/Git/GitItemStatus.cs [hunk 5]
```diff
@@ -182,6 +182,25 @@ private void SetFlag(bool isSet, Flags flag)
...
+        /// </summary>
+        public bool IsUncommitted
+            => Staged is (StagedStatus.WorkTree or StagedStatus.Index);
+
+        public bool IsUncommittedAdded
```
Comment (RussKie) [inline GitCommands/Git/GitItemStatus.cs:199]:
```suggestion
        /// <summary>
        ///  Indicates whether the Git item was added in the commit, but it was not committed.
        /// </summary>
        public bool IsUncommittedAdded
```

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 6]
```diff
@@ -485,49 +482,64 @@ private void RequestRefresh()
...
-                foreach (var childId in selectedItems.SecondIds())
+                if (actsAsChild)
                 {
-                    var itemsToCheckout = selectedItems
-                        .Where(item => !item.Item.IsDeleted && item.SecondRevision.ObjectId == childId)
+                    // Reset to selected revision
+
+                    var deletedItems = selectedItems
+                        .Where(item => item.Item.IsDeleted)
                         .Select(item => item.Item.Name).ToList();
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:501]:
```suggestion
                    var deletedItems = selectedItems
                        .Where(item => item.Item.IsDeleted)
                        .Select(item => item.Item.Name)
                        .ToList();
```

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 7]
```diff
@@ -485,49 +482,64 @@ private void RequestRefresh()
...
-                    .Select(item => item.Item.Name).ToList();
-                Module.RemoveFiles(addedItems, false);
+                    Module.RemoveFiles(deletedItems, false);
 
-                foreach (var parentId in selectedItems.FirstIds())
+                    foreach (var childId in selectedItems.SecondIds())
+                    {
+                        var itemsToCheckout = selectedItems
+                            .Where(item => !item.Item.IsDeleted && item.SecondRevision.ObjectId == childId)
+                            .Select(item => item.Item.Name).ToList();
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:508]:
```suggestion
                        var itemsToCheckout = selectedItems
                            .Where(item => !item.Item.IsDeleted && item.SecondRevision.ObjectId == childId)
                            .Select(item => item.Item.Name)
                            .ToList();
```

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 8]
```diff
@@ -485,49 +482,64 @@ private void RequestRefresh()
...
+                    else
+                    {
+                        Module.RemoveFiles(addedItems.Select(item => item.Item.Name).ToList(), force: false);
+                    }
+
+                    foreach (var parentId in selectedItems.FirstIds())
+                    {
+                        var itemsToCheckout = selectedItems
+                            .Where(item => !item.Item.IsNew && item.FirstRevision?.ObjectId == parentId)
+                            .Select(item => item.Item.Name).ToList();
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:534]:
```suggestion
                        var itemsToCheckout = selectedItems
                            .Where(item => !item.Item.IsNew && item.FirstRevision?.ObjectId == parentId)
                            .Select(item => item.Item.Name)
                            .ToList();
```

**Review by RussKie — COMMENTED** [review]
Some nits.

File: GitCommands/Git/GitItemStatus.cs (hunk 4 above)
Comment (gerhardol) [reply GitCommands/Git/GitItemStatus.cs:194]: Artificial is ge specific, but it is more than worktree and index. In this case worktree and index is more correct though, but longer and you get less focus on the functionality.

**Comment by mstv** [comment]
I think I have resolved all comments.

**Review by RussKie — APPROVED** [review]
:shipit:

File: GitCommands/Git/GitItemStatus.cs [hunk 9]
```diff
@@ -182,6 +182,29 @@ private void SetFlag(bool isSet, Flags flag)
...
+
+        /// <summary>
+        /// Indicates whether the Git item is yet to be committed;
+        /// that is it belongs to either WorkTree or Index (<see cref="Staged"/> must be set).
+        /// </summary>
+        public bool IsUncommitted
+            => Staged is (StagedStatus.WorkTree or StagedStatus.Index);
+
+        /// <summary>
+        /// Indicates whether the Git item is new or copied and has not been committed yet.
```
Comment (gerhardol) [inline GitCommands/Git/GitItemStatus.cs:201]: I did not suggest a summary here (as for the others), as it is hard to explain. 
Adding references at least.
```suggestion
        /// Indicates whether the Git item is new or copied (<see cref="IsAdded"/>) and has not been committed yet (<see cref="IsUncommitted"/>).
```

**Review by gerhardol — APPROVED** [review]
great!
Just one suggestion.

**Comment by RussKie** [comment]
Please set the correct milestone, if backporting to a release branch.
