### PR TITLE
fix(Diff View): Avoid exception on open

### LINKED ISSUE #12026: [NBug] Invoke or BeginInvoke cannot be called on a control until t...
### Environment

- Git Extensions 5.1.0.17965
- Build f9e558c2f1645008b4c426f847cadbf10c92fcd0
- Git 2.47.0.windows.2
- Microsoft Windows NT 10.0.20348.0
- .NET 8.0.10
- DPI 96dpi (no scaling)
- Portable: True

### Issue description

```
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at GitUI.FileStatusList.<OnUICommandsSourceSet>g__UICommands_PostSettings|50_1(Object sender, GitUIPostActionEventArgs e) in C:\projects\gitextensions\src\app\GitUI\UserControls\FileStatusList.cs:line 266
   at GitUI.FileStatusList.<OnUICommandsSourceSet>g__OnUICommandsChanged|50_0(Object sender, GitUICommandsChangedEventArgs e) in C:\projects\gitextensions\src\app\GitUI\UserControls\FileStatusList.cs:line 259
   at GitUI.FileStatusList.OnUICommandsSourceSet(IGitUICommandsSource source) in C:\projects\gitextensions\src\app\GitUI\UserControls\FileStatusList.cs:line 245
   at GitUI.GitModuleControl.set_UICommandsSource(IGitUICommandsSource value) in C:\projects\gitextensions\src\app\GitUI\GitModuleControl.cs:line 68
   at GitUI.GitModuleControl.get_UICommandsSource() in C:\projects\gitextensions\src\app\GitUI\GitModuleControl.cs:line 49
   at GitUI.GitModuleControl.get_UICommands() in C:\projects\gitextensions\src\app\GitUI\GitModuleControl.cs:line 76
   at GitUI.GitModuleControl.get_Module() in C:\projects\gitextensions\src\app\GitUI\GitModuleControl.cs:line 98
   at GitUI.FileStatusList.<.ctor>b__47_1() in C:\projects\gitextensions\src\app\GitUI\UserControls\FileStatusList.cs:line 113
   at GitUI.FileStatusDiffCalculator.GetModule() in C:\projects\gitextensions\src\app\GitUI\UserControls\FileStatusDiffCalculator.cs:line 327
   at GitUI.FileStatusDiffCalculator.CalculateDiffs(IReadOnlyList`1 revisions, GitRevision selectedRev, ObjectId headId, Boolean allowMultiDiff, CancellationToken cancellationToken) in C:\projects\gitextensions\src\app\GitUI\UserControls\FileStatusDiffCalculator.cs:line 75
   at GitUI.FileStatusDiffCalculator.Calculate(IReadOnlyList`1 prevList, Boolean refreshDiff, Boolean refreshGrep, CancellationToken cancellationToken) in C:\projects\gitextensions\src\app\GitUI\UserControls\FileStatusDiffCalculator.cs:line 51
   at GitUI.FileStatusList.SetDiffs(IReadOnlyList`1 revisions) in C:\projects\gitextensions\src\app\GitUI\UserControls\FileStatusList.cs:line 833
   at GitUI.UserControls.CommitDiff.SetRevision(ObjectId objectId, String fileToSelect) in C:\projects\gitextensions\src\app\GitUI\UserControls\CommitDiff.cs:line 53
   at GitUI.HelperDialogs.FormCommitDiff..ctor(IGitUICommands commands, ObjectId objectId) in C:\projects\gitextensions\src\app\GitUI\HelperDialogs\FormCommitDiff.cs:line 15
   at GitUI.RevisionGridControl.<>c__DisplayClass165_0.<ViewSelectedRevisions>g__ProvideForm|0() in C:\projects\gitextensions\src\app\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 1845
   at GitUI.GitUICommands.ShowModelessForm(IWin32Window owner, Boolean requiresValidWorkingDir, EventHandler`1 preEvent, EventHandler`1 postEvent, Func`1 provideForm) in C:\projects\gitextensions\src\app\GitUI\GitUICommands.cs:line 270
   at GitUI.RevisionGridControl.ViewSelectedRevisions() in C:\projects\gitextensions\src\app\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 1848
   at GitUI.RevisionGridControl.OnGridViewDoubleClick(Object sender, MouseEventArgs e) in C:\projects\gitextensions\src\app\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 1772
   at System.Windows.Forms.DataGridView.OnMouseDoubleClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

Steps to reproduce:
 - Get the latest and greatest GitExtensions, portable edition.
 - Get the latest and greatest PortableGit, version git version 2.47.0.windows.2.
 - Open GitExtensions, my repo gets auto-opened.
 - Double click on latest commit.
 - This wild bug report appears.

### Steps to reproduce

already described

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #12026

## Proposed changes

Fixup FileStatusList:
- Skip unnecessary git-grep box visibility handling (which called `BeginInvoke` too early)
- Clear search string on hide of git-grep box

### Before

N/A

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/UserControls/FileStatusList.cs [hunk 1]
```diff
@@ -375,6 +378,11 @@ private void SetFindInCommitFilesGitGrepVisibilityImpl(bool visible)
                 // Adjust sizes "automatically" changed by visibility
                 cboFindInCommitFilesGitGrep.Top = 0;
             }
+            else if (_formFindInCommitFilesGitGrep?.Visible is false or null && cboFindInCommitFilesGitGrep.Text.Length > 0)
```
Comment (gerhardol) [inline src/app/GitUI/UserControls/FileStatusList.cs:381]: I prefer `is not true`

Comment (RussKie) [inline src/app/GitUI/UserControls/FileStatusList.cs:381]:
```suggestion
            else if (_formFindInCommitFilesGitGrep?.Visible is != true && cboFindInCommitFilesGitGrep.Text.Length > 0)
```

**Review by gerhardol — APPROVED** [review]

File: src/app/GitUI/UserControls/FileStatusList.cs (hunk 1 above)
Comment (mstv) [reply src/app/GitUI/UserControls/FileStatusList.cs:381]: I preferred that, too, until I trapped into
image

This made me think about replacing all `is not`.

**Review by pmiossec — APPROVED** [review]

File: src/app/GitUI/UserControls/FileStatusList.cs (hunk 1 above)
Comment (gerhardol) [reply src/app/GitUI/UserControls/FileStatusList.cs:381]: No, must handle null too. See my comment below.

Comment (gerhardol) [reply src/app/GitUI/UserControls/FileStatusList.cs:381]: please explain what you mean...

Comment (mstv) [reply src/app/GitUI/UserControls/FileStatusList.cs]: The change in the screenshot should have removed nullable only.
But I got confused by the inverse logic of "`is not`".
It would have been clearer if the old code had been `?.IsEmpty is true or null`.

I have changed the condition for this PR to match the recent code style as requested. We can finish the discussion later and, perhaps, adapt those 5 occurrences.

Comment (gerhardol) [reply src/app/GitUI/UserControls/FileStatusList.cs]: There should probably be `is (false or null)` and `is not true` is shorter. But Russkie commented on it and has done that before.
