### PR TITLE
Prevent NRE in designers that use EditNetSpell

### LINKED ISSUE #7583: NRE CreateTag Designer
## Current behaviour

Open CreateTag form in GitGui project.  You will get an object is null exception in the designer.  The cause is the designer is trying to toggle autocomplete in EditNetSpell control.  
## Expected behaviour

Designer just opens and lets developer design form.

## Steps to reproduce

Open FormCreateTag Designer

## Screenshots

image

## Did this work in previous version of GitExtensions

Probably.  Easy fix.  Just add a check to ToggleAutoCompletion that cancels it if in designer along with appsettings check.

## Environment

- Git Extensions 3.3.0
- Build b4eccee2aa39df80a15ec50c00b30c46a2d5ac23
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by vbjay**
Fixes #7583 

## Proposed changes

- Add design check to ToggleAutoCompletion.

## Test methodology 

- Built Project.
- Opened FormCreateTag Designer
- Did not get NRE in designer

## Test environment(s) 

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/SpellChecker/EditNetSpell.cs [hunk 1]
```diff
@@ -369,7 +369,7 @@ private void LoadDictionary()
 
         private void ToggleAutoCompletion()
         {
-            if (!AppSettings.ProvideAutocompletion)
```
Comment (gerhardol) [inline GitUI/SpellChecker/EditNetSpell.cs]: Observation: In most situations where DesignMode changes are done (like on line 350), there is a comment too. 
I first wanted to have a comment here too, but the property is called DesignMode, should be clear enough.

**Comment by RussKie** [comment]
Heya buddy, long time no see!
