### PR TITLE
FormCheckoutBranch: Handle no current checkout

### LINKED ISSUE #11498: [NBug] Value must not be null.
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.Exception: Value must not be null.
   at void Microsoft.Validates.Fail(string message) in C:/projects/gitextensions/GitExtUtils/Validates.cs:line 35
   at async void GitUI.CommandsDialogs.FormCheckoutBranch.Branches_SelectedIndexChanged(object sender, EventArgs e)+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCheckoutBranch.cs:line 489
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

a

### Steps to reproduce

1. Create a new repo in a folder containing files
2. Open Git Extensions
3. Add origin to an existing remote repo
4. Viola, the error message popped up

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11498

## Proposed changes

- FormCheckoutBranch: Handle no current checkout

## Screenshots 

N/A

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by pmiossec — APPROVED** [review]

File: GitUI/CommandsDialogs/FormCheckoutBranch.cs [hunk 1]
```diff
@@ -484,9 +484,14 @@ private void Branches_SelectedIndexChanged(object sender, EventArgs e)
...
                 ThreadHelper.FileAndForget(async () =>
                     {
-                        var currentCheckout = Module.GetCurrentCheckout();
+                        ObjectId? currentCheckout = Module.GetCurrentCheckout();
 
-                        Validates.NotNull(currentCheckout);
+                        // If there is no checkout yet, ahead/behind info is not applicable
+                        if (currentCheckout is null)
+                        {
+                            lbChanges.Text = "";
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/FormCheckoutBranch.cs:492]: Not on ui thread yet, await?

This could be handled in Module.GetCommitCountString(null,...) too

Comment (mstv) [reply GitUI/CommandsDialogs/FormCheckoutBranch.cs]: > Not on ui thread yet

Thank you!

`Module.GetCommitCountString` is complex enough already.
I have rather turned into a single assignment.

**Review by gerhardol — APPROVED** [review]
