### PR TITLE
Fix commit drop downs (#4698)

### LINKED ISSUE #4698: Commit message drop down issues
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Drop down shows:

- First item twice
- `...` after strings that are not shortened, nor open any kind of popup (usually menu items ending with `...` open a dialog or something)
- The gutter appears to be redundant on this drop down as it doesn't use icons (need to verify in code)

image

**Environment you encounter the issue:**

- GitExtensions version: 2.51

**Did this work in previous version of GitExtensions (which)?**

I've seen this bug for as long as I can remember.

### PR DESCRIPTION
**Pull request by drewnoakes**
Fixes #4698.

## Changes proposed in this pull request:

- Fix duplicate entry in commit message drop down list
- Fix truncation of commit message drop down labels
- Fix position of separator in commit templates drop down list
- Remove margin from these two drop down lists
- Misc tidying
 
### Before

image

image

### After

image

image

## What did I do to test the code and ensure quality:
 - Lots of manual testing and code review

### Has been tested on:
 - GIT 2.16
 - Windows 10

### CODE REVIEW

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 1]
```diff
@@ -2944,76 +2944,72 @@ private void copyFolderNameMenuItem_Click(object sender, EventArgs e)
...
-               .Union(fromSettings)
-               .Union(fromSettings.Length > 0 ? new[] { (CommitTemplateItem)null } : Array.Empty<CommitTemplateItem>())
-               .ToArray();
+            AddSeparator();
 
-            if (commitTemplates.Length > 0)
+            // Add a settings item
+            AddSettingsItem();
+
+            void CreateToolStripItem(CommitTemplateItem item)
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/FormCommit.cs]: a "return;" before local functions would be of help here

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 2]
```diff
@@ -2944,76 +2944,72 @@ private void copyFolderNameMenuItem_Click(object sender, EventArgs e)
...
             {
-                frm.ShowDialog(this);
+                CreateToolStripItem(item);
             }
 
-            _shouldReloadCommitTemplates = true;
-        }
+            AddSeparator();
 
-        private void LoadCommitTemplates()
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/FormCommit.cs]: My head spins trying to find how the old code worked, but the new seem logical...

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 1 above)
Comment (drewnoakes) [reply GitUI/CommandsDialogs/FormCommit.cs]: Thanks for the review. Added return.

**Comment by sharwell** [comment]
@drewnoakes I've been thinking about this one this evening. Tomorrow I'm going to try writing a set of regression tests for it.

**Comment by sharwell** [comment]
@drewnoakes After #4601 is merged, I can submit a pull request for this branch:

https://github.com/sharwell/gitextensions/compare/vs-threading...form-commit-tests

The second commit in this branch shows an initial regression test for the feature you are working on here. It does not currently reveal the bug you have fixed, but you should be able to build on that test to create a proper regression test for this feature.

**Comment by drewnoakes** [comment]
@sharwell that looks fantastic. Very nice.

Looking forward to #4601 being merged and getting through the backlog of pending PRs. I've stopped work for now to reduce conflicts.

**Comment by sharwell** [comment]
> Looking forward to #4601 being merged and getting through the backlog of pending PRs. I've stopped work for now to reduce conflicts.

Sounds good. Where possible, I would like to add regression and/or feature tests for the remaining cases. I'm sure many of them get into code which was never tested in the past, but hopefully it won't take long to add them.

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 3]
```diff
@@ -228,6 +229,12 @@ public FormCommit(GitUICommands commands, CommitKind commitKind = CommitKind.Nor
             {
                 gpgSignCommitToolStripComboBox.SelectedIndex = 0;
             }
+
+            ((ToolStripDropDownMenu)commitTemplatesToolStripMenuItem.DropDown).ShowImageMargin = false;
+            ((ToolStripDropDownMenu)commitTemplatesToolStripMenuItem.DropDown).ShowCheckMargin = false;
+
+            ((ToolStripDropDownMenu)commitMessageToolStripMenuItem.DropDown).ShowImageMargin = false;
+            ((ToolStripDropDownMenu)commitMessageToolStripMenuItem.DropDown).ShowCheckMargin = false;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormCommit.cs]: these double casts look uncharacteristic for you, Drew :)

**Comment by sharwell** [comment]
@drewnoakes I would like to see a regression test added before this one is merged. I'm hoping the work in #4717 (especially 37e8b679b07ce31312596017a29f64f606e27d1d and 6537756016233b389f16d6021dbad636731ca527) makes this easy.

**Comment by drewnoakes** [comment]
@sharwell I went through and rebased a bunch of PRs but left this one as I know you're looking at it too. Whether the tests are added now or later I'll leave up to @RussKie, but I wholeheartedly applaud the initiative to add more UI tests.

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 3 above)
Comment (drewnoakes) [reply GitUI/CommandsDialogs/FormCommit.cs]: Haha, I don't know what came over me :)
