### PR TITLE
FormCommit no longer show the committer info

### LINKED ISSUE #6201: FormCommit: Commiter are no more displayed but link is clickable
## Current behaviour

The commiter info are not displayed but the link is there clickable.
When the bug is debbuged, the link appears. [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug)?

## Expected behaviour

We could see the commiter info.

## Steps to reproduce

Open Commit Form.

## Screenshots

image

## Did this work in previous version of GitExtensions

Yes:

* 2.51 for sure
* 3, I don't know

## Environment

- Git Extensions 3.1.0
- Build 5ec1507ab077027c3508f4429d8d7e0e2210839d
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 192dpi (200% scaling)

## Diagnostics

Putting `UpdateAuthorInfo()` call in `OnShown()` instead of in `OnApplicationActivated()` solve the problem.

/cc @drewnoakes I see that you worked on it in a688346a21bd0ba9f22d0294c3547703e5a2ea20
Do you reproduce and have a idea on that?

### PR DESCRIPTION
**Pull request by RussKie**
The regression is caused by changes in #6134

Fixes #6201

## Test methodology 

- manual
- unit tests

/cc: @pmiossec could you confirm the fix please

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 1]
```diff
@@ -409,6 +404,8 @@ protected override void OnShown(EventArgs e)
                 Initialize();
             }
 
+            UpdateAuthorInfo();
+
```
Comment (vbjay) [inline GitUI/CommandsDialogs/FormCommit.cs]: Needs to be activated event. OnShown runs once. If user alters name or email it will not stay current.

**Comment by pmiossec** [comment]
>/cc: @pmiossec could you confirm the fix please

Successfully fixed.

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 1 above)
Comment (pmiossec) [reply GitUI/CommandsDialogs/FormCommit.cs]: I think he needs to close the form to update the settings and reopen it.
If he did it in an external console, I think that we could live with that...

Comment (RussKie) [reply GitUI/CommandsDialogs/FormCommit.cs]: Thanks Jay.
I'm split both ways... I suppose we can call it from both places.

Comment (vbjay) [reply GitUI/CommandsDialogs/FormCommit.cs]: Wrong. I developed that piece. I know what it does. Click the link to alter the user name or email. It WAS in activated event for a reason.

Comment (RussKie) [reply GitUI/CommandsDialogs/FormCommit.cs]: Fixed

Comment (vbjay) [reply GitUI/CommandsDialogs/FormCommit.cs]: 👍   The issue is the user will click the link, change user name and save.  They close settings dialog.  Commit form activates and reads in new settings.  The code was in the activated event to catch user changing setting even from console and then creating issues because their info is not correct when they will commit.  When he changed the code from Activated to Application Activated, he changed that functionality.

Comment (RussKie) [reply GitUI/CommandsDialogs/FormCommit.cs]: I have updated the code, please have a look.

Comment (pmiossec) [reply GitUI/CommandsDialogs/FormCommit.cs]: @RussKie Still OK for me.
