### PR TITLE
fix: RunCommand() should not throw when exit is checked

### LINKED ISSUE #11869: Error when clicked "View details" in error dialog
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.45.1.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.29
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: check-ref-format --branch "DPP-2133-V_logu_je_spousta_warningu_\\"HHH90003004__firstResult/maxResults_specified_with_collection_fetch;_applying_in_memory\\""
Working directory: C:\develop\soliteapay-portal\

```
GitExtUtils.ExternalOperationException: fatal: 'DPP-2133-V_logu_je_spousta_warningu_\HHH90003004__firstResult/maxResults_specified_with_collection_fetch;_applying_in_memory\' is not a valid branch name
 ---> System.Exception: fatal: 'DPP-2133-V_logu_je_spousta_warningu_\HHH90003004__firstResult/maxResults_specified_with_collection_fetch;_applying_in_memory\' is not a valid branch name
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.RunCommandAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 234
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.RunCommand(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 169
   at GitCommands.GitModule.CheckBranchFormat(String branchName) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 3974
   at GitUI.CommandsDialogs.FormCreateBranch.OkClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormCreateBranch.cs:line 121
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

trying to create a branch of name 'V logu je spousta warningu "HHH90003004: firstResult/maxResults specified with collection fetch; applying in memory"'.

Error dialog appeared with "Ignore" and "View details" buttons. I clicked "View details"

### Steps to reproduce

Try to create branch with name `V logu je spousta warningu "HHH90003004: firstResult/maxResults specified with collection fetch; applying in memory"`

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #11869 

## Proposed changes

Some methods intend to check the Git output, but the command always throws at exit.
throwOnErrorExit need to be configurable for these methods.
Quotes were additionally quouted too (done in QuoteNE())

This occurs for instance when checking the characters in a branch name and staging files.
Note that the command still echoes the branchname to the console.

While Git allows quotes in branch names, Windows does not (this is a file) allow quotes in the name.

Note: There are a few calls of RunCommand() that could be supressed in addition to those thatactually check the output, but I left it at the checked calls.
This cannot be be too commonly occurring as the throwOnErrorExit checks were added in 4.1 or 4.0.

### Before

NBug

### After

image

## Test methodology 

Manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

File: src/app/GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -1779,7 +1779,8 @@ public bool StageFile(string file)
                 {
                     "--add",
                     file.ToPosixPath().Quote()
-                });
+                },
+                throwOnErrorExit: false);
```
Comment (mstv) [inline src/app/GitCommands/Git/GitModule.cs:1783]: As the result of `StageFile` is never evaluated, rather remove the return value and throw.
If there are known uncritical exit codes, please handle them explicitly.

File: src/app/GitCommands/Git/GitModule.cs [hunk 2]
```diff
@@ -1889,7 +1890,8 @@ private async Task<bool> ExpressIntentToAddAsync(GitItemStatus file)
                 {
                     "--intent-to-add",
                     file.Name.Quote()
-                });
+                },
+                throwOnErrorExit: false);
```
Comment (mstv) [inline src/app/GitCommands/Git/GitModule.cs:1894]: ditto

File: src/app/GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (gerhardol) [reply src/app/GitCommands/Git/GitModule.cs:1783]: OK, changes requires changes of the plugin interface though.

**Review by mstv — APPROVED** [review]
