### PR TITLE
Fix Stashes drop-down size calculation

### LINKED ISSUE #12302: Stash dialog doesn't show stashes drop-down at 150%-200% scaling
### Environment

- GitExtensions version: master @ c40280f38b3fde418ecf73add681308aabd2916a
- OS version: Win11 200% scaling

### Issue description

Stashes dialog doesn't show stashes drop-down

Image

### Steps to reproduce

I've tested this with 150% and 200%, other scaling factors might "work" too.

1. Open Stashes dialog
2. ~Notice~ drop-down or lack thereof

### Did this work in previous version of GitExtensions?

Yes

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mdonatas**
Fixes #12302

## Proposed changes

- Revert changes to `Stashes` drop-down size calculation introduced in #12149

### Before

At 200%
image

### After

At 200%
image

At 100%
image

## Test methodology 

- Manually at 100% and 200% scaling

## Test environment(s) 

- Windows 11

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/CommandsDialogs/FormStash.cs [hunk 1]
```diff
@@ -291,7 +291,7 @@ private void LoadGitItemStatuses(IReadOnlyList<GitItemStatus> gitItemStatuses)
         private void ResizeStashesWidth()
         {
             const int spacingBetweenLabelAndComboBox = 5;
-            Stashes.Width = toolStrip1.Width - spacingBetweenLabelAndComboBox - showToolStripLabel.Width;
+            Stashes.Size = new Size(toolStrip1.Width - DpiUtil.Scale(spacingBetweenLabelAndComboBox) - showToolStripLabel.Width, Stashes.Size.Height);
```
Comment (gerhardol) [inline src/app/GitUI/CommandsDialogs/FormStash.cs:294]: Any reason why Height need to be set?

**Comment by mdonatas** [comment]
I haven't dug into the specifics but it was like that before it stopped
working. In debugger I've noticed thay the value of Width was simply not
updating

**Review by RussKie — APPROVED** [review]

**Review by gerhardol — APPROVED** [review]

File: src/app/GitUI/CommandsDialogs/FormStash.cs (hunk 1 above)
Comment (mstv) [reply src/app/GitUI/CommandsDialogs/FormStash.cs:294]: Thank you for testing and fixing! 200% scaling is hardly testable on a Full HD display.

> In debugger I've noticed the value of Width was simply not updating

This seems to be an effect just in the debugger because `WndProc` is halted, too.

> I haven't dug into the specifics but it was like that before it stopped working.

The key is the missing `DpiUtil.Scale`. The following works and should be used for clarity:
```suggestion
            Stashes.Width = toolStrip1.Width - DpiUtil.Scale(spacingBetweenLabelAndComboBox) - showToolStripLabel.Width;
```

(I wonder why it worked before #12149 - most likely because of additional space.)
image

**Review by mstv — APPROVED** [review]

File: src/app/GitUI/CommandsDialogs/FormStash.cs (hunk 1 above)
Comment (mdonatas) [reply src/app/GitUI/CommandsDialogs/FormStash.cs]: Thanks for clarification reg. values in debugger. Changed to your proposed variant and tested it at 100% 150% and 200% and.... THIS... to see what's the experience to test scaling with 1080p screen... looked "gorgeous" on my 4K monitor :D

image
