### PR TITLE
Fix selection from pull menu always performing default action rather …

### LINKED ISSUE #5420: Fetch menu item performs the default pull action
**Do you want to request a *feature* or report a *bug*?**

:bug:

**What is the current behavior?**

When clicking on Fetch menu item the default pull action is performed instead of fetch command.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Set rebase as the default pull action
2. Click on the Fetch menu item.

**What is the expected behavior?**

Fetch menu item should run git fetch command.

**Environment you encounter the issue:**

- GitExtensions version: f8946e9b9ea8449499ccb27fe5c97248de4bc3a6

### PR DESCRIPTION
**Pull request by amaiorano**
…than selected action

Fixes #5420 

Changes proposed in this pull request:
- This change is in the same spirit as the old code that used to set the next default action. The old code would set Module.LastPullAction to whichever action you selected from the menu (e.g. Settings.PullAction.Merge). Now, the behaviour isn't to set the next action to the last one you chose. Instead, we select a default action. So we can't just change the default action. Instead, we temporarily change the default action, perform the action, then bring it back.
 
Screenshots before and after (if PR changes UI):
- N/A

What did I do to test the code and ensure quality:
- I tested all the combinations, I believe.

Has been tested on (remove any that don't apply):
- Windows 10

### CODE REVIEW

**Comment by amaiorano** [comment]
@RussKie

**Comment by RussKie** [comment]
Thanks for the PR. Whilst it (probably, I haven't run it) addresses the bug I don't believe the addresses it in the most efficient way. 
Unfortunately the underlying code is quite convoluted and requires some untangling. 

I think the core of the problem lies in `FormPull` - when it is instantiated, its checkboxes are initialised from `AppSettings.DefaultPullAction`, which is incorrect.
https://github.com/gitextensions/gitextensions/blob/f4b0d3c1a3b0040280765c468cb6146cc2d10504/GitUI/CommandsDialogs/FormPull.cs#L130-L142

What I think we need to do something like the following:
* when we reach `PullToolStripMenuItemClick` we know the command the user requested, it is stored in `sender.Tag`
* we pass that information to `StartPullDialogAndPullImmediately`
* `StartPullDialogAndPullImmediately` needs to have its signature changed - `bool fetchAll = false, bool prune = false` must be dropped in favour of `PullAction pullAction = PullAction.None`
* in turn, when `StartPullDialogAndPullImmediately` instantiates `FormPull` it must pass `pullAction` to the form, which then should set its context according to the user's directives.

Thoughts?

**Comment by amaiorano** [comment]
@RussKie I completely agree with you. When I looked over the code last night, it was not obvious why it wasn't working, and that was, indeed, because it uses this global variable AppSettings.PullAction. I looked over the history to see what had happened from when it used to work to now, and saw that although changes were made to move away from "next action sets the default" to "set the explicit default", no attempt was made to fix this interaction with the AppSettings.PullAction. So I proceeded to make the minimal and functional change required to make this work.

However, it sounds like you would rather we do this *right*, and if that's the case, I'll be happy to go ahead with that.

**Comment by amaiorano** [comment]
I've got something that works, and the code is cleaner, but I've got questions about expected behaviour:

The original code seems to have some confusing logic around whether to hide the Pull dialog based on whether you're holding "shift" or not. I *think* the behavior we want is the following:

1. If the default action is "Open Pull Dialog...", then clicking on the Pull toolbar button will **always** open the PullDialog. Otherwise, the default action is performed silently when clicking the button. For example, if "Pull - merge" is selected as the default action, clicking the toolbar Pull button (which shows a special Pull - merge icon) will silently perform the action (i.e. will not open the PullDialog):
image

2. If the user manually selects any action from the toolbar Pull button dropdown, silently perform that action EXCEPT if "Open pull dialog..." was selected (of course):
image

3. Ctrl+Down, mapped to Commands -> Pull/Fetch... **always** open the PullDialog.

Now about the "Shift" key. In the above, I made no mention of holding "Shift". I don't really see how it would make sense to use "Shift". The only way I see it possibly making sense is changing rule 1 above so that clicking on the Pull toolbar button **always** opens the PullDialog, regardless of what default action you've set, except if you hold Shift. So we could rewrite rule 1 as:

1. Clicking on the Pull toolbar button **always** opens the PullDialog, except if Shift is being pressed. One exception: if the default action is "Open Pull Dialog...", then Shift will be ignored.

Thoughts?

**Comment by RussKie** [comment]
What you have described makes total sense, that's exactly what I would
expect. :+1:

Wrt: "shift" - I didn't know there was such functionality, I will have to
look at the code, but I don't think it is appropriate in these flows. Right
now I think we'll remove it, but I will have to have a look at the code to
confirm.

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -2344,51 +2300,77 @@ private void CommandsToolStripMenuItem_DropDownOpening(object sender, EventArgs
               enabled;
         }
 
-        private class ScopedSetLastPullAction : IDisposable
+        private void PullToolStripMenuItemClick(object sender, EventArgs e)
         {
-            private AppSettings.PullAction _oldPullAction;
+            // "Pull/Fetch..." menu item always opens the dialog
+            DoPull(false, pullAction: AppSettings.DefaultPullAction);
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs]: worth adding `isSilent: `

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 2]
```diff
@@ -2344,51 +2300,77 @@ private void CommandsToolStripMenuItem_DropDownOpening(object sender, EventArgs
...
+            DoPull(isSilent: true, pullAction: AppSettings.PullAction.FetchAll);
+        }
+
+        private void fetchPruneAllToolStripMenuItem_Click(object sender, EventArgs e)
         {
-            using (new ScopedSetLastPullAction(AppSettings.PullAction.None))
+            DoPull(isSilent: true, pullAction: AppSettings.PullAction.FetchPruneAll);
+        }
+
+        private void DoPull(bool isSilent, AppSettings.PullAction pullAction)
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs]: Suggest reordering the args to be more logical: `(AppSettings.PullAction pullAction, bool isSilent)`.

**Comment by RussKie** [comment]
I had a look, let's remove shift handling from these code paths.

File: GitUI/GitUICommands.cs [hunk 3]
```diff
@@ -478,41 +478,31 @@ bool Action()
...
+                using (var formPull = new FormPull(this, remoteBranch, remote, pullAction))
                 {
-                    if (fetchAll)
-                    {
-                        formPull.SetForFetchAll();
-                    }
-
-                    if (prune)
-                    {
-                        formPull.SetPrune();
```
Comment (RussKie) [inline GitUI/GitUICommands.cs]: Neither `SetForFetchAll` nor `SetPrune` no longer used outside of `FormPull` and thus can be removed completely, instructions they contain can be inlined at respective call sites

**Comment by amaiorano** [comment]
Made changes requested by @RussKie. Once you're happy with this PR, I'd be happy to squash down to a single commit, unless you'd rather keep the history in there.

**Comment by RussKie** [comment]
I prefer clean history - each commit to contain an atomic set of changes. 
I certainly like to see review comments be squashed in to respective changes.

**Comment by amaiorano** [comment]
Squashed changes to single commit

**Comment by RussKie** [comment]
Thank you
