### PR TITLE
Do not throw if SSH key is missing

### LINKED ISSUE #9588: GitExtensions not using SSH key for authentication, fallsback to basic credential authentication without trying to use keys
## Current behaviour

Git Extensions does not add/use SSH keys

## Expected behaviour

Git Extensions adds/uses SSH keys

## Steps to reproduce

- Generate key using puttygen
- Save private key (tried saving on multiple local drives as well)
- Open manage remotes window
- Private key file field: browse to created key
- Save changes
- Try to push, Git Extensions doesn't use SSH key and instead tries to fallback on credentials

I've also manually added the key into the putty keystore and the behaviour does not change.

## Did this work in previous version of GitExtensions

No. It's never worked and now I can't use credentials to authenticate with github.

## Environment

- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git 2.28.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #10530: [NBug] SSH key file could not be found
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

''

```
GitUI.NBugReports.UserExternalOperationException: SSH key file could not be found
 ---> System.IO.FileNotFoundException: SSH key file could not be found
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.PuttyHelpers.ThrowIfFileNotFound(String filePath, String errorMessage, String heading)
   at GitUI.Infrastructure.PuttyHelpers.StartPageantIfConfigured(Func`1 sshKeyFileLoader)
   at GitUI.CommandsDialogs.FormPush.StartPageant(String remote)
   at GitUI.CommandsDialogs.FormPush.PushChanges(IWin32Window owner)
   at GitUI.CommandsDialogs.FormPush.PushClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I just tried to push to remote origin.
Pull work just fine.
I use key stored in putty session which I use for accessing remote repository.
So I do not have private key in remote repository configuration.

### Steps to reproduce

Try to push into remote configured without explicit ssh key(using putty).

### Did this work in previous version of GitExtensions?

Yes

### Diagnostics

_No response_

### LINKED ISSUE #10555: [NBug] SSH key file could not be found
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

''

```
GitUI.NBugReports.UserExternalOperationException: SSH key file could not be found
 ---> System.IO.FileNotFoundException: SSH key file could not be found
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.PuttyHelpers.ThrowIfFileNotFound(String filePath, String errorMessage, String heading)
   at GitUI.Infrastructure.PuttyHelpers.StartPageantIfConfigured(Func`1 sshKeyFileLoader)
   at GitUI.CommandsDialogs.FormPush.StartPageant(String remote)
   at GitUI.CommandsDialogs.FormPush.PushChanges(IWin32Window owner)
   at GitUI.CommandsDialogs.FormPush.PushClick(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Tried to push to an SMB remote directory. No SSH key needed or expected.

### Steps to reproduce

1. Create a remote repository from an SMB url, example "\\mymachine.myhost.com\git\MyRepo"
2. Push to that repo.

### Did this work in previous version of GitExtensions?

Yes, pushing to remote SMB repositories has worked in all versions up til 4.x

### Diagnostics

_No response_

### LINKED ISSUE #10562: [NBug] SSH key file could not be found
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 192dpi (200% scaling)

### Issue description

''

```
GitUI.NBugReports.UserExternalOperationException: SSH key file could not be found
 ---> System.IO.FileNotFoundException: SSH key file could not be found
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.PuttyHelpers.ThrowIfFileNotFound(String filePath, String errorMessage, String heading)
   at GitUI.Infrastructure.PuttyHelpers.StartPageantIfConfigured(Func`1 sshKeyFileLoader)
   at GitUI.CommandsDialogs.FormPush.StartPageant(String remote)
   at GitUI.CommandsDialogs.FormPush.PushChanges(IWin32Window owner)
   at GitUI.CommandsDialogs.FormPush.PushClick(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

after upgrade

### Steps to reproduce

upgrdade

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### LINKED ISSUE #10565: [NBug] SSH key file could not be found
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22623.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

```
GitUI.NBugReports.UserExternalOperationException: SSH key file could not be found
 ---> System.IO.FileNotFoundException: SSH key file could not be found
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.PuttyHelpers.ThrowIfFileNotFound(String filePath, String errorMessage, String heading)
   at GitUI.Infrastructure.PuttyHelpers.StartPageantIfConfigured(Func`1 sshKeyFileLoader)
   at GitUI.CommandsDialogs.FormPush.StartPageant(String remote)
   at GitUI.CommandsDialogs.FormPush.PushChanges(IWin32Window owner)
   at GitUI.CommandsDialogs.FormPush.PushClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Ssh key is loaded with pagent. Trying to push to a branch that worked in previous version

Works is ssh key is manually specified in remotes config.

### Steps to reproduce

Create a remote using ssh. load public key via pagent. Try to push to remote.

### Did this work in previous version of GitExtensions?

Worked in previous 4.0 release

### Diagnostics

_No response_

### LINKED ISSUE #10569: [NBug] SSH key file could not be found
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

'C:/Users/kgrammer/.ssh/kg.ppk'

```
GitUI.NBugReports.UserExternalOperationException: SSH key file could not be found
 ---> System.IO.FileNotFoundException: SSH key file could not be found
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.PuttyHelpers.ThrowIfFileNotFound(String filePath, String errorMessage, String heading)
   at GitUI.Infrastructure.PuttyHelpers.StartPageantIfConfigured(Func`1 sshKeyFileLoader)
   at GitUI.CommandsDialogs.FormPush.StartPageant(String remote)
   at GitUI.CommandsDialogs.FormPush.LoadSshKeyClick(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

This latest upload will not let me change the location of the SSH key file.  It's defaulting to a very old location from a previous laptop (I upgraded earlier this month) and now I can't change the location of the ssh key file.

### Steps to reproduce

I'm not sure how you will reproduce this other then to simply try to change your SSH key file and see if you can reproduce the error.

### Did this work in previous version of GitExtensions?

The release prior to this current on.  I don't have the exact release number because you auto-updated my system.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by RussKie**
Resolves #10530
Resolves #10555
Resolves #10562
Resolves #10565
Resolves #10569
Resolves #9588

Restore the behaviour that was changed in https://github.com/gitextensions/gitextensions/pull/10357

### CODE REVIEW

File: GitUI/Infrastructure/PuttyHelpers.cs [hunk 1]
```diff
@@ -68,7 +68,10 @@ public static bool StartPageantIfConfigured(Func<string?> sshKeyFileLoader)
             ThrowIfFileNotFound(AppSettings.Pageant, $"'{AppSettings.Pageant}'\r\n\r\n{TranslatedStrings.ErrorSshPuTTYInstalled}");
 
             string? sshKeyFile = sshKeyFileLoader();
-            ThrowIfFileNotFound(sshKeyFile, $"'{sshKeyFile}'", TranslatedStrings.ErrorSshKeyNotFound);
+            if (!File.Exists(sshKeyFile))
+            {
+                return false;
```
Comment (mstv) [inline GitUI/Infrastructure/PuttyHelpers.cs:73]: Dummy question: Why not start Pageant anyway and bail out before `RunCommand(keyfile)`?

Comment (vbjay) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: Could do even better. Check if already running and then start only if not running.

Comment (gerhardol) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: Yes, switch the order.
Has anyone tested the setup?

Comment (RussKie) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: https://github.com/gitextensions/gitextensions/blob/6eab7392839c4d103bad1581fba5eaf6f008d766/GitUI/CommandsDialogs/FormPull.cs#L893-L916

If I'm not mistaken, this was the original logic - collect keys and, if those exist, start PuTTY.

I don't use SSH or keys, so I'm not setup to test it.

Comment (mstv) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: > I don't use SSH or keys, so I'm not setup to test it.

Me too. That's why "dummy question".

Comment (vbjay) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: https://www.howtogeek.com/devops/should-you-use-https-or-ssh-for-git/#:~:text=Where%20SSH%20takes,over%20the%20wire.  Why I use it.

Comment (RussKie) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: Thank you for the guide.
Plink seems to be hanging on me while trying to connect:
https://github.com/gitextensions/gitextensions/blob/21345f29511f71fb1ca7cfd8ea128972b56863e4/GitUI/Infrastructure/Plink.cs#L74-L82

image

Comment (RussKie) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: I didn't have PuTTY installed, and I installed the latest one available: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.78-installer.msi

Comment (RussKie) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: Omg.... I had to type "y" in this window so that a new fingerprint was recorded. Then I had to cancel the whole sequence and go restart the putty agent... t😩

Comment (vbjay) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: Oh yeah. That's the putty am I talking to valid server. Only have to do that once.per server.

**Comment by RussKie** [comment]
Tests locally.

* v4.0.1
image

* v4.0.2
image

File: GitUI/Infrastructure/PuttyHelpers.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: start plink should be before the key check
Otherwise this PR is approved

Comment (RussKie) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: Do you mean like this?
```diff
diff --git a/GitUI/Infrastructure/PuttyHelpers.cs b/GitUI/Infrastructure/PuttyHelpers.cs
index b2b8ddff0..fb07fe2ea 100644
--- a/GitUI/Infrastructure/PuttyHelpers.cs
+++ b/GitUI/Infrastructure/PuttyHelpers.cs
@@ -64,29 +64,29 @@ public static bool StartPageantIfConfigured(Func<string?> sshKeyFileLoader)
                 throw new UserExternalOperationException(TranslatedStrings.ErrorSshPuTTYWhereConfigure,
                     new ExternalOperationException(innerException: new Exception(TranslatedStrings.ErrorSshPuTTYNotConfigured)));
             }
 
             ThrowIfFileNotFound(AppSettings.Pageant, $"'{AppSettings.Pageant}'\r\n\r\n{TranslatedStrings.ErrorSshPuTTYInstalled}");
 
-            string? sshKeyFile = sshKeyFileLoader();
-            if (!File.Exists(sshKeyFile))
-            {
-                return false;
-            }
-
             Executable pageantExecutable = new(AppSettings.Pageant);
 
             // ensure pageant is loaded, so we can wait for loading a key in the next command
             // otherwise we'll stuck there waiting until pageant exits
             if (!IsPageantRunning())
             {
                 // NOTE we leave the process to dangle here
                 IProcess process = pageantExecutable.Start();
                 process.WaitForInputIdle();
             }
 
+            string? sshKeyFile = sshKeyFileLoader();
+            if (!File.Exists(sshKeyFile))
+            {
+                return false;
+            }
+
             return pageantExecutable.RunCommand(sshKeyFile.Quote());
 
             static bool IsPageantRunning()
             {
                 var pageantProcName = Path.GetFileNameWithoutExtension(AppSettings.Pageant);
                 return Process.GetProcessesByName(pageantProcName).Length != 0;

```

Could you please help me understand why we'd want to start plink if we don't have a key?

Comment (vbjay) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: From the feedback of the other issues we basically want to have 2 cases. 

If key file is blank then still attempt connect can suggest key file be set but not required in some alert. 

If key file not blank and file doesn't exist then show error that can't find key file.

Comment (vbjay) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: See https://github.com/gitextensions/gitextensions/issues/10530#issuecomment-1354346577

Comment (RussKie) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: @vbjay I still having troubles understanding why this is necessary. In the original implementation we would only start putty is we had a valid key.
https://github.com/gitextensions/gitextensions/blob/6eab7392839c4d103bad1581fba5eaf6f008d766/GitUI/CommandsDialogs/FormPull.cs#L893-L916
https://github.com/gitextensions/gitextensions/blob/6eab7392839c4d103bad1581fba5eaf6f008d766/GitCommands/Git/GitModule.cs#L1429-L1439

@SymbioticKilla confirmed in https://github.com/gitextensions/gitextensions/issues/10530#issuecomment-1357709486 that the current change is working as expected.

Comment (vbjay) [reply GitUI/Infrastructure/PuttyHelpers.cs:73]: So in putty you can save sessions that are configured ri have all their config setup. So when its used this way the server address used ditects it to use x key. 

Yes. I still like putting the key in my config because I can run grep or whatever to find all repos that use x key by examining the config files. But others are managing in putty so we need to support both flows. 

1. Doing it the way we do it now with key files
1. Leaving key file blank and still able to connect because we trust putty to load it up. But we still check result and I'd failed can ask did you include key file or whatnot.

**Review by mstv — APPROVED** [review]
The code LGTM, have not run

File: GitUI/Infrastructure/PuttyHelpers.cs [hunk 2]
```diff
@@ -81,6 +78,12 @@ public static bool StartPageantIfConfigured(Func<string?> sshKeyFileLoader)
                 process.WaitForInputIdle();
             }
 
+            string? sshKeyFile = sshKeyFileLoader();
+            if (!File.Exists(sshKeyFile))
```
Comment (vbjay) [inline GitUI/Infrastructure/PuttyHelpers.cs:82]: Make sure it only does this if not empty string.

**Review by vbjay — COMMENTED** [review]
Just confirming this. Basically. If set and file is missing we want to say hey issue with config. If empty then see if it ran successfully like you did.

**Comment by RussKie** [comment]
I think it's ready now.

File: GitUI/Infrastructure/PuttyHelpers.cs [hunk 3]
```diff
@@ -81,6 +78,12 @@ public static bool StartPageantIfConfigured(Func<string?> sshKeyFileLoader)
                 process.WaitForInputIdle();
             }
 
+            string? sshKeyFile = sshKeyFileLoader();
+            if (!string.IsNullOrWhiteSpace(sshKeyFile) && !File.Exists(sshKeyFile))
+            {
+                return false;
+            }
```
Comment (mstv) [inline GitUI/Infrastructure/PuttyHelpers.cs:85]: ❔ If a file is configured, we should tell the user if it cannot be found. 
```suggestion
            if (string.IsNullOrWhiteSpace(sshKeyFile))
            {
                return false;
            }

            ThrowIfFileNotFound(sshKeyFile, $"'{sshKeyFile}'", TranslatedStrings.ErrorSshKeyNotFound);
```

Comment (RussKie) [reply GitUI/Infrastructure/PuttyHelpers.cs:85]: Yes, thank you!

**Comment by psivanov** [comment]
I am using putty and pageant and it's still not fixed in 4.0.2...

- Git Extensions 4.0.2.15986
- Build b063d3258751505e45a0ea207778a19f4914fde7
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

image
