### PR TITLE
RevisionDiff: Stage/Unstage selected lines

### LINKED ISSUE #7338: Stage/unstage select lines in Browse
## Feature description

GE supports staging/unstaging files from the Browse window. The commit modal dialog is still required to stage/unstage lines (as well as the actual commit, that is a separate feature). It is possible to Cherry-pick/revert lines, but that often fails (git-apply has different options).

FormCommit has additions to FileViewer compared to RevisionDiffControl.  These options should be moved to FileViewer.cs so they can be shared with RevisionDiffControl.cs for the artificial commits.
A difference is that the "stage mode" is static in FormCommit but will depend on the selectedrevisions in RevisionDiffControl

## Environment
- Git Extensions 3.3.0
- Build 395cf7af41c8bdbfe3d4ef421608623e23acf1e7
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #7338 

Based on #8708 

## Proposed changes

Move handling of stage/unstage/reset line patching from FormCommit to FileViewer.
Instead of FormCommit adding menu items to FileViewer, handle
the actions directly in FileViewer, including the hotkey handling.
Also hotkey for general stage/reset lines (previously cherry-pick and revet line patches).
This also aligns the stage/reset menu items to other forms.

Apply the line patching also to RevDiff, supporting line patches for
worktree/index properly, including hotkey handling.
When manipulating a diff involving an artificial commit, refresh the diff

Some code cleanup, like using ViewChangesAsync consistently for diffs/patches

This is a step to avoid using FormCommit to prepare commits

## Screenshots

For WorkTree, Similar for Index
Normal commits gets hotkeys and changed Copy grouping too

### Before

image

image

### After

image

image

## Test methodology 

Manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
CodeFactor complains about complexity for a function with case (3 more added by new hotkeys). I do not see a good way to rewrite that.

**Comment by RussKie** [comment]
Don't worry about it

**Comment by gerhardol** [comment]
Updated for #7831 
(to be squashed on next update)
I considered a nicer solution than enabling the stage/unstage menu item in TextLoaded, but will wait for that for  after #4154 (that partly depends on this PR).
Build fails on translation, I expect this  to go in after #7877.

@mstv @RussKie Can you please review?

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 1]
```diff
@@ -1063,7 +1070,8 @@ private void DiffText_TextLoaded(object sender, EventArgs e)
         /// <returns>If 'artificial' handling</returns>
         private bool IsWorkTreeOrIndexWithParent()
         {
-            if (DiffFiles.SelectedItem == null ||
+            var item = DiffFiles.SelectedItem;
+            if (item == null ||
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs]: Nit: This modification is unnecessary.

Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: It is an effect of my backported changes. I can revert it...

**Comment by gerhardol** [comment]
> Stage/untage file/selected lines seem to work well. But the hotkeys are not shown for the FileStatusList.

I cannot why they do not appear...

> The next thing I really like to have, is that the hotkeys work from the RevisionGrid, too, because it gets focused when switching the artificial commits.

and/or hotkeys for switching between worktree/index, or global keys to select worktree/index and view RevDiff
But that is later, I would like to finish other open items first...

File: GitUI/CommandsDialogs/RevisionDiffControl.cs (hunk 1 above)
Comment (mstv) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: Keep `item` if you are going to use it in a follow up PR.

Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: I reverted that, there will be other changes to the assignment

File: GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs [hunk 2]
```diff
@@ -245,6 +245,7 @@ private void InitializeComponent()
             this.stageFileToolStripMenuItem.Name = "stageFileToolStripMenuItem";
             this.stageFileToolStripMenuItem.Size = new System.Drawing.Size(296, 22);
             this.stageFileToolStripMenuItem.Text = "Stage file(s)";
+            this.stageFileToolStripMenuItem.ShortcutKeyDisplayString = GetShortcutKeyDisplayString(Command.StageSelectedFile);
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs]: Add the following to `ReloadHotkeys` instead:
```C#
            resetFileToParentToolStripMenuItem.ShortcutKeyDisplayString = GetShortcutKeyDisplayString(Command.ResetSelectedFiles);
            stageFileToolStripMenuItem.ShortcutKeyDisplayString = GetShortcutKeyDisplayString(Command.StageSelectedFile);
            unstageFileToolStripMenuItem.ShortcutKeyDisplayString = GetShortcutKeyDisplayString(Command.UnStageSelectedFile);
```

**Comment by mstv** [comment]
> global keys to select worktree/index and view RevDiff

👍 That's the use case. Of course, for later.

File: GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs]: This also fixes that the shortcuts were not shown and makes it reasonable to allow reset file by shortcut (still no popup)
image

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 3]
```diff
@@ -998,14 +1001,25 @@ private bool UnStageSelectedFile()
...
+            {
+                var parents = DiffFiles.SelectedItemParents.ToList();
+                if (parents.Count != 1 || !CanResetToRevision(parents.FirstOrDefault()))
+                {
+                    return false;
+                }
+
+                // Reset to first (parent)
+                ResetSelectedItemsTo(false);
+                return true;
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs]: readability can be improved
```suggestion
                if (parents.Count == 1 && CanResetToRevision(parents.FirstOrDefault()))
                {
                    // Reset to first (parent)
                    ResetSelectedItemsTo(actsAsChild: false);
                    return true;
                }
```

Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: I can agree on the readability and it follows the pattern better, but @RussKie usually requests as early exits as possible...

Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: will change, calculate revisions before first if to reduce depth (readability is more important than a few CPU cycles saved when line patching)

File: GitUI/Editor/FileViewer.cs [hunk 4]
```diff
@@ -336,6 +338,72 @@ public ToolStripMenuItem AddContextMenuEntry(string text, EventHandler toolStrip
             return toolStripItem;
         }
 
+        /// <summary>
+        /// If the file viewer menu supports line patch editing
+        /// </summary>
+        public bool SupportLinePatching { get; set; }
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/Editor/FileViewer.cs]: ok

File: GitUI/Editor/FileViewer.cs [hunk 5]
```diff
@@ -336,6 +338,72 @@ public ToolStripMenuItem AddContextMenuEntry(string text, EventHandler toolStrip
...
+        public void CherryPickContextMenuEntry_OverrideClick(EventHandler cherryToolStripItemClick, EventHandler resetToolStripItemClick)
+        {
+            cherrypickSelectedLinesToolStripMenuItem.Click -=
+                cherrypickSelectedLinesToolStripMenuItem_Click;
+            cherrypickSelectedLinesToolStripMenuItem.Click +=
+                cherryToolStripItemClick;
+
+            revertSelectedLinesToolStripMenuItem.Click -=
+                revertSelectedLinesToolStripMenuItem_Click;
+            revertSelectedLinesToolStripMenuItem.Click +=
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/Editor/FileViewer.cs]: I have gotten used to code in Groovy, where it is preferred to have the operator at the end of the line. Will change

File: GitUI/Editor/FileViewer.cs [hunk 6]
```diff
@@ -336,6 +338,72 @@ public ToolStripMenuItem AddContextMenuEntry(string text, EventHandler toolStrip
...
+            cherrypickSelectedLinesToolStripMenuItem.ShortcutKeyDisplayString = shortcut;
+        }
+
+        /// <summary>
+        /// Set the visibility for the cherry-pick (stage) menu item
+        /// </summary>
+        public void CherryPickContextMenuEntry_Visible()
+        {
+            cherrypickSelectedLinesToolStripMenuItem.Visible =
+                SupportLinePatching = true;
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/Editor/FileViewer.cs]: Separating assign to SupportLinePatching, can remove multiassign. Rename

File: GitUI/Editor/FileViewer.cs [hunk 7]
```diff
@@ -360,16 +428,11 @@ private void SetVisibilityDiffContextMenu(bool visibleTextFile, [CanBeNull] stri
 
             cherrypickSelectedLinesToolStripMenuItem.Visible =
                 revertSelectedLinesToolStripMenuItem.Visible =
+                    SupportLinePatching =
                     visibleTextFile && fileExists && !Module.IsBareRepository();
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/Editor/FileViewer.cs]: see above

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 8]
```diff
@@ -928,5 +943,366 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+            }
+
+            ProcessApplyOutput(output, patch);
+        }
+
+        private void ProcessApplyOutput(string output, byte[] patch)
+        {
+            if (!string.IsNullOrEmpty(output))
+            {
+                MessageBox.Show(this, output + "\n\n" + DiffText.Encoding.GetString(patch), "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: I have noticed that too but it should be separate - in some other places too
(Good to comment unrelated while reviewing, just to be clear what should be handled here)

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 9]
```diff
@@ -928,5 +943,366 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+
+            if (DiffText.ContainsFocus && DiffText.SupportLinePatching)
+            {
+                StageOrCherryPickSelectedLines();
+                return true;
+            }
+            else if (DiffFiles.Focused && DiffFiles.Revision.ObjectId == ObjectId.WorkTreeId)
+            {
+                // Only stage files for WorkTree (even if lines can be cherry-picked/staged)
+                StageFileToolStripMenuItemClick(this, null);
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: Changing to the common pattern to call shared code instead

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 10]
```diff
@@ -928,5 +943,366 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+        private bool UnStageSelectedFile()
+        {
+            if (DiffFiles.Revision.ObjectId != ObjectId.IndexId)
+            {
+                return false;
+            }
+
+            if (DiffText.ContainsFocus && DiffText.SupportLinePatching)
+            {
+                StageSelectedLinesToolStripMenuItemClick(this, null);
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: Changing to the common pattern to call shared code instead

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 11]
```diff
@@ -928,5 +943,366 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+                return true;
+            }
+            else if (DiffFiles.Focused)
+            {
+                UnstageFileToolStripMenuItemClick(this, null);
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: Changing to the common pattern to call shared code instead

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 12]
```diff
@@ -928,5 +943,366 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+            var selectedRev = DiffFiles.Revision;
+            var firstId = DiffFiles.SelectedItemParent?.ObjectId;
+            if ((selectedRev.ObjectId != ObjectId.WorkTreeId
+                 && selectedRev.ObjectId != ObjectId.IndexId)
+                || selectedRev.FirstParentGuid != firstId)
+            {
+                return false;
+            }
+
+            return true;
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: ok

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 13]
```diff
@@ -928,5 +953,357 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+            var parents = DiffFiles.SelectedItemParents.ToList();
+            if (DiffText.ContainsFocus && DiffText.SupportLinePatching)
+            {
+                ResetOrRevertSelectedLines();
+                return true;
+            }
+            else if (DiffFiles.Focused && parents.Count == 1 && CanResetToRevision(parents.FirstOrDefault()))
+            {
+                // Reset to first (parent)
+                ResetSelectedItemsTo(false);
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs]:
```suggestion
                ResetSelectedItemsTo(actsAsChild: false);
```

Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: ok

**Comment by gerhardol** [comment]
> R works for file as expected now. I guess I had not built everything last time.

I have seen this too, since around the time SDK style project was merged. (I did report this in a comment, probably my worst issue description ever). It seem to occur more often if I have not saved before Start/F5, but there has been situations where I thought I saved too.

Dont know how to proceed with that.

**Comment by gerhardol** [comment]
There are some things I am not so happy about with this PR.
Some changes will be simpler with changes that depends on the following:
https://github.com/gitextensions/gitextensions/issues/4154#issuecomment-602254811

Replace ViewCurrentChanges with ViewChangesAsync - to unify

Another is the handling of SelectedDiff.CherryPickContextMenuEntry_Visible(); in TextLoaded. If the file to view is stored in FileViewer as GitItemStatusWithParent then that handling can be built in, as well as the patch handling that currently is slightly duplicated in FileViewer, FormCommit and RevisionDiffControl.

**Comment by gerhardol** [comment]
Squashed review comments and changes due to #7831, rebased on #7868 (to be merged tomorrow, will conflict). If no further review I plan to initiate a merge in two days.

**Comment by gerhardol** [comment]
> Go ahead!

I will give our mighty leader @RussKie a chance to review too, even if he cannot do everything.
(will mark this as off topic myself...)

**Comment by RussKie** [comment]
I'll do it in a day or two, if that's ok

File: GitUI/CommandsDialogs/RevisionDiffControl.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: #7893 created, need to rebase this PR and change this before merge

**Comment by mstv** [comment]
> `R` works for file as expected now. I guess I had not built everything last time.

This is no build issue. Sometimes, `R` works, sometimes not. Then a sound is played as if it was an invalid or not supported key. The menu item `Reset to | First` has always worked. (I have no clue yet what might be the difference in the situations. Explicitly focusing by clicking the FileStatusList does not help.)

**Comment by gerhardol** [comment]
> This is no build issue. Sometimes, R works, sometimes not. Then a sound is played as if it was an invalid or not supported key. The menu item Reset to | First has always worked. (I have no clue yet what might be the difference in the situations. Explicitly focusing by clicking the FileStatusList does not help.)

If no other solution, I suggest disabling the shortcut (as it was initially).

**Comment by mstv** [comment]
We'll make it work. I use it often enough and will watch it. I don't like fiddling with the submenu.

**Comment by mstv** [comment]
`R` works for real commits and for `Commit Index` but not for `Working Directory`.

**Comment by gerhardol** [comment]
> R works for real commits and for Commit Index but not for Working Directory.

For changes to tracked files, it works for me. The command that is executed is the same as for the menu item (just that the menu item is disabled when you cannot reset, like to worktree).

For new files this works as for the reset menu: It does not
This requires some special handling. I would prefer to handle that in #4154 where the first/selected commits is known in the selected item.
A PR for #4154 depends on this PR, that awaits a review from @RussKie 

Adding a commit to simplify merge with #7887 (will be merged first)

**Comment by gerhardol** [comment]
> I'm not content with the new API. I'll need to think through it

I plan further cleanups of the API after #7899, but I guess you do not want any bigger PRs than this?

**Comment by RussKie** [comment]
> * Refactor the FormCommit handling from adding menu items to FileViewer,
>   to reusing cherry-pick/revert items, so the FileViewer menu is aligned
>   The same setup used for the RevisionDiff menus

I'm not happy with this, and I'm not liking the proposed API.
By reusing we're not saving much, but increasing a confusion on multiple levels.
Is there any reason why we can't add new menu items, that have set captions/tooltips/shortcuts/etc, and make them visible/hidden as required?

**Comment by gerhardol** [comment]
> Is there any reason why we can't add new menu items, that have set captions/tooltips/shortcuts/etc, and make them visible/hidden as required?

One reason is consistency, the menu items show up in different positions in different forms.

Then the logic for enabling disabling need to be updated too, FormCommit/RevDiff will have to implement the refresh privately.
(In the current implementation, FormCommit has separate interface to FileViewer, that is to removed in follow up PR with  0a7543701d0119201412b4b9cc075bd084dbc916)

After #7899 I plan to unify the line patch handling and move the logic to FileViewer
(FileViewer will have to save a GitItemStatusWithParents if available and implement most of the logic that are parallel implemented in FileViewer, FormCommit, RevisionDiffControl now)

**Comment by RussKie** [comment]
Ok, if there is a plan to do it in a near future, I'm not going to block it. Though please make these at least "internal".

**Comment by gerhardol** [comment]
> Ok, if there is a plan to do it in a near future, I'm not going to block it. Though please make these at least "internal".

Can you outline what you want to see in a final API?

My plan is to keep the separate event handlers, but have most code common in FileViewer. RevDiff and FormCommit still some handling to refresh.

**Comment by RussKie** [comment]
Can we have an overarching discussion about what we want to achieve in the
target state?
What API we have, what's missing and what needs changing.

There's a lot of change and churn atm, and I'm struggling to keep track of
it.
I don't want to have new methods added for the sake of adding. I'm sure we
can clean the lot as well.

**Comment by gerhardol** [comment]
After #7899
FileViewer.ViewChanges(GitStatusItemWithParents item)
FileViewer can use the item to determine what line stage options that are available as well as the names and icons.
For the EventHandlers, forms may need to perform actions (at least FormCommit and RevDiff to refresh the artificial commits) so the implementation of the event viewer still need to be local for those with specific requirements but most of the code to create and apply patches can be common.

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 14]
```diff
@@ -902,5 +927,357 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+            {
+                return false;
+            }
+
+            if (DiffText.ContainsFocus && DiffText.SupportLinePatching)
+            {
+                StageOrCherryPickSelectedLines();
+                return true;
+            }
+            else if (DiffFiles.Focused && DiffFiles.Revision.ObjectId == ObjectId.WorkTreeId)
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:947]: nit: `else` can be omitted
```suggestion
            
            if (DiffFiles.Focused && DiffFiles.Revision.ObjectId == ObjectId.WorkTreeId)
```

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 15]
```diff
@@ -902,5 +927,357 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+            {
+                return false;
+            }
+
+            if (DiffText.ContainsFocus && DiffText.SupportLinePatching)
+            {
+                StageOrCherryPickSelectedLines();
+                return true;
+            }
+            else if (DiffFiles.Focused)
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:973]: ditto

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 16]
```diff
@@ -902,5 +927,357 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+        /// <returns>true if executed</returns>
+        private bool ResetSelectedFiles()
+        {
+            var parents = DiffFiles.SelectedItemParents.ToList();
+            if (DiffText.ContainsFocus && DiffText.SupportLinePatching)
+            {
+                ResetOrRevertSelectedLines();
+                return true;
+            }
+            else if (DiffFiles.Focused && parents.Count == 1 && CanResetToRevision(parents.FirstOrDefault()))
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:994]: ditto

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 17]
```diff
@@ -902,5 +927,357 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+                patch = PatchManager.GetSelectedLinesAsNewPatch(Module, item.Name,
+                    DiffText.GetText(), DiffText.GetSelectionPosition(),
+                    DiffText.GetSelectionLength(), DiffText.Encoding, false, DiffText.FilePreamble, treeGuid);
+            }
+            else
+            {
+                patch = PatchManager.GetSelectedLinesAsPatch(
+                    DiffText.GetText(),
+                    DiffText.GetSelectionPosition(), DiffText.GetSelectionLength(),
+                    currentItemStaged, DiffText.Encoding, item.IsNew);
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:1167]: Our new style is to have all arguments on one line or on single lines.

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 18]
```diff
@@ -902,5 +927,357 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+                patch = PatchManager.GetResetWorkTreeLinesAsPatch(
+                    Module, DiffText.GetText(),
+                    DiffText.GetSelectionPosition(), DiffText.GetSelectionLength(), DiffText.Encoding);
+            }
+            else
+            {
+                patch = PatchManager.GetSelectedLinesAsPatch(
+                    DiffText.GetText(),
+                    DiffText.GetSelectionPosition(), DiffText.GetSelectionLength(),
+                    false, DiffText.Encoding, false);
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:1128]: ditto arguments

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 19]
```diff
@@ -902,5 +927,357 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+            {
+                patch = PatchManager.GetSelectedLinesAsPatch(
+                    DiffText.GetText(),
+                    DiffText.GetSelectionPosition(), DiffText.GetSelectionLength(),
+                    currentItemStaged, DiffText.Encoding, item.IsNew);
+            }
+            else
+            {
+                patch = PatchManager.GetResetWorkTreeLinesAsPatch(Module, DiffText.GetText(),
+                    DiffText.GetSelectionPosition(), DiffText.GetSelectionLength(), DiffText.Encoding);
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:1246]: ditto arguments

File: GitUI/CommandsDialogs/RevisionDiffControl.cs (hunk 14 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:947]: ok for all

**Comment by gerhardol** [comment]
plan to base this on top of #7899 (when that has been reviewed) and change the API to get @RussKie  happier

**Comment by gerhardol** [comment]
Added a cleanup that should be done since merging #7926, will continue to do also if not it will be merged soon

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 20]
```diff
@@ -1828,16 +1819,27 @@ private void Unstage(bool canUseUnstageAll = true)
...
+            {
+                headRev = null;
+                indexRev = new GitRevision(ObjectId.IndexId);
             }
 
-            return null;
+            var workTreeRev = new GitRevision(ObjectId.WorkTreeId)
+            {
+                ParentIds = new[] { ObjectId.IndexId }
+            };
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormCommit.cs:1841]: Put this on one line as above for `indexRev`, please.

Comment (gerhardol) [reply GitUI/CommandsDialogs/FormCommit.cs]: squashed

**Comment by gerhardol** [comment]
Rebased on master, with review comments and adaption for #7926 

This branch based on #7899: https://github.com/gerhardol/gitextensions/tree/feature/i7338-revdiff-stage-2
Will await a review by RussKie before preparing updates here, there will be too many changes otherwise

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 21]
```diff
@@ -902,5 +927,383 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+
+            applySelectedLines(false);
+        }
+
+        /// <summary>
+        /// apply patches
+        /// Similar to FileViewer.applySelectedLines()
+        /// </summary>
+        /// <param name="reverse">set if patches is to be reversed</param>
+        private void applySelectedLines(bool reverse)
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:1117]:
```suggestion
        private void ApplySelectedLines(bool reverse)
```

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 22]
```diff
@@ -902,5 +927,383 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+            }
+
+            applySelectedLines(false);
+        }
+
+        /// <summary>
+        /// apply patches
+        /// Similar to FileViewer.applySelectedLines()
+        /// </summary>
+        /// <param name="reverse">set if patches is to be reversed</param>
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:1116]:
```suggestion
        /// <summary>
        /// Apply patches.
        /// Similar to FileViewer.ApplySelectedLines()
        /// </summary>
        /// <param name="reverse"><see langword="true"/> if patches is to be reversed; otherwise <see langword="false"/>.</param>
```

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 23]
```diff
@@ -902,5 +927,383 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+            }
+
+            return false;
+        }
+
+        /// <summary>
+        /// Hotkey handler
+        /// </summary>
+        /// <returns>true if executed</returns>
+        private bool UnStageSelectedFile()
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:962]:
```suggestion
        private bool UnstageSelectedFile()
```

File: GitUI/CommandsDialogs/RevisionDiffControl.cs (hunk 21 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:1117]: OK for all

File: GitUI/Editor/FileViewer.cs [hunk 24]
```diff
@@ -383,38 +385,98 @@ public ToolStripMenuItem AddContextMenuEntry(string text, EventHandler toolStrip
...
+        /// If the file viewer menu supports line patch editing
+        /// </summary>
+        public bool SupportLinePatching { get; private set; }
+
+        /// <summary>
+        /// Override the default event handlers
+        /// </summary>
+        /// <param name="cherryToolStripItemClick">Cherry pick event handler</param>
+        /// <param name="resetToolStripItemClick">Reset event handler</param>
+        public void CherryPickContextMenuEntry_OverrideClick(EventHandler cherryToolStripItemClick, EventHandler resetToolStripItemClick)
```
Comment (RussKie) [inline GitUI/Editor/FileViewer.cs:398]: I've been staring at the override API, but I am really struggling to grasp it.

Do you think we could explore a different way to express the desired functionality?
E.g. something like this:

```cs
	// FileViewer.cs

        public class OverrideEvents
        {
            public EventHandler CherryPickSelected;
            public EventHandler ResetSelected;
        }

        public OverrideEvents Overrides { get; } = new OverrideEvents();


        private void SetVisibilityDiffContextMenu(bool isDiff, [CanBeNull] string fileName)
        {
			// ...

            cherrypickSelectedLinesToolStripMenuItem.Visible = SupportLinePatching && Overrides.CherryPickSelected != null;
            revertSelectedLinesToolStripMenuItem.Visible = SupportLinePatching && Overrides.ResetSelected != null;
        }
```

```cs
	// FormCommit.cs

            SelectedDiff.Overrides.CherryPickSelected += StageSelectedLinesToolStripMenuItemClick;
            SelectedDiff.Overrides.ResetSelected += ResetSelectedLinesToolStripMenuItemClick;
```

**Comment by RussKie** [comment]
I'm not sure we're approaching the implementation from the right angle. `FileViewer`'s encapsulation feels very weak, we appear to be manipulating the same menu items over and over by flipping text and icons in the consuming controls... 
This makes it very hard to reason about what and when sets what and track where it gets handled.

Have you considered having "Cherry pick", "Stage selected", "Unstage selected", "Reset selecte", etc. menus, with the same appearance and shortcuts, and have `FileViewer` expose simple API to show/hide these menus, e.g.: 
```cs
bool ShowCherryPickSelected { get; set }
bool ShowStageSelected { get; set }
bool ShowUnstageSelected { get; set }
bool ShowResetSelected { get; set }
```

Alternative handles can be wired up via something like the `Overrides` I proposed in https://github.com/gitextensions/gitextensions/pull/7825/commits/f36a98bb0ef6a305f804c379145e4057c33477be.

This way we will have a bigger menu and more code in `FileViewer` (-) but it will be constrained to `FileViewer` alone (+), and all its consumers will interact with the menu via a simplified API surface (+).

**Comment by gerhardol** [comment]
> . FileViewer's encapsulation feels very weak, we appear to be manipulating the same menu items over and over by flipping text and icons in the consuming controls...

FileViewer has not much details of what it is to show right now. Basically the Forms ask to view Text or Changes, but FileViewer has no information of what revisions to display (except in current master where FormCommit has special handling, a much bigger hack than the API in this PR). Menu Items are somehow adjusted to what is displayed (again, FormCommit has the special hooks to adjust the presentation). RevDiff/Commit uses the Event Text_Changed to enable the correct menu items.

After the text is displayed, FileViewer has no knowledge of what it has displayed. The information about revisions and the file to present is required to perform the actions like staging lines. However, the forms still need to do private actions, like refreshing the views, done from the menu event handlers.

What you are proposing in https://github.com/gitextensions/gitextensions/pull/7825#issuecomment-616136617 is basically to not adjust the CherryPick/Revert menu items but to add extra stage/unstage/reset items. SetVisibilityDiffContextMenu would reset Enable to default but RevDiff/Commit Text_Loaded will then adjust the enabled menus. The code base will increase some though.

Similarly, f36a98bb0ef6a305f804c379145e4057c33477be is handling the event handlers differently. (But event handlers need to be added for all five menu items).

These changes will not change the responsibilities of the modules, just a patchup of the API.
Regardless of these changes, it may be possible to share a little more of the patch and git-apply handling, currently slightly separate in FileViewer/RevDiff/Commit

But before doing these changes, I would like to agree on if the structure should be changed or not.
I will not change many times again, like for other changes and commented on here.

If FileViewer knows what to display, like ```ShowPatch(GitItemStatusWithParents item)``` with first/second revision according to #7899 (some Forms will still use ShowChanges(String text) ). Then FileViewer can enable the menu items and implement the git-apply handling. The event handlers for the staging actions are still needed (possibly to refresh the forms).
But then this PR is dependent of #7899 and at least part of that PR should be merged first.

**Comment by gerhardol** [comment]
Squashed on top of master (now that #7899 is merged)
Set to WIP as this will not be merged before 3.4 and some changes will be done.

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 25]
```diff
@@ -948,5 +973,372 @@ public void SwitchFocus(bool alreadyContainedFocus)
...
+        {
+            var item = DiffFiles.SelectedItem;
+            if (item == null || !item.SecondRevision.IsArtificial)
+            {
+                return false;
+            }
+
+            return (item.SecondRevision.ObjectId == ObjectId.WorkTreeId
+                    || item.SecondRevision.ObjectId == ObjectId.IndexId)
+                   && item.SecondRevision.FirstParentGuid == item.FirstRevision?.ObjectId;
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:1115]: Do you still consider this WIP -- except this minor merge conflict?
```suggestion
                   && item.SecondRevision.FirstParentId == item.FirstRevision?.ObjectId;
```

Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:1115]: This is high priority for me for next release. I get very frustrated when I am not using this and have to use FormCommit...

RussKie requested changes, he was not satisfied with keeping the responsibilities as they are before this PR. 
I therefore have have to rewrite some, which I have not started with yet. (Wanted the changes leading up to 3.4 to settle and not spend all time rebasing, then I want to finish other tasks that are closer to completion.)

Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: I had already changed this in my wip branch...

**Comment by gerhardol** [comment]
Just rebased on master (this is really what I am using myself).
Still trying to rewrite this, going slow. Quite some new code needed (probably more than saved by using common snippets).

**Comment by mstv** [comment]
👍 works well again (shortcuts), (waiting for the refactoring).

**Comment by gerhardol** [comment]
> 👍 works well again (shortcuts), (waiting for the refactoring).

The merge problems was in the private branch only that I had not pushed in a while.
I am not so inspired to rewrite this, it takes some time...

**Comment by gerhardol** [comment]
Rewritten the existing functionality (and thereby this PR) after @RussKie requests.
Still WIP as  #8708 is not merged yet - I actually would like a comment on this PR before merging that PR.
The code is ready for a review though.

**Review by mstv — COMMENTED** [review]
LGTM. Only nits. Will run it later.

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 26]
```diff
@@ -78,17 +79,17 @@ public void UICommands_PostRepositoryChanged(object sender, GitUIEventArgs e)
             _rememberFileContextMenuController.RememberedDiffFileItem = null;
         }
 
-        public void RefreshArtificial()
+        public bool RefreshArtificial()
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:82]: I was using it in an intermediate version, to check if ArtificialCommits were affected, but changed to only run the callback for artificial. There were some thoughts if this wasenough though and I kept this.
So I will revert this change.

File: GitUI/Editor/FileViewer.cs [hunk 27]
```diff
@@ -1665,7 +1877,10 @@ internal enum Commands
             NextChange = 6,
             PreviousChange = 7,
             NextOccurrence = 10,
-            PreviousOccurrence = 11
+            PreviousOccurrence = 11,
+            StageLines = 12,
+            UnstageLines = 13,
+            ResetLines = 14
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/Editor/FileViewer.cs:1883]: OK

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 28]
```diff
@@ -751,9 +723,9 @@ private bool UnStageSelectedFile()
                 UnstageFilesClick(this, null);
                 return true;
             }
-            else if (SelectedDiff.ContainsFocus && _currentItemStaged && _stageSelectedLinesToolStripMenuItem.Enabled)
+            else if (SelectedDiff.ContainsFocus && _currentItemStaged)
             {
-                StageSelectedLinesToolStripMenuItemClick(this, null);
+                SelectedDiff.StageSelectedLines(false);
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormCommit.cs:728]: I prefer to not have too many interface functions, so I go with the first suggestion.

**Comment by gerhardol** [comment]
Rebased on latst #8708 , review comments addressed and a fixup of my own

**Comment by gerhardol** [comment]
Squashed review comments (but not my unreviewed changes) and rebased on master, removed WIP now when #8708 is merged

**Comment by RussKie** [comment]
Since @mstv is happy, let's merge it :)

**Comment by gerhardol** [comment]
Will merge after #8734 

Now I only miss a way to change the commit message for Index commit and a commit button to skip the modal commit dialog in most situations

**Comment by gerhardol** [comment]
Squashed and rebased after #8734 with a minor removal ofunused code in FormCommit:ShowChanges()

**Comment by gerhardol** [comment]
@msftbot merge in 3 days
