### PR TITLE
Fix issue that excess rebase command being performed when continue rebase

### LINKED ISSUE #4593: Excess rebase command being performed when opening the Rebase dialog
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
In the middle of a rebase operation, clicking on the status bar button (_You are in the middle of a rebase_) runs the rebase command again.
@EbenZhang, I believe this was introduced in commit 0ad00e7ebce38be762c314187ddc93c3714643e4.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open the attached [repository](https://github.com/gitextensions/gitextensions/files/1793551/RebaseTest.zip)
1. Right-click on the `master` branch and select _Rebase current branch on →  Selected commit_
1. A merge conflict occurs
1. If the Rebase dialog opens, close it
1. Click on the _You are in the middle of a rebase_ status bar button
1. a `git rebase --autostash "master"` command is performed (and obviously fails) before the dialog opens

**What is the expected behavior?**
No extra rebase command is performed when a rebase operation is already underway.

**Environment you encounter the issue:**

- GitExtensions version: (current master)
- Git version: 2.16.2
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Yes, 2.51.

### PR DESCRIPTION
**Pull request by EbenZhang**
Fixes #4593

Changes proposed in this pull request:
 - Fix the excessive rebase command when continue rebase.

What did I do to test the code and ensure quality:
 - do an interactive rebase, edit one of the commit, and stop in middle
 - press the `you are in middle of a rebase` at the bottom right
 - make sure it only pops up the continue rebase dialog and no rebase has been performed.

Has been tested on (remove any that don't apply):
 - GIT 2.16
 - Windows 10

### CODE REVIEW

File: GitUI/GitUICommands.cs [hunk 1]
```diff
@@ -1485,10 +1485,10 @@ public bool StartRebase(IWin32Window owner, string onto)
                 interactive: false, startRebaseImmediately: true);
         }
 
-        public bool ContinueRebase(IWin32Window owner)
+        public bool StartContinueRebaseDialog(IWin32Window owner)
```
Comment (gerhardol) [inline GitUI/GitUICommands.cs]: I do not get the meaning with StartContinueRebase, is the meaning StartOrContinue or should not Start be there?

Comment (EbenZhang) [reply GitUI/GitUICommands.cs]: it's: start the rebase dialog to continue rebase.
I'll rename it to `StartTheContinueRebaseDialog`

**Comment by gerhardol** [comment]
@RussKie Can we merge after @EbenZhang has rebased?

**Comment by RussKie** [comment]
If it works - go for it.

I'm not sure I will have time to look at anything until the weekend, sorry.
