### PR TITLE
Fixed Bitbucket plugin error on non-Bitbucket repo

### LINKED ISSUE #5147: Bitbucket Server plugin throws on non-Bitbucket repo
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

1. Open GE repo in GE
2. Select Plugins | BitBucket
3. See message box "Your repository is not hosted in Bitbucket."
4. See exception dialog

```
System.ObjectDisposedException
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Bitbucket.BitbucketPlugin.Execute(GitUIEventArgs args) in C:\Users\Drew\dev\tools\gitextensions\Plugins\Bitbucket\BitbucketPlugin.cs:line 28
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass70_0.<RegisterPlugins>b__1(Object <p0>, EventArgs <p1>) in C:\Users\Drew\dev\tools\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 548
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**What is the expected behavior?**

No error.

**Environment you encounter the issue:**

- GitExtensions version: v3-ux (probably master too)
- GIT version: N/A
- OS version: Win 10
- .NET version: 4.7.2

**Did this work in previous version of GitExtensions (which)?**

Not sure.

### PR DESCRIPTION
**Pull request by oriash93**
Fixes #5147 

Changes proposed in this pull request:
- Fixed Bitbucket plugin server error on non-Bitbucket repo.
The error was trying to use BitbucketPullRequestForm after it was disposed.

What did I do to test the code and ensure quality:
- Run the scenario and made sure the bug does not reproduce.

### CODE REVIEW

File: Plugins/Bitbucket/BitbucketPlugin.cs [hunk 1]
```diff
@@ -22,7 +22,10 @@ public override bool Execute(GitUIEventArgs args)
         {
             using (var frm = new BitbucketPullRequestForm(this, Settings, args))
             {
-                frm.ShowDialog(args.OwnerForm);
+                if (!frm.IsDisposed)
```
[the remark this answers is not in the document]
Comment (oriash93) [reply Plugins/Bitbucket/BitbucketPlugin.cs]: I agree, didn't see the bigger picture here.

File: Plugins/Bitbucket/BitbucketPullRequestForm.cs [hunk 2]
```diff
@@ -24,7 +23,7 @@ public partial class BitbucketPullRequestForm : GitExtensionsFormBase
         private readonly Settings _settings;
         private readonly BindingList<BitbucketUser> _reviewers = new BindingList<BitbucketUser>();
 
-        public BitbucketPullRequestForm(BitbucketPlugin plugin, ISettingsSource settings, GitUIEventArgs gitUiCommands)
+        internal BitbucketPullRequestForm(Settings settings)
```
Comment (RussKie) [inline Plugins/Bitbucket/BitbucketPullRequestForm.cs]: Why has the visibility changed?

Comment (oriash93) [reply Plugins/Bitbucket/BitbucketPullRequestForm.cs]: Because `Settings` class is internal. Maybe I should have changed that class to public :haha:

File: Plugins/Bitbucket/BitbucketPlugin.cs [hunk 3]
```diff
@@ -20,7 +23,14 @@ public BitbucketPlugin()
 
         public override bool Execute(GitUIEventArgs args)
         {
-            using (var frm = new BitbucketPullRequestForm(this, Settings, args))
+            Settings settings = Bitbucket.Settings.Parse(args.GitModule, Settings, this);
+            if (settings == null)
+            {
+                MessageBox.Show(_yourRepositoryIsNotInBitbucket.Text);
```
Comment (RussKie) [inline Plugins/Bitbucket/BitbucketPlugin.cs]: Please pass `owner`. Also may worth setting the icon to the error.

File: Plugins/Bitbucket/BitbucketPlugin.cs [hunk 4]
```diff
@@ -12,6 +13,8 @@ public class BitbucketPlugin : GitPluginBase
         public readonly StringSetting BitbucketBaseUrl = new StringSetting("Specify the base URL to Bitbucket", "https://example.bitbucket.com");
         public readonly BoolSetting BitbucketDisableSsl = new BoolSetting("Disable SSL verification", false);
 
+        private readonly TranslationString _yourRepositoryIsNotInBitbucket = new TranslationString("Your repository is not hosted in Bitbucket.");
```
Comment (gerhardol) [inline Plugins/Bitbucket/BitbucketPlugin.cs]: Should say BitBucket Server (previous Stash, not the same as bitbucket.org).
(This is not a new string, same in existing code.)

File: Plugins/Bitbucket/BitbucketPullRequestForm.cs (hunk 2 above)
Comment (oriash93) [reply Plugins/Bitbucket/BitbucketPullRequestForm.cs]: Changed it back.

File: Plugins/Bitbucket/BitbucketPlugin.cs (hunk 3 above)
Comment (oriash93) [reply Plugins/Bitbucket/BitbucketPlugin.cs]: Done and done.

File: Plugins/Bitbucket/BitbucketPlugin.cs (hunk 4 above)
Comment (oriash93) [reply Plugins/Bitbucket/BitbucketPlugin.cs]: Done.

**Comment by RussKie** [comment]
Please resolve conflicts and squash.

**Comment by drewnoakes** [comment]
The two conflicts are minor and can be fixed in the browser.

- One conflict is around `using` directives (make sure they end up in alphabetical order to prevent compile error)
- The other is due to fixing a typo (~~~commited~~~ -> committed).

**Comment by drewnoakes** [comment]
Thanks!
