### PR TITLE
Fix test dependent on file watcher delay

### LINKED ISSUE #6329: Flaky DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/22757682/tests

### PR DESCRIPTION
**Pull request by sharwell**
Observed this test as flaky in a few builds and tracked it down to a race condition in the configuration file.

Fixes #6329

### CODE REVIEW

File: UnitTests/GitUITests/Editor/FileViewerTextTests.cs [hunk 1]
```diff
@@ -41,7 +41,9 @@ public void DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending(AutoCRLFTy
         {
             using (var testHelper = new GitModuleTestHelper())
             {
-                testHelper.CreateRepoFile(@".git\config", $"[core]\n\tautocrlf = {autoCRLFType}");
+                testHelper.Module.LocalConfigFile.SetEnum("core.autocrlf", autoCRLFType);
+                testHelper.Module.LocalConfigFile.Save();
```
Comment (sharwell) [inline UnitTests/GitUITests/Editor/FileViewerTextTests.cs]: 📝 If this continues to be flaky, the likely cause in the file system not assigning a new timestamp to this save operation, immediately following the first save operation in the constructor.

**Comment by jbialobr** [comment]
Have you noticed that our tests occasionally hang?
https://ci.appveyor.com/project/spdr870/gitextensions-f0pvf/builds/22747806/messages

**Comment by RussKie** [comment]
@spdr870 why are builds going to your project again?

**Comment by spdr870** [comment]
> @spdr870 why are builds going to your project again?

Do not know, the settings are not changed and seem correct. In the console it also points to the correct repository.
image

image

**Comment by RussKie** [comment]
Yet the build link points to your project
image

Is your personal fork's config somehow competes with the project's config? 🤔
