### PR TITLE
fix: Recent repositories history size not respected

### LINKED ISSUE #3908: Bug: Recent repositories settings / max number not respected
**What is the current behavior?**

Bug report: when setting the _"Maximum number of most recent repositories"_ to a high number, that number is not respected. Instead a maximum of 30 (?) repositories are remembered.

ge screenshot recent repos

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

* Open the repository dropdown and click on "Configure this menu"
* Set the max number of recent repos to 100
* Open a number of repos to make sure you go over thirty recently opened repos.

**What is the expected behavior?**

That the number would be respected.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version: 2.14.1.windows,1
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**
No, the bug has been around for as long as I remember.

Loosely related to #3769 / #3780

### PR DESCRIPTION
**Pull request by RussKie**
Recent repositories history size is set to 30 without any ability to change. The "recent repositories settings" form provides the ability to set "Maximum number of most recent repositories" which does
not have any effect on the history size and it is not used anywhere else.

The fix deprecates "MaxMostRecentRepositories" setting and consolidates the use of "history size" setting.

Fixes #3908
 
Screenshots before and after (if PR changes UI):
image
image

Has been tested on (remove any that don't apply):
 - GIT 2.10 and above
 - Windows 10 and above

### CODE REVIEW

File: GitCommands/Repository/RecentRepoInfo.cs [hunk 1]
```diff
@@ -68,7 +68,7 @@ public class RecentRepoSplitter
 
         public RecentRepoSplitter()
         {
-            MaxRecentRepositories = AppSettings.MaxMostRecentRepositories;
```
Comment (jbialobr) [inline GitCommands/Repository/RecentRepoInfo.cs]: MaxMostRecentRepositories should be untouched, you have to introduce a new setting for RecentRepositoryHistorySize

Comment (RussKie) [reply GitCommands/Repository/RecentRepoInfo.cs]: reworked

**Comment by jrfnl** [comment]
Thank you @RussKie !
