### PR TITLE
Show Stash in rev grid

### LINKED ISSUE #5371: Show all stashes in the revision grid
**Do you want to request a *feature* or report a *bug*?**
enhancement (low prio, primarily logged as an issue if someone else stumbles on this, too)

**What is the current behavior?**
Multiple stashes (with identical names based on the same revision) are not shown separately in the Revision grid.
In general, Git Extensions shows only the latest stash in the Revision grid (see gerhardol's comment below)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* checkout (the most recent) branch and modify a file
* stash the changes
grafik
* modify a file and stash the changes
grafik
* open the stash manager and drop down the list of stashes
grafik

**What is the expected behavior?**
All stashed should be visible in the Revision grid.
gerhardol: A second enhancement could be to allow for manipulations of stashes in Revision grid.

**Environment you encounter the issue:**

- GitExtensions version: master **and** 2.51.02
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
no

### LINKED ISSUE #9873: Add stash options for context menu
### Feature description

The idea of context menu as I understand it is to have alternative interaction options with given item in most-used first order.

When right-clicking a stash on the tree, the first options should be to:

- pop this stash - allows for easily finding relevant stashes in tree history instead of doing typical error-prone pop or finding the stash through the dedicated dialog
- apply this stash (apply diff without deleting stash)
- delete this stash - allows for stash cleanup as you go instead of finding them in separate dialog and deleting them there.

I'm in the process of migrating from GitKraken and lack of this little UX feature makes using Git Extensions a bit tedious. :(

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4470.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Resolves #5371 (and #5785
Fixes #9873

## Proposed changes

Show stash commits in the revision grid, with menu options to pop and drop stashes.

A stash is implemented in Git with 3 internal commit.
Some more explanations in GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:988
The implementations I have seen do not expose the third commit with untracked files.
The PR includes this "untracked" commit (empty "untracked" are filtered) for the first 10 stashes (see Performance below for details).
This setting is read from the settings but no setter is exposed, mostly because there is no natural place to show it (maybe in View is the best, but other similar settings are in General, that is considered full).

The implementation by default only show the stashes where the parents are shown in the grid.
So for instance if you stash and then rebase then the stash is not shown (but see below).
Unless reflogs are shown, only stashes that are related to commits visible in the grid is shown.
(Another difference with reflog is that stashes are presented in Git order, the "inserted" stashes are always shown related to the main commit).

The label for stash commits is partly for this reason set to the reflog selector like "stash@{0}" (required to pop/drop stashes) (another reason is to not get lost too easy when looking at commits, especially when many stashes are created for the same commit).
(For instance GitKraken shows these commits.)
FormStash can still be used to see these, they could also be added to the side panel (similar to SourceTree) (but the contents would not be shown). See #5460.
(Sublime merge shows both in grid and sidepanel)

GE currently always show the latest stash, this was expected by mstv in the initial version.
The latest stash is therefore always shown if stashes are shown.
This commit will always include the index and untracked commits.
See https://github.com/gitextensions/gitextensions/pull/10138#issuecomment-1236200583 for a discussion about how that could be changed.

There is no new menu operation to create a stash, use stash button or Ctrl-Alt-Up to create a stash.
Create a stash operate on both Index and WorkTree commits, so there is no natural way to connect this to a revision (but _partial_ commit should be possible to create in RevDiff).
FormStash was improved in #9303 too.

### Performance

Loading revisions in 4.0 is heavily optimized, some performance measurements to ensure there is no regression.
(I have tried to make sure the addition has minimal impact on performance).

My GE repo has 19400 commits and 542 stashes, testing on Win10 with Zen2600, 16GB, SSD.
I consider 542 stashes to be an upper limit to what is reasonable to test with.

If stashes are not displayed, basically one null variable is, adding less than 1 ms to process all revisions. So usecases not showing stashes are not affected.
Enabled but no existing stashes has a few more checks, affects loading with about 9 ms.

Times are approximate, some variation (+/- 30 ms), but relative consistent differences.
Time will be affected by number of cores etc
Refreshing refs is done in three partly parallel steps:

1. Getting refs and checkout
Total step 175 ms (git-for-each-ref 125 ms)

2. Getting Stash commit (10 stash checked for untracked)
Total step 175 ms (git-stash-list 95 ms, git-log <untracked-id> 70 ms)
If this time is higher than step 1 the load time is increasing.
Note that the second Git command for untracked is not needed if reflog is shown.

3. Getting revisions
Total git-log time 600 ms but first revision is delivered and could be processed for display after 140 ms (this is when the spinner is replaced with "Loading" in upper right corner) (as refs are slower, revgrid will be updated 35 ms after this)
(if sorting in the grid is enabled, revisions will be shown with at least a 100 ms delay)
Processing time to find if stashes should be added is about 9 ms.
The GUI update is done in about the time that git-log runs.
The "Loading" label is then removed, but some additional CPU may be needed for selecting a new revision (if filtering changed).

Stashes slow down showing revisions in the grid with about 9 ms plus possible additional time due to parallel processing overhead (but I have not seen any faster ref handling with stash disabled).
This is assuming that the 10 "untracked" takes the same time as getting refs, which in my case is 10, which I also believe is an OK value of untracked to show.
0 untracked limits step 2 with 60 ms (but revisions are not shown earlier), 50 untracked adds 30 ms and all 542 adds 400 ms.

Brief tests with Linux repo in wsl limited to 100000 commits shown with one local branch and 10 stashes.
With so few refs, refs are handled in 150 ms and stash-list in 170 and listing untracked will add 100 ms and 50 ms (processing adding to grid) out of total 4.1 s. So hardly noticeable.

## Screenshots 

With reflogs shown, the change is that labels and menu operations are enabled for all commits.

### Before

Latest stash shown

image

### After

If parent commit is not shown, stash is not shown (first is shown though, not updated example)

image

Other commits are shown, "untracked" commit only if it is not empty

image

Menu

image

## Test methodology 

A few tests added, some modified.

## Test environment(s) 

Git 2.37.1
No other version tested, nothing seen in the Git doc about any compatibility.

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
I have not had a look at the details yet.
Though the current approach does not display (the most recent) stash if it is based on an invisible commit, e.g. "disappears" after a rebase.
The stash index is shown also only if the reflog is shown.

**Comment by gerhardol** [comment]
Latest stash can always be included (it is explicitly excluded now), but then the latest stash will always look like 
image

But maybe a fixed number of stashes can always be added ("stash@{0} stash@{1} stash@{2} ... stash@{20}") by default.
Then there would be a smaller delay then if stashes have to be queried first (so maybe 20 ms extra instead of 200 ms in my GE clone).

The full info should be seen in the side panel (not implemented).

**Comment by gerhardol** [comment]
Some measurements:
git-log <stash@{} for 542 stashes> adds about 550 ms to the listing of the first commit. Limiting to 20 adds about 20 ms. (So about 1 ms/commit. So if "force include" is used, the list should be limited. This will require a hard to explain configuration. I canparse about 2000 stashes, then the command line get too long.

To avoid adding the "index" commit and empty untracked, processing time added is about 10 ms, similar handling as for inserting untracked commits

**Comment by mstv** [comment]
> Latest stash can always be included (it is explicitly excluded now), but then the latest stash will always look like the following, unless there are some funky code to remove the index and empty untracked commits. image 

That's how it used to be. Some of this info is rarely really needed indeed. Though stashes can be not just one commit. So, alright for me.

> But maybe a fixed number of stashes can always be added ("stash@{0} stash@{1} stash@{2} ... stash@{20}") by default.

Will Git complain if there are fewer stashes?

> Then there would be a smaller delay then if stashes have to be queried first (so maybe 20 ms extra instead of 200 ms in my GE clone).

👍
I think 10 would suffice.

**Comment by gerhardol** [comment]
> > But maybe a fixed number of stashes can always be added ("stash@{0} stash@{1} stash@{2} ... stash@{20}") by default.
> 
> Will Git complain if there are fewer stashes?

No, that is fine.

> > Then there would be a smaller delay then if stashes have to be queried first (so maybe 20 ms extra instead of 200 ms in my GE clone).
> 
> 👍 I think 10 would suffice.

I have a problem explaining this setting, so not keen on it.
As `rev-parse stash@{0} etc` can take long time, the complete stash listing should probably be done before listing in the grid, always delaying commit presentation.
(Except for reflog when the stashes are added anyway)

**Comment by mstv** [comment]
> I have a problem explaining this setting, so not keen on it.

OK, so explicitly request just the most recent stash.

**Comment by RussKie** [comment]
Perhaps worth considering bumping the stash'related menus to the top:
image

**Comment by gerhardol** [comment]
> > I have a problem explaining this setting, so not keen on it.
> 
> OK, so explicitly request just the most recent stash.

Changed to show the latest stash if ShowStashes

If  (currently hidden) and `MinimumStashesAlwaysInGrid` are added in settings, the descriptions could be something like below.
Likely a follow up. Similar with stash in sidepanel.

image

`ShowStashes`
(Checkbox as in _View_ menu)

`MinimumStashesAlwaysInGrid` (default 1)
Stashes in the grid are by default shown in the grid if the parent commit is visible in the revision grid.
(If reflogs are shown, all commits including all stashes are shown.)
This setting will ensure that the stashes are added to the grid.
Note that the _index_ and _untracked_ commits are always included.
Note: Setting this value to a high value may delay the display of commits.

`MaxStashesWithUntrackedFiles` (default 10)
By default only `MinimumStashesAlwaysInGrid` stashes will include the stash commit with untracked files.
This setting will include the untracked commit (unless it is empty) for additional stashes.
Note: Setting this value to a high value may delay the display of commits.

**Comment by gerhardol** [comment]
squashed, rebased (mstv had pulled the latest updates so they could be reviewed...) and updated the description, removed draft.

**Review by RussKie — COMMENTED** [review]
A quick review, will need more time for a more in depth review

File: GitCommands/RevisionReader.cs [hunk 1]
```diff
@@ -42,18 +42,107 @@ public sealed class RevisionReader
...
+
+                    if (TryParseRevision(chunk, out GitRevision? revision))
+                    {
+                        stashes.Add(revision);
+                    }
+                }
+            }
+
+            return stashes;
+        }
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/RevisionReader.cs:95]: This is leading revisions, just a different Git command than the git-log currently in the class.
So an instance of RevisionReader is needed regardless.

File: GitCommands/RevisionReader.cs [hunk 2]
```diff
@@ -42,18 +42,107 @@ public sealed class RevisionReader
...
+
+        /// <summary>
+        /// Get the GitRevisions for the listed files,
+        /// excluding commits without changes.
+        /// </summary>
+        /// <param name="untracked">commit list</param>
+        /// <param name="token">Cancellation token</param>
+        /// <returns>List with GitRevisions</returns>
+        public List<GitRevision> GetRevisionsFromList(IList<ObjectId> untracked, CancellationToken token)
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/RevisionReader.cs:104]: We can settle on cancellationToken, starting with this PR

File: GitCommands/RevisionReader.cs [hunk 3]
```diff
@@ -42,18 +42,107 @@ public sealed class RevisionReader
...
+                    }
+                }
+            }
+
+            return stashes;
+        }
+
+        /// <summary>
+        /// Get the GitRevisions for the listed files,
+        /// excluding commits without changes.
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/RevisionReader.cs:99]: ok

File: GitCommands/RevisionReader.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/RevisionReader.cs:104]: What is the benefit with this?
I find it easier to read checking the size (and slightly more efficient even if that is not a focus here).

[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/RevisionReader.cs]: Changed the existing code in this module
About 100 more occurrences, excluding tests, translations and externals

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs [hunk 4]
```diff
@@ -189,6 +193,22 @@ private void InitializeComponent()
...
+            this.popStashToolStripMenuItem.Size = new System.Drawing.Size(264, 24);
+            this.popStashToolStripMenuItem.Text = "Pop &stash...";
+            this.popStashToolStripMenuItem.Click += new System.EventHandler(this.PopStashToolStripMenuItemClick);
+            // 
+            // dropStashToolStripMenuItem
+            // 
+            this.dropStashToolStripMenuItem.Image = global::GitUI.Properties.Images.Stash;
+            this.dropStashToolStripMenuItem.Name = "dropStashToolStripMenuItem";
+            this.dropStashToolStripMenuItem.Size = new System.Drawing.Size(264, 24);
+            this.dropStashToolStripMenuItem.Text = "&Drop stash...";
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs:209]: These dots imply there was a confirmation dialog. But it is missing. Add the optional confirmation, please. We already have a regarding AppSetting (which I do not turn off).
Dropped stashes are hard to recover. They do not appear in the RefLog.
After `recovering` the `lost object`, the commit is filtered out somehow as long as RefLog references are shown.

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 5]
```diff
@@ -1154,6 +1214,32 @@ void OnRevisionRead(GitRevision revision)
...
+                if (stashesById is not null)
+                {
+                    if (stashesById.TryGetValue(revision.ObjectId, out GitRevision gridStash))
+                    {
+                        revision.ReflogSelector = gridStash.ReflogSelector;
+
+                        // Do not add this again (when the main commit is handled)
+                        stashesById.Remove(revision.ObjectId);
+                    }
+                    else if (stashesByParentId?.Contains(revision.ObjectId) ?? false)
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1226]: Nit: I would prefer
```suggestion
                    else if (stashesByParentId?.Contains(revision.ObjectId) is true)
```

File: GitCommands/Settings/AppSettings.cs [hunk 6]
```diff
@@ -1085,10 +1085,17 @@ public static bool ShowReflogReferences
...
-            set => SetBool("showLatestStash", value);
+            get => GetBool("showStashes", true);
+            set => SetBool("showStashes", value);
+        }
+
+        // No official setting
+        public static int MaxStashesWithUntrackedFiles
+        {
+            get => GetInt("maxStashesWithUntrackedFiles", 10);
+            set => SetInt("maxStashesWithUntrackedFiles", value);
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/Settings/AppSettings.cs:1098]: changing this here too, as well as aligning the comment

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs (hunk 4 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs:209]: OK
Making a temporary change to hide the option for now

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs (hunk 5 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1226]: OK

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs (hunk 4 above)
Comment (mstv) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs:209]: > Making a temporary change to hide the option for now

OK. We can activate it in a follow-up - as well as add `Apply stash`.

**Comment by mstv** [comment]
>> After `recovering` the `lost object`, the commit is filtered out somehow as long as RefLog references are shown.

The restored commit "LOST_FOUND_1" (and the index commit) is not returned by
`git -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B"`
neither with nor without `--reflog`.
How is it found and added if **not** showing RefLog references?
The base commit c9b8c5d is only returned *with* `--reflog`. Weird!
 
image

File: GitCommands/RevisionReader.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/RevisionReader.cs]: We constantly reading revisions, and this code is on the hot path. So we want to avoid memory churn as much as possible.

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs (hunk 4 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs:209]: "stash apply" is basically the same command as git-cherry-pick so it is not really needed. stash apply can be applied to any commit.

But as the menu is only for stash I guess it is not much in the way.

To be clear: I will remove the stash-drop (unless I get around to create a confirmation) before merging this if approved.

File: GitCommands/RevisionReader.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/RevisionReader.cs]: I did not see any improvement for allocation in your proposal, just a slower check.

For performance and allocation when loading, the important path is the reading of revisions (in RevisionReader that is optimized with my best effort) and in RevGrid (can likely be a few tuning done). The general improvement is to avoid calling Git when not needed.
I am adding an if and a null allocation in this PR to the rev reading loop, which will add ms.
(Replacing String.Empty with "" and removing precompiled regex is a more obvious optimization...)

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs (hunk 4 above)
Comment (mstv) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs:209]: > I will remove the stash-drop (unless I get around to create a confirmation) before merging this if approved.

It has already been implemented in FormStash - with optional confirmation.
If you omit this menu item, I will add it myself.

> "stash apply" is basically the same command as git-cherry-pick.

Is this also true for complex stashes, e.g. with untracked files?

Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs:219]: I added _Apply stash_ as well as a confirmation for drop stash
(Same keyboard accelerator for stash-apply as for cherry-pick)

> Is this also true for complex stashes, e.g. with untracked files?

The dialog lists the untracked commit but do add the files. (index commit files are included, but they are included in the main commit already). Could be an issue in the dialog, not investigated (do not plan to).

I just did not see the usefulness of appy stash myself, but if you ask for it, other may do that too.
Did not want to add too many bells and whistles before I know if it will be accepted.

File: GitCommands/RevisionReader.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/RevisionReader.cs]: I made a simple refactoring and changed this code slightly.

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 7]
```diff
@@ -2152,6 +2246,71 @@ private void CherryPickCommitToolStripMenuItemClick(object sender, EventArgs e)
...
+
+        private void PopStashToolStripMenuItemClick(object sender, EventArgs e)
+        {
+            var stashName = LatestSelectedRevision.ReflogSelector;
+            if (string.IsNullOrEmpty(stashName))
+            {
+                return;
+            }
+
+            UICommands.StashPop(this, LatestSelectedRevision.ReflogSelector);
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:2263]: nit:
```suggestion
            string stashName = LatestSelectedRevision.ReflogSelector;
            if (string.IsNullOrEmpty(stashName))
            {
                return;
            }

            UICommands.StashPop(this, stashName);
```

**Review by mstv — APPROVED** [review]
👍 Thank you
Fixes #9873

**Comment by gerhardol** [comment]
Plan to squash and rebase tomorrow
@RussKie @pmiossec Any objections to merging and including in 4.0?

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs [hunk 8]
```diff
@@ -120,6 +123,9 @@ private void InitializeComponent()
             this.stopBisectToolStripMenuItem,
             this.bisectSeparator,
             this.copyToClipboardToolStripMenuItem,
+            this.applyStashToolStripMenuItem,
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs:126]: Please add a separator after the "Copy to clipboard" menu item.

**Review by RussKie — COMMENTED** [review]
Looked through on a phone in a browser. I don't have any major objections. Supportive of taking it in to the release.

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs (hunk 8 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs:128]: Changed this in the latest commit before squashing and updating the commit message.

**Comment by gerhardol** [comment]
Plan to merge this tomorrow
