### PR TITLE
Show diff for last selected file

### LINKED ISSUE #3510: File diff window always shows the top most file in a multiple selection
GitExt version 2.49.
On Windows 7 service pack 1.

**Observed Behavior**
While in the diff window, if the user uses the ctrl or shift key to select multiple files in the left file pane, the right file diff pane will always show the top most selected file. This leads to inconsistent and undesirable behavior.

If you select a file and then hold shift or ctrl, and then add another file to the selection, AND the other file is below the first file in ordering, the right file diff view will remain on the previous file.

If you select a file and then add a file to selection that is above it in the file view, the file diff view will now change to the second selected file.

**Expected Behavior**
The more desirable behavior is that the last clicked file will always be the file that is shown in the right diff view pane.

The use case where this behavior is desirable is when selecting multiple files to apply the "Reset File to" command to.

A user could then click a file and inspect it in the right pane and decide if this files changes should be reverted. Then the user could ctrl click another file to add it to the selection, and because the diff view on the right updated to it, determine if its changes are to be tossed out ( in which case the user could ctrl click to unselect). The user would then be able to add to selection and inspect until all the files have been assessed, and the batch selection is ready to be "reset files to".

In the current observed behavior, you must either assess all the files you want to revert, then remember them, then batch select them all once they have been assessed. Or you can select from the bottom up, which is an un-intuitive workaround.

### PR DESCRIPTION
**Pull request by NikolayXHD**
Fixes #3510

Purpose:
> Expected Behavior
The more desirable behavior is that the last clicked file will always be the file that is shown in the right diff view pane.

Changes proposed in this pull request:
- show the focused item if it is selected
- show any other selected item otherwise

Tested on Windows 7

### CODE REVIEW

File: GitUI/Editor/FileViewerInternal.cs [hunk 1]
```diff
@@ -119,8 +119,10 @@ public void SetText(string text, Action openWithDifftool, bool isDiff = false)
             }
 
             TextEditor.BeginUpdate();
-            TextEditor.ShowLineNumbers = !isDiff;
             TextEditor.Text = text;
+
+            // important to set after the text was changed
+            TextEditor.ShowLineNumbers = !isDiff;
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitUI/Editor/FileViewerInternal.cs]: I opened #5572 but your fix is better 👍 
I'm going to copy your fix into #5572 and push it since it addresses a specific bug.

[the remark this answers is not in the document]
Comment (NikolayXHD) [reply GitUI/Editor/FileViewerInternal.cs]: > Is this a fix for #5568?

exactly, the screnshot in #5568 shows what I observed.

File: GitExtUtils/GitUI/UIExtensions.cs [hunk 2]
```diff
@@ -47,5 +50,34 @@ public static bool IsFixedWidth(this Font ft, Graphics g)
...
+        public static IEnumerable<T> SelectedItemTags<T>(this ListView listView) =>
+            listView.SelectedItems().Select(Tag<T>);
+
+        /// <summary>
+        /// <para>For practical purposes: The last <see cref="ListViewItem"/> added to selection.</para>
+        /// <para>Actually: Focused item if selected, otherwise first selected item</para>
+        /// </summary>
+        public static ListViewItem LastSelectedItem(this ListView listView) =>
+            listView.FocusedItem?.If(_ => _.Selected) ??
+            listView.SelectedItems().FirstOrDefault();
```
Comment (RussKie) [inline GitExtUtils/GitUI/UIExtensions.cs]: Let's move it out to `ListViewExtensions` or something like that

File: GitUI/UserControls/FileStatusList.cs [hunk 3]
```diff
@@ -242,7 +231,8 @@ public int SelectedIndex
         [Browsable(false)]
         public GitItemStatus SelectedItem
         {
-            get { return SelectedItems.FirstOrDefault(); }
+            get => FileStatusListView.LastSelectedItem()?.Tag<GitItemStatus>();
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]: to keep stylistic consistency between `get` and `set` in this instance, please have `get { ... }`
the same applies to other similar cases

File: GitExtUtils/GitUI/UIExtensions.cs [hunk 4]
```diff
@@ -47,5 +50,34 @@ public static bool IsFixedWidth(this Font ft, Graphics g)
...
+
+        public static IEnumerable<T> ItemTags<T>(this ListView listView) =>
+            listView.Items().Select(Tag<T>);
+
+        public static IEnumerable<T> SelectedItemTags<T>(this ListView listView) =>
+            listView.SelectedItems().Select(Tag<T>);
+
+        /// <summary>
+        /// <para>For practical purposes: The last <see cref="ListViewItem"/> added to selection.</para>
+        /// <para>Actually: Focused item if selected, otherwise first selected item</para>
```
Comment (gerhardol) [inline GitExtUtils/GitUI/UIExtensions.cs]: It makes more sense to select the last file in the list. This is how FormCommit worked (FormBrowse selected first though)

File: GitExtUtils/GitUI/UIExtensions.cs (hunk 2 above)
Comment (NikolayXHD) [reply GitExtUtils/GitUI/UIExtensions.cs]: ok

File: GitExtUtils/GitUI/UIExtensions.cs (hunk 4 above)
Comment (NikolayXHD) [reply GitExtUtils/GitUI/UIExtensions.cs]: agree

**Comment by RussKie** [comment]
I haven't run it, but given that Gerhard approved it twice I trust it is good 👍
