### PR TITLE
Fix statistics plugin not showing line counts

### LINKED ISSUE #12746: Some tabs in Statistics plugin load indefinitely
### Environment

- Git Extensions 6.0.5.18375
- Build 069d8b7789e806682c97baaeca36e5f3b8b0973f
- Git 2.52.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 9.0.11
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 8.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 9.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 9.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 10.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 10.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

### Issue description

Any of the last three tabs shown in the screenshot below (from the Plugins -> Statistics menu) appear to simply show the title and the text "Loading...", whereas the first tab loads immediately. This is a really small project, so at most 1000 lines of c# source code (see the repo url in reproduction steps), thus should not take long to load at all.

Image

The only command that appears to be run when opening the statistics window (git command log (f12)) is `"D:\Program Files\Git\bin\git.exe" shortlog --all -s -n --no-merges` which finishes with code 0 after 91ms, so that seems totally fine. When closing it, `"D:\Program Files\Git\bin\git.exe" config list --local --includes --null` gets executed.

Image

One really interesting aspect are the filters, which are set in the 'Effective' view but not in the other three (Local, Distributed and Global):

Set in here:
Image

Not set in here:
Image

When going back to Effective after having looked at Local, they are also gone there:
Image

But clicking Cancel and reopening this menu appears to bring them back. Perhaps this has something to do with this? Though i have never tweaked these filters to my knowledge. What made the issue appear for me was updating from a previous Major version (either 3.x,4.x or 5.x) to 6.x a few revision-versions ago, though it is still present in the one that i have updated to today.

### Steps to reproduce (updated)

0. Create a fresh Windows 10 64 bit VM, install git, git extensions, kdiff3 via winget
1. Clone https://github.com/GHXX/SteamEngineSimController (though it also appears to happen with all other repositories, one even written in Java, batch and powershell), via git extensions, though that should not matter
2. Open the repository with git extensions (6.x.x.x); 
  2.1. Check out the master branch, though this is the default one anyway
3. Click on Plugins > Statistics
4. Click on any tab besides Commits per contributor (e.g. click on Lines of code per language)
5. (Hopefully) observe that they appear to be loading forever

### Did this work in previous version of GitExtensions?

Yes, definitely in at least one of the previous major versions, so most likely it worked in 3.x, but likely even 4.x and maybe even 5.x.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by GHXX**
Fixes #12746

## Proposed changes

The statistics plugin stopped being able to count lines in commit 3948354070b92c73e8e2c50447ef00e6ef2e52eb.
This commit appears to have tweaked argument building a bit, by setting commitId to null (and meaning HEAD by that). See https://github.com/gitextensions/gitextensions/commit/3948354070b92c73e8e2c50447ef00e6ef2e52eb#diff-8f9b8a7437f617ff1c6cb1bed00aff1835abe42fde0a9478ef8e770f6ef64b6dL185 and https://github.com/gitextensions/gitextensions/commit/3948354070b92c73e8e2c50447ef00e6ef2e52eb#diff-e77c88efcdcdf77d038ff331b9c68a3b1343a37168170218322ee2f1846a1e30L3230.

This ternary (of the previous link) is then *essentially* expressed as `null is null ? "HEAD" : null.ToString()`. This still throws an exception though as the last argument is still always evaluated, even though the result will be discarded. Therefore the proposal is to simply replace the member access `.` with `?.`.

### Before

image
(Observe that the line counts and the pie chart never load)

### After

image
(Observe that the statistics plugin shows the line count again)

## Test methodology 

The affected line is effectively a ternary expression, of which the second return value may now also be null if the `commitId` is null. (`commitId is null ? "HEAD" : commitId?.ToString()`)
But if that is the case, we will always choose the first one anyway and discard the second. 
This means we are never actually using the null value in the second case, thus are never changing existing behaviour, assuming existing code does not rely on an exception being thrown in exactly this case.
Therefore, there should be no way of things breaking.

Regardless, my commits were made with this commit applied and the core features indeed appear to be working (Committing, pushing, fetching, etc.).

## Test environment(s) 

- GIT 2.52.0.windows.1
- Windows 10 64bit
- System language: German

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -3238,7 +3238,7 @@ public IEnumerable<IObjectGitItem> GetTree(ObjectId? commitId, bool full, string
                 // optimized codepath, default is "--format={_gitTreeParser.GitTreeFormat}"
                 "-z",
                 { full, "-r" },
-                { commitId is null, "HEAD", commitId.ToString() },
+                { commitId is null, "HEAD", commitId?.ToString() },
```
Comment (gerhardol) [inline src/app/GitCommands/Git/GitModule.cs]: A ternary should not evaluate the second if first is taken sowhy is this failing?
But I would prefer the following instead
```suggestion
                { commitId?.ToString() ?? "HEAD" },
```

**Review by gerhardol — COMMENTED** [review]
There are 24 occurrences of "is null ?" (so slightly more with wrapped lines. A quick check indicates that only a few of them is similar to this snippet..

File: src/app/GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (GHXX) [reply src/app/GitCommands/Git/GitModule.cs]: Here is essentially what the current code does:
`{ commitId is null, "HEAD", commitId.ToString() }` gets turned into `Add(commitId is null, "HEAD", commitId.ToString())`, where then the Add method determines whether to choose the second or third argument as the actual command line argument to be added. The Add function is an extension function defined here: https://github.com/gitextensions/gitextensions/blob/2662d7e57f5cf420c79761c94137836bf63c2531/src/app/GitCommands/ArgumentBuilderExtensions.cs#L44

And heres now why it breaks, the arguments are passed to a function, therefore have to be evaluated before the function call as to ensure consistent behaviour. Regardless of that ternary usage afterwards.

But yeah your suggestion should be good also, and also a lot cleaner.

**Comment by GHXX** [comment]
FYI: Just retested the latest commit; seems the statistics plugin still works.

File: contributors.txt [hunk 2]
```diff
@@ -224,3 +224,4 @@ YYYY/MM/DD, github id, Full name, email
 2025/11/08, hultqvist, Peter Hultqvist, hultqvist@silentorbit.com
 2026/01/07, xan2622, Xan Seiehun, xan2622(at)online(dot).fr
 2026/01/09, jmg2k, Jonas Guss, 44924601+jmg2k@users.noreply.github.com
+2026/01/12, GHXX, GHXX, GHXX@users.noreply.github.com
```
Comment (mstv) [inline contributors.txt]: We should not have accepted that mail address of Jonas Guss.
Yours is even missing a clear name.

File: src/app/GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (mstv) [reply src/app/GitCommands/Git/GitModule.cs]: IMO, the problem is this pseudo-convenience function.
The old code is not very clear and does not work:
```
{ commitId is null, "HEAD", commitId.ToString() }
```
A real ternary had been clear enough and had worked without `?.`:
```
{ commitId is null ? "HEAD" : commitId.ToString() }
```
I am not requesting a change to this line (although it made me wonder whether `ToString` could return `null`).

**Review by mstv — COMMENTED** [review]
nice analysis

File: contributors.txt (hunk 2 above)
Comment (mstv) [reply contributors.txt]: @GHXX: Please add a proper sing-off! We need a clear name and non-GH e-mail address.

Comment (GHXX) [reply contributors.txt]: I can add a regular email address into there, but i am very hesitant sharing my real name like this, especially as this is completely irreversible. 

Furthermore, and dont take this the wrong way, i personally strongly believe that the contribution of literally a single questionmark can never violate the terms 1-4 in contributors.txt. That original contribution added 1 letter to the existing codebase of 145201 lines of c# (at the time), so i really cant see any court ruling that i now somehow suddenly own parts of this project.

I respect your terms, and i do not want to set a bad precedent for other people adding themselves to the agreement, but i am not willing to put my real name into there. 

Whatever your decision will be, please do not let the investigating go to waste, and incorporate the fix somehow, even if under someone else's name.
