### PR TITLE
Fix url openings in plugins

### LINKED ISSUE #10726: [NBug] An error occurred trying to start process 'https://github.c...
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.13
- DPI 96dpi (no scaling)

### Issue description

```
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'https://github.com/nvie/gitflow' with working directory 'C:\Program Files (x86)\GitExtensions'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at GitExtensions.Plugins.GitFlow.GitFlowForm.lnkGitFlow_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Hi,
I've tried to open link About GitFolw from dialog of GitFlow plugin.

### Steps to reproduce

* Open the app
* Select a repository
* Open menu Plugins -> GitFlow
* Click About GitFlow link

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by pmiossec**
because the way to open url has changed since .net core

I had to move `OsShellUtil` to `GitCommands.csproj`
so that it is available in plugins
to prevent code duplication

Fixes  #10726 and #10728 (and similar bugs in other plugins)

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build f4ca8cfafac6d436200ac2edb7b74f8fc539a53a (Dirty)
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Git/Executable.cs [hunk 1]
```diff
@@ -45,6 +46,50 @@ public Executable(Func<string> fileNameProvider, string workingDir = "", string
             return new ProcessWrapper(fileName, _prefixArguments, args, _workingDir, createWindow, redirectInput, redirectOutput, outputEncoding, useShellExecute, throwOnErrorExit);
         }
 
+        /// <summary>
+        /// Open a file with its associated default application.
+        /// </summary>
+        /// <param name="filePath">Pathname of the file to open.</param>
+        public static void Open(string filePath)
```
Comment (mstv) [inline GitCommands/Git/Executable.cs:53]: But these utility functions should not be merged into the `Executable` class.
Rather make `OsShellUtil` available for plugins, please.

**Review by mstv — COMMENTED** [review]
This is on the right path.

File: GitCommands/Git/Executable.cs (hunk 1 above)
Comment (RussKie) [reply GitCommands/Git/Executable.cs:53]: I tend to agree with @mstv, I had the same first reaction that we shouldn't do this...

**Comment by RussKie** [comment]
This would also fix #10728

File: GitCommands/Git/Executable.cs (hunk 1 above)
Comment (pmiossec) [reply GitCommands/Git/Executable.cs]: Done.

**Review by RussKie — APPROVED** [review]

File: Plugins/GitHub3/GitHub3Plugin.cs [hunk 2]
```diff
@@ -267,7 +261,6 @@ public void ConfigureContextMenu(ContextMenuStrip contextMenu)
 
             ToolStripMenuItem toolStripMenuItem = new(string.Format(_viewInWebSite.Text, Name), Icon);
             contextMenu.Items.Add(toolStripMenuItem);
-            toolStripMenuItem.Click += (s, e) => Process.Start(_hostedRemotesForModule.First().Data);
```
Comment (mstv) [inline Plugins/GitHub3/GitHub3Plugin.cs:270]: Why should this be removed?

File: Plugins/Gource/GourceStart.cs [hunk 3]
```diff
@@ -155,7 +155,7 @@ private void WorkingDirBrowseClick(object sender, EventArgs e)
 
         private void linkLabel1_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
         {
-            Process.Start(@"https://github.com/acaudwell/Gource/");
+            OsShellUtil.OpenUrlInDefaultBrowser(@"https://github.com/acaudwell/Gource/");
```
Comment (mstv) [inline Plugins/Gource/GourceStart.cs:158]: Can `using System.Diagnostics;` be removed?

File: Plugins/GitHub3/GitHub3Plugin.cs (hunk 2 above)
Comment (pmiossec) [reply Plugins/GitHub3/GitHub3Plugin.cs:270]: I didn't know if that was an url that we try to open and so after an investigation, I found out that there is no risk to remove for 2 reasons:
* it makes no sense to have this strange action on a menuitem with a submenu. I think it is the remaining of a development test that should have been removed
* all this code is dead code at the moment because that is linked to a feature lost during the transition to the blame inside the browse form. I found the reason but it needs more work and it will be in a following PR...

File: Plugins/Gource/GourceStart.cs (hunk 3 above)
Comment (pmiossec) [reply Plugins/Gource/GourceStart.cs:158]: Maybe yes. I will try to have a look before being not available during a week...

Comment (pmiossec) [reply Plugins/Gource/GourceStart.cs:158]: In fact, no, that's not possible due to a Process.Start to launch gource executable:
https://github.com/gitextensions/gitextensions/blob/2be645a4d66560dc6d7adef45520d476ba7dd80c/Plugins/Gource/GourceStart.cs#L46

**Review by mstv — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you!
