### PR TITLE
Rebase: improve perfs when displaying list of commits

### LINKED ISSUE #10698: Slow Rebase dialog loading prevent user aborting the rebase
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

If I accidentally try to rebase on a revision far from the current branch, it takes a long time before the Rebase dialog is displayed.
It seems to be getting information on each revision one by one.
Provide a way to cancel the Rebase dialog and abort the rebase.

### Steps to reproduce

Rebase on a revision far from the current branch.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### LINKED ISSUE #11196: Rebase dialog is very slow on confict during big rebase
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.21
- DPI 144dpi (150% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

I'm making interactive rebase of a lot of commits (approx 1000) and if there is a conflict and Rebase dialog is opened whole GUI is frozen for 1+ minute.
It depends on number of rebased commits. If there are only few commits, it's not a problem. But with increasing number of commits it takes more time to open dialog.

### Steps to reproduce

1. Make interactive rebase of branch with a lot of commits (1000)
2. Wait for conflict
3. Click to OK button in Process dialog
4. Wait few minutes before Rebase dialog is opened and respond to user interaction

### Did this work in previous version of GitExtensions?

No

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by pmiossec**
by retrieving all the commits data with only one `git log` call instead of one by commit.
It is possible as when rebasing, all the commits belong to the same branch.

Kept a fall back to previous way to retrieve commit data for 1 commit if commit is not in the one loaded.

Results to show the rebase popup with 7448 commits rebased: 2s instead of 4m50 previously

Fixes #10698 and fixes #11196

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build acee8341dc4bb07b1a576d3ddf468ed0f459942b (Dirty)
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.21
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
@dosercz You could try the portable version here: https://ci.appveyor.com/project/gitextensions/gitextensions/build/artifacts

File: GitCommands/RevisionReader.cs [hunk 1]
```diff
@@ -97,13 +97,37 @@ public IReadOnlyCollection<GitRevision> GetRevisionsFromList(IList<ObjectId> unt
...
+        }
+
         /// <summary>
         /// Get the GitRevisions for Git argument.
         /// </summary>
         /// <param name="arguments">Git command arguments.</param>
         /// <param name="cancellationToken">Cancellation cancellationToken.</param>
         /// <returns>List with GitRevisions.</returns>
-        private IReadOnlyCollection<GitRevision> GetRevisionsFromArguments(GitArgumentBuilder arguments, CancellationToken cancellationToken)
+        public IReadOnlyCollection<GitRevision> GetRevisionsFromArguments(GitArgumentBuilder arguments, CancellationToken cancellationToken)
```
Comment (gerhardol) [inline GitCommands/RevisionReader.cs:130]: why?

File: GitCommands/Git/GitModule.cs [hunk 2]
```diff
@@ -2143,42 +2143,47 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
+            var isCurrentFound = false;
 
-                    string commitHash = parts[1];
-                    CommitData? data = _commitDataManager.GetCommitData(commitHash, out var error);
-                    var isApplying = currentCommitShortHash is not null && commitHash.StartsWith(currentCommitShortHash);
-                    isCurrentFound |= isApplying;
+            RevisionReader reader = new(this, hasReflogSelector: false);
+            CancellationTokenSource cts = new(2 * 60_000);
+            Dictionary<string, GitRevision> rebasedCommitsRevisions =
+                reader.GetRevisionsFromRange(todoCommitsInfos[0][1], todoCommitsInfos[todoCommitsInfos.Length - 1][1], cts.Token)
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs:2164]:
```suggestion
                reader.GetRevisionsFromRange(todoCommitsInfos[0][1], todoCommitsInfos[^1][1], cts.Token)
```

File: GitCommands/Git/GitModule.cs [hunk 3]
```diff
@@ -2143,42 +2143,47 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
-                        IsNext = isApplying,
-                        IsApplied = !isCurrentFound,
-                    });
-                }
+            foreach (string[] parts in todoCommitsInfos)
+            {
+                string commitHash = parts[1];
+                CommitData? data = rebasedCommitsRevisions.TryGetValue(commitHash, out GitRevision commitRevision)
+                    ? _commitDataManager.CreateFromRevision(commitRevision, null)
+                    : _commitDataManager.GetCommitData(commitHash, out var error);
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs:2172]:
```suggestion
                    : _commitDataManager.GetCommitData(commitHash, out var _);
```

Comment (gerhardol) [inline GitCommands/Git/GitModule.cs:2172]: Note to self: GetCommitData should use RevisionReader too

**Review by gerhardol — COMMENTED** [review]
+1
Has not run

File: GitCommands/RevisionReader.cs (hunk 1 above)
Comment (pmiossec) [reply GitCommands/RevisionReader.cs:130]: Because i needed it for my PoC and I don't really understand how I forgot to revert it...
Will do it right away ;)

File: GitCommands/Git/GitModule.cs [hunk 4]
```diff
@@ -2143,42 +2143,47 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
+                    : _commitDataManager.GetCommitData(commitHash, out var _);
+
+                var isApplying = currentCommitShortHash is not null && commitHash.StartsWith(currentCommitShortHash);
+                isCurrentFound |= isApplying;
+
+                patchFiles.Add(new PatchFile
+                {
+                    Author = data?.Author,
+                    ObjectId = data?.ObjectId,
+                    Subject = data?.Body,
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs:2181]: Is body or Subject needed?
RevisionReader will not save Body (just subject) if the commit is older than 6 months. 
(rename the _sixMonths variable to _oldestBody?)

```
        public RevisionReader(GitModule module, bool hasReflogSelector, bool allBodies = false)
            : this(module, hasReflogSelector, module.LogOutputEncoding, allBodies ? 0 : new DateTimeOffset(DateTime.Now.ToUniversalTime() - TimeSpan.FromDays(30 * 6)).ToUnixTimeSeconds())
        {
        }
```

**Review by gerhardol — APPROVED** [review]
Approving, assuming the question is fixed

File: GitCommands/Git/GitModule.cs [hunk 5]
```diff
@@ -2143,42 +2143,47 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
+                .Select(l => l.Split(Delimiters.Space))
+                .Where(p => p.Length >= 3)
+                .ToArray();
 
-                    if (parts.Length < 3)
-                    {
-                        continue;
-                    }
+            string? currentCommitShortHash = File.Exists(CurrentFilePath) ? File.ReadAllText(CurrentFilePath).Trim() : null;
+            var isCurrentFound = false;
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs:2159]: Please don't use `var` for the intrinsic types.
```suggestion
            bool isCurrentFound = false;
```
Ditto below

File: GitCommands/Git/GitModule.cs [hunk 6]
```diff
@@ -2143,42 +2143,47 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
-                    {
-                        continue;
-                    }
+            string commentChar = EffectiveConfigFile.GetString("core.commentChar", "#");
 
-                    string[] parts = todoCommit.Split(Delimiters.Space);
+            string[][] todoCommitsInfos = todoCommits.Where(l => !l.StartsWith(commentChar))
+                .Select(l => l.Split(Delimiters.Space))
+                .Where(p => p.Length >= 3)
+                .ToArray();
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs:2156]: This could use some comments explaining what data we have here and what we get after the reduction.

File: GitCommands/RevisionReader.cs [hunk 7]
```diff
@@ -97,6 +97,30 @@ public IReadOnlyCollection<GitRevision> GetRevisionsFromList(IList<ObjectId> unt
             return GetRevisionsFromArguments(arguments, cancellationToken);
         }
 
+        /// <summary>
+        /// Get the GitRevisions for all commits between 2 commits (boundaries included).
+        /// </summary>
+        /// <param name="olderCommitId">older commit Id.</param>
+        /// <param name="newerCommitId">newer commit Id.</param>
+        /// <param name="cancellationToken">Cancellation cancellationToken.</param>
+        /// <returns>List with GitRevisions.</returns>
```
Comment (RussKie) [inline GitCommands/RevisionReader.cs:106]:
```suggestion
        /// <summary>
        ///  Retrieves the git history in the requested range (boundaries included).
        /// </summary>
        /// <param name="olderCommitId">The first (older) commit.</param>
        /// <param name="newerCommitId">The last (newer) commit.</param>
        /// <param name="cancellationToken">A cancellation token.</param>
        /// <returns>The retrieved git history.</returns>
```

I'm a little confused with the terminology - are we using `commit`, `commit hash`, `commit id`, or something else...?

**Review by RussKie — COMMENTED** [review]
Few nits and suggestions

File: GitCommands/RevisionReader.cs (hunk 7 above)
Comment (pmiossec) [reply GitCommands/RevisionReader.cs:106]: Thanks for your comment that makes me investigate.
From what I can get looking at GE source code, `commit id` is used when the type is `ObjectId`. When it is the string, it is `commit hash`. So I will rename the parameters.

**Comment by dosercz** [comment]
@pmiossec I have tested portable version builded for this PR and it's fine, good job. It'll safe a lot of my time!

**Comment by pmiossec** [comment]
@gerhardol Could you give your point of view on the 2nd commit that get the bodies for older commits as I did some refactoring/renaming?

**Comment by RussKie** [comment]
👍

File: GitCommands/Git/GitModule.cs [hunk 8]
```diff
@@ -2143,42 +2143,50 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
-                        IsNext = isApplying,
-                        IsApplied = !isCurrentFound,
-                    });
-                }
+            foreach (string[] parts in todoCommitsInfos)
+            {
+                string commitHash = parts[1];
+                CommitData? data = rebasedCommitsRevisions.TryGetValue(commitHash, out GitRevision commitRevision)
+                    ? _commitDataManager.CreateFromRevision(commitRevision, null)
+                    : _commitDataManager.GetCommitData(commitHash, out var _);
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:2175]:
```suggestion
                string? error;
                CommitData? data = rebasedCommitsRevisions.TryGetValue(commitHash, out GitRevision commitRevision)
                    ? _commitDataManager.CreateFromRevision(commitRevision, children: null)
                    : _commitDataManager.GetCommitData(commitHash, out error);
```

File: GitCommands/Git/GitModule.cs [hunk 9]
```diff
@@ -2143,42 +2143,50 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
+
+                var isApplying = currentCommitShortHash is not null && commitHash.StartsWith(currentCommitShortHash);
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:2177]: nit (on unmodified code):
```suggestion
                bool isApplying = currentCommitShortHash is not null && commitHash.StartsWith(currentCommitShortHash);
```

File: GitCommands/Git/GitModule.cs (hunk 4 above)
Comment (mstv) [reply GitCommands/Git/GitModule.cs:2184]:
```suggestion
                    Subject = error ?? data?.Subject,
```

File: GitCommands/Git/GitModule.cs [hunk 10]
```diff
@@ -2143,42 +2143,50 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
-                        continue;
-                    }
+            string? currentCommitShortHash = File.Exists(CurrentFilePath) ? File.ReadAllText(CurrentFilePath).Trim() : null;
+            bool isCurrentFound = false;
 
-                    string commitHash = parts[1];
-                    CommitData? data = _commitDataManager.GetCommitData(commitHash, out var error);
-                    var isApplying = currentCommitShortHash is not null && commitHash.StartsWith(currentCommitShortHash);
-                    isCurrentFound |= isApplying;
+            RevisionReader reader = new(this, hasReflogSelector: false, allBodies: true);
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:2164]: no need for bodies:
```suggestion
            RevisionReader reader = new(this, hasReflogSelector: false, noBodies: true);
```

File: GitCommands/Git/GitModule.cs [hunk 11]
```diff
@@ -2143,42 +2143,50 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
+                CommitData? data = rebasedCommitsRevisions.TryGetValue(commitHash, out GitRevision commitRevision)
+                    ? _commitDataManager.CreateFromRevision(commitRevision, null)
+                    : _commitDataManager.GetCommitData(commitHash, out var _);
+
+                var isApplying = currentCommitShortHash is not null && commitHash.StartsWith(currentCommitShortHash);
+                isCurrentFound |= isApplying;
+
+                patchFiles.Add(new PatchFile
+                {
+                    Author = data?.Author,
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:2182]:
```suggestion
                    Author = error ?? data?.Author,
```

File: GitCommands/Git/GitModule.cs [hunk 12]
```diff
@@ -2143,42 +2143,50 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
+                    ObjectId = data?.ObjectId,
+                    Subject = data?.Body,
+                    Action = parts[0],
+                    Date = data?.CommitDate.LocalDateTime.ToString(),
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:2186]:
```suggestion
                    Date = error ?? data?.CommitDate.LocalDateTime.ToString(),
```

File: GitCommands/RevisionReader.cs [hunk 13]
```diff
@@ -33,26 +33,30 @@ public sealed class RevisionReader
...
 
         // reflog selector to identify stashes
         private readonly bool _hasReflogSelector;
 
         private string LogFormat => _hasReflogSelector ? FullFormat.Replace("%B", "%gD%n%B") : FullFormat;
 
-        public RevisionReader(GitModule module, bool hasReflogSelector)
-            : this(module, hasReflogSelector, module.LogOutputEncoding, new DateTimeOffset(DateTime.Now.ToUniversalTime() - TimeSpan.FromDays(30 * 6)).ToUnixTimeSeconds())
+        public RevisionReader(GitModule module, bool hasReflogSelector, bool allBodies = false)
+            : this(module, hasReflogSelector, module.LogOutputEncoding, allBodies ? 0 : GetUnixTimeForOffset(_offsetDaysForOldestBody))
```
Comment (mstv) [inline GitCommands/RevisionReader.cs:45]:
```suggestion
        public RevisionReader(GitModule module, bool hasReflogSelector, bool noBodies = false)
            : this(module, hasReflogSelector, module.LogOutputEncoding, GetUnixTimeForOffset(noBodies ? 0 : _offsetDaysForOldestBody))
```

File: GitCommands/RevisionReader.cs [hunk 14]
```diff
@@ -33,26 +33,30 @@ public sealed class RevisionReader
 
         private readonly GitModule _module;
         private readonly Encoding _logOutputEncoding;
-        private readonly long _sixMonths;
+        private readonly long _oldestBody;
+        private const int _offsetDaysForOldestBody = 6 * 30; // env 6 months
```
Comment (mstv) [inline GitCommands/RevisionReader.cs:37]: nit: Did you mean
```suggestion
        private const int _offsetDaysForOldestBody = 6 * 30; // about 6 months
```
?

**Review by mstv — COMMENTED** [review]
just tuning

File: GitCommands/Git/GitModule.cs [hunk 15]
```diff
@@ -2170,20 +2170,31 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
+
                 patchFiles.Add(new PatchFile
                 {
-                    Author = data?.Author,
-                    ObjectId = data?.ObjectId,
-                    Subject = data?.Body,
                     Action = parts[0],
-                    Date = data?.CommitDate.LocalDateTime.ToString(),
+                    ObjectId = objectId,
+                    Subject = data?.Body ?? string.Join(' ', parts.Skip(2)),
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs:2195]: Is Subject or Body needed?

Comment (pmiossec) [reply GitCommands/Git/GitModule.cs:2195]: Before this PR, the grid was using the body (1st line i.e. subject displayed in the grid and body displayed in the tooltip).
So my goal is more to not break this behavior.
But we could decide that subject is enough and the user will double click to see the whole message (even if personally I found the whole body in the tooltip useful in some rare cases when you rebase some commits with very similar subjects)

Comment (pmiossec) [reply GitCommands/Git/GitModule.cs:2196]: Not sure to get what you mean but I have added a comment.

File: GitCommands/Git/GitModule.cs [hunk 16]
```diff
@@ -2143,42 +2143,62 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
+            string? currentCommitShortHash = File.Exists(CurrentFilePath) ? File.ReadAllText(CurrentFilePath).Trim() : null;
+            bool isCurrentFound = false;
 
-                    string commitHash = parts[1];
-                    CommitData? data = _commitDataManager.GetCommitData(commitHash, out var error);
-                    var isApplying = currentCommitShortHash is not null && commitHash.StartsWith(currentCommitShortHash);
-                    isCurrentFound |= isApplying;
+            // retrieve commits bodies to display them in the grid or as tooltips
+            RevisionReader reader = new(this, hasReflogSelector: false, allBodies: true);
+            CancellationTokenSource cts = new(TimeSpan.FromSeconds(15));
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:2166]: This might be too short. It can take a few seconds for a few commits on a workstation.

**Review by mstv — COMMENTED** [review]
👍

File: GitCommands/Git/GitModule.cs (hunk 15 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:2196]: I meant on line 2195 - or someone may change the code to only get the subject

File: GitCommands/Git/GitModule.cs (hunk 16 above)
Comment (pmiossec) [reply GitCommands/Git/GitModule.cs:2166]: Is it something you saw?
Because, in GE repo, I made a rebase of 12k commits and it took only 250ms that's why I concluded that in this case 15s was enough. But I have no problem to increase it. 30s?

Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:2166]: git-log+parsing requires about 2 s for 100K commits so rebasing all commits in the linux repo would require 20s or so on my machine. 30s is safe

The git-rebase operation can require some time though

Comment (pmiossec) [reply GitCommands/Git/GitModule.cs:2166]: The cancelation token is only for the 'git log & parsing' so I'm happy you confirm that 15s is enough (to rebase 700k commits!) 🤣
But secured 30s is OK for me as we are talking about a worst case scenario that will nearly never happen...

File: GitCommands/Git/GitModule.cs [hunk 17]
```diff
@@ -2143,42 +2143,73 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
+            string? currentCommitShortHash = File.Exists(CurrentFilePath) ? File.ReadAllText(CurrentFilePath).Trim() : null;
+            bool isCurrentFound = false;
 
-                    string commitHash = parts[1];
-                    CommitData? data = _commitDataManager.GetCommitData(commitHash, out var error);
-                    var isApplying = currentCommitShortHash is not null && commitHash.StartsWith(currentCommitShortHash);
-                    isCurrentFound |= isApplying;
+            RevisionReader reader = new(this, hasReflogSelector: false, allBodies: true);
+            CancellationTokenSource cts = new(TimeSpan.FromSeconds(30));
+            Dictionary<string, GitRevision> rebasedCommitsRevisions;
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:2167]: 👍
```suggestion
            Dictionary<string, GitRevision> rebasedCommitsRevisions;
            try
            {
                using CancellationTokenSource cts = new(TimeSpan.FromSeconds(30));
```

File: GitCommands/Git/GitModule.cs (hunk 16 above)
Comment (mstv) [reply GitCommands/Git/GitModule.cs]: > Is it something you saw?

Yes, perhaps caused by hyperactive enterprise AV and / or Windows Update.

(Also git itself became quirky later yesterday. It reproducibly returned exit code 128 without error output when resetting single files using `git checkout` - vanished after reboot.)

**Comment by pmiossec** [comment]
Do you still want to review something or I could squash and rebase everything?

**Review by mstv — APPROVED** [review]
👍

**Comment by pmiossec** [comment]
Squashed and rebase. Ready to be merged...

File: GitCommands/RevisionReader.cs [hunk 18]
```diff
@@ -97,6 +101,30 @@ public IReadOnlyCollection<GitRevision> GetRevisionsFromList(IList<ObjectId> unt
...
+        {
+            if (string.IsNullOrWhiteSpace(olderCommitHash) || string.IsNullOrWhiteSpace(newerCommitHash))
+            {
+                return Array.Empty<GitRevision>();
+            }
+
+            GitArgumentBuilder arguments = new("log")
+                {
+                    "-z",
+                    $"--pretty=format:\"{FullFormat}\"",
```
Comment (gerhardol) [inline GitCommands/RevisionReader.cs:121]: This should have been `LogFormat`, will change at another update
