### PR TITLE
Fix/7931

### LINKED ISSUE #7931: NullReferenceException when Clone Repository from Dashboard
## Current behaviour

From the Dashboard, clicking on 'Clone Repository' throws a NullReferenceException.

## Expected behaviour

Should not throw an exception.

## Steps to reproduce

Go to the Dashboard -> click on 'Clone Repository'

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.CommandsDialogs.FormClone.CanBeGitURL(String url)
   at GitUI.CommandsDialogs.FormClone.OnRuntimeLoad(EventArgs e)
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Regression from #7876  

## Environment
- Git Extensions 4.0.0.8945
- Build a6f3362e7ca4d5e18de85b7284bfec4785ef914a (Dirty)
- Git 2.25.1.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4018.0
- DPI 144dpi (150% scaling)

### PR DESCRIPTION
**Pull request by NoahLerner**
Fixes #7931 

## Proposed changes

- Fix NullReferenceException

## Test methodology 

- Added unit test with multiple test cases

## Test environment(s) 

- GIT 
- Windows 

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/PathUtil.cs [hunk 1]
```diff
@@ -89,6 +89,18 @@ public static bool IsUrl(string path)
...
         }
 
+        public static bool CanBeGitURL(string url)
+        {
+            if (url.IsNullOrWhiteSpace())
+            {
+                return false;
+            }
+
+            return PathUtil.IsUrl(url)
```
Comment (mstv) [inline GitCommands/PathUtil.cs:99]: Does it work without repeating the class?
```suggestion
            return IsUrl(url)
```

Comment (NoahLerner) [reply GitCommands/PathUtil.cs]: > Does it work without repeating the class?

Fixed.



> Could you also sign-off the `contributors.txt` file, please? Open another PR for this in order to avoid merge conflicts.

I am already a listed contributor - and I recall signing this several months ago. Do I still need to do this?

Comment (NoahLerner) [reply GitCommands/PathUtil.cs]: Opened a dedicated PR for the contributors file. My name wasn't there.. must be new since I last contributed.

**Comment by NoahLerner** [comment]
A PR (#7933) with the signed `contributors.txt` file is awaiting review.
