### PR TITLE
Fix 6310 Provide ability to sort/order branches and tags

### LINKED ISSUE #6310: Sort branches alphabethical/lastAccess was removed
## Current behaviour

In 2.51, it was possible to order branches in Browse by either alphabethical or last access order.
This possibility was removed in 9c7c76fb619480429cbe02e11ce889b00423eac2 (likely #5087)

## Expected behaviour

Change of sorting was useful, even little hard to find.
Sort could be restored or we decide that it should not be possible.

## Steps to reproduce

       public static BranchOrdering BranchOrderingCriteria
        {
            get { return GetEnum("BranchOrderingCriteria", BranchOrdering.ByLastAccessDate); }
            set { SetEnum("BranchOrderingCriteria", value); }
        }

## Screenshots

image

## Did this work in previous version of GitExtensions
2.51

## Environment

- Git Extensions 3.1.0
- Build d753f4a7e0c175529d7c6ecffa7f297ea239faf3
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #7472: Set minimum git version to 2.19  or later
## Feature description

With the move to .NET Core I propose we set the minimum git version to 2.19 or newer, and remove all older versions and their quirks.

Git 2.19 was release Sep 2018, .NET Core was released Sep/Dec 2019, so a user will likely need to have .NET Core runtime installed to run a new version of the app (we may or may not publish a self contained bundle).

The move will help providing simple solutions to #4869 and #7456.

### LINKED ISSUE #8301: "Go to tag" is broken
## Current behaviour

"Navigate -> Go to commit -> Go to tag" does nothing.
The list of tags is shown, but GitExtensions does not navigate to the tag I select.

## Expected behaviour
The selected tag is navigated to.

## Steps to reproduce

See above.

## Did this work in previous version of GitExtensions

This has been broken since at least v3.3.x.

## Environment

- GitExtensions version: 3.4.2.9737
- GIT version: 2.23.0
- OS version: Win10 build 18363 (release 1909)
- .NET version: 4.8.4180.0

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #6310
Fixes #8301
Resolves #7472
Closes #4869
Closes #8309 as obsolete

## Proposed changes

- Provide ability to sort/order branches

Restore the functionality (albeit improved) removed in 9c7c76fb619480429cbe02e11ce889b00423eac2.

Allow to either defer sorting to git (i.e. sort by Default) which is either implicit, or configured via `git config branch.sort`.

Alternatively expose the following sort by options:
- authordate
- committerdate
- creatordate
- taggerdate
- refname
- objectsize
- upstream

For user-specified sort, allow to select ascending or descending order (default: desc).

Git v2.19+ is required to facilitate the above, hence bump in the min version.

The sort configuration applies to both the left panel and the branches dropdown in the toolstrip.

### After

* Settings:
image
image

* The left panel:
image

## Test methodology 

- manual 
- added few unit tests

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
@msftbot merge in 48 hours

File: GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -2861,41 +2861,42 @@ public RemoteActionResult<IReadOnlyList<IGitRef>> GetRemoteServerRefs(string rem
...
-                    noLocks && GitVersion.Current.SupportNoOptionalLocks
-                        ? (ArgumentString)"--no-optional-locks"
-                        : default)
+                cmd = new GitArgumentBuilder("for-each-ref",
+                        gitOptions: noLocks && GitVersion.Current.SupportNoOptionalLocks
+                            ? (ArgumentString)"--no-optional-locks"
+                            : default)
                 {
-                    "--sort=-committerdate",
+                    { sortBy != GitRefsSortBy.Default, GetSortCriteria(sortBy, sortOrder), string.Empty },
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs:2899]: --sort was introduced in Git 2.14.6 (not 2.19, not opposing the raise)
For all other Git options, GE checks arguments to avoid crashes. Should that be done here?

File: GitCommands/Git/GitVersion.cs [hunk 2]
```diff
@@ -22,7 +22,7 @@ public class GitVersion : IComparable<GitVersion>
         private static readonly GitVersion v2_19_0 = new GitVersion("2.19.0");
         private static readonly GitVersion v2_20_0 = new GitVersion("2.20.0");
 
-        public static readonly GitVersion LastSupportedVersion = v2_11_0;
+        public static readonly GitVersion LastSupportedVersion = v2_19_0;
         public static readonly GitVersion LastRecommendedVersion = new GitVersion("2.25.1");
```
Comment (gerhardol) [inline GitCommands/Git/GitVersion.cs:26]: Should be bumped to 2.27 - what we should use when "testing"

File: GitUI/BranchTreePanel/ContextMenu/GitRefsSortOrderContextMenuItem.cs [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+using GitUI.Properties;
+using GitUIPluginInterfaces;
+using ResourceManager;
+
+namespace GitUI.BranchTreePanel.ContextMenu
+{
+    internal class GitRefsSortOrderContextMenuItem : ToolStripMenuItem
+    {
+        internal const string MenuItemName = "GitRefsSortOrderContextMenuItem";
+        private readonly TranslationString _sortByText = new TranslationString("&Sort order...");
```
Comment (gerhardol) [inline GitUI/BranchTreePanel/ContextMenu/GitRefsSortOrderContextMenuItem.cs:15]: translate?

**Review by gerhardol — COMMENTED** [review]
Brief, review, brief testing. Some comments, considered blocking auto merge

**Review by gerhardol — CHANGES_REQUESTED** [review]
git show-ref do not have --sort option
I cannot trigger the use of --sort to GetRefsCmd() with sort though

**Comment by gerhardol** [comment]
@msftbot forget what I just told you

File: GitCommands/Git/GitModule.cs [hunk 4]
```diff
@@ -2861,41 +2861,42 @@ public RemoteActionResult<IReadOnlyList<IGitRef>> GetRemoteServerRefs(string rem
...
-                    noLocks && GitVersion.Current.SupportNoOptionalLocks
-                        ? (ArgumentString)"--no-optional-locks"
-                        : default)
+                cmd = new GitArgumentBuilder("show-ref",
+                        gitOptions: noLocks && GitVersion.Current.SupportNoOptionalLocks
+                            ? (ArgumentString)"--no-optional-locks"
+                            : default)
                 {
                     { branches, "--dereference", "--tags" },
+                    { sortBy != GitRefsSortBy.Default, GetSortCriteria(sortBy, sortOrder), string.Empty }
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/Git/GitModule.cs:2888]: My mistake, I was too eager here, and haven't tested whether tags can be sorted.
Thank you

File: GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (RussKie) [reply GitCommands/Git/GitModule.cs:2899]: Yes, but `git branch.sort` option was only introduced in 2.19
https://github.blog/2018-09-10-highlights-from-git-2-19/#user-content-sorting-branches

> For all other Git options, GE checks arguments to avoid crashes. Should that be done here?

Please elaborate, I don't think I understand.

File: GitCommands/Git/GitVersion.cs (hunk 2 above)
Comment (RussKie) [reply GitCommands/Git/GitVersion.cs:26]: Sure

File: GitUI/BranchTreePanel/ContextMenu/GitRefsSortOrderContextMenuItem.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/BranchTreePanel/ContextMenu/GitRefsSortOrderContextMenuItem.cs:15]: It appears these aren't translatable in the current form. 
I hoped no-one would notice :D

File: GitCommands/Git/GitModule.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/Git/GitModule.cs]: It looks like we don't need `git show-ref`, and instead we can replace it with `git for-each-ref` supplying necessary refs, i.e. `refs/heads/`, `refs/remotes/`, and `refs/tags/`. With this we can leverage the benefits of sorting.

Do you see any issues with this change?

File: GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs]: > Yes, but git branch.sort option was only introduced in 2.19

Not what is used here, so min version is 2.14.6

> Please elaborate, I don't think I understand.

GE has checks for Git options in versions, also for unsupported versions to avoid crashes.

File: GitCommands/Git/GitModule.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs]: > Do you see any issues with this change?

No

**Comment by RussKie** [comment]
Outstanding: resolution of the context menu placement for the Tags node. Judging by incoming PRs looks like @ivangrek has significantly better understanding of this part 😁.

File: GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (RussKie) [reply GitCommands/Git/GitModule.cs]: I'm split. We're moving the bar up, so adding checks for something we no longer support feels redundant.
I'll add it if you feel it is truly necessary.

**Comment by ivangrek** [comment]
Is this the correct state?

image

image

File: Plugins/GitUIPluginInterfaces/GitRefsOrder.cs [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+namespace GitUIPluginInterfaces
+{
+    // NB: The values are fed directly into git commands, casing is important!
+    public enum GitRefsSortBy
+    {
+        [Description("Git default")]
+        Default = 0,
+
+        [Description("Author date")]
+        authordate,
```
Comment (ivangrek) [inline Plugins/GitUIPluginInterfaces/GitRefsOrder.cs:12]: Enum Naming

Comment (RussKie) [reply Plugins/GitUIPluginInterfaces/GitRefsOrder.cs:12]: I left a comment on line:5 - these go directly into `git` commands

**Comment by RussKie** [comment]
> Is this the correct state?

Champion! You're clearly a better tester than I am 🙇‍♂️ No, this is definitely something I didn't anticipate, and now I need to think of it more. 
Though this should go into https://github.com/gitextensions/gitextensions/pull/8414, this PR is about sorting.

**Comment by RussKie** [comment]
@gerhardol I'd appreciate your re-review, I believe your points are addressed.

File: GitCommands/Git/Commands/GitCommandHelpers.cs [hunk 6]
```diff
@@ -81,39 +80,54 @@ public static ArgumentString AddSubmoduleCmd(string remotePath, string localPath
...
+            static string GetSortCriteria(bool needTags, GitRefsSortBy sortBy, GitRefsSortOrder sortOrder)
+            {
+                string order = sortOrder == GitRefsSortOrder.Ascending ? string.Empty : "-";
+                if (!needTags)
+                {
+                    return $"--sort={order}{sortBy}";
+                }
+
+                // Sort by dereferenced data
+                return $"--sort={order}{sortBy} --sort={order}*{sortBy}";
```
Comment (gerhardol) [inline GitCommands/Git/Commands/GitCommandHelpers.cs:129]: Add a comment that Git 2.14.6 is required (maybe remove checks and add comments elsewhere?)
There is a workaround, to not set any sorting too
https://github.com/gitextensions/gitextensions/pull/8427#discussion_r483852667

**Review by gerhardol — COMMENTED** [review]
I mostly looked at GitModule changes, a few comments only.
Briefly looked at the rest, briefly tested.
I suggest it is merged, but not deep enough review to formally approve.

File: GitCommands/Git/Commands/GitCommandHelpers.cs [hunk 7]
```diff
@@ -81,39 +80,54 @@ public static ArgumentString AddSubmoduleCmd(string remotePath, string localPath
...
 
+            GitArgumentBuilder cmd = new GitArgumentBuilder("for-each-ref",
+                gitOptions: noLocks && GitVersion.Current.SupportNoOptionalLocks
+                    ? (ArgumentString)"--no-optional-locks"
+                    : default)
+            {
+                { sortBy != GitRefsSortBy.Default, GetSortCriteria(tags, sortBy, sortOrder), string.Empty },
+                format,
+                { branches, "refs/heads/", string.Empty },
+                { branches && tags, "refs/remotes/", string.Empty },
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/Git/Commands/GitCommandHelpers.cs:114]: Thank you for pointing me to this. This API can do with quite a bit of improvement, but I didn't want to change to much in the context of this PR. I will do a follow up improvement later.

File: GitCommands/Git/Commands/GitCommandHelpers.cs [hunk 8]
```diff
@@ -81,39 +80,54 @@ public static ArgumentString AddSubmoduleCmd(string remotePath, string localPath
...
+                // or "dereferences" (i.e. commits that contian metadata and point to other commits, "^{}").
+                // Derefence commits do not contain date information, so we need to find information from the referenced commits (those with '*').
+                // So the following format is as follows:
+                //      If (there is a 'authordate' information, then this is a simple tag/direct commit)
+                //      Then
+                //          format = %(objectname) %(refname)
+                //      Else
+                //          format = %(*objectname) %(*refname) // i.e. info from a referenced commit
+                //      End
+                format = @"--format=""%(if)%(authordate)%(then)%(objectname) %(refname)%(else)%(*objectname) %(*refname)%(end)""";
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/Git/Commands/GitCommandHelpers.cs:103]: Nice, we can certainly look at this as a follow up 👍

File: GitCommands/Git/GitModule.cs [hunk 9]
```diff
@@ -2895,53 +2895,11 @@ public RemoteActionResult<IReadOnlyList<IGitRef>> GetRemoteServerRefs(string rem
...
         public IReadOnlyList<IGitRef> GetRefs(bool tags = true, bool branches = true)
         {
-            return GetRefs(tags, branches, false);
-        }
-
-        public IReadOnlyList<IGitRef> GetRefs(bool tags, bool branches, bool noLocks)
-        {
-            var refList = _gitExecutable.GetOutput(GitCommandHelpers.GetRefsCmd(tags: tags, branches: branches, noLocks: noLocks));
-
+            string cmd = GitCommandHelpers.GetRefsCmd(tags: tags, branches: branches, noLocks: true, AppSettings.RefsSortBy, AppSettings.RefsSortOrder);
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/Git/GitModule.cs:2898]: Yeah, I was somewhat confused and had to search through docs. My impression that we want to use "nolocks" for these commands.

File: GitCommands/Git/Commands/GitCommandHelpers.cs (hunk 6 above)
Comment (RussKie) [reply GitCommands/Git/Commands/GitCommandHelpers.cs:134]: Added `GitVersion.Current.SupportRefSort`

**Comment by RussKie** [comment]
> I suggest it is merged, but not deep enough review to formally approve.

Taking this as an approval. Feel free to cancel the auto-merge, if it isn't so.

**Comment by RussKie** [comment]
@msftbot merge in 24 hours or if @gerhardol approves

**Comment by RussKie** [comment]
@msftbot merge in 24 hours

File: GitCommands/Git/GitModule.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:2898]: We do not want to lock the repo for background operations. For git-status the commit count is in the background but FormCommit is in the foreground. This is the primary use of noLocks (before this, FormCommit occasionally failed).

This change assumes that all GetRefs() is done in the background, which is the case right now but may not be correct in the future.

**Review by gerhardol — APPROVED** [review]
> > I suggest it is merged, but not deep enough review to formally approve.
> 
> Taking this as an approval. Feel free to cancel the auto-merge, if it isn't so.

Approval to merge, but incomplete review, focusing on GetRefs() that I found to be important. 
More of browsing the remaining, I could understand what I looked at and no obvious problems.
There are a few discussion points still, can be discussed separately.

Approving with the limitations in the review stated above.

File: GitCommands/Git/GitModule.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/Git/GitModule.cs:2898]: I added your explanation as a comment to the code.

**Comment by jrfnl** [comment]
Thank you!!!! ❤️  Been missing this a lot!

Only question I have is: is there a way to sort alphanumerically, but case insensitively ? Might be possible already, but I haven't figured out how to do it.

**Comment by RussKie** [comment]
I don't know.
Git is a Linux tool, so it is generally case sensitive. And as you can see
from the PR diff or command log (F12) the sort command can be quite
intricate.

That said, I haven't considered or investigated case sensitivity because
for me it was never an issue...

**Comment by RussKie** [comment]
Related: https://github.com/gitextensions/gitextensions/issues/8508
