### PR TITLE
Hide extra separator in context menu for folder item

### LINKED ISSUE #8136: Redundant context menu splitter
## Current behaviour

image

## Steps to reproduce

Right click on a folder in the File Tree for the current revision

## Did this work in previous version of GitExtensions

I presume so

## Environment

- Git Extensions 3.4.0.9378
- Build 85ab13ae47d7f68deae8135694ef2c622e2b498b
- Git 2.16.1.windows.4 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4150.0
- DPI 144dpi (150% scaling)

### PR DESCRIPTION
**Pull request by RussKie**
Resolves #8136

### Before

image

### After

image

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
Will push a change with more changes, to reorder options and make it simpler to make further changes...

**Comment by RussKie** [comment]
Sure, no probs :+1:

File: GitUI/CommandsDialogs/RevisionFileTreeControl.cs [hunk 1]
```diff
@@ -550,51 +550,51 @@ private void FileTreeContextMenu_Opening(object sender, System.ComponentModel.Ca
...
-            fileTreeCleanWorkingTreeToolStripMenuItem.Enabled = isExistingFileOrDirectory;
-
-            fileHistoryToolStripMenuItem.Enabled = itemSelected;
-            blameToolStripMenuItem1.Visible = isFile;
+            // Diff with workTree (some tools like kdiff3 and meld allows diff to NUL)
+            openWithDifftoolToolStripMenuItem.Visible = isFile;
+            resetToThisRevisionToolStripMenuItem.Visible = itemSelected && !Module.IsBareRepository();
+            toolStripSeparatorTopActions.Visible = itemSelected && ((gitItem.ObjectType == GitObjectType.Commit && isExistingFileOrDirectory)
+                                                                    || !Module.IsBareRepository()
+                                                                    || isFile);
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionFileTreeControl.cs:568]: This condition is too complex IMO.
```suggestion
            toolStripSeparatorTopActions.Visible = openSubmoduleMenuItem.Visible
                || openWithDifftoolToolStripMenuItem.Visible
                || resetToThisRevisionToolStripMenuItem.Visible;
```

File: GitUI/CommandsDialogs/RevisionFileTreeControl.cs [hunk 2]
```diff
@@ -550,51 +550,51 @@ private void FileTreeContextMenu_Opening(object sender, System.ComponentModel.Ca
             var isFile = itemSelected && gitItem.ObjectType == GitObjectType.Blob;
             var isFolder = itemSelected && gitItem.ObjectType == GitObjectType.Tree;
             var isFileOrFolder = isFile || isFolder;
+
+            // Many items does not make sense if a local file does not exist, why this is used for Enabled
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionFileTreeControl.cs:554]:
```suggestion
            // Many menu items do not make sense if the local file does not exist, that's why this is used for Enabled
```

File: GitUI/CommandsDialogs/RevisionFileTreeControl.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionFileTreeControl.cs:568]: That is what I would like too, but Visible is always false when reading.
(It would be possible to set Enabled or a separate variable of course).

File: GitUI/CommandsDialogs/RevisionFileTreeControl.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionFileTreeControl.cs:554]: will update

**Comment by RussKie** [comment]
@gerhardol i'm struggling to visualise the change, can you please post a screenshot?

**Comment by gerhardol** [comment]
There is no visual change except for open sub module (try nbug in a year ago commit) and diff tool (any file removed in the work tree).
