### PR TITLE
Prevent NRE when getting AppVeyor build duration

### LINKED ISSUE #8150: AppVeyor GetBuildDuration fails with NRE
## Current behaviour

image
```
>	GitExtensions.AppVeyorIntegration.dll!AppVeyorIntegration.AppVeyorAdapter.GetBuildDuration(Newtonsoft.Json.Linq.JToken buildData = {Newtonsoft.Json.Linq.JObject}) Line 437	C#	Symbols loaded.
 	GitExtensions.AppVeyorIntegration.dll!AppVeyorIntegration.AppVeyorAdapter.UpdateDescription(AppVeyorIntegration.AppVeyorBuildInfo buildDetails = {AppVeyorIntegration.AppVeyorBuildInfo}, System.Threading.CancellationToken cancellationToken = IsCancellationRequested = false) Line 417	C#	Symbols loaded.
 	GitExtensions.AppVeyorIntegration.dll!AppVeyorIntegration.AppVeyorAdapter.ObserveBuilds(System.IObserver<GitUIPluginInterfaces.BuildServerIntegration.BuildInfo> observer = {System.Reactive.AutoDetachObserver<GitUIPluginInterfaces.BuildServerIntegration.BuildInfo>}, System.Threading.CancellationToken cancellationToken = IsCancellationRequested = false) Line 359	C#	Symbols loaded.
 	GitExtensions.AppVeyorIntegration.dll!AppVeyorIntegration.AppVeyorAdapter.GetBuilds.AnonymousMethod__2() Line 322	C#	Symbols loaded.
```

Payload:
```json
{
  "buildId": 33119920,
  "projectId": 0,
  "jobs": [
    {
      "jobId": "42cdwfd9reqnc5e3",
      "name": "",
      "osType": "Windows",
      "allowFailure": false,
      "messagesCount": 0,
      "compilationMessagesCount": 0,
      "compilationErrorsCount": 0,
      "compilationWarningsCount": 0,
      "testsCount": 0,
      "passedTestsCount": 0,
      "failedTestsCount": 0,
      "artifactsCount": 0,
      "status": "starting",
      "created": "2020-05-26T21:24:39.0580037+10:00",
      "updated": "2020-05-26T21:37:45.3407094+10:00"
    }
  ],
  "buildNumber": 9556,
  "version": "3.4.0.9556",
  "message": "Hide extra separator in context menu for folder item (#8138)",
  "messageExtended": "Co-authored-by: Gerhard Olsson <gerhardol@users.noreply.github.com>",
  "branch": "release/3.4",
  "isTag": false,
  "commitId": "fd54418501f3f48ab274e151509cae9bcca352fc",
  "authorName": "Igor Velikorossov",
  "authorUsername": "RussKie",
  "committerName": "GitHub",
  "committerUsername": "web-flow",
  "committed": "2020-05-26T21:24:34+10:00",
  "messages": [],
  "status": "starting",
  "created": "2020-05-26T21:24:38.0713663+10:00",
  "updated": "2020-05-26T21:37:45.3407094+10:00"
}
```

## Expected behaviour

No exceptions

## Steps to reproduce

No idea. I started the app under the debugger...

## Environment

- Build 71ee25272ff39bcc59dedca0a4d8fc956cb68971

### PR DESCRIPTION
**Pull request by pmiossec**
Fixes #8150

## Proposed changes

- return 0 instead of throwing an NRE

## Test methodology 

- None. Occured one time but difficult to reproduce.

## Test environment(s) 

- Git Extensions 3.3.0
- Build 0ef262dc8eddb1d6b8958d4cf7bf730c8ce28739
- Git 2.25.0.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4180.0
- DPI 168dpi (175% scaling)

### CODE REVIEW

File: Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs [hunk 1]
```diff
@@ -434,9 +434,14 @@ private void UpdateDescription(AppVeyorBuildInfo buildDetails, CancellationToken
 
         private static long GetBuildDuration(JToken buildData)
         {
-            var startTime = buildData["started"].ToObject<DateTime>();
-            var updateTime = buildData["updated"].ToObject<DateTime>();
-            return (long)(updateTime - startTime).TotalMilliseconds;
+            var startTime = buildData["started"]?.ToObject<DateTime>();
```
Comment (gerhardol) [inline Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs:437]: The log in #8150 has 'created', should be used first

```suggestion
            var startTime = buildData["started"]?.ToObject<DateTime>() ?? buildData["created"]?.ToObject<DateTime>();
```

Comment (pmiossec) [reply Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs]: indeed. done.

**Comment by RussKie** [comment]
Thank you
