### PR TITLE
Ignore OperationCanceledException from ProcessCmdKey

### LINKED ISSUE #11636: OperationCanceledException not caught by GitExtensionsControl.ProcessCmdKey
### Environment

- Git Extensions 33.33.33
- Build b16c117255f8e5449b6c004ef5332ffd8a24f929
- Git 2.42.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.2
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at GitUI.RevisionGridControl.PerformRefreshRevisions(Func`2 getRefs, Boolean forceRefreshRefs) in F:\Build\gitextensions3\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 979
   at GitUI.RevisionGridControl.ShowRevisionFilterDialog() in F:\Build\gitextensions3\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 1967
   at GitUI.RevisionGridControl.ExecuteCommand(Int32 cmd) in F:\Build\gitextensions3\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 3164
   at ResourceManager.GitExtensionsControl.ProcessHotkey(Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData) in F:\Build\gitextensions3\ResourceManager\GitExtensionsControl.cs:line 123
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& message)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

### Steps to reproduce

- open filter dialog using hotkey (`Ctrl+I`)
- filter for file path and author
- confirm

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11636

## Proposed changes

- Ignore `OperationCanceledException` and `TaskCanceledException` in the `BugReportInvoker`
- Just trace them in debug builds

### Before

BugReporter

### After

nothing

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — APPROVED** [review]

File: ResourceManager/GitExtensionsFormBase.cs [hunk 1]
```diff
@@ -95,7 +95,14 @@ protected void LoadHotkeys(string hotkeySettingsName)
...
         protected override bool ProcessCmdKey(ref Message msg, Keys keyData)
         {
-            return ProcessHotkey(keyData) || base.ProcessCmdKey(ref msg, keyData);
+            try
+            {
+                return ProcessHotkey(keyData) || base.ProcessCmdKey(ref msg, keyData);
+            }
+            catch (OperationCanceledException)
+            {
+                return true;
```
Comment (RussKie) [inline ResourceManager/GitExtensionsFormBase.cs:104]: Worth adding a comment why we're doing it here

**Review by RussKie — APPROVED** [review]

**Review by gerhardol — APPROVED** [review]

**Review by RussKie — APPROVED** [review]
