### PR TITLE
Include stash, bisect in grid if tags are shown

### LINKED ISSUE #8879: "bisect" labels no longer displayed
## Current behaviour

image

## Expected behaviour

Git Extensions 3.4.3.9999
image

## Steps to reproduce

Start bisect and compare 3.4.3 version with the current dev

## Did this work in previous version of GitExtensions

Git Extensions 3.4.3.9999

## Environment

- Git Extensions 33.33.33
- Build 221fc396b5db296c45d566a35a76facd6fbab38b (Dirty)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #8879

## Proposed changes

Revert behavior to be same as in 3.4

If tag labels are shown, also show bisect, notes, stash etc

Note that the labels were orange in 3.4, changed in #8424

### Before

(slightly older than master)
image

### After

image

## Test methodology 

Manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Thank you.
Please let me tinker with it.

File: GitCommands/Git/Commands/GitCommandHelpers.cs [hunk 1]
```diff
@@ -109,9 +109,7 @@ public static ArgumentString GetRefsCmd(bool tags, bool branches, bool noLocks,
             {
                 { sortBy != GitRefsSortBy.Default, GetSortCriteria(tags, sortBy, sortOrder), string.Empty },
                 format,
-                { branches, "refs/heads/", string.Empty },
-                { branches && tags, "refs/remotes/", string.Empty },
-                { tags, "refs/tags/", string.Empty },
+                { !tags, "refs/remotes/ refs/heads/", string.Empty },
```
Comment (RussKie) [inline GitCommands/Git/Commands/GitCommandHelpers.cs:112]: This is incorrect, since this would never be true.

Since we can't filter at `` commands, we can fix it by delegating the filter to the bash:
```diff
                 format,
-                { branches, "refs/heads/", string.Empty },
-                { branches && tags, "refs/remotes/", string.Empty },
-                { tags, "refs/tags/", string.Empty },
+                { !branches, "| sed 'refs\\/heads\\//d", string.Empty },
+                { !(branches && tags), "| sed 'refs\\/remotes\\//d", string.Empty },
+                { !tags, "| sed 'refs\\/tags\\//d", string.Empty },
             };
```

Comment (RussKie) [reply GitCommands/Git/Commands/GitCommandHelpers.cs:112]: Here's the fix for the tests:
```diff
diff --git a/UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs b/UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
index ec2ab688c..62e35dee9 100644
--- a/UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
+++ b/UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
@@ -664,13 +664,14 @@ private static IEnumerable<TestCaseData> GetRefsCommandTestData
                         }
 
                         yield return new TestCaseData(/* tags */ true, /* branches */ true, /* noLocks */ false, sortBy, sortOrder,
-                            /* expected */ $@"for-each-ref{sortConditionRef}{sortCondition}{format} refs/heads/ refs/remotes/ refs/tags/");
+                            /* expected */ $@"for-each-ref{sortConditionRef}{sortCondition}{format}");
                         yield return new TestCaseData(/* tags */ true, /* branches */ false, /* noLocks */ false, sortBy, sortOrder,
-                            /* expected */ $@"for-each-ref{sortConditionRef}{sortCondition}{format} refs/tags/");
+                            /* expected */ $@"for-each-ref{sortConditionRef}{sortCondition}{format} | sed 'refs\/heads\//d | sed 'refs\/remotes\//d");
                         yield return new TestCaseData(/* tags */ false, /* branches */ true, /* noLocks */ false, sortBy, sortOrder,
-                            /* expected */ $@"for-each-ref{sortCondition} --format=""%(objectname) %(refname)"" refs/heads/");
+                            /* expected */ $@"for-each-ref{sortCondition} --format=""%(objectname) %(refname)"" | sed 'refs\/remotes\//d | sed 'refs\/tags\//d");
+
                         yield return new TestCaseData(/* tags */ false, /* branches */ true, /* noLocks */ true, sortBy, sortOrder,
-                            /* expected */ $@"--no-optional-locks for-each-ref{sortCondition} --format=""%(objectname) %(refname)"" refs/heads/");
+                            /* expected */ $@"--no-optional-locks for-each-ref{sortCondition} --format=""%(objectname) %(refname)"" | sed 'refs\/remotes\//d | sed 'refs\/tags\//d");
                     }
                 }
             }
```

Comment (gerhardol) [reply GitCommands/Git/Commands/GitCommandHelpers.cs:112]: The argument need to be added twice, in some other way. But the matching should be done on a positional base, sed will match in the middle of the refs too

Comment (gerhardol) [reply GitCommands/Git/Commands/GitCommandHelpers.cs]: I changed the solution to handle the RevGrid usage specially and explicitly, to really show that this is a special usage.
I looked at the usage for when both tags and branches were retrieved, they were all to get remotes - that should be a separate option too, but I do not want to change the IGitModule interface. Added some xml doc.

Note that stash, notes, bisect labels are always shown.

File: GitCommands/Git/GitModule.cs [hunk 2]
```diff
@@ -2903,6 +2903,18 @@ public RemoteActionResult<IReadOnlyList<IGitRef>> GetRemoteServerRefs(string rem
...
+        }
+
+        /// <summary>
+        /// Get the Git refs.
+        /// </summary>
+        /// <param name="tags">Include tags.</param>
+        /// <param name="branches">Include local branches, also remote branches if <see paramref="tags"/> is set.</param>
+        /// <param name="all">Include all refs (override <see paramref="tags"/>, <see paramref="branches"/>). This includes stash, bisect, stash.</param>
+        /// <returns>All Git refs.</returns>
+        public IReadOnlyList<IGitRef> GetAllRefs(bool tags = true, bool branches = true, bool all = false)
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs:2917]: If we're going down this path then we ought to create an enum:

Local
Remote
Tag
All = Local | Remote | Tag

File: GitCommands/Git/Commands/GitCommandHelpers.cs (hunk 1 above)
Comment (RussKie) [reply GitCommands/Git/Commands/GitCommandHelpers.cs]: > The argument need to be added twice, in some other way. But the matching should be done on a positional base, sed will match in the middle of the refs too

To match the start of line use `^`

https://www.howtogeek.com/666395/how-to-use-the-sed-command-on-linux/

Comment (RussKie) [reply GitCommands/Git/Commands/GitCommandHelpers.cs]: > The argument need to be added twice, in some other way. 

Can you please clarify this bit?

**Comment by RussKie** [comment]
The more pocessing we can offload to the underlying cli - the better, we'll do less work, less allocations, which is a win for our users.

File: GitCommands/Git/GitModule.cs (hunk 2 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:2917]: All is more than that, it was the problem here...
The handling of remotes is quite gross too. 

Can we make the change like this now and add an enum later in master?

**Comment by RussKie** [comment]
Sure

File: GitCommands/Git/GitModule.cs (hunk 2 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:2917]: Can we change the IGitModule interface here?

Comment (RussKie) [reply GitCommands/Git/GitModule.cs:2917]: Yes

File: GitCommands/Git/Commands/GitCommandHelpers.cs [hunk 3]
```diff
@@ -107,11 +108,11 @@ public static ArgumentString GetRefsCmd(bool tags, bool branches, bool noLocks,
...
             {
-                { sortBy != GitRefsSortBy.Default, GetSortCriteria(tags, sortBy, sortOrder), string.Empty },
+                { sortBy != GitRefsSortBy.Default, GetSortCriteria(hasTags, sortBy, sortOrder), string.Empty },
                 format,
-                { branches, "refs/heads/", string.Empty },
-                { branches && tags, "refs/remotes/", string.Empty },
-                { tags, "refs/tags/", string.Empty },
+                { (getRef & GetRefsEnum.All) == 0 && (getRef & GetRefsEnum.Branches) != 0, "refs/heads/", string.Empty },
+                { (getRef & GetRefsEnum.All) == 0 && (getRef & GetRefsEnum.Remotes) != 0, "refs/remotes/", string.Empty },
+                { (getRef & GetRefsEnum.All) == 0 && (getRef & GetRefsEnum.Tags) != 0, "refs/tags/", string.Empty },
```
Comment (RussKie) [inline GitCommands/Git/Commands/GitCommandHelpers.cs:115]: We're duplicating this code, so it is worth considering extracting it in a local static method:
```cs
static bool HasFlag(GetRefsEnum requested, GetRefsEnum flag)
    => (requested & GetRefsEnum.All) == 0 && (requested & flag) != 0;
```

**Review by RussKie — APPROVED** [review]
👍

File: GitCommands/Git/Commands/GitCommandHelpers.cs (hunk 3 above)
Comment (gerhardol) [reply GitCommands/Git/Commands/GitCommandHelpers.cs]: changed

**Comment by gerhardol** [comment]
Note that GetRefs are called six times during a refresh (probably four from the sidepanel).
The startup can be optimized...

Remotes were incorrectly handled in the latest commit, rebased and squashed.

File: GitCommands/Git/Commands/GitCommandHelpers.cs [hunk 4]
```diff
@@ -79,10 +79,11 @@ public static ArgumentString AddSubmoduleCmd(string remotePath, string localPath
                 };
         }
 
-        public static ArgumentString GetRefsCmd(bool tags, bool branches, bool noLocks, GitRefsSortBy sortBy, GitRefsSortOrder sortOrder)
+        public static ArgumentString GetRefsCmd(GetRefsEnum getRef, bool noLocks, GitRefsSortBy sortBy, GitRefsSortOrder sortOrder)
         {
             string format;
-            if (!tags)
+            bool hasTags = (getRef & GetRefsEnum.All) != 0 || (getRef & GetRefsEnum.Tags) != 0;
```
Comment (RussKie) [inline GitCommands/Git/Commands/GitCommandHelpers.cs:85]: Did you miss this one?

**Review by RussKie — APPROVED** [review]

File: GitCommands/Git/Commands/GitCommandHelpers.cs (hunk 4 above)
Comment (gerhardol) [reply GitCommands/Git/Commands/GitCommandHelpers.cs:85]: This is different - I can add a special if you prefer

**Comment by RussKie** [comment]
No worries then
