### PR TITLE
fix(FormGoToCommit): Improve performance

### LINKED ISSUE #11683: "Go To Commit" dialog is SLOW when there are many tags
### Environment

- GitExtensions version: 4.2.1.17611
- GIT version: 2.44.0.windows.1
- OS version: Microsoft Windows NT 10.0.19045.0  (Windows 10 Enterprise 22H2 build 19045.4170)
- .NET version: 6.0.28

### Issue description

When there are many tags in the repo, using menu choice [Navigate] > [Go To Commit] (key default Cttrl+Shift+G), the dialog box appears quickly but takes a long time to be ready, due to loading all the tags into the "Go to tag" control.  If you want to simply enter a commit expression, you cannot rapidly go to it: clicking in the control just puts the dialog into "(Not Responding)" status.  The user must wait for the 45-95 seconds it takes to load the tag window.   If the user is in a hurry and already has a commit expression to enter, this is a counterproductive delay: the user doesn't need the control populated in order to enter their expression.

Possible Corrective Actions (in order of likely desireability):
- you could put the control loaders in separate threads so the dialog is immediately ready, and set the dialog up to enable the "Go" button as soon as a commit expression is entered
- you could preload a cache for the controls when a checkout is done (again, probably in a separate thread so you don't hold up other things)
- you could force the user to await the controls loading for the first visit, but cache the data at that time, which would at least mean all subsequent visits would be quick
- other solutions may be available and should be investigated

### Steps to reproduce

1. Open a repo that has a LOT of tags.   (Unfortunately, I can't tell you how many tags is "a lot."  It will require investigation.)
2. Find a commit hash somewhere else in the history than where you are.  Note the first 6-8 characters.
3. Go to menu choice [Navigate] > [Go To Commit] (or use the default key mapping of Ctrl+Shift+G if that is valid on your machine).
4. When the dialog appears, immediately click on the "Commit expression" control and try to enter your partial commit hash.
5. Observe the dialog goes into "(Not Responding)" state.
6. Further observe that you have to wait (potentially more than a minute!) for the dialog to become ready.  If you attempt to cancel the operation using the "X" in the dialog banner, in Windows you get the OS's warning dialog that the application is not responding and you can either kill the application or wait for the dialog to be ready.  Thus if you open this dialog in a hurry in a tag-rich repo, YOU ARE STUCK until it has loaded all the tags.

### Did this work in previous version of GitExtensions?

Don't know.

### Diagnostics

No diagnostics available.

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11683

## Proposed changes

`FormGoToCommit`:
- limit number of loaded branches and tags to 20.000 entries each
- assign `DisplayMember` first!
- activate `TextChanged` last
- cancel loading on `FormClosed`

## Screenshots 

N/A

## Test methodology 

- manual
- simulate lots of tags

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
BTW: `AsyncLoader` hides exceptions (by default)!

**Comment by mstv** [comment]
How long does https://ci.appveyor.com/api/buildjobs/3als72ks8po3va54/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.1.0.17932-21427d51e.zip block the UI for your repo, @cforbin1?

**Comment by gerhardol** [comment]
Why not send the refs from FormBrowse, it is calculated when loading the grid?

File: src/app/GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs [hunk 1]
```diff
@@ -6,6 +6,8 @@ namespace GitUI.CommandsDialogs.BrowseDialog
 {
     public sealed partial class FormGoToCommit : GitModuleForm
     {
+        private const int _maxDropDownCount = 20_000;
```
Comment (RussKie) [inline src/app/GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs:9]: This feels like a lot.... Why this many and, say, not 1,000 or 3,000?

Comment (mstv) [reply src/app/GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs:9]: > This feels like a lot.... Why this many and, say, not 1,000 or 3,000?

It is a restriction. That's why I chose a larger number with which the UI is blocked shortly enough.
I even was afraid someone would request a button in order to load all refs.
(Furthermore, the ComboBox dropdown is unable to list more than ~ 35,000 entries without weird scrollbar behavior.)

**Comment by cforbin1** [comment]
77 seconds!I wish we didn't have so many tags, but we do --- there are several teams working out of this repo, and I don't have the clout necessary to force a re-org, which is what I think should REALLY happen.
-------- Original message --------From: Michael Seibt ***@***.***> Date: 10/1/24  16:40  (GMT-05:00) To: gitextensions/gitextensions ***@***.***> Cc: CForbin ***@***.***>, Mention ***@***.***> Subject: Re: [gitextensions/gitextensions] fix(FormGoToCommit): Improve
  performance (PR #11952) 
How long does https://ci.appveyor.com/api/buildjobs/3als72ks8po3va54/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.1.0.17932-21427d51e.zip block the UI for your repo, @cforbin1?

**Comment by cforbin1** [comment]
Oh, wait.My bad, I didn't see the attachment, MANY apologies for trying to do too many things at once!I'll put the zip contents into place and will let you know...
-------- Original message --------From: sw7dev ***@***.***> Date: 10/3/24  13:07  (GMT-05:00) To: gitextensions/gitextensions ***@***.***>, gitextensions/gitextensions ***@***.***> Cc: Mention ***@***.***> Subject: Re: [gitextensions/gitextensions] fix(FormGoToCommit): Improve
  performance (PR #11952) 77 seconds!I wish we didn't have so many tags, but we do --- there are several teams working out of this repo, and I don't have the clout necessary to force a re-org, which is what I think should REALLY happen.-------- Original message --------From: Michael Seibt ***@***.***> Date: 10/1/24  16:40  (GMT-05:00) To: gitextensions/gitextensions ***@***.***> Cc: CForbin ***@***.***>, Mention ***@***.***> Subject: Re: [gitextensions/gitextensions] fix(FormGoToCommit): Improve
  performance (PR #11952) 
How long does https://ci.appveyor.com/api/buildjobs/3als72ks8po3va54/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.1.0.17932-21427d51e.zip block the UI for your repo, @cforbin1?

**Comment by cforbin1** [comment]
> How long does https://ci.appveyor.com/api/buildjobs/3als72ks8po3va54/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.1.0.17932-21427d51e.zip block the UI for your repo, @cforbin1?

Okay, this time I paid attention (!!) and installed the portable version.
MUCH much better!   **This version blocks for only 6-8 seconds.**
(I tried it about a half dozen times.)

**Review by gerhardol — APPROVED** [review]

**Review by RussKie — APPROVED** [review]
