### PR TITLE
fix: Application crashes when selecting "Go to commit" and having big contents in clipboard

### LINKED ISSUE #6288: Application crashes when selecting "Go to commit" and having big contents in clipboard
## Current behaviour
Application crashes.
## Expected behaviour
Application should not crash if clipboard contents is too big to handle.
## Steps to reproduce
* Open a big text file (> 32kB),
* copy the whole contents,
* select "Go to commit" from the Navigate menu -> application crashes.
## Screenshots
gitex1
## Did this work in previous version of GitExtensions
Unknown.
## Environment
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #6288

## Proposed changes

- Ignore any revision expression that are either null, whitespace or longer than 260 chars.

## Test methodology 

- added unit tests

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: UnitTests/GitCommandsTests/GitModuleTests.cs [hunk 1]
```diff
@@ -316,6 +316,15 @@ public void ParseRefs()
             Assert.AreSame(_gitModule, refs[3].Module);
         }
 
+        [TestCase(null)]
+        [TestCase("")]
+        [TestCase("\t")]
+        [TestCase("012345678abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789")]
```
Comment (pmiossec) [inline UnitTests/GitCommandsTests/GitModuleTests.cs]: Perhaps a little better...

```suggestion
        [TestCase("A very long string exceeding the limit of length handled (260 characters) 012345678abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz01234567")]
```

Comment (RussKie) [reply UnitTests/GitCommandsTests/GitModuleTests.cs]: Apologies, I got distracted and didn't see your suggestion until after the merge.
I will fix it up. Thank you
