### PR TITLE
#5665 Commit info not sized correctly

### LINKED ISSUE #5665: Commit info not sized correctly
**Do you want to request a *feature* or report a *bug*?**
layout regression

**What is the current behavior?**
image

**What is the expected behavior?**
The commit info is taking all available space

**Environment you encounter the issue:**
master @ 970ea53081a782f6c6dedbf5b146a51c80fa1c7c

- Git Extensions 3.00.a1
- 970ea53081a782f6c6dedbf5b146a51c80fa1c7c  (Dirty)
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3163.0

**Did this work in previous version of GitExtensions (which)?**
yes

/cc: @NikolayXHD

### PR DESCRIPTION
**Pull request by NikolayXHD**
Fixes #5665

Changes proposed in this pull request:
- Commit info `layoutTable` is laid out manually in `Layout` event
- `CommitInfoHeader` is still resized automatically
- Commit message and Revision info take all available width

What did I do to test the code and ensure quality:
- Tested on Windows 7
- tested `CommitInfo` layout in `FormCommit` (all 3 positions), `BlameControl`, and `CommitDiff`

### CODE REVIEW

**Comment by RussKie** [comment]
It works for the most part. 

However occasionally it fails to correctly recalc the height, as if the resize event is arriving to late
commit-info-scroll-issue

**Comment by RussKie** [comment]
I wonder if we can force resize by setting `MinimumSize` property for the control, this way we can `Dock=Fill` it and force the scrollbars, when necessary.
Thoughts?

**Comment by RussKie** [comment]
What I'd do is go back and pretty much start from the scratch.

Something like the following (thinking out loud):

- extract the message panel into a separate control (say CommitInfoMessage)
- calculate preferred size at the CommitInfoHeader control
- ditto for CommitInfoMessage
- in the CommitInfo control remove the footer rtb, set the minimum size for
both the header and the message controls based on the preferred size
(width=max of two).
- get the control to work in the above setup
- then restore the footer control, set its minimum width to the above, and
ensure everything still works.

Thoughts?

**Comment by gerhardol** [comment]
> I don't feel like it's time yet to start from the scratch

I agree, unless we are to replace WInForms

**Comment by NikolayXHD** [comment]
Manually calculated layout did not affect scrolls correctly sometimes, because custom layout logic is not supposed to be handled in `Layout` event, instead it has to be handled in overriden `OnLayout` method, which is said in `OnLayout` doc.

Rich text box `HideSelection` property did not work because of `SetHideSelectionInternal` calls in `SetXhtmlText`. I believe these calls are redundant because `BeginUpdate` / `EndUpdate` were called to prevent painting intermediate RTB state. In .NET40 `SetHideSelectionInternal` was nesessary, I noticed visible selection changes despite `BeginUpdate` / `EndUpdate` too.

I removed some `DoubleBuffered = true` in `CommitInfo`. All painting there consists in filling client area with background color which is not changed over time. From my understanding it cannot flicker. Correct me if I am wrong.

**Comment by mstv** [comment]
Looks good with my configuration.
But on startup the commit message can be missing.
Reproducible with the GE repo but not with another one.
grafik

**Comment by NikolayXHD** [comment]
> the commit message can be missing

Was in the fresh build from 95337d1 ?

**Comment by mstv** [comment]
Yes, I ran the AppVeyor build 3.00.00.4034.

**Comment by NikolayXHD** [comment]
Thanks for reporting, I see it too now. It did't happen when starting GitExt from IDE, that's why I missed it.

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -2981,7 +2981,7 @@ private void LayoutRevisionInfo()
             }
             else
             {
-                int width = DpiUtil.Scale(420);
+                int width = DpiUtil.Scale(490) + SystemInformation.VerticalScrollBarWidth;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs]: What's this magic number? Worth having at least a comment about it.
I know there was another undocumented magic number, but since you changed it, you probably have some idea what it is.

File: GitUI/CommitInfo/CommitInfo.Designer.cs [hunk 2]
```diff
@@ -250,6 +251,6 @@ private void InitializeComponent()
         private CommitInfoHeader commitInfoHeader;
         private System.Windows.Forms.Panel pnlCommitMessage;
         private System.Windows.Forms.RichTextBox rtbxCommitMessage;
-        private GitUI.UserControls.DoubleBufferedTableLayoutPanel tableLayout;
+        private System.Windows.Forms.TableLayoutPanel tableLayout;
```
Comment (RussKie) [inline GitUI/CommitInfo/CommitInfo.Designer.cs]: If you don't think `DoubleBufferedTableLayoutPanel` is useful, then we should remove it completely.
I added it whilst working on the commit info rendering.

**Comment by RussKie** [comment]
Further more, at 100%, 125% and 200% scaling - the new line is not needed, it is clearly rendered as a new line:

**100% without newline**
image
**100% with newline**
image

**125% without newline**
image
**125% with newline**
image

**200% without newline**
image
**200% with newline**
image


However, at 150% scaling the new line is necessary, otherwise the text is clipped
**150% without newline**
image
**150% with newline**
image

I'm really baffled... 😱

**Comment by NikolayXHD** [comment]
On the other hand, what an extremely good (actually good) luck to notice it from the very beginning!

**Comment by NikolayXHD** [comment]
Maybe it has to do with rounding issues when .NET calculates text area. Like every row gets underestimated 1 px and voila, the last row gets eaten.

**Comment by RussKie** [comment]
I've pushed a commit that adds a newline. 
I'm happy with the current implementation. I'm going to merge it as is, so we can publish a RC.

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 1 above)
Comment (NikolayXHD) [reply GitUI/CommandsDialogs/FormBrowse.cs]: ok

File: GitUI/CommitInfo/CommitInfo.Designer.cs (hunk 2 above)
Comment (NikolayXHD) [reply GitUI/CommitInfo/CommitInfo.Designer.cs]: ok

File: GitUI/CommitInfo/CommitInfo.cs [hunk 3]
```diff
@@ -213,7 +213,7 @@ void UpdateCommitMessage()
                 }
 
                 var commitMessage = _commitDataBodyRenderer.Render(data, showRevisionsAsLinks: CommandClickedEvent != null);
-                rtbxCommitMessage.SetXHTMLText(commitMessage);
+                rtbxCommitMessage.SetXHTMLText(commitMessage + Environment.NewLine);
```
Comment (gerhardol) [inline GitUI/CommitInfo/CommitInfo.cs]: I suggest a comment about the workaround here (to avoid Blame->PR discussion to find why).

Comment (RussKie) [reply GitUI/CommitInfo/CommitInfo.cs]: Good point, will do

Comment (RussKie) [reply GitUI/CommitInfo/CommitInfo.cs]: I actually was planning to merge your branch as is, unsquashed. 
This is one of those rare instances where I want to preserve the full history, given that we've (you mainly) gone through getting it right.

Comment (NikolayXHD) [reply GitUI/CommitInfo/CommitInfo.cs]: ok, let me unsquash then

**Comment by RussKie** [comment]
Thank you very much, you're a legend!

**Comment by NikolayXHD** [comment]
thank you :construction_worker:
