### PR TITLE
fix(FormRenameBranch): Run git interactively

### LINKED ISSUE #10375: ExternalOperationException from denied branch rename is swallowed
### Environment

- Git Extensions 33.33.33
- Build 0bd62f609cb1df6348acfc6098f0a7ac6b57dcf4
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

Errors from renaming a branch are only visible in the Git Command Log:

```
Exception:
 GitExtUtils.ExternalOperationException: error: 'refs/heads/release/4.0' exists; cannot create 'refs/heads/release/4.0/debug'
fatal: Branch rename failed
 ---> System.Exception: error: 'refs/heads/release/4.0' exists; cannot create 'refs/heads/release/4.0/debug'
fatal: Branch rename failed
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.RenameBranch(String name, String newName)
   at GitUI.CommandsDialogs.FormRenameBranch.OkClick(Object sender, EventArgs e)
Standard err:
 error: 'refs/heads/release/4.0' exists; cannot create 'refs/heads/release/4.0/debug'
fatal: Branch rename failed
```

### Steps to reproduce

- create / checkout a branch like 'release/4.0'
- create a branch 'release/4.0_debug'
- rename it to 'release/4.0/debug'

### Did this work in previous version of GitExtensions?

I doubt it

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10375

## Proposed changes

- FormRenameBranch: Run git interactively instead of manually dealing with git output and silent tracing of exceptions
- dialog remains open on error in order to be able to fixup the entered name

### Before

nothing but an entry in the Git Command Log:

image

### After

image

## Test methodology 

- manual
- adapt testcase

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/CommandsDialogs/FormRenameBranch.cs [hunk 1]
```diff
@@ -51,22 +51,10 @@ private void OkClick(object sender, EventArgs e)
                 return;
             }
 
-            try
-            {
-                string renameBranchResult = Module.RenameBranch(_oldName, newName);
```
Comment (gerhardol) [inline src/app/GitUI/CommandsDialogs/FormRenameBranch.cs:56]: I would have preferred to use the return status from the command instead, and present the error text.
You hate error hiding, I dislike popups that are not needed
Not requiring a change

**Review by gerhardol — APPROVED** [review]
Commit message is fix!, this changes the plugin interface

Have not run

File: src/app/GitUI/CommandsDialogs/FormRenameBranch.cs (hunk 1 above)
Comment (mstv) [reply src/app/GitUI/CommandsDialogs/FormRenameBranch.cs:56]: > I dislike popups that are not needed

The popup is transient if "Keep dialog open" is unticked and no error occurred.
(AD: The success output can be read in the Output History if the popup closes too fast. I.e. there is no need to "Keep dialog open" any longer. [FormProcess could even be merged into the Output History, i.e. less popups.])

Comment (gerhardol) [reply src/app/GitUI/CommandsDialogs/FormRenameBranch.cs:56]: >  (AD: The success output can be read in the Output History if the popup closes too fast. I.e. there is no need to "Keep dialog open" any longer. [FormProcess could even be merged into the Output History, i.e. less popups.])

Sidenote:
that is #10307 that I have approved and support, have used it even if I not have used it much. 
I mostly use the popup to open/view PRs from BitBucket/GitHub urls and that is more easily available and I have not changed how I work.
It has not been high on my agenda though to convince RussKie there.

So also this could be better if I change the way I work.
Right now I am mostly neutral, not enthusiastic at this moment... (Take this literally, no understatement.)
