### PR TITLE
Fix FileViewer's encoding bug when showing unstaged files

### LINKED ISSUE #11934: Garbled characters in rebase branch interactively.
### Environment

- GitExtensions version: Git Extensions 5.0.0.17897
- GIT version:  Git 2.43.0.windows.1
- OS version: Microsoft Windows NT 10 19045.0
- .NET version:  .NET 8.0.8

### Issue description

when using rebase with selected commit interactively, garbled characters appear.

image

### Steps to reproduce

type chinese in commit message, than rebase with selected commit interactively.

### Did this work in previous version of GitExtensions?

it work fine in Git Extensions 4.0 (in the same git repository / the same system / diff .net core version).

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mdonatas**
Fixes #11934

A bigger issue than originally mentioned in #11934 is that currently TextEditor provided/used by GitExtensions actually corrupts files 😬

## Proposed changes

- ICSharpCode.TextEditor has a helper which attempts to auto-detect the encoding, lets use it
- Depends on https://github.com/gitextensions/ICSharpCode.TextEditor/pull/42 because of this line [`FilePreamble = reader.CurrentEncoding.GetPreamble();`](https://github.com/gitextensions/gitextensions/blob/master/src/app/GitUI/Editor/FileViewer.cs#L793)
- For good measure, lets avoid creating `MemoryStream` when not necessary and we can write straight to `FileStream`

### Before

Switching between UTF8 file without BOM and with BOM

https://github.com/user-attachments/assets/b746f341-b702-427d-9514-2e83874c6d98

After save using `fileeditor` (`F4` from within commit dialog) ⚠️⚠️⚠️ notice corruption in a file without BOM

https://github.com/user-attachments/assets/6db61e34-6906-4713-a16b-fe100110bc35

### After

Both files even after saving them with `fileeditor` (`F4` from within commit dialog) are recognized as UTF8

https://github.com/user-attachments/assets/23260abd-30e1-4848-8027-323de38f1bcf

## Test methodology 

- Manually, checking files visually and with Hex editor

## Test environment(s) 

- Windows 11

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mdonatas** [comment]
p.s. currently HEX view of binary files is broken when they are staged, that is this was already broken before this PR and this PR doesn't do anything to fix it. That fix will come later.

File: src/app/GitUI/Editor/FileViewer.cs [hunk 1]
```diff
@@ -786,7 +786,7 @@ public Task ViewFileAsync(string fileName, bool isSubmodule = false, FileStatusI
             string GetFileText()
             {
                 using FileStream stream = File.Open(fullPath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
-                using StreamReader reader = new(stream, GitModule.LosslessEncoding);
+                using StreamReader reader = ICSharpCode.TextEditor.Util.FileReader.OpenStream(stream, GitModule.LosslessEncoding);
```
Comment (mstv) [inline src/app/GitUI/Editor/FileViewer.cs:789]: code style if possible:
```suggestion
using ICSharpCode.TextEditor.Util;
                using StreamReader reader = FileReader.OpenStream(stream, GitModule.LosslessEncoding);
```

**Review by mstv — COMMENTED** [review]
LGTM, have not run

**Review by RussKie — COMMENTED** [review]
👍

File: src/app/GitUI/Editor/FileViewer.cs (hunk 1 above)
Comment (mdonatas) [reply src/app/GitUI/Editor/FileViewer.cs]: done

**Review by gerhardol — APPROVED** [review]
have not run

**Review by mstv — APPROVED** [review]
