### PR TITLE
#6147 inverted diffs after refresh

### LINKED ISSUE #6147: inverted diffs after refresh
## Current behaviour

Under certain circumstances, the diffs shown in the Diff tab can be inverted just by refreshing the GUI.
I.e. when showing the differences from _<some_old_commit>_ to _<some_new_commit>_ and refreshing the GUI, the Diff tab shows the differences from _<some_new_commit>_ to _<some_old_commit>_ instead.

## Expected behaviour

Diffs shall not be shown as inverted, no matter whether the GUI is refreshed or not.

## Steps to reproduce

1. Load any repository in GitExtensions and click on the Diff tab.

2. Select any commit, except the latest one in your revision graph.
bugdiffrefresh1

3. Hold the CTRL key and select another commit, which is **after** the first one (i.e. more top-wards in the revision graph). It doesn't have to be on the same branch and it doesn't have to be a direct child commit. It may also be one of the artificial commits (if enabled).
It is important, however, that the second commit is shown above the first one in the revision graph.
bugdiffrefresh2

4. Press F5 or click on the Refresh icon.
bugdiffrefresh3

## Did this work in previous version of GitExtensions

Yes, GitExtensions 2.51.05 is not inverting the diffs.

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by ignacioerrico**
Fixes #6147 

## Proposed changes

- The `HashSet ToBeSelectedObjectIds` should be a `List`, because order matters.
- There is no need for `ToBeSelectedRowIndexes` to be a `ConcurrentQueue`, since we want to wait till we have all the rows to be selected and, when we have them, we select them. The list of indices can thus be stored in a `List` that includes order information.

### Before

The grid attempts to select a commit as soon as it is loaded. Consequently, rows are being selected in the order in which revisions are read, not in the order in which they had originally been selected.

### After

By waiting till all rows to be selected have been added to the grid before attempting to select them, we can select them in the correct order. With the current implementation, that's the best that can be done if we don't want to wait till all commits have been loaded before attempting to select the rows.

## Test methodology 

- Manual testing. I followed the same steps as indicated in the ticket, and verified that the behavior is as expected.
  - I considered special cases, like selection of many commits, and selection of commits at both ends of the commit history. (By the way, without these changes, a selection scattered throughout the commit history, would produce a new random selection when refreshing.)

## Test environment(s) 

- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt), which I signed in [this pull request](https://github.com/gitextensions/gitextensions/pull/6384).

### CODE REVIEW

**Comment by ignacioerrico** [comment]
It looks much better now! Thanks for explaining the correct workflow, @mast-eu!

File: GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs [hunk 1]
```diff
@@ -178,11 +177,21 @@ internal Font NormalFont
 
         internal AuthorRevisionHighlighting AuthorHighlighting { get; set; }
 
-        // Contains the object Id's that will be selected as soon as they are loaded.
-        public HashSet<ObjectId> ToBeSelectedObjectIds { get; set; } = new HashSet<ObjectId>();
+        // Contains the object Id's that will be selected as soon as all of them have been loaded.
+        // The object Id's are in the order in which they were originally selected.
+        public List<ObjectId> ToBeSelectedObjectIds { get; set; } = new List<ObjectId>();
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs]:
```suggestion
        public IReadOnlyList<ObjectId> ToBeSelectedObjectIds { get; set; } = new List<ObjectId>();
```

**Comment by RussKie** [comment]
@spdr870 could you please review

File: GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs]: Fails to compile with this change

**Comment by gerhardol** [comment]
Looks OK and works for me.

File: GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs [hunk 2]
```diff
@@ -290,9 +299,15 @@ public void Add(GitRevision revision, RevisionNodeFlags types = RevisionNodeFlag
...
             _revisionGraph.Add(revision, types);
 
-            if (ToBeSelectedObjectIds.Remove(revision.ObjectId))
+            if (ToBeSelectedObjectIds.Contains(revision.ObjectId))
             {
-                ToBeSelectedRowIndexes.Enqueue(_revisionGraph.Count - 1);
+                var rowIndexToBeSelectedWithOrderInfo = new RowIndexToBeSelectedWithOrderInfo
+                {
+                    RowIndex = _revisionGraph.Count - 1,
+                    SelectionOrder = ToBeSelectedObjectIds.IndexOf(revision.ObjectId)
```
Comment (illfated) [inline GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs]:
```csharp
UserControls\RevisionGrid\RevisionDataGridView.cs(307,68):
 error CS1503: Argument 2:
 cannot convert from 'GitUIPluginInterfaces.ObjectId' to 'System.Func<GitUIPluginInterfaces.ObjectId, bool>' 
```

Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs]: See my review comment about the compile error introduced by the latest commit.

File: GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs (hunk 1 above)
Comment (ignacioerrico) [reply GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs]: That was my fault.

RussKie suggested turning `ToBeSelectedObjectIds` from a `List` to an `IReadOnlyList`. That makes sense, since `ToBeSelectedObjectIds` contains a fixed list of commits that are to be selected, so I accepted the change.

However, I overlooked the fact that `IndexOf(T)` is a method of `List<T>`. For an `IReadOnlyList`, the extension method `IndexOf` on `IEnumerable<T>` takes a lambda instead of an object, as the error message indicates.

**Comment by ignacioerrico** [comment]
The commits in my branch have been squashed.

By the way, and I hope I don't sound pretentious by asking this, but should I add my name to the resource file `GitUI\Properties\Resources.resx`, which includes the list of contributors? How is that file updated?

**Comment by illfated** [comment]
I imagine some kind of "magic" script would pick the coder names from the list of commits or the blame list from the current released source. Then again, I could be wrong and the list could be a manually written one.

**Comment by vbjay** [comment]
No. Our release generation automatically adds authors.

**Comment by gerhardol** [comment]
See Setup/Prepare-Release.ps1 for contributors update

**Comment by RussKie** [comment]
Thank you.

@ignacioerrico you will see your name added in the next release.

**Comment by ignacioerrico** [comment]
Thank you guys for explaining that. I'm really glad to be a contributor to this terrific project! :-)
