### PR TITLE
Stash: Keyboard navigation

### LINKED ISSUE #8108: Current stash list UI control disallow quickily navigate between the changes of all stashes
## Current behavior

The current "Manage stashes" UI is using combo-box to select which stash to show its changes. However, after user clicked or press ENTER on a selected stash, the focus on the combo-box control (with label "Show:") is lost. This makes the user cannot use the arrow key in the keyboard to quickly switch to another stash (they must use mouse with at least two clicks and one movement, to jump to the next stash).

Consequence: This is inconvenience if I want to inspect all stashes to see if they are still useful, so as to clean-up some useless ones.

P.S. this is so far the worst UI flow, which pushes me to find other Git GUI client to help.

## Expected behavior

After the user selected a stash in the combo-box of "Show:", in the "Manage stashes" view, the focus should be kept. And allow user to use up-arrow/down-arrow to directly switch to previous/next stash to show the changes immediately, with one keystroke only.

## Steps to reproduce

Choose Main Menu > Commands > "Manage stashes" that jump to the UI view which inspects stashes and their changes. Click the combo-box labeled by "Show:", and click one item. Then, try using up-arrow or down-array key to navigate to previous/next stash --> it is impossible, must use mouse with multi-clicks and movement (inconvenience).

## Screenshots

(focus of the "Show:" combo-box is lost after selected an item by mouse-clicking or keyboard ENTER of the combo-box list)

image

## Did this work in previous version of GitExtensions

No.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #8108

## Proposed changes

- HotKeys for next/previous stash and refresh
Ctrl-P navigates to next older stash item, similar to how navigation in RevGrid.

- Mnemonics for the form. 
As `Stashes` control gets a specific hotkey, it is possible to navigate in the stashes list with Alt-H arrow /PageUp/etc too
"&Apply stash" but "S&tash all changes" as I expect Ctrl-Alt-Up to be used for stash in current worktree.

- Stash: Keep position when dropping a stash 
Simplify deleting stashes, unless deleting the first, you would have to search for the stash close to where you just deleted the stash.

- Remove button for custom message, just make it writeable for worktree.
Add label for mnemonics 

### After

image

## Test methodology 

Manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — APPROVED** [review]
LGTM
Hotkey(s) for `Write custom stash message` (and for `Refresh`) would be nice.

**Comment by gerhardol** [comment]
> LGTM
> Hotkey(s) for `Write custom stash message` (and for `Refresh`) would be nice.

Implemented that too (also just showing refresh when it has effect, for worktree).

For the custom text mnemonics would be more natural than a hotkey, but then the logic for the custom message would need to be changed (remove button, add label and add to command if not empty) and I am not sure exactly how to handle.

**Comment by mstv** [comment]
> Implemented that too (also just showing refresh when it has effect, for worktree).

👍 Thank you!

> For the custom text mnemonics would be more natural than a hotkey, but then the logic for the custom message would need to be changed (remove button, add label and add to command if not empty) and I am not sure exactly how to handle.

I agree, it is not perfect. But I think this would be too much effort for little gain.
Though the hotkey should be displayed in the tooltip of `toolStripButton_customMessage`.
(BTW: The message can be double-clicked in order to enable editing it.)

File: GitUI/CommandsDialogs/FormStash.cs [hunk 1]
```diff
@@ -192,6 +211,60 @@ private void FileViewer_BottomScrollReached(object sender, EventArgs e)
...
+
+        private bool EnableCustomMessage()
+        {
+            if (Stashes.SelectedIndex != 0)
+            {
+                // Worktree not select, not relevant
+                return false;
+            }
+
+            toolStripButton_customMessage.Enabled = true;
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormStash.cs:248]:
```suggestion
            if(!toolStripButton_customMessage.Enabled)
            {
                return false;
            }
```

Comment (gerhardol) [reply GitUI/CommandsDialogs/FormStash.cs]: changed implementation

**Comment by gerhardol** [comment]
> I agree, it is not perfect. But I think this would be too much effort for little gain.

Replaced button with label, could also simplify the logic.
To some extent, also the label could be removed, the box is focused by default.
(Some struggling with WinForms layout as usual...)

**Review by RussKie — COMMENTED** [review]
:shipit:

**Review by mstv — APPROVED** [review]
Works for me. (The failing test is unrelated.)

**Comment by gerhardol** [comment]
rebased without further changes

**Comment by gerhardol** [comment]
@msftbot merge in 24 hours
