### PR TITLE
fix: assert in patch grid

### LINKED ISSUE #12456: [NBug] Index was out of range. Must be non-negative and less than ...
### Environment

- Git Extensions 33.33.33
- Build 32da873600da1a17dbc212ec7cd7042122c27dcf
- Git 2.50.1.windows.1
- Microsoft Windows NT 10.0.26100.0
- .NET 9.0.7
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

I'm in a middle of 5-commit rebase, where I skipped the first commit and attempted to skip the second.
At this step I'm getting the following git response in the Progress dialog:
```
"C:\Program Files\Git\bin\git.exe" -c rebase.autosquash=false rebase --skip
error: The following untracked working tree files would be overwritten by merge:
        src/......cs
Please move or remove them before you merge.
Aborting
hint: Could not execute the todo command
hint:
hint:     pick 0dd0b7fabfbc1a625dc83eac5a390128fd71a70d # ....
hint:
hint: It has been rescheduled; To edit the command before continuing, please
hint: edit the todo list first:
hint:
hint:     git rebase --edit-todo
hint:     git rebase --continue
Done

Press Enter or Esc to exit...
```

Closing the Progress dialog, I get the crash dialog:

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at GitUI.PatchGrid.RefreshGrid() in D:\Development\gitextensions\src\app\GitUI\UserControls\PatchGrid.cs:line 338
   at GitUI.CommandsDialogs.FormRebase.SkipClick(Object sender, EventArgs e) in D:\Development\gitextensions\src\app\GitUI\CommandsDialogs\FormRebase.cs:line 279
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### Steps to reproduce

¯\\_(ツ)\_/¯

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #12456

## Proposed changes

Add debug assert, avoid exception

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/UserControls/PatchGrid.cs [hunk 1]
```diff
@@ -332,8 +333,14 @@ public void RefreshGrid()
             Validates.NotNull(PatchFiles);
 
             IReadOnlyList<PatchFile> updatedPatches = GetPatches();
+            if (updatedPatches.Count > PatchFiles.Count)
+            {
+                string s = $"PatchGrid: RefreshGrid: PatchFiles count {PatchFiles.Count} is less than updatedPatches count {updatedPatches.Count}. This should not happen.";
+                DebugHelpers.Assert(true, s);
```
Comment (mstv) [inline src/app/GitUI/UserControls/PatchGrid.cs]:
```suggestion
```
To be removed because it has no effect at all.

File: src/app/GitUI/UserControls/PatchGrid.cs [hunk 2]
```diff
@@ -332,8 +333,14 @@ public void RefreshGrid()
             Validates.NotNull(PatchFiles);
 
             IReadOnlyList<PatchFile> updatedPatches = GetPatches();
+            if (updatedPatches.Count > PatchFiles.Count)
+            {
+                string s = $"PatchGrid: RefreshGrid: PatchFiles count {PatchFiles.Count} is less than updatedPatches count {updatedPatches.Count}. This should not happen.";
```
Comment (mstv) [inline src/app/GitUI/UserControls/PatchGrid.cs]: ❔
```suggestion
            if (updatedPatches.Count != PatchFiles.Count)
            {
                string s = $"PatchGrid: RefreshGrid: PatchFiles count {PatchFiles.Count} is different from updatedPatches count {updatedPatches.Count}. This should not happen.";
```

File: src/app/GitUI/UserControls/PatchGrid.cs (hunk 1 above)
Comment (gerhardol) [reply src/app/GitUI/UserControls/PatchGrid.cs]: should have been false, of course to notify if this occurs in Debug mode

**Review by RussKie — APPROVED** [review]
Thank you.

👍 modulo the @mstv's comment.

File: src/app/GitUI/UserControls/PatchGrid.cs [hunk 3]
```diff
@@ -332,8 +333,15 @@ public void RefreshGrid()
             Validates.NotNull(PatchFiles);
 
             IReadOnlyList<PatchFile> updatedPatches = GetPatches();
+            if (updatedPatches.Count != PatchFiles.Count)
+            {
+                // assert for popup in Debug
+                string s = $"PatchGrid: RefreshGrid: PatchFiles count {PatchFiles.Count} is different from updatedPatches count {updatedPatches.Count}. This should not happen.";
+                DebugHelpers.Assert(false, s);
+                Trace.Write(s);
```
Comment (mstv) [inline src/app/GitUI/UserControls/PatchGrid.cs]:
```suggestion
                // Fail for popup in Debug
                string s = $"PatchGrid: RefreshGrid: PatchFiles count {PatchFiles.Count} is different from updatedPatches count {updatedPatches.Count}. This should not happen.";
                Trace.Write(s);
                DebugHelpers.Fail(s);
```

**Review by mstv — APPROVED** [review]
