### PR TITLE
Apply action to all selected files in solve merge conflict

### LINKED ISSUE #6279: Selecting multiple files in a merge conflict continues to prompt.
## Current behaviour
Using "choose theirs" in a merge conflict with multiple files continues to prompt on deletes.

## Expected behaviour
When selecting multiple files, and "choose theirs" it should choose whatever is in "theirs" For example, if there are 25 deletes in theirs, it shouldn't prompt 25 times since chose theirs was already selected.

## Steps to reproduce
Begin a merge with a conflict that has several deletes in the branch.
Merge that branch in to your local branch causing a merge conflict. 
Select multiple files that have been deleted in "theirs", right click and select "choose theirs."
You'll be prompted for each file to keep modified or delete file.

## Screenshots

image

## Did this work in previous version of GitExtensions
no

## Environment

- GitExtensions version:3.00.00.443
- GIT version: 2.20.0.windows.1
- OS version: Windows 10.0.16299.0
- .NET version: 4.7.2650.0

### PR DESCRIPTION
**Pull request by racecrew**
Fixes #6279

## Proposed changes
Add a checkbox to apply an action to all conflicted files which an user has selected and wants to get handled at once without promting each time a dialog

### Before

SolveMergeConflict_Dialog_Before

### After

SolveMergeConflict_Dialog_After

## Test methodology 

Manual

## Test environment(s) 

- GIT 
- Windows 

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
checkbox must be above buttons

**Comment by RussKie** [comment]
> checkbox must be above buttons

Actually I am going to suggest the keep it but use a Task Dialog instead, like we have for the push
image

**Review by RussKie — CHANGES_REQUESTED** [review]
Let's take a little further and delete `FormModifiedDeletedCreated` replacing it with a Task Dialog (have a look at https://github.com/gitextensions/gitextensions/pull/8291).

Thank you

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 1]
```diff
@@ -53,6 +53,8 @@ public partial class FormResolveConflicts : GitModuleForm
         private readonly TranslationString _keepModifiedButtonText = new TranslationString("Keep modified");
         private readonly TranslationString _keepBaseButtonText = new TranslationString("Keep base file");
 
+        private readonly TranslationString _applyToAllCheckBoxText = new TranslationString("Apply to all");
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitUI/CommandsDialogs/FormResolveConflicts.cs:56]: It would be a better UX to say "this action applies to 2/3/10/... files" as opposed to "all" files. Will it apply to _all_ files or _all selected_ files?
Also the checkbox shouldn't be shown if there is only one file is selected.

**Comment by RussKie** [comment]
Also please provide your sign-off in contributors.txt. Thanks

File: GitUI/CommandsDialogs/FormResolveConflicts.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (racecrew) [reply GitUI/CommandsDialogs/FormResolveConflicts.cs:56]: Yes, you are completely right.

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 2]
```diff
@@ -95,6 +97,9 @@ public partial class FormResolveConflicts : GitModuleForm
 
         private readonly IFullPathResolver _fullPathResolver;
 
+        private bool _ResolveConflictsApplyToAll = false;
+        private string _ResolveConflictsApplyToAllLastAction = "";
```
[the remark this answers is not in the document]
Comment (racecrew) [reply GitUI/CommandsDialogs/FormResolveConflicts.cs:101]: I'll change this

**Comment by RussKie** [comment]
Please update all screenshots

**Comment by racecrew** [comment]
**One file is selected**

SolveMergeConflict_TaskDialog_OneFile_Selected

**Multiple files are selected**

SolveMergeConflict_TaskDialog_MultipleFilesSelected


By selecting multiple files some of them could have a "different type of change". The conflicted files are grouped as:
* deleted locally and modified remotely 
* modified locally and deleted remotely
* remained files

https://github.com/gitextensions/gitextensions/blob/c411ac64c5946ebdedf669f81911543da5dbe804/GitUI/CommandsDialogs/FormResolveConflicts.cs#L1209-L1229

The task dialog will prompt for each group and "apply to all" is remembered for only one group. Before processing a new conflict group the dialog will prompt. For the "remained files" the checkbox "apply to all" is hidden. For each of this file the dialog will prompt.

**deleted locally and modified remotely**

SolveMergeConflict_TaskDialog_MultipleFilesSelected_DeletedLocallyAndModifiedRemotely

**modified locally and deleted remotely**

SolveMergeConflict_TaskDialog_MultipleFilesSelected_ModifiedLocallyAndDeletedRemotely

File: GitUI/GitUI.csproj [hunk 3]
```diff
@@ -66,10 +66,13 @@
   </ItemGroup>
 
   <ItemGroup>
+    <Compile Remove="CommandsDialogs\ResolveConflictsDialog\**" />
     <Compile Remove="Resources\Icons\artwork\**" />
     <Compile Remove="Resources\Icons\originals\**" />
+    <EmbeddedResource Remove="CommandsDialogs\ResolveConflictsDialog\**" />
     <EmbeddedResource Remove="Resources\Icons\artwork\**" />
     <EmbeddedResource Remove="Resources\Icons\originals\**" />
+    <None Remove="CommandsDialogs\ResolveConflictsDialog\**" />
```
Comment (RussKie) [inline GitUI/GitUI.csproj:75]: I don't believe any of these are needed

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 4]
```diff
@@ -94,6 +99,21 @@ public partial class FormResolveConflicts : GitModuleForm
...
+        private enum SolveMergeConflictActionType
+        {
+            atNone = 0,
+            atKeepLocal = 1,
+            atKeepRemote = 2,
+            atKeepBase = 3
+        }
+
+        private SolveMergeConflictActionType _solveMergeConflictDialogResult;
+        private bool _SolveMergeConflictApplyToAll;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormResolveConflicts.cs:111]: Here and below, fields must follow the _camelCase_ notation
```suggestion
        private bool _solveMergeConflictApplyToAll;
```

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 5]
```diff
@@ -94,6 +99,21 @@ public partial class FormResolveConflicts : GitModuleForm
...
+        private SolveMergeConflictActionType _SolveMergeConflictLastAction;
+        private string _SolveMergeConflictDialogCheckboxText;
+        private delegate void SolveMergeConflictCheckRevisionDelegate(SolveMergeConflictActionType dialogResult);
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormResolveConflicts.cs:114]: Not needed, use `Action<SolveMergeConflictActionType>` instead

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 6]
```diff
@@ -94,6 +99,21 @@ public partial class FormResolveConflicts : GitModuleForm
         #endregion
 
         private readonly IFullPathResolver _fullPathResolver;
+        private enum SolveMergeConflictActionType
+        {
+            atNone = 0,
+            atKeepLocal = 1,
+            atKeepRemote = 2,
+            atKeepBase = 3
+        }
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormResolveConflicts.cs:108]:
```suggestion
        private enum ConflictResolutionPreference
        {
            None = 0,
            KeepLocal = 1,
            KeepRemote = 2,
            KeepBase = 3
        }
```

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 7]
```diff
@@ -874,38 +894,115 @@ private void ChooseRemoteOnConflict(string fileName)
...
+
+            return dialog;
+        }
+
+        private void OpenSolveMergeConflictDialogAndExecuteSelectedMergeAction(SolveMergeConflictCheckRevisionDelegate selectedMergeAction,
+            string dialogText, string dialogInstructionText, string dialogCaption, string dialogFooterCheckboxText,
+            string keepLocalButtonText, string keepRemoteButtonText, string keepBaseButtonText)
+        {
+            bool shouldOpenDialog = _SolveMergeConflictApplyToAll == false;
+            if (shouldOpenDialog)
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormResolveConflicts.cs:950]: Non nullable bools don't need this notation. The same applies below to other bool operations.

The temp variable is not required:
```suggestion
            if (!_solveMergeConflictApplyToAll)
```

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 8]
```diff
@@ -874,38 +894,115 @@ private void ChooseRemoteOnConflict(string fileName)
...
+
+            selectedMergeAction(_solveMergeConflictDialogResult);
+        }
 
-                if (frm.KeepRemote)
+        private void BinaryFilesChooseLocalBaseRemote(ConflictData item)
+        {
+            SolveMergeConflictCheckRevisionDelegate executeAction = (dialogResult) =>
+            {
+                switch (dialogResult)
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormResolveConflicts.cs:967]: Use pattern matching, it will make the code denser and easier to read

**Comment by RussKie** [comment]
> **Multiple files are selected**
> 
> SolveMergeConflict_TaskDialog_MultipleFilesSelected
> 

This is totally non obvious, and instead of 3 it should say 5. Or the text has to clearly explain why it is 3.

**Comment by RussKie** [comment]
Thank you for the screenshots 🚀

File: GitUI/CommandsDialogs/FormResolveConflicts.cs (hunk 8 above)
Comment (racecrew) [reply GitUI/CommandsDialogs/FormResolveConflicts.cs]: Honestly speaking, I am not sure what you are meaning with that. I did change the code, maybe the change is somehow already there ;-) Please take a look, thank you!

**Comment by racecrew** [comment]
> > **Multiple files are selected**
> > SolveMergeConflict_TaskDialog_MultipleFilesSelected
> 
> This is totally non obvious, and instead of 3 it should say 5. ~Or the text has to clearly explain why it is 3.~
> 
> [EDIT] Apparently I didn't read the top text :) But the fact that the selection contains 5 entries and the bottom checkbox has 3 is head-spinning...
> I think it should say something like "Apply to all selected". I know it kind of goes back to the original wording, but I didn't realise there could be grouping like the top message of the dialogs, which has numbers that may be different to selection count.

I have reworked the text messages, here are the new screenshots... I hope, this time it looks better, I did my best :-)

**Selected files of the same group, e.g. "deleted locally and modified remotely"**

1_SelectedFilesOfSameGroup

**Selected files of the different groups, e.g. "deleted locally and modified remotely" and vice versa"**

2_SelectedFilesOfDifferentGroups_DeletedLocaly

3_SelectedFilesOfDifferentGroups_DeletedRemotely

**Comment by racecrew** [comment]
In addition, if the user doesn't use the "apply" checkbox, the counter of the files is decremented, e.g.

1_SelectedFilesOfSameGroup

After an action the checkbox text will change:
- Apply to f1.txt and 2 other file(s)
- Apply to f2.txt and 1 other file(s)
- Checkbox will be hidden because one file will be left

**Comment by RussKie** [comment]
Thank you.

I'm still struggling with visual disconnect between selections and words... But the whole conflict resolution subject is head spinning :)
So I suppose this may work (with few more tweaks, please read on).




> **Selected files of the different groups, e.g. "deleted locally and modified remotely" and vice versa"**
> 
> 2_SelectedFilesOfDifferentGroups_DeletedLocaly

I personally think the bolded text in "_f4.txt and 2 other **of 5** selected files..._" in unnecessary.

So what happens to other 3 files if a user checks the box and proceeds to deleting? The message doesn't specify this, so if I were the user I'd probably cancel and then selected files invidiually.

> In addition, if the user doesn't use the "apply" checkbox, the counter of the files is decremente

👍

**Comment by racecrew** [comment]
> Thank you.
> 
> I'm still struggling with visual disconnect between selections and words... But the whole conflict resolution subject is head spinning :)
> So I suppose this may work (with few more tweaks, please read on).
> 
> > **Selected files of the different groups, e.g. "deleted locally and modified remotely" and vice versa"**
> > 2_SelectedFilesOfDifferentGroups_DeletedLocaly
> 
> I personally think the bolded text in "_f4.txt and 2 other **of 5** selected files..._" in unnecessary.
> 
> So what happens to other 3 files if a user checks the box and proceeds to deleting? The message doesn't specify this, so if I were the user I'd probably cancel and then selected files invidiually.
> 
> > In addition, if the user doesn't use the "apply" checkbox, the counter of the files is decremente
> 
> 👍

The other 3 files are belonging to "other group", in this case they are _deleted remotely and modified locally_. So, after the user applied the same action to f1.txt and f3.txt, the task dialog will appear again with the msg _"f4.txt and 2 other of 5 selected..."_

So, the Task Dialog will prompt for each of such groups.... 

You are right, the whole topic is not easy to handle :-)

**Comment by racecrew** [comment]
> The message doesn't specify this, so if I were the user I'd probably cancel and then selected files invidiually.

The user can do this, it would be nothing wrong, but if the user would check the box, then a task dialog will prompt for the new group of selected items.

**Review by gerhardol — COMMENTED** [review]
Seem OK, only browsed the code
Wordings seem sensible to me (I would use "out of" instead of just "of".

The resolution form need to associate the "user branch" and possibly "target" branch with local/remote, ours/theirs, but that is a separate task (not so easy as it seems).

**Comment by RussKie** [comment]
> Seem OK, only browsed the code
> Wordings seem sensible to me (I would use "out of" instead of just "of".

Alright, let's fix the wording and take it.

Please resolve the MC as well. Thanks

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 9]
```diff
@@ -1053,16 +1224,75 @@ private void OpenMergeTool()
...
+                            filesModifiedLocallyAndDeletedRemotely.Add(conflictData);
+                        }
+                        else
+                        {
+                            filesRemained.Add(conflictData);
+                        }
+                    }
+
+                    // This is needed the task dialog shows the same order of files as selected in the grid
+                    filesDeletedLocallyAndModifiedRemotely.Reverse();
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormResolveConflicts.cs:1249]: This isn't perf optimal - we create a list, add items and the reverse. Why not just add items in the order we need?
I.e. 
```cs
List<ConflictData> filesDeletedLocallyAndModifiedRemotely = new List<ConflictData>();
foreach (var conflictData in items)
{
    filesDeletedLocallyAndModifiedRemotely.Insert(0, conflictData);
}
```

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 10]
```diff
@@ -1007,41 +1148,71 @@ private bool CheckForRemoteRevision(ConflictData item)
...
-                    ChooseLocalOnConflict(item.Filename);
+                    dialogText = string.Format(_filesModifiedLocallyAndDeletedRemotelyLong.Text, item.Filename, _filesModifiedLocallyAndDeletedRemotelySolved - 1, _conflictItemsCount);
                 }
+            }
+
+            string dialogInstruction = string.Empty;
+            string dialogCaption = _solveMergeConflictDialogCaption.Text;
+            string dialogFooterCheckboxText = (_filesModifiedLocallyAndDeletedRemotelySolved > 1) ? string.Format(_solveMergeConflictApplyToAllCheckBoxText.Text, item.Filename, _filesModifiedLocallyAndDeletedRemotelySolved - 1) : string.Empty;
+
+            string keepLocalButtonText = string.Format(_keepModifiedButtonText.Text + " ({0})", GetLocalSideString());
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormResolveConflicts.cs:1177]: This (and similar) is done in a number of places for seemingly no good reason - we're creating many unnecessary string objects.
```suggestion
            string keepLocalButtonText = string.Concat(_keepModifiedButtonText.Text, $" (GetLocalSideString())");
```

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 11]
```diff
@@ -94,6 +101,25 @@ public partial class FormResolveConflicts : GitModuleForm
...
 
         private readonly IFullPathResolver _fullPathResolver;
+        private enum ConflictResolutionPreference
+        {
+            None = 0,
+            KeepLocal = 1,
+            KeepRemote = 2,
+            KeepBase = 3
+        }
+
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormResolveConflicts.cs:111]:
```suggestion
        private enum ConflictResolutionPreference
        {
            None = 0,
            KeepLocal = 1,
            KeepRemote = 2,
            KeepBase = 3
        }
        
        private readonly IFullPathResolver _fullPathResolver;
```

File: GitUI/CommandsDialogs/FormResolveConflicts.cs (hunk 10 above)
Comment (racecrew) [reply GitUI/CommandsDialogs/FormResolveConflicts.cs:1177]: Okay, I will remove local string objects and pass the values directly as arguments

**Comment by gerhardol** [comment]
Merge is evil...
I rebased your changes and squashed: https://github.com/gerhardol/gitextensions/tree/feature/ApplyActionToAllSelectedFilesInSolveMergeConflict

You can either just rebase interactively on master, change all but the first pick to s (squash) and merge the commit message
Or just reset hard to my commit

**Review by gerhardol — COMMENTED** [review]
Briefly reviewed, has not run
Seem OK to me
(@RussKie will never believe that I give a lot of comments at work reviews!)

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 12]
```diff
@@ -1053,16 +1184,72 @@ private void OpenMergeTool()
...
+                    // An empty string as a value of FooterCheckBox in TaskDialog hides the checkbox
+                    _solveMergeConflictApplyToAll = false;
+                    _solveMergeConflictLastAction = ConflictResolutionPreference.None;
+                    foreach (var conflictData in filesDeletedLocallyAndModifiedRemotely)
+                    {
+                        IncrementProgressBarValue();
+                        ResolveItemConflict(conflictData);
+                    }
+
+                    // For the remained files it should be asked for each file separately which one should be taken
```
[the remark this answers is not in the document]
Comment (racecrew) [reply GitUI/CommandsDialogs/FormResolveConflicts.cs:1229]: It means, for each file the task dialog asks user what to do

File: GitUI/CommandsDialogs/FormResolveConflicts.cs [hunk 13]
```diff
@@ -1053,16 +1184,72 @@ private void OpenMergeTool()
                 try
                 {
                     var items = GetConflicts();
+                    _conflictItemsCount = items.Count;
+
+                    List<ConflictData> filesDeletedLocallyAndModifiedRemotely = new List<ConflictData>();
+                    List<ConflictData> filesModifiedLocallyAndDeletedRemotely = new List<ConflictData>();
+                    List<ConflictData> filesRemained = new List<ConflictData>();
```
[the remark this answers is not in the document]
Comment (racecrew) [reply GitUI/CommandsDialogs/FormResolveConflicts.cs:1191]: Okay, thanks!

**Comment by racecrew** [comment]
How do I resolve the conflict in **contributors.txt**?!

**Comment by RussKie** [comment]
> How do I resolve the conflict in **contributors.txt**?!

Rebase :)

**Comment by RussKie** [comment]
> will never believe that I give a lot of comments at work reviews!

Hahahah! Don't tell me you ask for tests at work too.

**Comment by racecrew** [comment]
> > How do I resolve the conflict in **contributors.txt**?!
> 
> Rebase :)

Again?! :-O

**Comment by RussKie** [comment]
As a developer one constantly fetches and rebases...
Only the first few times rebase feels difficult, then it becomes almost
mechanical.

**Comment by gerhardol** [comment]
There is a reason why contributors.txt should be a separate pr...

OT: I prefer fast forward merges, not rewriting commits at merges. This is especially _needed_ to work with sub modules But github has no support for ff-only.

**Comment by gerhardol** [comment]
Dont merge, rebase...

**Comment by racecrew** [comment]
> Dont merge, rebase...

I am struggling here.... I have merged, fetched, sqaushed into one commit.. still getting the conflict... :-(

Meanwhile I know that I should rebase

**Comment by racecrew** [comment]
Yeahaaa!! Finally! Thank you guys for your help!!

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you
