### PR TITLE
Fix #7077: Hide push checkbox cells when there's no local branches

### LINKED ISSUE #7077: Push to multiple branches, deletes remote branch as well
## Current behaviour

Pushing to multiple branch, without selecting "Delete Remote Branch" **IS DELETING** remote branch

## Expected behaviour

Pushing to multiple branch, without selecting "Delete Remote Branch" **SHOULD NOT DELETE** any remote branch

## Steps to reproduce

Simply push to multiple branches, without selecting "Delete Remote Branch" and say bye bye to remote branch

## Screenshots

image

## Did this work in previous version of GitExtensions

I'm not sure because I recently started using this functionality

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by hieuxlu**
Fixes #7077

## Proposed changes

- Hide push checkbox cells when there's no local branches

### Before

image

### After

image

## Test methodology 

- Manual test

## Test environment(s) 

- Git Extensions 3.3.0
- Build 81fe6435db607ed42c197390d34e085f3f658e33
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4018.0
- DPI 144dpi (150% scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormPush.cs [hunk 1]
```diff
@@ -977,6 +977,9 @@ void ProcessHeads(IReadOnlyList<IGitRef> remoteHeads)
                 var localHeads = GetLocalBranches().ToList();
                 var remoteBranches = remoteHeads.ToHashSet(h => h.LocalName);
 
+                // Fix #7077: Optimize data loading notifications
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormPush.cs]: This is redundant, this can be tracked via git history. Please remove.

Applies universally.

Comment (hieuxlu) [reply GitUI/CommandsDialogs/FormPush.cs]: Done

**Comment by RussKie** [comment]
Thank you
