### PR TITLE
should fix: [NBug] Sequence contains no elements #7011

### LINKED ISSUE #7011: [NBug] Sequence contains no elements
## Current behaviour

Git Extension process crash and show a popup window of bug reporting instead of compare to menu

## Expected behaviour

No process crash and ability to compare a commit with a branch

## Steps to reproduce
Click to select a commit row
Ctrl+Click to unselect the commit
Right click on that commit row
Go to Compare sub menu, then click on "Compare To branch..."

## Error Details
```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GitUI.RevisionGridControl.CompareToBranchToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information

Looking at the code the exception is on that line and cause because there is no selected commit
https://github.com/gitextensions/gitextensions/blob/ddce80631f19c41662fef4632b6d0aa22a8cddde/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs#L2365

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by manuc66**
Fixes #7011 

## Proposed changes

- When right clicking on a row that has been removed from selection force the row to be selected

## Test methodology 

- 
- 
- 

## Test environment(s) 

- GIT 
- Windows 

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by manuc66** [comment]
@RussKie The real problem is that the line was not selected, the fix should be better now as it should fix the root cause

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 1]
```diff
@@ -1344,7 +1344,7 @@ private void OnGridViewCellMouseDown(object sender, DataGridViewCellMouseEventAr
             var pt = _gridView.PointToClient(Cursor.Position);
             var hti = _gridView.HitTest(pt.X, pt.Y);
 
-            if (_latestSelectedRowIndex == hti.RowIndex)
+            if (_latestSelectedRowIndex == hti.RowIndex && _gridView.Rows[_latestSelectedRowIndex].Selected)
```
Comment (gerhardol) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs]: This is basically "handle rightclick as selecting the revision". 
That the Selected property deviates from _latestSelectedRowIndexis an error that should be handled. Maybe this is sufficient.

This should be fine, but I cannot see that _gridView.Rows[_latestSelectedRowIndex] may not give null exceptions, so that should be checked.

However, it is not a guarantee that _latestSelectedRowIndex is still correct. There may have to be a check in CompareToBranchToolStripMenuItem_Click() and/or in OnGridViewSelectionChanged() or ContextMenuOpening().

Comment (manuc66) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs]: `_gridView.Rows[_latestSelectedRowIndex]` is de-referenced on line 1357 with a guard `IsValidRevisionIndex(_latestSelectedRowIndex)` but I wouldn't imagine that  `_latestSelectedRowIndex == hti.RowIndex` beeing true and not `_latestSelectedRowIndex >= 0 && _latestSelectedRowIndex < _gridView.RowCount` since `_latestSelectedRowIndex ` is equal to ` hti.RowIndex` which basicaly is an existing row (it has been clicked). Do you think I really should check for null or `IsValidRevisionIndex` ?

Comment (manuc66) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs]: With this fix I was not able to open the conext menu without having a row selected. I think that context menu scenarios are fixed.

But action exposed by the context menu can also be triggered whit hot keys when there is no selection in the grid. If I hit `CTRL+D` (Which is Campare to working directory) without a section the app keep crashing ! => In this case what should be the expected behavior ?

Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs]: No exception with hot keys - a null check is needed.

**Comment by RussKie** [comment]
> I would have preferred to separate git-fetch and git-pull actions, but I can live with this.

I don't think you've meant it for this PR :)

File: GitUI/CommandsDialogs/RevisionFileTreeControl.cs [hunk 2]
```diff
@@ -287,7 +287,7 @@ protected override void OnRuntimeLoad()
 
         private IEnumerable<string> FindFileMatches(string name)
         {
-            var candidates = Module.GetFullTree(_revision.TreeGuid.ToString());
+            var candidates = _revision == null ? Enumerable.Empty<string>() : Module.GetFullTree(_revision.TreeGuid.ToString());
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionFileTreeControl.cs]:
```suggestion
            var candidates = _revision == null ? Array.Empty<string>() : Module.GetFullTree(_revision.TreeGuid.ToString());
```
`Array.Empty<T>` is a singleton, whilst `Enumerable.Empty<T>` is not.
In .NET Core it was fixed, but I don't believe it was fixed in .NET Fx.

I think the type inference should work, if not the following should work:
```suggestion
            IEnumerable<string> candidates = _revision == null ? Array.Empty<string>() : Module.GetFullTree(_revision.TreeGuid.ToString());
```

Comment (manuc66) [reply GitUI/CommandsDialogs/RevisionFileTreeControl.cs]: It seems fixed in framework 4.8, see : https://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,1284 or in 4.6.1: https://github.com/microsoft/referencesource/blob/4.6.2/System.Core/System/Linq/Enumerable.cs#L1161

Comment (RussKie) [reply GitUI/CommandsDialogs/RevisionFileTreeControl.cs]: The link is pointing to 4.6.2, not 4.6.1

**Comment by manuc66** [comment]
@RussKie squash done

**Comment by gerhardol** [comment]
> I don't think you've meant it for this PR :)

At least, I meant to approve this PR

**Comment by RussKie** [comment]
Thank you
