### PR TITLE
Fix a crash after clicking on "Browse..."

### LINKED ISSUE #3817: [Bug] Exception when opening click on "Browse..."
**Do you want to request a *feature* or report a *bug*?**
This bug is related to the "Browse..." button action, called inside the "Open local Repository" dialog, only when the repository history is empty.

**What is the current behavior?**
ArgumentException

**STACKTRACE**
```
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at System.IO.DirectoryInfo..ctor(String path)
   at GitUI.CommandsDialogs.BrowseDialog.FormOpenDirectory._NO_TRANSLATE_Directory_TextChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.OnTextChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.NotifyAutoComplete(Boolean setSelectedIndex)
   at System.Windows.Forms.ComboBox.OnValidating(CancelEventArgs e)
   at System.Windows.Forms.Control.NotifyValidating()
   at System.Windows.Forms.Control.PerformControlValidation(Boolean bulkValidation)
   at System.Windows.Forms.ContainerControl.ValidateThroughAncestor(Control ancestorControl, Boolean preventFocusChangeOnError)
   at System.Windows.Forms.ContainerControl.EnterValidation(Control enterControl)
   at System.Windows.Forms.ContainerControl.UpdateFocusedControl()
   at System.Windows.Forms.ContainerControl.AssignActiveControlInternal(Control value)
   at System.Windows.Forms.ContainerControl.ActivateControlInternal(Control control, Boolean originator)
   at System.Windows.Forms.ContainerControl.ActivateControlInternal(Control control, Boolean originator)
   at System.Windows.Forms.ContainerControl.ActivateControlInternal(Control control)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
image

image

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Clear "Recent Repository" list
2. Go to "Dashboard"
3. Click on "Open Repository", "Open local repository" dialog appears having a clean "Directory" combobox
4. Click on "Browse...", it crashes

**What is the expected behavior?**
Opens the Folder Selection dialog to open a repository.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
- GitExtension 2.50
- Git 2.13.2.windows.1
- Windows 7

### PR DESCRIPTION
**Pull request by gpongelli**
Having a clean repository history, when trying to Browse a local git repository, GitExtension will crash if "directories" list is empty.
This fix will add two directory (recent working dir and git home dir) to the list to avoid the crash.

Fixes #3817  .

Changes proposed in this pull request:
 - add two directory to avoid using an empty list
 

How did I test this code:
 - repeat the steps inside the issue, it will not crash

### CODE REVIEW

File: GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs [hunk 1]
```diff
@@ -52,6 +52,19 @@ private IList<string> GetDirectories(GitModule currentModule)
...
+            if (directories.Count == 0)
+            {
+                if (AppSettings.RecentWorkingDir.IsNotNullOrWhitespace())
+                {
+                    directories.Add(PathUtil.EnsureTrailingPathSeparator(AppSettings.RecentWorkingDir));
+                }
+
+                if (GitCommandHelpers.GetHomeDir().IsNotNullOrWhitespace())
+                {
+                    directories.Add(PathUtil.EnsureTrailingPathSeparator(GitCommandHelpers.GetHomeDir()));
```
Comment (RussKie) [inline GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs]: `GitCommandHelpers.GetHomeDir()` executed twice, please use an intermediary variable

File: GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs [hunk 2]
```diff
@@ -107,8 +120,14 @@ private void folderGoUpbutton_Click(object sender, EventArgs e)
 
         private void _NO_TRANSLATE_Directory_TextChanged(object sender, EventArgs e)
         {
-            DirectoryInfo currentDirectory = new DirectoryInfo(_NO_TRANSLATE_Directory.Text);
-            folderGoUpbutton.Enabled = (currentDirectory.Parent != null);
+            try
+            {
+                DirectoryInfo currentDirectory = new DirectoryInfo(_NO_TRANSLATE_Directory.Text);
+                folderGoUpbutton.Enabled = (currentDirectory.Parent != null);
```
Comment (RussKie) [inline GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs]: 1. redundant braces
2. you need to check whether the path provided exists and only enable the button if it is 
https://msdn.microsoft.com/en-us/library/system.io.directoryinfo.directoryinfo(v=vs.110).aspx

> This constructor does not check if a directory exists. This constructor is a placeholder for a string that is used to access the disk in subsequent operations.

File: GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs (hunk 1 above)
Comment (gpongelli) [inline GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs]: Changed.

File: GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs (hunk 2 above)
Comment (gpongelli) [inline GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs]: Here I've only moved the existing code into the try/catch because of System.ArgumentException that is raised by DirectoryInfo when `_NO_TRANSLATE_Directory.Text` is empty.
Look at the new commit.

Thank you.

File: GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs [hunk 3]
```diff
@@ -121,14 +121,13 @@ private void folderGoUpbutton_Click(object sender, EventArgs e)
 
         private void _NO_TRANSLATE_Directory_TextChanged(object sender, EventArgs e)
         {
-            try
```
Comment (jbialobr) [inline GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs]: It is better to have this try-catch block in case an user has typed any path that causes an exception being thrown by DirectoryInfo. In the catch block the folderGoUpbutton should be disabled in such a case.

**Comment by vbjay** [comment]
Keep the string check. But include the try catch.

File: GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs [hunk 4]
```diff
@@ -107,8 +121,13 @@ private void folderGoUpbutton_Click(object sender, EventArgs e)
...
         {
-            DirectoryInfo currentDirectory = new DirectoryInfo(_NO_TRANSLATE_Directory.Text);
-            folderGoUpbutton.Enabled = (currentDirectory.Parent != null);
+            if (_NO_TRANSLATE_Directory.Text.IsNotNullOrWhitespace())
+            {
+                DirectoryInfo currentDirectory = new DirectoryInfo(_NO_TRANSLATE_Directory.Text);
+                folderGoUpbutton.Enabled = currentDirectory.Parent != null;
+            }
+            else
+                folderGoUpbutton.Enabled = false;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs]: your previous version with `try...catch` was more correct, since `DirectoryInfo` can throw a number of different exceptions (https://msdn.microsoft.com/en-us/library/system.io.directoryinfo.directoryinfo(v=vs.110).aspx#Exceptions)

Perhaps something like this:

```
try 
{
    var currentDirectory = new DirectoryInfo(_NO_TRANSLATE_Directory.Text);
    folderGoUpbutton.Enabled = currentDirectory.Exists && currentDirectory.Parent != null;
}
catch
{
}

```

**Comment by RussKie** [comment]
Please squash as well

**Comment by vbjay** [comment]
In fact. Add a directory.exists check.

**Comment by jbialobr** [comment]
>In fact. Add a directory.exists check.

In the context of folderGoUpbutton it is enough to check if Parent is not null.

**Comment by vbjay** [comment]
So creating a directoryinfo with "car" won't cause an exception?

**Comment by vbjay** [comment]
Bad example. I meant invalid path characters. A simple directory.exists
check will prevent any issues.

If( !null check && directory.exists)
The parent check is good for if they picked c:\. I know it's dumb but they
could do it.

**Comment by gpongelli** [comment]
Last commit on this PR for me is the best solution
- try-catch for DirectoryInfo exception
- directory.Extists check for `folderGoUpbutton`
- `folderGoUpbutton` disabled into catch block

@RussKie squash command cannot be "added" as option [when accepting the PR (point 3)](https://help.github.com/articles/merging-a-pull-request/) ?
I can squash [forcing the push](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit), rewriting the history of this branch.

**Comment by RussKie** [comment]
Squash by force push, it is your fork - you can do whatever. 
You never force push into master, but in your fork you're the boss :)

File: GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs [hunk 5]
```diff
@@ -107,8 +121,15 @@ private void folderGoUpbutton_Click(object sender, EventArgs e)
...
         private void _NO_TRANSLATE_Directory_TextChanged(object sender, EventArgs e)
         {
-            DirectoryInfo currentDirectory = new DirectoryInfo(_NO_TRANSLATE_Directory.Text);
-            folderGoUpbutton.Enabled = (currentDirectory.Parent != null);
+            try
+            {
+                DirectoryInfo currentDirectory = new DirectoryInfo(_NO_TRANSLATE_Directory.Text);
+                folderGoUpbutton.Enabled = currentDirectory.Exists && currentDirectory.Parent != null;
+            }
+            catch (Exception)
```
Comment (RussKie) [inline GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs]: there's no real need for `(Exception)`

File: GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs (hunk 3 above)
Comment (gpongelli) [inline GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs]: Restored the try-catch clause and disabled the folderGoUpbutton into catch block.
Thanks.

**Comment by gpongelli** [comment]
@RussKie Commit squashed.
