### PR TITLE
Fix hang when requesting submodule status

### LINKED ISSUE #8914: GE hangs when viewing submodules in diff viewer
## Current behaviour

Regression in master in the last days. 

If a submodule is selected in worktree (at least - seem OK for HEAD though), GE hangs and stops responding. Status is never changed from the default. Mouse just spinning.

## Expected behaviour

Submodule is displayed.

## Steps to reproduce

Select modified submodule in worktree in the diff viewer.

## Screenshots

image

## Did this work in previous version of GitExtensions

- Git Extensions 3.6.0.11114
- Build f54a727a95393dcacfbbd8603dfd6daf931618c4 (Dirty)

## Environment

- Git Extensions 3.6.0.11170
- Build 273a0f6fd3e07858f837cdc19d50827871e32319 (Dirty)
- Git 2.30.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by drewnoakes**
- Fixes #8914 so that the application doesn't hang when submodule results have not completed at the time they're requested.
- Makes the UI responsive while the submodule operation is underway.
- Discards some unawaited tasks, as these triggered compiler diagnostics after making the above changes (unsure why).

This required making methods `GitModule.GetSingleDiff` and `SubmoduleHelpers.GetCurrentSubmoduleChanges` async.

## Test methodology

- Manual testing

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — COMMENTED** [review]
Looks sensible from ☎️

**Review by gerhardol — APPROVED** [review]
More or less what I expected, just done much faster than if I would have done it.
No hangup when introducing delays.

**Comment by gerhardol** [comment]
Assert_default_filter_related_settings() test failed, timeout after 90s (I believe that is the default).
Works locally, but requires about 30s
The test seem so be unrelated to the change

File: GitUI/GitUIExtensions.cs [hunk 1]
```diff
@@ -112,24 +123,26 @@ void OpenWithDiffTool()
                         : diffOfConflict;
                 }
 
-                if (file.IsSubmodule
-                    && file.GetSubmoduleStatusAsync() is Task<GitSubmoduleStatus> task)
+                var task = file.GetSubmoduleStatusAsync();
```
Comment (mstv) [inline GitUI/GitUIExtensions.cs:126]: Newbie question: Does this really nothing yet if it is not a submodule?

File: GitUI/GitUIExtensions.cs [hunk 2]
```diff
@@ -112,24 +123,26 @@ void OpenWithDiffTool()
...
+
+                if (file.IsSubmodule && task != null)
```
Comment (mstv) [inline GitUI/GitUIExtensions.cs:128]:
```suggestion
                if (file.IsSubmodule && task is not null)
```

**Review by mstv — COMMENTED** [review]
The same test has failed in a rerun.

(Both with and without this PR, I have noticed local hangs of the test `RunScript_with_arguments_with_s_option_with_RevisionGrid_with_selection_shall_succeed`, which passes when run by AppVeyor.)

File: GitUI/GitUIExtensions.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/GitUIExtensions.cs:126]: The task is only set if this is a submodule, so the first check is not technically needed (I prefer it though)

**Comment by RussKie** [comment]
Looks like this change causes tests instability.

File: GitUI/GitUIExtensions.cs (hunk 2 above)
Comment (drewnoakes) [reply GitUI/GitUIExtensions.cs]: I wish there was an analyzer to enforce this.

File: GitUI/GitUIExtensions.cs (hunk 1 above)
Comment (drewnoakes) [reply GitUI/GitUIExtensions.cs:126]: There is an opportunity to improve this code pattern to make it clearer. It is a bit confusing as it stands.

**Comment by gerhardol** [comment]
A drawback with this PR is that if the Git command takes long time (like git-range-diff with many commits), the command will update the fileviewer if you select another file before the current command is done.
A 5s artificial delay was added here. (The command is cached too)

Cancellation is needed somehow - maybe not now, this is probably better

submod-async

**Comment by RussKie** [comment]
@gerhardol merge if you're happy with it

**Comment by gerhardol** [comment]
> @gerhardol merge if you're happy with it

I am much happier with this than the hanging in master (not 3.5) that is unusable for me.
The cancelation issue is a nuance that very few users will ever see (since we cache they will basically only see it once...)

The only open I have is:
Can we consider the build issues as resolved as it is not exclusively this PR at least?

**Comment by gerhardol** [comment]
Test instability could have been fixed with #8949 
@drewnoakes  can you please rebase and merge?

File: GitUI/GitUIExtensions.cs [hunk 3]
```diff
@@ -77,15 +80,23 @@ public static class GitUIExtensions
...
-                return fileViewer.ViewRangeDiffAsync(filename, output ?? defaultText);
+                await fileViewer.ViewRangeDiffAsync(filename, output ?? defaultText);
+                return;
             }
 
-            string selectedPatch = GetSelectedPatch(fileViewer, firstId, item.SecondRevision.ObjectId, item.Item)
+            string selectedPatch = (await GetSelectedPatchAsync(fileViewer, firstId, item.SecondRevision.ObjectId, item.Item))
                 ?? defaultText;
 
-            return item.Item.IsSubmodule
```
Comment (gerhardol) [inline GitUI/GitUIExtensions.cs:86]: (I still prefer ?: before)

File: GitUI/GitUIExtensions.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/GitUIExtensions.cs:129]: regression...

**Review by gerhardol — APPROVED** [review]
One 'is not' regression

**Comment by drewnoakes** [comment]
@gerhardol

> Test instability could have been fixed with #8949
> @drewnoakes can you please rebase and merge?

Great, thanks for letting me know. I've rebased and pushed. Hoping it passes.

> A drawback with this PR is that if the Git command takes long time (like git-range-diff with many commits), the command will update the fileviewer if you select another file before the current command is done.
> A 5s artificial delay was added here. (The command is cached too)
> 
> Cancellation is needed somehow - maybe not now, this is probably better

Interesting. Looking at `FileViewer` it seems there is an `AsyncLoader` for this purpose but it is not used consistently.

I've filed https://github.com/gitextensions/gitextensions/issues/8997 to track improving cancellation of loading within `FileViewer` across all its various load methods.

**Comment by drewnoakes** [comment]
>> Test instability could have been fixed with #8949
>>@drewnoakes can you please rebase and merge?
>
>Great, thanks for letting me know. I've rebased and pushed. Hoping it passes.

Unfortunately the test still fails. I'll try and find some time to look into it later in the week. I'm getting busy at work again.

**Comment by gerhardol** [comment]
Timeout in `Should_handle_well_commit_message_in_commit_message_menu`
If this PR is not making the timeouts worse, it should be merged before the timeout issue is found.
This is still a blocker in master...

**Comment by drewnoakes** [comment]
@gerhardol so long as merging this won't start failing all other builds, I'm ok with merging as is until we revisit this.

**Comment by gerhardol** [comment]
Different failure now: SaveRecentHistoryAsync_should_trim_history_size
Rebuilding again

So the status is still unknown, I cannot say it is likely that this is not adding test instability.

I would like to push a follow-up commit to this PR though

**Comment by mstv** [comment]
A re-triggered CI build has succeeded.

**Comment by gerhardol** [comment]
> A re-triggered CI build has succeeded.

and another I did. A few previous builds have succeeded too.
But since previous failures has been for this PR only, it is hard to say that the problem was due to the environment.

Functionality considered, this is an improvement. Viewing a file no longer locks the UI.
I have been using this patch for some time, works fine.

**Comment by mstv** [comment]
Works well for me.

**Comment by gerhardol** [comment]
@drewnoakes How to continue here?
Builds occasionally fail but the functionality is fine. This will need a follow up to handle a cancel token to avoid the problems when quickly switching selection.

If not, I will submit the fix for submodule status

**Comment by drewnoakes** [comment]
@gerhardol I haven't dug into what's causing the test failures here. If you feel there is a better solution, feel free to invest in it. I am quite occupied by work/life at the moment so don't know how much time I'll have for this PR. If a problem is identified, I can find time to brainstorm solutions, but the investigation is unbounded and I won't have time for it in the near term.

I do feel like more of GE's innards should be made properly async, and had hoped that the patterns in this PR could be extended, ultimately removing all synchronous process execution from the code and APIs. Adding cancellation as you suggest is a good idea.

**Comment by gerhardol** [comment]
For now, I will just submit a fix like in https://github.com/gitextensions/gitextensions/issues/8914#issuecomment-790080907
May look at updating this later

**Comment by gerhardol** [comment]
This still fails on .NET5 (with even less information).

I rebased on master and added a cancelToken for ViewChangesAsync(), same problem.
Cancel only implemented for getting diffs in ViewChangesAsync(), not for FileViewer operations that most often is quite fast.

The tests need to be debugged
https://ci.appveyor.com/project/gerhardol/gitextensions/builds/39271723

**Comment by gerhardol** [comment]
Logged in to AppVeyor to find the exception popup - can we get rid of them somehow?

I pushed a change to fix this in TextEditor subrepo, but that is really a fix to see if there are not other issues (tests succeed now).
Will open a WIP PR for this.

System.NullReferenceException: Object reference not set to an instance of an object.
   at int ICSharpCode.TextEditor.TextView.get_FirstVisibleLine() in C:/projects/gitextensions/Externals/ICSharpCode.TextEditor/Project/Src/Gui/TextView.cs:line 41
   at int GitUI.Editor.FileViewerInternal.get_FirstVisibleLine() in C:/projects/gitextensions/GitUI/Editor/FileViewerInternal.cs:line 434
   at void GitUI.Editor.FileViewerInternal+CurrentViewPositionCache.Capture() in C:/projects/gitextensions/GitUI/Editor/FileViewerInternal.cs:line 601
   at void GitUI.Editor.FileViewerInternal.SetText(string text, Action openWithDifftool, bool isDiff, bool isRangeDiff) in C:/projects/gitextensions/GitUI/Editor/FileViewerInternal.cs:line 240
   at Task GitUI.Editor.FileViewer.ViewPrivateAsync(FileStatusItem item, string fileName, string text, Action openWithDifftool, ViewMode viewMode)+() => { } in C:/projects/gitextensions/GitUI/Editor/FileViewer.cs:line 729
   at Task GitUI.Editor.FileViewer.ShowOrDeferAsync(long contentLength, Func<Task> showFunc) in C:/projects/gitextensions/GitUI/Editor/FileViewer.cs:line 886
   at Task GitUI.Editor.FileViewer.ViewPrivateAsync(FileStatusItem item, string fileName, string text, Action openWithDifftool, ViewMode viewMode) in C:/projects/gitextensions/GitUI/Editor/FileViewer.cs:line 724
   at Task GitUI.Editor.FileViewer.ViewPatchAsync(FileStatusItem item, string text, Action openWithDifftool) in C:/projects/gitextensions/GitUI/Editor/FileViewer.cs:line 409
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, string defaultText, Action openWithDiffTool) in C:/projects/gitextensions/GitUI/GitUIExtensions.cs:line 104
   at void GitUI.CommandsDialogs.FormCommit+<>c__DisplayClass131_0+<<ShowChanges>b__0>d.MoveNext() in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCommit.cs:line 1144
   at void GitUI.ThreadHelper+<>c__DisplayClass13_0+<<FileAndForget>b__0>d.MoveNext() in C:/projects/gitextensions/GitExtUtils/GitUI/ThreadHelper.cs:line 112

System.NullReferenceException: Object reference not set to an instance of an object.
   at void ICSharpCode.TextEditor.TextArea.SearchMatchingBracket(object sender, EventArgs e) in C:/projects/gitextensions/Externals/ICSharpCode.TextEditor/Project/Src/Gui/TextArea.cs:line 211
   at void ICSharpCode.TextEditor.TextArea.OptionsChanged() in C:/projects/gitextensions/Externals/ICSharpCode.TextEditor/Project/Src/Gui/TextArea.cs:line 244
   at void ICSharpCode.TextEditor.TextAreaControl.OptionsChanged() in C:/projects/gitextensions/Externals/ICSharpCode.TextEditor/Project/Src/Gui/TextAreaControl.cs:line 341
   at void ICSharpCode.TextEditor.TextEditorControl.OptionsChanged() in C:/projects/gitextensions/Externals/ICSharpCode.TextEditor/Project/Src/Gui/TextEditorControl.cs:line 97
   at void ICSharpCode.TextEditor.TextEditorControlBase.set_ShowLineNumbers(bool value) in C:/projects/gitextensions/Externals/ICSharpCode.TextEditor/Project/Src/Gui/TextEditorControlBase.cs:line 571
   at void GitUI.Editor.FileViewerInternal.SetText(string text, Action openWithDifftool, bool isDiff, bool isRangeDiff) in C:/projects/gitextensions/GitUI/Editor/FileViewerInternal.cs:line 270
   at Task GitUI.Editor.FileViewer.ViewPrivateAsync(FileStatusItem item, string fileName, string text, Action openWithDifftool, ViewMode viewMode)+() => { } in C:/projects/gitextensions/GitUI/Editor/FileViewer.cs:line 729
   at Task GitUI.Editor.FileViewer.ShowOrDeferAsync(long contentLength, Func<Task> showFunc) in C:/projects/gitextensions/GitUI/Editor/FileViewer.cs:line 886
   at Task GitUI.Editor.FileViewer.ViewPrivateAsync(FileStatusItem item, string fileName, string text, Action openWithDifftool, ViewMode viewMode) in C:/projects/gitextensions/GitUI/Editor/FileViewer.cs:line 724
   at Task GitUI.Editor.FileViewer.ViewPatchAsync(FileStatusItem item, string text, Action openWithDifftool) in C:/projects/gitextensions/GitUI/Editor/FileViewer.cs:line 409
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, string defaultText, Action openWithDiffTool) in C:/projects/gitextensions/GitUI/GitUIExtensions.cs:line 104
   at void GitUI.CommandsDialogs.FormCommit+<>c__DisplayClass131_0+<<ShowChanges>b__0>d.MoveNext() in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCommit.cs:line 1144
   at void GitUI.ThreadHelper+<>c__DisplayClass13_0+<<FileAndForget>b__0>d.MoveNext() in C:/projects/gitextensions/GitExtUtils/GitUI/ThreadHelper.cs:line 112

**Comment by RussKie** [comment]
> Logged in to AppVeyor to find the exception popup - can we get rid of them somehow?

Did you happen to take a screenshot?

**Comment by gerhardol** [comment]
> > Logged in to AppVeyor to find the exception popup - can we get rid of them somehow?
> 
> Did you happen to take a screenshot?

image

**Comment by gerhardol** [comment]
Updated the failing test (turned out to be similar ti #9205).
Rebased and pushed to @drewnoakes clone

Also fixing https://github.com/gitextensions/gitextensions/pull/8923#issuecomment-797137950
The cancellation is only in GitUIExtentions. It could be trickled down to FileViewer too, but those operations are normally much quicker so not much effect.
A few other changes

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 4]
```diff
@@ -164,6 +164,7 @@ public sealed partial class FormCommit : GitModuleForm
         private readonly AsyncLoader _unstagedLoader = new();
         private readonly bool _useFormCommitMessage = AppSettings.UseFormCommitMessage;
         private readonly CancellationTokenSequence _interactiveAddSequence = new();
+        private readonly CancellationTokenSequence _viewChangesSequence = new();
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormCommit.cs:167]: Should be disposed explicitly.

File: GitUI/CommandsDialogs/FormFileHistory.cs [hunk 5]
```diff
@@ -31,6 +31,7 @@ public sealed partial class FormFileHistory : GitModuleForm
         private readonly FormBrowseMenus _formBrowseMenus;
         private readonly IFullPathResolver _fullPathResolver;
         private readonly FormFileHistoryController _controller = new();
+        private readonly CancellationTokenSequence _viewChangesSequence = new();
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormFileHistory.cs:34]: ditto

File: GitUI/CommandsDialogs/FormLog.cs [hunk 6]
```diff
@@ -4,6 +4,8 @@ namespace GitUI.CommandsDialogs
 {
     public partial class FormLog : GitModuleForm
     {
+        private readonly CancellationTokenSequence _viewChangesSequence = new();
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormLog.cs:7]: ditto

File: GitUI/CommandsDialogs/FormStash.cs [hunk 7]
```diff
@@ -24,6 +24,7 @@ public sealed partial class FormStash : GitModuleForm
         private readonly TranslationString _areYouSure = new("Are you sure you want to drop the stash? This action cannot be undone.");
         private readonly TranslationString _dontShowAgain = new("Don't show me this message again.");
 
+        private readonly CancellationTokenSequence _viewChangesSequence = new();
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormStash.cs:27]: ditto

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 8]
```diff
@@ -43,6 +43,7 @@ public partial class RevisionDiffControl : GitModuleControl
         private readonly IFullPathResolver _fullPathResolver;
         private readonly IFindFilePredicateProvider _findFilePredicateProvider;
         private readonly IGitRevisionTester _gitRevisionTester;
+        private readonly CancellationTokenSequence _viewChangesSequence = new();
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:46]: ditto

File: GitUI/GitUIExtensions.cs [hunk 9]
```diff
@@ -56,14 +59,19 @@ public static class GitUIExtensions
...
             if (item.Item.IsRangeDiff)
             {
-                // This command may take time, give an indication of what is going on
-                // The sha are incorrect if baseA/baseB is set, to simplify the presentation
-                fileViewer.ViewText("range-diff.sh", $"git range-diff {firstId}...{item.SecondRevision.ObjectId}");
+                // Git range-diff has cubic runtime complexity and can be slow and memory consuming,
+                // give an indication of what is going on
+                var range = item.BaseA is null || item.BaseB is null
+                ? $"{firstId}...{item.SecondRevision.ObjectId}"
+                : $"{item.BaseA}..{firstId} {item.BaseB}..{item.SecondRevision.ObjectId}";
```
Comment (mstv) [inline GitUI/GitUIExtensions.cs:72]: Indent
```suggestion
                    ? $"{firstId}...{item.SecondRevision.ObjectId}"
                    : $"{item.BaseA}..{firstId} {item.BaseB}..{item.SecondRevision.ObjectId}";
```
?

File: GitUI/UserControls/CommitDiff.cs [hunk 10]
```diff
@@ -8,6 +8,8 @@ namespace GitUI.UserControls
 {
     public partial class CommitDiff : GitModuleControl
     {
+        private readonly CancellationTokenSequence _viewChangesSequence = new();
```
Comment (mstv) [inline GitUI/UserControls/CommitDiff.cs:11]: Should be disposed explicitly.

File: IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs [hunk 11]
```diff
@@ -214,6 +214,9 @@ public void Should_handle_well_commit_message_in_commit_message_menu()
             _referenceRepository.CreateCommit("Too long commit message that should be shorten because first line of a commit message is only 50 chars long");
             RunFormTest(form =>
             {
+                // Await updated FileViewer
+                ThreadHelper.JoinPendingOperations();
```
Comment (mstv) [inline IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs:218]: I would rather add this to the method `RunFormTest` or even to `UITest.RunForm`.

File: GitUI/Editor/FileViewer.cs [hunk 12]
```diff
@@ -406,38 +406,27 @@ public void ClearHighlighting()
...
+            => ViewPrivateAsync(item, item?.Item?.Name, text, openWithDifftool, ViewMode.Diff);
 
         /// <summary>
         /// Present the text as a patch in the file viewer, for GitHub.
         /// </summary>
         /// <param name="fileName">The fileName to present.</param>
         /// <param name="text">The patch text.</param>
         /// <param name="openWithDifftool">The action to open the difftool.</param>
+        public Task ViewFixedPatchAsync(string fileName, string text, Action? openWithDifftool = null)
+            => ViewPrivateAsync(null, fileName, text, openWithDifftool, ViewMode.FixedDiff);
```
Comment (mstv) [inline GitUI/Editor/FileViewer.cs:418]:
```suggestion
            => ViewPrivateAsync(item: null, fileName, text, openWithDifftool, ViewMode.FixedDiff);
```

File: GitUI/Editor/FileViewer.cs [hunk 13]
```diff
@@ -406,38 +406,27 @@ public void ClearHighlighting()
...
-                () => ViewPrivateAsync(fileName, text, openWithDifftool, ViewMode.FixedDiff));
+                () => ViewFixedPatchAsync(fileName, text, openWithDifftool));
         }
 
-        public Task ViewFixedPatchAsync(string fileName, string text, Action? openWithDifftool = null)
-            => ViewPrivateAsync(fileName, text, openWithDifftool, ViewMode.FixedDiff);
-
         public Task ViewRangeDiffAsync(string fileName, string text)
-            => ViewPrivateAsync(fileName, text, openWithDifftool: null, ViewMode.RangeDiff);
+            => ViewPrivateAsync(null, fileName, text, openWithDifftool: null, ViewMode.RangeDiff);
```
Comment (mstv) [inline GitUI/Editor/FileViewer.cs:429]:
```suggestion
            => ViewPrivateAsync(item: null, fileName, text, openWithDifftool: null, ViewMode.RangeDiff);
```

File: GitUI/CommandsDialogs/FormCommit.cs (hunk 4 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormCommit.cs:167]: OK

File: GitUI/CommandsDialogs/FormDiff.cs [hunk 14]
```diff
@@ -26,6 +26,7 @@ public partial class FormDiff : GitModuleForm
         private readonly IFileStatusListContextMenuController _revisionDiffContextMenuController;
         private readonly IFullPathResolver _fullPathResolver;
         private readonly IFindFilePredicateProvider _findFilePredicateProvider;
+        private readonly CancellationTokenSequence _viewChangesSequence = new();
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormDiff.cs:29]: OK

File: GitUI/CommandsDialogs/FormLog.cs (hunk 6 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormLog.cs:7]: OK

File: GitUI/CommandsDialogs/FormFileHistory.cs (hunk 5 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormFileHistory.cs:34]: OK

File: GitUI/CommandsDialogs/FormStash.cs (hunk 7 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormStash.cs:27]: OK

File: GitUI/GitUIExtensions.cs (hunk 9 above)
Comment (gerhardol) [reply GitUI/GitUIExtensions.cs:72]: I expect auto indent should handle this, disappointed every time it is not.

File: GitUI/CommandsDialogs/RevisionDiffControl.cs (hunk 8 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:46]: OK

File: GitUI/UserControls/CommitDiff.cs (hunk 10 above)
Comment (gerhardol) [reply GitUI/UserControls/CommitDiff.cs:11]: OK

File: IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs (hunk 11 above)
Comment (gerhardol) [reply IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs:218]: Trying UITest

File: GitUI/Editor/FileViewer.cs (hunk 12 above)
Comment (gerhardol) [reply GitUI/Editor/FileViewer.cs:418]: OK

File: IntegrationTests/UI.IntegrationTests/UITest.cs [hunk 15]
```diff
@@ -75,6 +75,9 @@ void HandleApplicationIdle(object sender, EventArgs e)
                 form?.Dispose();
                 Assert.IsEmpty(Application.OpenForms.OfType<T>(), $"{Application.OpenForms.OfType<T>().Count()} open form(s) after test");
             }
+
+            // Await updated async, for instance FileViewer
+            ThreadHelper.JoinPendingOperations();
```
Comment (mstv) [inline IntegrationTests/UI.IntegrationTests/UITest.cs:80]: This is too late here, should be done right after `await WaitForIdleAsync();` at line 49.
Though I should not have pointed to this function (again): https://github.com/gitextensions/gitextensions/pull/7623/files#r365334811. I was not convinced but voted down.

Comment (gerhardol) [reply IntegrationTests/UI.IntegrationTests/UITest.cs:80]: I moved it to line 50 - at least for now.

If the referred discussion is the standard, then all tests with FileViewers need to be changed.
The last failures were all the same test, but previous failures were also in a few other tests.
I rather see stable tests than a winning a few second test time here, but my vote is weak.
@RussKie has the majority vote.

Comment (gerhardol) [reply IntegrationTests/UI.IntegrationTests/UITest.cs]: The tests fails with this change, moving it to RunFormTest for now (but changing UITest or all forms using FileViewer could still be done in this PR)

Comment (RussKie) [reply IntegrationTests/UI.IntegrationTests/UITest.cs]: > I rather see stable tests than a winning a few second test time here, but my vote is weak.
> @RussKie has the majority vote.

You and @mstv have significantly more weight these days :)

**Review by RussKie — APPROVED** [review]

File: IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs [hunk 16]
```diff
@@ -483,6 +483,9 @@ private void RunFormTest(Func<FormCommit, Task> testDriverAsync, CommitKind comm
                         CommitKind.Fixup => _commands.StartFixupCommitDialog(owner: null, _referenceRepository.Module.GetRevision()),
                         _ => throw new ArgumentException($"Unsupported commit kind: {commitKind}", nameof(commitKind))
                     });
+
+                    // Await updated FileViewer
+                    ThreadHelper.JoinPendingOperations();
                 },
                 testDriverAsync);
         }
```
Comment (mstv) [inline IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs:491]: The call of `JoinPendingOperations` might be too early in `showForm:` because e.g. `OnShown` might be processed later. This depends on how the specific Form works.
Let's see whether the tests pass stably. If not, this can be moved into the `runTestAsync:` with a follow-up PR, and - if necessary - even with a loop checking whether the `FileViewer` has been populated finally.
