### PR TITLE
Make folder removal safer

### LINKED ISSUE #6630: [NBug] 索引超出范围。必须为非负值并小于集合大小。参数名: index
## Error Details
```
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 GitUI.CommandsDialogs.WorktreeDialog.FormManageWorktree.Worktrees_CellClick(Object sender, DataGridViewCellEventArgs e)
   在 System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   在 System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #7170: [NBug] The directory is not empty.
## Error Details
```
System.IO.IOException: The directory is not empty.

   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at GitUI.CommandsDialogs.WorktreeDialog.FormManageWorktree.Worktrees_CellClick(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Just tried to delete non empty worktree.

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #7579: [NBug] The process cannot access the file 'db.lock' because it is ...
## Current behaviour
GitExtensions crashed trying to remove an existing worktree (repository --> worktrees --> manage worktrees) while a file was locked by another application.

## Expected behaviour
An error is presented to the user and the worktree is not deleted.

## Steps to reproduce
- open an existing repository 
- create a new worktree
- lock any file on the new worktree (in my case, 'db.lock')
- go to repository / worktrees / manage worktrees
- delete the new worktree before releasing the lock

## Error Details
```
System.IO.IOException: The process cannot access the file 'db.lock' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at GitUI.CommandsDialogs.WorktreeDialog.FormManageWorktree.Worktrees_CellClick(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #7679: [NBug] Could not find a part of the path when long path
## Current behaviour

Error when attempting to delete a worktree. Worktree is partially deleted.

## Expected behaviour

Worktree is deleted successfully.

## Steps to reproduce

1. Create a worktree for a existing branch
2. Opened Manage worktrees dialog
3. Clicked the delete icon on one worktree.
4. Got this error.

## Error Details
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'Choosing the product or environment to register.htm'.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at GitUI.CommandsDialogs.WorktreeDialog.FormManageWorktree.Worktrees_CellClick(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
The part of the path mentioned is a file that exists in the checkout directory (nested down a long way is this a 260 chars length limitation? - "\\?\C:\XXXXX\XXXX\XXXXX_XXXXXXXXXXX_XXXXXXXX_XXXXXX\XXXX\XXXXXXXXXXXXX\XXXXX XXXXXXX\XXXXXXX\XXXXXXXXXXXX XXXXXX\XXXXXXXXXXX XXXXXXXXX XXXXX XXXX XXXXXXXXXX\XXXXXXXXXXX X XXX XXXXXXXXXXXX\XXXXXXXXXXX X XXXXXXX XX XXXXXXXXXXX\Choosing the product or environment to register.htm" from Windows Explorer copy path, modified for privacy - s/[a-z0-9\._]/X/). 

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3468.0
- DPI 120dpi (125% scaling)

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #7679
Fixes #7579
Fixes #7170
Fixes #6630

## Proposed changes

- Centralise how folders get deleted, and make the deletion process safer.

## Test methodology 

- unit tests

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/PathUtil.cs [hunk 1]
```diff
@@ -332,5 +332,28 @@ string FindFile(string location, string fileName1)
                 return null;
             }
         }
+
+        [ContractAnnotation("=>false,errorMessage:null")]
+        [ContractAnnotation("=>true,errorMessage:notnull")]
+        public static bool TryDeleteDirectory([NotNull] this string path, out string errorMessage)
+        {
+            errorMessage = string.Empty;
```
Comment (mstv) [inline GitCommands/PathUtil.cs]: Nit: Currently, this function always sets a non-null `errorMessage`.

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 2]
```diff
@@ -825,7 +825,7 @@ private bool DeleteSelectedFiles()
                     bool isDir = (File.GetAttributes(path) & FileAttributes.Directory) == FileAttributes.Directory;
                     if (isDir)
                     {
-                        Directory.Delete(path, true);
+                        path.TryDeleteDirectory(out string _);
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs]: Fail silently?

File: GitUI/GitUICommands.cs [hunk 3]
```diff
@@ -736,7 +736,7 @@ private bool StartResetChangesDialog(string fileName)
                         }
                         else
                         {
-                            Directory.Delete(path, true);
+                            path.TryDeleteDirectory(out string _);
```
Comment (mstv) [inline GitUI/GitUICommands.cs]: We should display the error message here, too.

File: GitUI/CommandsDialogs/RevisionDiffControl.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: This is an unknown submodule (as files are listed separately).
A messagebox could be added, but not important as this a special case. The directory will still be there...

File: GitUI/GitUICommands.cs (hunk 3 above)
Comment (gerhardol) [reply GitUI/GitUICommands.cs]: This is only used from command line

File: GitCommands/PathUtil.cs (hunk 1 above)
Comment (RussKie) [reply GitCommands/PathUtil.cs]: Aye!

File: GitUI/GitUICommands.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/GitUICommands.cs]: The existing code appears to be failing silently. I wasn't convinced a popup was necessary here.
I propose we add it if we have a real usecase

File: GitUI/CommandsDialogs/RevisionDiffControl.cs (hunk 2 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: The existing code appears to be failing silently. I wasn't convinced a popup was necessary here.
I propose we add it if we have a real usecase

File: GitCommands/PathUtil.cs [hunk 4]
```diff
@@ -332,5 +332,28 @@ string FindFile(string location, string fileName1)
...
         }
+
+        [ContractAnnotation("=>false,errorMessage:null")]
+        [ContractAnnotation("=>true,errorMessage:notnull")]
+        public static bool TryDeleteDirectory([NotNull] this string path, out string errorMessage)
+        {
+            errorMessage = null;
+            if (string.IsNullOrWhiteSpace(path) || !Directory.Exists(path))
+            {
+                return true;
```
Comment (mstv) [inline GitCommands/PathUtil.cs]: This breaches the contract. Here I could agree on failing silently.

Though in general, what is the convention for `TryFoo` functions? I think they should return true on success.

File: GitUI/CommandsDialogs/RevisionDiffControl.cs (hunk 2 above)
Comment (mstv) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: IIUIC, it catched the exception and displayed it.

File: GitUI/GitUICommands.cs (hunk 3 above)
Comment (mstv) [reply GitUI/GitUICommands.cs]: Especially in FormCommit, operations on files have failed silently many times.
In FormCommit, one can see at least that it has not worked.
In FormBrowse, one must select the virtual commits in order to check the result.
I.e. bad UX.

File: GitCommands/PathUtil.cs (hunk 4 above)
Comment (RussKie) [reply GitCommands/PathUtil.cs]: I'm not aware of any conventions on the return. Following my logic (debatable :)) if there is nothing to delete - it is a success. 
Alternatively, if we return `false` we may be crashing for no good reason.

Thoughts?

Comment (mstv) [reply GitCommands/PathUtil.cs]: You have defined `[ContractAnnotation("=>true,errorMessage:notnull")`, I read this as "return `true` and provide a message on error".
E.g. `TryGet` returns `true` on success, which is more intuitive to me.
I agree return success if the folder does not exist.

Comment (RussKie) [reply GitCommands/PathUtil.cs]: Ahh, I got it reversed! Thank you

File: GitUI/GitUICommands.cs [hunk 5]
```diff
@@ -727,23 +727,30 @@ private bool StartResetChangesDialog(string fileName)
...
+                    else
                     {
+                        errorCaption = Strings.ErrorCaptionFailedDeleteFolder;
+                        path.TryDeleteDirectory(out errorMessage);
                     }
-                    catch (UnauthorizedAccessException)
+
+                    if (errorMessage is { })
                     {
+                        MessageBox.Show(null, errorMessage, errorCaption, MessageBoxButtons.OK, MessageBoxIcon.Error);
```
Comment (RussKie) [inline GitUI/GitUICommands.cs]: 🤔 ❗️  This may be _extremely_ invasive if attempt to reset a lot of files/folders that aren't accessible for whatever reason...

File: GitUI/CommandsDialogs/RevisionDiffControl.cs (hunk 2 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: @mstv you're absolutely correct, I reverted this change

File: GitUI/GitUICommands.cs (hunk 5 above)
Comment (RussKie) [reply GitUI/GitUICommands.cs]: Maybe not... I haven't followed the code all the way through. 😴

File: UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs [hunk 6]
```diff
@@ -229,5 +229,34 @@ public void FindAncestors(string path, string[] expected)
...
             Assert.AreEqual(expected, PathUtil.FindAncestors(path).ToArray());
         }
+
+        private static IEnumerable<TestCaseData> InvalidFolders
+        {
+            get
+            {
+                yield return new TestCaseData(null);
+                yield return new TestCaseData("");
+                yield return new TestCaseData(@"A:\does\not\exist");
```
Comment (mstv) [inline UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs]: 😉 I assign `B:` to my backup drives. Some day, I will have a good usage for `A:`, too, and then I'll create these folders.

File: GitUI/GitUICommands.cs [hunk 7]
```diff
@@ -727,23 +727,30 @@ private bool StartResetChangesDialog(string fileName)
...
                     }
-                    catch (IOException)
+                    else
                     {
+                        errorCaption = Strings.ErrorCaptionFailedDeleteFolder;
+                        path.TryDeleteDirectory(out errorMessage);
                     }
-                    catch (UnauthorizedAccessException)
+
+                    if (errorMessage is { })
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitUI/GitUICommands.cs]: https://dev.to/peledzohar/the-perfect-non-null-test-4ohm :)

**Comment by RussKie** [comment]
Thank you for the reviews, I'm functioning at 110% CPU load, extra pairs of eyes are very helpful.

**Comment by RussKie** [comment]
@msftbot merge in 24 hours
