### PR TITLE
Fix FormCreateBranch layout

### LINKED ISSUE #9491: "Create branch..." has a wrong layout on 4k monitor, 150% DPI scale.
## Environment

- GitExtensions version:GitExtensions-Portable-3.6.0.12527-d8ddc1f6e.zip
- GIT version: 2.32.0.windows.1
- OS version: Windows 11 Preview
- .NET version: 4.8+.Net Core 5.0

### PR DESCRIPTION
**Pull request by RussKie**
Resolves #9491

### Before

* 150%
    image

### After

* 150%
    image

## Test methodology 

- Manual at various scale factors in range of 100-200%

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormCreateBranch.cs [hunk 1]
```diff
@@ -34,9 +35,9 @@ public FormCreateBranch(GitUICommands commands, ObjectId? objectId, string? newB
         {
             InitializeComponent();
 
-            // work-around the designer bug that can't add controls to FlowLayoutPanel
-            ControlsPanel.Controls.Add(Ok);
-            AcceptButton = Ok;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormCreateBranch.cs:39]: I fixed this bug in VS 17.2 (I think)... I'll fix other instances of this bug in follow up PRs.

File: GitUI/CommandsDialogs/FormCreateBranch.cs [hunk 2]
```diff
@@ -34,9 +35,9 @@ public FormCreateBranch(GitUICommands commands, ObjectId? objectId, string? newB
...
+            var w = Width;
+            var h = MainPanel.PreferredSize.Height + ControlsPanel.PreferredSize.Height + (Size.Height - ClientSize.Height);
+            MinimumSize = new Size(w, h);
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormCreateBranch.cs:40]: This is a tactical fix. I'll think how it could be generalized, and send a proposal in a follow up PR.

**Comment by RussKie** [comment]
@mdonatas/@lanzhiquan/everyone I'd appreciate a confirmation that this addresses the issue.

**Comment by RussKie** [comment]
@mdonatas / @lanzhiquan / everyone I'd appreciate a confirmation that this addresses the issue.

**Comment by RussKie** [comment]
If there are no objections, I'm planning to merge this in the next few days.

**Comment by mdonatas** [comment]
After some clicking around this is the only problem I've noticed. The table row is too high.

image

**Comment by RussKie** [comment]
@mdonatas what scale factor are you running at?

**Comment by RussKie** [comment]
Also, this fix is for  `FormCreateBranch`

**Comment by RussKie** [comment]
@mdonatas  https://github.com/gitextensions/gitextensions/pull/9960 is for the Push form
