### PR TITLE
Issue environment info

### LINKED ISSUE #5419: About dialog Add system info
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Have to run all over the place to get the current info for the environment section.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Add a feature that generates the following with filled in info in the about dialog.
```
- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 
```
**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**
No.

### PR DESCRIPTION
**Pull request by vbjay**
Fixes #5419 
Closes #5456 

Changes proposed in this pull request:
- Add issue environment info to about screen
- Allow user to copy this info
- Copy the info when raising an issue
 
Screenshots before and after (if PR changes UI):
image

image

What did I do to test the code and ensure quality:
- Manual test.  Click copy and then paste to verify output

Has been tested on (remove any that don't apply):

### CODE REVIEW

File: GitUI/GitUIExtensions.cs [hunk 1]
```diff
@@ -271,5 +272,27 @@ public static Control FindFocusedControl(this ContainerControl container)
...
+            return $"{versionInfo.FileMajorPart}.{versionInfo.FileMinorPart}.{versionInfo.FileBuildPart}.{versionInfo.FilePrivatePart}";
+        }
+
+        public static string GetIssueInfo()
+        {
+            StringBuilder sb = new StringBuilder();
+            sb.AppendFormat("{1}- Git Extensions version:  {0}{1}", AppSettings.ProductVersion, Environment.NewLine);
+            sb.AppendFormat("- GIT version:  {0}{1}", GetGitVersionString(), Environment.NewLine);
+            sb.AppendFormat("- OS version:  {0}{1}", Environment.OSVersion.ToString(), Environment.NewLine);
+            sb.AppendFormat("- .NET version:  {0}{1}", Environment.Version, Environment.NewLine);
```
Comment (RussKie) [inline GitUI/GitUIExtensions.cs]: This property's return is pretty meaningless. 
Have a look at [this SO discussion](https://stackoverflow.com/q/49750769/2338036), I think we should be using `RuntimeInformation.FrameworkDescription`  and `AppDomain.CurrentDomain.SetupInformation.TargetFrameworkName`.

File: GitUI/GitUIExtensions.cs [hunk 2]
```diff
@@ -271,5 +272,27 @@ public static Control FindFocusedControl(this ContainerControl container)
                 }
             }
         }
+
+        public static string GetGitVersionString()
+        {
+            if (!File.Exists(AppSettings.GitCommandValue))
```
Comment (RussKie) [inline GitUI/GitUIExtensions.cs]: Arguably this is unreachable code - if git is not installed the app will crash, see #5562

File: GitUI/UserEnvironmentInformation.cs [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+    public sealed class UserEnvironmentInformation
+    {
+        public static void CopyInformation()
+        {
+            Clipboard.SetText(GetInformation());
+        }
+
+        public static string GetInformation()
+        {
+            StringBuilder sb = new StringBuilder();
```
Comment (vbjay) [inline GitUI/UserEnvironmentInformation.cs]: I added the newlines surrounding the block to prevent the problem of the user pasting and the markup not being correct (blank line before and after list).  Depending on what they highlight and paste the blank line can be removed in the issue. I am not bothered by the removal.  Just wanted to make you aware of the reason why I had it in there.

File: GitUI/GitUIExtensions.cs (hunk 1 above)
Comment (vbjay) [reply GitUI/GitUIExtensions.cs]: image
I think RuntimeInformation gives the better description.

**Comment by vbjay** [comment]
Updated with git sha.  Test info below

- Git Extensions version:  3.00.a1 (ec28ebc05)
- GIT version:  2.19.1.1
- OS version:  Microsoft Windows NT 10.0.17763.0
- .NET version:  .NET Framework 4.7.3190.0

File: GitUI/UserEnvironmentInformation.cs [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+            sb.AppendFormat("- Git Extensions version:  {0} ({1}){2}", AppSettings.ProductVersion, ThisAssembly.Git.Commit, Environment.NewLine);
```
Comment (drewnoakes) [inline GitUI/UserEnvironmentInformation.cs]: Where is `ThisAssembly.Git.Commit` defined?

**Comment by RussKie** [comment]
I think we can trim the text to:


   - Git Extensions: 3.00.a1 (ec28ebc
   <https://github.com/gitextensions/gitextensions/commit/ec28ebc05f77381ed7556fd940aca336beafb649>
   )
   - GIT: 2.19.1.1
   - Microsoft Windows NT 10.0.17763.0
   - .NET Framework 4.7.3190.0


This way there's nothing to translate.

**Comment by RussKie** [comment]
Remove `:` too

File: GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs [hunk 5]
```diff
@@ -240,6 +240,7 @@ private static void GitHubItem_Click(object sender, EventArgs e)
 
         private static void IssuesItem_Click(object sender, EventArgs e)
         {
+            UserEnvironmentInformation.CopyInformation();
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs]: I would prefer to not copy here, the user may have copied something already
(in Browse too)

File: GitUI/UserEnvironmentInformation.cs (hunk 4 above)
Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]: https://github.com/kzu/GitInfo

File: GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs (hunk 5 above)
Comment (vbjay) [reply GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs]: Note the issue template change.  The user can recopy the thing they needed.  When they fill in the issue, they will see the note about what is in the clipboard.  I was looking for a toast notification that would let them know environment info was copied.  A non modal messagebox as it were.

**Comment by vbjay** [comment]
I can get the sha but it looks like this at the moment.  
image

File: GitUI/UserEnvironmentInformation.cs (hunk 4 above)
Comment (vbjay) [reply GitUI/UserEnvironmentInformation.cs]:
```c#
// <auto-generated />
#define GLOBALNAMESPACE
#define NOMETADATA
#pragma warning disable 0436

#if ADDMETADATA
[assembly: System.Reflection.AssemblyMetadata("GitInfo.IsDirty", ThisAssembly.Git.IsDirtyString)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.Branch", ThisAssembly.Git.Branch)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.Commit", ThisAssembly.Git.Commit)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.Sha", ThisAssembly.Git.Sha)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.BaseVersion.Major", ThisAssembly.Git.BaseVersion.Major)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.BaseVersion.Minor", ThisAssembly.Git.BaseVersion.Minor)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.BaseVersion.Patch", ThisAssembly.Git.BaseVersion.Patch)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.Commits", ThisAssembly.Git.Commits)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.Tag", ThisAssembly.Git.Tag)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.BaseTag", ThisAssembly.Git.BaseTag)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.SemVer.Major", ThisAssembly.Git.SemVer.Major)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.SemVer.Minor", ThisAssembly.Git.SemVer.Minor)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.SemVer.Patch", ThisAssembly.Git.SemVer.Patch)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.SemVer.Label", ThisAssembly.Git.SemVer.Label)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.SemVer.DashLabel", ThisAssembly.Git.SemVer.DashLabel)]
[assembly: System.Reflection.AssemblyMetadata("GitInfo.SemVer.Source", ThisAssembly.Git.SemVer.Source)]
#endif

#if LOCALNAMESPACE
namespace 
{
#endif
  /// <summary>Provides access to the current assembly information.</summary>
  partial class ThisAssembly
  {
    /// <summary>Provides access to the git information for the current assembly.</summary>
    public partial class Git
    {
      /// <summary>IsDirty: true</summary>
      public const bool IsDirty = true;

      /// <summary>IsDirtyString: true</summary>
      public const string IsDirtyString = "true";

      /// <summary>Branch: IssueEnvironment</summary>
      public const string Branch = "IssueEnvironment";

      /// <summary>Commit: ec28ebc05</summary>
      public const string Commit = "ec28ebc05";

      /// <summary>Sha: ec28ebc05f77381ed7556fd940aca336beafb649</summary>
      public const string Sha = "ec28ebc05f77381ed7556fd940aca336beafb649";

      /// <summary>Commits on top of base version: 286</summary>
      public const string Commits = "286";

      /// <summary>Tag: v3.00.00-beta1-286-gec28ebc05</summary>
      public const string Tag = "v3.00.00-beta1-286-gec28ebc05";

      /// <summary>Base tag: v3.00.00-beta1</summary>
      public const string BaseTag = "v3.00.00-beta1";

      /// <summary>Provides access to the base version information used to determine the <see cref="SemVer" />.</summary>      
      public partial class BaseVersion
      {
        /// <summary>Major: 3</summary>
        public const string Major = "3";

        /// <summary>Minor: 00</summary>
        public const string Minor = "00";

        /// <summary>Patch: 00</summary>
        public const string Patch = "00";
      }

      /// <summary>Provides access to SemVer information for the current assembly.</summary>
      public partial class SemVer
      {
        /// <summary>Major: 3</summary>
        public const string Major = "3";

        /// <summary>Minor: 00</summary>
        public const string Minor = "00";

        /// <summary>Patch: 286</summary>
        public const string Patch = "286";

        /// <summary>Label: beta1</summary>
        public const string Label = "beta1";

        /// <summary>Label with dash prefix: -beta1</summary>
        public const string DashLabel = "-beta1";

        /// <summary>Source: Tag</summary>
        public const string Source = "Tag";
      }
    }
  }
#if LOCALNAMESPACE
}
#endif
#pragma warning restore 0436
```

**Comment by RussKie** [comment]
The last screenshot looks clean, good.

If you have something in clipboard - don't click the "copy" button, simple.

**Comment by RussKie** [comment]
Jay, please keep the code simple. We can call 'git --version'

**Comment by vbjay** [comment]
> Jay, please keep the code simple. We can call 'git --version

You know, i totally didn't think of that.

**Comment by vbjay** [comment]
Uggh. Dang phone. Tapped close and comment. 

@Russkie  So are you saying don't copy on the issue links at all or only do so if the clipboard is empty or what?

**Comment by RussKie** [comment]
I'm on a phone as well ;)
I'll come back to your tonight (AEST)

File: GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs (hunk 5 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs]: I don't think we need another message box here. Keep it simple.

File: GitUI/UserEnvironmentInformation.cs (hunk 4 above)
Comment (RussKie) [reply GitUI/UserEnvironmentInformation.cs]: I think we need to reflected that we are taking a new dependency to generate the current assembly info. At least in the commit message, but better in the code (if appropriate).

**Comment by vbjay** [comment]
Rebased.

- Git Extensions 3.00.a1
- a6bb057e46de39f48f4b4c9a23c9974cee789dec 
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0

**Comment by RussKie** [comment]
😱 I typed a comment into the merge text box.... :rage3: 💩 


> GitGui project needs to be built for the git info to update. So if GitGui is built and then someone commits and then builds Gitextensions project, it will look at the old commit.

Is there a way we could ensure this info is always current?

**Comment by vbjay** [comment]
Yes.  I could switch the gitinfo nuget to gitextensions project and have UserEnvironmentInfo accept git info as a parameter.

**Comment by RussKie** [comment]
Please do. I'd like to reduce the human factor

**Comment by vbjay** [comment]
Sure.  Do you want to reset master?

**Comment by RussKie** [comment]
Mmmm, no. :)
I'm exhausted, it's almost midnight, I don't want to create more mess...

**Comment by vbjay** [comment]
Ok.  I'll create a new pull to fix it.
