### PR TITLE
Fix/search unmerged branches

### LINKED ISSUE #6813: Plugin "Delete obsolete branches" include unmerged branches give error "fatal: 'HEAD' is not a valid branch name."
When trying to find unmerged branches in the plugin, get an error 
"fatal: 'HEAD' is not a valid branch name.".

I have noticed this in 3.1.1.6049. Not sure of other 3.x versions. This feature used to work in 2.51.05.

Steps to reproduce:
1) Open the plugin "Delete obsolete branches"
2) Click on "Include unmerged branches"
3) Click on on the caution dialog
4) Click on "Search branches"

Expected result:
Should be able to get unmerged branches based on settings and filters.

Actual result:
Get an error "fatal: 'HEAD' is not a valid branch name." in the Name column.

### PR DESCRIPTION
**Pull request by manuelspezzani**
Fixes #6813

## Proposed changes

- added a "--list" option to the issued "git branch" command to prevent unexpected behaviors (e.g. creating a new branch, see comments on #6813)
- if the command fails a message box is displayed 

## Screenshots 
This is what happens in case of error:

error message

## Test methodology 
- Manual test

## Test environment(s) 
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Briefly look on my mobile. I have comments to write.

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs [hunk 1]
```diff
@@ -87,7 +89,7 @@ protected override void OnLoad(EventArgs e)
             BranchesGrid.DataSource = _branches;
         }
 
-        private static IEnumerable<Branch> GetObsoleteBranches(RefreshContext context, string curBranch)
+        private IEnumerable<Branch> GetObsoleteBranches(RefreshContext context, string curBranch)
```
Comment (RussKie) [inline Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: Why has this changed to an instance method?

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs [hunk 2]
```diff
@@ -108,7 +110,7 @@ private static IEnumerable<Branch> GetObsoleteBranches(RefreshContext context, s
             }
         }
 
-        private static IEnumerable<string> GetObsoleteBranchNames(RefreshContext context, string curBranch)
+        private IEnumerable<string> GetObsoleteBranchNames(RefreshContext context, string curBranch)
```
Comment (RussKie) [inline Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: ditto

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs [hunk 3]
```diff
@@ -125,21 +127,26 @@ private static IEnumerable<string> GetObsoleteBranchNames(RefreshContext context
...
-                .ToArray();
+            var result = context.Commands.GitExecutable.Execute(args);
 
-            return branches.Where(branchName => (!context.IncludeRemotes || branchName.StartsWith(context.RemoteRepositoryName + "/")) &&
-                                   (regex == null || regex.IsMatch(branchName) == regexMustMatch)).ToArray();
+            if (result.ExitedSuccessfully)
+            {
+                return _commandOutputParser.GetBranchNames(result.AllOutput)
+                                           .Where(branchName => branchName != curBranch && branchName != context.ReferenceBranch)
+                                           .Where(branchName => (!context.IncludeRemotes || branchName.StartsWith(context.RemoteRepositoryName + "/")) && (regex == null || regex.IsMatch(branchName) == regexMustMatch))
```
Comment (RussKie) [inline Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: Please wrap to make it readable

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs [hunk 4]
```diff
@@ -125,21 +127,26 @@ private static IEnumerable<string> GetObsoleteBranchNames(RefreshContext context
...
+                                           .ToArray();
```
Comment (RussKie) [inline Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: The method returns `IEnumerable<T>`, and the caller will materialise the sequence.
Why do we need to enumerate and allocate here?

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs [hunk 5]
```diff
@@ -125,21 +127,26 @@ private static IEnumerable<string> GetObsoleteBranchNames(RefreshContext context
...
+            }
+            else
```
Comment (RussKie) [inline Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: `else` is redundant.

Purely as an observation, I prefer to structure the code to have the "happy path" exit as the very last statement. This typically makes the code easier to follow.

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs [hunk 6]
```diff
@@ -125,21 +127,26 @@ private static IEnumerable<string> GetObsoleteBranchNames(RefreshContext context
...
+            {
+                MessageBox.Show(this, result.AllOutput, $"git {args}", MessageBoxButtons.OK, MessageBoxIcon.Error);
+                return new string[0];
```
Comment (RussKie) [inline Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]:
```suggestion
                return Array.Empty<string>();
```

File: Plugins/DeleteUnusedBranches/GitBranchOutputCommandParser.cs [hunk 7]
```diff
@@ -0,0 +1,26 @@
+﻿using System.Collections.Generic;
+
+namespace DeleteUnusedBranches
+{
+    public class GitBranchOutputCommandParser
+    {
+        public IEnumerable<string> GetBranchNames(string commandOutput)
+        {
+            if (commandOutput != null)
```
Comment (RussKie) [inline Plugins/DeleteUnusedBranches/GitBranchOutputCommandParser.cs]: Please invert to reduce nesting

File: Plugins/DeleteUnusedBranches/GitBranchOutputCommandParser.cs [hunk 8]
```diff
@@ -0,0 +1,26 @@
...
+            {
+                foreach (var line in commandOutput.Split('\n'))
+                {
+                    if (!string.IsNullOrWhiteSpace(line))
```
Comment (RussKie) [inline Plugins/DeleteUnusedBranches/GitBranchOutputCommandParser.cs]: Please amalgamate into the `foreach`.

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs (hunk 1 above)
Comment (manuelspezzani) [reply Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: Because the actual parsing is now performed by the new GitBranchOutputCommandParser: it's a class field so I remove the static clause on both methods.

I could have instantiated the parser as a local variable, but I prefer to instantiate all the collaborators in the constructor. Anyway, having a consistent code base it's more important so just let me know if you prefer to change it and I'll do my best. ;)

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs (hunk 2 above)
Comment (manuelspezzani) [reply Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: same as the other method

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs (hunk 4 above)
Comment (manuelspezzani) [reply Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: Honestly? It was materializing before and it's materializing now :)
I had a look at the caller method and you are right: that ToArray is useless. 
I'll fix it.

File: Plugins/DeleteUnusedBranches/GitBranchOutputCommandParser.cs (hunk 8 above)
Comment (manuelspezzani) [reply Plugins/DeleteUnusedBranches/GitBranchOutputCommandParser.cs]: Can you please elaborate on this?

Do you mean something like:
```
foreach (var line in commandOutput.Split('\n').Where(x => !string.IsNullOrWhiteSpace(x)))
{
 ...
}
```

I don't think it's actually better than the original in terms of readability...

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs (hunk 1 above)
Comment (RussKie) [reply Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs]: I missed that `GetObsoleteBranchNames` references an instance member.
Thank you for the clarification.

**Comment by RussKie** [comment]
Please squash and we'll get it merged.
Thank you

**Comment by RussKie** [comment]
Thank you
