### PR TITLE
Artificial commit count was cleared when manually refreshing the index

### LINKED ISSUE #4483: Commit index count dissapears on refresh
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The new "Commit index" and "Current unstaged changes" file count disappears when you click the refresh button. (Or press F5)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Stage some files and close the commit dialog. Note the commit index has a file count next to the words Commit index. Click the fresh icon. Both the Commit index count and Current unstaged changes count dissapear.

**Workaround**
Reopen the commit dialog and close it (making no changes). The values appear again next to Commit index and Current unstaged changes. The commit file count on the commit button is always correct.

**What is the expected behavior?**
The values should not disappear.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version:  2.13.0.windows.1
- OS version:  Windows 10x64

### PR DESCRIPTION
**Pull request by gerhardol**
fixes #4483
The count was cleared when refreshing the index (recreating all commits) but the commit count was not forced to be updated.
This change caches the count (similar to the commit button).

What did I do to test the code and ensure quality:
- Enable artificial commits
- Refresh the index
- Verify that count (may be 0) is still visible

Has been tested on (remove any that don't apply):
- Windows 10 and above

### CODE REVIEW

File: GitUI/UserControls/RevisionGrid.cs [hunk 1]
```diff
@@ -3024,28 +3024,25 @@ public void UpdateArtificialCommitCount(IReadOnlyList<GitItemStatus> status)
 
         private void UpdateArtificialCommitCount(IReadOnlyList<GitItemStatus> status, GitRevision unstagedRev, GitRevision stagedRev)
         {
-            int staged = status.Count(item => item.IsStaged);
-            int unstaged = status.Count - staged;
-            if (unstagedRev != null)
+            if (status != null)
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid.cs]: please invert to reduce nesting

Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid.cs]: null check was previously in CheckUncommitedChanged(), but should be in UpdateArtificialCommitCount() where the data is used.

OK to keep?

Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid.cs]: @RussKie ?

Comment (RussKie) [reply GitUI/UserControls/RevisionGrid.cs]: Apologies if I wasn't clear, I asked to invert the `if` to reduce nesting of the code

image

so it looks like 

```
if (status == null) 
{
    return;
}

// the rest of the code
```
