### PR TITLE
Fix Clone URL Population

### LINKED ISSUE #9520: Clone no longer detects github ssh url
## Current behaviour

Since #9116 was included a default url provided by github of `git@github.com:gitextensions/gitextensions.git` is no longer seen as a valid url and automatically included in the clone diaglog.

Example URL: `git@github.com:gitextensions/gitextensions.git`

## Expected behaviour

When getting the clone URL from github, gitextensions automatically populates this into the clone diaglog.

## Steps to reproduce

Put `git@github.com:gitextensions/gitextensions.git` on clipboard
Open clone diaglog
URL is not automatically populated on the diaglog

## Did this work in previous version of GitExtensions

Yes, in any version before #9116 was merged

## NOTE

The reason for this is that .net doesn't see `git@github.com:gitextensions/gitextensions.git` as a well formed uri string.

```
Uri.IsWellFormedUriString("git@github.com:gitextensions/gitextensions.git", UriKind.Absolute)
```
returns `False`

### PR DESCRIPTION
**Pull request by BlythMeister**
Fixes #9520

## Proposed changes

- Re-use the PathUtil.CanBeGitURL when checking parts of the string rather than only looking for a valid URL.

### Before

Clipboard had to contain a valid URL, not a valid Git URL.
This meant that urls like 'git@github.com:gitextensions/gitextensions.git' were not pulled from the clipboard.

### After

URL loaded from clipboard

## Test methodology

- Manual test
- 
- 

## Test environment(s) 

- GIT 2.33.0.windows.1
- Windows 10

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).
----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormClone.cs [hunk 1]
```diff
@@ -493,7 +493,7 @@ private bool TryExtractUrl(string contents, out string url)
             var parts = contents.Split(' ');
             foreach (string s in parts)
             {
-                if (Uri.IsWellFormedUriString(s, UriKind.Absolute))
+                if (PathUtil.CanBeGitURL(s))
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/FormClone.cs:496]: This will also include Git directories, which clone cannot handle.

Comment (BlythMeister) [reply GitUI/CommandsDialogs/FormClone.cs:496]: Fair, but the current logic doesn't even pull valid SSH URLs used by one of the biggest (if not the biggest) centralised git solutions in the world.

This is essentially a revert without losing the new functionality of pulling the git URL from a paragraph of text.

Comment (gerhardol) [reply GitUI/CommandsDialogs/FormClone.cs:496]: Not arguing bout that, just that `CanBeGitURL` is probably to general. 
If git-clone accepts Git directories, this is OK but the comment should be changed

Comment (BlythMeister) [reply GitUI/CommandsDialogs/FormClone.cs:496]: You can clone from a bare repository on a file system directory.
Which comment are you referring to?

Comment (gerhardol) [reply GitUI/CommandsDialogs/FormClone.cs:496]: Line 476

Comment (BlythMeister) [reply GitUI/CommandsDialogs/FormClone.cs:495]: Got it, thanks.  I've updated.

**Review by gerhardol — APPROVED** [review]

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you
