### PR TITLE
RevDiff: follow selection only in first list group

### LINKED ISSUE #7907: Improvement of retained file selection vs. two commit diff / merge diff
## Current behaviour

The combination of #7798 and of the #4154 implementation selects files in these additional diff groups. This can be unexpected and misleading, especially if the diff group headings are not visible due to many files.

The selection jumps to the second diff group of a merge diff when the previous commit was the left parent.

I guess the match is based only on the file name and ignores the path.

## Expected behaviour

Only matches in the first diff group are reselected.
The file path must match.

## Steps to reproduce

- select a merge commit, e.g. 37f4f9326da1ce72dafb468ab42a86e4d1eda947
- Ctrl+P, Ctrl+N

## Environment

- Git Extensions 4.0.0.8859
- Build 3bb59459d39c3fe086da40cf59994eb775562014 (Dirty)
- Git 2.24.1.windows.2
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #7907

## Proposed changes

Do not try to retain the selected item, if selection was done in
other than the first group or if the item is only appearing in other than the first group

See the issue for a description and discussion. I personally prefer the current behavior, but @mstv has requested this change. (This also conflicts with several other open PRs.)
The retain/follow for RevDiff was introduced in #7798 

## Screenshots 

Showing the behavior after only

i7907-retain-file

## Test methodology 

Code review, manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/UserControls/FileStatusList.cs [hunk 1]
```diff
@@ -400,6 +400,19 @@ public IEnumerable<GitItemStatusWithParent> SelectedItemsWithParent
                 .Where(i => i.Group?.Tag is GitRevision)
                 .Select(i => new GitItemStatusWithParent(i.Group.Tag<GitRevision>(), i.Tag<GitItemStatus>()));
 
+        public IEnumerable<GitItemStatus> FirstGroupItems
+        {
+            get
+            {
+                if (FileStatusListView.Groups.Count == 0)
+                {
+                    return new List<GitItemStatus>();
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]:
```suggestion
                    return Enumerable.Empty<GitItemStatus>();
```

File: GitUI/UserControls/FileStatusList.cs [hunk 2]
```diff
@@ -400,6 +400,19 @@ public IEnumerable<GitItemStatusWithParent> SelectedItemsWithParent
...
+                }
+
+                return from ListViewItem item in FileStatusListView.Groups[0].Items select item.Tag<GitItemStatus>();
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]: Can we write it in a functional way?
```cs
return FileStatusListView.Groups[0].Items.Select(item => item.Tag<GitItemStatus>())
```

Do we need to check for nulls?

Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: ListViewItemCollection does not support Select()
This is what Re# suggested
I can write as a loop instead

File: GitUI/UserControls/FileStatusList.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: Not supported
image

Comment (RussKie) [reply GitUI/UserControls/FileStatusList.cs]: Try `Array.Empty<GitItemStatus>()`

File: GitUI/UserControls/FileStatusList.cs (hunk 2 above)
Comment (RussKie) [reply GitUI/UserControls/FileStatusList.cs]: Do it as a `foreach` loop, it is faster and less allocations. I think it would look like:
```cs
foreach (ListViewItem item in FileStatusListView.Groups[0].Items)
{
	yield return item.Tag<GitItemStatus>();
}
```

File: GitUI/UserControls/FileStatusList.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: Using yield below required use here too: yield brake

File: GitUI/UserControls/FileStatusList.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: ok, rebased and pushed

File: GitUI/UserControls/FileStatusList.cs [hunk 3]
```diff
@@ -400,6 +400,22 @@ public IEnumerable<GitItemStatusWithParent> SelectedItemsWithParent
                 .Where(i => i.Group?.Tag is GitRevision)
                 .Select(i => new GitItemStatusWithParent(i.Group.Tag<GitRevision>(), i.Tag<GitItemStatus>()));
 
+        public IEnumerable<GitItemStatus> FirstGroupItems
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: done
Squashed

**Comment by gerhardol** [comment]
@msftbot merge in 1 day
