### PR TITLE
Limit removable for "Contained in branches/tags"

### LINKED ISSUE #5966: Overflow of superproject references
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
scrambled display and unclear `...` reference(s) after some time
3.00.00.4433:
grafik

current pre 3.01.00 master 7211073:
grafik

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- open the GE repo
- go to the subproject "ICSharpCode.TextEditor"
- move the mouse around for about 30 seconds

**What is the expected behavior?**
The revision grid is invalidated/refreshed correctly when the background process has finished.
The omitted info behind grafik should be displayed somewhere (if there is really something behind -- see the difference between the head commits in the screenshots).

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.10.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
new feature in 3.x

### PR DESCRIPTION
**Pull request by mstv**
Fixes #5966 (part 2 of 2).

## Proposed changes

- [x] Show up to 12 lines for "Contained in branches/tags", one branch/tag per line
- [x] Add link to show all "Contained in branches/tags"
- [x] Show relevant branches (current & masters) first
- [x] As long as GetSortedRefs() doesn't return the branches sorted by date (#7181), sort other branches alphabetically.
- [x] Add `TranslationString`s from helper classes to translation
- [x] Turn GetSortedRefs into GetSortedTags (no more need to load sorted branches)

### Before

grafik

### After

grafikgrafik
grafik

## Test methodology 

- added NUnit tests

## Test environment(s)- Git Extensions 3.3.0
- Build 7ff0c27138154120d4e886b8169119250af7fd5b
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: ResourceManager/LinkFactory.cs [hunk 1]
```diff
@@ -12,12 +12,14 @@ public interface ILinkFactory
...
         string CreateBranchLink(string noPrefixBranch);
         string CreateCommitLink(ObjectId objectId, string linkText = null, bool preserveGuidInLinkText = false);
+        string CreateShowAllLink(string what);
         string ParseLink(string linkText);
     }
 
     public sealed class LinkFactory : ILinkFactory
     {
         private readonly ConcurrentDictionary<string, string> _linksMap = new ConcurrentDictionary<string, string>();
+        private readonly TranslationString _showAll = new TranslationString("[ Show all ]");
```
Comment (mstv) [inline ResourceManager/LinkFactory.cs]: This `TranslationString` and those of the static class RefsFormatter are not detected.
How should I add them? `ITranslate` seems to be not prepared for `static` fields at first glance.

File: GitUI/CommitInfo/CommitInfo.cs [hunk 2]
```diff
@@ -264,9 +279,11 @@ private void ReloadCommitInfo()
             showMessagesOfAnnotatedTagsToolStripMenuItem.Checked = AppSettings.ShowAnnotatedTagsMessages;
             showTagThisCommitDerivesFromMenuItem.Checked = AppSettings.CommitInfoShowTagThisCommitDerivesFrom;
 
+            _showAllBranches = false;
+            _showAllTags = false;
             _branches = null;
-            _annotatedTagsMessages = null;
```
Comment (gerhardol) [inline GitUI/CommitInfo/CommitInfo.cs]: why change order
(just kidding, does not matter to me but you asked the same recently...)

**Comment by mstv** [comment]
> One comment about missing comment, ...

Could you give an example comment, please, @gerhardol?
This small function is too obvious to me - perhaps because I wrote it myself.

> I also have seen that the branch list is empty, but that could be caused by the Synantec virus that slows down git-status 7 times. Will check again.

I don't think I have tampered with this. It always loaded all refs before. 

> I would prefer to not see the + after prio branches

Are you sure that you don't have an (additional) branch named "+ bugfix/i7086-directory-detect".
(I've seen that you had "bugfix/i7086-directory-detect" for PR 7109.)
I'd say the `+` cannot have been added by the `RefsFormatter` because it wouldn't be the first "after-prio branch" due to the alphabetical ordering.

File: GitUI/CommitInfo/CommitInfo.cs [hunk 3]
```diff
@@ -859,6 +828,9 @@ int IndexOf(string s)
 
                     return -1;
                 }
+
+                bool IsLocalMaster(string branch) => branch == "master";
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommitInfo/CommitInfo.cs]: // Note: This assumes that "master" is the important branch, this is not configurable
(In some projects I work with any branch without "/" is a master branch. Some have multiple like master, master_special that are related, other projects happened to use a name like main)
But right now, configuring is not worth it.

**Comment by gerhardol** [comment]
> I don't think I have tampered with this. It always loaded all refs before.

Was just mentioning, I will just not approve myself until this is clear to me (it is likely slowness but I cannot troubleshoot on that PC)

> Are you sure that you don't have an (additional) branch named "+ bugfix/i7086-directory-detect".

The branch do not have + in the name.
The format of git-branch look strange though (just for this branch).
I find nothing about this in the man page

image

**Comment by pmiossec** [comment]
>
> I find nothing about this in the man page
>

Is there a possibility that it's due to a worktree?

>

**Comment by gerhardol** [comment]
> Is there a possibility that it's due to a worktree?

Bingo, it is the branch in the master worktree.

**Comment by gerhardol** [comment]
+ for branches checked out in other worktrees also occurs in current master, it is just that this is not so visible. This is another indication that this PR is an improvement

No brances at all is due to that I did not display remote branches where I saw the behavior

**Comment by gerhardol** [comment]
Separate PR for '+', could have been added here too
#7209

File: GitUI/CommitInfo/RefsFormatter.cs [hunk 4]
```diff
@@ -0,0 +1,131 @@
...
+            {
+                string noPrefixBranch = branch;
+                bool branchIsLocal;
+                if (getLocal && getRemote)
+                {
+                    // "git branch -a" prefixes remote branches with "remotes/"
+                    // It is possible to create a local branch named "remotes/origin/something"
+                    // so this check is not 100% reliable.
+                    // This shouldn't be a big problem if we're only displaying information.
+                    branchIsLocal = !branch.StartsWith(remotesPrefix);
```
Comment (gerhardol) [inline GitUI/CommitInfo/RefsFormatter.cs]: improve on comment
// This could be solved by listing local and remote branches separetly

File: GitUI/CommitInfo/CommitInfo.cs [hunk 5]
```diff
@@ -204,6 +201,24 @@ public void SetRevisionWithChildren(GitRevision revision, IReadOnlyList<ObjectId
             ReloadCommitInfo();
         }
 
+        public void ShowAll(string what)
+        {
+            switch (what)
+            {
+                case "branches": _showAllBranches = true; _branchInfo = null; break;
+                case "tags": _showAllTags = true; _tagInfo = null; break;
+                default: Debug.Fail("unsupported type in ShowAll(\"" + what + "\")"); return;
```
Comment (RussKie) [inline GitUI/CommitInfo/CommitInfo.cs]: I'm not finding this `switch` readable. It is easy to miss the second statements.
Please reformat with one statement per line.

File: GitUI/CommitInfo/RefsFormatter.cs [hunk 6]
```diff
@@ -0,0 +1,131 @@
...
+        ///
+        /// If limited, the line "[Show all]" and an empty line are added.
+        /// Hence the list needs to be limited only if it exceeds MaximumDisplayedRefsIfLimited + 2.
+        /// </summary>
+        private const int MaximumDisplayedRefsIfLimited = 10;
+
+        private static readonly TranslationString _containedInBranches = new TranslationString("Contained in branches:");
+        private static readonly TranslationString _containedInNoBranch = new TranslationString("Contained in no branch");
+        private static readonly TranslationString _containedInTags = new TranslationString("Contained in tags:");
+        private static readonly TranslationString _containedInNoTag = new TranslationString("Contained in no tag");
```
Comment (RussKie) [inline GitUI/CommitInfo/RefsFormatter.cs]: Can we not leverage the same mechanism for conditional strings as we have in `ResourceManager.Strings`?

Comment (mstv) [reply GitUI/CommitInfo/RefsFormatter.cs]: `RefsFormatter` would be a `static` class if it did not need to implement `ITranslate`.
Only temporary instance is created in order to satisfy the translation interface.

Is there a way in C# to give the metaobject to the `Translator`?
As an alternative, these few `TranslationString`s could be moved to `ResourceManager.Strings`.

Comment (mstv) [reply GitUI/CommitInfo/RefsFormatter.cs]: Is there a way in C# to give the metaobject to the `Translator`?

Should I move these few `TranslationString`s to `ResourceManager.Strings`, @RussKie?

Comment (mstv) [reply GitUI/CommitInfo/RefsFormatter.cs]: I have moved the `TranslationString`s to `Strings`.

File: ResourceManager/LinkFactory.cs [hunk 7]
```diff
@@ -84,6 +85,11 @@ public string CreateCommitLink(ObjectId objectId, string linkText = null, bool p
             return AddLink(linkText, "gitext://gotocommit/" + objectId);
         }
 
+        public string CreateShowAllLink(string what)
+        {
+            return AddLink("[ " + Strings.ShowAll + " ]", "gitext://showall/" + what);
```
Comment (RussKie) [inline ResourceManager/LinkFactory.cs]:
```suggestion
            return AddLink($"[ {Strings.ShowAll} ]", $"gitext://showall/{what}");
```

File: GitUI/CommitInfo/RefsFormatter.cs [hunk 8]
```diff
@@ -0,0 +1,116 @@
...
+using System.Linq;
+using System.Net;
+using System.Text;
+using System.Threading.Tasks;
+using GitCommands;
+using ResourceManager;
+
+namespace GitUI.CommitInfo
+{
+    public sealed class RefsFormatter
```
Comment (RussKie) [inline GitUI/CommitInfo/RefsFormatter.cs]: If a class contains only `static` members, the class should be marked as `static` (a small perf optimisation).
However can we not make members static? It creates coupling and makes testing harder

Comment (mstv) [reply GitUI/CommitInfo/RefsFormatter.cs]: Yes, it had been a `static` class until I implemented `ITranslate`. Forgot to turn it back to `static`.

This class contains only static methods and an instance of `LinkFactory`. But it does not use stateful methods of `LinkFactory`.

File: GitUI/CommitInfo/RefsFormatter.cs [hunk 9]
```diff
@@ -0,0 +1,116 @@
...
+
+            IEnumerable<string> FormatTags(IEnumerable<string> tags_)
+            {
+                return tags_.Select(s => showAsLinks ? LinkFactory.CreateTagLink(s) : WebUtility.HtmlEncode(s));
+            }
+        }
+
+        private static string ToString(IEnumerable<string> links, string prefix, string textIfEmpty, string refsType, bool truncated)
+        {
+            if (links.Any())
```
Comment (RussKie) [inline GitUI/CommitInfo/RefsFormatter.cs]: Invert if to reduce nesting

Comment (RussKie) [inline GitUI/CommitInfo/RefsFormatter.cs]: ❗️ Multiple enumerations

```cs
        private static string ToString(IEnumerable<string> links, string prefix, string textIfEmpty, string refsType, bool truncated)
        {
            var links = links.Join(Environment.NewLine);
            if (links.Length < 1)
                return string.Empty;
            // else format as necessary
```

File: GitUI/CommitInfo/RefsFormatter.cs [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+            {
+                var sb = new StringBuilder().AppendLine(WebUtility.HtmlEncode(prefix)).Append(links.Join(Environment.NewLine));
```
Comment (RussKie) [inline GitUI/CommitInfo/RefsFormatter.cs]: [readability]
```suggestion
                var sb = new StringBuilder()
                  .AppendLine(WebUtility.HtmlEncode(prefix))
                  .Append(links.Join(Environment.NewLine));
```

File: GitUI/CommitInfo/RefsFormatter.cs [hunk 11]
```diff
@@ -0,0 +1,116 @@
...
+                if (truncated)
+                {
+                    sb.AppendLine().AppendLine(LinkFactory.CreateShowAllLink(refsType));
```
Comment (RussKie) [inline GitUI/CommitInfo/RefsFormatter.cs]:
```suggestion
                    sb.AppendLine()
                      .AppendLine(LinkFactory.CreateShowAllLink(refsType));
```

File: GitUI/CommitInfo/RefsFormatter.cs [hunk 12]
```diff
@@ -0,0 +1,116 @@
...
+            return ToString(links, Strings.ContainedInBranches, Strings.ContainedInNoBranch, "branches", truncated);
+        }
+
+        public static string FormatTags(IReadOnlyList<string> tags, bool showAsLinks, bool limit)
+        {
+            bool truncate = limit && tags.Count > MaximumDisplayedRefsIfLimited + 2;
+            var links = FormatTags(truncate ? tags.Take(MaximumDisplayedRefsIfLimited) : tags);
+            return ToString(links, Strings.ContainedInTags, Strings.ContainedInNoTag, "tags", truncate);
+
+            IEnumerable<string> FormatTags(IEnumerable<string> tags_)
```
Comment (RussKie) [inline GitUI/CommitInfo/RefsFormatter.cs]:
```suggestion
            IEnumerable<string> FormatTags(IEnumerable<string> selectedTags)
```

File: GitUI/CommitInfo/RefsFormatter.cs [hunk 13]
```diff
@@ -0,0 +1,116 @@
...
+                }
+            }
+
+            return ToString(links, Strings.ContainedInBranches, Strings.ContainedInNoBranch, "branches", truncated);
+        }
+
+        public static string FormatTags(IReadOnlyList<string> tags, bool showAsLinks, bool limit)
+        {
+            bool truncate = limit && tags.Count > MaximumDisplayedRefsIfLimited + 2;
+            var links = FormatTags(truncate ? tags.Take(MaximumDisplayedRefsIfLimited) : tags);
```
Comment (RussKie) [inline GitUI/CommitInfo/RefsFormatter.cs]:
```suggestion
            var formattedTags = FormatTags(truncate ? tags.Take(MaximumDisplayedRefsIfLimited) : tags);
```

File: GitUI/CommitInfo/RefsFormatter.cs [hunk 14]
```diff
@@ -0,0 +1,116 @@
...
+                    allowRemote = false;
+                }
+            }
+
+            return ToString(links, Strings.ContainedInBranches, Strings.ContainedInNoBranch, "branches", truncated);
+        }
+
+        public static string FormatTags(IReadOnlyList<string> tags, bool showAsLinks, bool limit)
+        {
+            bool truncate = limit && tags.Count > MaximumDisplayedRefsIfLimited + 2;
```
Comment (RussKie) [inline GitUI/CommitInfo/RefsFormatter.cs]: Please don't use magic numbers, use consts instead

File: GitUI/CommitInfo/RefsFormatter.cs (hunk 9 above)
Comment (mstv) [reply GitUI/CommitInfo/RefsFormatter.cs]: > Invert if to reduce nesting

I agree: negative cases first.

Comment (mstv) [reply GitUI/CommitInfo/RefsFormatter.cs]: (Resharper works for me - thank you for the license!) I saw this warning, too. Though in this case, Re# is not perfect IMO.  I think it is cheaper to start the enumeration twice than to allocate an array (or a string in your quite efficient proposal) - because the first enumeration is stopped at once for `Any`.
Your proposal is mixing the positive with the negative case at the expense of readability.
So: How expensive is the second enumeration for `Any` really?

Comment (RussKie) [reply GitUI/CommitInfo/RefsFormatter.cs]: No, it is not so much the issue with the `Any` call, but the fact that the underlying collection may be enumerated multiple times when `links.Any()` is called followed by `links.Join(...)`

If the `links` underlying collection is materialised (e.g. a concrete `List<string>` or `Array`) then there will be no further allocations.
However imaging you have a complex query that fetches data from a database, a file or a network stream, and the result hasn't materialised:
```cs
var links = LoadInfoFromDatabase(ids)
				.Union(FetchLinksFromHttp)
				.Where(id => id < 100);

var formattedLinks = ToString(links, ...);
```

When the code reaches `Any` it hasn't loaded anything from a db or hit a remote endpoint. Executing `Any` will perform that so we have a result - "have results or not?".
Then `Join` operation will **again** execute the db request and hit the remote endpoint.

File: GitUI/CommitInfo/CommitInfo.cs [hunk 15]
```diff
@@ -859,6 +832,10 @@ int IndexOf(string s)
 
                     return -1;
                 }
+
+                // Note: This assumes that "master" is the important branch, this is not configurable.
+                bool IsLocalMaster(string branch) => branch == "master";
```
Comment (gerhardol) [inline GitUI/CommitInfo/CommitInfo.cs]: New suggestion: Can this be set to all branches starting with "master"? 
That would improve my use case and I cannot see that this will be too cumbersome for other users.
(IsRemoteMaster will require a regexp)

Comment (mstv) [reply GitUI/CommitInfo/CommitInfo.cs]: Done. Would have been no big deal if identifiers like `aIsRemoteMaster` would not have been denied as Hungarian Notation. So dont blame me for `isRemoteMaster_a`!

grafik

**Comment by mstv** [comment]
@RussKie 
> Public API must validate input parameters, please update tests as well.

I agree in principle. Here we are talking about a _formatter_ only.
I've declared the regarding arguments `[NotNull]` and added a test that checks for the regarding exceptions.

Or do you really want to have something like:
`Contained in branches: <null list>` and
`Contained in branches: current, master, <null>, upstream/master`?

In this area, I consider a `null` as a logical error and want to get NBug reports (if ever).
Though the exception should be considered non-fatal, i.e. shall not kill GE.
Should we introduce a base class "NonFatalException"? Or should we mark such exceptions with e.g. "[non-fatal]" in the exception message?

File: GitUI/CommitInfo/CommitInfo.cs (hunk 15 above)
Comment (RussKie) [reply GitUI/CommitInfo/CommitInfo.cs]: > That would improve my use case and I cannot see that this will be too cumbersome for other users.

omg, Gerhard-specific feature 😁

**Comment by RussKie** [comment]
More like:
```cs
        public string FormatBranches([NotNull] IEnumerable<string> branches, bool showAsLinks, bool limit)
        {
			if (branches == null)
			{
				return string.Empty;
			}

			// ...
```

An attribute decoration won't stop dereferencing a `null` at run time, it is only a hint for the compiler to help a developer.

File: GitUI/CommitInfo/CommitInfo.cs [hunk 16]
```diff
@@ -833,17 +769,69 @@ protected override void DisposeCustomResources()
...
+                {
+                    return -1;
+                }
+                else if (isRemoteMaster_b)
+                {
+                    return 1;
+                }
+
+#if true        // As long as GetSortedRefs() doesn't return the branches sorted by date, sort other branches alphabetically.
+                return defaultCompareResult;
```
Comment (gerhardol) [inline GitUI/CommitInfo/CommitInfo.cs]: Discussion: I wish to see local branches before remote and (especially on GH where I have many remotes) origin-upstream-other remotes after that. But this PR is an improvement as-is.

Comment (mstv) [reply GitUI/CommitInfo/CommitInfo.cs]: If you prefix the names of the other remotes with "z", you'll get most of this sorting - also in the left panel. Have a look at the screenshots.
Further tuning of the sorting should be addressed in conjunction with the git(?) bug #7181.

Comment (gerhardol) [reply GitUI/CommitInfo/CommitInfo.cs]: > If you prefix the names of the other remotes

Kind of what I use now.
With more information, more requests to format it will come. But I got the master* change, so I am satisfied

**Comment by mstv** [comment]
> Except #if true...#else..#end

That's why I have opened #7181.
Though sorting first by remotes, then in alphabetical order seems to be preferred.
So we could throw the `#else` code away and close #7181. Opinions, @gitextensions/git-extensions-source?

**Comment by gerhardol** [comment]
Ok for me, we can always revisit this

**Comment by mstv** [comment]
Restored tags sorted by date; created a dedicated `BranchComparer`; avoided loading of sorted branches which was not used anymore and did not work (#7181).
I hope this was the final iteration.

File: UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs [hunk 17]
```diff
@@ -74,18 +75,94 @@ public void OneTimeTearDown()
         }
 
         [Test]
-        public void GetSortedRefs_should_throw_on_git_warning()
+        public void BranchComparer([Values(null, "current")] string currentBranch)
```
Comment (RussKie) [inline UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs]: Is this a fancy replacement for `TestCase`?

Comment (mstv) [reply UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs]: Yes, especially if you have a few arguments. It tests all combinations.

File: GitUI/CommitInfo/CommitInfo.cs [hunk 18]
```diff
@@ -204,14 +204,33 @@ public void SetRevisionWithChildren(GitRevision revision, IReadOnlyList<ObjectId
...
+                case "branches":
+                    _showAllBranches = true;
+                    _branchInfo = null; // forces update
+                    break;
+                case "tags":
+                    _showAllTags = true;
+                    _tagInfo = null; // forces update
+                    break;
+                default:
+                    Debug.Fail("unsupported type in ShowAll(\"" + what + "\")");
```
[the remark this answers is not in the document]
Comment (mstv) [reply GitUI/CommitInfo/CommitInfo.cs]: There's no reason to kill GE if this fails. This is only a notice to developers for the case this type of link will be extended in the future.
We can change it when we have an exception type that triggers a NBug report and does _not_ close the repo.

**Comment by mstv** [comment]
@msftbot merge in 4 hours
