### PR TITLE
Increase stability of test execution

### LINKED ISSUE #7382: Appveyor tests hang/fail; tests with forms fail in debugger
## Current behaviour

Similar to #6172, builds intermittently hang and get killed by the AppVeyor timeout after 1 hour.
However the same builds succeed on re-run.

Additionally, some tests fail intermittently.

## Expected behaviour

All builds finish within reasonable time (~15min) before the timeout.

## Environment

- Git Extensions 3.3.0
- Build 1efcf3fc75f583242f71dbe12f326aef00b6a42a (both Debug & Release)
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

## Screenshots

grafik
grafik

## Diagnostics

I started the tests in the debugger in order to check the callstacks in case of `Debug` assertions.
But one test did not close FormBrowse. Then I could not open the `About` dialog. `Repository | Close` did not open the Dashboard, just removed the regarding main menu items. `Start | Exit` let the testcase finish.
The following tests failed with `System.Runtime.InteropServices.InvalidComObjectException: COM object disconnected`:
```
RepoObjectTree_moving_first_up_and_last_down_does_nothing
RepoObjectTree_moving_node_across_hidden_trees_skips_them
RepoObjectTree_moving_node_legally_moves_it
RepoObjectTree_should_show_all_submodules
```
Many other tests which open forms failed the same way.
I guess the forms are loaded too slowly when the tests are executed in the debugger.

Callstacks:
```
 	GitUI.dll!GitUI.GitUICommands.StartBrowseDialog(System.Windows.Forms.IWin32Window owner, string filter, GitUIPluginInterfaces.ObjectId selectedCommit) Line 1153	C#
 	GitUITests.dll!GitUITests.CommandsDialogs.CommitDialog.FormBrowseLeftPanelReorderNodesTest.RunFormTest.AnonymousMethod__13_0() Line 192	C#
 	GitUITests.dll!GitUITests.UITest.RunForm<GitUI.CommandsDialogs.FormBrowse>(System.Action showDialog, System.Func<GitUI.CommandsDialogs.FormBrowse, System.Threading.Tasks.Task> runAsync) Line 52	C#
 	GitUITests.dll!GitUITests.CommandsDialogs.CommitDialog.FormBrowseLeftPanelReorderNodesTest.RunFormTest(System.Func<GitUI.CommandsDialogs.FormBrowse, System.Threading.Tasks.Task> testDriverAsync) Line 189	C#
 	GitUITests.dll!GitUITests.CommandsDialogs.CommitDialog.FormBrowseLeftPanelReorderNodesTest.RunFormTest(System.Action<GitUI.CommandsDialogs.FormBrowse> testDriver) Line 179	C#
 	GitUITests.dll!GitUITests.CommandsDialogs.CommitDialog.FormBrowseLeftPanelReorderNodesTest.RepoObjectTree_moving_first_up_and_last_down_does_nothing() Line 73	C#
```
```
>	GitUI.dll!GitUI.GitUICommands.StartBrowseDialog(System.Windows.Forms.IWin32Window owner, string filter, GitUIPluginInterfaces.ObjectId selectedCommit) Line 1153	C#
 	GitUITests.dll!GitUITests.CommandsDialogs.CommitDialog.FormBrowseLeftPanelReorderNodesTest.RunFormTest.AnonymousMethod__13_0() Line 192	C#
 	GitUITests.dll!GitUITests.UITest.RunForm<GitUI.CommandsDialogs.FormBrowse>(System.Action showDialog, System.Func<GitUI.CommandsDialogs.FormBrowse, System.Threading.Tasks.Task> runAsync) Line 52	C#
 	GitUITests.dll!GitUITests.CommandsDialogs.CommitDialog.FormBrowseLeftPanelReorderNodesTest.RunFormTest(System.Func<GitUI.CommandsDialogs.FormBrowse, System.Threading.Tasks.Task> testDriverAsync) Line 189	C#
 	GitUITests.dll!GitUITests.CommandsDialogs.CommitDialog.FormBrowseLeftPanelReorderNodesTest.RunFormTest(System.Action<GitUI.CommandsDialogs.FormBrowse> testDriver) Line 179	C#
 	GitUITests.dll!GitUITests.CommandsDialogs.CommitDialog.FormBrowseLeftPanelReorderNodesTest.RepoObjectTree_moving_node_across_hidden_trees_skips_them() Line 134	C#
```
```
	GitExtUtils.dll!GitUI.ThreadHelper.FileAndForget(System.Threading.Tasks.Task task, System.Func<System.Exception, bool> fileOnlyIf) Line 96	C#
 	GitUI.dll!GitUI.UserControls.RevisionGrid.RevisionDataGridView.BackgroundThreadEntry() Line 479	C#

```

### PR DESCRIPTION
**Pull request by mstv**
Improves #7382

## Proposed changes

- do not run tests in parallel: `--workers=1`
  in order to avoid race conditions with singletons like the `AppSettings` and the clipboard
  (applies only to the tests of the same test assembly)
- set a default timeout of 90 seconds for every single test, and to 10 minutes for the only long running test (the maximum runtime seen was almost 40 seconds / 5 minutes) 

## Screenshots 

N/A

## Test methodology 

- trigger AppVeyor builds

## Test environment(s) 

- Git Extensions 3.3.0
- Build e6dad27982e96ccfc37a81b6ba99f80fb062d9b9
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
In `TestResult.xml`, thousands of assertions are counted.

Tests with status `gray`:
- `GitUITests.CancellationTokenSequenceTests.Concurrent_callers_to_Next_only_result_in_one_non_cancelled_token_being_issued`
  "![CDATA[This test requires more than one physical processor to run.]]"
  Does this test really not work good enough on one core with hyperthreading?
- `GitCommandsTests.StringPoolTests.AnalyzeHashFunctionDistribution`
  Only this one is mentioned on the console and counted as skipped:
```
Tests Not Run
1) Ignored : GitCommandsTests.StringPoolTests.AnalyzeHashFunctionDistribution
For hash analysis only, has no assertions
```
Test with status `yellow blinking` without duration, i.e. "unfinished", seem to be a problem of AppVeyor parsing `TestResult.xml`:
- `GitCommandsTests.GitModuleTests.BatchUnstageFiles_should_work_as_expected`
- `GitCommandsTests.ExternalLinks.ExternalLinksStorageIntegrationTests.Can_load_settings`

**Comment by mstv** [comment]
No good option:
If `nunit3-console.exe` is run with `--process=Single`, lots of unhandled exceptions are traced on the AppVeyor console with different call stacks, e.g.:
```
Unhandled Exception:
 
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Post(SendOrPostCallback d, Object state)
   at System.Reactive.Concurrency.SynchronizationContextExtensions.PostWithStartComplete(SynchronizationContext context, Action action)
   at System.Reactive.Concurrency.SynchronizationContextScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action)
   at System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.<>c__DisplayClass5_0.<Connect>b__0()
   at System.Reactive.Disposables.AnonymousDisposable.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.ObserveOnObserver`1.Dispose(Boolean disposing)
   at System.Reactive.ObserverBase`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at GitUI.CommitInfo.CommitInfo.DisposeCustomResources() in C:\projects\gitextensions\GitUI\CommitInfo\CommitInfo.cs:line 764
   at GitUI.GitModuleControl.Dispose(Boolean disposing) in C:\projects\gitextensions\GitUI\GitModuleControl.cs:line 130
   at GitUI.CommitInfo.CommitInfo.Dispose(Boolean disposing) in C:\projects\gitextensions\GitUI\CommitInfo\CommitInfo.Designer.cs:line 25
   at System.ComponentModel.Component.Finalize()
```

**Comment by mstv** [comment]
> We mustn't be wrapping everything in `NoAssertContext`, it only guards against `Debug.Assert` and `Debug.Fail`.

That's clear - see the "wrk in prgrss" in the title. AppVeyor was confusing me with its unability to parse the test case status correctly. I still think that the `NoAssertContext` will not have any effect on the AppVeyor runs.

> `GitUITests.CancellationTokenSequenceTests.Concurrent_callers_to_Next_only_result_in_one_non_cancelled_token_being_issued`
output message: "![CDATA[This test requires more than one physical processor to run.]]"

> Does this test really not work good enough on one core with hyperthreading (as the AppVeyor VM is provisioned)?

Thoughts?

**Comment by mstv** [comment]
Any idea why the recent [master build](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/28727936/tests) hung?
Unfortunately, `TestResult.xml` contains only the NUnit3 command line.
(For the next hung build, I killed the NUnit Agent via RDP. There must have been a `TestResult.xml` with tests including the pending one. Though the VM had been killed befored I noticed that. And artifacts are not stored if the tests fail.)

last completed tests
NUnit Agent not responding
parallel
threads
callstack 1
callstack 2

**Comment by mstv** [comment]
Establishing a RDP connection can have a quite bad influence on the tests.
The warning regarding the untrusted certificate popped up in the background and I didn't confirm it.
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/28729723
Many CommitDialog tests failed with the same message:
```
GitUITests.CommandsDialogs.CommitDialog.FormBrowseLeftPanelRemotesTests.RepoObjectTree_should_load_active_remotes
[00:04:40] System.InvalidOperationException : The UI Command Source is not available for this control. Are you calling methods before adding it to the parent control?
[00:04:40]    at GitUI.GitModuleControl.get_UICommandsSource() in C:\projects\gitextensions\GitUI\GitModuleControl.cs:line 65
[00:04:40]    at GitUI.GitModuleControl.get_UICommands() in C:\projects\gitextensions\GitUI\GitModuleControl.cs:line 89
[00:04:40]    at GitUI.GitModuleControl.get_Module() in C:\projects\gitextensions\GitUI\GitModuleControl.cs:line 112
[00:04:40]    at GitUI.CommitInfo.CommitInfo.<>c__DisplayClass55_0.<<ReloadCommitInfo>g__LoadBranchInfoAsync|7>d.MoveNext() in C:\projects\gitextensions\GitUI\CommitInfo\CommitInfo.cs:line 494
[00:04:40] --- End of stack trace from previous location where exception was thrown ---
```

**Comment by mstv** [comment]
The tests run a little quicker and should timeout earlier if they hang.
The test results are stored as artifact.
I'd like to merge this now. Further improvements can be done in a follow-up PR.

File: UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs [hunk 1]
```diff
@@ -41,7 +41,7 @@ public void Setup()
             _revisionGraph.Add(revision, RevisionNodeFlags.CheckedOut);
         }
 
-        [Test]
+        [Test, Timeout(10 /*min*/ * 60 /*s*/ * 1000 /*ms*/)]
```
Comment (RussKie) [inline UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs]: How did you come to a conclusion this test is causing hangs?
Why did you come up with 10 minutes figure?

File: Build/Run-Tests.ps1 [hunk 2]
```diff
@@ -12,8 +12,10 @@ $opencover_console = "packages\OpenCover.$opencover_version\tools\OpenCover.Cons
     -excludebyfile:*\*Designer.cs `
     -output:"OpenCover.GitExtensions.xml" `
     -target:"nunit3-console.exe" `
-    -targetargs:"$testAssemblies"
-if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
+    -targetargs:"$testAssemblies --workers=1 --timeout=90000"
```
Comment (RussKie) [inline Build/Run-Tests.ps1]: How does this affect a duration of the build?

**Comment by RussKie** [comment]
> Any idea why the recent [master build](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/28727936/tests) hung?

Looking at the log, the following tests haven't finished:


Test name | File name
-- | --
GitUITests.Script.ScriptOptionsParserTests.ScriptOptionsParser_resolve_cRemoteBranch("","feature/branch") | GitUITests.dll
GitUITests.Script.ScriptRunnerTests.RunScript_with_arguments_with_s_option_with_RevisionGrid_with_selection_shall_succeed | GitUITests.dll
GitCommandsTests.GitModuleTests.BatchUnstageFiles_should_work_as_expected([abc2,   abc2, abc2, Renamed def to abc3],["reset \"HEAD\" -- abc2 abc3   def", "update-index --info-only --index-info",   "update-index --force-remove --stdin"],False) | GitCommandsTests.dll
GitCommandsTests.FullPathResolverTests.Resolve_combines_paths("C:\\dev\\repo") | GitCommandsTests.dll

File: UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs (hunk 1 above)
Comment (mstv) [reply UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs]: This test does not hang. It always takes more than 4 minutes to pass. To be on the safe side, I've set the timeout to the double time (see issue description).

File: Build/Run-Tests.ps1 (hunk 2 above)
Comment (mstv) [reply Build/Run-Tests.ps1]: It does. It takes less time to execute the tests. I guess the single CPU core (with hyperthreading) works more effective with less threads. Anyway the tests from the different test assemblies are still run in parallel.

**Comment by mstv** [comment]
> Looking at the log, the following tests haven't finished:

You cannot trust the tab `Tests` of AppVeyor. There are always displayed yellow tests, i.e. unfinished ones, allegedly although all tests passed. That's why I want to store `TestRunner.xml` as an artifact ASAP. https://github.com/gitextensions/gitextensions/pull/7389#issuecomment-551306631

**Comment by RussKie** [comment]
Running tests locally I randomly get a popup that blocks.
e.g. something I just got:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding) in C:\Development\gitextensions\GitCommands\Git\Executable.cs:line 101
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding) in C:\Development\gitextensions\GitCommands\Git\Executable.cs:line 43
   at GitCommands.ExecutableExtensions.<GetOutputAsync>d__4.MoveNext() in C:\Development\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\Development\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 48
   at GitCommands.Git.AheadBehindDataProvider.GetData(Encoding encoding, String branchName) in C:\Development\gitextensions\GitCommands\Git\AheadBehindDataProvider.cs:line 60
   at GitCommands.Git.AheadBehindDataProvider.GetData(String branchName) in C:\Development\gitextensions\GitCommands\Git\AheadBehindDataProvider.cs:line 38
   at GitUI.BranchTreePanel.RepoObjectsTree.BranchTree.FillBranchTree(IEnumerable`1 branches, CancellationToken token) in C:\Development\gitextensions\GitUI\BranchTreePanel\RepoObjectsTree.Nodes.Branches.cs:line 284
   at GitUI.BranchTreePanel.RepoObjectsTree.BranchTree.<LoadNodesAsync>d__4.MoveNext() in C:\Development\gitextensions\GitUI\BranchTreePanel\RepoObjectsTree.Nodes.Branches.cs:line 248
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext() in C:\Development\gitextensions\GitUI\BranchTreePanel\RepoObjectsTree.Nodes.cs:line 220
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass40_0.<<AddTree>b__1>d.MoveNext() in C:\Development\gitextensions\GitUI\BranchTreePanel\RepoObjectsTree.cs:line 309
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext() in C:\Development\gitextensions\GitExtUtils\GitUI\ThreadHelper.cs:line 101
```

It is very similar to https://github.com/gitextensions/gitextensions/issues/6172, and I suspect we haven't fixed the root cause.

**Comment by mstv** [comment]
> I suspect we haven't fixed the root cause.

Nobody claimed this.
As stated above, in order to have reliable information about the test execution:
> I'd like to merge this now. Further improvements can be done in a follow-up PR.
> That's why I want to store TestRunner.xml as an artifact ASAP.

This PR will _not_ close the issue #7382. We should continue the discussion there.

**Comment by RussKie** [comment]
IIRC we started having dramas since we added ROT tests. I suspect some of the implementations (perhaps in tests) we use result in race conditions...
Right now I hypothesis that it may be multiple calls to `StartBrowseDialog` in tests.

May be try disabling the ROT tests, and see if you observe less hangs.
