### PR TITLE
Reset from command line

### LINKED ISSUE #10899: [NBug] git checkout-index:  is not in the cache
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.2.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

```
GitExtUtils.ExternalOperationException: git checkout-index:  is not in the cache ---> System.Exception: git checkout-index:  is not in the cache

   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResetFile(String file)
   at GitUI.GitUICommands.StartResetChangesDialog(String fileName)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

I just want to revert a lot of files and temporary work with the current set

### Steps to reproduce

Revert an old commit which has lots of files.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### LINKED ISSUE #10950: [NBug] git checkout-index: lib is not in the cache
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

```
GitExtUtils.ExternalOperationException: git checkout-index: lib is not in the cache ---> System.Exception: git checkout-index: lib is not in the cache

   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResetFile(String file)
   at GitUI.GitUICommands.StartResetChangesDialog(String fileName)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

Trying to reset the file changes.

### Steps to reproduce

Trying to reset the file changes back to original

### Did this work in previous version of GitExtensions?

Don't know.  First time trying it.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Resolves #10899 
Resolves #10950 

## Proposed changes

Three parts:
* Refactoring to use common code to reset all changes (just git-reset is not sufficient to reset in all situations).
* Common code to reset file changes.
Note that FormCommit:ResetFilesClick() vs RevisionDiffControl:ResetSelectedItemsWithConfirmation() are not merged. They are slightly different (the first only handles reset to HEAD). They still may require alignment.
* GE command line reset [file] (and revert that really is an alias) raised warnings if new, renamed, conflicted files were selected and did not work at all if 'reset all changes' were used.

Note: This PR (together with #10956) should be included in a 4.1.1, it is one of the most common issues raised.
I thought this was fixed in other PRs, but this is a separate scenario.
(Most issues regarding this have very minimal description.)

Note: This PR does not change the behavior (except command line usage that is aligned to FormCommit). Several of my private test scenarios fail with this PR still. 
I will submit a separate PR to handle these scenarios, not necessarily for 4.1.x

## Test methodology 

Manual

## Merge strategy

- Rebase merge

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
Cannot reset an unstaged file in FormCommit

- Git Extensions 33.33.33
- Build 6aec1427dc07ebd4ddb14482b77a947041d9f133
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Portable: False
```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at GitCommands.GitModule.ResetChanges(IEnumerable`1 selectedItems, Boolean resetAndDelete, IFullPathResolver fullPathResolver, List`1& filesInUse, StringBuilder& output, Action`1 action) in F:\Build\gitextensions3\GitCommands\Git\GitModule.cs:line 1396
   at GitUI.CommandsDialogs.FormCommit.ResetFilesClick(Object sender, EventArgs e) in F:\Build\gitextensions3\GitUI\CommandsDialogs\FormCommit.cs:line 2131
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by gerhardol** [comment]
Mostly working. Some tweaks may still be required.

image

Still occurs:
git checkout-index: a is not in the cache

RevDiff should use the same code path as for ResetChanges() when resetting in Index.
SSome situations are not handled there now (but other, that is not just resetting worktree/index to head).

'error: path 'a' is unmerged
error: pathspec 'a' did not match any file(s) known to git'

**Comment by gerhardol** [comment]
This will need some more work: When resetting, the status in both Index and WorkTree must be reset, so files in Index need to be unstaged. A separate git-status call may be required. Similar, after unstaging the new status is required and a new git-status is required.
In RevDiff, resetting to Index must be replaced with reset to HEAD to work well. This will remove the special code in RevDiff.

**Comment by gerhardol** [comment]
Only fixed the issues for command line (including the refactoring).
The updated functionality to handle some more scenarios in #10980

**Comment by RussKie** [comment]
> This PR (together with #10956) should be included in a 4.1.1, it is one of the most common issues raised.

Please tag the PRs you think should be included with [4.1.1 milestone](https://github.com/gitextensions/gitextensions/milestone/68).

File: GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -1334,21 +1334,34 @@ public string GetSubmoduleSummary(string submodule)
             return _gitExecutable.GetOutput(args);
         }
 
-        public void Reset(ResetMode mode, string? file = null)
+        public bool ResetAllChanges(bool resetAndDelete, bool onlyWorkTree = false)
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs:1337]: Could you please add xml-docs explaining each argument?

File: GitCommands/Git/GitModule.cs [hunk 2]
```diff
@@ -1367,6 +1380,75 @@ public string ResetFiles(IReadOnlyList<string> files)
                 .BuildBatchArgumentsForFiles(files));
         }
 
+        /// <summary>
+        /// Reset changes to the selected files.
+        /// </summary>
+        /// <param name="selectedItems">Items to reset, with Staged status set.</param>
+        /// <param name="resetAndDelete">Delete new (and renamed) files.</param>
+        /// <param name="fullPathResolver">The </param>
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs:1388]: Looks unfinished ;)

File: GitCommands/Git/GitModule.cs [hunk 3]
```diff
@@ -1367,6 +1380,75 @@ public string ResetFiles(IReadOnlyList<string> files)
...
+        /// <param name="filesInUse">Out put listing files in use, that cannot be deleted.</param>
+        /// <param name="output">Error messages from the reset.</param>
+        /// <param name="progressAction">Action when unstaging files (to update a progress bar).</param>
+        /// <returns><see langword="true"/> if successfully executed</returns>
+        public bool ResetChanges(IEnumerable<GitItemStatus> selectedItems, bool resetAndDelete, IFullPathResolver fullPathResolver, out List<string> filesInUse, out StringBuilder output, Action<BatchProgressEventArgs>? progressAction = null)
+        {
+            // If Staged was selected, unstage file first
+            IEnumerable<GitItemStatus> stagedFiles = selectedItems.Where(item => item.Staged == StagedStatus.Index).ToList();
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs:1396]: I think `ToList` is superfluous here, `BatchUnstageFiles` takes an enumerable and then materialises it itself.

File: GitUI/GitUICommands.cs [hunk 4]
```diff
@@ -701,93 +701,53 @@ bool Action()
...
+                }
 
-                    if (errorMessage is not null)
-                    {
-                        MessageBox.Show(null, errorMessage, errorCaption, MessageBoxButtons.OK, MessageBoxIcon.Error);
-                    }
+                Module.ResetChanges(selectedItems, resetAndDelete: resetType == FormResetChanges.ActionEnum.ResetAndDelete, _fullPathResolver, out List<string> filesInUse, out StringBuilder output);
+                if (!string.IsNullOrWhiteSpace(output.ToString()))
+                {
+                    MessageBox.Show(null, output.ToString(), TranslatedStrings.ResetChangesCaption, MessageBoxButtons.OK, MessageBoxIcon.Error);
```
Comment (RussKie) [inline GitUI/GitUICommands.cs:750]: Multiple calls to `output.ToString()`. Please use [`StringBuilder.Length` property](https://learn.microsoft.com/dotnet/api/system.text.stringbuilder.length) to check.

Comment (RussKie) [inline GitUI/GitUICommands.cs:750]: I think we should start making sure we're on the main thread before invoking message boxes. Functionality in `Module` can be (and perhaps should be) switching to a background thread.

Also, we should generally avoid using `null` for the owner argument as it makes messages boxes appear in different places to the app.

**Review by RussKie — COMMENTED** [review]
The changes look sensible. 👍 
Though, since it is a problematic spot in our codebase as you mentioned, we need to have a good test coverage.

**Comment by gerhardol** [comment]
> Though, since it is a problematic spot in our codebase as you mentioned, we need to have a good test coverage.

There are several parts here:
* This is a change for command line, there is no behavior tests for command line. I do not believe that there are many users that use explorer much with dev versions, so this is tested first in live releases. As this uses common code, at least the functionality is tested by common usage now.
* Test the Git behavior, that files are reset as expected. Before 4.0, some scenarios (mostly renamed and conflicts) did not work at all and raised NBug in 4.0 why there has been issues here (most remaining issues hopefully handled with #10980 ). To test Git behavior is a massive task, I am not sure it is worth it (very complex tests that will be slow). This PR isolates the path (and makes one common code base).

File: GitUI/GitUICommands.cs (hunk 4 above)
Comment (gerhardol) [reply GitUI/GitUICommands.cs:750]: This is from the command line only, there is no app and always on the main thread.
But this should be changed (not planned to do it here).

Comment (gerhardol) [reply GitUI/GitUICommands.cs:750]: ok

File: GitCommands/Git/GitModule.cs (hunk 3 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:1396]: removed (may be needed in #10980)

File: GitCommands/Git/GitModule.cs (hunk 2 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:1388]: fixed

File: GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:1337]: done

**Review by mstv — APPROVED** [review]

**Review by RussKie — APPROVED** [review]

**Comment by gerhardol** [comment]
I would have preferred to rebase merge this PR, as specified i the description.
The commit message is not describing the changes so well now.
(I waited merging this to make sure there were no changes required in the follow-ups, it does not seem to be the case.)

**Comment by RussKie** [comment]
> I would have preferred to rebase merge this PR, as specified i the description.
> The commit message is not describing the changes so well now.

My bad, I'll try to remember to check this before merging. ...Or let you merge yourself :)
