### PR TITLE
Insert artificial commits if filter without any matches is applied

### LINKED ISSUE #10162: [NBug] Unexpected artificial commit in Git command: 22222222222222...
### Environment

- Git Extensions 4.1.0.14868
- Build 2c3150d01d9c76bd13c72a742c26ceafcbf9eb64 (Dirty)
- Git 2.37.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.7
- DPI 96dpi (no scaling)

### Issue description

```
System.ArgumentException: Unexpected artificial commit in Git command: 2222222222222222222222222222222222222222
   at void GitCommands.ArgumentBuilderExtensions.Add(ArgumentBuilder builder, ObjectId objectId)
   at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+TryGetParents()
   at void GitUI.UserControls.RevisionGrid.RevisionDataGridView.SetToBeSelectedFromParents(IEnumerable<ObjectId> parents)
   at async void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+(?) => { } [30]
   at async void GitUI.ThreadHelper.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

### Steps to reproduce

Tried to filter for commit after disabling "commit message and hash" filter option, and enabling it again.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #10162

## Proposed changes

Handle selection after refresh if artificial commits are
removed from the view

## Test methodology 

Manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 1]
```diff
@@ -1324,7 +1325,17 @@ void OnRevisionReadCompleted()
...
+                            {
+                                notSelectedId = CurrentCheckout is not null
+                                    ? CurrentCheckout
+                                    : _gridView.ToBeSelectedObjectIds.Where(id => !id.IsArtificial).FirstOrDefault();
+                            }
+
+                            if (notSelectedId is not null)
+                            {
+                                parents = TryGetParents(Module, _filterInfo, notSelectedId);
+                            }
```
Comment (gerhardol) [inline GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:1338]: To keep it simple, the following can be reduced with the drawback that unselecting ShowArtificial while artificial is selected will not select anything

```suggestion
                            if (!notSelectedId.IsArtificial)
                            {
                                parents = TryGetParents(Module, _filterInfo, notSelectedId);
                            }
```

**Review by mstv — APPROVED** [review]
LGTM, I think the shorter variant suffices

File: GitUI/UserControls/RevisionGrid/RevisionGridControl.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionGridControl.cs]: Simplified this, added a comment instead
(The snippet was written when the solution was slightly different, I kept it though)
