### PR TITLE
Difference for initial commit of a file were presented as a diff to the working directory

### LINKED ISSUE #4580: Wrong diff for initial commit
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
gitext05

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Checkout 458ef9d6f76f0d6278c218717b7ce48750124e3d (from jbialobr fork)
2. Open file history for the SearchWindow.cs file
3. Go to the initial commit and see the diff tab.

**What is the expected behavior?**
gitext

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.15.1 
- OS version: win10

**Did this work in previous version of GitExtensions (which)?**

Yes: 2.50

### PR DESCRIPTION
**Pull request by gerhardol**
Difference for initial commit of a file were presented as a diff to the working directory (#4585)

Fixes #4580
Regression from #4313

Non-existing commits are handled with the "revision" null which is mostly handled as a working directory file.
The compare options for working directory files were limited in 2.50. In 2.51 the changes are presented with git-diff if possible and the non-existing parent were incorrectly handled.
Also some async/await changes

Don't indicate "in progress" async actions with WaitCursor.
If needed, the "awaiting" status should be displayed by the control that is awaiting the async action.
This should be done only if the load time is significant.

Cherry-pick of 7f7b26499bce424864ada3c05d15bd9ab6534581 from #4585  with one change: Suppress exception for patch release

The arguments to ViewChanges() is not fully investigated for the 2.51 release, use same behavior as in 2.50 and do not throw exceptions

Has been tested on (remove any that don't apply):
 - Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
I'm trying to reproduce the original bug as per Janusz's instrutions:

> Checkout 458ef9d (from jbialobr fork)
Open file history for the SearchWindow.cs file
Go to the initial commit and see the diff tab.

Here's what I'm getting built from this commit:

image


And this is what I see in **2.50.02**
image

**Comment by RussKie** [comment]
We have the exactly same behaviour in master.

**Comment by gerhardol** [comment]
There is nothing to compare with so this is expected. Diff cannot describe dev null to a commit. 
The other behaviour depends if you have a local file or something. 
In 2.51 there is special handling of untracked so diffs are presented.

File: GitUI/GitUIExtensions.cs [hunk 1]
```diff
@@ -87,11 +89,32 @@ public static Task ViewChanges(this FileViewer diffViewer, IList<GitRevision> re
...
-            return diffViewer.ViewPatch(() =>
+            if (firstRevision == null)
+            {
+                // The previous commit does not exist, nothing to compare with
+                if (file.TreeGuid.IsNullOrEmpty())
+                {
+                    if (secondRevision.IsNullOrWhiteSpace())
+                    {
+                        // Revision unexpectedly is not set, just return for 2.51 update
+                        return Task.CompletedTask;
```
Comment (jbialobr) [inline GitUI/GitUIExtensions.cs]: I don't understand why you want to silently swallow this. It should never happen, however if some path leads to this case I just  would like to throw an exception here and get a bug report about it happening. Otherwise an user can be misled about the diff content.

**Comment by jbialobr** [comment]
@RussKie This change is done on purpose. As I understand, @gerhardol shows the initial file content instead of showing a diff to /dev/null. The content of the diff here is pretty much the same, but UX is much better when the raw file content is shown for the initial commit.

**Comment by RussKie** [comment]
Thanks, I suppose we call it done then :)

**Comment by gerhardol** [comment]
> This change is done on purpose

@jbialobr @RussKie 
Not really on purpose. The example that show a diff is a special case. If there is no parent at all, also 2.50 shows this a new file. As there is no pssibility to "git-diff /dev/null..sha", the file has to be extracted and "git-diff --no-index /dev/null local-extracted-file" be used. 

Leave it as is.

image

File: GitUI/GitUIExtensions.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/GitUIExtensions.cs]: The diff will be empty, not incorrect.
I propose to leave the issue report to master. This would normally occur in a transient situations when switching revisions, or something. The users sees this as a blank diff so if there are situations where this occurs in valid situations, there will be visible anyway.

**Comment by RussKie** [comment]
I think that's the last outstanding issue for 2.51.01.
I'll try to wrap up the 2.51 release tonight

File: GitUI/GitUIExtensions.cs (hunk 1 above)
Comment (jbialobr) [reply GitUI/GitUIExtensions.cs]: >The diff will be empty, not incorrect.

It is hard to say not knowing circumstances at which it happened. 
In your solution you can at best get a bug report complaining about an empty diff. In my solution it is likely you get a call stack pointing to the bad invocation place.

Comment (RussKie) [reply GitUI/GitUIExtensions.cs]: @gerhardol let's throw

**Comment by RussKie** [comment]
Yay! 🍾 🎆
