### PR TITLE
Bypass hotkeys processing when inside SearchControl

### LINKED ISSUE #11122: Unexpected delete key behavior in the branch search box
### Environment

- Git Extensions 4.1.0.16698
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.16

### Issue description

Using the delete key when the cursor is in the branch search box doesn't edit the text as I would expect, but opens the "Delete branch" window instead

image

image

### Steps to reproduce

1. Type some text in the branch search box
2. Try to edit the text with the delete key
3. Observe that the Delete branch dialog opens instead of text getting modified

### Did this work in previous version of GitExtensions?

Not tested

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by dmitrybozhenok**
Fixes #11122 

## Proposed changes
Bypass hotkeys processing when the user is in branch search control. This should eliminate the possibility of unexpected behavior while editing. 

## Test methodology 

Manual

## Test environment(s) 

- GIT 2.41.0
- Microsoft Windows NT 10.0.22621.0

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]
👍

File: GitUI/LeftPanel/RepoObjectsTree.cs [hunk 1]
```diff
@@ -565,6 +565,16 @@ private void TxtBranchCriterion_KeyDown(object sender, KeyEventArgs e)
             e.Handled = true;
         }
 
+        public override bool ProcessHotkey(Keys keyData)
+        {
+            if (ActiveControl is SearchControl<string>)
```
[the remark this answers is not in the document]
Comment (dmitrybozhenok) [reply GitUI/LeftPanel/RepoObjectsTree.cs]: Done, also changed the condition to fit the existing code style

**Review by RussKie — APPROVED** [review]
Thank you

File: GitUI/LeftPanel/RepoObjectsTree.cs [hunk 2]
```diff
@@ -565,6 +565,17 @@ private void TxtBranchCriterion_KeyDown(object sender, KeyEventArgs e)
             e.Handled = true;
         }
 
+        public override bool ProcessHotkey(Keys keyData)
+        {
+            // skip hotkeys processing when inside branch search control to ensure proper editing
+            if (ActiveControl == _txtBranchCriterion)
```
Comment (mstv) [inline GitUI/LeftPanel/RepoObjectsTree.cs:571]: Other hotkeys, particularly the focus-changing `Ctrl+<digit>` should still work.
The following variant should be clear without a comment:
```suggestion
            if (_txtBranchCriterion.ContainsFocus && IsTextEditKey(keyData))
```

**Review by mstv — COMMENTED** [review]
@RussKie, we should take this for 4.2, shouldn't we?
So rebase on the release/4.0 branch and `Edit` the PR target?

**Comment by RussKie** [comment]
Good call,  yes please rebase on top of release/4.0.

File: GitUI/LeftPanel/RepoObjectsTree.cs (hunk 2 above)
Comment (dmitrybozhenok) [reply GitUI/LeftPanel/RepoObjectsTree.cs]: Thanks, this looks better! Done.

**Comment by dmitrybozhenok** [comment]
Modified according to @mstv suggestion, rebased to release/4.0 and changed target

**Review by mstv — APPROVED** [review]
Thank you
