### PR TITLE
do not crash on missing theme file

### LINKED ISSUE #7811: InvalidOperationException from ColorSettingsPage
##  Current behaviour

After the update from an a few weeks old 4.0 dev build to 65a1b55 (extended with Gerhard's diff features),
I cannot open the settings and cannot run some of the user scripts anymore. Instead I get this popup:

```
---------------------------
Error
---------------------------
System.InvalidOperationException: Themes were not added to ComboBox
   in GitUI.CommandsDialogs.SettingsDialog.Pages.ColorsSettingsPage.set_SelectedThemeId(ThemeId value)
   in GitUI.CommandsDialogs.SettingsDialog.Pages.ColorsSettingsPage.SettingsToPage()
   in GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()
   in GitUI.CommandsDialogs.FormSettings.LoadSettings()
---------------------------
OK   
---------------------------
```

## Expected behaviour

Settings can be opened, scripts can be run

## Steps to reproduce

- have an older GE settings file
- open Settings
- run a script using the context menu of the RevisionGrid (works if triggered using the assigned hotkey)

## Did this work in previous version of GitExtensions

Yes. This build works on my GE dev PC.

## Error Details
```
System.InvalidOperationException: Themes were not added to ComboBox
   bei GitUI.CommandsDialogs.SettingsDialog.Pages.ColorsSettingsPage.set_SelectedThemeId(ThemeId value)
   bei GitUI.CommandsDialogs.SettingsDialog.Pages.ColorsSettingsPage.SettingsToPage()
   bei GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()
   bei GitUI.CommandsDialogs.FormSettings.LoadSettings()
   bei GitUI.RevisionGridControl.<RefreshOwnScripts>g__RunScript|208_2(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

```
System.InvalidOperationException: Themes were not added to ComboBox
   bei GitUI.CommandsDialogs.SettingsDialog.Pages.ColorsSettingsPage.set_SelectedThemeId(ThemeId value)
   bei GitUI.CommandsDialogs.SettingsDialog.Pages.ColorsSettingsPage.SettingsToPage()
   bei GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()
   bei GitUI.CommandsDialogs.FormSettings.LoadSettings()
   bei GitUI.CommandsDialogs.FormSettings.FormSettings_Shown(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnShown(EventArgs e)
   bei System.Windows.Forms.Form.CallShownEvent()
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

## Environment
- Git Extensions 3.3.0
- Build d25652c1254aad8f0fa1cdbb7f8ca9b0ef560a56
- Git 2.21.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.4069.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by NikolayXHD**
Fixes #7811

## Proposed changes

Prevent crash when loading settings page if file for selected theme in AppSettings is missing.

Instead default theme is selected.

## Test methodology

- selected dark theme
- closed GitExtensions
- renamed `dark.css` to `dark2.css`
- started GitExtensions
- opened settings page

result:

- settings page opens
- default theme is selected

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs [hunk 1]
```diff
@@ -34,10 +35,17 @@ private ThemeId SelectedThemeId
...
                 if (index < 0)
                 {
-                    throw new InvalidOperationException("Themes were not added to ComboBox");
+                    // Handle case when selected theme is missing gracefully.
+                    // It may happen in a following scenario:
+                    // - user creates custom theme and selects it in this settings page
+                    // - user saves app settings
+                    // - user deletes the file with custom theme
+                    Trace.WriteLine("Theme not found: " + formattedThemeId);
+                    index = 0;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs]: What happens if there are no themes? And the combo stays empty?

Comment (NikolayXHD) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs]: If no themes combo still has 1 entry for default theme

Comment (RussKie) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs]: And the default theme can't be deleted, right?

Comment (NikolayXHD) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs]: Right, there is no file for it )
