### PR TITLE
GitStatusMonitor tweaks

### LINKED ISSUE #4256: memory leak & high CPU usage on windows 10
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
A memory leak & high CPU usage always happens to me. it causes nearly 100% memory usage & 100% single-thread CPU usage.

I have closed console window, it happens also.
I have tryed an older version - 2.49, it happens also.

snipaste_20171220_104610
snipaste_20171220_104544
I am sure that git bash has no problem. If I only use git bash, it works fine and memory used will never exceed 2M.
 **Here is a comparation:**
  * processes of git.exe launched by gitextensions:
snipaste_20171220_111031
  * a process of plain git bash:
snipaste_20171220_111907

**20171221 Updated**
A error dialog will be displayed in v2.49(may be fixed already ,i don't know) :
snipaste_20171221_110456

> Message:
>    Exception of type 'System.OutOfMemoryException' was thrown.
>
> Target Site:
>    Byte[] ReadByte(System.IO.Stream) @ GitCommands.SynchronizedProcessReader
>
> Stacktrace:   
>    at GitCommands.SynchronizedProcessReader.ReadByte(Stream stream)
>    at GitCommands.SynchronizedProcessReader.<>c__DisplayClass19_0.<ReadBytes>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart(Object obj)
>
> HResult:
>     -2147024882

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1.  open gitextensions with an existed git repository.
2.  after 10 minutes, it causes 100% memory usage & 100% single-thread CPU usage

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02/2.49
- GIT version: 2.15.1.windows.2
- OS version: windows 10 x64 professional edition (zh-CN language)
- hardware: Intel i5-6200U(2core,4threads), 8GB memory

**Did this work in previous version of GitExtensions (which)?**
no

### LINKED ISSUE #5439: Refreshing the repo status takes too long.
**Do you want to request a *feature* or report a *bug*?**

It is more like a bug.

**What is the current behavior?**

Eagerly loading all the ignored files slows down the regular status query.
When you have tens of thousands of ignored files it can take up to a minute to get git status completed
when run with ignored files included. Since we base the working dir and commit index info on this, it is a poor experience to have to wait that long for seeing changes to be reflected in the revisions grid.

**What is the expected behavior?**

The state of the working dir and commit index should be refreshed almost immediately.
As discussed in https://github.com/gitextensions/gitextensions/pull/5429, perhaps the best solution would be to drop the ignored files handling at all.

**Environment you encounter the issue:**

- GitExtensions version: e5384d73c6396ff4ceef8651ef9e151dbc71a58c

**Did this work in previous version of GitExtensions (which)?**

I think it was, when the ignored files where loaded separately.

### PR DESCRIPTION
**Pull request by gerhardol**
fixes #5439
fixes #4256

partly based on #5429
The handling was improved in #4327, #4328, fixing the regression
Those PRs limited the max load for git-status

Changes:
React faster on changing directory (1.0s->0.2s)
Some tweaks to the checks, do not check if update is required if an update is already scheduled

Do not read ignored files due to two problems:
 * Reading ignored can takes significant time. Since this was done the first time, the first update was delayed.
   (Reading ignored could be done later, but this will still delay the next update).
 * Saving all seen ignored files require substantial memory, see #4256.
   The list could be limited (see the issue), but that will increase the test time for ignored files

As ignored files will now always trigger git-status may cause some more runs.
However, the ignored file list was never complete, the list was better over time,
so GE must be able to handle this load anyway.
 
Screenshots before and after (if PR changes UI):
n/a

What did I do to test the code and ensure quality:
- manually

Has been tested on (remove any that don't apply):
- GIT 2.19
- Windows 7 and 10

### CODE REVIEW

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs [hunk 1]
```diff
@@ -394,71 +333,84 @@ private void Update()
...
                 {
                     // Still not up-to-date, but present what received, GetAllChangedFilesCmd() is the heavy command
-                    CalculateNextUpdateTime(UpdateDelay);
+                    CalculateNextUpdateTime();
                 }
             }
         }
 
-        private void CalculateNextUpdateTime(int delay)
+        private void CalculateNextUpdateTime(int delay = FileChangedUpdateDelay, bool isInterActive = false)
```
Comment (jbialobr) [inline GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: isInterActive  => isInteractive

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs [hunk 2]
```diff
@@ -394,71 +333,84 @@ private void Update()
             _statusIsUpToDate = true;
             _previousUpdateTime = Environment.TickCount;
 
+            // capture a consistent state in the main thread
+            var statusCancellationToken = _statusCancellationToken;
+            IGitModule module = Module;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: I don't think this will save us, should a user change working directory while we doing this.
Should it be something like 
```
var workingDir = Module.WorkingDir;
ThreadHelper.JoinableTaskFactory.RunAsync(async () => { ....
    var module = new GitModule(workingDir);
    ...
});

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs [hunk 3]
```diff
@@ -394,71 +333,84 @@ private void Update()
...
                 })
                 .FileAndForget();
 
-            // Schedule update every 5 min, even if we don't know that anything changed
-            CalculateNextUpdateTime(MaxUpdatePeriod);
-
             return;
 
-            void UpdatedStatusReceived(IReadOnlyList<GitItemStatus> changedFiles)
+            async Task<IEnumerable<GitItemStatus>> GetChangedFilesAsync()
```
Comment (RussKie) [inline GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Can we extract it as `ChangedFilesProvider`?

```
public interface IChangedFilesProvider
{
    Task<IEnumerable<GitItemStatus>> GetAsync();
}

public sealed class ChangedFilesProvider : IChangedFilesProvider
{
    public ChangedFilesProvider(Func<IGitModule> getModule) { ... }

    public async Task<IEnumerable<GitItemStatus>> GetAsync()
    {
        var module = GetModule();
        // ...
    }

    [NotNull]
    private IGitModule GetModule()
    {
        var module = _getModule();

        if (module == null)
        {
            throw new ArgumentException($"Require a valid instance of {nameof(IGitModule)}");
        }

        return module;
    }
}
```

The call site would probably look something like (pseudo code, it's past midnight here):

```
    try
    {
        await TaskScheduler.Default;
        var changedFiles = await _changedFilesProvider.GetAsync().ConfigureAwait(false);
        
        await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync(statusCancellationToken);
        UpdatedStatusReceived(changedFiles);
    }
    catch
    {
        await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync(statusCancellationToken);
        CurrentStatus = GitStatusMonitorState.Stopped;
        throw;
    }
    finally
    {
        ...
    }
```

This way we can inject it and test it (you knew I'd say this, didn't you? 😄).

Thoughts?

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs (hunk 2 above)
Comment (RussKie) [inline GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: I don't think this will save us, should a user change working directory while we doing this.
Should it be something like 
```
var workingDir = Module.WorkingDir;
ThreadHelper.JoinableTaskFactory.RunAsync(async () => { ....
    var module = new GitModule(workingDir);
    ...
});

Comment (vbjay) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: To be 100% sure, you need a thread boundary. A lock, or other way to prevent working directory changes between 

var workingDir = Module.WorkingDir;
AND
ThreadHelper.JoinableTaskFactory.RunAsync(async () => { ....

http://afana.me/archive/2015/07/10/memory-barriers-in-dot-net.aspx/

Comment (jbialobr) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: IGitModule does not allow to change its WorkingDir. I see no reason why we should create a new GitModule instance here.

Comment (gerhardol) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Not planning any change here then

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs (hunk 3 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: I know this was coming, should have written something about it....
You know my answer too, I have considered being more polite but then it would not be me so my standard answer is: I see no benefit in having this tested. 
The time for a test is better spent on other improvements in my opinion.

As usual, I will think about it but probably come to the same conclusion in some time.
The benefit of a test I see is that the implementation can be replaced without changing the behavior, but if we change the implementation of this small part it is to change the behavior.

**Comment by gerhardol** [comment]
Added a tweak to the refreshtimer, will squash before merging

**Comment by RussKie** [comment]
Pushed a refactor, which functionally I believe is equivalent to the original.
However after the refactor I started questioning the logic, which until the refactor wasn't as easy to spot.

 I inlined the code:
```
ThreadHelper.JoinableTaskFactory.RunAsync(
    async () =>
    {
        try
        {
            await TaskScheduler.Default;
            if (statusCancellationToken.IsCancellationRequested)
            {
                return;
            }

            var changedFiles = <get changed files>
            await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync(statusCancellationToken);

            // Adjust the interval between updates. (This does not affect an update already scheduled).
            _currentUpdateInterval = Math.Max(MinUpdateInterval, 3 * (Environment.TickCount - _previousUpdateTime));

// **** this block looks strange

            if (CurrentStatus != GitStatusMonitorState.Running)
            {
                return;
            }

            GitWorkingDirectoryStatusChanged?.Invoke(this, new GitWorkingDirectoryStatusEventArgs(changedFiles));

// ****
            if (!_statusIsUpToDate)
            {
                CalculateNextUpdateTime();
            }
        }
        finally
        {
            await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync(statusCancellationToken);
            CurrentStatus = GitStatusMonitorState.Stopped;
            _commandIsRunning = false;
        }
    })
    .FileAndForget();
```

The logic I'm finding confusing is between `// ****` markers.
1. Why would `CurrentStatus` be anything other than `Stopped`?
2. Few instructions above we have detected all changed files, why are we not raising an event to communicate the changes? Even, if the current status is still running?
3. If the current status is `Running` how do we report changed files?

It would be great if you could clarify it to me.
Thanks

**Comment by gerhardol** [comment]
Updated the refactoring so it works as before
The benefit with ChangedFilesProvider is that you can test GitCommandHelpers.GetStatusChangedFilesFromString(), already done though.

**Comment by gerhardol** [comment]
>> The logic I'm finding confusing is between // **** markers.

CurrentStatus is changed when the commit count is activated/deactivated (and at failures/updates)
So the status should always be Running here. If the status has changed, we do not report the status of course, otherwise reporting in the Invoke.

**Comment by RussKie** [comment]
> I think it is a bad idea to push it directly to this PR. I would prefer to see these changes submitted as a PR to the @gerhardol's branch.

The reason I've done it to generate/continue the discussion in the current thread and with the curent audience. Submitting to a fork would make it much harder. The owner of the fork can remove the change if it is wrong or incorrect (that appears it is).
The reason I want the code refactored is because (for one reason or another) I'm struggling to comprehend it. And I somewhat expect others to have troubles too.

**Comment by gerhardol** [comment]
I continued on the work @jbialobr had done in #5429 which used the structure of two levels of Tasks. This is not really needed here and can be simplified, pushed an update. Hopefully it is easier to understand now. As a second step, I removed some of the error handling, did not see a big need of disabling the service due to an exception.

**Comment by RussKie** [comment]
LGTM

**Comment by jbialobr** [comment]
> did not see a big need of disabling the service due to an exception.

Perhaps you are right here, but I perceive it as being on a safe side. Fetching the status is performed automatically and if for some repo it results in an error, it will be constantly bothering the user with error reports. When the user closes the error report window, instantly another error window is going to be shown.

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs [hunk 4]
```diff
@@ -384,86 +324,78 @@ private void Update()
...
 
             _commandIsRunning = true;
             _statusIsUpToDate = true;
             _previousUpdateTime = Environment.TickCount;
 
+            // Schedule update every 5 min, even if we don't know that anything changed
+            CalculateNextUpdateTime(PeriodicUpdateInterval);
+
+            // capture a consistent state in the main thread
+            var statusCancellationToken = _statusCancellationToken;
```
Comment (jbialobr) [inline GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Actually we capture here only the current `_statusCancellationToken` not capturing the current `Module`. While it seems to be harmless in this particular situation, it gives a bad pattern to follow. The harmless corner case I see here is when the `_changedFilesProvider.Get() ` is invoked after the repo change. `_changedFilesProvider` will operate on the new repo, but the result of `Get` will be discarded because the token being cancelled. The result is valid and could be used. The loss is meaningless.

**Comment by gerhardol** [comment]
> it will be constantly bothering the user with error reports

Will revert the latest commit then, add a few comments to the code.

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs (hunk 4 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Reverting ChangedFilesProvider changes would probably make this clearer

Comment (jbialobr) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Happy you are noticing that. 
I came across these talks related to this phenomenon
https://www.youtube.com/watch?v=JoTB2mcjU7w
https://www.youtube.com/watch?v=z9quxZsLcfo
Interestingly they all consider mocking as the last resort option.

Comment (RussKie) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Whilst this certainly is a possibility, what is the likelihood of  this actually happening?

I haven't had a chance to watch the videos, but comments seem to support my drive to decouple.

Comment (gerhardol) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: I reverted ChangedFilesProvider for now, readded the error handling and simplified some more. Commit chain is messy, but I will squash before merge. I expect that there will be further changes.

> Whilst this certainly is a possibility, what is the likelihood of this actually happening?

The problem pointed out was more to not set a pattern, low likelihood with no real drawback.

Removing ChangedFilesProvider makes this harder to test. I argue that GetStatusChangedFilesFromString() is tested anyway and ChangedFilesProvider adds a level of complexity without benefits.

Me and @RussKie have a different opinion on tests. RussKie is the 'tsar' and I try to adapt and be mostly quiet, it is much better that RussKie is happy than me slightly increases number of PRs. My (lazy) opinion is that a test should add something and RussKie that tests should always be added to not have a discussion.

Comment (RussKie) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: For me tests boost confidence and provide assurance when the code needs changing

**Comment by gerhardol** [comment]
@RussKie @jbialobr 
Any comments?
Can we keep it like this until a useful test case is defined?

Rebased (will squash when I get a go ahead)

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs [hunk 5]
```diff
@@ -384,86 +311,99 @@ private void Update()
...
-                        _ignoredFilesPending = _ignoredFilesAreStale;
-
-                        // git-status with ignored files when needed only
-                        var cmd = GitCommandHelpers.GetAllChangedFilesCmd(!_ignoredFilesPending, UntrackedFilesMode.Default, noLocks: true);
-                        var output = Module.RunGitCmd(cmd);
-                        var changedFiles = GitCommandHelpers.GetStatusChangedFilesFromString(Module, output);
+                        try
+                        {
+                            await TaskScheduler.Default;
+                            if (!statusCancellationToken.IsCancellationRequested)
```
Comment (RussKie) [inline GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Suggest inverting to reduce nesting

**Comment by RussKie** [comment]
Now you need to convince Janusz 😉

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs [hunk 6]
```diff
@@ -384,86 +311,99 @@ private void Update()
...
 
-                        UpdatedStatusReceived(changedFiles);
+                                UpdatedStatusReceived(changedFiles);
+                            }
+                        }
+                        catch
+                        {
+                            try
+                            {
+                                await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync(statusCancellationToken);
```
Comment (jbialobr) [inline GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Here, a CancellationException will override the caught exception if the token is cancelled. Since we have dropped the support for  ignored files, we no longer perform an expensive job here. Hence I would give up the `statusCancellationToken` at all and replace it with a simple check that the captured module has not been changed while fetching the repo status.

```csharp

            ThreadHelper.JoinableTaskFactory.RunAsync(
                async () =>
                {
                    try
                    {
                        try
                        {
                            await TaskScheduler.Default;
                            var cmd = GitCommandHelpers.GetAllChangedFilesCmd(true, UntrackedFilesMode.Default, noLocks: true);
                            var output = module.RunGitCmd(cmd);
                            var changedFiles = GitCommandHelpers.GetStatusChangedFilesFromString(module, output);

                            await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync;
                            if(!ModuleHasChanged())
                            {
                                UpdatedStatusReceived(changedFiles);
                            }
                        }
                        catch
                        {
                            await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync;
                            if(!ModuleHasChanged())
                            {
                                CurrentStatus = GitStatusMonitorState.Stopped;
                            }

                            throw;
                        }
                    }
                    finally
                    {
                        _commandIsRunning = false;
                    }
                })
                .FileAndForget();

                boolean ModuleHasChanged()
                {
                    return module != Module;
                }


```

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs [hunk 7]
```diff
@@ -384,86 +311,99 @@ private void Update()
...
+                            }
+                            finally
+                            {
+                                CurrentStatus = GitStatusMonitorState.Stopped;
```
Comment (jbialobr) [inline GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Performing this in the `finally` block does not guarantee that we are on the main thread.

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs (hunk 6 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Changed, but I would have preferred to keep this
git-status can still take many seconds. I also have some thoughts about reintroducing --ignored=matching at least as a test.

Code is simpler though.

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs (hunk 7 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Intentionally done like that even if not threadsafe. The worst that could happen is that the status is overwritten, this writing should be atomic.
Changed the handling to not introduce a bad pattern.

File: GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs [hunk 8]
```diff
@@ -384,86 +305,102 @@ private void Update()
...
+                        catch
+                        {
+                            try
+                            {
+                                await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
+
+                                // Avoid possible popups on every file changes
+                                CurrentStatus = GitStatusMonitorState.Stopped;
+                            }
+                            finally
```
Comment (jbialobr) [inline GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs]: Did you mean `catch`? I see no point in having try-finally with an empty `finally` block.
