### PR TITLE
Splitters: Fix crash when restoring size

### LINKED ISSUE #11085: SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.18
- DPI 120dpi (125% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

StackTrace (taken from later opened issue #11522 ):

```
System.InvalidOperationException: SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.
   at System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
   at GitUI.CommandsDialogs.FormBrowse.SetSplitterPositions() in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 2222
   at GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 473
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 106
   at GitUI.CommandsDialogs.FormBrowse.WndProc(Message& m) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 565
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

When I start Git Extentions, I get this error message.
I've fully deinstalled it, restarted and installed the same version again but it didn't help.

This seems like an issue issue which should be solved in an earlier version

### Steps to reproduce

Just start Git Extensions via it's shortcut generates this error

### Did this work in previous version of GitExtensions?

It worked fine with this version until yesterday. 

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by pmiossec**
(Should) Fixes #11085

## Test methodology 

- None (because I don't have a crash). Looking at stacktrace.

## Test environment(s) 

- GIT 
- Windows 

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -2231,7 +2231,18 @@ private void SetSplitterPositions()
             // Account for this shift. This is a workaround at best in the same way as for FormCommit.
             if (!RevisionsSplitContainer.Panel2Collapsed && RevisionsSplitContainer.FixedPanel == FixedPanel.Panel2)
             {
-                RevisionsSplitContainer.SplitterDistance -= 4;
+                try
+                {
+                    int adjustedDistance = RevisionsSplitContainer.SplitterDistance - 4;
+                    if (adjustedDistance > 0)
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormBrowse.cs:2237]: ❔
```suggestion
                    if (RevisionsSplitContainer.Panel1MinSize <= adjustedDistance && adjustedDistance <= RevisionsSplitContainer.Width - RevisionsSplitContainer.Panel2MinSize
```

**Review by mstv — COMMENTED** [review]
Looks sensible
(I was afraid we had to resolve this in `RestoreSplitters`. But yes, the callstack clearly points to here.)

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormBrowse.cs:2237]: Yes, probably better according to the exception

**Review by gerhardol — APPROVED** [review]
Pending mstv approval

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 1 above)
Comment (pmiossec) [reply GitUI/CommandsDialogs/FormBrowse.cs:2237]: In fact, I didn't like to re-implement all the logic in the setter. I find it difficult to read/maintain.
I misread the setter logic and I thinking about it again, I think that the try/catch only is good enough because the if don't add value here... I will remove it.

**Review by RussKie — APPROVED** [review]

**Review by mstv — APPROVED** [review]

**Comment by pmiossec** [comment]
Thanks.
