### PR TITLE
handle worktrees with spaces in the path

### LINKED ISSUE #3849: "Existing worktrees" window does not handle worktrees with a space in the path
**Do you want to request a *feature* or report a *bug*?**
Bug Report.

**What is the current behavior?**
The "Existing worktrees" window does not properly handle worktrees whose path contain a space. It's unclear, but this behavior may extend to more of the worktree experience.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create/have a Git repository in a folder that contains one or more space characters. Browse the repository with Git Extensions. On the main menu, select [Repository > Worktrees > Manage worktrees...].

**What is the expected behavior?**
The "Existing worktrees" window displays the full path to the root repository folder in the "Path" column of the displayed table, and the rest of the table reflects that the worktree exists.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**

- Git Extensions: 2.50.01
- Git: 2.12.2.windows.1
- Windows: Windows 7 Professional SP1

### PR DESCRIPTION
**Pull request by pmiossec**
Fixes #3849

- Fix "Manage worktree" form
- Fix creation of the worktree when putting a space in the path

Has been tested on:
 - GIT 2.13

### CODE REVIEW

File: GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs [hunk 1]
```diff
@@ -124,17 +124,17 @@ private void createWorktreeButton_Click(object sender, EventArgs e)
         private void CreateWorktree()
         {
             //https://git-scm.com/docs/git-worktree
-            var arguments = "worktree add " + WorktreeDirectory;
+            var arguments = "worktree add \"" + WorktreeDirectory + "\"";
```
Comment (RussKie) [inline GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs]: I hope this won't become another [_"Illegal characters in path" exception in worktrees_ issue...](https://github.com/gitextensions/gitextensions/issues/3489)

File: GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs [hunk 2]
```diff
@@ -46,7 +46,7 @@ private void Initialize()
                 var strings = current.Split(' ');
                 if (strings[0] == "worktree")
                 {
-                    currentWorktree = new WorkTree { Path = strings[1] };
+                    currentWorktree = new WorkTree { Path = current.Substring(9) };
```
Comment (RussKie) [inline GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs]: does this need changing? if so, why?
lines 55 and 66 use `strings[1]`

File: GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs (hunk 1 above)
Comment (pmiossec) [reply GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs]: Not sure of what I can do to work around that...

File: GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs (hunk 2 above)
Comment (pmiossec) [reply GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs]: For the other lines than "worktree", the values are separated by a space (that explain the `split()`) but for this line, there is just the abolute path of the worktree, that coud contains spaces.

So we must not split the line and just take the first element after "worktree" but all the rest of the line...

File: GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs (hunk 1 above)
Comment (jbialobr) [reply GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs]: There is nothing to be done. The cited issue does not apply here.

Comment (pmiossec) [reply GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs]: OK, that was my feeling but was not sure. Thanks a lot.

**Comment by tebeco** [comment]
\o/
thx @RussKie

**Comment by RussKie** [comment]
@tebeco - Thank @pmiossec, he did the work :)

**Comment by tebeco** [comment]
you're right ;)
thx @pmiossec
