### PR TITLE
fix(RevisionReader): Avoid hang on lengthy StandardOutput

### LINKED ISSUE #12055: After clicking on "Created new branch here..." application hangs forever
### Environment

- GitExtensions version: 5.1.1.17970
- GIT version:  2.47.0.windows.2
- OS version:  Windows 11
- .NET version:  .NET 8.0.11

### Issue description

After clicking on "Created new brunch here..." application hangs forever

Appeared after update to latest version.

### Steps to reproduce

- Right click on a brunch
- Clicking on "Created new brunch here"

### Did this work in previous version of GitExtensions?

Yes

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #12055

## Proposed changes

- fix(`RevisionReader.GetRevision`): Avoid hang in `StandardError.ReadToEnd` on lengthy `StandardOutput`
- The other usages of `GitCommandRunner.RunDetached` are not affected as they do not read `StandardError` at all.
- Extract `GetRevisionAsync` as proposed by Roslyn analyzer

## Screenshots 

N/A

## Test methodology 

- manual

## Test environment(s) 

https://github.com/mstv/test_lfs/tree/test_long_commit_body

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
+1 looks reasonable

File: src/app/GitCommands/RevisionReader.cs [hunk 1]
```diff
@@ -184,13 +201,21 @@ public IReadOnlyCollection<GitRevision> GetRevisionsFromRange(string olderCommit
                 Debug.WriteLine($"git {arguments}");
 #endif
                 using IProcess process = _module.GitCommandRunner.RunDetached(cancellationToken, arguments, redirectOutput: true, outputEncoding: null);
-                string errorOutput = process.StandardError.ReadToEnd();
+
+                // StandardError.ReadToEnd[Async] hangs if lengthy StandardOutput is not consumed in parallel. So, buffer the StandardOutput
```
Comment (RussKie) [inline src/app/GitCommands/RevisionReader.cs:205]:
```suggestion
                // StandardError.ReadToEnd[Async] may become unresponsive, if lengthy StandardOutput is not consumed in parallel. So, buffer the StandardOutput.
```

File: src/app/GitCommands/RevisionReader.cs [hunk 2]
```diff
@@ -184,13 +201,21 @@ public IReadOnlyCollection<GitRevision> GetRevisionsFromRange(string olderCommit
...
+                MemoryStream standardOutputBuffer = new();
```
Comment (RussKie) [inline src/app/GitCommands/RevisionReader.cs:206]:
```suggestion
                using MemoryStream standardOutputBuffer = new();
```

File: src/app/GitCommands/RevisionReader.cs [hunk 3]
```diff
@@ -184,13 +201,21 @@ public IReadOnlyCollection<GitRevision> GetRevisionsFromRange(string olderCommit
...
+                string errorOutput = await errorOutputTask;
                 if (!string.IsNullOrWhiteSpace(errorOutput) && throwOnError)
                 {
                     throw new ExternalOperationException(AppSettings.GitCommand, arguments.ToString(), innerException: new Exception(errorOutput));
                 }
 
-                commandBytes = new ReadOnlyMemory<byte>(process.StandardOutput.BaseStream.SplitLogOutput().SingleOrDefault().ToArray());
+                await standardOutputTask;
+                standardOutputBuffer.Position = 0;
+                commandBytes = new ReadOnlyMemory<byte>(standardOutputBuffer.SplitLogOutput().SingleOrDefault().ToArray());
```
Comment (RussKie) [inline src/app/GitCommands/RevisionReader.cs:218]: Please annotate (at least method) with NRT (you can use `#nullable enable/disable` in code).

Does `new ReadOnlyMemory<byte>()` accept null?

**Review by RussKie — COMMENTED** [review]
👍

File: src/app/GitCommands/RevisionReader.cs (hunk 1 above)
Comment (mstv) [reply src/app/GitCommands/RevisionReader.cs]: done

File: src/app/GitCommands/RevisionReader.cs (hunk 2 above)
Comment (mstv) [reply src/app/GitCommands/RevisionReader.cs]: done

File: src/app/GitCommands/RevisionReader.cs (hunk 3 above)
Comment (mstv) [reply src/app/GitCommands/RevisionReader.cs:220]: > Please annotate (at least method) with NRT (you can use `#nullable enable/disable` in code).

Done in a separate commit.

> Does `new ReadOnlyMemory<byte>()` accept null?

I does not need to. What could be `null` here? Proven by `﻿#nullable enable`.

Comment (RussKie) [reply src/app/GitCommands/RevisionReader.cs:220]: SingleOrDefault suggests it may be a null...

Comment (mstv) [reply src/app/GitCommands/RevisionReader.cs:220]: You are right that this code was suspicious and that `default` often means `null`.
But the `default` for `ReadOnlyMemory<byte>` seems to be an instance with length 0.
And its ctor accepts `byte[]?`.
But this was completely unnecessary because `SplitLogOutput` already yields the needed type.
