### PR TITLE
fix(PictureBox.OnPaint): Handle exceptions

### LINKED ISSUE #12583: [NBug] A generic error occurred in GDI+.
### Environment

- Git Extensions 5.2.1.18061
- Build 0d74cfdc312df90114a0cf8d6c8a30ca4213e2ff
- Git 2.49.0.windows.1
- Microsoft Windows NT 10.0.26100.0
- .NET 8.0.20
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Drawing.Graphics.DrawImage(Image image, Rectangle rect)
   at System.Windows.Forms.PictureBox.OnPaint(PaintEventArgs pe)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

.jpeg image crashes the diff view. The image was initially .ico, then I changed manually the extension to .jpeg and when gitextensions tries to preview it explodes

### Steps to reproduce

desc above

### Did this work in previous version of GitExtensions?

idk

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #12583

## Proposed changes

- fix(PictureBox.OnPaint): Handle exceptions which can occur on broken images

### Before

image

### After

image

## Test methodology 

- manually

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by pmiossec — APPROVED** [review]

File: src/app/GitUI/UserControls/PictureBoxEx.cs [hunk 1]
```diff
@@ -0,0 +1,22 @@
+﻿namespace GitUI.UserControls;
+
+/// <summary>
+///  A PictureBox which handles exceptions from OnPaint.
+/// </summary>
+public class PictureBoxEx : PictureBox
```
Comment (RussKie) [inline src/app/GitUI/UserControls/PictureBoxEx.cs]: Internal?

**Review by RussKie — APPROVED** [review]

**Review by gerhardol — APPROVED** [review]
