### PR TITLE
Fix 7097 crash invalid escape character in .gitmodule

### LINKED ISSUE #7097: [NBug] Invalid escape character in .gitmodule leads to crash
## Current behaviour

GitExtensions crashes with an error message when an invalid escape character is found in .gitmodule

## Expected behaviour

GitExtensions should warn the user, and make the user correct the file, before attempting to reload it again.

## Steps to reproduce

When you manually edit the path entry of a module in .gitmodules, the path may contain invalid escape characters. Upon saving the file, GitExtensions reloads the file, and crasehs.

## Error Details
```
System.Exception: Invalid escape character: f
   at GitCommands.Config.ConfigFile.ConfigFileParser.ReadValue(Char c)
   at GitCommands.Config.ConfigFile.ConfigFileParser.Parse(String fileContent)
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   at GitCommands.GitModule.GetSubmoduleConfigFile()
   at GitCommands.GitModule.<GetSubmodulesLocalPaths>g__GetSubmodulePaths|72_1(GitModule module)
   at GitCommands.GitModule.<GetSubmodulesLocalPaths>g__DoGetSubmodulesLocalPaths|72_0(GitModule module, String parentPath, List`1 paths, Boolean recurse)
   at GitCommands.GitModule.GetSubmodulesLocalPaths(Boolean recursive)
   at GitCommands.Submodules.SubmoduleStatusProvider.<UpdateSubmodulesStatusAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitCommands.Submodules.SubmoduleStatusProvider.<>c__DisplayClass17_0.<<UpdateSubmodulesStatus>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.18.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #7097

## Proposed changes

Catch exceptions related to invalid configs and present them to user in a better way, giving the user an opportunity to correct it rather than crashing the app.

### Before

image

### After

image

## Test methodology 

- manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
I rebases @lhiginbotham code from https://github.com/gitextensions/gitextensions/pull/7339, that sadly went stale. I've run the code to test it manually but I haven't had a chance to delve deep into the tests. 
@mstv you're now our test master, could you cast your eye on the `SubmoduleTestHelpers` tests? Is this needed?

**Comment by RussKie** [comment]
This change requires translations, but I'm happy to take it into the release without the translation unless there are objections.

**Comment by gerhardol** [comment]
For me, this can wait to a second RC or 3.4.1

File: UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs [hunk 1]
```diff
@@ -35,9 +35,22 @@ void ProviderStatusUpdated(object sender, SubmoduleStatusEventArgs e)
 
         public static async Task UpdateSubmoduleStatusAndWaitForResultAsync(ISubmoduleStatusProvider provider, GitModule module, IReadOnlyList<GitItemStatus> gitStatus)
         {
-            provider.UpdateSubmodulesStatus(workingDirectory: module.WorkingDir, gitStatus: gitStatus, forceUpdate: true);
+            List<DetailedSubmoduleInfo> result = new List<DetailedSubmoduleInfo>();
+            provider.StatusUpdated += Provider_StatusUpdated;
```
Comment (mstv) [inline UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs:39]: Looks unfinished. Can be done but is kind of pointless with the empty handler.

File: UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs [hunk 2]
```diff
@@ -64,7 +64,8 @@ public void TearDown()
             [Test]
             public async Task UpdateSubmoduleStructure_valid_result_for_top_module()
             {
-                var result = await SubmoduleTestHelpers.UpdateSubmoduleStructureAndWaitForResultAsync(_provider, _repo1Module);
+                var result = await SubmoduleTestHelpers.UpdateSubmoduleStructureAndWaitForResultAsync(_provider, _repo1Module).ConfigureAwait(false);
+                result.Should().NotBeNull();
 
                 result.TopProject.Path.Should().Be(_repo1Module.WorkingDir);
                 result.SuperProject.Should().Be(null);
```
Comment (mstv) [inline UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs:71]: nit: The pattern here was: Empty line before the assertions.
We can make the not-null assertion explicit but then for all call sites.

File: UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs [hunk 3]
```diff
@@ -118,7 +122,8 @@ public async Task Submodule_status_changes_for_top_module()
                 changedFiles.Should().HaveCount(1);
                 await SubmoduleTestHelpers.UpdateSubmoduleStatusAndWaitForResultAsync(_provider, currentModule, changedFiles);
 
-                result.OurSubmodules[0].Detailed.IsDirty.Should().BeTrue();
+                // Disabled test as the test case does not await async retrieval of submodule status
+                ////result.OurSubmodules[0].Detailed.IsDirty.Should().BeTrue();
```
Comment (mstv) [inline UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs:126]: I guess it will work with `forceUpdate: true`.

File: GitCommands/Submodules/SubmoduleStatusProvider.cs [hunk 4]
```diff
@@ -66,77 +65,75 @@ public void Init()
...
-            }).FileAndForget();
+                OnStatusUpdated(result, cancelToken);
+            }
+
+            _submoduleInfoResult = result;
         }
 
         /// <inheritdoc />
-        public void UpdateSubmodulesStatus(string workingDirectory, [CanBeNull] IReadOnlyList<GitItemStatus> gitStatus, bool forceUpdate)
+        public async Task UpdateSubmodulesStatusAsync(string workingDirectory, [CanBeNull] IReadOnlyList<GitItemStatus> gitStatus, bool forceUpdate)
```
Comment (gerhardol) [inline GitCommands/Submodules/SubmoduleStatusProvider.cs:136]: When I implemented the 'pruning' of submodule updates I did not get the cancellation token working properly so I implemented dropping of frequent updates only. The variable handling was a concern when reviewing this.
Fixed this, could make a parallel PR but rather wait until until this is merged.

https://github.com/gerhardol/gitextensions/tree/feature/i7097-cleanup-status-update

File: UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs (hunk 2 above)
Comment (mstv) [reply UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs:71]: > ... but then for all call sites.

Already there for all call sites. The diff display in GH made me think some were missing.

**Comment by mstv** [comment]
I took the liberty to resolve some of my comments myself.
Still open:
- factor out `GitConfigurationException` handling with `MessageBox` (https://github.com/gitextensions/gitextensions/pull/8049#discussion_r417614641 and https://github.com/gitextensions/gitextensions/pull/8049#discussion_r417616557)
- `ConfigureAwait(false)` (https://github.com/gitextensions/gitextensions/pull/8049#discussion_r417629924)
- unfinished `Provider_StatusUpdated` handler (https://github.com/gitextensions/gitextensions/pull/8049#discussion_r417638600)

File: GitCommands/Submodules/SubmoduleStatusProvider.cs (hunk 4 above)
Comment (mstv) [reply GitCommands/Submodules/SubmoduleStatusProvider.cs:136]: @gerhardol, could you have also a look a the disabled assertion in `Submodule_status_changes_for_first_nested_module` (#7443), please?

Comment (gerhardol) [reply GitCommands/Submodules/SubmoduleStatusProvider.cs:136]: I have looked at it, will continue later

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 5]
```diff
@@ -2567,7 +2583,23 @@ private void UpdateSubmodulesStructure()
...
+                }
+                catch (GitConfigurationException ex)
+                {
+                    await this.SwitchToMainThreadAsync();
+                    MessageBox.Show(this,
+                        string.Format(ResourceManager.Strings.GeneralGitConfigExceptionMessage, ex.ConfigPath, Environment.NewLine, (ex.InnerException ?? ex).Message),
+                        ResourceManager.Strings.GeneralGitConfigExceptionCaption,
+                        MessageBoxButtons.OK, MessageBoxIcon.Warning);
+                }
+            });
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitUI/CommandsDialogs/FormBrowse.cs:2602]: 👍

File: UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs (hunk 1 above)
Comment (RussKie) [reply UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs:39]: I'm not sure if it is needed at all...

**Comment by RussKie** [comment]
Thank you @mstv!

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (RussKie) [reply GitUI/CommandsDialogs/FormBrowse.cs]: done

File: UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs [hunk 6]
```diff
@@ -13,10 +13,10 @@ public static async Task<SubmoduleInfoResult> UpdateSubmoduleStructureAndWaitFor
...
             try
             {
-                provider.UpdateSubmodulesStructure(
-                    workingDirectory: module.WorkingDir,
-                    noBranchText: string.Empty,
-                    updateStatus: updateStatus);
+                await provider.UpdateSubmodulesStructureAsync(
+                        workingDirectory: module.WorkingDir,
+                        noBranchText: string.Empty,
+                        updateStatus: updateStatus).ConfigureAwait(false);
```
[the remark this answers is not in the document]
Comment (RussKie) [reply UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs:19]: `ConfigureAwait(false)` doesn't capture the context, and the continuation is performed on the same worker thread thread.
Since we aren't testing the UI here, thread affinity isn't important.

[the remark this answers is not in the document]
Comment (RussKie) [reply UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs]: I removed all `ConfigureAwait(false)`.

**Comment by RussKie** [comment]
I'd like to take it into 3.4. Any objections?

**Comment by mstv** [comment]
> I'd like to take it into 3.4. Any objections?

None. But I cannot review everything now.

File: GitCommands/Submodules/SubmoduleStatusProvider.cs (hunk 4 above)
Comment (gerhardol) [reply GitCommands/Submodules/SubmoduleStatusProvider.cs:136]: Submitted #8119 for the throttling changes
Tests are separate

**Comment by gerhardol** [comment]
> I'd like to take it into 3.4. Any objections?

Same comment for SubmoduleStatusProvider as in
https://github.com/gitextensions/gitextensions/pull/8049#pullrequestreview-402981180

This changes the timing some when refreshing/canceling and I would like to have #8119 in first, but that is maybe to big to be merged in 3.4 
There is still a disabled  testcase and the tests do not have complex enough setups.

But I doubt that this will give much issues compared to what we corrected in releases before 3.3

**Comment by gerhardol** [comment]
Tests are fixed in #8119 (as well as a minor problem in addition to the core feature).
(that also rebases this PR on master)

I prefer to not backport the fix and suggest we either include #8119 in 3.4 or wait with the correction.

**Comment by gerhardol** [comment]
> > The variable handling was a concern when reviewing this.
> 
> This makes me unsure, too, whether it is OK to turn the whole `UpdateSubmodules...` into async.
> Is this addressed by #8119, @gerhardol?

Not directly, but the cancellation token handling is less crappy so it is of less concern.

File: UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs [hunk 7]
```diff
@@ -15,169 +14,173 @@ namespace GitCommandsTests.Submodules
 {
     [SetCulture("en-US")]
     [SetUICulture("en-US")]
+    ////[Apartment(ApartmentState.STA)]
```
[the remark this answers is not in the document]
Comment (RussKie) [reply UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs]: Aye, thank you.

**Comment by RussKie** [comment]
Thank you @mstv 👍

**Comment by RussKie** [comment]
Catch exceptions related to invalid configs and present them to user in a better
way, giving the user an opportunity to correct it rather than crashing the app.

Fixes #7097

Co-authored-by: Logan Higinbotham, logan.higinbotham(at)gmail.com
Co-authored-by: Michael Seibt, mstv(at)gmx.net
