### PR TITLE
fix: label "No changes" no more hiding first file of the list

### LINKED ISSUE #11679: First file path is hidden by "No changes" in commit details form
### Environment

- GitExtensions version: `master` (after v4.2: 8a552ac13fa698f47674939aaebc671cf623d711 )
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

"No changes" should be hidden
image

### Steps to reproduce

In revision grid, double click on a commit.

### Did this work in previous version of GitExtensions?

Don't know.

### Diagnostics

"No changes" should be hidden

### PR DESCRIPTION
**Pull request by pmiossec**
when opening "FormLog"
even if it was set as not visible.

Fixes #11679

Reproduce step: double click on a revision in the revision grid

Regression introduced by f8c035302bba1351d88b5159e5ec93bfbbc5933d

/!\ Technical reason of the bug:
Previous code was:

            FilterComboBox.Visible = filesPresent || (SearchComboBox.Visible && !string.IsNullOrEmpty(SearchComboBox.Text));
            NoFiles.Visible = !FilterComboBox.Visible;

But as `FilterComboBox.Visible` is not just a property storing the value directly to a backed field
(it has a complex WinFoms internal logic),
 the value retrieved by the getter ( to after set `NoFiles.Visible`) is sometimes wrong and not the one set to the property :(
The value is not "well" set due to complex internal logic and so a wrong value is used after.

Using a temporary variable fix the issue because the set of the 2 properties has no more impact on each others!
### Before

image

### After

image

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build 10b42c51f9bf9285b4a064e2a3d2547ea215f87a
- Git 2.45.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.1
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/UserControls/FileStatusList.cs [hunk 1]
```diff
@@ -1070,6 +1070,7 @@ private void FileStatusListLoading()
             FileStatusListView.Groups.Clear();
             FileStatusListView.Items.Clear();
             FileStatusListView.EndUpdate();
+            FileStatusListView.BringToFront();
```
Comment (mstv) [inline GitUI/UserControls/FileStatusList.cs:1073]: Rather set the visibility in dependency on whether the commit is empty (tested with branch mstv/repro/empty_commit).

Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs:1073]: Set visibility is preferred, bring to front disrupts but just changing Visible seem to change order in some situations at least.
I had some problems here...
Whatever that works is OK for me.

Comment (pmiossec) [reply GitUI/UserControls/FileStatusList.cs:1073]: I will have a look again but the problem is that visibility is already set to false and the label is still visible 🤷

So I tried that as we already play with that to bring the label to front.

Comment (RussKie) [reply GitUI/UserControls/FileStatusList.cs:1073]: Can we push the lable to the back rather change the z-order of other controls?

File: GitUI/UserControls/FileStatusList.cs [hunk 2]
```diff
@@ -358,7 +358,7 @@ private void SetFileStatusListVisibility(bool filesPresent)
         {
             LoadingFiles.Visible = false;
             FilterComboBox.Visible = filesPresent || (SearchComboBox.Visible && !string.IsNullOrEmpty(SearchComboBox.Text));
-            NoFiles.Visible = !FilterComboBox.Visible;
+            NoFiles.Visible = !filesPresent;
```
Comment (mstv) [inline GitUI/UserControls/FileStatusList.cs:361]: Then rather make that `SearchComboBox.Visible` has already been set to `false` before calling this function.

**Comment by pmiossec** [comment]
I have spent some time investigating and found the real reason behind the regression in `SetFileStatusListVisibility()` (introduced by f8c035302bba1351d88b5159e5ec93bfbbc5933d ).

It was a difficult investigation partly because I didn't know the search feature.

Explained in the commit message (that I reproduce here):

>Previous code was:
>
>            FilterComboBox.Visible = filesPresent || (SearchComboBox.Visible && !string.IsNullOrEmpty(SearchComboBox.Text));
>            NoFiles.Visible = !FilterComboBox.Visible;
>
>But as `FilterComboBox.Visible` is not just a property storing the value directly to a backed field
>(it has a complex WinFoms internal logic),
> the value retrieved by the getter ( to after set `NoFiles.Visible`) is sometimes wrong and not the one set to the property :(
>The value is not "well" set due to complex internal logic and so a wrong value is used after.
>
>Using a temporary variable fix the issue because the set of the 2 properties has no more impact on each others!

File: GitUI/UserControls/FileStatusList.cs (hunk 2 above)
Comment (pmiossec) [reply GitUI/UserControls/FileStatusList.cs]: Sorry temporary push during investigation at a moment I though I get the reason but in fact not. Real fix pushed and just posted an explanation...

**Comment by pmiossec** [comment]
Investigation was painful and time consuming (also partly because, as I said I didn't know the search feature and the bug let me think that I missed something logical) and make me doubt about my knowledge of the De Morgan's Law Formula `!(A||B) = !A && !B` because it seems the 2 parts were not returning the same value 🤯

**but in fact the "bad behavior" lie in `FilterComboBox.Visible` getter/setter implementation/behavior....**: we don't always get back the value that have just been set 😕

**Review by gerhardol — APPROVED** [review]
approved pending mstv comment

I spent a lot of time on this too, handled many cases but missed this...
Thanks

File: GitUI/UserControls/FileStatusList.cs [hunk 3]
```diff
@@ -357,8 +357,11 @@ private void EnableSearchForList(bool enable)
...
         {
             LoadingFiles.Visible = false;
-            FilterComboBox.Visible = filesPresent || (SearchComboBox.Visible && !string.IsNullOrEmpty(SearchComboBox.Text));
-            NoFiles.Visible = !FilterComboBox.Visible;
+
+            // Use variable to prevent bad value retrieved from `Visible` property
+            bool filesToFilter = filesPresent || (SearchComboBox.Visible && !string.IsNullOrEmpty(SearchComboBox.Text));
+            FilterComboBox.Visible = filesToFilter;
+            NoFiles.Visible = !filesToFilter;
             if (NoFiles.Visible)
```
[the remark this answers is not in the document]
Comment (pmiossec) [reply GitUI/UserControls/FileStatusList.cs]: > Or is only `ComboBox` affected?

It seems to be OK for the label but as I can't be sure, you're right it's better to be careful. Done.

**Review by gerhardol — APPROVED** [review]

**Comment by RussKie** [comment]
> Investigation was painful and time consuming (also partly because, as I said I didn't know the search feature and the bug let me think that I missed something logical) and make me doubt about my knowledge of the De Morgan's Law Formula `!(A||B) = !A && !B` because it seems the 2 parts were not returning the same value 🤯
> 
> **but in fact the "bad behavior" lie in `FilterComboBox.Visible` getter/setter implementation/behavior....**: we don't always get back the value that have just been set 😕

Ah yes, `Control.Visible` (and few other properties) have complex logic behind them, and one shouldn't rely on those directly for state keeping purposes.
