### PR TITLE
Fix4185

### LINKED ISSUE #4185: Jenkins integration does not refresh "in progress" builds info.
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

As in the title.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Push a commit.
2. The build status is always In Progress.

**What is the expected behavior?**

Build server integration should query for completion status.

**Environment you encounter the issue:**
- GitExtensions version: 11c8c59ed79c617602d528d94bc6a51ecac31f56

**Did this work in previous version of GitExtensions (which)?**
No.

### PR DESCRIPTION
**Pull request by jbialobr**
Fixes #4185.

Changes proposed in this pull request:

1. Notify observers about completion.
2. Cache finished builds info.
3. Correct filtering out finished builds.

How did I test this code:

Manually observed build report tab and build status info.

Has been tested on (remove any that don't apply):
 - Windows 10

### CODE REVIEW

File: Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildInfo.cs [hunk 1]
```diff
@@ -16,10 +16,26 @@ public enum BuildStatus
...
         public string Id { get; set; }
         public DateTime StartDate { get; set; }
+        public long? Duration { get; set; }
         public BuildStatus Status { get; set; }
         public string Description { get; set; }
         public string[] CommitHashList { get; set; }
         public string Url { get; set; }
         public bool ShowInBuildReportTab { get; set; } = true;
+
+        public string DurationText()
```
Comment (RussKie) [inline Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildInfo.cs]: This overloads the DTO with behaviors, which isn't good.
I don't see any reason for this to be a method, it renders the set state, so it is deterministic.
Perhaps it is better to:
* rename `string DurationText()` to `string DurationFormatted { get; }`
* change the `Duration` property to set `DurationFormatted` upon assignment

File: Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildInfo.cs [hunk 2]
```diff
@@ -16,10 +16,26 @@ public enum BuildStatus
...
+        {
+            if (Duration.HasValue)
+            {
+                return " (" + (TimeSpan.FromMilliseconds(Duration.Value)).ToString(@"mm\:ss") + ")";
+            }
+
+            return string.Empty;
+        }
+
+        public void AddDurationToDescription()
```
Comment (RussKie) [inline Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildInfo.cs]: Same as above.
I would remove it completely, as it is only used in `JenkinsAdapter` and modify the adapter to set the `Description` the way it requires.

File: Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs [hunk 3]
```diff
@@ -530,7 +530,7 @@ public void ChangeProgressCounter()
 
         public void UpdateDescription()
         {
-            Description = Id + PullRequestText + " " + DisplayStatus + " " + Duration + TestsResultText;
+            Description = Id + PullRequestText + " " + DisplayStatus + " " + DurationText() + TestsResultText;
```
Comment (RussKie) [inline Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs]: Similar to the comment about `BuildInfo.AddDurationToDescription()` this method doesn't really belong to the DTO. And it should really be a concern of  `AppVeyorAdapter` (in `void UpdateDisplay(...)`).
Since this is an existing method, take this as a general design comment.

File: Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs [hunk 4]
```diff
@@ -84,14 +83,24 @@ public void Initialize(IBuildServerWatcher buildServerWatcher, ISettingsSource c
...
-                    task =>
-                    {
-                        JObject jobDescription = JObject.Parse(task.Result);
-                        return jobDescription["builds"].Select(b => b["url"].ToObject<string>());
-                    },
-                    TaskContinuationOptions.ExecuteSynchronously | TaskContinuationOptions.AttachedToParent));
+            _projectsUrls.Add(projectUrl);
+        }
+
+        private IEnumerable<Task<IEnumerable<string>>> getBuildUrls(bool forceUpdate)
```
Comment (RussKie) [inline Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs]: Please make the name PascalCase

File: Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs [hunk 5]
```diff
@@ -114,27 +123,25 @@ public IObservable<BuildInfo> GetRunningBuilds(IScheduler scheduler)
...
         }
 
+        private static Dictionary<string, BuildInfo> _finishedBuildsInfo = new Dictionary<string, BuildInfo>();
+
         private void ObserveBuilds(DateTime? sinceDate, bool? running, IObserver<BuildInfo> observer, CancellationToken cancellationToken)
         {
             try
             {
-                if (_getBuildUrls.All(t => t.IsCanceled))
+                var buildUrls = getBuildUrls(running ?? false);
```
Comment (RussKie) [inline Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs]: lines 138 and 144 cause multiple enumerations. 
perhaps change the signature of `GetBuildUrls` to be `IList<T>` or `T[]`

File: Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs [hunk 6]
```diff
@@ -114,27 +123,25 @@ public IObservable<BuildInfo> GetRunningBuilds(IScheduler scheduler)
...
-            {
-                return Observable.Empty<BuildInfo>(scheduler);
-            }
-
             return Observable.Create<BuildInfo>((observer, cancellationToken) =>
                 Task<IDisposable>.Factory.StartNew(
                     () => scheduler.Schedule(() => ObserveBuilds(sinceDate, running, observer, cancellationToken))));
         }
 
+        private static Dictionary<string, BuildInfo> _finishedBuildsInfo = new Dictionary<string, BuildInfo>();
```
Comment (RussKie) [inline Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs]: This can be made `readonly`

File: Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildInfo.cs (hunk 1 above)
Comment (jbialobr) [reply Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildInfo.cs]: >change the Duration property to set DurationFormatted upon assignment

I need the raw value to be able to compute the end date.

>rename string DurationText() to string DurationFormatted { get; }

It looks odd to me to pretend it is a property. The same way toString() is a function not a property (being deterministic as well). I want to provide a common, consistent way across all adapters to format the duration.

Comment (RussKie) [reply Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildInfo.cs]: I meant the following:

```
long? Duration 
{ 
    get { return _duration; }
    set 
    {
        _duration = value;
       DurationFormatted = _duration.HasValue ? ... : ...;
    }
}

string DurationFormatted { get; }
```

Comment (RussKie) [reply Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildInfo.cs]: > I want to provide a common, consistent way across all adapters to format the duration.

In this case I think it is better to create a separate class to do just that:

```
public interface IBuildDurationFormatter 
{
    string Format(long? buildDuration);
}


public sealed class BuildDurationFormatter : IBuildDurationFormatter
{
    public string Format(long? buildDuration) 
    {
           if (durationMilliseconds.HasValue)
           {
               return " (" + TimeSpan.FromMilliseconds(durationMilliseconds.Value).ToString(@"mm\:ss") + ")";
            }
            return string.Empty;
    }
}
```

Comment (jbialobr) [reply Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildInfo.cs]: How is DurationFormatted  better than DurationText()? What is the introduced behavior you are talking about that DurationText introduces and why DurationFormatted does not introduce it?

Don't you feel that BuildDurationFormatter  is a little over engineered? It does not have any dependencies nor state - it is just a static function.

**Comment by RussKie** [comment]
It may seem as over-engineered, but it makes it SOLID and allows to
decouple the code and reason about it in isolation.
The benefits are:
- the DTO/POCO object remains pure
- the consumer of the DTO does not concern itself with formatting specifics
- if a particular consumer needs a specific implementation it can be easily
provided without increasing cyclomatic complexity
- it makes it easy to test various behaviors and evolve them as required

The codebase is suffering from mix of state and behavior (GitModule is the
perfect example) and this makes it very difficult to change or evolve.

**Comment by RussKie** [comment]
> How is DurationFormatted better than DurationText()?

From pure API perspective, in a number of ways.
First, the original proposal is contrary to the naming guidelines (
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members).
It should have a verb in its name, e.g. `GetDurationText()` (which is
probably still a poor choice, since it isn't quite meaningful).
Secondly it isn't very meaningful - without looking into implementation I
struggled to infer its exact purpose. A better name is something like
`FormatDuration()` or something to that extent.
Thirdly, the method indicates/suggests an action, which typically much more
expensive than a property, and generally produces a non-deterministic
result. In this case, it is deterministic - once duration is set, its
formatted representation remains the same.

**Comment by jbialobr** [comment]
>It may seem as over-engineered, but it makes it SOLID and allows to
decouple the code and reason about it in isolation.

Done.

Thanks for explaining your point. Could you also address the last question I asked: "What is the introduced behavior you are talking about that DurationText introduces and why DurationFormatted does not introduce it?"

**Comment by RussKie** [comment]
Methods represent "behaviors", properties represent "state".
One can argue that .NET properties are syntactic sugar on top of get_/set_ methods, but they serve a very important role - to allow developers to tell behavior from state. In Java it is impossible to know whether something is a state accessor or a long running state-changing method.

My general concern was about mixing the state and behaviors - a POCO shouldn't have behaviors attached to it. One of the reasons - POCOs are passed around, sometimes crossing appdomain or process boundaries - for that they need to be serialised. You can't serialise behavior.
On a flip side, behaviors are often context-based and get substituted, that's where IoC comes to shine. But it makes it incredibly difficult or impossible to use IoC if behaviours are inter-mixed with state.

Depending on a situation it may be sensible to add additional computed properties (e.g. `DurationFormatted`) if it makes it easier to deal with the object.
