### PR TITLE
Highlight the new name in the FileStatusList

### LINKED ISSUE #6465: FileStatusList: highlight the new name
## Current behaviour

The path is displayed gray and the filename black.
For renamed files the new name is gray, too. Only the old is black which usually must be scrolled into view first.

## Expected behaviour

The new filename or both should be displayed in black.

## Steps to reproduce

select a commit with a moved file

### Screenshots

grafik

## Did this work in previous version of GitExtensions

If yes, then long time ago in 3.x. N/A for 2.5x.

## Environment

- Git Extensions 3.1.0
- Build 827c746e82af33ba959512fba4bd69251e37a782
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by mstv**
Fixes #6465

## Proposed changes

- detect renamed/copied files
- draw only the new filename black

### Before

before moved
before renamed without path

### After

after moved
after renamed without path

## Test methodology 

- manual

## Test environment(s) 

- Git Extensions 3.1.0
- Build 4ba5be25f33398170adc8651825b3c0107092ae2
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/UserControls/FileStatusList.cs [hunk 1]
```diff
@@ -1117,25 +1117,43 @@ private void FileStatusListView_DrawSubItem(object sender, DrawListViewSubItemEv
...
+                string prefix = null;
                 {
-                    formatter.DrawString(text, textRect, SystemColors.ControlText);
-                    return;
+                    int slashIndex = text.LastIndexOf('/');
+                    if (slashIndex >= 0 && slashIndex < text.Length)
+                    {
+                        prefix = text.Substring(0, slashIndex + 1);
+                        text = text.Substring(slashIndex + 1);
+                    }
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]: Let's extract prefix/suffix calculations into own private method and test these extensively (via `TestAccessor`)

Comment (mstv) [reply GitUI/UserControls/FileStatusList.cs]: How to extract the old name safely? Let PathFormatter return it separately! Rewritten including test for new methods.
