### PR TITLE
fix: Write and read enum setting as string not number

### LINKED ISSUE #8493: Script settings: JsonReaderException
> Test with the [portable build](https://ci.appveyor.com/api/buildjobs/f38yfwvu44gln65a/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-4.0.0.10218-2fb29d4e6.zip), please.

I'm testing the portable build and getting this error when open the Settings:

## Error Details
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: i. Path '', line 0, position 0.
   在 Newtonsoft.Json.JsonTextReader.ParseValue()
   在 Newtonsoft.Json.JsonTextReader.Read()
   在 Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   在 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   在 GitCommands.Settings.Setting.SettingOf`1.<>c.<GetValue>b__20_0(String value)
   在 GitCommands.SettingsCache.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   在 GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   在 GitCommands.Settings.SettingsContainer`2.GetValue[T](String name, T defaultValue, Func`2 decode)
   在 GitCommands.Settings.SettingsPath.GetValue[T](String name, T defaultValue, Func`2 decode)
   在 GitCommands.Settings.Setting.SettingOf`1.GetValue(String name)
   在 GitCommands.Settings.Setting.SettingOf`1.get_Value()
   在 GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.SettingsToPage()
   在 GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()
   在 GitUI.CommandsDialogs.FormSettings.LoadSettings()
   在 GitUI.CommandsDialogs.FormSettings.FormSettings_Shown(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnShown(EventArgs e)
   在 System.Windows.Forms.Form.CallShownEvent()
   在 System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   在 System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   在 System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

## Environment
- Git Extensions 4.0.0.10218
- Build 2fb29d4e6b29d1218ba4a5e21041cec9b0dbf171 (Dirty)
- Git 2.27.0.windows.1 (recommended: 2.28.0 or later)
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.4240.0
- DPI 96dpi (no scaling)

image

_Originally posted by @zjh-coder in https://github.com/gitextensions/gitextensions/issues/8486#issuecomment-699747852_

### PR DESCRIPTION
**Pull request by ivangrek**
Fixes #8493

## Proposed changes

- Write and read enum setting as string not number

### Before

- Enum value is stored as number

### After

- Enum value is stored as string

## Test methodology 

- Automation

## Test environment(s) 

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4220.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Settings/Setting.cs [hunk 1]
```diff
@@ -173,7 +173,24 @@ private object GetValue(string name)
...
                     {
-                        switch (Type.GetTypeCode(typeof(T)))
+                        var type = typeof(T);
+                        var underlyingType = Nullable.GetUnderlyingType(type) ?? type;
+
+                        if (underlyingType.IsEnum)
+                        {
+                            try
+                            {
+                                var result = Enum.Parse(underlyingType, value);
```
Comment (RussKie) [inline GitCommands/Settings/Setting.cs:183]: Why not https://docs.microsoft.com/en-us/dotnet/api/system.enum.tryparse?view=netframework-4.6.1?

File: GitCommands/Settings/Setting.cs [hunk 2]
```diff
@@ -173,7 +173,24 @@ private object GetValue(string name)
                 return SettingsSource
                     .GetValue<object>(name, null, value =>
                     {
-                        switch (Type.GetTypeCode(typeof(T)))
+                        var type = typeof(T);
+                        var underlyingType = Nullable.GetUnderlyingType(type) ?? type;
+
+                        if (underlyingType.IsEnum)
```
Comment (RussKie) [inline GitCommands/Settings/Setting.cs:179]: It is worth adding a comment why we handle enums differently

File: GitCommands/Settings/Setting.cs (hunk 1 above)
Comment (ivangrek) [reply GitCommands/Settings/Setting.cs:183]: .NET Core 3.1

Comment (RussKie) [reply GitCommands/Settings/Setting.cs:183]: https://docs.microsoft.com/en-us/dotnet/api/system.enum.tryparse?view=netframework-4.6.1

Comment (ivangrek) [reply GitCommands/Settings/Setting.cs:183]: where TEnum : struct;

image

**Comment by ivangrek** [comment]
During testing, I found out that it is impossible to save the space symbol.

`writer.WriteAttributeString("xml", "space", null, "preserve");`

Solves this issue.

If this is not possible. Perhaps it is worth pointing out and add some description?

You can test by setting the value.

`autocrlf = input`

File: GitCommands/Settings/Setting.cs [hunk 3]
```diff
@@ -173,13 +174,37 @@ private object GetValue(string name)
...
+                        switch (Type.GetTypeCode(underlyingType))
                         {
                             case TypeCode.String:
-                                return value;
+                                return (string)value;
+                            case TypeCode.Object:
+                                try
+                                {
+                                    return JsonConvert
+                                        .DeserializeObject<T>(value);
```
Comment (RussKie) [inline GitCommands/Settings/Setting.cs:188]: I must have totally zoned out when reviewed your previous PR, what do we serialize/deserialize to JSON? All the settings files I've seen were all XML and XML within XML...

Comment (ivangrek) [reply GitCommands/Settings/Setting.cs:188]: If value is object, now it is a structure, besides standard types.
This does not affect the xml structure.

Comment (ivangrek) [reply GitCommands/Settings/Setting.cs:188]: This also allows you to collect settings into one logical group.

Comment (RussKie) [reply GitCommands/Settings/Setting.cs:188]: I'm trying to establish - is it a new or an existing functionality?

**Comment by RussKie** [comment]
> During testing, I found out that it is impossible to save the space symbol.

IIRC, null, empty string or a space are all treated like unset value. In what usecase do you feel we need to persist a space?

File: GitCommands/Settings/Setting.cs (hunk 3 above)
Comment (ivangrek) [reply GitCommands/Settings/Setting.cs:188]: Fixed convertation for simple types. Relatively new.

**Comment by ivangrek** [comment]
> IIRC, null, empty string or a space are all treated like unset value. In what usecase do you feel we need to persist a space?

I see the space symbol as a value from a theoretical point of view. Ok I remove this.

**Comment by RussKie** [comment]
> I see the space symbol as a value from a theoretical point of view. Ok I remove this.

Right. In this case let's remove it until we have a real usecase where we need this.
It may worth adding a test that fails, and thus document this behaviour.

**Comment by ivangrek** [comment]
VS allows to store space symbols. 😄 

The test exists. When I delete it will fail.

**Comment by ivangrek** [comment]
image

For char '  ' also.

I'll have to remove them for the build to work.

File: GitCommands/Settings/Setting.cs (hunk 3 above)
Comment (ivangrek) [reply GitCommands/Settings/Setting.cs:188]: For Int, Byte, Float, Enum... changed to use type converter

**Review by RussKie — APPROVED** [review]
I'm going to accept it since we need to fix the bug.

But in the near future I'd like to revisit JSON serialization, which I understand is new. The Settings are on the hot path, since they are used quite liberally throughout the app.
Loading and unloading settings also affects how quickly the Settings dialog opens up too (and it is very slow as is).

I don't think we require persistence of objects right now, we generally persist strings and integral types. There are few scenarios where we persist collections, but those are persisted as XML separately and then saved as strings.
