### PR TITLE
fix(FileViewer): Avoid crash on animated image file

### LINKED ISSUE #12269: [NBug] A generic error occurred in GDI+.
### Environment

- Git Extensions 5.2.1.18061
- Build 0d74cfdc312df90114a0cf8d6c8a30ca4213e2ff
- Git 2.48.1.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.13
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.SelectActiveFrame(FrameDimension dimension, Int32 frameIndex)
   at System.Drawing.ImageAnimator.ImageInfo.UpdateFrame()
   at System.Drawing.ImageAnimator.UpdateFrames(Image image)
   at System.Windows.Forms.PictureBox.OnPaint(PaintEventArgs pe)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### Steps to reproduce

Try to checkin a gif-animation with transparent background.

### Did this work in previous version of GitExtensions?

Not sure.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #12269

## Proposed changes

FileViewer: Render only the first frame of an animated image in order to avoid exception in `PictureBox.WndProc` 

### Before

first frame, then red frame and cross

### After

first frame

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
Any example of a file that triggers this problem?

File: src/app/GitUI/Editor/FileViewer.cs [hunk 1]
```diff
@@ -1201,6 +1202,16 @@ private Task ViewItemAsync(string fileName, bool isSubmodule, Func<Image?> getIm
                                     return;
                                 }
 
+                                if (image.FrameDimensionsList.Length > 0)
+                                {
+                                    FrameDimension frameDimension = new(image.FrameDimensionsList[0]);
+                                    if (image.GetFrameCount(frameDimension) > 1)
+                                    {
+                                        image.SelectActiveFrame(frameDimension, 0);
+                                        image = new Bitmap(image);
```
Comment (RussKie) [inline src/app/GitUI/Editor/FileViewer.cs:1211]: I suspect we might be leaking a handle here...

**Review by RussKie — COMMENTED** [review]
Is it possible to add a test for this?

**Comment by mstv** [comment]
> Is it possible to add a test for this?

This would require integration testing. Integration test cases are too expensive and too difficult to setup stably. It is not worth IMO, specifically for this workaround for a bug in the platform, which the debugger even cannot catch.

**Review by gerhardol — COMMENTED** [review]
+1 have not run
