### PR TITLE
correctly detect/handle script options

### LINKED ISSUE #6285: NRE on script hotkey unless the revision grid has the focus
## Current behaviour

A NullReferenceException is thrown when the hotkey of a script is hit while the Revision Grid is not focused.

## Expected behaviour

No exception, no hard exit.

## Steps to reproduce

- assign a hotkey to a script
- focus something else than the Revision Grid, e.g. the Diff files list or the Commit Info
- hit the assigned hotkey

## Screenshots

script hotkeys

## Did this work in previous version of GitExtensions

Yes, partially: Both 2.51.05 and 3.0.0.4433 show an explanation:
grafik

*Not* caused by the appreciated PR # 6219 crypto-rsa/5834-skip-grid-refresh-after-navigational-script.

## Environment

- Git Extensions 3.1.0
- Build 5e825a186d8ea793be4c3bff9893ab56b158700b
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

## Diagnostics

```
   at GitUI.Script.ScriptOptionsParser.ParseScriptArguments(String argument, String option, IWin32Window owner, RevisionGridControl revisionGrid, IGitModule module, IReadOnlyList`1 allSelectedRevisions, IList`1& selectedTags, IList`1& selectedBranches, IList`1& selectedLocalBranches, IList`1& selectedRemoteBranches, IList`1& selectedRemotes, GitRevision selectedRevision, IList`1& currentTags, IList`1& currentBranches, IList`1& currentLocalBranches, IList`1& currentRemoteBranches, GitRevision currentRevision, String currentRemote) in F:\Build\gitextensions\GitUI\Script\ScriptOptionsParser.cs:line 351
   at GitUI.Script.ScriptOptionsParser.Parse(String argument, IGitModule module, IWin32Window owner, RevisionGridControl revisionGrid) in F:\Build\gitextensions\GitUI\Script\ScriptOptionsParser.cs:line 118
   at GitUI.Script.ScriptRunner.RunScript(IWin32Window owner, GitModule module, ScriptInfo scriptInfo, IGitUICommands uiCommands, RevisionGridControl revisionGrid) in F:\Build\gitextensions\GitUI\Script\ScriptRunner.cs:line 83
   at GitUI.Script.ScriptRunner.ExecuteScriptCommand(IWin32Window owner, GitModule module, Int32 command, IGitUICommands uiCommands, RevisionGridControl revisionGrid) in F:\Build\gitextensions\GitUI\Script\ScriptRunner.cs:line 19
   at GitUI.GitModuleForm.ExecuteCommand(Int32 command) in F:\Build\gitextensions\GitUI\GitModuleForm.cs:line 69
   at GitUI.CommandsDialogs.FormBrowse.ExecuteCommand(Int32 cmd) in F:\Build\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 2205
   at ResourceManager.GitExtensionsFormBase.ProcessCmdKey(Message& msg, Keys keyData) in F:\Build\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 52
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData) in F:\Build\gitextensions\ResourceManager\GitExtensionsControl.cs:line 90
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

### PR DESCRIPTION
**Pull request by mstv**
Fixes #6285

## Proposed changes

- resolve regression introduced by 1b8bb93c7121cd291a17303edfdd313c8edb9f88
  by correctly detecting script options starting with "s" again
  The regression was a NRE instead of the message (see screenshot).
- bugfix: The script options {cHash}, {cMessage}, {cAuthor}, {cCommitter}, {cAuthorDate}, {cCommitDate} did not work due to currentRevision being null when the script was not run from RevisionGridControl.

### Before

before 1b8bb93c7121cd291a17303edfdd313c8edb9f88
grafik

since 1b8bb93c7121cd291a17303edfdd313c8edb9f88
NRE 

### After

messagebox if the RevisionGrid is not focused

## Test methodology 

- manual

## Test environment(s) 

- Git Extensions 3.1.0
- Build ca548259cc4cbee4b99ae6724a75345e57ab023c
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
Further improvements and NUnit tests have been prepared in #6491, which has to wait for another huge PR.

File: GitUI/Script/ScriptOptionsParser.cs [hunk 1]
```diff
@@ -191,6 +191,7 @@ private static string AskToSpecify(IEnumerable<string> options, RevisionGridCont
                 if (revisionGrid == null)
                 {
                     var currentRevisionGuid = module.GetCurrentCheckout();
+                    currentRevision = new GitRevision(currentRevisionGuid);
```
Comment (RussKie) [inline GitUI/Script/ScriptOptionsParser.cs]: Why is this needed?

File: GitUI/Script/ScriptRunner.cs [hunk 2]
```diff
@@ -57,7 +57,7 @@ public static CommandStatus RunScript(IWin32Window owner, GitModule module, stri
                     continue;
                 }
 
-                if (!option.StartsWith("{s"))
+                if (!option.StartsWith("s"))
```
Comment (RussKie) [inline GitUI/Script/ScriptRunner.cs]: Is there a test we could add?

File: GitUI/Script/ScriptOptionsParser.cs (hunk 1 above)
Comment (mstv) [reply GitUI/Script/ScriptOptionsParser.cs]: > bugfix: The script options {cHash}, {cMessage}, {cAuthor}, {cCommitter}, {cAuthorDate}, {cCommitDate} did not work due to currentRevision being null when the script was not run from RevisionGridControl.

Before these script options have been added, all the existing options options starting with "c" depended on the current refs not on the commit itself.

File: GitUI/Script/ScriptRunner.cs (hunk 2 above)
Comment (mstv) [reply GitUI/Script/ScriptRunner.cs]: see my short comment https://github.com/gitextensions/gitextensions/pull/6502#issuecomment-485584736 above and https://github.com/gitextensions/gitextensions/pull/6491#issuecomment-485569990

**Comment by RussKie** [comment]
Thank you
