### PR TITLE
#8684 Avatars are misaligned in blame form

### LINKED ISSUE #8684: Avatars in blame viewer are misaligned
## Current behaviour

When blaming a file with view avatars enabled, avatars are misaligned with lines of code.

## Expected behaviour

Should be aligned.

## Steps to reproduce

Make sure you enabled the feature to show avatar when blaming.
Blame a file with lots of lines and lots of modifications (here: `GitExtensions` repo, commit: `67f5fd9197ef5055c778510aecd6ece29cff8fe4`, file: `GitExtensions.sln` )
Go to the end of the file
Avatars are misaligned with lines of code.

## Screenshots

image

## Did this work in previous version of GitExtensions

No idea.

## Environment

- Git Extensions 33.33.33
- Build 30b8505c8991c5a9e3c06016c34f9d501c6d856e
- Git 2.22.0.windows.1 (recommended: 2.28.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

## Diagnostics

None

### PR DESCRIPTION
**Pull request by bansan85**
The font used to compute height of image could be out of date
if font of text view is changed by user preferences.

Fixes #8684

## Proposed changes

- The height of avatar is computed at startup. But the height of the textview can be updated by user preferences. So both size could be different.

In my case, font size used by blame author margin is "Consolas 10" and text view is "Consolas 9,75". The tiny difference of size explains why it affects randomly dpi windows parameter.

### Before

image

### After

image

## Test methodology 

None :/

## Test environment(s) 

- Git Extensions 33.33.33
- Build 3c75c4b696788cf573c856795dca61485c351ad5
- Git 2.30.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — APPROVED** [review]
Good catch.
Have not run it myself.

File: GitUI/Editor/BlameAuthorMargin.cs [hunk 1]
```diff
@@ -15,31 +15,26 @@ public class BlameAuthorMargin : AbstractMargin
...
-            _lineHeight = GetFontHeight(textArea.Font);
             _backgroundColor = SystemColors.Window;
-            Width = _lineHeight + AgeBucketMarkerWidth + DpiUtil.Scale(2);
         }
 
-        public override int Width { get; }
-        public override bool IsVisible => _isVisible;
-
-        private static int GetFontHeight(Font font)
+        public override int Width
```
Comment (RussKie) [inline GitUI/Editor/BlameAuthorMargin.cs:28]:
```suggestion
        public int LineHeight => textArea.TextView.FontHeight;
        public override int Width => LineHeight + AgeBucketMarkerWidth + DpiUtil.Scale(2);
```

File: GitUI/Editor/BlameAuthorMargin.cs [hunk 2]
```diff
@@ -84,9 +79,9 @@ public override void Paint(Graphics g, Rectangle rect)
             }
 
             var verticalOffset = textArea.VirtualTop.Y;
-            var lineStart = verticalOffset / _lineHeight;
-            var negativeOffset = (lineStart * _lineHeight) - verticalOffset;
-            var lineCount = (int)Math.Ceiling((double)(rect.Height - negativeOffset) / _lineHeight);
+            var lineStart = verticalOffset / textArea.TextView.FontHeight;
+            var negativeOffset = (lineStart * textArea.TextView.FontHeight) - verticalOffset;
+            var lineCount = (int)Math.Ceiling((double)(rect.Height - negativeOffset) / textArea.TextView.FontHeight);
```
Comment (RussKie) [inline GitUI/Editor/BlameAuthorMargin.cs:84]:
```suggestion
            var lineStart = verticalOffset / LineHeight;
            var negativeOffset = (lineStart * LineHeight) - verticalOffset;
            var lineCount = (int)Math.Ceiling((double)(rect.Height - negativeOffset) / LineHeight);
```

File: GitUI/Editor/BlameAuthorMargin.cs [hunk 3]
```diff
@@ -95,8 +90,8 @@ public override void Paint(Graphics g, Rectangle rect)
                     break;
                 }
 
-                int y = negativeOffset + (i * _lineHeight);
-                g.FillRectangle(_brushs[_blameLines[lineStart + i].AgeBucketIndex], 0, y, AgeBucketMarkerWidth, _lineHeight);
+                int y = negativeOffset + (i * textArea.TextView.FontHeight);
+                g.FillRectangle(_brushs[_blameLines[lineStart + i].AgeBucketIndex], 0, y, AgeBucketMarkerWidth, textArea.TextView.FontHeight);
```
Comment (RussKie) [inline GitUI/Editor/BlameAuthorMargin.cs:94]:
```suggestion
                int y = negativeOffset + (i * LineHeight);
                g.FillRectangle(_brushs[_blameLines[lineStart + i].AgeBucketIndex], 0, y, AgeBucketMarkerWidth, LineHeight);
```

**Review by RussKie — COMMENTED** [review]
Few suggestions

**Comment by bansan85** [comment]
@RussKie you're right, it's cleaner.

**Review by gerhardol — COMMENTED** [review]
+1
Not run, only overview review

**Comment by RussKie** [comment]
LGTM
Have you checked it in different scaling factors? 150%? 200%?

**Comment by pmiossec** [comment]
@bansan85 Thank you for this fix for something I did wrongly but was unable to fix. Merci!

@ivangrek You that was able to reproduce the problem, could you validate the fix?

**Comment by bansan85** [comment]
Please find enclosed some example for 100%, 125%, 150%, 175% and 238% (a custom random value).
They all work.

100%


125%


150%


175%


238%

**Review by ivangrek — APPROVED** [review]
### Before
image

### After

image

**Comment by RussKie** [comment]
Thank you!

**Comment by RussKie** [comment]
Please send a matching PR to the release/3.5 branch. I can't cherrypick it due to conflicts.

**Comment by bansan85** [comment]
Sure. I will do it a bit later.
