### PR TITLE
Avoid NRE in CommitAutoCompleteProvider

### LINKED ISSUE #7473: NRE testing CommitAutoCompleteProvider
## Current behaviour

```
System.Reflection.Assembly.GetEntryAssembly(...) returned null.

System.NullReferenceException
  HResult=0x80004003
  Message=Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
  Source=GitUI
  StackTrace:
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.ReadOrInitializeAutoCompleteRegexes() in F:\Build\gitextensions\GitUI\AutoCompletion\CommitAutoCompleteProvider.cs:line 84
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.ParseRegexes() in F:\Build\gitextensions\GitUI\AutoCompletion\CommitAutoCompleteProvider.cs:line 98
   at System.Lazy`1.CreateValue()
```

## Expected behaviour

no NRE

## Steps to reproduce

_Debug_ tests, especially `FormCommitTests`.

## Did this work in previous version of GitExtensions

probably no

## Environment

- Git Extensions 3.3.0
- Build 69763de058580d0dbf84be9a2d725b1719f607c6
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

## Diagnostics

```
	GitUI.dll!GitUI.AutoCompletion.CommitAutoCompleteProvider.ReadOrInitializeAutoCompleteRegexes() Line 84	C#
 	GitUI.dll!GitUI.AutoCompletion.CommitAutoCompleteProvider.ParseRegexes() Line 98	C#
 	[External Code]	
 	GitUI.dll!GitUI.AutoCompletion.CommitAutoCompleteProvider.GetRegexForExtension(string extension) Line 72	C#
 	GitUI.dll!GitUI.AutoCompletion.CommitAutoCompleteProvider.GetAutoCompleteWordsAsync(System.Threading.CancellationToken cancellationToken) Line 38	C#
 	[Resuming Async Method]	
 	[External Code]	
 	GitCommands.dll!GitCommands.ExecutableExtensions.GetOutputAsync(GitUIPluginInterfaces.IExecutable executable, GitCommands.ArgumentString arguments, byte[] input, System.Text.Encoding outputEncoding, GitCommands.CommandCache cache, bool stripAnsiEscapeCodes) Line 151	C#
 	[Resuming Async Method]	
 	[External Code]	
 	GitCommands.dll!GitCommands.Executable.ProcessWrapper.OnProcessExit(object sender, System.EventArgs eventArgs) Line 116	C#
 	[External Code]	
 	[Async Call Stack]	
 	[External Code]	
 	[Async] GitUI.dll!GitUI.SpellChecker.EditNetSpell.InitializeAutoCompleteWordsTask.AnonymousMethod__109_0() Line 870	C#
 	[External Code]	
```

### PR DESCRIPTION
**Pull request by mstv**
Fixes #7473

## Proposed changes

- Avoid NRE in CommitAutoCompleteProvider

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/AutoCompletion/CommitAutoCompleteProvider.cs [hunk 1]
```diff
@@ -81,7 +81,7 @@ private static IEnumerable<string> ReadOrInitializeAutoCompleteRegexes()
                 return File.ReadLines(path);
             }
 
-            Stream s = Assembly.GetEntryAssembly().GetManifestResourceStream("GitExtensions.AutoCompleteRegexes.txt");
+            Stream s = Assembly.GetEntryAssembly()?.GetManifestResourceStream("GitExtensions.AutoCompleteRegexes.txt");
             if (s == null)
             {
                 throw new NotImplementedException("Please add AutoCompleteRegexes.txt file into .csproj");
```
Comment (sharwell) [inline GitUI/AutoCompletion/CommitAutoCompleteProvider.cs]: We avoid a `NullReferenceException`, but then we immediately throw `NotImplementedException`. Was that intended?

Comment (mstv) [reply GitUI/AutoCompletion/CommitAutoCompleteProvider.cs]: Yes, it is intended because it gives a more clear information what failed.
As a positive side effect, the debugger does not stop on `NotImplementedException` by default when debugging tests.
Though it is only a workaround.
