### PR TITLE
Remove Brittle Version Replace

### LINKED ISSUE #10345: Brittle Version replace
### Environment

- Git Extensions 33.33.33
- Build fa210ff8484eef4ef713e7dd8c706df9a0c08759
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

https://github.com/gitextensions/gitextensions/blob/fa210ff8484eef4ef713e7dd8c706df9a0c08759/GitCommands/Git/GitVersion.cs#L175-L179

This is brittle and if git ever releases more than that many versions.  Better fix is to do a regex replacement.  

image
```regex
\.windows\.\d+
```

### Steps to reproduce

Assume a git version of 2.40.1.windows.4

### Did this work in previous version of GitExtensions?

No.  

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by vbjay**
Fixes #10345

## Proposed changes

- ~~Use regex to replace windows.#~~ Remove regex and just return Full.  See https://github.com/gitextensions/gitextensions/pull/10346#discussion_r1034426681

## Test methodology 

- Validated version replaced correctly

## Test environment(s) 

- GIT 
- Windows 

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

File: GitCommands/Git/GitVersion.cs [hunk 1]
```diff
@@ -172,11 +173,7 @@ private static int Compare(GitVersion left, GitVersion right)
 
         public override string ToString()
         {
-            return Full
-                .Replace(".windows.0", "")
-                .Replace(".windows.1", "")
-                .Replace(".windows.2", "")
-                .Replace(".windows.3", "");
+            return Regex.Replace(Full, @"\.windows\.\d+", "");
```
Comment (gerhardol) [inline GitCommands/Git/GitVersion.cs:176]: This cleans the suffix in display. "windows" could be changed too, is different in wsl and wine I suppose.
An alternative could be to just display the version like below, but that will clean -rc etc
```
            return Regex.Replace(Full, @"(\d+(\.\d+)+)", "$1");
```

Why not display this part of the version instead, no replace at all?

**Review by gerhardol — COMMENTED** [review]
+1

File: GitCommands/Git/GitVersion.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Git/GitVersion.cs:176]: @vbjay ?

Comment (vbjay) [reply GitCommands/Git/GitVersion.cs:176]: I am not trying to alter functionality here.  The replace is being used for

https://github.com/gitextensions/gitextensions/blob/78092cb9d74b3068803d8b03d986f573553f0a83/GitUI/Infrastructure/Telemetry/AppEnvironmentTelemetryInitializer.cs#L26

I happened to catch the brittle case of a potential running out of numbers and it not being replaced.

Comment (gerhardol) [reply GitCommands/Git/GitVersion.cs:176]: There is no harm in Telemetry tracking the full name, especially if alternative Git implementations are used.
@RussKie ?

Comment (gerhardol) [reply GitCommands/Git/GitVersion.cs:176]: image

Comment (vbjay) [reply GitCommands/Git/GitVersion.cs:176]: Ok. I'll switch it to just use full.

Comment (RussKie) [reply GitCommands/Git/GitVersion.cs:176]: > There is no harm in Telemetry tracking the full name, especially if alternative Git implementations are used.

I _personally_ see no issues with that.

**Comment by RussKie** [comment]
@msftbot merge if @gerhardol approves

**Comment by RussKie** [comment]
@gerhardol a friendly nudge

File: GitCommands/Git/GitVersion.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Git/GitVersion.cs:176]: > a friendly nudge

Last comment from @vbjay was to change to remove the clean, not done.

File: GitCommands/Git/GitVersion.cs [hunk 2]
```diff
@@ -174,11 +174,7 @@ private static int Compare(GitVersion left, GitVersion right)
 
         public override string ToString()
         {
-            return Full
-                .Replace(".windows.0", "")
-                .Replace(".windows.1", "")
-                .Replace(".windows.2", "")
-                .Replace(".windows.3", "");
+            return Full;
```
Comment (mstv) [inline GitCommands/Git/GitVersion.cs:177]: The regex has got lost. 🤔

Comment (vbjay) [reply GitCommands/Git/GitVersion.cs:177]: Read previous comments first.

File: GitCommands/Git/GitVersion.cs (hunk 1 above)
Comment (vbjay) [reply GitCommands/Git/GitVersion.cs]: Updated.

**Review by mstv — APPROVED** [review]
Just update the PR title and description, please, @vbjay.

**Review by gerhardol — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you
