### PR TITLE
Winstore and msysgit

### LINKED ISSUE #2472: 2.48 git-credential-winstore installation issue
I'm not 100% sure if this is a duplicate of #2467 but a friend of mine made some interesting observations when installting GitExtensions on a clean VM (no other GitExtensions version installed before).

git-credential-winstore does not work after the installation because of:

* The installer installs git-credential-winstore *before* MSysGit  -> git-credential-winstore cannot find the git.exe!
* Furthermore it looks for git.exe in the PATH variable -> if the user chooses to not put git.exe into the PATH during instalaltion, it will never find git.exe, even if installed after MSysGit

### LINKED ISSUE #3058: Switch to new Git Credential Manager
git-credential-winstore is no longer actively maintained so it might be a good idea to switch to the new Git Credential Manager (see http://blogs.msdn.com/b/visualstudioalm/archive/2015/12/08/announcing-the-git-credential-manager-for-windows-1-0.aspx).

### LINKED ISSUE #3140: How to fix the Windows Git Extensions to save https git username and password
--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1
I've looked at a number of sites to try to figure out how to have git store my https git username and password.  

[credential]
	helper = wincred
OR
[credential]
	helper = !'C:\\Users\\<<username>>\\AppData\\Roaming\\GitCredStore\\git-credential-winstore.exe'

When I put either of the following in my .gitconfig file, I get the error
fatal:  repository'https://github.com/<<repository>>" not found

Any ideas?

### PR DESCRIPTION
**Pull request by karyon**
See commit messages.

fixes #3058, closes #3140, closes #2472

### CODE REVIEW

File: GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs [hunk 1]
```diff
@@ -27,15 +26,13 @@ public static SettingsPageReference GetPageReference()
...
         }
-        private ConfigFileSettings GlobalConfigFileSettings { get { return CommonLogic.ConfigFileSettingsSet.GlobalSettings; } }
 
         protected override void SettingsToPage()
         {
             PlinkPath.Text = AppSettings.Plink;
             PuttygenPath.Text = AppSettings.Puttygen;
             PageantPath.Text = AppSettings.Pageant;
             AutostartPageant.Checked = AppSettings.AutoStartPageant;
-            GitCredPath.Text = GlobalConfigFileSettings.GetValue("credential.helper");
```
Comment (KindDragon) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs]: Maybe we should display warning if credential helper not installed?
Without it HTTPS wouldn't work
I don't know what SuggestGitCred should do after removing git-credential-winstore from installer

Comment (karyon) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs]: why wouldn't https work without it? and i don't quite understand, i removed SuggestGitCred...

File: Setup/UI/RequiredSoftwareDlg.wxs [hunk 2]
```diff
@@ -21,11 +21,7 @@
         <Control Id="KDiffTitle" Type="Text" Height="12" Width="200" X="15" Y="111" Text="{\WixUI_Font_Title}KDiff3 32bit 0.9.97" />
         <Control Id="KDiffDescription" Type="Text" Height="44" Width="238" X="25" Y="127" Text="KDiff is a diff/merge tool that Git Extensions calls upon when it encounters a merge conflict. If you already have a diff/merge tool that works with Git then you don't need to install this." />
         <Control Id="KDiffCheckBox" Type="CheckBox" Height="20" Width="78" X="274" Y="129" Text="Install KDiff" Property="INSTALLKDIFF3" CheckBoxValue="1" />
-
-        <Control Id="GitCredentialWinStoreTitle" Type="Text" Height="12" Width="200" X="15" Y="176" Text="{\WixUI_Font_Title}Windows Credential Store for Git 1.4" />
```
Comment (KindDragon) [inline Setup/UI/RequiredSoftwareDlg.wxs]: You should realign Git and KDiff controls

File: GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs (hunk 1 above)
Comment (KindDragon) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs]: You right, recently added GitExtSshAskPass should show window that ask password

File: Setup/UI/RequiredSoftwareDlg.wxs (hunk 2 above)
Comment (karyon) [inline Setup/UI/RequiredSoftwareDlg.wxs]: i'm sorry, from the git history i couldn't see what i should realign, the diffs are pretty hard to read. are there any tools you use for editing wxs files?

Comment (KindDragon) [inline Setup/UI/RequiredSoftwareDlg.wxs]: Just plain text editor

It should look like
install2 1

After your changes it would be like
test

Comment (KindDragon) [inline Setup/UI/RequiredSoftwareDlg.wxs]: Set Git and KDiff controls coordinates to those that were before commit
https://github.com/karyon/gitextensions/commit/ef379796a25ebea1b10abad13f87e70689840ff4#diff-beae95e27bbb86fbe94b3ea4fb4041f2

**Comment by karyon** [comment]
i copied the exact values from that diff, but can't test it atm as i can't build the installer.

File: GitCommands/Git/GitVersion.cs [hunk 3]
```diff
@@ -176,7 +176,11 @@ private static int Compare(GitVersion left, GitVersion right)
 
         public override string ToString()
         {
-            return Full.Replace(".msysgit.0", "").Replace(".msysgit.1", "");
+            return Full
+                .Replace(".msysgit.0", "")
+                .Replace(".msysgit.1", "")
+                .Replace(".windows.0", "")
+                .Replace(".windows.1", "");
```
Comment (linquize) [inline GitCommands/Git/GitVersion.cs]: Handle only  `.windows.0` and `.windows.1`? There may be more than 2 very minor versions.

Comment (karyon) [inline GitCommands/Git/GitVersion.cs]: you're right, i must admit i didn't feel like making the code more flexible than it was before.
