### PR TITLE
Reflect the fact that the diff is reloaded in the form state.

### LINKED ISSUE #5570: Not able to stage selected lines twice in a row.
**Do you want to request a *feature* or report a *bug*?**

:bug:

**What is the current behavior?**

After staging selected lines once, I can not stage other lines.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Go to the commit dialog. 
2. Stage a line.
3. Try to stage another line.

**What is the expected behavior?**

Stage selected lines more than once.

**Environment you encounter the issue:**

- GitExtensions version: 59094d76371583ccaf2b789a771f42da85a863e6

**Did this work in previous version of GitExtensions (which)?**
Yes, 2.5x

### PR DESCRIPTION
**Pull request by jbialobr**
Fixes #5570.

### CODE REVIEW

File: GitUI/CommandsDialogs/FormCommit.cs [hunk 1]
```diff
@@ -1089,7 +1089,11 @@ private void ShowChanges(GitItemStatus item, bool staged)
                 return;
             }
 
-            SetSelectedDiff(item, staged);
+            ThreadHelper.JoinableTaskFactory.RunAsync(async () =>
+            {
+                await SetSelectedDiffAsync(item, staged);
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormCommit.cs]: Do we need to call `await this.SwitchToMainThreadAsync();` before?

Comment (jbialobr) [reply GitUI/CommandsDialogs/FormCommit.cs]: I see no need for this.

**Comment by Khaon** [comment]
Thank you, was a pain in the a** ;)
