### PR TITLE
Ignore failure getting `Process.Id` when opening URL

### LINKED ISSUE #9169: BugReporter: InvalidOperationException
## Current behaviour

The `BugReporter` fails with an exception if `Microsoft Edge 41.16299.248.0` is the default browser:
```
GitCommands.ExternalOperationException: Diesem Objekt ist kein Prozess zugeordnet. ---> System.InvalidOperationException: Diesem Objekt ist kein Prozess zugeordnet.
   bei System.Diagnostics.Process.EnsureState(State state)
   bei System.Diagnostics.Process.EnsureState(State state)
   bei System.Diagnostics.Process.get_Id()
   bei GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute)
   bei GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute)
   bei BugReporter.BugReportForm.SendAndQuitButton_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Expected behaviour

bug reporting works without crashing itself

## Steps to reproduce

- set the old `Edge` as default browser
- run
```
BugReporter.exe PFNlcmlhbGl6YWJsZUV4Y2VwdGlvbiB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4bWxuczp4c2Q9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIj4NCiAgPEV4dGVuZGVkSW5mb3JtYXRpb24+DQogICAgPENvbW1hbmQ+Jmx0O2NvbW1hbmQmZ3Q7PC9Db21tYW5kPg0KICAgIDxBcmd1bWVudHM+Jmx0O2FyZ3VtZW50cyZndDs8L0FyZ3VtZW50cz4NCiAgICA8V29ya2luZ0RpcmVjdG9yeT4mbHQ7d2RpciZndDs8L1dvcmtpbmdEaXJlY3Rvcnk+DQogICAgPEhSZXN1bHQ+LTIxNDYyMzMwODg8L0hSZXN1bHQ+DQogIDwvRXh0ZW5kZWRJbmZvcm1hdGlvbj4NCiAgPElubmVyRXhjZXB0aW9uPg0KICAgIDxFeHRlbmRlZEluZm9ybWF0aW9uPg0KICAgICAgPEhSZXN1bHQ+LTIxNDYyMzMwODg8L0hSZXN1bHQ+DQogICAgPC9FeHRlbmRlZEluZm9ybWF0aW9uPg0KICAgIDxJbm5lckV4Y2VwdGlvbj4NCiAgICAgIDxFeHRlbmRlZEluZm9ybWF0aW9uPg0KICAgICAgICA8SFJlc3VsdD4tMjE0NzM1MjU1ODwvSFJlc3VsdD4NCiAgICAgIDwvRXh0ZW5kZWRJbmZvcm1hdGlvbj4NCiAgICAgIDxNZXNzYWdlPkJhbmchPC9NZXNzYWdlPg0KICAgICAgPFR5cGU+U3lzdGVtLkRpdmlkZUJ5WmVyb0V4Y2VwdGlvbjwvVHlwZT4NCiAgICA8L0lubmVyRXhjZXB0aW9uPg0KICAgIDxNZXNzYWdlPlByb2Nlc3MgZXhpdGVkIHdpdGggZmFpbHVyZSBjb2RlIC0xPC9NZXNzYWdlPg0KICAgIDxUeXBlPlN5c3RlbS5FeGNlcHRpb248L1R5cGU+DQogIDwvSW5uZXJFeGNlcHRpb24+DQogIDxNZXNzYWdlPlByb2Nlc3MgZXhpdGVkIHdpdGggZmFpbHVyZSBjb2RlIC0xPC9NZXNzYWdlPg0KICA8U291cmNlPkdpdENvbW1hbmRzPC9Tb3VyY2U+DQogIDxTdGFja1RyYWNlPiAgIGF0IEdpdENvbW1hbmRzLkV4ZWN1dGFibGUuUHJvY2Vzc1dyYXBwZXIuT25Qcm9jZXNzRXhpdChPYmplY3Qgc2VuZGVyLCBFdmVudEFyZ3MgZXZlbnRBcmdzKQ0KICAgYXQgU3lzdGVtLkRpYWdub3N0aWNzLlByb2Nlc3MuT25FeGl0ZWQoKQ0KICAgYXQgU3lzdGVtLkRpYWdub3N0aWNzLlByb2Nlc3MuUmFpc2VPbkV4aXRlZCgpDQogICBhdCBTeXN0ZW0uRGlhZ25vc3RpY3MuUHJvY2Vzcy5Db21wbGV0aW9uQ2FsbGJhY2soT2JqZWN0IGNvbnRleHQsIEJvb2xlYW4gd2FzU2lnbmFsZWQpDQogICBhdCBTeXN0ZW0uVGhyZWFkaW5nLl9UaHJlYWRQb29sV2FpdE9yVGltZXJDYWxsYmFjay5XYWl0T3JUaW1lckNhbGxiYWNrX0NvbnRleHQoT2JqZWN0IHN0YXRlLCBCb29sZWFuIHRpbWVkT3V0KQ0KICAgYXQgU3lzdGVtLlRocmVhZGluZy5fVGhyZWFkUG9vbFdhaXRPclRpbWVyQ2FsbGJhY2suV2FpdE9yVGltZXJDYWxsYmFja19Db250ZXh0X2YoT2JqZWN0IHN0YXRlKQ0KICAgYXQgU3lzdGVtLlRocmVhZGluZy5FeGVjdXRpb25Db250ZXh0LlJ1bkludGVybmFsKEV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dCwgQ29udGV4dENhbGxiYWNrIGNhbGxiYWNrLCBPYmplY3Qgc3RhdGUsIEJvb2xlYW4gcHJlc2VydmVTeW5jQ3R4KQ0KICAgYXQgU3lzdGVtLlRocmVhZGluZy5FeGVjdXRpb25Db250ZXh0LlJ1bihFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQsIENvbnRleHRDYWxsYmFjayBjYWxsYmFjaywgT2JqZWN0IHN0YXRlLCBCb29sZWFuIHByZXNlcnZlU3luY0N0eCkNCiAgIGF0IFN5c3RlbS5UaHJlYWRpbmcuX1RocmVhZFBvb2xXYWl0T3JUaW1lckNhbGxiYWNrLlBlcmZvcm1XYWl0T3JUaW1lckNhbGxiYWNrKE9iamVjdCBzdGF0ZSwgQm9vbGVhbiB0aW1lZE91dCk8L1N0YWNrVHJhY2U+DQogIDxUYXJnZXRTaXRlPlZvaWQgT25Qcm9jZXNzRXhpdChTeXN0ZW0uT2JqZWN0LCBTeXN0ZW0uRXZlbnRBcmdzKSBAIEdpdENvbW1hbmRzLkV4ZWN1dGFibGUrUHJvY2Vzc1dyYXBwZXI8L1RhcmdldFNpdGU+DQogIDxUeXBlPkdpdEV4dFV0aWxzLkV4dGVybmFsT3BlcmF0aW9uRXhjZXB0aW9uPC9UeXBlPg0KPC9TZXJpYWxpemFibGVFeGNlcHRpb24+
```
- enter a dummy description
- `Send and Quit`

## Environment

- #9167
- Microsoft Edge 41.16299.248.0
- Git Extensions 33.33.33
- Build fec693532c9cc0e23e0e91c841b9a343c64f86c2
- Git 2.31.1.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.7.2633.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by mstv**
Fixes #9169

## Proposed changes

- Ignore failure getting `Process.Id` after successful `Process.Start` if `useShellExecute: true`

### After

CommandLog:

CommandLog

## Test methodology 

- manual (see #9169)

## Test environment(s) 

- Git Extensions 33.33.33
- Build 8fbc9d3405af49bf27f1421b41874a1468018e69
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — COMMENTED** [review]
Reading [the docs](https://docs.microsoft.com/dotnet/api/system.diagnostics.process.id#exceptions), I think the correct fix would be to trap the exception here:
https://github.com/gitextensions/gitextensions/blob/f5c3f229b677a60195353dab0b39191f59cef668/GitCommands/Git/Executable.cs#L110

**Comment by mstv** [comment]
> I think the correct fix would be to trap the exception here.

I hesitated to do it here because there was no special handling in the code before adding `ExternalOperationException` - and no regarding crash reports.
We want a process to be started. Though for `useShellExecute: true`, it may be forwarded to another. I agree, this case should directly be handled here in `ProcessWrapper`.

File: GitCommands/Git/Executable.cs [hunk 1]
```diff
@@ -111,7 +111,15 @@ private sealed class ProcessWrapper : IProcess
...
                     _process.Start();
-                    _logOperation.SetProcessId(_process.Id);
+                    try
+                    {
+                        _logOperation.SetProcessId(_process.Id);
+                    }
+                    catch (InvalidOperationException ex) when (useShellExecute)
+                    {
+                        // _process.Start() has succeeded, ignore the failure getting the _process.Id
+                        _logOperation.LogProcessEnd(ex);
```
Comment (gerhardol) [inline GitCommands/Git/Executable.cs:121]: I assume that the actual exit will still update command and results?

**Review by gerhardol — COMMENTED** [review]
+1
This seems a better way than the original

**Review by RussKie — APPROVED** [review]

File: GitCommands/Git/Executable.cs (hunk 1 above)
Comment (mstv) [reply GitCommands/Git/Executable.cs:121]: > I assume that the actual exit will still update command and results?

The call is visible and - to my surprise - even with a duration (see screenshot in the PR description).
