### PR TITLE
Jenkins: Ignore build events for certain branches

### LINKED ISSUE #5054: Jenkins: limit builds based on branchnames
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
GE displays one build result pr commit only. Extending that is a separate enhancement.

Jenkins can start several builds for one event. Especially multibranch pipeline setups can start several builds on one commit. The normal build event trigger Git->Jenkins is a branch event, based on branch name. The action in a build is therefore normally dependent on the branch name too. A typical example is a master branch build vs a release branch build, may be on the same commit (you move the release branch to trigger release builds). Other special branches can be to trigger a special build on a commit when a submodule is changed, internally called "progression builds" at work. Such build events are interesting for the quality of the submodule changes, not for the current commit.

The Jenkins build plugin presents the latest build for a certain commit. There is no priority for separate branch events. (The initial implementation had such a priority order, but the code got complicated and "latest is best" was adopted instead.)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Reproducible in private environments.
builds.apache.org has public builds with multibranch pipeline, but no multiple events per commit what I can see.

**What is the expected behavior?**
The Jenkins plugin should allow for certain branch build events to be ignored, so the initial build event results can be displayed for interesting branches.

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
Jenkins multibranch pipeline support added in 2.51.

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #5054

Changes proposed in this pull request:
- Configureable ignore build events for certain branch names
 
Screenshots before and after (if PR changes UI):
n/a

What did I do to test the code and ensure quality:
- Manually - Jenkins setup with multiple build events for one branch required to see the benefits, but logging-log4net on builds.apache.org can be used to suppress certain branches.

Has been tested on (remove any that don't apply):
- Windows 7 and 10

### CODE REVIEW

File: Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs [hunk 1]
```diff
@@ -323,9 +328,26 @@ private BuildInfo CreateBuildInfo(JObject buildDescription)
             string testResults = string.Empty;
             foreach (var element in action)
             {
+                // Ignore build events for specified branches
```
Comment (jbialobr) [inline Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs]: This comment should go to the 336 line.
