### PR TITLE
Dashboard: Add ability to drag and drop a folder from Windows explorer to UserRe…

### LINKED ISSUE #6221: Drag and drop windows folder onto Extensions used to open that repo
## Current behaviour
For the 2.X releases, you could drag and drop a Windows folder from File Explorer onto a Git Extensions window, and it would open that folder as a repository (as if choosing that folder for "open repository")
With the recent 3.x release, that functionality seems to have been lost.

## Steps to reproduce
Open folder in windows.
Open Git Extensions (first main window)
Drag a subfolder from windows explorer window to Git Extensions

## Expected behavior
Expected: Open that folder like "Open repository" does.
Actual: Drag & drop folder displays the "not possible" cursor.

## Did this work in previous version of GitExtensions
Yes.
Many/most recent 2.x versions of GitExtensions

## Environment

- GitExtensions version: 3.00.00.4433
- GIT version: 2.20.1.windows.1
- OS version: MS Windows NT 10.017134.0
- .NET version: 4.7.3260.0

### PR DESCRIPTION
**Pull request by DmitryZhelnin**
…positoriesList inside the Dashboard form

Fixes #6221 

## Proposed changes

- User can drag and drop a folder with a git repo to the repositories list inside the Dashboard form to open that repository
- The code was taken from the version 2.51 of GitExtensions

## Screenshots 
dnd

## Test methodology 

- Manual testing

## Test environment(s) 

- Windows 7 SP1

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Please send your sign off to contributors.txt in a separate PR

File: GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs [hunk 1]
```diff
@@ -785,5 +791,53 @@ private void tsmiCategoryClear_Click(object sender, EventArgs e)
...
+                if (!string.IsNullOrEmpty(dir) && Directory.Exists(dir))
+                {
+                    GitModule module = new GitModule(dir);
+
+                    if (!module.IsValidGitWorkingDir())
+                    {
+                        DialogResult dialogResult = MessageBox.Show(this, _directoryIsNotAValidRepositoryOpenIt.Text,
+                            _directoryIsNotAValidRepositoryCaption.Text, MessageBoxButtons.YesNo,
+                            MessageBoxIcon.Exclamation, MessageBoxDefaultButton.Button2);
+                        if (dialogResult == DialogResult.No)
```
Comment (RussKie) [inline GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs]: Even if I click "yes", the folder doesn't get opened

Comment (RussKie) [reply GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs]: I think we should just show a message saying "Cannot open the folder" (heading) "Not a valid git repository" (message)

**Comment by DmitryZhelnin** [comment]
@RussKie I've made requested changes and created another PR ([#6259](https://github.com/gitextensions/gitextensions/pull/6259))

**Comment by DmitryZhelnin** [comment]
Force pushed again with signature

**Comment by RussKie** [comment]
We provide a further improvement, if a one or several folders are dropped into one of favourite sections (not recent) - those new folders (that contain git repos) would get added to the favourite category.

**Comment by DmitryZhelnin** [comment]
> 
> 
> +1
> 
> The d'n'd is constrained to a part of the dashboard and it could be improved, but I won't block because of it
> 6255-dnd

I did this on purpose to repeat the behaviour of previous versions.

**Comment by DmitryZhelnin** [comment]
> 
> 
> We provide a further improvement, if a one or several folders are dropped into one of favourite sections (not recent) - those new folders (that contain git repos) would get added to the favourite category.

By "favourite sections" you mean sections that user created by himself?

**Comment by RussKie** [comment]
> By "favourite sections" you mean sections that user created by himself?

Yes
image

**Comment by DmitryZhelnin** [comment]
> 
> 
> > By "favourite sections" you mean sections that user created by himself?
> 
> Yes

I think sometimes it can be hard to aim to the right section. Maybe we should open context menu when user d'n'd the folder(s) to the dashboard. something like
- Open
- Add to category
    - *list of categories*
    - Create new...

 Or left the default behaviour to open the repo and use some modifiers (like ctrl, or d'n'd by right mouse button) to open context menu. 
I think d'n'd by right mouse button is more preferable because Windows Explorer has the same behaviour.

**Comment by RussKie** [comment]
I like your thought process 👍

**Comment by RussKie** [comment]
Thank you
