### PR TITLE
Workaround ImageList transparent image regression introduced in .NET 8

### LINKED ISSUE #11506: Commit info tab image transparency back-color is broken after update to .NET 8
### Environment

- OS version: Windows 11
- .NET version: 6/8

### Issue description

This could be a regression in WinForms in .NET 8 (or 7 since we skipped it) but the icons in Commit Info tab headers are no longer transparent.. or maybe they are but a white background is painted behind them.

Before
image

Now
image

I've tried meddling with various properties on the `ImageList` and `TabPage` but to no avail.

### Steps to reproduce

Run eeaf3c13e644a15178686af70bf362547943daa6 and notice transparent icons
Run 291c6d1c3615e6bc67ea56bbe1beae78db823743 an notice white background color for the icons

### Did this work in previous version of GitExtensions?

Yes, in eeaf3c13e644a15178686af70bf362547943daa6

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mdonatas**
Fixes #11506

A root cause was found to be an incorrect setting of the image background during `ImageList` handle creation https://github.com/dotnet/winforms/issues/10462#issuecomment-1880068488

This also suggests a clear fix:

## Proposed changes

- Set ImageList background to a value used before this regression got introduced
- Add comment instructing to remove this workaround once the fix is implemented in .NET 9 (most likely) 

### Before

FormBrowse > Commit Info
image

FormFileHistory
image

### After

image
image

## Test methodology 

- Manually

## Test environment(s) 

- Windows 11

## Merge strategy

- Squash merge (there is just a single commit but this maintains PR number in a commit message)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitExtUtils/GitUI/ImageListExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,23 @@
+﻿using System.Runtime.InteropServices;
+
+namespace GitUI
```
Comment (RussKie) [inline GitExtUtils/GitUI/ImageListExtensions.cs:3]:
```suggestion
namespace GitUI;
```

**Review by RussKie — APPROVED** [review]

**Review by gerhardol — APPROVED** [review]

File: GitExtUtils/GitUI/ImageListExtensions.cs (hunk 1 above)
Comment (mstv) [reply GitExtUtils/GitUI/ImageListExtensions.cs:3]: ❔ for the const and import:
```suggestion
namespace System;

internal static partial class NativeMethods
```

File: GitExtUtils/GitUI/ImageListExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+    {
+        internal const int ComCtl32CLRNone = unchecked((int)0xFFFFFFFF);
+
+        [DllImport("comctl32.dll", EntryPoint = "ImageList_SetBkColor")]
+        internal static extern int ImageListSetBkColor(IntPtr himl, int clrBk);
+
+        /// <summary>
+        /// A regression was introduced in .net8 which causes an incorrect background color to be set
+        /// which manifests when using transparent images. See https://github.com/dotnet/winforms/issues/10462
+        /// This metod should be removed once the underlying issue is fixed.
```
Comment (mstv) [inline GitExtUtils/GitUI/ImageListExtensions.cs:15]:
```suggestion
        /// This method should be removed once the underlying issue is fixed.
```

File: GitExtUtils/GitUI/ImageListExtensions.cs (hunk 1 above)
Comment (mdonatas) [reply GitExtUtils/GitUI/ImageListExtensions.cs]: @mstv please have a look if I understood you correctly. I've moved the interop method (and a constant) into `GitExtUtils/GitUI/Interops/ComCtl32/ImageListSetBkColor.cs` following a pattern used in `GitUI` project.

File: GitExtUtils/GitUI/ImageListExtensions.cs [hunk 3]
```diff
@@ -0,0 +1,15 @@
+﻿namespace GitUI;
+
+public static class ImageListExtensions
+{
+    /// <summary>
+    /// A regression was introduced in .net8 which causes an incorrect background color to be set
```
Comment (RussKie) [inline GitExtUtils/GitUI/ImageListExtensions.cs:6]:
```suggestion
    /// A regression was introduced in .NET 8 which causes an incorrect background color to be set
```

**Review by RussKie — APPROVED** [review]
