### PR TITLE
catch cannot write to settings

### LINKED ISSUE #6635: [NBug] Access to the path 'C:\Users\TEAM_PUTRA_SERPENT\Desktop\bin...
## Error Details
```
System.UnauthorizedAccessException: Access to the path 'C:\Users\TEAM_PUTRA_SERPENT\Desktop\bin\.gitconfig.backup' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at GitCommands.Settings.FileSettingsCache.SaveImpl()
   at GitCommands.SettingsCache.<>c__DisplayClass3_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.Settings.SettingsContainer`2.Save()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #6794: [NBug] Die Datei "config19728.tmp" konnte nicht gefunden werden.
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.FileNotFoundException: Die Datei "config19728.tmp" konnte nicht gefunden werden.
Dateiname: "config19728.tmp"
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei GitCommands.Settings.FileSettingsCache.SaveImpl()
   bei GitCommands.SettingsCache.<>c__DisplayClass3_0.<LockedAction>b__0()
   bei GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   bei GitCommands.Settings.SettingsContainer`2.Save()
   bei GitUI.CommandsDialogs.FormSettings.Save()
   bei GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 144dpi (150% scaling)

### LINKED ISSUE #6830: [NBug] Could not find file 'config6456.tmp'.
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.FileNotFoundException: Could not find file 'config6456.tmp'.
File name: 'config6456.tmp'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at GitCommands.Settings.FileSettingsCache.SaveImpl()
   at GitCommands.SettingsCache.<>c__DisplayClass3_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.Settings.SettingsContainer`2.Save()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ChecklistSettingsPage.SaveAndRescan_Click(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ChecklistSettingsPage.GitFound_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)

### LINKED ISSUE #7345: [NBug] Access to the path 'config' is denied.
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.UnauthorizedAccessException: Access to the path 'config' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at GitCommands.Settings.FileSettingsCache.SaveImpl()
   at GitCommands.SettingsCache.<>c__DisplayClass3_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.Settings.SettingsContainer`2.Save()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
f

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #7345 
Fixes #6830 
Fixes #6794 
Fixes #6635 

## Proposed changes
If settings cannot be saved, show popup instead of NBug for users
Also catch all errors on the backup file, read-only gives UnauthorizedException

### Before

NBug

### After

image

## Test methodology
Manual
Set read-only on GitExtensions.settings

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Settings/FileSettingsCache.cs [hunk 1]
```diff
@@ -151,21 +152,28 @@ protected override void SaveImpl()
...
+                    }
 
-                File.Copy(tmpFile, SettingsFilePath, true);
-                File.Delete(tmpFile);
+                    File.Copy(tmpFile, SettingsFilePath, true);
+                    File.Delete(tmpFile);
+                }
+                catch (Exception ex)
+                {
+                    MessageBox.Show(ex.Message, "Cannot save settings", MessageBoxButtons.OK, MessageBoxIcon.Information);
```
Comment (RussKie) [inline GitCommands/Settings/FileSettingsCache.cs]:
```suggestion
                    MessageBox.Show(ex.Message, "Cannot save settings", MessageBoxButtons.OK, MessageBoxIcon.Error);
```

Comment (RussKie) [inline GitCommands/Settings/FileSettingsCache.cs]: Need to LOC the heading

Comment (gerhardol) [reply GitCommands/Settings/FileSettingsCache.cs]: changed - I felt informing was sufficient

Comment (gerhardol) [reply GitCommands/Settings/FileSettingsCache.cs]: This module is not in GitUI and is not translated right now
Very few of these popups are translated right now
I suggest to skip this

Comment (RussKie) [reply GitCommands/Settings/FileSettingsCache.cs]: When showing errors it needs to be error, or if it isn't terminal, it could be a warning.

File: UnitTests/GitCommandsTests/Settings/FileSettingsCacheTests.cs [hunk 2]
```diff
@@ -50,16 +50,6 @@ public void ctor_CanEnableFileWatcher_should_be_false_if_invalid_dir(string sett
...
-        [TestCase(null)]
-        [TestCase("")]
-        [TestCase("C:\\" + "\t")]
-        public void SaveImpl_should_throw_if_invalid_path(string settingsFilePath)
-        {
-            var cache = new MockFileSettingsCache(settingsFilePath, false).GetTestAccessor();
-            cache.SetLastModificationDate(DateTime.Now);
-            ((Action)(() => cache.SaveImpl())).Should().Throw<Exception>();
-        }
-
```
Comment (mstv) [inline UnitTests/GitCommandsTests/Settings/FileSettingsCacheTests.cs]: I'd like to keep this test. Perhaps you can borrow the class `SimpleDialog` from #6348. It might be a good first part of the pending rework of that PR. Thoughts, @RussKie?

Comment (RussKie) [reply UnitTests/GitCommandsTests/Settings/FileSettingsCacheTests.cs]: I won't say "no" to more tests :)

Comment (mstv) [reply UnitTests/GitCommandsTests/Settings/FileSettingsCacheTests.cs]: > I won't say "no" to more tests :)

That's no surprise :)
My question was more about tests with `MessageBox.Show`. #6348 introduces the class `SimpleDialog` with abstractions.

Comment (RussKie) [reply UnitTests/GitCommandsTests/Settings/FileSettingsCacheTests.cs]: I propose we decorate the test with `Ignore` attribute. 
Introduction of MessageBox abstractions should be done seprately

Comment (gerhardol) [reply UnitTests/GitCommandsTests/Settings/FileSettingsCacheTests.cs]: Set to Ignore()
Please stop auto-merge if you believe this should be handled differently

**Comment by gerhardol** [comment]
@msftbot merge in 1 day
