### PR TITLE
fix(file tree): ls-tree if no grep

### LINKED ISSUE #12413: First opening of file tree is slow
### Environment

- Git Extensions 33.33.33
- Build f94e62bc546e20c3e06f1a0b2c4184fdd3469d88  (custom build up to date with `master`)
- Git 2.47.0.windows.1
- Microsoft Windows NT 10.0.26100.0
- .NET 9.0.6
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 8.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Microsoft.WindowsDesktop.App 9.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

### Issue description

On a relatively big repository, opening the file tree for the first time when the filetree is not filtered (and nothing is cached) could be really slow (on my work repo --that doesn't use git-lfs-- between 15 to 30s).

It 's the `git grep --files-with-matches -z -e "^" a821940e23a71a770e51010a6e8939d3a447462f --` command which is long to run:
Image

Note: it seems not to be only the number of files that is the cause of the command to be slow as my work repo has 3.1k files and as a comparison gitextensions repo has 2.8k...

### Steps to reproduce

1. Open a big repository
2. Switch to file tree tab
3. notice that the display is slow

### Did this work in previous version of GitExtensions?

Yes. Side effect of #12341

### Diagnostics

Doing a `git grep` while there is nothing to search (takes between 15 to 30s) seems much less efficient than just loading the file tree with `git ls-tree -r` (less than 2.5s and cache seems more effective and could take only 0.15s).

I think it could be better to use `git ls-tree -r` instead of  `git grep`  when the file tree is not filtered

### LINKED ISSUE #12464: [NBug] Sequence contains more than one matching element
### Environment

- Git Extensions 5.2.1.18061
- Build 0d74cfdc312df90114a0cf8d6c8a30ca4213e2ff
- Git 2.47.1.windows.1
- Microsoft Windows NT 10.0.26100.0
- .NET 8.0.14
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitUI.CommandsDialogs.RevisionFileTreeController.FindSubNode(TreeNodeCollection nodes, Queue`1 pathParts) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\RevisionFileTreeController.cs:line 166
   at GitUI.CommandsDialogs.RevisionFileTreeController.SelectFileOrFolder(NativeTreeView tree, String fileSubPath) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\RevisionFileTreeController.cs:line 149
   at GitUI.CommandsDialogs.RevisionFileTreeControl.LoadRevision(GitRevision revision) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\RevisionFileTreeControl.cs:line 231
   at GitUI.CommandsDialogs.FormBrowse.FillFileTree(GitRevision revision) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormBrowse.cs:line 1230
   at GitUI.CommandsDialogs.FormBrowse.RefreshSelection() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormBrowse.cs:line 741
   at GitUI.CommandsDialogs.FormBrowse.CommitInfoTabControl_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormBrowse.cs:line 1574
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

I clicked on "File tree" for the selected file and it says "Sequence contains more than one matching element". It was my fault, I have some files starting with the space character in my repository.

### Steps to reproduce

1. Create a random file (e.g. "a.txt")
2. Create a file with the same name and put the space character at the beginning (e.g. " a.txt")
3. Commit these files
4. Open "File Tree" for one of these files

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
fixes #12413 
fixes #12464 

## Proposed changes

Improve performance (especially for lfs files) to display the file tree if no grep filter is active.
See the issue for the reduced time to run the command.

This could be moved to GitModule instead.
GitModule is a better place for checking that 

Note: ls-tree cannot be used for artificial commits, but ls-files could be used
That is a separate optimization

## Test methodology 

view manual git log

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/UserControls/FileStatusDiffCalculator.cs [hunk 1]
```diff
@@ -315,7 +315,9 @@ GitRevision GetActualRevisionForRevision(GitRevision revision)
             }
 
             IGitModule module = GetModule();
-            IReadOnlyList<GitItemStatus> statuses = module.GetGrepFilesStatus(selectedRev.ObjectId, _fileStatusDiffCalculatorInfo.GrepArguments, applyAppSettings: !_fileStatusDiffCalculatorInfo.FileTreeMode, cancellationToken);
+            IReadOnlyList<GitItemStatus> statuses = !selectedRev.IsArtificial && _fileStatusDiffCalculatorInfo.GrepArguments == @"-e ""^"""
+                ? module.GetTreeFiles(selectedRev.ObjectId, full: true)
+                : module.GetGrepFilesStatus(selectedRev.ObjectId, _fileStatusDiffCalculatorInfo.GrepArguments, applyAppSettings: !_fileStatusDiffCalculatorInfo.FileTreeMode, cancellationToken);
```
Comment (gerhardol) [inline src/app/GitUI/UserControls/FileStatusDiffCalculator.cs]: Will cleanup a little: Remove the hardcoded setting of GrepArguments  to ^ for file tree (use "") and move that to GetTreeFiles() for articicial (replace later with ls-files?) (maybe cancellation token too, but ls-tree does not take more than 200ms also in Linux repo so not long running).

Comment (mstv) [reply src/app/GitUI/UserControls/FileStatusDiffCalculator.cs]: Thank you, and much simpler than feared. 🎉

**Comment by pmiossec** [comment]
@gerhardol I don't know if you noticed but it has the strange side effect that in the filetree, all the files are displayed with the 'add' icon instead of the file type icon (until the `grep` command is run and after that the icons are good):
image

**Comment by mstv** [comment]
> @gerhardol I don't know if you noticed but it has the strange side effect that in the filetree, all the files are displayed with the 'add' icon instead of the file type icon (until the `grep` command is run and after that the icons are good)

I have noticed this, too. I think I will see the cause when I am going to review this later.

File: src/app/GitUI/UserControls/FileStatusDiffCalculator.cs [hunk 2]
```diff
@@ -309,13 +309,15 @@ GitRevision GetActualRevisionForRevision(GitRevision revision)
...
+            if (string.IsNullOrEmpty(_fileStatusDiffCalculatorInfo.GrepArguments) && !_fileStatusDiffCalculatorInfo.FileTreeMode)
             {
                 return null;
             }
 
             IGitModule module = GetModule();
-            IReadOnlyList<GitItemStatus> statuses = module.GetGrepFilesStatus(selectedRev.ObjectId, _fileStatusDiffCalculatorInfo.GrepArguments, applyAppSettings: !_fileStatusDiffCalculatorInfo.FileTreeMode, cancellationToken);
+            IReadOnlyList<GitItemStatus> statuses = string.IsNullOrEmpty(_fileStatusDiffCalculatorInfo.GrepArguments)
+                ? module.GetTreeFiles(selectedRev.ObjectId, full: true, cancellationToken)
+                : module.GetGrepFilesStatus(selectedRev.ObjectId, _fileStatusDiffCalculatorInfo.GrepArguments, applyAppSettings: !_fileStatusDiffCalculatorInfo.FileTreeMode, cancellationToken);
```
Comment (mstv) [inline src/app/GitUI/UserControls/FileStatusDiffCalculator.cs]: OT: Addendum to "actual git-grep in 'File tree'" is needed:
```suggestion
                : module.GetGrepFilesStatus(selectedRev.ObjectId, _fileStatusDiffCalculatorInfo.GrepArguments, applyAppSettings: true, cancellationToken);
```

File: src/app/GitCommands/Git/GitModule.cs [hunk 3]
```diff
@@ -2559,8 +2559,13 @@ public IReadOnlyList<GitItemStatus> GetStashDiffFiles(string stashName)
             return resultCollection;
         }
 
-        public IReadOnlyList<GitItemStatus> GetTreeFiles(ObjectId commitId, bool full)
+        public IReadOnlyList<GitItemStatus> GetTreeFiles(ObjectId commitId, bool full, CancellationToken cancellationToken = default)
```
Comment (mstv) [inline src/app/GitCommands/Git/GitModule.cs:2563]: Rather move default arg to interface `IGitModule`?

**Review by mstv — COMMENTED** [review]
The major change LGTM.
It needs two additions:
29d98228c48eb38b191caf4cadb0f0905c037501
dc2d21cf58a2ada9443631c6da10d664e6c1230d

**Comment by gerhardol** [comment]
There is something still that is not right,  but it probably works:
If grep status is set once, icon is updated from that on without manipulating the status (why I got it working without the grep string). But GitItemStatus is set with  prefix:
                            summary: $"{_grepSummaryPrefix}{_fileStatusDiffCalculatorInfo.GrepArguments} {GetDescriptionForRevision(selectedRev.ObjectId)}",

**Comment by mstv** [comment]
> There is something still that is not right, but it probably works: If grep status is set once, icon is updated from that on without manipulating the status (why I got it working without the grep string).

This is not wrong: Icons are cached. If they have already been loaded, they can be used at once.
The loading of icons is triggered for git-grep results only because actual *status* items have their special icon.

> But GitItemStatus is set with prefix: summary: $"{_grepSummaryPrefix}{_fileStatusDiffCalculatorInfo.GrepArguments} {GetDescriptionForRevision(selectedRev.ObjectId)}",

How is this related to this PR?
This `summary` is used for diff groups (`FileStatusWithDescription`) but not for single items (`GitItemStatus`).
For file tree, there is only one "group" without heading.

File: src/app/GitUI/UserControls/FileStatusDiffCalculator.cs [hunk 4]
```diff
@@ -83,21 +83,7 @@ private List<FileStatusWithDescription> CalculateDiffs(
...
-                        statuses: selectedRev.TreeGuid is null
-
-                            // likely index commit without HEAD
-                            ? module.GetDiffFilesWithSubmodulesStatus(firstId: null, selectedRev.ObjectId, parentToSecond: null, cancellationToken)
-
-                            // No parent for the initial commit
-                            : module.GetTreeFiles(selectedRev.TreeGuid, full: true)));
-                }
-                else
+                if (actualRev.ParentIds?.Count is > 0)
```
Comment (mstv) [inline src/app/GitUI/UserControls/FileStatusDiffCalculator.cs:86]: This is just a refactoring (condition equivalently inverted [and shortened]). Or have I missed something?

Comment (gerhardol) [reply src/app/GitUI/UserControls/FileStatusDiffCalculator.cs:86]: correct, added when looking at it - I can revert
It was just that I read this for the 100th times and asked myself again why the order is what it was...

**Comment by gerhardol** [comment]
> How is this related to this PR?
This summary is used for diff groups (FileStatusWithDescription) but not for single items (GitItemStatus).
For file tree, there is only one "group" without heading.

I fixed this
The icon was set from the GitItemStatus properties. The check for grepstring was not first but before added.
But there is no pint to look at the status if we know the grep/filetree status already.
The update is slightly shorter and less risky for similar changes

**Comment by gerhardol** [comment]
submodules are not displayed correctly after my latest change

File: src/app/GitUI/UserControls/FileStatusList.cs [hunk 5]
```diff
@@ -1436,9 +1436,12 @@ int GetItemImageIndex(GitItemStatus gitItemStatus, bool isGitGrep)
                     return imageIndex;
                 }
 
-                string imageKey = gitItemStatus.IsStatusOnly || !string.IsNullOrWhiteSpace(gitItemStatus.ErrorMessage)
-                    ? gitItemStatus == noItemStatuses[0] && !isGitGrep ? nameof(Images.FileStatusCopiedSame) : nameof(Images.FileStatusUnknown)
-                    : GetItemImageKey(gitItemStatus);
+                // FileTree/grep images are added async to _imageListData
+                string imageKey = isGitGrep
+                    ? nameof(ImageListData.DefaultFileImage)
```
Comment (mstv) [inline src/app/GitUI/UserControls/FileStatusList.cs]: Why not use the cached icon? Otherwise, this triggers an unnecessary async operation.

> submodules are not displayed correctly after my latest change

In addition, `ls-tree` reports submodules in contrast to `git grep`. The manual addition needs to be suppressed for real commits.
`src/app/GitUI/UserControls/FileStatusDiffCalculator.cs` lines 322-330.

File: src/app/GitUI/UserControls/FileStatusDiffCalculator.cs (hunk 4 above)
Comment (mstv) [reply src/app/GitUI/UserControls/FileStatusDiffCalculator.cs:86]: > I can revert

Rather keep it. It is good. I was just confused by the commit message.

File: src/app/GitUI/UserControls/FileStatusList.cs (hunk 5 above)
Comment (gerhardol) [reply src/app/GitUI/UserControls/FileStatusList.cs]: The change is just to set the placeholder icon explicitly, without calling GetItemImageKey() and rely on the fake GitItemStatus info.
Cached image is handled a few lines before,.

For submodules GetItemImageKey() will need to be called though, so a little more to handle (in addition to inserting submodules) why I set this as a draft. (maybe not handled here)
Maybe go back to setting fake grep string.

Maybe adding ls-files for artificial commits too, that seem to be quite minor and some more  special handling can be removed.

**Comment by gerhardol** [comment]
Two commits added, left a branch behind and squashed and rebased
ls-files works fine, could remove the special submodule handling too. Some optimizations, probably not possible to see. (I belive that there are no additional async added.)
Limitations in git-doc should be updated.

File: src/app/GitCommands/Git/GitModule.cs [hunk 6]
```diff
@@ -3191,18 +3185,35 @@ public IReadOnlyList<string> GetFullTree(string id)
...
         {
-            GitArgumentBuilder args = new("ls-tree")
+            bool isArtificial = commitId?.IsArtificial is true;
+            if (isArtificial && !full)
             {
-                "-z",
-                { full, "-r" },
-                commitId
-            };
+                throw new ArgumentOutOfRangeException(nameof(full), "Artificial commit requires fu.");
```
Comment (mstv) [inline src/app/GitCommands/Git/GitModule.cs]: There is no need to leave a nit for me. :)
```suggestion
                throw new ArgumentOutOfRangeException(nameof(full), "Artificial commit requires 'full'.");
```

File: src/app/GitCommands/Git/GitTreeParser.cs [hunk 7]
```diff
@@ -33,10 +33,13 @@ public IEnumerable<GitItem> Parse(string? tree)
...
-            // Split on \0 too, as GitModule.GetTree uses `ls-tree -z` which uses null terminators
-            string[] items = tree.Split(Delimiters.NullAndLineFeed);
+            // Split on \0, as GitModule.GetTree uses `ls-tree -z`
+            IEnumerable<string> items = tree.LazySplit('\0');
 
-            return items.Select(ParseSingle).Where(item => item is not null)!;
+            return from item in items
+                   let parsed = ParseSingle(item)
+                   where parsed is not null
+                   select parsed;
```
Comment (mstv) [inline src/app/GitCommands/Git/GitTreeParser.cs]: Do we (really) want to switch to this syntax? I would prefer at least that C# would add an implicit `select` clause because it is pretty redundant. What else should be meant?

**Review by mstv — COMMENTED** [review]
works well and fast for me, have not tested with removed submodule
In `GetLsTreeOutput` for `GitTreeParserTests.Parse_should_return_the_list`, the `'\n'` need to be replaced with `'\0'`.

File: src/app/GitCommands/Git/GitTreeParser.cs (hunk 7 above)
Comment (gerhardol) [reply src/app/GitCommands/Git/GitTreeParser.cs]: I asked CoPilot that suggested that this more efficient, less allocations as it iterates.
A foreach should be the same.
Why the LINQ is not iterating by default is something I do not realize. 
@russkie?

File: src/app/GitCommands/Git/GitModule.cs (hunk 6 above)
Comment (gerhardol) [reply src/app/GitCommands/Git/GitModule.cs]: I wish it was intentional...

**Comment by gerhardol** [comment]
> have not tested with removed submodule

A removed subm is not included in the output, except for git ls-files --no-cached
The attempt to get data is obviously failing
This is a Git issue, ignore

image

Before the subm information could be incorrect, the following lists also the removed 

HEAD
image

index
it is a bug to attempt getting the treeid here
image

worktree
image

--
In diff the behavior is the same as before
New submodule is wrong, but the subm info is not available

image

File: src/app/GitCommands/Git/GitTreeParser.cs (hunk 7 above)
Comment (RussKie) [reply src/app/GitCommands/Git/GitTreeParser.cs]: The framework teams don't use the linq at all (in the runtime implementations), as its perf isn't there (it's being improved, but there are still better alternatives).
I personally never like the sql-style linq syntax, and prefer the original syntax (or `foreach`, if applicable).

Comment (RussKie) [reply src/app/GitCommands/Git/GitTreeParser.cs]: > I asked CoPilot that suggested that this more efficient, less allocations as it iterates.

It can and does hallucinate every now and then :)

**Review by mstv — APPROVED** [review]
If it is actually more efficient than just
`return items.Select(ParseSingle).WhereNotNull();`

(The implementation of `WhereNotNull` could be turned into `Where(item => item is not null)` in order to let the IL compiler optimize it. I guess there is also a cost to the statemachine for `IEnumerable` and `yield`.)

**Comment by gerhardol** [comment]
> If it is actually more efficient than just `return items.Select(ParseSingle).WhereNotNull();`
> 
> (The implementation of `WhereNotNull` could be turned into `Where(item => item is not null)` in order to let the IL compiler optimize it. I guess there is also a cost to the statemachine for `IEnumerable` and `yield`.)

Do you suggest to change to
`items.Select(ParseSingle).WhereNotNull();`

**Comment by mstv** [comment]
> Do you suggest to change to

I assume you have changed it because it costs less time / allocations. Then, no.
(When using `WhereNotNull`, it should be simplified so that the compiler can apply its LINQ optimizations.)

**Review by mstv — APPROVED** [review]

**Comment by gerhardol** [comment]
added commit for #12464 

edit: also used a few lines from the followup in in #12436 for the #12464 change

**Review by mstv — APPROVED** [review]

**Comment by gerhardol** [comment]
squashed, rebased and added https://github.com/gitextensions/gitextensions/pull/12436#discussion_r2260879672
Plan to merge tomorrow together with #12421
