### PR TITLE
Do not try to show deleted images in diffviewer

### LINKED ISSUE #9195: [NBug] Value must not be null.
## Current behaviour
An exception occurs when selecting a commit with the first change in the list being a removal of an `.ico` file.

## Expected behaviour
A crash does not occur and the diff window is perhaps empty (or might show the contents of the `.ico` file)?

## Error Details
```
System.Exception: Value must not be null.
   at void Microsoft.Validates.Fail(string message)
   at void Microsoft.Validates.NotNull<T>(T value)
   at Task GitUI.Editor.FileViewer.ViewGitItemAsync(GitItemStatus file, Action openWithDifftool)
   at Task GitUI.Editor.FileViewer.ViewGitItemRevisionAsync(GitItemStatus file, ObjectId revision, Action openWithDifftool)
   at Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, string defaultText, Action openWithDiffTool)
   at async Task GitUI.CommandsDialogs.RevisionDiffControl.ShowSelectedFileDiffAsync()
   at async void GitUI.CommandsDialogs.RevisionDiffControl.DiffFiles_SelectedIndexChanged(object sender, EventArgs e)+(?) => { }
   at void GitUI.ThreadHelper+<>c__DisplayClass13_0+<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
I suppose there is something wrong with displaying the "diff" for a removed `.ico` file.

## Environment
- Git Extensions 33.33.33
- Build f840a0ab83a461035f816951fe39c752a92abc4c
- Git 2.30.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #9195

## Proposed changes

Do not try to view deleted images.
This applies both to difftab and commit.

### Before

3.5
Separate view in worktree and index/commit

image

image

master has the popup, not really required

### After

Same for worktree and index

image

## Test methodology 

manual
----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — APPROVED** [review]
Works for me

File: GitUI/GitUIExtensions.cs [hunk 1]
```diff
@@ -53,7 +53,7 @@ public static class GitUIExtensions
 
             openWithDiffTool ??= OpenWithDiffTool;
 
-            if (item.Item.IsNew || firstId is null || FileHelper.IsImage(item.Item.Name))
+            if (item.Item.IsNew || firstId is null || (FileHelper.IsImage(item.Item.Name) && !item.Item.IsDeleted))
```
Comment (gerhardol) [inline GitUI/GitUIExtensions.cs:56]: Switching evaluation order to slightly improve efficiency...
```suggestion
            if (item.Item.IsNew || firstId is null || !item.Item.IsDeleted && (FileHelper.IsImage(item.Item.Name)))
```

Will change and merge

**Comment by gerhardol** [comment]
@msftbot merge in 15 hours
