### PR TITLE
File status list tweaks

### LINKED ISSUE #5437: Diff tab: file list resize bug
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The listview (or the entries in it) moves to the right
diff-tab-bug-1

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Courtesy of @NikolayXHD:
1. Set `truncate long filename` setting to `None`
2. resize file status panel to the size when horizontal scroll appears
3. move scroll to the right (not necessarily rightmost) position
4. [optional] double-click group header twice to collapse and re-expand the group
5. resize the panel in 1 large movement, larger than the missing width created on step 2. 

Note: step 4 is optional. collapse / expand does not have to do with the issues at all.
The problem is caused by resizing the panel while the scroll is not in leftmost position

**What is the expected behavior?**
Correct layout after resize

**Environment you encounter the issue:**
Current master @ 7c4e8c5758c4d2a27703ad656973e3942ed128bb

**Did this work in previous version of GitExtensions (which)?**
No, 2.51 exhibits the same behavior

### PR DESCRIPTION
**Pull request by NikolayXHD**
Fixes #5437 and preserves autowidth behavior in FileStatusListView as requested in #5458

Changes proposed in this pull request:
- ListView items text is allways maintained exactly same as displayed text, depending on AppSettings.TruncatePathMethod, to keep horizontal scroll consistent.
- Column resizing is delayed by 10 ms to get out of Resize event handler to avoid the bugs #5437 and #5438 which totally belong to .NET framework.
- FileStatusList filter ComboBox is invalidated on resize to fix its distorted look.
- Ctrl+A is handled more presicely. Previous implementation would also handle Ctrl+Alt+A and etc.
 
Tested on Windows 7

### CODE REVIEW

**Comment by RussKie** [comment]
You're quick! 👍 
Could you please rebase on top of #5543, it is non functional but all members are rearranged.

**Comment by RussKie** [comment]
Please rebase on top of the master. Thanks

File: GitUI/UserControls/FileStatusList.cs [hunk 1]
```diff
@@ -493,6 +513,81 @@ int GetLastIndex()
             }
         }
 
+        private void FileStatusListView_DrawSubItem(object sender, DrawListViewSubItemEventArgs e)
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]: please move it below to where the other event handlers are.
bonus if you observe the A-Z order

File: GitUI/UserControls/FileStatusList.cs [hunk 2]
```diff
@@ -108,6 +108,26 @@ Bitmap ScaleHeight(Bitmap input)
...
         }
 
+        private void FileStatusListView_ClientSizeChanged(object sender, EventArgs e)
+        {
+            if (!FileStatusListView.IsHandleCreated)
+            {
+                return;
+            }
+
+            var formatter = new PathFormatter(FileStatusListView.CreateGraphics(), FileStatusListView.Font);
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]: Can this be created in .ctor and then reused?
Curious whether `FileStatusListView.CreateGraphics() == eventArgs.Graphics`....

File: GitUI/UserControls/FileStatusList.cs [hunk 3]
```diff
@@ -948,6 +1031,32 @@ string GetDescriptionForRevision(ObjectId objectId)
...
+                    var minWidth = FileStatusListView.ClientSize.Width;
+                    if (columnHeader.Width < minWidth)
+                    {
+                        columnHeader.Width = minWidth;
+                    }
+
+                    FileStatusListView.EndUpdate();
+                });
+            });
+        }
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]: @sharwell / @jbialobr is this implementation ok, or should this be written something like:

```
            this.InvokeAsync(() =>
            {
                // by changing the width after delay we workaround ListView bug
                // that renders ListView unusable if column Width is set within any
                // event handler like SizeChanged, ClientSizeChanged, Layout and etc.
                // https://github.com/gitextensions/gitextensions/issues/5437
                Thread.Sleep(TimeSpan.FromMilliseconds(10));

                FileStatusListView.BeginUpdate();
                columnHeader.AutoResize(ColumnHeaderAutoResizeStyle.ColumnContent);

                var minWidth = FileStatusListView.ClientSize.Width;
                if (columnHeader.Width < minWidth)
                {
                    columnHeader.Width = minWidth;
                }

                FileStatusListView.EndUpdate();
            }).FileAndForget();
```

File: GitUI/UserControls/FileStatusList.cs [hunk 4]
```diff
@@ -103,6 +103,26 @@ Bitmap ScaleHeight(Bitmap input)
             }
         }
 
+        private void FileStatusListView_ClientSizeChanged(object sender, EventArgs e)
```
[the remark this answers is not in the document]
Comment (NikolayXHD) [reply GitUI/UserControls/FileStatusList.cs]: ok

File: GitUI/UserControls/FileStatusList.cs (hunk 1 above)
Comment (NikolayXHD) [reply GitUI/UserControls/FileStatusList.cs]: ok

File: GitUI/UserControls/FileStatusList.cs (hunk 2 above)
Comment (NikolayXHD) [reply GitUI/UserControls/FileStatusList.cs]: No, because Graphics must correspond to correct Control.Handle which as far as I know is not immutable.

Comment (vbjay) [reply GitUI/UserControls/FileStatusList.cs]: When does a handle change?  https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.handlecreated

Comment (NikolayXHD) [reply GitUI/UserControls/FileStatusList.cs]: When some of `ListView` settings change. [example](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ListView.cs,976). You may also find other usages of `RecreateHandleInternal()` there.

File: GitUI/UserControls/FileStatusList.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/UserControls/FileStatusList.cs]: Yes, thanks, I had a brain fart after a long day. 🤦‍♂️ 
I was thinking of JTF

**Comment by RussKie** [comment]
Thank you
