### PR TITLE
Do not allow duplicate submodule paths

### LINKED ISSUE #9343: [NBug] An item with the same key has already been added.
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at GitUI.CommandsDialogs.FormBrowse.<UpdateSubmoduleMenuStatusAsync>d__195.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass193_0.<<SubmoduleStatusProvider_StatusUpdated>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
When I open any git repo I get this error but if I ignore it seems that everything is working fine

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.20.1.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.22000.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #9343

## Proposed changes

Check that submodule paths are not empty and unique.
This should already be the case, but non unique paths occurs in #9343 and should in a similar .ToDictionary() for the sidepanel.

The removed break in FormBrowse is not necessary - following submodules should be updated.

To be cherry-picked to release/3.5 after merge to master

## Test methodology 

Manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Submodules/SubmoduleStatusProvider.cs [hunk 1]
```diff
@@ -242,6 +243,12 @@ private void SetSubmoduleData(GitModule currentModule, SubmoduleInfoResult resul
                     bold = true;
                 }
 
+                if (string.IsNullOrWhiteSpace(path) || result.AllSubmodules.Any(info => info.Path == path))
```
Comment (RussKie) [inline GitCommands/Submodules/SubmoduleStatusProvider.cs:246]: `info.Path == path` should this be case insensitive?

**Review by mstv — APPROVED** [review]
LGTM, have not run
(On case-sensitive filesystems, this could be too restrictive. But we do not need to support people who want to confuse others and themselves by using submodules with different capitalization only.)

**Comment by gerhardol** [comment]
> LGTM, have not run
> (On case-sensitive filesystems, this could be too restrictive. But we do not need to support people who want to confuse others and themselves by using submodules with different capitalization only.)

I'll change this to windows only
