### PR TITLE
FormFileHistory: DiffToLocal hidden also when relevant

### LINKED ISSUE #4315: FormFileHistory: DiffToLocal hidden also when relevant
**Do you want to request a *feature* or report a *bug*?**
bug, regression in 2.51.RC1
Introduced in 9f5fe413

**What is the current behavior?**
The diff-to-local menu option is always disabled

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The menu option should not be disabled when a local file exists

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
2.50

### PR DESCRIPTION
**Pull request by gerhardol**
Regression in #4308 9f5fe413

Fixes #4315
bug, regression in 2.51.RC1
Introduced in 9f5fe41

Changes proposed in this pull request:
 - FormFileHistory, enable diff-to-local when local file exists
 
What did I do to test the code and ensure quality:
 - Context menu in revision grid
 - DiffToLocal isenabled when a local file exists

Has been tested on (remove any that don't apply):
 - Windows 10

### CODE REVIEW

File: GitUI/CommandsDialogs/FormFileHistory.cs [hunk 1]
```diff
@@ -429,7 +429,8 @@ private void FileHistoryContextMenuOpening(object sender, CancelEventArgs e)
             var selectedRevisions = FileChanges.GetSelectedRevisions();
 
             diffToolremotelocalStripMenuItem.Enabled =
-                selectedRevisions.Count == 1 && selectedRevisions[0].Guid != GitRevision.UnstagedGuid && File.Exists(FileName);
+                selectedRevisions.Count == 1 && selectedRevisions[0].Guid != GitRevision.UnstagedGuid &&
+                File.Exists(Path.Combine(Module.WorkingDir, FileName));
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormFileHistory.cs]: Ideally we would use `IFullPathResolver` here

**Comment by RussKie** [comment]
Squash and good to go.
