### PR TITLE
fix(inline-diff): Limit highlight length

### LINKED ISSUE #12038: Regression for Built-in Diff Tool when parsing very long line causes Git Extensions to permanently hang
### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.47.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.11
- DPI 144dpi (150% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

This issue is a regression with the built-in diff tool introduced in Git Extensions 5.1.  I use a tool that generates text files with very long lines.  When using Git Extensions 5.0 or older, I have never had a problem diffing this file.  After upgrading to 5.1.1 the built-in diff causes Git Extensions to permanently hang and either exits with no error or requires a force-kill from Windows.

This is extremely problematic as whenever this file is selected in Git Extensions the app will die, and the file is already in the repo history so there is no practical work-around for me aside from rolling back Git Extensions which is painful because I use the MSI installer and that does not allow downgrades.

### Steps to reproduce

[DiffTest.zip](https://github.com/user-attachments/files/17731027/DiffTest.zip)
Open the attached Git repo with Git Extensions 5.1 or newer.
Select the commit ff8f2f3 to see the built-in diff.
Git Extensions will permanently hang.

### Did this work in previous version of GitExtensions?

This issue was introduced with in-line diff parsing in Git Extensions 5.1 and newer.  It is not reproducible in Git Extensions 5.0 or older.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #12038

## Proposed changes

- DiffHighlightService: Apply highlighting to the first 2000 characters only

### Before

stack overflow

### After

image

image

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/Editor/Diff/DiffHighlightService.cs [hunk 1]
```diff
@@ -293,6 +293,14 @@ internal static void AddDifferenceMarkers(List<TextMarker> markers, Func<ISegmen
             markers.Add(CreateDimmedMarker(offsetRemoved + textRemoved.Length - lengthIdenticalAtEnd, lengthIdenticalAtEnd, isRemoved: true, dimBackground));
             markers.Add(CreateDimmedMarker(offsetAdded + textAdded.Length - lengthIdenticalAtEnd, lengthIdenticalAtEnd, isRemoved: false, dimBackground));
         }
+
+        return;
+
+        static ReadOnlySpan<char> LimitLength(ReadOnlySpan<char> text)
+        {
+            const int maxLength = 2000;
```
Comment (gerhardol) [inline src/app/GitUI/Editor/Diff/DiffHighlightService.cs:301]: Maybe decrease this even more?
I doubt I would scroll more than 200 characters so 500?

**Review by gerhardol — APPROVED** [review]

**Review by RussKie — APPROVED** [review]
