### PR TITLE
GPG: don't crash on artificial commits

### LINKED ISSUE #11388: [NBug] fatal: bad object 2222222222222222222222222222222222222222
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.24
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log --pretty="format:%G?" -1 2222222222222222222222222222222222222222
Working directory: C:\Devel\git-repos\sfm\

```
GitExtUtils.ExternalOperationException: fatal: bad object 2222222222222222222222222222222222222222
 ---> System.Exception: fatal: bad object 2222222222222222222222222222222222222222
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 147
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<T>(Func<Task<T>> asyncMethod, JoinableTaskCreationOptions creationOptions) x 2
   at string GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 43
   at Task<CommitStatus> GitCommands.Gpg.GitGpgController.GetRevisionCommitSignatureStatusAsync(GitRevision revision)+() => { } in C:/projects/gitextensions/GitCommands/Git/GitGpgController.cs:line 108
   at async Task<CommitStatus> GitCommands.Gpg.GitGpgController.GetRevisionCommitSignatureStatusAsync(GitRevision revision) in C:/projects/gitextensions/GitCommands/Git/GitGpgController.cs:line 99
   at async Task<GpgInfo> GitUI.CommandsDialogs.FormBrowseController.LoadGpgInfoAsync(GitRevision revision) in C:/projects/gitextensions/GitUI/CommandsDialogs/FormBrowseController.cs:line 32
   at async Task GitUI.CommandsDialogs.FormBrowse.FillGpgInfoAsync(GitRevision revision) in C:/projects/gitextensions/GitUI/CommandsDialogs/FormBrowse.cs:line 1276
   at async void GitUI.TaskManager.InvokeAndForget(Control control, Func<Task> asyncAction, CancellationToken cancellationToken)+(?) => { } [1] in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 111
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

dunno !! Maybe a type by the cat ?

### Steps to reproduce

the cat passed on the keyboard

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by pmiossec**
and hide the tab

Fixes #11388

### Before

Crash

### After

We don't see the tab anymore:
image

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build 6dd05e51f3540f6d9d0ee2c8b12e780230c8c1c6 (Dirty)
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -1263,6 +1263,24 @@ private void FillCommitInfo(GitRevision? revision)
 
         private async Task FillGpgInfoAsync(GitRevision? revision)
         {
+            // Don't show the "GPG" tab for artificial commits
+            bool showGpgInfoTab = revision?.IsArtificial != true && AppSettings.ShowGpgInformation.Value;
+
+            if (showGpgInfoTab)
+            {
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs:1270]: Please invert

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 2]
```diff
@@ -1263,6 +1263,24 @@ private void FillCommitInfo(GitRevision? revision)
...
+                if (GpgInfoTabPage.Parent is null)
+                {
+                    int index = CommitInfoTabControl.TabPages.IndexOf(TreeTabPage);
+                    Debug.Assert(index != -1, "TabControl should contain file tree tab page");
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs:1274]: Use DebugHelper

**Review by RussKie — COMMENTED** [review]
👍

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 3]
```diff
@@ -1263,6 +1263,24 @@ private void FillCommitInfo(GitRevision? revision)
 
         private async Task FillGpgInfoAsync(GitRevision? revision)
         {
+            // Don't show the "GPG" tab for artificial commits
+            bool showGpgInfoTab = revision?.IsArtificial != true && AppSettings.ShowGpgInformation.Value;
```
Comment (mstv) [inline GitUI/CommandsDialogs/FormBrowse.cs:1267]:
```suggestion
            bool showGpgInfoTab = revision?.IsArtificial is false && AppSettings.ShowGpgInformation.Value;
```

Comment (RussKie) [reply GitUI/CommandsDialogs/FormBrowse.cs:1267]: What about `null`?

Comment (mstv) [reply GitUI/CommandsDialogs/FormBrowse.cs:1267]: That's what `is false` means. `null` *is* not `false`, i.e. do not show the tab if we do not have a real revision.

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 2 above)
Comment (pmiossec) [reply GitUI/CommandsDialogs/FormBrowse.cs:1274]: I did the fix on master and that's what I used but I think it's not available in release branch...

Comment (RussKie) [reply GitUI/CommandsDialogs/FormBrowse.cs:1274]: Ah, makes sense. Thank you.

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormBrowse.cs:1267]: I am still unconvinced. These two expressions aren't equivalent:
image

Comment (pmiossec) [reply GitUI/CommandsDialogs/FormBrowse.cs:1267]: I'm not sure we are discussing about the logic but more on the business which is: does it make sense to display the tab when the there is no revision selected (i.e. empty repo)? I think that's not really important....

It has been decided to show the "File tree" in this case (code I borrowed) but as @mstv says, maybe it's better to not show the GPG tab in this case. Or you prefer @RussKie?

I tend to share @mstv point of view so I will change for "is false".

Comment (mstv) [reply GitUI/CommandsDialogs/FormBrowse.cs]: `==` and `is` are equivalent - as it should be.
If it does not work here, add parens.

image

```            StringBuilder sb = new();
            sb.AppendLine("\tnull\tfalse\ttrue");
            foreach (bool? value in new bool?[] { null, false, true })
            {
                sb.AppendLine($"{value?.ToString() ?? "null"} is\t{value is null}\t{value is false}\t{value is true}")
                  .AppendLine($"{value?.ToString() ?? "null"} ==\t{value == null}\t{value == false}\t{value == true}")
                  .AppendLine($"{value?.ToString() ?? "null"} is !\t{value is not null}\t{value is not false}\t{value is not true}")
                  .AppendLine($"{value?.ToString() ?? "null"} !=\t{value != null}\t{value != false}\t{value != true}");
            }

            MessageBox.Show(sb.ToString());
```

**Review by gerhardol — APPROVED** [review]

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 3 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormBrowse.cs]: I feel we have had this discussion before...

Just to clarify:

`revision?.IsArtificial is false` is equivalent to `revision is not null && revision?.IsArtificial == false`

> == and is are equivalent - as it should be.

...unless you override the operator ==...
