### PR TITLE
Bugfix/i7898 nre no parent

### LINKED ISSUE #7898: NRE on Ctrl+A
## Current behaviour

NRE

## Expected behaviour

behavior as in #7560

## Steps to reproduce

`Ctrl+A` on WIP branch #7899

## Screenshots

grafik

## Did this work in previous version of GitExtensions

yes

## Environment

- Git Extensions 4.0.0.8859
- Build 3bb59459d39c3fe086da40cf59994eb775562014 (Dirty)
- Git 2.24.1.windows.2
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

## Diagnostics

```
   at GitCommands.GitModule.GetDiffFilesWithSubmodulesStatus(ObjectId firstId, ObjectId secondId, ObjectId parentToSecond)
   at GitUI.FileStatusList.SetDiffs(IReadOnlyList`1 revisions, Func`2 getRevision)
   at GitUI.CommandsDialogs.RevisionDiffControl.SetDiffs(IReadOnlyList`1 revisions)
   at GitUI.CommandsDialogs.RevisionDiffControl.DisplayDiffTab()
   at GitUI.CommandsDialogs.FormBrowse.FillDiff()
   at GitUI.CommandsDialogs.FormBrowse.<.ctor>b__49_2(Object sender, EventArgs e)
   at GitUI.RevisionGridControl.<.ctor>b__108_0(Object _, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #7898

## Proposed changes

 * Uses a refactoring part of #7899
 * check for null of parents to currently selected. This is used to get the IsStaged status, used for artificial commits (to compare if Index is compared to HEAD).
 * avoids trying a common BASE if more than two are selected (does not seem to be an issue here but probably what is expected)

first,second commit to be squashed

## Test methodology 

Manual
Tests are updated

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Git/GitRevisionTester.cs [hunk 1]
```diff
@@ -15,7 +16,7 @@ public interface IGitRevisionTester
         /// <returns>
         /// True if one of the first selected is parent
         /// </returns>
-        bool AllFirstAreParentsToSelected(IEnumerable<GitRevision> firstSelected, GitRevision selectedRevision);
+        bool AllFirstAreParentsToSelected(IReadOnlyList<ObjectId> firstSelected, GitRevision selectedRevision);
```
Comment (RussKie) [inline GitCommands/Git/GitRevisionTester.cs]: Why?

Comment (gerhardol) [reply GitCommands/Git/GitRevisionTester.cs]: In some situations (for instance in FormCommit), the GitRevision need to be recreated, just to be converted to ObjectId and strings later.
There are further changes in #7899 and beyond, I have done some conversions previously to.

Comment (RussKie) [reply GitCommands/Git/GitRevisionTester.cs]: Why do we need to change from `IEnumerable<>` to `IReadOnlyList<>`?
This requires additional allocations

Comment (gerhardol) [reply GitCommands/Git/GitRevisionTester.cs]: That is not needed, the list is enumerated to a list though.

Comment (gerhardol) [reply GitCommands/Git/GitRevisionTester.cs]: changed this

Comment (RussKie) [reply GitCommands/Git/GitRevisionTester.cs]: Need to revert all `.ToList()` in `AllFirstAreParentsToSelected` calls

Comment (gerhardol) [reply GitCommands/Git/GitRevisionTester.cs]: Done

**Comment by gerhardol** [comment]
Updated review comments, squashed first and second commit
Scheduling merge, abort if further comments

**Comment by gerhardol** [comment]
@msftbot merge in 1 day

File: GitUI/UserControls/FileStatusList.cs [hunk 2]
```diff
@@ -678,15 +676,15 @@ public void SetDiffs(IReadOnlyList<GitRevision> revisions, Func<ObjectId, GitRev
...
+                        var status = Module.GetDiffFilesWithSubmodulesStatus(rev.ObjectId, Revision.ObjectId, Revision.FirstParentGuid);
                         tuples.Add((rev, desc, status));
                     }
 
                     // Show combined (merge conflicts) only when all first (A) are parents to selected (B)
                     // (a single merge commit is selected with parents explicit or implicit selected)
                     var isMergeCommit = AppSettings.ShowDiffForAllParents &&
                                         Revision.ParentIds != null && Revision.ParentIds.Count > 1 &&
-                                        _revisionTester.AllFirstAreParentsToSelected(parentRevs, Revision);
+                                        _revisionTester.AllFirstAreParentsToSelected(parentRevs.Select(item => item.ObjectId).ToList(), Revision);
```
Comment (RussKie) [inline GitUI/UserControls/FileStatusList.cs]:
```suggestion
                                        _revisionTester.AllFirstAreParentsToSelected(parentRevs.Select(item => item.ObjectId), Revision);
```

Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: Missed that - will be gone in #7899
