### PR TITLE
Git Notes not displayed in Commit info

### LINKED ISSUE #5653: Git Notes don't show in beta 3.00.00.01
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Git Notes show just fine in v2.51.05, but don't show at all in the latest beta.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a git note.

**What is the expected behavior?**
The note should show as it does in the previous stable version.

**Environment you encounter the issue:**
Windows

The "Help-About Copy" or "Report an Issue" button doesn't seem to put anything into my clipboard either.

- GitExtensions version:
- GIT version:  git version 2.18.0.windows.1
- OS version:  Windows 10
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #5653

## Proposed changes
GE supports adding Git Notes in the commit info view, shown as a part of 

In 2.x GE always fetched CommitInfo separately for each commit.
In 3.0 the full commit message is saved for commits newer than 6 months and information if multiline existed is stored with each commit. Git Notes is not fetched at this stage.
Git Notes were therefore just shown for multiline messages older than six months.

This PR will fetch the Git Notes if not done already for each commit similar to 2.x.

### Before
image

image

### After
image

## Test methodology 
Manual

## Test environment(s)

### CODE REVIEW

**Comment by gerhardol** [comment]
I have tested this commit in release/3.00 too

**Comment by RussKie** [comment]
Thank you

File: GitCommands/Git/GitRevision.cs [hunk 1]
```diff
@@ -87,6 +87,7 @@ public BuildInfo BuildStatus
         [CanBeNull]
         public string Body { get; set; }
         public bool HasMultiLineMessage { get; set; }
+        public bool HasNotes { get; set; }
```
Comment (drewnoakes) [inline GitCommands/Git/GitRevision.cs]: This bool could be packed into a integer field along with `HasMultiLineMessage` to save space. Not a blocker for this PR though.

**Comment by drewnoakes** [comment]
> Do you know whether querying notes during the initial log adds significant overhead?

I ran some quick and rough tests and adding `%N` to the log format to include notes (with output sent to `/dev/null`) increased time by ~5%.

If we did pull this down as part of the initial load, it'd be a bit tricky to parse out. Currently all output fields are single-line except for the body. Adding notes introduces a second variable-length field, and we'd need some kind of delimiter to separate it.

I'm not sure it's worth changing anything here.

**Comment by gerhardol** [comment]
> I ran some quick and rough tests and adding %N to the log format to include notes (with output sent to /dev/null) increased time by ~5%.

Seems reasonable. Even if this only occurs if Git Notes is configured, it may not be desired.
However, tooltips should be fetched async and a line about Git Notes missing be added to the tooltip if not available (then the info should be available next time).

**Comment by RussKie** [comment]
Is showing notes in tooltips that important?
Personally I don't like tooltips that cover half my screen, if I need all
info I can click on a revision...

**Comment by vbjay** [comment]
I agree.  Notes should be seen in the commit info tab and the dialog when you double click a commit. The tooltip should so basic info only,

**Comment by vbjay** [comment]
Instead of trying to pull it in git log, we can just use git notes list.  It just gives the refs "<note object> <annotated object>"  We can store that away as a dictionary or whatever.  We can then use git notes show <annotated object> to get the note info.

**Comment by drewnoakes** [comment]
I don't use notes personally, so I can't say for sure, but would it be useful to see an icon in the revision grid for rows that have a corresponding note (similar to how we show the multiline indicator)?

**Comment by vbjay** [comment]
> 
..useful to see an icon in the revision grid for rows that have a corresponding note...


Yes. 100%. With git notes list we can easily know that info.

**Comment by vbjay** [comment]
> query for all notes separately.

That is the way to go. How many note lines from git notes list do we expect?  Not a lot. Running git notes list shouldn't take a long time. It can populate a data structure (dictionary or whatever). When we need to get the note knowing it already has a note use git notes show ref here.

**Comment by RussKie** [comment]
I'd like to render notes separately from the message on the commit info tab
as well.
TBD in the future

**Comment by gerhardol** [comment]
Merge something like this now then and open a separate issue with enhancements, maybe something like based on vbjays suggestions:

Separate notes from message:
 * Do not fetch notes together with message (also when message is missing) but as a separate command (probably a configurable limit of notes, or use same as git-log).
 * Store separately from GitRevision (like a Dictionary)
 * Present separately in CommitInfo (and tooltip)
 * New column or overflow indicator to show that notes exists.

**Comment by vbjay** [comment]
One thing to remember. We could have fetched git note and shown it but they could edit note and we would show them a note. So caching note body is probably not a good idea.

**Comment by gerhardol** [comment]
> So caching note body is probably not a good idea.

That is a bug in this PR as well as in 2.x, changing the notes will require a separate refresh. (Suggest that is not changed now.)
In my opinion, invalidating the cache entry when adding notes in GE or when refreshing is sufficient.
Most use of notes are from other tools (like references to releases, issues, etc)

**Comment by gerhardol** [comment]
Updated that notes were not updated after editing (this issue exits in 2.x too).
Considered adding info to the tooltip if notes is missing, but this should be refreshed anyway and I want to have this ready for 3.0.1.

**Comment by drewnoakes** [comment]
Agree with merging this to fix regression.

> We could have fetched git note and shown it but they could edit note and we would show them a note.

Simple approach for now would be to just reload the cache whenever we reload revisions.

Agree too with @vbjay's idea of querying notes separately, and maintaining a separate lookup sounds reasonable. Potentially some trickery around preventing race conditions between two data sources and painting the UI.
