### PR TITLE
Better handle git security exception

### LINKED ISSUE #9954: After updating my Git version to `2.35.2.windows.1` my repoisitory doesn't show any commits
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.35.2.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4470.0
- DPI 96dpi (no scaling)

### Issue description

After updating my Git version to `2.35.2.windows.1` my repoisitory doesn't show any commits (this worked before updating Git). Some repositories are working fine, but some show no commits now.

image
 

### Steps to reproduce

Update to the latest git version (2.35.2.windows.1) open repositories until you find one that can't show commits.

### Did this work in previous version of GitExtensions?

It worked in the older versions of Git

### Diagnostics

NA

### PR DESCRIPTION
**Pull request by pmiossec**
by presenting a user frendly popup
that allows the user to add a security exception
for the current repository

Fixes #9954

## Proposed changes

Display a user frendly popup that allows the user to add a security exception for the current repository

### Before

image

### After

Without git output details:
image

With git output details:
image

git_security_warning

## Test methodology 

Manual: 
- Clone a (small) repo (like `https://github.com/gitextensions/gitextensions.github.io`) in a console with Admin rights
- Open this repo into GitExtensions (without admin rights)
- See error

## Test environment(s) 

- Git Extensions 33.33.33
- Build 8b2f138ce975609f5ba6d513652b9bf4b221257b (Dirty)
- Git 2.38.0.windows.1 (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.10
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
⚠️ Quick PoC. Any UI feedback or direct contribution welcomed...
...so that it lands in v4.0.1? (I see value in that to have less issue reporting).

Remaining TODOs:
* strings need to be converted to translated strings
* Maybe check only when Version >= 2.35

**Comment by RussKie** [comment]
Looked at screenshots only - this looks awesome!

I'll review in coming days.

File: GitUI/NBugReports/BugReportInvoker.cs [hunk 1]
```diff
@@ -100,6 +102,60 @@ public static void Report(Exception exception, bool isTerminating)
                 LogError(exception, isTerminating);
             }
 
+            if (exception is GitDubiousOwnershipSecurityException gitDubiousOwnershipSecurityException)
+            {
+                TaskDialogPage pageSecurity = new()
+                {
+                    Icon = TaskDialogIcon.Error,
+                    Caption = TranslatedStrings.GitSecurityError,
+                    Heading = "Git has detected a security problem that prevent the opening of the repository",
```
Comment (mstv) [inline GitUI/NBugReports/BugReportInvoker.cs:111]: ❔ 
```suggestion
                    Heading = "Git has detected a security problem that prevents opening the repository",
```

File: GitUI/NBugReports/BugReportInvoker.cs [hunk 2]
```diff
@@ -100,6 +102,60 @@ public static void Report(Exception exception, bool isTerminating)
...
+                    AllowCancel = true,
+                    SizeToContent = true,
+                    Text = @"To be able to open this repository, you will have to either fix the rights into the repository or add a security exception for the repository
```
Comment (mstv) [inline GitUI/NBugReports/BugReportInvoker.cs:114]:
```suggestion
                    Text = @"To be able to open this repository, you will have to either fix the rights in the repository or add a security exception for the repository.
```

File: GitExtUtils/GitDubiousOwnershipSecurityException.cs [hunk 3]
```diff
@@ -0,0 +1,17 @@
+﻿namespace GitExtUtils;
+
+public class GitDubiousOwnershipSecurityException : Exception
+{
+    private const string _dubiousOwnershipSecurityConfigString = "config --global --add safe.directory";
+    public const string TrustAllReposCommand = "config --global --add safe.directory *";
```
Comment (mstv) [inline GitExtUtils/GitDubiousOwnershipSecurityException.cs:6]:
```suggestion
    public const string TrustAllReposCommand = $"{_dubiousOwnershipSecurityConfigString} *";
```

File: GitExtUtils/GitDubiousOwnershipSecurityException.cs [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+    public string Error { get; }
+    public string Command { get; }
+
+    public static bool IsGitDubiousOwnershipSecurityError(string error)
+        => error.Contains(_dubiousOwnershipSecurityConfigString);
+    public GitDubiousOwnershipSecurityException(string error)
```
Comment (mstv) [inline GitExtUtils/GitDubiousOwnershipSecurityException.cs:12]:
```suggestion
        => error.Contains(_dubiousOwnershipSecurityConfigString);

    public GitDubiousOwnershipSecurityException(string error)
```

**Review by mstv — COMMENTED** [review]
👍 very user friendly
Translation should be supported.
Explorer invocation would be good, too.
`BugReportInvoker.Report()` should rather handle the TaskDialogs in nested functions.

File: GitCommands/Git/Executable.cs [hunk 5]
```diff
@@ -150,8 +150,11 @@ private void OnProcessExit(object sender, EventArgs eventArgs)
                             if (_throwOnErrorExit && exitCode != 0)
                             {
                                 string errorOutput = _process.StandardError.ReadToEnd().Trim();
-                                ExternalOperationException ex
-                                    = new(command: _process.StartInfo.FileName,
+
+                                Exception ex
+                                    = GitDubiousOwnershipSecurityException.IsGitDubiousOwnershipSecurityError(errorOutput)
+                                ? new GitDubiousOwnershipSecurityException(errorOutput)
+                                : new ExternalOperationException(command: _process.StartInfo.FileName,
```
Comment (RussKie) [inline GitCommands/Git/Executable.cs:157]: This looks misindented
```suggestion
                                Exception ex = GitDubiousOwnershipSecurityException.IsGitDubiousOwnershipSecurityError(errorOutput)
                                    ? new GitDubiousOwnershipSecurityException(errorOutput)
                                    : new ExternalOperationException(command: _process.StartInfo.FileName,
```

File: GitCommands/Git/Executable.cs [hunk 6]
```diff
@@ -150,8 +150,11 @@ private void OnProcessExit(object sender, EventArgs eventArgs)
                             if (_throwOnErrorExit && exitCode != 0)
                             {
                                 string errorOutput = _process.StandardError.ReadToEnd().Trim();
-                                ExternalOperationException ex
-                                    = new(command: _process.StartInfo.FileName,
+
+                                Exception ex
+                                    = GitDubiousOwnershipSecurityException.IsGitDubiousOwnershipSecurityError(errorOutput)
+                                ? new GitDubiousOwnershipSecurityException(errorOutput)
```
Comment (RussKie) [inline GitCommands/Git/Executable.cs:156]: This isn't good - this adds a hard dependency between different projects to implementation details. It doesn't feel to do this at this layer.
We're passing `errorOutput` verbatim wrapped in an inner exception, so at the UI layer - where we present the exception - we should be able to inspect it and provide different UI/handling.

File: GitExtUtils/GitDubiousOwnershipSecurityException.cs (hunk 3 above)
Comment (RussKie) [inline GitExtUtils/GitDubiousOwnershipSecurityException.cs:6]: I refer to avoid `public const` at all costs.

File: GitExtUtils/GitDubiousOwnershipSecurityException.cs [hunk 7]
```diff
@@ -0,0 +1,17 @@
+﻿namespace GitExtUtils;
+
+public class GitDubiousOwnershipSecurityException : Exception
+{
+    private const string _dubiousOwnershipSecurityConfigString = "config --global --add safe.directory";
+    public const string TrustAllReposCommand = "config --global --add safe.directory *";
+    public string Error { get; }
+    public string Command { get; }
+
+    public static bool IsGitDubiousOwnershipSecurityError(string error)
```
Comment (RussKie) [inline GitExtUtils/GitDubiousOwnershipSecurityException.cs:10]: This doesn't feel right to have it here. Coupled with the comment above, this check should be at the UI layer where we made a decision about what UI to present to the user.

File: GitUI/NBugReports/BugReportInvoker.cs [hunk 8]
```diff
@@ -100,6 +102,60 @@ public static void Report(Exception exception, bool isTerminating)
...
+                {
+                    RunGitConfigCommand(gitDubiousOwnershipSecurityException.Command);
+                };
+                pageSecurity.Buttons.Add(trustRepoButton);
+
+                TaskDialogCommandLinkButton trustAllButton = new("Trust all repositories (Dangerous!)");
+                trustAllButton.Click += (s, e) =>
+                {
+                    RunGitConfigCommand(GitDubiousOwnershipSecurityException.TrustAllReposCommand);
+                };
```
Comment (RussKie) [inline GitUI/NBugReports/BugReportInvoker.cs:130]: I wouldn't do this automatically, instead I'd link the user to https://git-scm.com/docs/git-config/#Documentation/git-config.txt-safedirectory. The full git command can be put as https://learn.microsoft.com/dotnet/api/system.windows.forms.taskdialogcommandlinkbutton.descriptiontext.

File: GitUI/NBugReports/BugReportInvoker.cs (hunk 1 above)
Comment (RussKie) [inline GitUI/NBugReports/BugReportInvoker.cs:111]: I'd retain the git's verbage:
```suggestion
                    Heading = "Detected dubious ownership in repository",
```

**Comment by RussKie** [comment]
I pushed a little tweak - just moved code around a little. Hope you don't mind.

**Comment by pmiossec** [comment]
I've made some changes and translated the strings.
Updated screenshot:

File: GitUI/NBugReports/BugReportInvoker.cs (hunk 8 above)
Comment (pmiossec) [reply GitUI/NBugReports/BugReportInvoker.cs]: I have kept the button but added an help button.

File: GitUI/NBugReports/BugReportInvoker.cs (hunk 1 above)
Comment (pmiossec) [reply GitUI/NBugReports/BugReportInvoker.cs]: Not 100% convinced by the proposed text because I understand that it could make sense when the user type directly the command but IMHO, it requires a little more context as the command is run by GE.

But I have updated the text to add git's verbage (that I thought I used but in fact it was just in the output logs).

I hope it will be good.

File: GitUI/NBugReports/BugReportInvoker.cs [hunk 9]
```diff
@@ -100,6 +105,14 @@ public static void Report(Exception exception, bool isTerminating)
                 LogError(exception, isTerminating);
             }
 
+            if (exception is ExternalOperationException externalOperationException
+                && externalOperationException.InnerException is { }
+                && externalOperationException.InnerException.Message.Contains(_dubiousOwnershipSecurityConfigString))
```
Comment (gerhardol) [inline GitUI/NBugReports/BugReportInvoker.cs:110]: Git commands that handles Git errors will not raise this exception.
I guess that there will be at least one command in the revision refresh scenario that will though.

I wish there were a safer way to detect the issue, but this I assume this is good enough.

**Review by gerhardol — COMMENTED** [review]
+1
Have reviewed details briefly, but in general it looks good.
Very welcome change. In 4.0.1 too?

**Comment by RussKie** [comment]
I pushed another tweak

- Tweaked wording
- Whenever the dialog is dismissed or Close button is pressed - show the dashboard.
- Use existing helpers to open Explorer or web links

I've tested all non-core interactions - i.e., I didn't test "Trust this..." buttons.

I'm still not convinced we should execute "Trust all repos" action - it's dangerous, and a user must consciously run it. I propose we open a temp text file with the command (and optionally, an instruction) that the user will need to execute/follow.

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 10]
```diff
@@ -561,7 +561,7 @@ private void UICommands_PostRepositoryChanged(object sender, GitUIEventArgs e)
         /// <summary>
         /// Refresh revisions, also handling changes external to GE.
         /// </summary>
-        private void RefreshRevisions()
+        public void RefreshRevisions()
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs:564]: Please revert this.

**Comment by vbjay** [comment]
> I'm still not convinced we should execute "Trust all repos" action - it's dangerous, and a user must consciously run it. I propose we open a temp text file with the command (and optionally, an instruction) that the user will need to execute/follow.

Instead add the directory. Don't use * but instead trust x directory.

**Comment by pmiossec** [comment]
> Instead add the directory. Don't use * but instead trust x directory.

This button is already there. Should we understand that you do agree with @RussKie that the "Trust All" should be removed?

@RussKie I didn't understood that you were only talking about the "Trust All" action.
So, I don't have a strong opinion on it and I can remove it. I was just thinking about the user that have a lot of repositories to allow and that would like to add this global exception after having added 5 or 6 repo exceptions. But it should be a very rare edge case.

>I propose we open a temp text file with the command (and optionally, an instruction) that the user will need to execute/follow.
Nor real added value. Let's drop the option I think....

**Comment by vbjay** [comment]
Yes. That's what I meant. Trust all should only be put in by user. Maybe a link or short description saying you (the user) can do this(use * in config value) but they will have to run it themselves.

**Comment by RussKie** [comment]
I'll see if I can share a change with a behaviour I mean over the weekend.
If not  - next week.

**Comment by RussKie** [comment]
> I'm still not convinced we should execute "Trust all repos" action - it's dangerous, and a user must consciously run it. I propose we open a temp text file with the command (and optionally, an instruction) that the user will need to execute/follow.

Like this:
image

**Review by RussKie — APPROVED** [review]

File: GitUI/NBugReports/BugReportInvoker.cs [hunk 11]
```diff
@@ -100,6 +103,14 @@ public static void Report(Exception exception, bool isTerminating)
...
```
Comment (mstv) [inline GitUI/NBugReports/BugReportInvoker.cs:108]:
```suggestion
                && externalOperationException.InnerException?.Message?.Contains(_dubiousOwnershipSecurityConfigString)) is true
```
(`is not null` is much clearer than `is {}` - not needed here anyway.)

File: GitUI/NBugReports/BugReportInvoker.cs [hunk 12]
```diff
@@ -172,6 +183,107 @@ void AddIgnoreOrCloseButton()
...
+            pageSecurity.Expander = new TaskDialogExpander
+            {
+                CollapsedButtonText = TranslatedStrings.GitDubiousOwnershipSeeGitCommandOutput,
+                ExpandedButtonText = TranslatedStrings.GitDubiousOwnershipHideGitCommandOutput,
+                Position = TaskDialogExpanderPosition.AfterFootnote,
+                Text = error,
+            };
+
+            TaskDialogButton button = TaskDialog.ShowDialog(OwnerFormHandle, pageSecurity);
+            if (button == TaskDialogButton.Cancel || button == TaskDialogButton.Close)
```
Comment (mstv) [inline GitUI/NBugReports/BugReportInvoker.cs:227]:
```suggestion
            if (button is (TaskDialogButton.Cancel or TaskDialogButton.Close))
```

**Review by mstv — COMMENTED** [review]
👍 just nits

File: GitUI/NBugReports/BugReportInvoker.cs [hunk 13]
```diff
@@ -172,6 +183,107 @@ void AddIgnoreOrCloseButton()
...
+            {
+                TaskDialogCommandLinkButton button = new(buttonText, allowCloseDialog: false)
+                {
+                    DescriptionText = $"git {_dubiousOwnershipSecurityConfigString} *",
+                };
+
+                button.Click += (_, _) =>
+                {
+                    string tempFile = Path.GetTempFileName();
+                    File.WriteAllText(tempFile, $"{TranslatedStrings.GitDubiousOwnershipTrustAllInstruction}\r\n\r\ngit {_dubiousOwnershipSecurityConfigString} *");
```
Comment (gerhardol) [inline GitUI/NBugReports/BugReportInvoker.cs:260]:
```suggestion
                    File.WriteAllText(tempFile, $"{TranslatedStrings.GitDubiousOwnershipTrustAllInstruction}\r\n\r\ngit {_dubiousOwnershipSecurityConfigString} \"*\"");
```

**Review by gerhardol — APPROVED** [review]

File: GitUI/NBugReports/BugReportInvoker.cs (hunk 12 above)
Comment (RussKie) [reply GitUI/NBugReports/BugReportInvoker.cs:227]: I don't think that'd compile. I'm not near a computer to verify.

File: GitUI/NBugReports/BugReportInvoker.cs (hunk 13 above)
Comment (RussKie) [reply GitUI/NBugReports/BugReportInvoker.cs:260]: Are quotes necessary?

Comment (gerhardol) [reply GitUI/NBugReports/BugReportInvoker.cs:260]: in bash, * is expanded to files in the directory

Comment (RussKie) [reply GitUI/NBugReports/BugReportInvoker.cs:260]: 👍

File: GitUI/NBugReports/BugReportInvoker.cs (hunk 12 above)
Comment (RussKie) [reply GitUI/NBugReports/BugReportInvoker.cs:227]: image

**Comment by RussKie** [comment]
@pmiossec you get the honours of merging it :)

**Comment by pmiossec** [comment]
Squashed and rebased. Tested. Updated the commit message and the screenshots. I think we are good to go...
Will merge after CI build finished...

**Comment by pmiossec** [comment]
And it finished at the exact moment I sent my comment 🤣

**Comment by RussKie** [comment]
:+1:
