### PR TITLE
fix(push): fix tracking reference not well selected

### LINKED ISSUE #11899: "Replace tracking reference" doesn't work on the Push dialog
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

The "Replace tracking reference" checkbox doesn't have any effect.
image

### Steps to reproduce

- Open the push dialog
- Check "Replace tracking reference"
- Modify the "to" branch to something else
- Push
- Open the push dialog again

The "to" branch returns to the original value instead of the modified one

### Did this work in previous version of GitExtensions?

Yes Version 4.2.1 

### Diagnostics

It creates the following command:
"C:\Program Files\Git\bin\git.exe" push -u --progress "origin" refs/heads/work1:refs/heads/other

### PR DESCRIPTION
**Pull request by pmiossec**
by retrieving the gitref corresponding to local branch combobox

fixes #11899

### Before

image

### After

image

## Test methodology 

- Manual

## Test environment(s) 

- GIT 
- Windows 

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
Alternative to  #11950 / poke @RussKie 
I think this change handle better the case where push dialog is open when no branch is checked out.

File: src/app/GitUI/CommandsDialogs/FormPush.cs [hunk 1]
```diff
@@ -780,24 +780,27 @@ private void BranchSelectedValueChanged(object sender, EventArgs e)
             {
                 if (PushToRemote.Checked)
                 {
-                    if (_NO_TRANSLATE_Branch.SelectedItem is GitRef branch)
+                    IGitRef selectedRef = _NO_TRANSLATE_Branch.SelectedItem as IGitRef;
+                    if (selectedRef == null && !string.IsNullOrEmpty(_NO_TRANSLATE_Branch.Text))
```
Comment (mstv) [inline src/app/GitUI/CommandsDialogs/FormPush.cs:784]: code style:
```suggestion
                    if (selectedRef is null && !string.IsNullOrEmpty(_NO_TRANSLATE_Branch.Text))
```

File: src/app/GitUI/CommandsDialogs/FormPush.cs [hunk 2]
```diff
@@ -780,24 +780,27 @@ private void BranchSelectedValueChanged(object sender, EventArgs e)
...
                     {
-                        if (_selectedRemote is not null)
+                        selectedRef = _gitRefs.FirstOrDefault(r => r.Name == _NO_TRANSLATE_Branch.Text);
+                    }
+
+                    if (selectedRef != null && _selectedRemote is not null)
```
Comment (mstv) [inline src/app/GitUI/CommandsDialogs/FormPush.cs:789]:
```suggestion
                    if (selectedRef is not null && _selectedRemote is not null)
```

File: src/app/GitUI/CommandsDialogs/FormPush.cs [hunk 3]
```diff
@@ -780,24 +780,27 @@ private void BranchSelectedValueChanged(object sender, EventArgs e)
             {
                 if (PushToRemote.Checked)
                 {
-                    if (_NO_TRANSLATE_Branch.SelectedItem is GitRef branch)
+                    IGitRef selectedRef = _NO_TRANSLATE_Branch.SelectedItem as IGitRef;
```
Comment (mstv) [inline src/app/GitUI/CommandsDialogs/FormPush.cs:783]: Why change the name?
```suggestion
                    IGitRef branch = _NO_TRANSLATE_Branch.SelectedItem as IGitRef;
```
or
```suggestion
                    IGitRef branchRef = _NO_TRANSLATE_Branch.SelectedItem as IGitRef;
```

**Review by mstv — COMMENTED** [review]
Looks sensible, have not run either

**Review by RussKie — COMMENTED** [review]
I'm not sure this is a more correct fix than proposed by me in #11950.
The reason is that the order of the dropdown initialisation is still incorrect, which means `_NO_TRANSLATE_Branch.SelectedItem` is null when the dialog first loaded and this method executes.

**Review by gerhardol — APPROVED** [review]
I believe this PR addresses the core problem I see: The selected ref is not always correct. I have seen that occasionally but not have been able to reproduce. The remote ref may not always match the local.
It can well be merged together with #11950 that also addresses the standard case

**Comment by pmiossec** [comment]
> The reason is that the order of the dropdown initialisation is still incorrect, which means `_NO_TRANSLATE_Branch.SelectedItem` is null when the dialog first loaded and this method executes.

It was made on purpose to not load the items of the combobox (and load them only when interacting with it) so that there is no slow down on opening (especially when you have a lot of local branches). As a consequence, indeed, `_NO_TRANSLATE_Branch.SelectedItem` is null.
The goal is to not pay the cost of loading the branches every times the form is opened for something that is very rarely used (we push the current branch or multiple branch, nearly never another local branch) and so handle the case of the current branch specifically as this fix is intended to do...

>I have seen that occasionally but not have been able to reproduce

You could reproduce it when trying to push to a tracking remote branch that has not the same name than the local branch.

> I'm not sure this is a more correct fix than proposed by me in #11950.

@RussKie If you prefer your fix, you will have to handle the case where you are in detached HEAD state.
When I started to work on the fix for this issue, I end up with the same fix before seeing the regression in this edge case. And this PR is the result of trying to provide a better fix that handle the 2 cases....

**Comment by RussKie** [comment]
> > The reason is that the order of the dropdown initialisation is still incorrect, which means `_NO_TRANSLATE_Branch.SelectedItem` is null when the dialog first loaded and this method executes.
> 
> It was made on purpose to not load the items of the combobox (and load them only when interacting with it) so that there is no slow down on opening (especially when you have a lot of local branches). As a consequence, indeed, `_NO_TRANSLATE_Branch.SelectedItem` is null. The goal is to not pay the cost of loading the branches every times the form is opened for something that is very rarely used (we push the current branch or multiple branch, nearly never another local branch) and so handle the case of the current branch specifically as this fix is intended to do...

Oh, that's the insights I wasn't aware of. This makes sense, and it'd be great to add comments capturing this knowledge, so no one would try to "fix" it again.
With that I'll close my change.

File: src/app/GitUI/CommandsDialogs/FormPush.cs (hunk 3 above)
Comment (pmiossec) [reply src/app/GitUI/CommandsDialogs/FormPush.cs:783]: `branch` is not expressive at all for me.
Because we take the `SelectedItem` it seems natural to me to have `selected` in the name.
I would prefer `selectedBranchRef` or, as a 2nd choice, `branchRef`.

**Comment by pmiossec** [comment]
> it'd be great to add comments capturing this knowledge, so no one would try to "fix" it again.

Done.

File: src/app/GitUI/CommandsDialogs/FormPush.cs (hunk 3 above)
Comment (mstv) [reply src/app/GitUI/CommandsDialogs/FormPush.cs:786]: I, too, am fine with `selectedBranchRef`.

**Review by mstv — APPROVED** [review]

**Comment by pmiossec** [comment]
Renamed. Squashed and rebased....

**Review by RussKie — APPROVED** [review]
