### PR TITLE
Fix #7257 ConEmu is missing

### LINKED ISSUE #7257: [NBug] Could not run the console emulator. The path to ConEmu.exe ...
## Current behaviour

A not handled exception is generated when ConEmu is not found.

## Expected behaviour

An error message should be better.

## Steps to reproduce

Delete ConEmu.exe.
Click on "Console" tab.

## Error Details
```
System.InvalidOperationException: Could not run the console emulator. The path to ConEmu.exe could not be detected.
   à ConEmu.WinForms.ConEmuSession.Init_StartConEmu(ConEmuStartInfo startinfo, CommandLineBuilder cmdl) dans [..]\gitextensions\Externals\conemu-inside\ConEmuWinForms\ConEmuSession.cs:ligne 718
   à ConEmu.WinForms.ConEmuSession..ctor(ConEmuStartInfo startinfo, HostContext hostcontext, JoinableTaskFactory joinableTaskFactory) dans [..]\gitextensions\Externals\conemu-inside\ConEmuWinForms\ConEmuSession.cs:ligne 136
   à ConEmu.WinForms.ConEmuControl.Start(ConEmuStartInfo startinfo, JoinableTaskFactory joinableTaskFactory) dans [..]\gitextensions\Externals\conemu-inside\ConEmuWinForms\ConEmuControl.cs:ligne 128
   à GitUI.CommandsDialogs.FormBrowse.<FillTerminalTab>b__210_0(Object sender, TabControlCancelEventArgs args) dans [..]\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:ligne 2979
   à System.Windows.Forms.TabControl.OnSelecting(TabControlCancelEventArgs e)
   à System.Windows.Forms.TabControl.WmSelChange()
   à System.Windows.Forms.TabControl.WndProc(Message& m)
   à GitUI.CommandsDialogs.FullBleedTabControl.WndProc(Message& m) dans [..]\gitextensions\GitUI\CommandsDialogs\FullBleedTabControl.cs:ligne 24
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.3.0
- Build c531c5fce8d3820eb1595750a1ccea8daf2f24b4 (Dirty) **I build it from source.**
- Git 2.21.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by bansan85**
Fixes #7257 

## Proposed changes

- Add an error message if ConEmu is missing instead of having a unhandled exception.

### Before

If ComEmu.exe is missing,Git Extensions shows the crash report window.

### After

Now Git Extensions shows an error message that ask to reinstall application.

## Test methodology

- Run the application with ComEmu.exe missing and click on the Console tab.
- An error message shall be shown.

## Test environment(s)

- GIT git version 2.23.0.windows.1
- Windows 10 v 1903 18362.356

The message will need to be translated.

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
Update translations strings as seen in the build message:
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/28052411

This could be done in Debug only, but the translation string will appear anyway (if run in Debug, weird to have different results for Release and Debug too).
I am for the change, since it helps those that see this the first time

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -87,6 +87,8 @@ public sealed partial class FormBrowse : GitModuleForm, IBrowseRepo
         private readonly TranslationString _undoLastCommitText = new TranslationString("You will still be able to find all the commit's changes in the staging area\n\nDo you want to continue?");
         private readonly TranslationString _undoLastCommitCaption = new TranslationString("Undo last commit");
 
+        private readonly TranslationString _comEmuNotFound = new TranslationString("Failed to found ConEmu.exe. Please reinstall Git Extensions.");
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs]: As discussed, we don't expect this error to occur for an installed app. The issue is only expected to occur in dev time, so directing a user to reinstall would be misleading.

I would say something along the line of:
`ConEmu appears to be missing. Please perform a full rebuild and try again.`

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 2]
```diff
@@ -2976,7 +2978,14 @@ private void FillTerminalTab()
...
                 }
 
-                _terminal.Start(startInfo, ThreadHelper.JoinableTaskFactory);
+                try
+                {
+                    _terminal.Start(startInfo, ThreadHelper.JoinableTaskFactory);
+                }
+                catch (InvalidOperationException)
+                {
+                    MessageBox.Show(_comEmuNotFound.Text, _errorCaption.Text, MessageBoxButtons.OK, MessageBoxIcon.Error);
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs]: In addition to the above, I see no reason to show the message box for Release builds, nor translate the message to our users. I want the app to crash, if a user has decided to randomly delete files.

To this extent, I suggest we do the following:
```suggestion
#if DEBUG
                    MessageBox.Show(@"ConEmu appears to be missing. Please perform a full rebuild and try again.", @"Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
#else
                    throw;
#endif
```

Because this affects only dev time experience, there is no need to translate the message, and the string must be inlined

Comment (bansan85) [reply GitUI/CommandsDialogs/FormBrowse.cs]: I agree that the translation is not needed if it's for developper only. I will do another commit in few hours.

**Comment by RussKie** [comment]
Please rebase and squash. Thanks

**Comment by RussKie** [comment]
Please squash and we'll have it merged
Thanks
