### PR TITLE
Fixup GDI object leaks

### LINKED ISSUE #9166: 3.5.0: Application randomly closes
## Current behaviour

At - to me - completely random intervals, the applications closes itself without any visible crash or error notification.

Happens multiple times a day.

Restarting the application lets me continue where I left off without any notice that the application is aware that it crashed.

## Expected behaviour

The application to be stable.

## Steps to reproduce

Sorry, I honestly don't know.

## Screenshots

N/A

## Did this work in previous version of GitExtensions

I have seen this happen occasionally in 3.4.3, but nowhere near as often as it is happening now.

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 144dpi (150% scaling)
 

## Relevant error information found in the Windows Event Viewer

---
<details>
  <summary>Set of log entries related to one crash (fold out for details)</summary>

```
Log Name:      Application
Source:        Windows Error Reporting
Date:          6-5-2021 6:52:41
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      ADVIESENZO-DT2020
Description:
Fault bucket 1627556613040182809, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: GitExtensions.exe
P2: 3.5.0.11713
P3: d1506942
P4: KERNELBASE.dll
P5: 10.0.19041.906
P6: 26452a2a
P7: c000041d
P8: 0012a6e2
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1253.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER161C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER162D.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER162D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER164D.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_GitExtensions.ex_7093d17356131af2f75088ee3ef7992ab898c5_b18fbb94_0a199c0b-9f52-4786-abad-1390c1bedb0b

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5f8a58ef-5699-47a5-aaa1-2ebca1eab7b2
Report Status: 268435456
Hashed bucket: 393e6a8f25df28b4b6963e1dcc191619
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-06T04:52:41.3590533Z" />
    <EventRecordID>25719</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>ADVIESENZO-DT2020</Computer>
    <Security />
  </System>
  <EventData>
    <Data>1627556613040182809</Data>
    <Data>1</Data>
    <Data>APPCRASH</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>GitExtensions.exe</Data>
    <Data>3.5.0.11713</Data>
    <Data>d1506942</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.906</Data>
    <Data>26452a2a</Data>
    <Data>c000041d</Data>
    <Data>0012a6e2</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1253.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER161C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER162D.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER162D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER164D.tmp.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_GitExtensions.ex_7093d17356131af2f75088ee3ef7992ab898c5_b18fbb94_0a199c0b-9f52-4786-abad-1390c1bedb0b</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>5f8a58ef-5699-47a5-aaa1-2ebca1eab7b2</Data>
    <Data>268435456</Data>
    <Data>393e6a8f25df28b4b6963e1dcc191619</Data>
    <Data>0</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          6-5-2021 6:52:38
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ADVIESENZO-DT2020
Description:
Faulting application name: GitExtensions.exe, version: 3.5.0.11713, time stamp: 0xd1506942
Faulting module name: KERNELBASE.dll, version: 10.0.19041.906, time stamp: 0x26452a2a
Exception code: 0xc000041d
Fault offset: 0x0012a6e2
Faulting process ID: 0x3d0c
Faulting application start time: 0x01d74216fea24a52
Faulting application path: C:\Program Files (x86)\GitExtensions\GitExtensions.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 5f8a58ef-5699-47a5-aaa1-2ebca1eab7b2
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-06T04:52:38.3150239Z" />
    <EventRecordID>25717</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>ADVIESENZO-DT2020</Computer>
    <Security />
  </System>
  <EventData>
    <Data>GitExtensions.exe</Data>
    <Data>3.5.0.11713</Data>
    <Data>d1506942</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.906</Data>
    <Data>26452a2a</Data>
    <Data>c000041d</Data>
    <Data>0012a6e2</Data>
    <Data>3d0c</Data>
    <Data>01d74216fea24a52</Data>
    <Data>C:\Program Files (x86)\GitExtensions\GitExtensions.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>5f8a58ef-5699-47a5-aaa1-2ebca1eab7b2</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Windows Error Reporting
Date:          6-5-2021 6:52:37
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      ADVIESENZO-DT2020
Description:
Fault bucket 2249714220862838513, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: GitExtensions.exe
P2: 3.5.0.11713
P3: d1506942
P4: GitExtensions
P5: 3.5.0.11713
P6: d1506942
P7: 10
P8: 0
P9: System.IO.FileNotFoundException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7F2.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBEB.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBFC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBFA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC1A.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_GitExtensions.ex_9b7f587f712196ca935eea64f3c6fea9680e278_b18fbb94_67930b9b-a96d-444b-8d4c-d4b53e10822c

Analysis symbol: 
Rechecking for solution: 0
Report Id: ee067263-3bc8-470c-bea9-84d6f396dd04
Report Status: 268435456
Hashed bucket: c15a62ee56052b730f38972a14ac96f1
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-06T04:52:37.5366455Z" />
    <EventRecordID>25716</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>ADVIESENZO-DT2020</Computer>
    <Security />
  </System>
  <EventData>
    <Data>2249714220862838513</Data>
    <Data>5</Data>
    <Data>CLR20r3</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>GitExtensions.exe</Data>
    <Data>3.5.0.11713</Data>
    <Data>d1506942</Data>
    <Data>GitExtensions</Data>
    <Data>3.5.0.11713</Data>
    <Data>d1506942</Data>
    <Data>10</Data>
    <Data>0</Data>
    <Data>System.IO.FileNotFoundException</Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7F2.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBEB.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBFC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBFA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC1A.tmp.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_GitExtensions.ex_9b7f587f712196ca935eea64f3c6fea9680e278_b18fbb94_67930b9b-a96d-444b-8d4c-d4b53e10822c</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>ee067263-3bc8-470c-bea9-84d6f396dd04</Data>
    <Data>268435456</Data>
    <Data>c15a62ee56052b730f38972a14ac96f1</Data>
    <Data>0</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          6-5-2021 6:52:35
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ADVIESENZO-DT2020
Description:
Faulting application name: GitExtensions.exe, version: 3.5.0.11713, time stamp: 0xd1506942
Faulting module name: KERNELBASE.dll, version: 10.0.19041.906, time stamp: 0x26452a2a
Exception code: 0xe0434352
Fault offset: 0x0012a6e2
Faulting process ID: 0x3d0c
Faulting application start time: 0x01d74216fea24a52
Faulting application path: C:\Program Files (x86)\GitExtensions\GitExtensions.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: ee067263-3bc8-470c-bea9-84d6f396dd04
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-06T04:52:35.6473799Z" />
    <EventRecordID>25715</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>ADVIESENZO-DT2020</Computer>
    <Security />
  </System>
  <EventData>
    <Data>GitExtensions.exe</Data>
    <Data>3.5.0.11713</Data>
    <Data>d1506942</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.906</Data>
    <Data>26452a2a</Data>
    <Data>e0434352</Data>
    <Data>0012a6e2</Data>
    <Data>3d0c</Data>
    <Data>01d74216fea24a52</Data>
    <Data>C:\Program Files (x86)\GitExtensions\GitExtensions.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>ee067263-3bc8-470c-bea9-84d6f396dd04</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          6-5-2021 6:52:35
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ADVIESENZO-DT2020
Description:
Application: GitExtensions.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at GitUI.NBugReports.BugReportInvoker.Report(System.Exception, Boolean)
   at GitExtensions.Program+<>c.<Main>b__1_3(System.Object, System.Threading.ThreadExceptionEventArgs)
   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
   at System.Windows.Forms.Control.WndProcException(System.Exception)
   at System.Windows.Forms.Control+ControlNativeWindow.OnThreadException(System.Exception)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-06T04:52:35.3833704Z" />
    <EventRecordID>25714</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>ADVIESENZO-DT2020</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: GitExtensions.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at GitUI.NBugReports.BugReportInvoker.Report(System.Exception, Boolean)
   at GitExtensions.Program+&lt;&gt;c.&lt;Main&gt;b__1_3(System.Object, System.Threading.ThreadExceptionEventArgs)
   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
   at System.Windows.Forms.Control.WndProcException(System.Exception)
   at System.Windows.Forms.Control+ControlNativeWindow.OnThreadException(System.Exception)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)

</Data>
  </EventData>
</Event>
```
</details>

---

### PR DESCRIPTION
**Pull request by mstv**
Fixes #9166

## Proposed changes

Fixup GDI object leaks:
- Release DC retrieved using `GetWindowDC`
- Dispose resources in `WindowsJumpListManager.MakeIcon`
- Correctly convert `Bitmap` to `Icon`
- Cache `Icons` drawn for Taskbar overlay / Jump List

## Test methodology 

- manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build 99649dc430eb85fbacda92046a639af8d1c552dc
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4360.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/Interops/User32/GetWindowDC.cs [hunk 1]
```diff
@@ -7,5 +7,8 @@ internal static partial class NativeMethods
     {
         [DllImport(Libraries.User32)]
         public static extern IntPtr GetWindowDC(IntPtr hwnd);
+
+        [DllImport(Libraries.User32)]
+        public static extern void ReleaseDC(IntPtr hwnd, IntPtr dc);
```
Comment (RussKie) [inline GitUI/Interops/User32/GetWindowDC.cs:12]: Move it to GitUI/Interops/User32/ReleaseDC.cs

**Review by RussKie — APPROVED** [review]
🚀

File: GitUI/Interops/User32/GetWindowDC.cs (hunk 1 above)
Comment (mstv) [reply GitUI/Interops/User32/GetWindowDC.cs:12]: Yes, of course.

**Comment by mstv** [comment]
I have rebased and added a proposal https://github.com/gitextensions/gitextensions/commit/d81ce7544cf293ca4093177c2c1e3094a3ff054a with minor changes to "Correctly convert bitmap to icon":
- Rename extension method to just `ToBitmap` (like `ToString`)
- Replace `var`

**Review by gerhardol — COMMENTED** [review]
+1
An alternative approach could have been to not recreate the icon if it is the same as before. This has less leaks, just slightly higher memory use though.

**Comment by mstv** [comment]
> An alternative approach could have been to not recreate the icon if it is the same as before.

That has already been implemented: refer to `LastBrush`. But is has only very little effect because the status is invalidated often.

> This has less leaks, just slightly higher memory use though.

It is limited to a low number of icons since we have a defined set of both overlay colors and images for the Jump List buttons.

File: GitUI/BitmapExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,34 @@
+﻿#nullable enable
+
+using System;
+using System.Drawing;
+
+namespace GitUI
+{
+    public static class BitmapExtensions
+    {
+        public static Icon BitmapToIcon(this Bitmap bitmap)
```
Comment (sharwell) [inline GitUI/BitmapExtensions.cs:10]: 💡 As an extension method, `Bitmap` seems redundant.

```suggestion
        public static Icon ToIcon(this Bitmap bitmap)
```

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 3]
```diff
@@ -104,6 +104,8 @@ public sealed partial class FormBrowse : GitModuleForm, IBrowseRepo
 
         [CanBeNull] private TabPage _consoleTabPage;
 
+        private Dictionary<Brush, Icon> _overlayIconByBrush = new();
```
Comment (sharwell) [inline GitUI/CommandsDialogs/FormBrowse.cs:107]:
```suggestion
        private readonly Dictionary<Brush, Icon> _overlayIconByBrush = new();
```

File: GitUI/WindowsJumpListManager.cs [hunk 4]
```diff
@@ -24,6 +25,7 @@ public sealed class WindowsJumpListManager : IDisposable
         private ThumbnailToolBarButton _pushButton;
         private ThumbnailToolBarButton _pullButton;
         private string _deferredAddToRecent;
+        private static Dictionary<Image, Icon> _iconByImage = new();
```
Comment (sharwell) [inline GitUI/WindowsJumpListManager.cs:28]:
```suggestion
        private static readonly Dictionary<Image, Icon> _iconByImage = new();
```

File: GitUI/UserControls/TextBoxEx.cs [hunk 5]
```diff
@@ -60,24 +60,22 @@ protected override void WndProc(ref Message m)
             {
                 case NativeMethods.WM_NCPAINT:
                 case NativeMethods.WM_PAINT:
```
Comment (sharwell) [inline GitUI/UserControls/TextBoxEx.cs:62]: ❓ Can we not just set `UserPaint` style and move the draw code to `OnPaint`?

File: GitUI/BitmapExtensions.cs (hunk 2 above)
Comment (mstv) [reply GitUI/BitmapExtensions.cs]: I forgot to push...

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 3 above)
Comment (mstv) [reply GitUI/CommandsDialogs/FormBrowse.cs]: Done. (I find C++ `const` clearer than `readonly`.)

File: GitUI/WindowsJumpListManager.cs (hunk 4 above)
Comment (mstv) [reply GitUI/WindowsJumpListManager.cs]: Done

File: GitUI/UserControls/TextBoxEx.cs (hunk 5 above)
Comment (mstv) [reply GitUI/UserControls/TextBoxEx.cs:62]: This should be done in a dedicated PR on the main dev branch.

**Comment by RussKie** [comment]
Champion 💯
