### PR TITLE
FileDiff: Factor in that two line numbers are displayed

### LINKED ISSUE #6031: diff / small space for large line numbers
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
part of second column line numbers cutted

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
compare changed lines with numbers > 20000

**What is the expected behavior?**
full output line numbers

**Environment you encounter the issue:**
- Git Extensions 3.01.00.4684
- Build 3209178ddf650121595314f0a150c60f2eea3a97 (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
Not sure

diff_line_numbers_cut

### PR DESCRIPTION
**Pull request by mstv**
Fixes #6031 (and #6568)

## Proposed changes

- width calculation factors in that two line numbers are displayed
- do not multiply `TextHorizontalMargin` by `textArea.TextView.WideSpaceWidth`!

### Before

grafik grafik

### After

grafik grafik

## Test methodology 

- manual

## Test environment(s) 

- Git Extensions 3.2.0
- Build 2bfd1153219c59c1c418541d2beee0ae7be5b6fa
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/Editor/Diff/DiffViewerLineNumberControl.cs [hunk 1]
```diff
@@ -31,7 +31,8 @@ public override int Width
             {
                 if (_visible && _diffLines.Any())
                 {
-                    return textArea.TextView.WideSpaceWidth * ((int)Math.Log10(MaxLineNumber) + TextHorizontalMargin + 3);
+                    int maxDigits = (int)Math.Log10(MaxLineNumber) + 1;
+                    return TextHorizontalMargin + (textArea.TextView.WideSpaceWidth * ((2 * maxDigits) + /* a space behind each number */ 2));
```
Comment (mstv) [inline GitUI/Editor/Diff/DiffViewerLineNumberControl.cs]: Just a rant: Which maths-agnostic guy has configured the Style Cop to enforce the parentheses in `(2 * maxDigits) + 1`?

Comment (RussKie) [reply GitUI/Editor/Diff/DiffViewerLineNumberControl.cs]: Ask @sharwell 😉
