### PR TITLE
fix: Randomly crash adding local as most recent

### LINKED ISSUE #4874: GitExtensions v3 Soft-Crash (See Attached Image)
**Do you want to request a *feature* or report a *bug*?** Report a Bug

**What is the current behavior?** GitExtensions shows an System.ArgumentException Error of 'repositoryPath' at Target Site "Void MoveNext() @ GitCommands.UserRepositoryHistory.LocalRepositoryManager+<AddAsMostRecentAsync>d__3"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Just Launch GitExtensions.exe

**What is the expected behavior?** App should launch without a Crash Error

**Environment you encounter the issue:**

- GitExtensions version: 3.00.00.2485-Portable (Is present in earlier versions)
- GIT version: 2.17.0
- OS version: Windows 10 x64

**Did this work in previous version of GitExtensions (which)?** Yes, in v2 and earlier v3 builds, this crash is not present.

Screenshots:

### PR DESCRIPTION
**Pull request by RussKie**
It appears at times Module.WorkingDir path is an empty string, which
tripped AE in Locals.AddAsMostRecentAsync.
All other uses of the API are verified to have guards in place.

Fixes #4874

What did I do to test the code and ensure quality:
- run unit tests
- run manually
- checked all other call sites to verify there are checks and guards from similar issues re-occurring.

Has been tested on (remove any that don't apply):
- GIT 2.10 and above
- Windows 7 and above

### CODE REVIEW

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -724,6 +724,13 @@ private void SetShortcutKeyDisplayStringsFromHotkeySettings()
         private void RefreshWorkingDirCombo()
         {
             var path = Module.WorkingDir;
+
+            // it appears at times Module.WorkingDir path is an empty string, this caused issues like #4874
+            if (string.IsNullOrWhiteSpace(path))
+            {
+                return;
```
Comment (jbialobr) [inline GitUI/CommandsDialogs/FormBrowse.cs]: The `_NO_TRANSLATE_Workingdir.Text` should be updated to reflect that no repo is open.

**Comment by RussKie** [comment]
thank you, I'll fix it up
