### PR TITLE
Render revision graph in the background

### LINKED ISSUE #11700: Revision graph broken (regression)
### Environment

- GitExtensions version: master ( 0b74e26ef4239e99822483eb59ed1c00ab8228fa )

### Issue description

At least on repository opening (I don't know if it could happen during a refresh)
it seems only when the repo has unrelated histories (but not sure)
the graph is broken:

image

instead of expected:

image

Refreshing the repository seems to make the bug disappear...

### Steps to reproduce

No clear steps:
1. switching from repos with unrelated histories increase the probability to get the bug

### Did this work in previous version of GitExtensions?

Bisected to 609e03d074ce312c036761ce39028a8ef70902f4, so yes, before

### Diagnostics

Handling of `e.Handled` is too aggressive?

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11700

## Proposed changes

Have clear chains of revision grid updates (one for graph loading affecting RowCount, one for visible row range).
Get rid of several workarounds and of the mix-up of revision loading and graph-only operations.
Avoid unnecessary blocking the UI thread.

- Do not render the graph in the UI thread but in a background task with double buffering
  in order to avoid calling the potentially expensive `RevisionGraphRow.BuildSegmentLanes` from the UI thread
- Remove `RevisionDataGridView.UpdateGraphAsync`, just call `RevisionGraph.CacheTo` once with cancellation
  because `CacheTo` is needed for graph rendering only
- Remove `UpdateVisibleRowRange` call on unhandled `OnCellPainting`
  because there no need to for this additional trigger of graph update
- `RevisionDataGridView`: Remove special `OnScroll` handler which called `Update` from time to time
  because the revision graph rendering does not block the UI any longer

## Screenshots 

N/A

## Test methodology 

- manual
- adapted tests

## Please do not squash merge!

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
This seem to work OK, have not reviewed all details

**Review by gerhardol — COMMENTED** [review]
+1 seem to work well, no obvious comments in the review
It is hard to review though, it is hard to understand why changes are done, what is better, how this is an improvement.

**Comment by mstv** [comment]
> It is hard to review though, it is hard to understand why changes are done, what is better, how this is an improvement.

Yes, this was missing in the description. Updated.

File: GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs [hunk 1]
```diff
@@ -73,115 +64,141 @@ private bool PaintGraphCell(int rowIndex, int rowHeight, Rectangle cellBounds, G
...
+            int height = _graphRenderCache.Capacity * rowHeight;
+            _graphRenderCache.Allocate(Math.Max(_columnWidth, GraphRenderer.LaneWidth * 3), height);
+
+            for (int rowIndex = fromRowIndex; rowIndex <= toRowIndex; ++rowIndex)
+            {
+                RenderGraphToCache(rowIndex, rowHeight);
+            }
+        }
+
+        private void RenderGraphToCache(int rowIndex, int rowHeight)
```
Comment (RussKie) [inline GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs:133]:
```suggestion
        private void RenderRowToCache(int rowIndex, int rowHeight)
```

**Review by RussKie — COMMENTED** [review]
:shipit:
