### PR TITLE
Fix rebase status displayed during a rebase

### LINKED ISSUE #8540: Wrong commit displayed as "Applying..." when there is a conflict
## Current behaviour

In the rebase popup, when solving a conflict, the wrong commit is displayed as "Applying".
That's the next one that is displayed as "Applying" instead of the current one which is not displayed.

## Expected behaviour

The current commit should be displayed as "Applying..."

## Screenshots

image

## Did this work in previous version of GitExtensions

Yes. It was fixed for v3.2 ( #6531 ) 
But it could be a git behavior change more than a GitExtensions regression...

## Environment

- Git Extensions 33.33.33
- Build 905403fe2edfa879c96e293973afebe555eb6e8e
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4240.0
- DPI 192dpi (200% scaling)

## Diagnostics

GitExtensions logic is to use the patch files generated by git to detect where we are in the rebase.

Previous behavior was:
image

It seems that now, only the remaining patches are displayed :(

### PR DESCRIPTION
**Pull request by pmiossec**
Fixes #8540, #7152 and #6350

## Proposed changes

- Fix the list of displayed commits that are rebased to always display all of them and with the good `Status` displayed
- other adjustments:
    * Move the important 'Status' column to be the first one (and not lost after author and date so that it could be more easily compare to the `Action` and `Subject`)
    * Display commit hash
    * Rename "Name" header to "Action" (because it display the define action. Especially when doing an interactive rebase)
    * Being able to open a commit diff window by double click (like it is possible to see the patch file for the patches)
    * Set a minimum height for a row (to avoid possible strange behavior)
    * Resize some columns

### Before

image

### After

* New list:
image

* Opening a commit:
image

## Test methodology 

- Manual

## Test environment(s) 

- GIT 
- Windows 

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -1926,14 +1926,14 @@ private string GetNextRebasePatch()
         private static readonly Regex HeadersMatch = new Regex(@"^(?<header_key>[-A-Za-z0-9]+)(?::[ \t]*)(?<header_value>.*)$", RegexOptions.Compiled);
         private static readonly Regex QuotedText = new Regex(@"=\?([\w-]+)\?q\?(.*)\?=$", RegexOptions.Compiled);
 
-        public bool InTheMiddleOfInteractiveRebase()
-        {
-            return File.Exists(GetRebaseDir() + "git-rebase-todo");
-        }
+        private string RebaseTodoFilePath => GetRebaseDir() + "git-rebase-todo.backup";
+        private string CurrentFilePath => GetRebaseDir() + "stopped-sha";
```
Comment (ivangrek) [inline GitCommands/Git/GitModule.cs:1930]: Could we use constants for strings?

File: GitCommands/Git/GitModule.cs [hunk 2]
```diff
@@ -1951,19 +1953,28 @@ public IReadOnlyList<PatchFile> GetInteractiveRebasePatchFiles()
...
-                            Date = error ?? data.CommitDate.LocalDateTime.ToString(),
-                            IsNext = patchFiles.Count == 0
-                        });
+                    string commitHash = parts[1];
+                    CommitData data = _commitDataManager.GetCommitData(commitHash, out var error);
+                    var isApplying = currentCommitShortHash != null && commitHash.StartsWith(currentCommitShortHash);
+                    if (!isCurrentFound && isApplying)
+                    {
+                        isCurrentFound = isApplying;
                     }
```
Comment (ivangrek) [inline GitCommands/Git/GitModule.cs:1967]:
``` suggestion
   isCurrentFound |= isApplying
```

Comment (ivangrek) [reply GitCommands/Git/GitModule.cs:1967]: false false => false
false true => true
true false => true
true true => true

OR

File: GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (RussKie) [reply GitCommands/Git/GitModule.cs:1930]: In which way?

Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:1930]: In this case the string is used only once (related to this routine) and the statement is is the accessor so it is used as a constant with a dynamic part.
I lean on not having a constant here, as it adds another layer. (Me and @ivangrek has had that discussion in #8628.) At the same time I see the point when seeing a stray string in code.

In a wider usage, "git-rebase-todo" is hardcoded also in GitUI\Editor\FileViewerInternal.cs SetHighlightingForFile() to highlight in the editor. This file does not need to be syntax highlighted what I see.

To use constants for files GE uses should be a TODO.

**Review by gerhardol — APPROVED** [review]
Great change
Also a step towards #5161?

**Comment by gerhardol** [comment]
This should be included, I added to next release milestone

**Comment by pmiossec** [comment]
Updated to better handle skipped commits/patches. Now, if the popup is closed and opened again, the skipped commit are still displayed as "Skipped" (instead of "Applied").

And better highlight the currently applied commit/patch (with conflicts) with some color:
image

And fixed a bug so that the currently applied patch line was not selected (due to the selecting was not made in the UI thread).

**Comment by RussKie** [comment]
@msftbot merge in 24 hours

**Comment by jrfnl** [comment]
@pmiossec Thanks so much! This has been bugging me for quite a while, but never got round to opening an issue. Awesome to see this fixed!
