### PR TITLE
Submodule context menus: Only show if dir exists

### LINKED ISSUE #8104: [NBug] The directory name is invalid
Automated reporting: May be a duplicate of #7671.

:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

In the commit window, I tried to reset the deletion of a directory. I don't recall, but directory may have been a submodule for some reason. The right-click menu showed 'reset submodule changes' instead of the expected 'reset file or directory changes'. When I chose to reset, the app crashed.

## Expected behaviour

The app should restore the directory/submodule

## Steps to reproduce

I'm not sure how this submodule item was created. It was an empty directory. I deleted it. I tried to reset the change through the commit window. Crash.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<RunCommandAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.RunCommand(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow)
   at GitUI.CommandsDialogs.FormCommit.resetSubmoduleChanges_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Don't know. I had deleted a directory named ZXing.Net.Mobile, and made a change to one file, which showed as two changes in the commit window. I tried to reset the delete (it showed as reset submodule changes), and it crashed.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #8104 

A few other NBug issues exist. I have considered this to be a too much edge case to fix it. Maybe users experience this before they have downloaded submodules? Or this is an indication that there are few serious NBug issues that are not reported.

There has been cleanups for access to submodule dirs in changes the last year, for instance #7690 and #8117, to not access submodules if the directories does not exist.

## Proposed changes

Only show context menus for work tree submodules "internals" if the submodule directories exists, required for the Git commands to run.

For FormCommit, the menus are disabled.

For RevDiff the menus the are not shown. The Controller structure (which is made this way to test) adds another layer to handle enable/disable and makes this quite complicated, it is not worth the effort.

### Before

image

image

### After

image

image

## Test methodology 

Added a test

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 1]
```diff
@@ -349,32 +349,36 @@ private ContextMenuSelectionInfo GetSelectionInfo()
...
                 foreach (var item in items)
                 {
                     var path = fullPathResolver.Resolve(item.Item.Name);
                     var fileExists = File.Exists(path);
-                    allFilesExist = allFilesExist && fileExists;
-                    var fileOrUntrackedDirectoryExists = fileExists || (!item.Item.IsTracked && Directory.Exists(path));
-                    allFilesOrUntrackedDirectoriesExist = allFilesOrUntrackedDirectoriesExist && fileOrUntrackedDirectoryExists;
+                    var directoryExists = Directory.Exists(path);
+                    allFilesExist &= fileExists;
+                    allDirectoriesExist &= directoryExists;
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:371]: (I am afraid, C# lacks the `&&=` operator. Though it should only matter for C but not for C# and C++ `bool`.)

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 2]
```diff
@@ -349,32 +349,36 @@ private ContextMenuSelectionInfo GetSelectionInfo()
...
+                    var fileOrUntrackedDirectoryExists = fileExists || (!item.Item.IsTracked && allDirectoriesExist);
```
Comment (mstv) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:372]: Have you changed this intentionally? Or should it be:
```suggestion
                    var fileOrUntrackedDirectoryExists = fileExists || (!item.Item.IsTracked && directoryExists);
```

File: GitUI/CommandsDialogs/RevisionDiffControl.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:371]: (I tried &&= first too, had to look up operators.)

File: GitUI/CommandsDialogs/RevisionDiffControl.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs:372]: Intentional, to show the menu only if only submodules are shown

**Review by mstv — APPROVED** [review]

**Comment by gerhardol** [comment]
@msftbot merge in 48 hours
