### PR TITLE
Fix visual glitch in the revision grid

### LINKED ISSUE #10672: Visual glitches in the revision grid when scrolling many lines at a time with mouse wheel
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.13
- DPI 134dpi (140% scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When scrolling the revision grid by 8 lines at a time with mouse wheel, visual glitches appear:
- Some rows are rendered out of place (shifted up or down), leading to duplicate rows and rows that are cut in half. All columns are affected.
- When selecting these out-of-place rows, they are instantly updated and rendered correctly.
- Tooltips don't seem to be affected.
- The glitch occurs nearly always (while scrolling up or down).

Please see this video in which I first scroll down, then select rows:

https://user-images.githubusercontent.com/39014485/214060645-6efe0b1b-dba9-44a5-ba13-5425d04e94c6.mp4

### Steps to reproduce

1. Configure your mouse wheel to scroll 8 lines at a time (Windows Settings > Devices > Mouse). I can reproduce the issue with any value between 6 and 20, but it becomes rare with bigger values and disappears with very big values (≳ 50).
2. With your mouse wheel scroll up or down in the revision grid.

### Did this work in previous version of GitExtensions?

The issue seems to be introduced by 02d5fdb0f57d5236c219f5460b2d7ea1ea56c0f1. I did not observe it with its parent fbb4000a648c9db317e29a344450a9dd672ac725.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by MaxKoll**
Fixes #10672. Although not knowing C# or the code, I could not resist investigating.

## Proposed changes

- Move the periodic repaint routine to the grid's scroll handler. Message interception via WndProc() seems to happen before the grid even had a chance to handle the message (i.e. move rows up or down). The scroll handler on the other hand seems to be called after the grid handled the scroll event.
- Counting consecutive WM_CTLCOLORSCROLLBAR messages seems to be unreliable in the case of dragging the scroll bar, because even more messages (other than WM_CTLCOLORSCROLLBAR) are being sent to the grid than when scrolling with the mouse wheel. As a result, _consecutiveScrollMessageCnt is reset to 0 before exceeding 5 most of the time, preventing forced repaints. Fix this by using a time-based approach to detect fast scrolling and force periodic repaints, which makes the GUI feel more responsive.
- I replaced
  ```
  var mm = new Message() { HWnd = Handle, Msg = NativeMethods.WM_PAINT };
  base.WndProc(ref mm);
  ```
  with
  ```
  Update();
  ```
  mostly for clarity. `Update()` triggers a repaint only if the grid is invalid. This seems to be the case after scrolling (well, it works), but please correct me if that's not the case.

## Test methodology 

I compared the scrolling behaviour against v3.5.4.12724 and the current master using this repo, and had an eye on visual appearance and performance. I used an app that emulates smooth scrolling to test the intended behaviour of the changed code segment.

## Test environment(s) 

Windows 10.0.19045.0 (134dpi, 140% scaling)
VS2022 Community
Git 2.38.1

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs [hunk 1]
```diff
@@ -622,6 +623,35 @@ private void SetRowCountAndSelectRowsIfReady(int rowCount)
...
+            {
+                _consecutiveScroll.Start();
+            }
+            else
+            {
+                _consecutiveScroll.Reset();
+            }
+
+            if (_consecutiveScroll.ElapsedMilliseconds > 50 &&
+                _lastRepaint.ElapsedMilliseconds > 50)
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs:646]: code style (left reading):
```suggestion
            if (_consecutiveScroll.ElapsedMilliseconds > 50
                && _lastRepaint.ElapsedMilliseconds > 50)
```

**Review by mstv — APPROVED** [review]
Thank you

**Review by RussKie — COMMENTED** [review]
Looks sensible. Haven't tested.

**Comment by MaxKoll** [comment]
This can be simplified slightly by starting `_consecutiveScroll` on initialization like the other timers and then just doing

```
if (_lastScroll.ElapsedMilliseconds > 100)
{
    _consecutiveScroll.Restart();
}
```

instead of:

```
if (_lastScroll.ElapsedMilliseconds < 100)
{
    _consecutiveScroll.Start();
}
else
{
    _consecutiveScroll.Reset();
}
```

May I force push this? (What's best, another commit or replace the existing one?)

**Comment by mstv** [comment]
You may force push. But since we are going to squash merge it, an additional commit is clearer - particularly regarding what has already been reviewed.

**Review by mstv — APPROVED** [review]

**Comment by MaxKoll** [comment]
Nice, thanks!
