### PR TITLE
Set custom difftool list to empty if parsing is cancelled

### LINKED ISSUE #10435: [NBug] Value cannot be null. (Parameter 'source')
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET 6.0.11
- DPI 120dpi (125% scaling)

### Issue description

```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at void System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at List<TSource> System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
   at async void GitUI.CustomDiffMergeToolProvider.LoadCustomDiffMergeTools(GitModule module, IList<CustomDiffMergeTool> menus, IContainer components, bool isDiff, int delay, CancellationToken cancellationToken)+(?) => { } [0]
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

there is error in settings dialog 
try to change ssh settings

### Steps to reproduce

some action ))

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #10435

## Proposed changes

If loading custom diff tools is cancelled, the list could be null and a null exception occur.

This has been around since custom difftools list (3.5?) so not urgent for 4.0.

## Test methodology 

Code review

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — APPROVED** [review]

**Review by RussKie — COMMENTED** [review]
What'd happen if there was an exception?

**Comment by gerhardol** [comment]
> What'd happen if there was an exception?

just catching that...

**Review by RussKie — APPROVED** [review]

File: GitCommands/CustomDiffMergeToolCache.cs [hunk 1]
```diff
@@ -68,15 +68,17 @@ public async Task<IEnumerable<string>> GetToolsAsync(GitModule module, int delay
                 }
             }
             catch
+            {
+                // No action.
```
Comment (mstv) [inline GitCommands/CustomDiffMergeToolCache.cs:72]: Non-cancellation exceptions are forwarded by the `.FileAndForget()` in `LoadCustomDiffMergeTools()`.
Why should we swallow them?

Comment (gerhardol) [reply GitCommands/CustomDiffMergeToolCache.cs:72]: Keep this as non important, similar to git-status refreshes in the background, to avoid user confusion for non critical issues.

Comment (gerhardol) [reply GitCommands/CustomDiffMergeToolCache.cs:72]: Unless you request changes, I would like to merge this tomorrow.

Comment (mstv) [reply GitCommands/CustomDiffMergeToolCache.cs:72]: I don't. We can ask for the Git Command Log in case of issues.
