### PR TITLE
Use ViewChangesAsync consistently for changes

### LINKED ISSUE #7866: Wrong diff in stash window
## Current behaviour

From the Manage stashes... window, Stash diffs occasionally do not reflect what is stored in the cache.
When multiple stash entries are created, that have different changes to the same file, sometimes a stash entry in the Manage Stashes... window will show a diff from an another stash entry.

While searching whether this was already documented, I've stumbled upon Issue [#2007](https://github.com/gitextensions/gitextensions/issues/2007) from 2013, which was about caching and it mentioned that restarting the program made it go away. It works with my issue as well! It may be a related issue.

## Expected behaviour

Each stash entry should show the diff in accordance to its changed files.

## Steps to reproduce

Just keeps happening randomly but I cannot yet reproduce it at will.
Common actions I've noticed that may have been related to these issues:
-giving custom names to the stash entries
-resetting branches and then creating commits with the same name (and having a stash on the commit that no longer belongs to any branch and was reset)
-dropping stashes

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.21.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Part of #7338 
Related to #7825 
Fixes #7866 

## Proposed changes

There are many codepaths that "presents changes" to files (binary, images) and submodules. The presentation differs if the file is new, tracked etc.
The logic for that is split between the separate forms and GitUIExtensions.cs, ViewChangesAsync(). Some of that has been cleaned up in previous PRs.
(FormCommit.cs also needs to have some logic in FileViewer.cs ViewCurrentChanges(), that requires #7825 first.)
The presentation therefore differs from form to form.

This change unifies the handling to be consistent, all using ViewChangesAsync()

This PR shares (conflicts) a change in #7914, rev-parse is required to get guid, see the explanation there.

This only changes how FormStash presents changes, the only actual change of this PR is that images that are changed should now be displayed.
(and FormCommit should not see any changes when this is applied in or after #78825, depending what goes in first).

## Test methodology
Manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
@gerhardol, could you create a list of your PRs with their dependencies, please, in order to know which to review first.

**Comment by gerhardol** [comment]
> could you create a list of your PRs with their dependencies

Some kond of review order, with simple and obvious first

#7926 refactoring and independent functionality but conflict with #7914 . #7825 needed to complete this (I expect this to go in first and #7825 be updated) 
#7914 refactoring and independent functionality but conflict with #7926

#7900 No major dependencies, to be updated soon

#7922 No dependencies

#7927 independent (and simple)

#7923 Move out the "algorithm" part of #7899, to at least start the discussion about the change

#7825 A few relations to files above, other than #7825 only rebase

#7899 Refactoring for GitItemStatusWithParents, enables unique diff of BASE->first. After #7923 right now. A major blocker for me.

#7915 WIP for discussion of how to handle parse errors. Need to be rebased on #7926

TBD
fix FileViewer API: Use GitItemStatusWithParents from #7899 and #7914 to cleanup the API in #7825

File: GitUI/GitUIExtensions.cs [hunk 1]
```diff
@@ -34,82 +34,90 @@ public static class GitUIExtensions
...
-                if (selectedRevision == null)
+                if (firstId == ObjectId.CombinedDiffId)
                 {
-                    throw new ArgumentNullException(nameof(selectedRevision));
+                    var diffOfConflict = fileViewer.Module.GetCombinedDiffContent(selectedId, file.Name,
+                        fileViewer.GetExtraDiffArguments(), fileViewer.Encoding);
+
+                    return string.IsNullOrWhiteSpace(diffOfConflict)
+                        ? diffOfConflict
+                        : Strings.UninterestingDiffOmitted;
```
Comment (mstv) [inline GitUI/GitUIExtensions.cs]:
```suggestion
                    return string.IsNullOrWhiteSpace(diffOfConflict)
                        ? Strings.UninterestingDiffOmitted
                        : diffOfConflict;
```

File: GitUI/GitUIExtensions.cs [hunk 2]
```diff
@@ -34,82 +34,90 @@ public static class GitUIExtensions
...
-                // View blob guid from revision, or file for worktree
-                return diffViewer.ViewGitItemRevisionAsync(file, selectedRevision.ObjectId, openWithDifftool);
-            }
+                if (file.IsSubmodule && file.GetSubmoduleStatusAsync() != null)
+                {
+                    // Patch already evaluated
+                    var status = ThreadHelper.JoinableTaskFactory.Run(file.GetSubmoduleStatusAsync);
+                    return status != null
+                        ? LocalizationHelpers.ProcessSubmoduleStatus(fileViewer.Module, status)
+                        : $"Submodule \"{file.Name}\" has unresolved conflicts";
```
Comment (mstv) [inline GitUI/GitUIExtensions.cs]: Consider localization. Perhaps rather support `null` in `ProcessSubmoduleStatus`.

File: GitUI/GitUIExtensions.cs [hunk 3]
```diff
@@ -34,82 +34,90 @@ public static class GitUIExtensions
...
             {
-                var fullPath = Path.Combine(diffViewer.Module.WorkingDir, file.Name);
-                if (Directory.Exists(fullPath) && GitModule.IsValidGitWorkingDir(fullPath))
+                if (defaultText.IsNotNullOrWhitespace())
                 {
-                    // git-status does not detect details for untracked and git-diff --no-index will not give info
-                    return LocalizationHelpers.GetSubmoduleText(diffViewer.Module, file.Name.TrimEnd('/'), "");
+                    return fileViewer.ViewTextAsync(file?.Name, defaultText, openWithDiffTool);
                 }
-            }
```
Comment (mstv) [inline GitUI/GitUIExtensions.cs]: Can the whole block `if (!file.IsTracked)` be omitted safely?

Comment (gerhardol) [reply GitUI/GitUIExtensions.cs]: Yes, !IsTracked -> IsNew is always set and we never try to get patches
This is handled in FileViewr.cs ViewFileAsync():397 (also for other code paths), see also #7869

File: GitUI/GitUIExtensions.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/GitUIExtensions.cs]: ok

File: GitUI/CommandsDialogs/FormStash.cs [hunk 4]
```diff
@@ -187,52 +188,22 @@ private void StashedSelectedIndexChanged(object sender, EventArgs e)
...
-                                {
-                                    return View.ViewPatchAsync(fileName: stashedItem.Name, text: LocalizationHelpers.ProcessSubmodulePatch(Module, stashedItem.Name, patch),
-                                            openWithDifftool: null /* not implemented */, isText: stashedItem.IsSubmodule);
-                                }
-
-                                return View.ViewPatchAsync(fileName: stashedItem.Name, text: patch.Text, openWithDifftool: null /* not implemented */, isText: stashedItem.IsSubmodule);
-                            });
-                    }
+                    first = ObjectId.IndexId;
+                    selected = ObjectId.WorkTreeId;
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormStash.cs]: > Though I guess stash stores both unstaged and staged files, doesn't it?

Yes
This causes the worktree files to be displayed in the viewer rather than the index, so incorrect...
Will fix the versions
(This is better handled with GitItemStatusWithParent after #7899)

[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormStash.cs]: worktree and index should be presented in two groups too (this definitely requires #7899)

[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormStash.cs]: Improved the change to only rev-parse when creating the FileStatusList and separated to own commit - could be a separate PR (but still dependent on this PR).

File: GitUI/UserControls/FileStatusList.cs [hunk 5]
```diff
@@ -726,12 +726,16 @@ ObjectId GetRevisionOrHead(ObjectId rev, Lazy<ObjectId> head)
...
+        public void SetDiffs([CanBeNull] GitRevision selectedRev, [CanBeNull] GitRevision parentRev, [NotNull] IReadOnlyList<GitItemStatus> items)
         {
             Revision = selectedRev;
-            GitItemStatusesWithDescription = items == null
-                ? Array.Empty<(GitRevision, string, IReadOnlyList<GitItemStatus>)>()
-                : new[] { (parentRev, _diffWithParent.Text + GetDescriptionForRevision(parentRev?.ObjectId), items) };
+            GitItemStatusesWithDescription = new[] { (parentRev, _diffWithParent.Text + GetDescriptionForRevision(parentRev?.ObjectId), items) };
+        }
+
+        public void SetDiffs()
```
Comment (mstv) [inline GitUI/UserControls/FileStatusList.cs:735]: Should it rather be renamed to `ClearDiffs` or `ResetDiffs`?

File: IntegrationTests/UI.IntegrationTests/CommandsDialogs/FileStatusListTests.cs [hunk 6]
```diff
@@ -48,7 +48,7 @@ public void ItemSelections()
             var itemAt0 = item1;
             var itemAt1 = item2;
             var itemAt2 = item0;
-            _fileStatusList.SetDiffs(items: items);
+            _fileStatusList.SetDiffs(null, null, items: items);
```
Comment (mstv) [inline IntegrationTests/UI.IntegrationTests/CommandsDialogs/FileStatusListTests.cs:51]: Yes, Re# injects these -- but it slows down the IDE too much for me.
```suggestion
            _fileStatusList.SetDiffs(selectedRev: null, parentRev: null, items);
```

File: GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs [hunk 7]
```diff
@@ -367,7 +367,9 @@ private void SplitAndLoadDiff(string diffData)
                 _diffCache.Add(gis.Name, match.Groups[3].Value);
             }
 
-            _fileStatusList.SetDiffs(items: giss);
+            // Commits in PR may not exist in the repo so GitRevision in FileStatusList is not used,
+            // patches directly from the cache
+            _fileStatusList.SetDiffs(null, null, items: giss);
```
Comment (mstv) [inline GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs:372]:
```suggestion
            _fileStatusList.SetDiffs(selectedRev: null, parentRev: null, items: giss);
```

File: GitUI/UserControls/FileStatusList.cs (hunk 5 above)
Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs:735]: ClearFileStatus()
I did not want to change so much in this PR - will change this and open a new PR for Stash

File: IntegrationTests/UI.IntegrationTests/CommandsDialogs/FileStatusListTests.cs (hunk 6 above)
Comment (gerhardol) [reply IntegrationTests/UI.IntegrationTests/CommandsDialogs/FileStatusListTests.cs:51]: ok, for all

**Comment by gerhardol** [comment]
Removed the FormStash improvements, will create a new PR continued from this, also likely separating worktree/index in groups.

File: GitUI/UserControls/FileStatusList.cs (hunk 5 above)
Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: It should be easier to get smaller PRs merged, but with @RussKie you never know. The smaller the PRs are, the more changes requested per line changed. There is a review queue...
But many of my open PRs are related to each other, I am blocked and will probably spend time on other projects now.

Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: > But the counterpart is named SetDiffs

The method could maybe be called Clear() instead
SetDiffs() is not a good name, but I do not have any better suggestion

File: GitUI/GitUIExtensions.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/GitUIExtensions.cs]: I cannot see how the submodule status would not be evaluated except in case of errors, so I changed the message and suggest no translation.

**Comment by gerhardol** [comment]
@RussKie I would like to merge this and you have approved the follow up #7938. OK?

**Comment by RussKie** [comment]
I'll review this today

File: GitUI/UserControls/FileStatusList.cs (hunk 5 above)
Comment (gerhardol) [reply GitUI/UserControls/FileStatusList.cs]: As mentioned in #7938, changing to ClearDiffs()

File: GitCommands/FileHelper.cs [hunk 8]
```diff
@@ -57,8 +57,9 @@ public static class FileHelper
 
         public static bool IsBinaryFileName(GitModule module, string fileName)
         {
-            return IsBinaryAccordingToGitAttributes(module, fileName)
-                ?? HasMatchingExtension(BinaryExtensions, fileName);
+            return fileName.IsNotNullOrWhitespace()
+                   && (IsBinaryAccordingToGitAttributes(module, fileName)
+                       ?? HasMatchingExtension(BinaryExtensions, fileName));
```
Comment (RussKie) [inline GitCommands/FileHelper.cs:62]: Do we have tests for this?

File: GitUI/GitUIExtensions.cs [hunk 9]
```diff
@@ -34,82 +34,90 @@ public static class GitUIExtensions
...
+        /// View the changes between the revisions, if possible as a diff
+        /// </summary>
+        /// <param name="fileViewer">Current FileViewer</param>
+        /// <param name="firstId">The first (A) commit</param>
+        /// <param name="selectedRev">The selected (B) commit</param>
+        /// <param name="file">The git item to view</param>
+        /// <param name="defaultText">default text if no diff is possible</param>
+        /// <param name="openWithDiffTool">The difftool command to open with</param>
+        /// <returns>Task to view</returns>
+        public static Task ViewChangesAsync(this FileViewer fileViewer,
```
Comment (RussKie) [inline GitUI/GitUIExtensions.cs:47]: If we make it `this IFileViewer fileViewer`, we should be able to test for of the codepaths

File: GitUI/GitUIExtensions.cs [hunk 10]
```diff
@@ -34,82 +34,90 @@ public static class GitUIExtensions
...
+
+                    return string.IsNullOrWhiteSpace(diffOfConflict)
+                        ? Strings.UninterestingDiffOmitted
+                        : diffOfConflict;
                 }
 
-                // View blob guid from revision, or file for worktree
-                return diffViewer.ViewGitItemRevisionAsync(file, selectedRevision.ObjectId, openWithDifftool);
-            }
+                if (file.IsSubmodule && file.GetSubmoduleStatusAsync() != null)
```
Comment (RussKie) [inline GitUI/GitUIExtensions.cs:106]: `file.GetSubmoduleStatusAsync() != null` this looks sus. An async method should be awaited, not checked for `null`s...

File: GitCommands/FileHelper.cs (hunk 8 above)
Comment (gerhardol) [reply GitCommands/FileHelper.cs:62]: No

File: GitUI/GitUIExtensions.cs (hunk 9 above)
Comment (gerhardol) [reply GitUI/GitUIExtensions.cs:47]: There is no interface for the methods FileViewer.cs provides right now (like ViewTextAsync(), ViewGitItemRevisionAsync(), Clear()).
The IFileViewer interface handles FileViewerInternal.cs only right now (but is not used externally.)
This would also require that Module is supplied separetly (or difftool handling is removed as discussed).
So not an obvious change.

File: GitUI/GitUIExtensions.cs (hunk 10 above)
Comment (gerhardol) [reply GitUI/GitUIExtensions.cs:106]: This pattern is used in many situations (this PR reduces the usage, some more with #7825).
Submodule status is not always evaluated, this checks if the async Task has been started, if so await the result on the next line. (This is the normal code path I believe.)
If not started async, the submodule status is evaluated below.

**Comment by gerhardol** [comment]
> My biggest worry with sweeping changes like this is testing. There are lots of changes not accompanied by tests.

https://github.com/gitextensions/gitextensions/pull/7926#pullrequestreview-385057653

Currently, there are six different ways to present changes, with this PR this is down to two (with #7825 change to be added after this PR there will be one).
The different implementations is part of the form code and requires a refactoring anyway to be tested.
Also, I cannot see any sane tests that could test test the migration.

File: GitUI/GitUIExtensions.cs (hunk 9 above)
Comment (RussKie) [reply GitUI/GitUIExtensions.cs:47]: Ah, I remembered we had `IFileViewer`, it was on a different type...

**Comment by gerhardol** [comment]
Rebased and added an update in relation to https://github.com/gitextensions/gitextensions/pull/7938#discussion_r403334066

Moving out logic to handle ViewPatch as text from FileViewer, to keep the logic in the ViewChangesAsync extension method

FileViewer still has logic to detect binary files, to determine how to display "git items" (image, submodules or text) and to display .patch files as patches (diffs).

**Comment by gerhardol** [comment]
@RussKie further comments?

**Comment by RussKie** [comment]
I'll have a look today.

**Comment by gerhardol** [comment]
@msftbot merge in 12 hours
