### PR TITLE
fix(File History): Do not change capitalization of filename

### LINKED ISSUE #11886: File History is empty if capitalization of path name deviates from git
### Environment

- GitExtensions version: 5.0 pre
- Git 2.46.0.windows.1

### Issue description

The File History is empty if the capitalization of the Windows path name deviates from git.
Git does not update the capitalization of path names on checkout.
In the GE repo, the folder "Setup" was renamed to "setup".
Unfortunately, the File History uses the capitalization in the file system for setting the filter - although it is called with git capitalization.

### Steps to reproduce

- clone the GE repo with checkout of commit e.g. 967ecc4b7ad5159027b91c56ec0fde616ddff87d (before the renaming in 8863b8b46fc42b416f7493eaad35138e8c80ce41)
- open File History of `setup/assets/Logo/GitExtensionsLogoWide.png`, which was changed in commit ba4deca6deca7323e278045459a8abe217892be2

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

```
GitExtensions.exe filehistory "setup/assets/Logo/GitExtensionsLogoWide.png" ba4deca6deca7323e278045459a8abe217892be2 
```

affects FormFileHistory only, i.e. with

image

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11886

## Proposed changes

- fix(FileHistory): Do not change the capitalization of filename passed on the command line
  because the filename filter of "git log" is case-sensitive
  rather keep the existing path, which has the correct capitalization if the File History is invoked by GE

### Before

image

### After

image

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/GitUICommands.cs [hunk 1]
```diff
@@ -1724,10 +1724,7 @@ private string NormalizeFileName(string fileName)
         private bool RunFileHistoryCommand(IReadOnlyList<string> args, bool showBlame)
         {
             string fileHistoryFileName = args[2];
-            if (new FormFileHistoryController().TryGetExactPath(_fullPathResolver.Resolve(fileHistoryFileName), out string exactFileName))
-            {
-                fileHistoryFileName = NormalizeFileName(exactFileName);
-            }
+            fileHistoryFileName = NormalizeFileName(fileHistoryFileName);
```
Comment (RussKie) [inline src/app/GitUI/GitUICommands.cs:1727]: Worth adding a comment?

**Review by RussKie — APPROVED** [review]
Is this something we can add a test for?

File: src/app/GitUI/GitUICommands.cs [hunk 2]
```diff
@@ -1724,10 +1724,7 @@ private string NormalizeFileName(string fileName)
         private bool RunFileHistoryCommand(IReadOnlyList<string> args, bool showBlame)
         {
             string fileHistoryFileName = args[2];
```
Comment (gerhardol) [inline src/app/GitUI/GitUICommands.cs:1726]:
```suggestion
            // Use the reported filenames (Git file may differ from Windows file system).
            string fileHistoryFileName = NormalizeFileName(args[2]);
```

**Review by gerhardol — APPROVED** [review]
