### PR TITLE
Fix theme migration bug

### LINKED ISSUE #11629: Migration of color settings creates "black" theme
### Environment

- Git Extensions 33.33.33 with #11624 included
- Build 27a3b1e4eee462accae311e882443aeaf75e7110
- Git 2.42.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.0
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

The migration of color settings creates the following `migrated.css` if the user had not configured anything.

```
.OtherTag { color: #000000}
.AuthoredHighlight { color: #000000}
.HighlightAllOccurences { color: #000000}
.Tag { color: #000000}
.Graph { color: #000000}
.Branch { color: #000000}
.RemoteBranch { color: #000000}
.DiffSection { color: #000000}
.DiffRemoved { color: #000000}
.DiffRemovedExtra { color: #000000}
.DiffAdded { color: #000000}
.DiffAddedExtra { color: #000000}
```

### Steps to reproduce

run GE on a machine without prior GE settings

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by berrs**
Fixes #11629

There is a problem in SettingsSource.GetColor. If the settings do not contain a value for the requested color, GetColor will return Color.Empty rather than the provided default color (because of how ColorTranslator.FromHtml handles empty input).

This causes the theme migration to think the colors have been updated from the default to a very goth all-black.

## Proposed changes

Fix SettingsSource.GetColor to return the default color instead of Color.Empty

## Test methodology

- Added unit test for SettingsSource.GetColor

## Test environment(s) 

- Git Extensions 33.33.33
- Build 805cf4832e6e2ad5719c04bdc07607a87be4c7f5 (Dirty)
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.3
- DPI 144dpi (150% scaling)
- Portable: False

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Settings/AppSettings.cs [hunk 1]
```diff
@@ -2104,9 +2104,12 @@ private static void ImportFromRegistry()
         [Obsolete("AppSettings is no longer responsible for colors, ThemeModule is")]
         public static Color GetColor(AppColor name)
         {
-            return SettingsContainer.GetColor(name.ToString().ToLowerInvariant() + "color", AppColorDefaults.GetBy(name));
+            return SettingsContainer.GetColor(GetColorSettingName(name), AppColorDefaults.GetBy(name));
         }
 
+        [Obsolete("AppSettings is no longer responsible for colors, ThemeModule is")]
+        public static string GetColorSettingName(AppColor color) => color.ToString().ToLowerInvariant() + "color";
```
Comment (mstv) [inline GitCommands/Settings/AppSettings.cs:2111]: Please do not publicly expose methods just for tests.
If
```suggestion
        internal static string GetColorSettingName(AppColor color) => color.ToString().ToLowerInvariant() + "color";
```
does not work, the TestAccessor pattern should be applied.
But in this case, just duplicate the regarding code in the test.

**Review by mstv — COMMENTED** [review]
Looks sensible, have not run

Could you add your sign-off to `contributors.txt`, please?

File: GitCommands/Settings/AppSettings.cs (hunk 1 above)
Comment (berrs) [reply GitCommands/Settings/AppSettings.cs]: I just removed it. The name of the setting doesn't matter really, just that it doesn't exist.

**Review by mstv — APPROVED** [review]
👍 Thank you!

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you
