### PR TITLE
Ignore difftool for CombinedDiff

### LINKED ISSUE #7087: [NBug] CombinedDiff artificial commit cannot be explicitly compare...
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentOutOfRangeException: CombinedDiff artificial commit cannot be explicitly compared: 3333333333333333333333333333333333333333, a7d7f51ed7a57322d4ebb8805d7bd4a0c9d011de
Parameter name: firstRevision
Actual value was 3333333333333333333333333333333333333333.
   at GitCommands.Git.RevisionDiffProvider.GetInternal(String firstRevision, String secondRevision, String fileName, String oldFileName, Boolean isTracked)
   at GitCommands.GitModule.OpenWithDifftool(String filename, String oldFileName, String firstRevision, String secondRevision, String extraDiffArguments, Boolean isTracked)
   at GitUI.CommandsDialogs.RevisionDiffControl.openWithDifftoolToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.PerformClick()
   at GitUI.CommandsDialogs.RevisionDiffControl.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #7087

## Proposed changes

- Ignore difftool for combined diff

## Test methodology 

- Select GE b33a12e3af16cc1164ebfa2562f06b485421fbcf
- Rightclick a file in CombinedDiff
- Verifiy that diff in menu is disabled
- Verify that nothing happens (no error or difftool) when pressing F3, Shift-F3, Shift-Alt-F3

- Select both a file in CombinedDiff and normal commit, rightclick
- Verifiy that diff in menu is disabled
- Verify that the  when pressing F3, Shift-F3, Shift-Alt-F3, that the normal diftool is shown only

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 1]
```diff
@@ -609,6 +609,13 @@ private void openWithDifftoolToolStripMenuItem_Click(object sender, EventArgs e)
 
             foreach (var itemWithParent in DiffFiles.SelectedItemsWithParent)
             {
+                if (itemWithParent.ParentRevision.Guid == GitRevision.CombinedDiffGuid)
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs]: Should we do it for all artificial commits?

Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: worktree and index is specially handled in RevisionDiffProvider, they are OK
