### PR TITLE
CommitInfo: Fixup handling of detached head

### LINKED ISSUE #10317: Support decorated HEAD
### Feature description

Since Git 2.38 (guessed), HEAD is decorated as "(HEAD detached at 13e9559ee)" in the output of some commands like
`git branch -a --contains 168acda6a7f6cfb62075557eb3d09b62058d3211`

The internal link to this "branch" in the CommitInfo does not work any longer - to be fixed.
HEAD shall be correctly recognized as itself everywhere.
The parantheses could be removed in the CommitInfo.

grafik

### Environment

- Git Extensions 33.33.33
- Build cdc4767e25cdabda1cb9959e8b1633dfd24f367b
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10317

## Proposed changes

- `LinkFactory`: Create working internal links for detached head
- `BranchComparer`: Recognize detached head as current branch

## Test methodology 

- extend tests

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

File: GitUI/CommitInfo/CommitInfo.cs [hunk 1]
```diff
@@ -809,10 +809,12 @@ internal sealed class BranchComparer : IComparer<string>
                 RegexOptions.Compiled | RegexOptions.CultureInvariant);
 
             private readonly string _currentBranch;
+            private readonly bool _isDetachedHead;
 
             public BranchComparer(string currentBranch)
             {
                 _currentBranch = currentBranch;
+                _isDetachedHead = DetachedHeadParser.IsDetachedHead(currentBranch);
```
Comment (gerhardol) [inline GitUI/CommitInfo/CommitInfo.cs:817]: Side note: DetachedHeadParser.IsDetachedHead() checks for specific patterns, all patterns with ( or space should be considered invalid and handled as detached head.
But that is separate

**Review by gerhardol — APPROVED** [review]

**Review by gerhardol — APPROVED** [review]

**Review by RussKie — APPROVED** [review]
