### PR TITLE
Fixes #7557 - Dashboard: GitHub clone shortcut missing at initial load

### LINKED ISSUE #7557: Dashboard: GitHub clone shortcut missing at initial load
## Current behaviour

The GitHub clone link is not always available in the dashboard.
The plugins are not loaded directly, the GH plugin is not loaded when the shortcuts are created.

## Expected behaviour

Consistent behavior.
Low priority issue though.

## Steps to reproduce

Open to dashboard
Refresh (F5)
Open repo, exit to dashboard

## Screenshots

Open (GitHub menu pops up after a second or so)

image

Refresh ->

image

Open repo, close to dashboard:

image

## Did this work in previous version of GitExtensions

No

## Environment

- Git Extensions 3.3.0.7791
- Build 5d804cdfaf57fa122faf7811777140369826d11b
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by lhiginbotham**
Fixes #7557 - Dashboard: GitHub clone shortcut missing at initial load

## Proposed changes

- refresh the UI when plugins are done registering
- also re-register plugins whenever setting git module to an invalid git repo (means we are going to the dashboard)

### Before

Opening straight to the dashboard has missing plugin-action entries under "Clone repository"
image

Closing out of a repo to the dashboard has missing plugin action menus
image

### After

A refresh is done when opening straight to the dashboard to render the asynchronously loaded Git-host plugins
image

Similar behavior occurs when closing out to the dashboard from a valid repo

## Test methodology 

- interactive testing with changes (launching straight from Visual Studio), compared against a clean install from my machine

## Test environment(s) 

- GIT 2.28.0.windows.1
- Windows 10

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -1938,6 +1946,7 @@ private void SetGitModule(object sender, GitModuleEventArgs e)
 
                 RevisionGrid.IndexWatcher.Reset();
                 MainSplitContainer.Visible = false;
+                RegisterPlugins();
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormBrowse.cs:1949]: We call this in the other branch too, should this be moved either before or after the if..else...?

Comment (lhiginbotham) [reply GitUI/CommandsDialogs/FormBrowse.cs:1949]: @RussKie 
Things seem to still wrok after this diff:
image

Is this a change you would like to be made?

Comment (RussKie) [reply GitUI/CommandsDialogs/FormBrowse.cs:1949]: Yep, thanks

Comment (lhiginbotham) [reply GitUI/CommandsDialogs/FormBrowse.cs]: @RussKie done!

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you
