### PR TITLE
Refresh the left panel when it's shown

### LINKED ISSUE #10284: Revision trees are empty when opening left sidebar for the first time
### Environment

- GitExtensions version: 4 / build from master
- GIT version: 2.36.1
- OS version: Windows 
- .NET version: 6

### Issue description

When starting GitExtensions **without having the left sidebar open**,
**the trees for Branches, Remotes and Tags are empty** when opening it for the first time.

Clicking the Refresh button **works around** this.

### Steps to reproduce

1. Open GitExtensions
2. Make sure the left sidebar is hidden
3. Close GitExtensions (to have those display settings saved)
4. Reopen GitExtensions
5. Open the left sidebar

### Did this work in previous version of GitExtensions?

This worked fine in version 3.5.4 .

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #10284

### After

https://user-images.githubusercontent.com/4403806/197306889-82c394e7-5fc6-4717-a4d2-097427d3cfaa.mp4

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -2933,6 +2946,11 @@ private void toggleBranchTreePanel_Click(object sender, EventArgs e)
                 new Dictionary<string, string> { { "ShowLeftPanel", MainSplitContainer.Panel1Collapsed.ToString() } });
 
             RefreshLayoutToggleButtonStates();
+
+            if (!MainSplitContainer.Panel1Collapsed)
+            {
+                RefreshLeftPanel(forceRefresh: true, new FilteredGitRefsProvider(UICommands.GitModule).GetRefs);
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/FormBrowse.cs:2952]: Refs are loaded again, but that is OK, too much hassle to save the data

**Review by gerhardol — APPROVED** [review]
Have not run

**Review by h0lg — APPROVED** [review]
Looks good to me - thanks for the quick fix!

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 1 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormBrowse.cs:2952]: You're right, but I don't think showing/hiding the left panel is something users do all the time (compared to refreshing the grid). So it shouldn't cause a lot of perf degradation.

**Comment by RussKie** [comment]
Thank you folks
