### PR TITLE
Fix #6593: GitExtension Exception resetting 1500 files in Diff tab.

### LINKED ISSUE #6593: GitExtension Exception resetting 1500 files in Diff tab
## Current behaviour
GitExtensions crashes

## Expected behaviour
No crash

## Steps to reproduce
Have a big change in working directory (1500 files)
Go to Diff tab
Select all files
Press R (Reset to index)

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<RunCommandAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.RunCommand(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow)
   at GitCommands.GitModule.CheckoutFiles(IReadOnlyList`1 files, ObjectId revision, Boolean force)
   at GitUI.CommandsDialogs.RevisionDiffControl.ResetSelectedItemsTo(Boolean actsAsChild)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.ToolStrip.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.3801.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by hieuxlu**
Work around for Windows command line length 32767 characters limitation

Fix #6593: GitExtension Exception resetting 1500 files in Diff tab.

## Proposed changes

- Work around for Windows command line length 32767 characters limitation
- Add GitArgumentBuilderExtensions.BuildBatchArguments to wrap long commands in to multiple child commands
- Add RunBatchCommand to run commands in batch 

### Before
image

### After

image

## Test methodology 

- Add GitArgumentBuilderTest fixture
- Manual test

## Test environment(s) 

- GIT: 3.2
- Windows 10 64bit

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
Seem OK to me at first look.
You probably want to submitt the contributors.txt change separately, to avoid conflicts.

File: GitExtUtils/GitArgumentBuilderExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+
+namespace GitCommands
+{
+    public static class GitArgumentBuilderExtensions
+    {
+        private const byte BASE_LENGTH = 4; // 'git '
```
Comment (mstv) [inline GitExtUtils/GitArgumentBuilderExtensions.cs]: I haven't digged into how git is called exactly.
Is this really necessary? I.e., doesn't "git" be part of the executable to be started?
Isn't the full path to `git.exe` prepended if specified in the settings? Does the limit apply to arguments string or to the complete command line? It depends on how `CreateProcess` is called by .NET.

File: UnitTests/GitExtUtils/GitArgumentBuilderExtensionsTest.cs [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+
+namespace GitExtUtilsTests
+{
+    [TestFixture]
+    public class GitArgumentBuilderExtensionsTest
+    {
+        // 17: 'git checkout name1'
+        [TestCase("checkout", new string[] { "name1", "name2", "name3" }, 21, new string[] { "checkout name1", "checkout name2", "checkout name3" })]
+        [TestCase("checkout", new string[] { "name1", "name2", "name3" }, 22, new string[] { "checkout name1", "checkout name2", "checkout name3" })]
+        [TestCase("checkout", new string[] { "name1", "name2", "name3" }, 27, new string[] { "checkout name1 name2", "checkout name3" })]
```
Comment (mstv) [inline UnitTests/GitExtUtils/GitArgumentBuilderExtensionsTest.cs]: I would prefer to test the exact thresholds.

File: GitExtUtils/GitArgumentBuilderExtensions.cs (hunk 1 above)
Comment (hieuxlu) [reply GitExtUtils/GitArgumentBuilderExtensions.cs]: This says if we specify application name, then commandline can exclude executable module part. I'll check on how the process is called.

https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw#parameters

Comment (hieuxlu) [reply GitExtUtils/GitArgumentBuilderExtensions.cs]: C# implementation of `System.Diagnostic.Process` always combine application name in command line argument, and always add quotation + ' ' characters, so I modified the code to handle all that.
Reference source code: https://referencesource.microsoft.com/#system/services/monitoring/system/diagnosticts/Process.cs,1952

File: UnitTests/GitExtUtils/GitArgumentBuilderExtensionsTest.cs (hunk 2 above)
Comment (hieuxlu) [reply UnitTests/GitExtUtils/GitArgumentBuilderExtensionsTest.cs]: Test case for exact thresholds are added in `ExecutableExtensionsTests` fixture, which will call the actual `Process`. This only performs unit testing for the builder extensions.

**Comment by hieuxlu** [comment]
@gerhardol I resolved the conflicts, do I still need a separate PR for `contributor.txt`?
@mstv Please review again.

**Comment by RussKie** [comment]
> do I still need a separate PR for `contributor.txt`?

It is better to do a separate PR, as it may time to fully review and test this change, if another contributor provides a sign off in the interim - it will set this PR in a conflict state again.

**Comment by RussKie** [comment]
I had a brief look at the change - 👍 

To test - do I generate 1,5K files with a reasonably long name and then try to stage all at once?

**Comment by hieuxlu** [comment]
Yes, clone a really long files name, 1000 files, each > 40 characters. A for loop with echo would suffice. After that, reset the file to selected commit in Diff view to test. Staging does not cause crashing, just slow. The bug is in Diff view (and probably many other places).

**Comment by gerhardol** [comment]
> To test - do I generate 1,5K files with a reasonably long name and then try to stage all at once?

Just move all contents in a repo to a new folder

File: UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs [hunk 3]
```diff
@@ -64,5 +67,38 @@ public void GetOutput_with_cache_miss()
...
+            // Execute process
+            var exe = new Executable("cmd.exe");
+            var args = new ArgumentBuilder() { "/C echo" }
+                .BuildBatchArguments(new string[]
+                {
+                    GenerateStringByLength(arg1Len),
+                    GenerateStringByLength(arg2Len)
+                }, baseLength);
+
+            exe.RunBatchCommand(args);
```
Comment (mstv) [inline UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs]: Please check the return value.

File: GitCommands/Git/ExecutableExtensions.cs [hunk 4]
```diff
@@ -141,6 +141,31 @@ string ComposeOutput()
...
+        /// <param name="createWindow">A flag indicating whether a console window should be created and bound to the process.</param>
+        /// <returns><c>true</c> if the process's exit code was zero, otherwise <c>false</c>.</returns>
+        [MustUseReturnValue("Callers should verify that " + nameof(RunBatchCommand) + " returned true")]
+        public static bool RunBatchCommand(
+            this IExecutable executable,
+            ArgumentString[] batchArguments,
+            byte[] input = null,
+            bool createWindow = false)
+        {
+            // TODO: Process somehow always return non-zero exit code.
```
Comment (mstv) [inline GitCommands/Git/ExecutableExtensions.cs]: I'm afraid, the limit is lower. The Win32 API doc says: If the executable is left empty and added to the arguements, the length limit was `MAXPATH`.
`[TestCase(8193 - 1 - 19, 1, 10)]` is the maximum that succeeds.

File: GitCommands/Git/ExecutableExtensions.cs [hunk 5]
```diff
@@ -141,6 +141,31 @@ string ComposeOutput()
...
+            return batchArguments.Aggregate(true, (result, arguments) => result && executable.RunCommand(arguments, input, createWindow));
```
Comment (mstv) [inline GitCommands/Git/ExecutableExtensions.cs]: `result && executable.RunCommand(...)`: In C/C++, the function would never be called due to the lazy evaluation of logical expressions and because `result` is initialized with `true`. Though C# seems to work differently: In the debugger, I can see that `RunCommand` _is_ called. @gitextensions/git-extensions-source, can we rely on it?

File: GitCommands/Git/ExecutableExtensions.cs (hunk 4 above)
Comment (hieuxlu) [reply GitCommands/Git/ExecutableExtensions.cs]: `MAXPATH` length limit in Win32 API doc is for full path of the `git.exe` executable module, whereas `lpCommandLine` max length is always `32,768 characters, including the Unicode terminating null character`. Real test leaves us at `short.MaxValue - 1 // 32766` though.
>
> `lpCommandLine`
> The maximum length of this string is 32,768 characters, including the Unicode terminating null character. If `lpApplicationName` is NULL, the module name portion of `lpCommandLine` is limited to MAX_PATH characters.
>

The TODO was left here because in the test case `cmd.exe /C echo` always return non-zero exit code. In debug, `git.exe` returns correctly, so this is for the test case only. I will investigate the test case and resolve this.

File: GitCommands/ArgumentBuilderExtensions.cs [hunk 6]
```diff
@@ -300,5 +301,67 @@ public static void Add(this ArgumentBuilder builder, [CanBeNull, ItemCanBeNull]
...
+        public static ArgumentString[] BuildBatchArguments(this ArgumentBuilder builder, IEnumerable<string> arguments, int baseLength, int maxLength = short.MaxValue)
+        {
+            var baseCommand = builder.ToString();
+            if (baseCommand.Length + baseLength >= maxLength)
+            {
+                throw new ArgumentException($"Git base command \"{baseCommand}\" always reached max length of {maxLength} characters.", nameof(baseCommand));
+            }
+
+            // Clone command as argument builder
+            var tmpBuilder = new ArgumentBuilder() { baseCommand };
```
[the remark this answers is not in the document]
Comment (hieuxlu) [reply GitCommands/ArgumentBuilderExtensions.cs]: Originally, I want to reuse the cloned builder. On second though, this is not needed though, as a new builder is always created when command length reaches limit. So we can use the input builder.

File: GitCommands/Git/ExecutableExtensions.cs (hunk 5 above)
Comment (hieuxlu) [reply GitCommands/Git/ExecutableExtensions.cs]: I'm gonna change this to a for loop, both for clarity and for batch progress callback needed in #7237.

File: UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs (hunk 3 above)
Comment (hieuxlu) [reply UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs]: Yeah the TODO above should have been left here. Will do.

File: GitCommands/Git/ExecutableExtensions.cs (hunk 4 above)
Comment (mstv) [reply GitCommands/Git/ExecutableExtensions.cs]: Yes, you're right. It seems to be a limitation of the length of `<command>` in `cmd /c <command>`.

File: GitCommands/ArgumentBuilderExtensions.cs [hunk 7]
```diff
@@ -300,5 +301,67 @@ public static void Add(this ArgumentBuilder builder, [CanBeNull, ItemCanBeNull]
...
+                    // Return new argument builder
+                    return new ArgumentBuilder() { baseCommand, value };
+                }
+
+                curr.Add(value);
+                return curr;
+            });
+
+            // Handle rare case when last argument length exceed max length
+            if (argBuilder.Length >= maxLength)
```
[the remark this answers is not in the document]
Comment (mstv) [reply GitCommands/ArgumentBuilderExtensions.cs]: Extend the NUnit tests, please.

[the remark this answers is not in the document]
Comment (hieuxlu) [reply GitCommands/ArgumentBuilderExtensions.cs]: Sorry, had to gone to work, GMT+7. 8 more test cases with baselength added.

File: GitCommands/ArgumentBuilderExtensions.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (hieuxlu) [reply GitCommands/ArgumentBuilderExtensions.cs]: It turned out this was correct. I want to use ArgumentBuilder.Length, to get the full command length without calling ToString(). GitArgumentBuilder.Length is not reliable. So we had to clone a new base type instance here.

File: GitCommands/Git/ExecutableExtensions.cs (hunk 4 above)
Comment (hieuxlu) [reply GitCommands/Git/ExecutableExtensions.cs]: You're right, I need to find another executable to test, `cmd.exe` command line length limitation is `8191` characters.
https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation

File: UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs (hunk 3 above)
Comment (hieuxlu) [reply UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs]: Done checking the return value, both `true` and `false`

File: GitCommands/Git/ExecutableExtensions.cs (hunk 4 above)
Comment (hieuxlu) [reply GitCommands/Git/ExecutableExtensions.cs]: I pass max length `8191` into the test case and everything works find now. About order execution of and branch, I've switch function execution before boolean var, so in any language (C/C++), it would look logical.

File: GitCommands/Git/ExecutableExtensions.cs (hunk 5 above)
Comment (hieuxlu) [reply GitCommands/Git/ExecutableExtensions.cs]: I've switched function execution before boolean var, so in any language (C/C++), it would look logical now. The for loop change would be in another PR.

**Comment by hieuxlu** [comment]
@mstv Clarified all your questions. They're all great questions, thanks.

File: UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs [hunk 8]
```diff
@@ -71,9 +71,15 @@ public void GetOutput_with_cache_miss()
...
-        public void RunBatchCommand_can_handle_max_length_arguments(int arg1Len, int arg2Len, int baseLength)
+        // 1: ' ' character
+        // cmd.exe max length is 8191, including NULL Unicode -> 8189
+        // https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation
+        [TestCase(8189 - 1 - 18, 8189 - 1 - 18, 10, 8191, true)]
+        [TestCase(8189 - 1 - 19, 1, 10, 8191, true)]
+        [TestCase(8189 - 1 - 18, 8189 - 1 - 18, 10, 32767, true)]
+        [TestCase(8189 - 1 - 19, 1, 10, 32767, true)]
+        public void RunBatchCommand_can_handle_max_length_arguments(int arg1Len, int arg2Len, int appLength,
+            int maxLength, bool expectedResult)
```
Comment (mstv) [inline UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs]: I liked the attempt to test the maximum length of a command line.
You could switch to `sh.exe -c "echo abc..."`. This executable should exist in `AppSettings.GitBinDir`.

Comment (hieuxlu) [reply UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs]: When I run NUnit on my local machine, it resolves GitExtensions.Setting to `\AppData\Roaming\Microsoft Corporation\Microsoft.TestHost.x86\` instead of  `\AppData\Roaming\GitExtensions\GitExtensions`. How can I fix this?

Comment (mstv) [reply UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs]: That's a pity. There must be other NUnit tests which access the Git executable. These must access the GE settings, too. I haven't digged into this area yet.

Comment (hieuxlu) [reply UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs]: I've searched all the codes, they've only access `AppSettings` for setting bits that are not dependent on `Application.UserAppDataPath`, such as `AppSettings.AvatarImageCachePath`.

I've tried to manually create `SettingContainers` as below, but somehow it can't load settings in the correct folder.
```CSharp
var settingPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "GitExtensions\\GitExtensions");
var settingContainer = new RepoDistSettings(null, GitExtSettingsCache.Create(settingPath), SettingLevel.Unknown);
// gitbindir is always null
var appPath = Path.Combine(settingContainer.GetString("gitbindir", ""), "sh.exe");
```

Comment (hieuxlu) [reply UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs]: My bad, I've got it working. Correct `"GitExtensions\\GitExtensions"` to `"GitExtensions\\GitExtensions\\GitExtensions.settings"`. Works fine now.

Comment (hieuxlu) [reply UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs]: @mstv `sh.exe -c echo "abcd..."` will show below error at `32752` characters, `15` char short vs docs.
> 
> error launching git: The filename or extension is too long.
> 
Does that mean internally, sh.exe is launching `git`?

On the other hand, `git.exe reset -- "abcd..."` will correctly work until `35765` character (tested by create a batch script and execute it) with `%ERRORLEVEL% = 0`. However, when run in unit test, this command always returns non-zero exit code regardless of command length.

So I'm stuck at unit testing the exact threshold at the moment. `sh.exe` won't reach it, `git.exe` always return non-zero exit code.

Comment (hieuxlu) [reply UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs]: I was able to resolve the above issue, by setting `workingDir` of `git.exe` executable to local git repository using current Assembly location. Commited changes and passed test case with exact threshold of `32766` characters

**Comment by pmiossec** [comment]
A lot of work. Well done!

**Comment by hieuxlu** [comment]
@mstv Done. (using GitExtensions)
@pmiossec Thought I was doing my fulltime job!

**Comment by mstv** [comment]
@msftbot merge in 10 hours if approved twice

**Comment by mstv** [comment]
@msftbot merge in 10 hours, if two approvals

**Comment by mstv** [comment]
@msftbot merge in 10 hours, if at least 2 approvals

File: GitCommands/ArgumentBuilderExtensions.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/ArgumentBuilderExtensions.cs]: > GitArgumentBuilder.Length is not reliable. 

Could you please elaborate on why it isn't reliable?

[the remark this answers is not in the document]
Comment (hieuxlu) [reply GitCommands/ArgumentBuilderExtensions.cs]: GitBuilderArgument.Length is not the whole command length. Its length can only be determined after a ToString() call.

**Comment by hieuxlu** [comment]
@RussKie I answered your question about using a cloned builder. Is there anything else you concern about?

File: GitCommands/ArgumentBuilderExtensions.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/ArgumentBuilderExtensions.cs]: Can you please elaborate as I don't believe this claim is correct.
I have added a set of tests in https://github.com/gitextensions/gitextensions/pull/7251 and everything works as expected

**Comment by RussKie** [comment]
@msftbot please ignore

**Comment by RussKie** [comment]
@msftbot forget everything I just told you

File: GitCommands/ArgumentBuilderExtensions.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (hieuxlu) [reply GitCommands/ArgumentBuilderExtensions.cs]: @RussKie  The test was fore `ArgumentBuilder`. I'm saying `GitArgumentBuilder`, which is a derived class. You can try the fixture `GitArgumentBuilderTests`. `GitArgumentBuilder` can be initialized with a git command like `reset` or `config`. In that case, its `Lengths` is 0, while actual length is not.

**Comment by hieuxlu** [comment]
@RussKie I removed dependency on `ArgumentBuilder.Length`, thus remove extra allocation. There is no reference to this property in the entire source code now, we can safely remove this property now.

File: UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs [hunk 9]
```diff
@@ -9,11 +17,27 @@ namespace GitCommandsTests.Git
...
+            var userAppDataPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
+            var settingPath = Path.Combine(userAppDataPath, "GitExtensions\\GitExtensions\\GitExtensions.settings");
+            var settingContainer = new RepoDistSettings(null, GitExtSettingsCache.FromCache(settingPath), SettingLevel.Unknown);
+            _appPath = Path.Combine(settingContainer.GetString("gitbindir", ""), "git.exe");
+
+            // Execute process in GitExtension working directory, so that git will return success exit-code
+            // git always return non-zero exit code when run git reset outside of git repository
+            // NUnit working directory always default to MS test host
+            var workingDir = Path.GetDirectoryName(Assembly.GetAssembly(typeof(ExecutableExtensionsTests)).Location);
+            _gitExecutable = new Executable(_appPath, workingDir);
```
Comment (drewnoakes) [inline UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs]: Why do these tests need the actual `git.exe` path? I think this should be mocked out, making all the env var stuff redundant.

File: GitCommands/ArgumentBuilderExtensions.cs [hunk 10]
```diff
@@ -300,5 +301,68 @@ public static void Add(this ArgumentBuilder builder, [CanBeNull, ItemCanBeNull]
...
+        /// Implementation by <see cref="System.Diagnostics.Process"/> will have file path included in command line arguments,
+        /// as well as added quotation and space characters, so we need base length to account for all these added characters
+        /// <see href="https://referencesource.microsoft.com/#system/services/monitoring/system/diagnosticts/Process.cs,1944"/>
+        /// </summary>
+        /// <param name="builder">Argument builder instance.</param>
+        /// <param name="arguments">Arguments.</param>
+        /// <param name="baseLength">Base executable file and command line length.</param>
+        /// <param name="maxLength">Command line max length. Default is 32767 - 1 on Windows.</param>
+        /// <returns>Array of batch arguments split by max length.</returns>
+        public static ArgumentString[] BuildBatchArguments(this ArgumentBuilder builder, IEnumerable<string> arguments, int baseLength, int maxLength = short.MaxValue)
```
Comment (drewnoakes) [inline GitCommands/ArgumentBuilderExtensions.cs]: Doesn't this duplicate a bunch of stuff proposed in #7237? Which are you recommending?

**Comment by drewnoakes** [comment]
This change will cause more instances of bug #3280.

**Comment by drewnoakes** [comment]
Can we close this and focus on #7237 instead please? If there's a change here that's not in #7237 too, can you add it there too? The duplication makes reviewing difficult.

File: UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs (hunk 9 above)
Comment (hieuxlu) [reply UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs]: After discussion with @mstv, I think testing with actual `git.exe` is valid, because we want to see the `Win32Exception` when command line reaches actual threshold. If we don't test this, we would not be able to see differences of max command line length for each executable. For example, `cmd.exe` has a limit of `8191` characters, while `sh.exe` is limited at `32710` instead of `32767` characters. So testing againt `git.exe` would ensure we have correct understanding of `git` command line max length on Windows.

File: GitCommands/ArgumentBuilderExtensions.cs (hunk 10 above)
Comment (hieuxlu) [reply GitCommands/ArgumentBuilderExtensions.cs]: For #6593 this is the smallest viable amount of code. For #7237, we need to add BatchProgress callback, so if each PR would do only its purpose. I think we should focus on this before #7237.

**Comment by hieuxlu** [comment]
> Can we close this and focus on #7237 instead please? If there's a change here that's not in #7237 too, can you add it there too? The duplication makes reviewing difficult.

I think we should finish this before #7237. That's why #7237 is marked as WIP. #7237 is extending this, not overwriting.

**Comment by drewnoakes** [comment]
> I think we should finish this before #7237. That's why #7237 is marked as WIP. #7237 is extending this, not overwriting.

Fair enough. @RussKie tagged me on #7237 so I saw and commented there first. Please consider my review there as applying here.

**Comment by hieuxlu** [comment]
> Fair enough. @RussKie tagged me on #7237 so I saw and commented there first. Please consider my review there as applying here.

I did cherrypick all the suggested changes from #7237 and vice versa.

**Comment by gerhardol** [comment]
@RussKie @drewnoakes 
Any more comments here, should it be merged?
@hieuxlu Good work. Please rebase on mater and squash before it is merged

**Comment by hieuxlu** [comment]
> @hieuxlu Good work. Please rebase on mater and squash before it is merged

Done. Glad I could contribute back. Been using this software for 5 years and counting.

**Comment by RussKie** [comment]
@msftbot merge in 24 hours
