### PR TITLE
fix: Rebase specific range no more select the good 'to' branch

### LINKED ISSUE #3472: [Regression] Rebase specific range no more select the good 'to' branch
In `master` branch (it works well with current state of `release/2.49` which is `10cd10875dae73c92606a0d2f09a8de70b9198c9`), when you do a rebase, by selecting a specific range, GitExtensions fail to select the good branch and instead remains to the first item in the listbox.

You could see on this image, the value selected in the 'to' listbox which should have been `refs/heads/master`.
gitextensions_bug_rebase

Indeed, when select the default choice, some bad things happens....

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #3472

image

### CODE REVIEW

File: GitUI/CommandsDialogs/FormRebase.cs [hunk 1]
```diff
@@ -59,16 +60,18 @@ private void FormRebaseLoad(object sender, EventArgs e)
...
 
             if (_defaultBranch != null)
                 Branches.Text = _defaultBranch;
 
             Branches.Select();
 
+            refs = Module.GetRefs(true, true).OfType<GitRef>().ToList();
+            cboTo.DataSource = refs;
             cboTo.DisplayMember = "Name";
-            cboTo.DataSource = Module.GetRefs(false, true);
```
Comment (jbialobr) [inline GitUI/CommandsDialogs/FormRebase.cs]: Is it done on purpose?: Module.GetRefs(**false**, true);

Comment (RussKie) [inline GitUI/CommandsDialogs/FormRebase.cs]: I'm guessing this is a result of bad copy-paste... I'll fix it up

Comment (RussKie) [inline GitUI/CommandsDialogs/FormRebase.cs]: Put a PR #3608 with a fix
