### PR TITLE
FormReflog : fix crash when switching from reference

### LINKED ISSUE #7410: [NBug] Index non compreso nell'intervallo. Richiesto valore non ne...
## Current behaviour
Crash and quit.

## Expected behaviour
No crash and no quit.

## Steps to reproduce
Switched the reflog reference combobox and then I went on the grid.

## Error Details
```
System.ArgumentOutOfRangeException: Index non compreso nell'intervallo. Richiesto valore non negativo e minore della dimensione della raccolta.
Nome parametro: index
   in System.Collections.ArrayList.get_Item(Int32 index)
   in System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
   in System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
   in GitUI.CommandsDialogs.FormReflog.gridReflog_MouseMove(Object sender, MouseEventArgs e)
   in System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   in System.Windows.Forms.DataGridView.OnMouseMove(MouseEventArgs e)
   in System.Windows.Forms.Control.WmMouseMove(Message& m)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information

### PR DESCRIPTION
**Pull request by pmiossec**
`_lastHitRowIndex` contained a bad value after the switch
and could be higher than the number of rows.

This commit:

 * reset the value when reference selected is changed
 * add a control to prevent it to occur again if it contains a bad value

Fixes #7410

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 3.3.0
- Build 3b399511bbbc2cb6c1e65e13850a456c7a1ffdb8
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4042.0
- DPI 192dpi (200% scaling)

### CODE REVIEW

File: GitUI/CommandsDialogs/FormReflog.cs [hunk 1]
```diff
@@ -174,7 +175,11 @@ private void gridReflog_MouseMove(object sender, MouseEventArgs e)
...
             if (hit.Type == DataGridViewHitTestType.Cell && _lastHitRowIndex != hit.RowIndex)
             {
-                gridReflog.Rows[_lastHitRowIndex].Selected = false;
+                if (_lastHitRowIndex < gridReflog.Rows.Count)
+                {
+                    gridReflog.Rows[_lastHitRowIndex].Selected = false;
+                }
+
                 _lastHitRowIndex = hit.RowIndex;
                 gridReflog.Rows[_lastHitRowIndex].Selected = true;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormReflog.cs]: Are we sure `_lastHitRowIndex` here is within the array bounds?

Comment (pmiossec) [reply GitUI/CommandsDialogs/FormReflog.cs]: We are never sure with software but we can reasonably think that yes and that Winforms return the row index that is under the mouse... That works well at the moment.

**Comment by mstv** [comment]
@msftbot merge in 16 hours
