### PR TITLE
Fixes #8348. Allow to create patch for the root commit.

### LINKED ISSUE #8348: Unable to "Format patch" of first commit
## Current behaviour

Patch error dialog pops up with the message "Unable to to create patch file(s)".

## Expected behaviour

Patch file created without error.

## Steps to reproduce

1) Select "Format patch..." from the "Commands" drop down menu.
2) Select the first commit.  The one at bottom of the list (the initial commit).
3) Click the "Create patch(es)" button

## Did this work in previous version of GitExtensions

Doubt it previously worked.  But I don't actually know.

## Environment

- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

### PR DESCRIPTION
**Pull request by veremenko-y**
Fixes #8348

## Proposed changes

If base commit is not defined, use `--root` argument to create patch for root or orphaned comit.

## Test methodology 

- Tested on empty repository with one commit
- Tested with non root commits. Merges and single ones.
- Added additional test case for when `from` is empty.

## Test environment(s)

- GIT  2.27.0.windows.1
- Windows 10 1909

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -1364,7 +1364,8 @@ public string FormatPatch(string from, string to, string output, int? start = nu
                 {
                     "-M -C -B",
                     { start != null, $"--start-number {start}" },
-                    $"{from.Quote()}..{to.Quote()}",
+                    { !string.IsNullOrEmpty(from), $"{from.Quote()}..{to.Quote()}" },
+                    { string.IsNullOrEmpty(from), $"--root {to.Quote()}" },
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs:1368]:
```suggestion
                    { !string.IsNullOrEmpty(from), $"{from.Quote()}..{to.Quote()}", $"--root {to.Quote()}" },
```

I prefer the normal outcome first here, others may prefer a non negated test

Comment (veremenko-y) [reply GitCommands/Git/GitModule.cs:1368]: I can just make an if outside the initializer, to make it clearer. Thoughts?

Comment (veremenko-y) [reply GitCommands/Git/GitModule.cs]: Fixed as requested for now.

**Comment by vbjay** [comment]
I just added a script.

git rebase --root -i

**Comment by veremenko-y** [comment]
> I just added a script. git rebase --root -i

I'm not following.

**Comment by vbjay** [comment]
Go to settings. Look at the scripts settings.

**Comment by veremenko-y** [comment]
I don't see how it helps with "Format patch" function failing to create one.

**Comment by gerhardol** [comment]
>> I just added a script.

> I don't see how it helps with "Format patch" function failing to create one.

I interpret the comment as "use scripts instead of changing the code".
This change does have a merit though, a user do not understand why a patch cannot be created. Scripts could replace a lot of GE core functionality if going to the extreme, but the user interface would be horrible (better to use Git directly). 
I do not believe that the importance is high for the PR, but it is well motivated.

**Comment by gerhardol** [comment]
@msftbot merge in 24 hours

**Comment by vbjay** [comment]
Can a rebase --root patch apply to a clone of the current repo?
