### PR TITLE
fix(AnsiEscapeUtilities): Limit error tracing

### LINKED ISSUE #11774: Traces "New start marker without end for grep" need to be limited
### Environment

- GitExtensions version: vNext

### Issue description

Modifications (patch display) of colored `.diff` files like `UnitTests/GitCommands.Tests/Patches/testdata/color.diff` cause the parser to trace a lot of errors.

### Steps to reproduce

View the new file `UnitTests/GitCommands.Tests/Patches/testdata/color.diff` as patch using 34acebeb7f77e3c5632c89fee2782a96d3f41153 or modify it.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11774

## Proposed changes

- `AnsiEscapeUtilities.ParseEscape`: Limit error tracing

### Before

you don't want to see it

### After

```
New start marker without end for grep (270, 308) in:
diff --git a/UnitTests/GitCommands.Tests/Patches/testdata/color.diff b/UnitTests/GitCommands.Tests/Patches/testdata/color.diff
new file mode 100644
index 000000000..0bfb32613
--- /dev/null
+++ b/UnitTests/GitCommands.Tests/Patches/testdata/color.diff
[36m@@ -0,0 +1,325 @@[m
[38;2;0;0;0;48;2;200;255;200m+[1mdiff --git a/GitCommands/Patches/PatchProcessor.cs b/GitCommands/Patches/PatchProcessor.cs[m[m
[38;2;0;0;0;48;2;200;255;200m+[1mindex 70b40..c1e6c 100644[m[m
[38;2;0;0;0;48;2;200;255;200m+[1m--- a/GitCommands/Patches/PatchProcessor.cs[m[m
[38;2;0;0;0;48;2;200;255;200m+[1m+++ b/GitCommands/Patches/PatchProcessor.cs[m[m
[38;2;0;0;0;48;2;200;255;200m+[36m@@ -15,19 +15,29 @@[m [mprivate enum PatchProcessorState[m[m
[38;2;0;0;0;48;2;200;255;200m+             OutsidePatch[m[m
[38;2;0;0;0;48;2;200;255;200m+         }[m[m
[38;2;0;0;0;48;2;200;255;200m+ [m[m
<snip />
[38;2;0;0;0;48;2;200;255;200m+ }[m[m


New start marker without end for grep (362, 440)

New start marker without end for grep (389, 507)

```
## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/Editor/Diff/AnsiEscapeUtilities.cs [hunk 1]
```diff
@@ -114,8 +114,9 @@ public static void PrintColors(StringBuilder sb, List<TextMarker> textMarkers)
     /// <param name="text">The text to parse.</param>
     /// <param name="sb">StringBuilder to appened the text with with the escape sequences removed.</param>
     /// <param name="textMarkers">Detected and current started highlight info for the document.</param>
-    public static void ParseEscape(string text, StringBuilder sb, List<TextMarker> textMarkers, bool themeColors = false)
+    public static void ParseEscape(string text, StringBuilder sb, List<TextMarker> textMarkers, bool themeColors = false, bool traceErrors = true)
```
Comment (mstv) [inline src/app/GitUI/Editor/Diff/AnsiEscapeUtilities.cs:117]: Needed for #10307

**Review by gerhardol — APPROVED** [review]
