### PR TITLE
Static code analysis with PVS studio

### LINKED ISSUE #5604: Static analysis with PVS Studio
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
A number of issues seen in a static check with PVS Studio

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
As reported here:
https://www.viva64.com/en/b/0440/
(Unfortunately, no GE was not notified by this investigation).

An analysis on the current code basis shows similar issues. Some seem to be introduced since last major release too.
An example (PVS issue numbers):
 * V3083 null exception calling handlers
 * V3095 object used before null check
 * V3041 implicit int cast causes fractional loss
 * V3022 expression is always false
    - Check for Git running did ignore output
 * V3027 Variable used before null check

Except for the Git  running check, the issues should cause exceptions instead of proper error messages.
Most of the changes are just for unclear code, even removing duplicate checks.

**What is the expected behavior?**
Few ststic errors.

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: master

**Did this work in previous version of GitExtensions (which)?**
no

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #5604

Changes proposed in this pull request:
Static analysis of code with PVS Studio.
See the issue for a discussion.

This is done with the demo license, so I am running out of clicks (how demo is licensed) and evaluation time eventually.
 
Screenshots before and after (if PR changes UI):
n/a

What did I do to test the code and ensure quality:
- Manual tests - most changes cannot be provoked though

Code review should be sufficient
Note: Similar PRs for submodules. None of those should be critical, but they decrease the noise when analyzing the solution if someone else tries out PVS Studio.

Has been tested on (remove any that don't apply):
- GIT 2.19.1 and above
- Windows 10

### CODE REVIEW

File: GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -3728,7 +3728,7 @@ public bool IsRunningGitProcess()
             var cmd = Path.Combine(AppSettings.GitBinDir, "ps");
             var lines = new Executable(cmd).GetOutput("x").Split('\n');
 
-            if (lines.Length >= 2)
+            if (lines.Length <= 2)
```
Comment (gerhardol) [inline GitCommands/Git/GitModule.cs]: The output from ps was not used previously

File: GitUI/CommandsDialogs/SettingsDialog/Pages/ControlHotkeys.cs [hunk 2]
```diff
@@ -96,7 +94,7 @@ private void UpdateListViewItems(HotkeySettings setting)
                     if (cmd != null)
                     {
                         listMappings.Items.Add(
-                            new ListViewItem(new[] { cmd.Name, cmd.KeyData.ToText() ?? _hotkeyNotSet.Text })
+                            new ListViewItem(new[] { cmd.Name, cmd.KeyData.ToText() })
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/ControlHotkeys.cs]: KeyData is never null

File: GitUI/Script/ScriptRunner.cs [hunk 3]
```diff
@@ -145,7 +145,6 @@ private static bool RunScript(IWin32Window owner, GitModule module, ScriptInfo s
                 else if (option.StartsWith("{s") && selectedRevision == null && revisionGrid != null)
                 {
                     allSelectedRevisions = revisionGrid.GetSelectedRevisions();
-                    allSelectedRevisions.Reverse(); // Put first clicked revisions first
```
Comment (gerhardol) [inline GitUI/Script/ScriptRunner.cs]: Line without any effect, also array has correct order already

File: GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs [hunk 4]
```diff
@@ -110,7 +110,7 @@ private void FireSettingsPageSelectedEvent(TreeNode node)
                     }
                 }
 
-                SettingsPageSelected(this, new SettingsPageSelectedEventArgs { SettingsPage = page, IsTriggeredByGoto = _isSelectionChangeTriggeredByGoto });
+                SettingsPageSelected?.Invoke(this, new SettingsPageSelectedEventArgs { SettingsPage = page, IsTriggeredByGoto = _isSelectionChangeTriggeredByGoto });
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs]: The handler could be null after the check

File: GitUI/UserControls/WaitSpinner.cs [hunk 5]
```diff
@@ -130,8 +130,8 @@ protected override void OnPaint(PaintEventArgs e)
                 ref var angle = ref _angles[p];
                 e.Graphics.FillEllipse(
                     _brushes[i],
-                    (_centre.X - (_dotRadius / 2)) + (_circleRadius * angle.cos),
-                    (_centre.Y - (_dotRadius / 2)) + (_circleRadius * angle.sin),
+                    (_centre.X - (_dotRadius / 2f)) + (_circleRadius * angle.cos),
+                    (_centre.Y - (_dotRadius / 2f)) + (_circleRadius * angle.sin),
```
Comment (gerhardol) [inline GitUI/UserControls/WaitSpinner.cs]: Loss of precision

File: Plugins/GitUIPluginInterfaces/ObjectId.cs [hunk 6]
```diff
@@ -104,22 +104,14 @@ public static bool TryParse([CanBeNull] string s, int offset, out ObjectId objec
...
-            if (success)
-            {
-                objectId = new ObjectId(i1, i2, i3, i4, i5);
-                return true;
-            }
-
-            objectId = default;
-            return false;
+            objectId = new ObjectId(i1, i2, i3, i4, i5);
+            return true;
```
Comment (gerhardol) [inline Plugins/GitUIPluginInterfaces/ObjectId.cs]: Some temp testing code that should have been removed (or check added @drewnoakes ?)

**Comment by gerhardol** [comment]
Conemu update to be reverted

**Comment by drewnoakes** [comment]
Please hold off on merging during the GitHub outage. It's not clear whether feedback is being received.

File: GitUI/UserControls/WaitSpinner.cs (hunk 5 above)
Comment (drewnoakes) [reply GitUI/UserControls/WaitSpinner.cs]: See previous commend about subpixel rendering. At 96dpi this probably makes things look fuzzy.

File: Plugins/Statistics/GitImpact/ImpactControl.cs [hunk 7]
```diff
@@ -362,7 +362,7 @@ private void UpdatePathsAndLabels()
                     h_max = Math.Max(h_max, y);
 
                     // Add week date label
-                    _weekLabels.Add((new PointF(x + (BlockWidth / 2), y), weekDate));
+                    _weekLabels.Add((new PointF(x + (BlockWidth / 2f), y), weekDate));
```
Comment (drewnoakes) [inline Plugins/Statistics/GitImpact/ImpactControl.cs]: Ditto.

File: GitUI/UserControls/WaitSpinner.cs (hunk 5 above)
Comment (drewnoakes) [reply GitUI/UserControls/WaitSpinner.cs]: See previous comment about subpixel rendering. At 96dpi this probably makes things look fuzzy.

**Comment by RussKie** [comment]
do you want me to rewrite the history on that one?

**Comment by gerhardol** [comment]
> do you want me to rewrite the history on that one?

I am not ashamed of that change, so I will make a new PR in the subrepo, merge that and update this PR.
(We can live with noise like this.)

File: Plugins/Statistics/GitImpact/ImpactControl.cs (hunk 7 above)
Comment (gerhardol) [reply Plugins/Statistics/GitImpact/ImpactControl.cs]: Skipping ImpactControl (a not much used plugin, looks OK to me), just WaitSpinner.

This change puts the small circles closer to the "outer circle". The cos/sin part should make the fraction differ some anyway, this will make no difference.
This is what it looks like after the change:
image

To closer see that images cannot be put on center I used radius 3, the small circles are fuzzy:
image

The difference to the original (correct size 8) is very small, (you cannot really see that the circles are offset), but they look the same as after the change:
image

A better way is to align the middle of the small circle to a border: 
image

`                e.Graphics.FillEllipse(
                    _brushes[i],
                    (int)Math.Round((_centre.X - (_dotRadius / 2f)) + (_circleRadius * angle.cos)),
                    (int)Math.Round((_centre.Y - (_dotRadius / 2f)) + (_circleRadius * angle.sin)),
                    _dotRadius,
                    _dotRadius);
`

I suggest this is kept as is in the PR

**Comment by RussKie** [comment]
Let's merge it once #5610 is merged

**Comment by RussKie** [comment]
Go for it
