### PR TITLE
UI tweaks for v3

### LINKED ISSUE #3072: Remember Split View Layout?
Is it possible to remember the visibility of the split view? I mostly want this view hidden, but every time I turn it off, on the next restart of the application, I have to re-hide it. Could my last setting of the layout be remembered?

### LINKED ISSUE #3978: White Text on Light background
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
image

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
hit ctrl shift l and cycle through all the layouts.
**What is the expected behavior?**
Be able to read commit text
**Environment you encounter the issue:**

- GitExtensions version:2.50.02
- GIT version: NA
- OS version: windows server 2012 R2

**Did this work in previous version of GitExtensions (which)?**
Yes  2.49.03

### LINKED ISSUE #4195: Cyling through Layouts should re-layout everything
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Some of the layouts don't layout correctly until a repo refresh runs.
Example:  
image
After repo refresh: 
image

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Cycling should re layout the whole grid for each layout.
**Environment you encounter the issue:**

- GitExtensions version:2.50.02
- GIT version: NA
- OS version: 
image

**Did this work in previous version of GitExtensions (which)?**
Not sure

### LINKED ISSUE #4892: Branch graph lines can have invisible colors
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Branch colors used in branch graph do not exclude those used as background (or those very close to them).
The result is a graph with some branches almost invisible if branch contour lines are switched off.
(See branch "b12" on attached screenshot)
invisible_branch_b12

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. turn off branch borders in color settings
2. start creating branches
3. after about 8-10 branches at least one appears as a white line on white background

**What is the expected behavior?**
Branch lines should be different enough from background colors they are drawn on to be clearly visible even with contours turned off.
(default and alternate striped backgrounds, authored commits' background, etc.)

**Environment you encounter the issue:**
- GitExtensions version: 2.51.01
- GIT version: 2.15.1.windows.2
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Not checked.

### LINKED ISSUE #4902: Column widths not adjustable
**Do you want to request a *feature* or report a *bug*?**
Reporting a bug

**What is the current behavior?**
In the commits view, I can't change all column widths correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Widen the columns "commit message" and "committer"; the field "commit date" will become smaller. Then try to make those fields smaller again; you'll see that the field "commit date" can't be made wider.

**What is the expected behavior?**
I expect all field widths in the view to be adjustable to both sides.

**Environment you encounter the issue:**
Windows

- GitExtensions version: 2.51.01
- GIT version: git version 2.16.2.windows.1
- OS version: Windows 10 pro 10.0.16299.371

**Did this work in previous version of GitExtensions (which)?**
It did work, not sure till which version exactly.

PS thanks Russkie for your comment

### LINKED ISSUE #5026: Remove support for RevisionGrid layouts
The `RevisionGrid` control supports multiple layouts.

I strongly suspect that most users don't know this, and use the default layout.

I kinda wonder whether _anyone_ uses a non-default layout. Does anyone reading this do so?

### Layouts

Many of the layouts look completely broken. Here's what they look like in 2.51.02, and they look much the same on `master`.

You can cycle layouts by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd>, or via the "View" menu.

image

image

image

image

image

image

image

image

### Proposal

Remove the ability to change the layout. Have one good layout. Reduce the volume of code considerably. No one will notice :)

I've got a branch going with some tidying of `RevisionGrid`. That's such a huge class, with over 300 members (excluding the designer file). If this proposal gains support, I will do the necessary surgery on that branch and create a PR.

---

### Environment

GitExtensions version: 2.51.02, `master`
OS version: Windows 10

### LINKED ISSUE #5032: Displaying only the abbreviated sha1 in the revision grid
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

There is an option to display the sha1 in the revision grid but that display the complete sha1.
Which is not absolutely needed to display 

**What is the expected behavior?**

Display the abbreviated sha1 to use less width in the grid.
But still keep the full sha1 when using the copy feature

### LINKED ISSUE #5036: RevisionGrid: tooltip with multi-line body is not shown if the multi-line indicator column is hidden
**Do you want to request a *feature* or report a *bug*?**

bug/incompleteness in PR #5017 for issue #4990
I'll solve it myself after Drew Noakes will have finished the works on the RevisionGrid.

**What is the current behavior?**

no tooltip with multi-line body in MessageDataGridViewColumn if IsMessageMultilineDataGridViewColumn is hidden, i.e. AppSettings.ShowIndicatorForMultilineMessage == false.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

switch off "Show indicator for multiline message" in the main menu "View"
hover mouse in message column over a commit with a multi-line message

**What is the expected behavior?**

tooltip with complete commit message

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: (2.17.1.2)
- OS version: (Windows 7)

**Did this work in previous version of GitExtensions (which)?**

no, new feature

### LINKED ISSUE #5074: Very sluggish response when changing focus between panels for large repository
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Moving the mouse between commit tree panel and branch tree panel of the UI has very poor response. The mouse pointer moves quickly, but actions when moving into a new panel are sluggish (in my case, delays of 4 seconds or more before clicks seem to register).

Looking at ProcessExplorer, each time I move between those panels (without clicking on anything), it appears to launch "git branch -a--contains", which suggests that GitModule.GetAllBranchesWhichContainGivenCommit() is being fired on entry events.

On my machine, with a recently "git gc"'d repository, "git branch -a --contains" takes about 4.5 seconds.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

We have a large-ish repository (around 2GiB), with many 10's of thousand first-parent commits on master, and multiple release branches, and multiple feature branches.
This problem is not apparent on (for example) the gitextensions repository, where "git branch -a --contains" is quick.

1. Open the repository.
2. Hover over a commit in the commit tree view panel.
3. Move into the branch tree view panel.
4. Click on a branch.
5. Go back to the commit tree view panel.
6. Click on a commit.

I don't think that the "click on ..." is actually required - I can see the "git" command being triggered without it.

The same problem seems to when the branch tree panel is turned off when moving between bottom panel and the commit tree panel, but it's a little bit more temperamental.

**What is the expected behavior?**

Not being slow.

**Environment you encounter the issue:**

- GitExtensions version: master fa860cdfda35d663a90d0a9955a6f95854191ba6
- GIT version: git-for-windows 2.17.1.windows.2
- OS version: Windows 10 (1703)

**Did this work in previous version of GitExtensions (which)?**

It did in 2.50.01 (yes, I know it's an old version - I've been building the master version since that was installed :smile:)

### LINKED ISSUE #5149: Repo object tree icons
**Do you want to request a *feature* or report a *bug*?**

Discussion

**What is the current behavior?**

The repo objects tree has monochrome icons that look very different to the rest of GE's icons.

image

The fugue icon set does not really have a good icon for a git branch. But it has some bits and pieces that can be re-appropriated.

Here is a potential change:

image

What do people think?

### PR DESCRIPTION
**Pull request by drewnoakes**
Fixes #3072. Fixes #3978. Fixes #4195. Fixes #4892. Fixes #4902. Fixes #5026. Fixes #5032. Fixes #5036. Fixes #5074. Fixes #5149.

@RussKie has said he'd like to get an RC together for version 3.0 towards the end of the month.

It's been a long time since 2.0, so 3.0 would understandably come with some expectation of greatness!

The dashboard has seen significant improvement. GE has a new side panel. The application's innards have been tidied and sped up a fair bit.

I wanted the UI to have a more general refresh, in a bunch of subtle ways, so that it felt like 3.0 was really a new version. This PR attempts to modernise the UI in advance of 3.0 RC.

Apologies for the size of the PR. A lot of the changes are refactorings to separate out parts of the revision grid and revision graph, which both saw a lot of visual changes.

In addition to visual changes, I profiled a bunch of the rendering code for both memory and CPU usage, and made improvements. I won't discuss them here, but they should be easy to find in the commit list.

---

# FormBrowse

Before:

image

After:

image

image

## RevisionGrid

image

Each column is now backed by its own `ColumnProvider` subclass. This gives fine grained control over things such as rendering, tooltips, and so forth.

Refs (branches, tags, ...) have a flatter appearance, and more balanced internal padding.

image
image
image

Graph lines no longer have thin black borders, and the line between nodes is slightly darker than the nodes. The colours are a bit desaturated and therefore less like the EGA graphics palette.

image
image
image

A new column shows the author's avatar in the grid directly.

The message column shows the 'multiline message indicator' as a graphic rather than text `[...]`.

image
image
image

Thanks to @gerhardol, artificial commits now visually break down changes changes to the right of the tile (the before image here is from 2.51.02, not current master, which does show "Working directory" and "Commit index" tiles, but on the right of the text, not the left).

image
image
image

All columns now use the same font.

The Object ID (SHA-1) column shows enough characters to fit without trimming. It won't show ellipsis any more. Fixes #5032.

User can show/hide individual columns. Toggling these no longer reloads all revisions, where possible:

image

The ability to cycle between multiple grid layouts has been removed. Fixes #5026.

UI for empty and bare repos is no longer constructed unless needed, improving startup time and reducing flickering.

Dark borders have been removed from panels, and padding/margin tightened so everything fits more cleanly.

Author highlighting no longer sets the row background colour. Instead the author's name is highlighted in bold.

image

image

The header area and layout splitters are a bit darker to improve contrast in the absence of 1px borders.

Icons have been updated in many places, using the fugue icon set.

A performance issue in the tooltip for the graph column was addressed. Fixes #5074.

Body text is now kept for commits authored in the last six months. This allows the full message in the tooltip of recent commits. Fixes #5036.

## CommitInfo

No longer flickers when changing the selected revision.

Tweaked margins/padding. Grey box extends down to base of avatar if needed, reducing number of lines.

Use singular/plural form for parents/children.

image
image

(This needs a bit more padding, but it was hard to figure this in WinForms. Will revisit.)

## Quick Search

The quick search feature saw a few changes. The label is a bit larger and easier to notice.

image
image

The label stays on screen for 4 seconds instead of 0.75.

It goes red if the text you're searching for is not found.

image

If you keep typing and the new search string matches the same revision, it no longer flickers.

---

# FormCommit

image

image

Remove 1px borders. 

Increase splitter widths.

Increase number of recent commit messages from 4 to 6.

---

# FormPush

image
image

image
image

Remove group boxes.

Increase tab control padding.

Checkbox arrangement.

---

# FormCommitDiff

image
image

---

# FormFileHistory

image
image

---

# FormBlame

image
image

---

# FormAbout

image
image

---

# TextEdit Control

The text editor control `ICSharpCode.TextEditor` was sourced via NuGet, from @KindDragon's repo on GitHub.

The control always shows scrollbars, even if there's nothing to scroll.

I forked that repo into the `gitextensions` organisation and modified it to only show scrollbars when needed, and I think this looks a lot better in GitExtensions now.

image

image

(I will open an issue about the fact that we seem to have lost information on the submodule's changes.)

There's also syntax highlighting for many more language types. For example, .sln files:

image
image

---

# Form lifecycle

Subclasses of `GitExtensionsFormBase` no longer call `Translate`. Instead they call `InitializeComplete` which triggers translation and DPI scaling logic across _all_ forms. There were still many forms that were not adjusting for DPI scaling and had small icons. That shouldn't be a problem any more.

# Avatars

Some of the work from #4712 made it into this PR, resulting in a rewrite of the avatar loading and caching code. In-memory image caching turned out to be important with avatars in the grid. Prior to this change, 25% of rendering time was decoding images from the file system. There's now a single `IAvatarProvider` interface with two methods: `GetAvatarAsync` and `ClearCacheAsync`. The cache key now includes the image's size as well.

---

# Display paths

Paths that descend from the user's home dir are now displayed with a unix-style home dir identifier.

image

image

The capitalisation of these paths is also updated by querying the file system. Notice how the first screenshot has `Dev` and `dev` interspersed, based upon what I typed in to open the repo.

This also applies in the dashboard:

image

And form titles:

image

# Plugin Icons

image

# Application icon

The application icon was changed to the more simplistic X form across the entire application (and the project README).

image

image

image

image

# PNG optimisation

GE has lots of PNG files for icons. PNG files saved from most image editing programs can usually be losslessly compressed. Such compression saved about 250kB.

# Moo

The easter egg was recently removed on master. This PR removes left over cow images and the WAV file startup sound.

# FormSubmodules

image
image

# FormCommit load flicker

Another benefit of the `InitializeComplete` life-cycle hook is that we can perform certain operations on forms before they are shown. This allowed removing flickering due to resizing of splitters after the form is first shown. The result feels much snappier and less jarring. Here are some GIFs that sort of show what this means:

commit-load-before
commit-load-after

---

What did I do to test the code and ensure quality:
- Lots of manual testing

Has been tested on:
- GIT 2.17.1.windows.2
- Windows 10
- .NET 4.7.1

### CODE REVIEW

**Comment by RussKie** [comment]
Pure awesomeness! I want author highlighting back though.

(I'm still stuck in transit airport, so just reading emails).

**Comment by RussKie** [comment]
How hard is it to reconcile our changes to the "Colors" dialog?

**Comment by drewnoakes** [comment]
> I want author highlighting back though.

We can reinstate an option for this. Do you want the whole row highlighted in yellow as before? I still don't intuitively understand what this gives, but I'm ok with that.

In general I like the idea of removing options. But then I understand that eventually an option I actually use will be removed. This same feeling will come back on the issue tracker from users, post release. For example I personally change the application icon, and I see we're considering removing that in #5081.

Best outcome is we improve the default to encompass whatever the option provided to those who wanted it. Not always possible to do of course.

> How hard is it to reconcile our changes to the "Colors" dialog?

If we get #5081 merged first I can sort out whatever is left here in a rebase. Or you can copy the changes over to your PR -- they're not so complex. Basically just some checkbox label text changes, and colour picker button formatting and positioning.

Have a good flight. I thought maybe you were there for the world cup but I guess that's not the case.

**Comment by jbialobr** [comment]
>>I want author highlighting back though.

>We can reinstate an option for this. Do you want the whole row highlighted in yellow as before? I still >don't intuitively understand what this gives, but I'm ok with that.

@RussKie Could you give a try for a few days and then say if you want it back. The functionality is preserved by having the author name printed in bold. For me there is no difference in ease of noticing rows for the same author. This is how I came across https://github.com/gitextensions/gitextensions/pull/5088

**Comment by drewnoakes** [comment]
> Consider disabling automatic stretching of column widths, in favour of a horizontal scrollbar if too wide

Tried this out and I think I like it.

image

**Comment by vbjay** [comment]
Just an FYI.  The todo list can be a todo list that you can check and uncheck.  Remove the x at the beginning of each line to make it work

UnChecked: - [ ] 

- [ ] High DPI testing
- [ ] Test if these changes address #4982 (Revision graph is truncated)
- [ ] Consider disabling automatic stretching of column widths, in favour of a horizontal scrollbar if too wide (relates to #4902)
- [ ] Add credit for icons to README and About page, per license requirements
- [ ] Remove option for multiline indicator? This used to be optional as it would slow the app down a fair bit. I don't think we need this to be optional any more.
- [ ] Another few passes at squashing to get the number of commits down (I anticipate force pushing to this branch over time)

Checked - [x] 
- [x] High DPI testing
- [x] Test if these changes address #4982 (Revision graph is truncated)
- [x] Consider disabling automatic stretching of column widths, in favour of a horizontal scrollbar if too wide (relates to #4902)
- [x] Add credit for icons to README and About page, per license requirements
- [x] Remove option for multiline indicator? This used to be optional as it would slow the app down a fair bit. I don't think we need this to be optional any more.
- [x] Another few passes at squashing to get the number of commits down (I anticipate force pushing to this branch over time)

**Comment by drewnoakes** [comment]
@vbjay cheers

**Comment by RussKie** [comment]
Yes, absolutely. I'll give your branch run for the money.

**Comment by mstv** [comment]
Great @drewnoakes, what a speed-up loading repositories! Cute coloring!
Avoiding bold text in the selected line saves column width, I appreciate this. 

I'll test it the next days in my daily work.
But on the first try, there have already arisen some picky wishes/comments:
1. The merge lines seem to have an offset of one pixel to the right.
1. I'd prefer even more convergent/rounder bows, especially at the connection to perpendicular lines.
grafik (zoom factor 2x of screenshot on Windows 7 with scaling factor 100%)
1. The right columns become invisible if there are lots of parallel branches. I'd prefer automatic resizing of the message column although it had the ugly effect on resizing the rightmost column. Maybe it would work better if all other columns stay resizeable but have weight 0, i.e. are not resized automatically.
grafik
grafik
1. It took some time until I mananged to resize the message column: The multi-line indicator seems to belong to this column now.
1. Should I merge in the tooltips for branch lanes? First, I'd display only the commit message and the hash of the current line and omit the branch info which caused too high load by starting git.exe. An optimized retrieval of information about branches could be added later.
1. You mentioned a patch for tooltips following the mouse cursor. You or me?
1. For my eyes, there's too little contrast in the multi-line indicator. It appears blurred although it isn't.
grafik (original)
grafik (zoom factor 2x)
1. I'd prefer one more white pixel at the left of the commit info text (a).
1. The horizontal scrollbar appears although all columns are visible (b). The Hash column seems to be too large.
grafik
1. (I know that the flat style is modern. But I miss the 3D frames around input areas and separator lines between sections which guide the eyes.)

**Comment by drewnoakes** [comment]
@mstv thanks for the detailed feedback.

> The merge lines seem to have an offset of one pixel to the right.

I played around with this a bit and it's hard to make it perfect everywhere. The problem is that each row is drawn in isolation, and that the straight lines are drawing without anti-aliasing, yes the curves are antialiased. That means the first/last pixel row of the curves are wider than the straight edge. When a curve meets a straight edge, aligning them as you say tends to make them spill out the other side. If you want to try this out for yourself, search for `DrawBezier` in `RevisionDataGridView`.

> I'd prefer even more convergent/rounder bows, especially at the connection to perpendicular lines

I'm not entirely sure what you mean. I would like to change a few things about the curves, but there are two problems as I see it:

1. I don't understand the graph layout code yet properly. It's quite complex.
2. Each row is rendered in relative isolation of the others. To smooth things across rows would require additional coordination. See point 1.

> I'd prefer automatic resizing of the message column

I played around with various options here, and there is possibly more that can be done. Are you talking about automatically sizing the message column to fit its contents? Given the line should never be longer than 50 characters, keeping it fixed seems sensible to me. If it is sized to take up all remaining space, then other columns end up far to the right which looks bad on wide screens.

> The multi-line indicator seems to belong to this column now.

Yep, it's rendered into the message column directly. This might just be case of breaking a habit, more than anything. There isn't great discoverability on column resizing, but hopefully they're pretty well sized out of the box.

> tooltips for branch lanes

I'm not sure we really need one here. I'm not sure it's clear in general what someone would reasonably expect to see in such a tooltip.

> tooltips following the mouse cursor. You or me?

Either way. The implementation wasn't too bad and I have it in a stash somewhere. Might be better to get this PR in first.

> there's too little contrast in the multi-line indicator

What do you suggest changing? I don't think it should be very dominant on screen. I'd even vote for making it contrast less with the background, but my experience with tweaking subtle shades of grey is that other people have different monitor setups and what looks good here might look strange elsewhere, so I gave it a bit extra.

> I'd prefer one more white pixel at the left of the commit info text 

Yes, @RussKie pointed this out too. It's a bit tricky to do as the RichTextBox control doesn't have padding. I am half tempted to convert the control to WPF so we can have full control over it, but that's a bit out of scope. If you can find a simple way to move it over, that'd be great. But I don't want to introduce any white border, or break the layout of the rest of the control.

> I miss the 3D frames around input areas and separator lines between sections which guide the eyes

Is it possible that our monitors are showing different contrast between white and grey? For me, the wide splitter gives enough contrast to guide my eyes easily enough. I'm on Win 10 with default themes and using a Dell U3011 monitor.

**Comment by RussKie** [comment]
Let's leave the commit info tab out of this PR, we will tackle it separately. 
We probably give it a make over in a subsequent release.

**Comment by drewnoakes** [comment]
@RussKie the [`_Icon Sources.txt`](https://github.com/gitextensions/gitextensions/blob/master/GitUI/Resources/Icons/originals/_Icon%20Sources.txt) file will be a bit of a pain to update as I've added a tonne of images from the fugue set. How about I just add details of the icon set there?

**Comment by drewnoakes** [comment]
I added another button to the toolbar to control the layout:

image

In that configuration the window might resemble:

image

This is an interesting layout that was hard to find unless you went hunting about in the settings. Playing with it I also uncovered a NRE bug, which is now fixed.

I'll do some DPI testing tomorrow and then some fixups to get the commit count down, then I think I will remove the WIP label. The longer this stays open, the more it'll conflict. So if you've been sitting on the fence wrt testing it out, please do so!

**Comment by drewnoakes** [comment]
Also gave the Git Command Log a quick once over. You can launch it via <kbd>F12</kbd> (consistent with dev tools in many browsers). It shows operations that are launched on the UI thread in a 'column':

image

**Comment by gerhardol** [comment]
I want the count for working-dir and index to include more information, primarily about submodules
The changes text mentions just "files"
To change the text like "1 files and 1 submodules with unstaged changes" is 47 characters which definitely will be more than 50 characters in translated text.

image

I probably want to see #4281 eventually. Just icons and a number of changes should be clear enough.

**Comment by RussKie** [comment]
I propose we open the command log as a new tab, next to the conemu tab

**Comment by mstv** [comment]
This 50 characters limit is not whole truth for at least two reasons:
1. Labels for branches and tags are prepended to the message column.
1. There are several projects that do not follow the Git conventions strictly and allow longer message headings.

**Comment by RussKie** [comment]
> How about I just add details of the icon set there?

No worries at all, as long as we have a record of where images come from.

**Comment by gerhardol** [comment]
> This 50 characters limit is not whole truth

Sure, but the design should work OK with 50 chars for those that follow
A submodule with refs to the superproject can easily exceed 150 chars, is handled OK

image

**Comment by mstv** [comment]
> > The merge lines seem to have an offset of one pixel to the right.
> 
> I played around with this a bit and it's hard to make it perfect everywhere. The problem is that each row is drawn in isolation, and that the straight lines are drawing without anti-aliasing, yes the curves are antialiased. That means the first/last pixel row of the curves are wider than the straight edge. When a curve meets a straight edge, aligning them as you say tends to make them spill out the other side. If you want to try this out for yourself, search for DrawBezier in RevisionDataGridView.

It looks much better to me if the straight lines are drawn with anti-aliasing, too.

> Regarding: Bezier lines and flat style

It looks quite good. I only put in my two cents if someone is going to fine-tune it. Maybe I'll make some  experiments when higher-priority items on my list are done.

> > I'd prefer automatic resizing of the message column
>
> I played around with various options here, and there is possibly more that can be done. Are you talking about automatically sizing the message column to fit its contents?

No, that wasn't my intention.

> Given the line should never be longer than 50 characters, keeping it fixed seems sensible to me.

See my previous comment.

> If it is sized to take up all remaining space, then other columns end up far to the right which looks bad on wide screens.

I would really appreciate an option to switch on this behavior.

> > tooltips for branch lanes
>
> I'm not sure we really need one here. I'm not sure it's clear in general what someone would reasonably expect to see in such a tooltip.

I mean topic 1. of #4990. I think it's wrong and misleading to display the commit hash if the mouse is over a foreign branch line.
I'll reopen this issue and prepare a PR based on your branch. I will omit the display of "contained in branches" because it can cause too much load.

> >    there's too little contrast in the multi-line indicator
>
> What do you suggest changing? I don't think it should be very dominant on screen. I'd even vote for making it contrast less with the background, but my experience with tweaking subtle shades of grey is that other people have different monitor setups and what looks good here might look strange elsewhere, so I gave it a bit extra.

Understood and agreed. I'd expect that the dots are really as black as the texts around.

**Comment by gerhardol** [comment]
I will submit a PR for #4281, either to your branch or after merge

image

**Comment by RussKie** [comment]
Nice!
I presume there is a minus for deleted files?

**Comment by RussKie** [comment]
Few issues I found so far:
* incorrect 'add' icon
image
* branch labels overflow - I don't have a good proposal for handling these, perhaps labels need to be shortened with ellipses (e.g. 'branc....', 'branc...', 'branc...') so all of them fit in 
image
* branch labels [...] - I can't work out why some branches have "[...]" and some don't
image

**Comment by gerhardol** [comment]
Regarding #4281 - will suggest changes to changes in this PR as a separate WIP PR

> I presume there is a minus for deleted files?

Yes
(I would like to see dirty vs not updated submodules, that requires some async handling that will likely not be done now)

**Comment by gerhardol** [comment]
> tag labels [...] - I can't work out why some tags have "[...]" and some don't

https://github.com/gitextensions/gitextensions/pull/5087/files#diff-5506899781c3e3ed4580c64a55a09dcfR125

**Comment by drewnoakes** [comment]
@gerhardol that looks great! I've just force pushed a rebase that fixes conflicts.

@RussKie I ditched the changes to the colour settings page from this PR as they were too hard to merge.

Haven't had much time in the last day or two but hope to get to @jbialobr's StringPool PRs later today, as well as finishing the high DPI testing here.

> incorrect 'add' icon

Thanks, I'll fix that shortly.

> branch labels overflow 

I am not sure what's best here. Possibly we just make a max length with ellipsis for ref labels and make sure their details are in the tooltip text. I think that'll look better in general than trying to fit everything as the column gets narrow. The screenshot you post has some loooong branch names.

> I can't work out why some tags have "[...]" and some don't

This is because they have annotations. This behaviour was present if you turned on the multi-line commit indicator. We could give it a nicer presentation here. I've added it to the checklist.

**Comment by RussKie** [comment]
I'm running this branch on a scaled Windows under Parallels and haven't
observed anything unusual.

**Comment by RussKie** [comment]
> This is because they have annotations.

Thank you.
A newb question, how do I see these annoyations?

**Comment by gerhardol** [comment]
Current branch is grey - same in 2.51 though
image

**Comment by drewnoakes** [comment]
@RussKie I don't know if there's a way to see the annotations in GE. You can do it from the command line with `git tag -n99'.

If we don't have a way of seeing this, it might be good to add one. We need an issue to track this.

> Current branch is grey - same in 2.51 though

If that behaviour is in 2.51 as well then can we make a new issue for it? I haven't seen that yet, so maybe also capture something about that repo. Is it something public, and do you have a SHA?

**Comment by gerhardol** [comment]
> If that behaviour is in 2.51 as well then can we make a new issue for it? I haven't seen that yet, so maybe also capture something about that repo. Is it something public, and do you have a SHA?

Agree this is separate
I see the issue if checking out a branch that is branching to the leftmost lane
The following reproduces
gerhardol/feature/i5066-git-status-no-optional-locks

**Comment by drewnoakes** [comment]
I've checked off all the TODO items and believe this is ready now.

**Comment by gerhardol** [comment]
How to review?
It is more or less impossible...
The code looks good to me in the minor samples I looked at.

Should we just merge this (similar to the revision grid PR, another great one) when enough people have been running this (I have been running this for a couple of days).

**Comment by drewnoakes** [comment]
> How to review?

Not much to add here other than to say I will take ownership of any bugs that are regressions. I'll also help to back out any changes that a majority feels should be undone.

**Comment by RussKie** [comment]
Both of you make my life difficult... sigh

**Comment by gerhardol** [comment]
> Both of you make my life difficult... sigh

I choose to interpret this positively, being compared with drew.

File: GitCommands/AppTitleGenerator.cs [hunk 1]
```diff
@@ -36,19 +34,22 @@ public AppTitleGenerator(IRepositoryDescriptionProvider repositoryDescriptionPro
...
 
-            string repositoryDescription = _repositoryDescriptionProvider.Get(workingDir);
-            var title = string.Format(RepositoryTitleFormat, repositoryDescription, (branchName ?? "no branch").Trim('(', ')'));
+            branchName = branchName?.Trim('(', ')') ?? "no branch";
+
+            var description = _description.Get(workingDir);
+
 #if DEBUG
-            title += " -> DEBUG <-";
+            return $"{description} ({branchName}) - Git Extensions [DEBUG]";
```
Comment (gerhardol) [inline GitCommands/AppTitleGenerator.cs]: Great change!
Do we want to see the branch name in release builds though?
(RussKie wanted the version some months ago, I rather keep this clean in releases).

**Comment by pmiossec** [comment]
There are a lot of great stuff in this PR that I hope to see in GitExtensions without even finding the time to do it, so 🎉 🎆 

After a short test, just 2 regressions:

* The "Show build status text" add the column but display nothing
* The about page look like that for me (no highdpi):

image

Just to gather point of view of others, what do you think of the use of these icons to increase/decrease displayed lines of code in diffs? I like the visual but in the same time I find it disturbing because in the "git diff meaning" it is linked to "added/deleted lines". So I find it surprising to be find it specially here in a diff for another use...

image

>I vote for merging and take followup from usage.

i mostly agree

**Comment by pmiossec** [comment]
>After a short test, just 2 regressions:
> *    The "Show build status text" add the column but display nothing

In fact, it works but require a restart (a refresh or close/open repository is not enough) which is disturbing because the empty column is displayed :(

**Comment by drewnoakes** [comment]
@pmiossec thank you for the review. I will be offline for the next 36 hours but will get to your points ASAP.

File: GitCommands/AppTitleGenerator.cs (hunk 1 above)
Comment (drewnoakes) [reply GitCommands/AppTitleGenerator.cs]: Would be nice to have the git commit in the about box.

Comment (vbjay) [reply GitCommands/AppTitleGenerator.cs]: You mean like I suggested in #2533?

**Comment by gerhardol** [comment]
> The "Show build status text" add the column but display nothing

Works for me, but width has been zero occasionally

**Comment by RussKie** [comment]
Would it help, if headers were visible?

**Comment by gerhardol** [comment]
> Would it help, if headers were visible?

Yes, if you can see the column.
However, I cannot recreate now. I saw the problem with an earlier version and it is not unlikely that it just looked like zero width to me, that it was the restart required problem.

File: GitCommands/AppTitleGenerator.cs (hunk 1 above)
Comment (drewnoakes) [reply GitCommands/AppTitleGenerator.cs]: This looks like an easy way to add commit ID to the assembly metadata:

https://github.com/MarkPflug/MSBuildGitHash

**Comment by drewnoakes** [comment]
> The "Show build status text" add the column but display nothing

Fixed. Thanks for pointing this out. The workaround was to manually resize the column, however this is now done automatically when that setting is enabled.

> The about page look like that for me (no highdpi):

I'll reboot in a few minutes to get into 96dpi and look into fixing this.

> what do you think of the use of these icons to increase/decrease displayed lines of code in diffs? 

Perhaps `magnifier-zoom-in` / `magnifier-zoom-out` instead?

http://p.yusukekamiyamane.com/icons/preview/fugue.png

**Comment by gerhardol** [comment]
Any more thoughts on merging this?
@drewnoakes Any more additions planned?

Has anyone tried to review this PR?
(I have done that briefly.)

Who has tested this branch?
I use this as my daily driver, with my changes on top of this PR.

**Comment by pmiossec** [comment]
>Perhaps magnifier-zoom-in / magnifier-zoom-out instead?

Yes, I prefer. Any one with a point of view on the subject?

@gerhardol I have made a really quick test but I can't do more extensive use before next week where I will try to use it at work...

But what I saw suits me quite well.

I just remembered that I have a question...
Is it possible to change the color of the 2 drop-downs in the toolbar because when I look at them, I think they are disabled?

**Comment by mstv** [comment]
> Perhaps magnifier-zoom-in / magnifier-zoom-out instead?

Yes, it seems to be more descriptive to me - with the interpretation "zoom-in shows more details", i.e. more surrounding lines.
Though some users could expect to get larger text. But I don't expect too much confusion from this.

**Comment by RussKie** [comment]
I'm yet to review, but it is gigantic and Drew is still pushing in.
I'm running the branch locally

**Comment by RussKie** [comment]
Got the latest, hit an ANE
image

**Comment by RussKie** [comment]
...then I got another
image

**Comment by jbialobr** [comment]
There is a grey line in the subgraph of the current branch.
Before
gitext

After
gitext

**Comment by drewnoakes** [comment]
I'll look at the ANE and render glitch later today hopefully.

**Comment by drewnoakes** [comment]
@jbialobr I can only reproduce the rendering issue via "Highlight selected branch". Are you seeing it in other scenarios too?

**Comment by jbialobr** [comment]
>Are you seeing it in other scenarios too?

Yes, I am. I can not share the repo, but I can debug it in the next week.

**Comment by drewnoakes** [comment]
@RussKie the exception you were seeing should be fixed.

**Comment by drewnoakes** [comment]
>> Are you seeing it in other scenarios too?
>
> Yes, I am. I can not share the repo, but I can debug it in the next week.

If you select d963f90d3b88 from the GE repo and activate "Highlight selected branch" you get this:

image

image


Is that the same issue?

**Comment by drewnoakes** [comment]
`magnifier-zoom-in` / `magnifier-zoom-out` looks like this:

image

My only concern after using it is that the icon suggests "zoom in", so while the `+` indicates an increase of context lines, it feels more like you're zooming out.

**Comment by jbialobr** [comment]
I observe this also in the GE project. Fetch my fork and checkout 646d6c9166a5bc28416aeb3a85cfce3bee8e4a89. No need of highlighting other branch.
gitext

**Comment by gerhardol** [comment]
@pmiossec 
> I just remembered that I have a question...
Is it possible to change the color of the 2 drop-downs in the toolbar because when I look at them, I think they are disabled?

Drew changed this to get consistency of the appbar, but I rather change this too.

The major change I would like to see is changing the "WinForms" gray to something else (maybe a tint of blue or something). A lot of places to override the default, will not happen now, probably better to wait...

**Comment by drewnoakes** [comment]
> Is it possible to change the color of the 2 drop-downs in the toolbar because when I look at them, I think they are disabled?

How does this look:

image

Unfortunately the two controls look quite different, but I think we are stuck with this so long as we use `ToolStrip`. The toolbar is another candidate for conversion to WPF in future.

**Comment by gerhardol** [comment]
> How does this look:

OK

**Comment by mstv** [comment]
Three minor issues:

* Some dialog windows trigger an update of the RevisionGrid on close, e.g. commit and rebase.
Then the GraphColumn shows only one lane:
grafik
After scrolling one row it looks as expected:
grafik

* Some text in the `About` dialog is clipped:
grafik

* The surname of the contributors seems to be omitted.

**Comment by drewnoakes** [comment]
The about form has been fixed. There was a max height on the clipped labels.

Thanks for spotting the contributor name glitch too. It was splitting on spaces, so first and second names were appearing separately.

image

> Some dialog windows trigger an update of the RevisionGrid on close, e.g. commit and rebase.
> Then the GraphColumn shows only one lane

I haven't yet been able to reproduce this. I will investigate further.

---

What do we need to get this merged in?

**Comment by RussKie** [comment]
I've noticed that too. The spinner is not visible

On Jul 2, 2018 6:25 PM, "Gerhard Olsson" <notifications@github.com> wrote:

In some situations the switch to a new subrepo (and maybe refresh) is much
slower than in master and 2.51.
For a specific repo it is OK to go subrepo->super, but super->sub takes
1-2s in 2.51 and 20s in this branch. The grid area is just gray when this
occurs.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/pull/5087#issuecomment-401709687>,
or mute the thread

**Comment by gerhardol** [comment]
git-log is occasionally listed as "running" in the GE log. It is more likely that the command never updates the end time than that it never completes.

Refresh in GE 

image

**Comment by drewnoakes** [comment]
> the switch to a new subrepo (and maybe refresh) is much slower than in master and 2.51

Can you please double check that this is not actually a difference between release and debug builds? I know that might sound implausible, but I have observed that debug builds can exhibit this kind of pause on the UI thread. In fact, Windows can show the UI as unresponsive. The usual way to trigger this is to do something that causes the revision grid to scroll down a long way, such as clicking a very old ref in the repo object tree or by pressing the <kbd>End</kbd> key.

Whenever I see this slowdown and break into the debugger, the code is waiting to acquire a lock in `RevisionDataGridView.GetRevision`, which is called a _lot_. I've looked into removing the locks (or replacing with r/w locks), but that is non-trivial in this case and something to be done delicately with plenty of testing. I haven't been so concerned as I do not see these slow downs when I run a release build (which I do less often). My assumption is that locking works differently between configurations, though I can't back that up.

Either way it would be good to eradicate such problems even in debug builds. I will take a look. If you have a way of reliably reproducing it, please let me know.

**Comment by pmiossec** [comment]
Could the 2 filter controls be larger? Because they are quite small and we can't no longer see the text entered...
image

**Comment by gerhardol** [comment]
>> the switch to a new subrepo (and maybe refresh) is much slower than in master and 2.51

> Either way it would be good to eradicate such problems even in debug builds. I will take a look. If you have a way of reliably reproducing it, please let me know.

Many branches and tags

**Comment by drewnoakes** [comment]
> Could the 2 filter controls be larger? 

Are you on high DPI? These might need scaling.

**Comment by drewnoakes** [comment]
> git-log is occasionally listed as "running" in the GE log

This has the same root as the issue that caused me to context switch over to some UI stuff in this PR from the git process executable stuff.

Specifically, if you dispose a `Process` object (such at that returned by `RunGitCmdDetached`), then you might not get to handle the `Process.Exited` event. This will be best fixed on the other branch, where the 'process' object you receive from the API is actually our own class and we can make sure that clean up happens deterministically.

**Comment by pmiossec** [comment]
>Could the 2 filter controls be larger?

>>Are you on high DPI? These might need scaling.

Yes and indeed that fixes the issue...
Added to FormBrowse, line 317
```
            toolStripRevisionFilterTextBox.Size = DpiUtil.Scale(toolStripRevisionFilterTextBox.Size);
            toolStripBranchFilterComboBox.Size = DpiUtil.Scale(toolStripBranchFilterComboBox.Size);
```

**Comment by drewnoakes** [comment]
> Yes and indeed that fixes the issue

Thank you. Fixed.

**Comment by vbjay** [comment]
Your dpi issue made me think of a better fix for dpi scaling. Instead of
opting in to scaling, how about we loop and scale all controls and oot to
yt if scaling on any that don't require it. That way any new control gets
scaled and if scaling shouldn't apply, add it to an exclude list

Pseudo

For Each ctl in... .Except(excludeScalling)
Scale(ctl)
Next

**Comment by drewnoakes** [comment]
@vbjay we have a similar behaviour in `ControlDpiExtensions`.

For tool strips it doesn't currently apply as it just walks the control tree. It could be extended to other types as well.

I would like to try making the calling of this method mandatory, and having it on `GitExtensionsFormBase`. Currently our forms require the constructor to call `Translate` as well as any DPI helpers. Instead I'd like to have a single `NotifyConstructionComplete` or whatever method that does all of this in one hit. If we don't see that method call before `Load` fires, we throw with an exception explaining you need to add the call. This will make things more consistent and less error prone. It might have problems I haven't discovered yet.

**Comment by RussKie** [comment]
Some controls scale well, some don't (e.g. NumericUpDown) - see #5098.
It also looks like `AutoScaleMode` must be explicitly set to DPI, otherwise
controls aren't scaled well either.

**Comment by mstv** [comment]
Thank you for merging the "Graph tooltips"!

>> Some dialog windows trigger an update of the RevisionGrid on close, e.g. commit and rebase.
Then the GraphColumn shows only one lane

> I haven't yet been able to reproduce this. I will investigate further.

I can reproduce this issue:
1. open the `Commit` dialog
1. maximize the `Commit` dialog window (important!)
1. check `Amend Commit`
1. click `Commit` (without changing anything)
1. confirm to rewrite the history
1. repeat at most once from 1.

**Comment by gerhardol** [comment]
> the switch to a new subrepo (and maybe refresh) is much slower than in master and 2.51

This occurs in any subrepo and is a regression to master

GE displays the superrepo branch heads in the subrepo.
In master, this query is done in the background. In this branch it is done before displaying, so you see the gray area. (I thought there was a configuration for this behavior.) (No investigation why this occurs.

**Comment by jbialobr** [comment]
Refs labels are not clipped when overflowing:

gitext

**Comment by drewnoakes** [comment]
> This occurs in any subrepo and is a regression to master

Thank you for the repro steps. I'm looking at performance now and will address this soon.

> Maybe when you stop adding to it so other developers do not have to rebase constantly?

I've been rebasing due to conflicts. There was another this morning. I could merge from upstream, but I want to remain in a position to interactively rebase this branch as needed and have the feeling (I don't know for sure) that merge commits will make that tricky.

> I would like to submit #5104 to your branch so I do not have to rebase every day.

Would you like me to apply those commits onto this branch? Feel free to make a PR if you prefer, and I'll merge it immediately. #5104 looks great btw. 

@mstv has had two nice PRs merged against the `v3-ux` branch on my fork.

> most issues should probably come after merge to master

I'm sure some minor things would go unseen in this PR. I will take ownership of any regressions or problems my work introduces to make sure things move forwards.

> The PR is impossible to review. I have tried but anything can hide in all refactoring and inling.

Thank you for your effort in reviewing. I should point out that most of the refactoring is done automatically by ReSharper and committed as single commits. I can't remember the last time R# broke code due to refactoring, at least in an RTM build like the one I'm using, and certainly not via the workhorse refactorings such as rename/inline/extract.

We've seen thoroughly reviewable and reviewed PRs sneak bugs through. I'm not making excuses for the size of this PR, just pointing out the baseline for our review process is not some gold standard for the industry. It is not enough to have a good review process (though it definitely helps) -- we must also have a responsive and active community, which we do. Also, I will take on any pain caused by this PR down the line.

> Refs labels are not clipped when overflowing

Thanks, that should be an easy fix via setting a clip for the cell bounds.

---

The slow down and UI freeze we see on this branch is caused by lock contention. The [Visual Studio Concurrency Visualiser](https://docs.microsoft.com/en-us/visualstudio/profiling/concurrency-visualizer) was helpful here, and I recommend checking it out.

Currently, during a refresh, revisions are read in from `git log ...` on a background thread. They then go through some processing on this background thread before signalling across to the UI thread. So both the background thread and the UI thread share some data structures, and to prevent data races they use `lock` statements. These locks can be held for a long time on the background thread, which causes the long pause on the UI. Looking at performance counters, we see a large number of contentions occurring, and things run very slowly (especially in debug builds).

The first thing I tried was to move all processing to the UI thread and remove the locks altogether. This works, however it makes the load of `FormBrowse` quite a bit slower. So we definitely want to keep background thread processing.

It occurs to me that the background thread processes commits in "row order" from top to bottom, as you view them in the grid. Therefore I think we can rework this code so that the only shared state between the two parties is:

- an integer indicating the number of revisions loaded so far (i.e. the maximum row index available for rendering)
- a lock free "list" of data, appended to by the background thread and consumed by the UI thread

Attempts to render beyond the last loaded row currently block, but with this change we could render a blank row that repaints once the row is loaded. I think it should be possible to completely decouple the loading from rendering, with no locks at all.

I spent a few hours yesterday mapping out this portion of the code to better understand it. It's quite involved (and fun to come to grips with) and I'm starting to sense that a simpler lock-free formulation may be possible. It should be considerably faster. We may even be able to use more than one background thread in the process to better utilise multi-core machines.

image

---

I'm not happy with the situation this PR has us in. The promise of the changes is worthwhile, but it's in violation of our usual project workflow.

I've looked at trying to split it up into smaller PRs but have failed to do so. The work was done in an exploratory manner, attempting to improve the UX at various turns to see where we would end up. This means the changes walk around the codebase over time. Rearranging commits into functional areas causes conflicts. I've done some rearranges, as you can see from the author vs. commit dates, but not enough to split the PR down logical lines. We could split it chronologically, but then review questions would likely be answered by "that is fixed later, so please wait for the next PR" which doesn't feel great either.

That said, I'm not sure our current project workflow would have allowed such a UX overhaul to have occurred in a reasonable time-frame. The workflow is well suited to a steady stream of small changes, each of which sits for a few days before being merged. Changes on the scale of this PR would have taken months, yet we wanted to get a 3.0 RC out sooner than that.

It's not for me to decide how to progress from here, but I would like to hear suggestions.

**Comment by vbjay** [comment]
Why not use RX for UI of the grid?  Have an observable<git log entry>.

**Comment by gerhardol** [comment]
I still vote for merging this PR asap and take issues as they are found.
(But @RussKie's has a majority of the votes, unless @KindDragon or @jbialobr raise their hands.)

**Comment by drewnoakes** [comment]
> Why not use RX for UI of the grid? 

#4988 introduced Rx for the first step: passing revisions from `RevisionReader` into the grid/graph.

That worked quite well, and I hope Rx comes into play for subsequent steps. Let's see. It does seem like a good fit.

For now I am working to move all the graph related code into the graph column. Currently it's spread across quite a few classes, increasing their size and coupling.

**Comment by pmiossec** [comment]
@drewnoakes 
https://github.com/gitextensions/gitextensions/pull/5087/files#diff-004acd13700c4712583aa4786118efc1L78
should be replaced by `var parentId = ObjectId.Parse((string)linkLabel.Tag);` to avoid a cast exception (string in ObjectId)

**Comment by vbjay** [comment]
Nice.  One thought is with this we could call git log smartly.  Get the top visible commit and call git log to get visible grid row count commits down*{small window cache for scrolls}.  So user scrolls and the log is called and only retrieves the commits to be shown and a cache for nearby that are out of view.

**Comment by drewnoakes** [comment]
> https://github.com/gitextensions/gitextensions/pull/5087/files#diff-004acd13700c4712583aa4786118efc1L78 should be replaced by `var parentId = ObjectId.Parse((string)linkLabel.Tag);` to avoid a cast exception (string in ObjectId)

@pmiossec well spotted. The bug exists in current master though so is a candidate for another PR. Can you open another issue/PR for it please, and explain how to trigger the exception?

It should be sufficient to pass the string through without parsing as ObjectId, for now. Longer term I'd like parent IDs to be of type `ObjectId` as well. We may be able to share the instance of `ObjectId` between child and parent when parsing, reducing heap usage a little.

**Comment by gerhardol** [comment]
@drewnoakes 
First I do not think that this type of change is really possible with a reasonable amount of effort without cutting some corners, I agree with your comments in https://github.com/gitextensions/gitextensions/pull/5087#issuecomment-402422217. There are so many commits in this branch that the comments are hidden by default.

However, if you continue to push changes to this PR, it will slow down the merging for this master-to-be branch. I am getting a little slowed down. I want to test these changes so I make my small changes against this branch. Can you agree something with @RussKie and start a new exploratory branch?

**Comment by drewnoakes** [comment]
Anyone interested in this PR might like to re-read the description. I've updated the screenshots and added information about changes that have been made since the PR was first created.

**Comment by gerhardol** [comment]
> I want author highlighting back though.

And I am fine with the change.
Row highlight is slightly more functional when you want to see other commits, but "bold committers" (pun intended), is OK. 
When selecting rows for other reasons (more common), then bold committers are less in the way and looks nicer.

**Comment by drewnoakes** [comment]
I've been thinking a bit more about highlighting too. It's not only the author we may wish to highlight.

`gitk` has a useful feature for highlighting commits that touch a given file. Here's an example:

image

Here you see the result of clicking "Highlight this only" in the context menu for the file `GitModule.cs`. All commits that modify that file file are highlighted. This is very useful when reviewing as a folded-in view of the file history form, without switching UI context.

Regarding author highlighting, I propose making two changes:

- Make the message column text bold when a commit is highlighted, as this is the column you're generally looking at, and
- Only activate author highlighting when you click on an author cell.

I think we can bring in the general concept of revision highlighting. Perhaps `bool IsHighlighted { get; set; }` on `GitRevision`. This would be the boundary between selection logic and presentation logic. Currently the rendering code knows about author highlighting specifically.

We can then look at highlighting revisions based on modifications to a given file or folder, as seen in the screenshot above.

There may be other kinds of highlights we wish to include.

**Comment by vbjay** [comment]
image
That's what the history window is for.

**Comment by drewnoakes** [comment]
> That's what the history window is for.

Like I said: _This is very useful when reviewing as a folded-in view of the file history form, without switching UI context._ I don't want to switch context.

File: GitUI/UserControls/RevisionGrid/RevisionGridRefRenderer.cs [hunk 2]
```diff
@@ -32,7 +33,7 @@ public static void DrawRef(bool isRowSelected, Font font, ref int offset, string
             var rect = new Rectangle(
                 bounds.X + offset,
                 bounds.Y + outerMarginTopBottom,
-                textSize.Width + arrowWidth + paddingLeftRight + paddingLeftRight - 1,
+                Math.Min(bounds.Width - offset, textSize.Width + arrowWidth + paddingLeftRight + paddingLeftRight - 1),
```
Comment (gerhardol) [inline GitUI/UserControls/RevisionGrid/RevisionGridRefRenderer.cs]: TODO? Added to list/issues for v3-ux?
It should be more clear that branches/tags are clipped.
Also, the sort order in #5077 by @jbialobr is no longer followed (tags are displayed first, tracked remote are displayed after all local branches)

Order in tooltip is not as in the grid
The tooltip has no color, and should explain local/remote branches, tags etc.

image

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 3]
```diff
@@ -141,16 +141,16 @@ public FormBrowse([CanBeNull] GitUICommands commands, string filter, ObjectId se
...
-                    Images.FileTree,
-                    Images.Diff,
-                    Images.Key
+                    { nameof(Images.CommitSummary), Images.CommitSummary },
+                    { nameof(Images.FileTree), Images.FileTree },
+                    { nameof(Images.Diff), Images.Diff },
+                    { nameof(Images.Key), Images.Key }
                 }
             };
-            CommitInfoTabControl.TabPages[0].ImageIndex = 0;
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/FormBrowse.cs]: This (or previous comit) changes the default taborder, It is Commit-FileTree-Diff when no Commit left panel
OK change for me though

File: GitCommands/Git/GitRef.cs [hunk 4]
```diff
@@ -1,16 +1,28 @@
...
+    internal enum GitRefType
+    {
+        Other,
+        Head,
+        Remote,
+        Tag,
+        Bisect,
+        BisectGood,
+        BisectBad,
+        Stash
```
Comment (gerhardol) [inline GitCommands/Git/GitRef.cs]: Not sure if it is this commit, but viewing stash gives the following exception:

image

 	[External Code]	
>	GitExtUtils.dll!GitUI.ThreadHelper.CompletedResult<GitCommands.GitSubmoduleStatus>(System.Threading.Tasks.Task<GitCommands.GitSubmoduleStatus> task) Line 128	C#
 	GitUI.dll!GitUI.FileStatusList.AppendItemSubmoduleStatus(string text, GitCommands.GitItemStatus item) Line 379	C#
 	GitUI.dll!GitUI.FileStatusList.FileStatusListView_DrawItem(object sender, System.Windows.Forms.DrawListViewItemEventArgs e) Line 332	C#
 	[External Code]	
 	GitUI.dll!GitUI.UserControls.ExListView.WndProc(ref System.Windows.Forms.Message m) Line 236	C#
 	[External Code]	
 	GitUI.dll!GitUI.UserControls.ExListView.WndProc(ref System.Windows.Forms.Message m) Line 226	C#
 	[External Code]	
 	GitUI.dll!GitUI.FileStatusList.FileStatusListView_SizeChanged(object sender, System.EventArgs e) Line 1069	C#
 	[External Code]	
 	GitUI.dll!GitUI.UserControls.ExListView.WndProc(ref System.Windows.Forms.Message m) Line 270	C#
 	[External Code]	
 	GitUI.dll!GitUI.UserControls.ExListView.WndProc(ref System.Windows.Forms.Message m) Line 270	C#
 	[External Code]	
 	GitUI.dll!GitUI.FileStatusList.HandleVisibility_NoFilesLabel_FilterComboBox(bool filesPresent) Line 1236	C#
 	GitUI.dll!GitUI.FileStatusList.UpdateFileStatusListView(bool updateCausedByFilter) Line 814	C#
 	GitUI.dll!GitUI.FileStatusList.GitItemStatusesWithParents.set(System.Collections.Generic.IReadOnlyList<(GitCommands.GitRevision revision, System.Collections.Generic.IReadOnlyList<GitCommands.GitItemStatus> statuses)> value) Line 806	C#
 	GitUI.dll!GitUI.FileStatusList.SetDiffs(System.Collections.Generic.IReadOnlyList<GitCommands.GitRevision> revisions) Line 1228	C#
 	GitUI.dll!GitUI.CommandsDialogs.RevisionDiffControl.DisplayDiffTab() Line 142	C#
 	GitUI.dll!GitUI.CommandsDialogs.FormBrowse.FillDiff() Line 1056	C#
 	GitUI.dll!GitUI.CommandsDialogs.FormBrowse..ctor.AnonymousMethod__52_1(object sender, System.EventArgs e) Line 256	C#
 	GitUI.dll!GitUI.RevisionGridControl..ctor.AnonymousMethod__100_0(object _, System.EventArgs e) Line 134	C#
 	[External Code]	
 	GitUI.dll!GitUI.GitUICommands.StartBrowseDialog(System.Windows.Forms.IWin32Window owner, string filter, GitUIPluginInterfaces.ObjectId selectedCommit, bool startWithDashboard) Line 1073	C#
 	GitUI.dll!GitUI.GitUICommands.RunBrowseCommand(System.Collections.Generic.IReadOnlyList<string> args) Line 1555	C#
 	GitUI.dll!GitUI.GitUICommands.RunCommandBasedOnArgument(System.Collections.Generic.IReadOnlyList<string> args, System.Collections.Generic.IReadOnlyDictionary<string, string> arguments) Line 1387	C#
 	GitUI.dll!GitUI.GitUICommands.RunCommand(System.Collections.Generic.IReadOnlyList<string> args) Line 1356	C#
 	GitExtensions.exe!GitExtensions.Program.RunApplication() Line 130	C#
 	GitExtensions.exe!GitExtensions.Program.Main() Line 56	C#

File: GitUI/UserControls/RevisionGrid/RevisionGridRefRenderer.cs (hunk 2 above)
Comment (drewnoakes) [reply GitUI/UserControls/RevisionGrid/RevisionGridRefRenderer.cs]: @gerhardol thank you very much for the review.

- I've reinstated the ordering from #5077 
- The tool tip now has the same ordering as the ref badges in the cell
- Ref badges no longer render under the multiline message indicator

image

Other items:

- I'm not sure how to better show when ref badges are clipped. Do you or anyone else have a suggestion?
- Colour tool tips would be great, but a bit of a nightmare in WinForms. Another point for WPF.

(Will push these fixes today)

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 3 above)
Comment (drewnoakes) [reply GitUI/CommandsDialogs/FormBrowse.cs]: Adding a button to easily toggle the position of the "commit info" pane uncovered a but where the "file tree" and "diff" tabs could become transposed. Previously you had to go to settings to change this, so I doubt many/any saw this bug, and it would be fixed on restart.

That tab ordering actually felt more logical that way to me. The diff feels more closely linked to the commit that the tree, at least to me. Perhaps it was this way in the past because the diff tab item changed its length, and would reposition tabs to its right?

image

It's easy enough to change back if people dislike the change.

Comment (gerhardol) [reply GitUI/CommandsDialogs/FormBrowse.cs]: I suggest to keep it (I prefer it), just noting the change

File: GitCommands/Git/GitRef.cs (hunk 4 above)
Comment (gerhardol) [reply GitCommands/Git/GitRef.cs]: This is when selecting a stash by the way...

File: GitUI/UserControls/RevisionGrid/RevisionGridRefRenderer.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid/RevisionGridRefRenderer.cs]: > I'm not sure how to better show when ref badges are clipped. Do you or anyone else have a suggestion?

A separate overflow badge would be slightly more clear. But this is good enough right now

Thanks for all work with this PR. I am still voting to merge this now and take comments over time (and let you start a new test branch...).

**Comment by RussKie** [comment]
The sooner this gets in - the better.
My browser takes ages to load the PR...

File: GitUI/CommandsDialogs/FormBrowse.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormBrowse.cs]: LGTM

File: GitCommands/Git/GitRef.cs (hunk 4 above)
Comment (drewnoakes) [reply GitCommands/Git/GitRef.cs]: I cannot reproduce this. Looks like you're clicking on a stash in the revision grid to trigger this. Can you describe the stash for me? I've tried a few things here and failed. Were you in a subproject or a superproject?

I'd need the inner stack trace as well. The one you've posted gets the `AggregateException` raised by the `task.Result` call. The real NRE happened asynchronously within the task responsible for populating submodule statuses. That happens in both `GitModule.GetCurrentSubmoduleStatus` and `GitModule.GetSubmoduleStatus`.

R# points out there might be a NRE in the latter, which I'll push a patch for. It might be the fix, but I can't verify until able to reproduce.

Comment (gerhardol) [reply GitCommands/Git/GitRef.cs]: I get this for private changes in my RunnerUp repo when I first select Working dir and diff tab with one changed submodule and a few changes, then select stash on a another branch. I have not been able to reproduce in Gitextensions repo, will try some more.
 
  | Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   vid GitCommands.GitSubmoduleStatus.CheckSubmoduleStatus(GitModule submodule) i F:\\dev\\gc\\gitextensions_4\\GitCommands\\Git\\GitSubmoduleStatus.cs:rad 41\r\n   vid GitCommands.GitModule.<>c__DisplayClass192_1.<<GetSubmoduleStatus>b__1>d.MoveNext() i F:\\dev\\gc\\gitextensions_4\\GitCommands\\Git\\GitModule.cs:rad 2557\r\n--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\r\n   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   vid Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()\r\n--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\r\n   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   vid Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()" | string

Comment (gerhardol) [reply GitCommands/Git/GitRef.cs]: I have a hard time reproducing this outside of the debugger at home. I have seen similar issues before also in normal builds, more in v3-ux, but likely also in master. Then it has been sporadic.
So this is probably not something new in v3-ux, maybe it occurs more often (?) due to optimizations even.

It seems like the problem occur if switching from the repo before submodule calculations are finished. This would explain why I have seen this more often in my daytime life where many recursive levels of submodules are used rather than with GE development (the test setup has a slightly heavier submodule too).

Another occurrence, pointing to the same analysis @drewnoakes made.

  | Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   vid System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   vid GitUI.ThreadHelper.CompletedResult[T](Task`1 task) i F:\\dev\\gc\\gitextensions_4\\GitExtUtils\\GitUI\\ThreadHelper.cs:rad 128\r\n   vid GitUI.FileStatusList.AppendItemSubmoduleStatus(String text, GitItemStatus item) i F:\\dev\\gc\\gitextensions_4\\GitUI\\UserControls\\FileStatusList.cs:rad 379\r\n   vid GitUI.FileStatusList.FileStatusListView_DrawItem(Object sender, DrawListViewItemEventArgs e) i F:\\dev\\gc\\gitextensions_4\\GitUI\\UserControls\\FileStatusList.cs:rad 332\r\n   vid System.Windows.Forms.ListView.OnDrawItem(DrawListViewItemEventArgs e)\r\n   vid System.Windows.Forms.ListView.CustomDraw(Message& m)" | string

**Comment by gerhardol** [comment]
Another issue related to revision parsing

Fetched GitExtensions repo
Probably before finished loading, I switched to another repo
I then got the following exception in the new repo, pointing to v3-ux head, that was used.
Cannot reproduce though.

   at GitUIPluginInterfaces.ObjectId.Parse(String s) in F:\dev\gc\gitextensions_4\Plugins\GitUIPluginInterfaces\ObjectId.cs:line 172
   at GitUI.RevisionGridControl.<>c.<GetAllParents>b__145_0(String line) in F:\dev\gc\gitextensions_4\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 1089
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitUI.RevisionGridControl.GetAllParents(ObjectId objectId) in F:\dev\gc\gitextensions_4\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 1087
   at GitUI.RevisionGridControl.<SelectInitialRevision>g__SearchRevision|144_1(ObjectId objectId) in F:\dev\gc\gitextensions_4\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 1064
   at GitUI.RevisionGridControl.SelectInitialRevision() in F:\dev\gc\gitextensions_4\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 1037
   at GitUI.RevisionGridControl.<>c__DisplayClass140_0.<<ForceRefreshRevisions>b__11>d.MoveNext() in F:\dev\gc\gitextensions_4\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 949
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext() in F:\dev\gc\gitextensions_4\GitExtUtils\GitUI\ThreadHelper.cs:line 101

**Comment by pmiossec** [comment]
I think we all agree that this PR introduce some great stuff. And that in the end, it will be merged....

But this PR cause some problem in the way that it changes a lot of things here and there that make things annoying for all the other development that are already or will later be done.

A lot(?) of PRs (I have one in the case and will have another one) that are done now will be broken by the merge of this PR or will break that PR and that will require later (pain in the a**) rework.

So, I think it will be much better if we merge this PR as soon as possible, even if not perfect, and fix problems when they occurred than keeping this PR open.

I think there is no added value to let this PR not merged any longer.

What do you think?

**Comment by gerhardol** [comment]
> I think there is no added value to let this PR not merged any longer.

That is the agreement, drew is cleaning up and will merge soon.
Separate issues have been opened (I have raised some issues too in this thread, that may not be new in this PR. As the PR is too big to show the comments in a simple way, we will restart the review from master).

**Comment by RussKie** [comment]
Absolutely in agreement.
Let's get this one merged and be back to the normal routine: found a bug -> raise and issue -> send a PR.

**Comment by drewnoakes** [comment]
Conflicts are now fixed and I've spent some time doing tests without finding any issues. I don't doubt we'll find a few issues over time, but they shouldn't be hard to fix and I will have time over the next weeks to respond to regressions I've introduced.

Thank you all for your patience. I think this is in good shape to be merged if others are happy. I'll continue work with small, focussed issues/PRs from now on.

**Comment by gerhardol** [comment]
For artificial commits in Browse revision grid, items are no longer visible (used to be disabled).
Duplicate separators should be removed

image

Checkout branch is gone (Ctrl-. still works)
image

**Comment by gerhardol** [comment]
Logging another issue:
Bare repos are not handled. This is mentioned in the description. Personally, I would not use a GUI with a bare repo (limited use though), but @KindDragon has commented on this previously.

Opening a bare repo (and fetch, probably not) raised an exception: Unable to parse object ID "HEAD".
(This was with a slightly older version of v3-ux, built 2018-07-16 22:31 UTC, not reproduced in latest).
HEAD should maybe be specially handled when parsing.

   at GitUIPluginInterfaces.ObjectId.Parse(String s) in F:\dev\gc\gitextensions_4\Plugins\GitUIPluginInterfaces\ObjectId.cs:line 172
   at GitCommands.GitModule.GetCurrentCheckout() in F:\dev\gc\gitextensions_4\GitCommands\Git\GitModule.cs:line 1278
   at GitUI.RevisionGridControl.ForceRefreshRevisions() in F:\dev\gc\gitextensions_4\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 818
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions() in F:\dev\gc\gitextensions_4\GitUI\CommandsDialogs\FormBrowse.cs:line 468
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext() in F:\dev\gc\gitextensions_4\GitUI\GitUIExtensions.cs:line 214
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext() in F:\dev\gc\gitextensions_4\GitExtUtils\GitUI\ThreadHelper.cs:line 101

**Comment by RussKie** [comment]
Let's get it merged and deal with regressions after

**Comment by drewnoakes** [comment]
@gerhardol the context menu issues should be sorted now. Turns out that setting a tool strip item's `Visible` property to `true` during the `Opening` event doesn't then read back as `true`, as the menu is not yet on screen.

The bare repo issue is a good one, thanks. I'll take a look at it tomorrow.

@RussKie feel free to merge if you're happy. I'll be offline for the next 12 hours or so.

**Comment by RussKie** [comment]
By the power vested in me by the members of the team, contributors and all good folks using Git Extensions I hereby pronounce this work complete irrespective of all regressions and bugs it may contain herein. Hence forth all bugs and regressions attributed to this PR are to be dealt by the traditional workflow - _raise issue -> submit a PR_.
You can send all kudos @drewnoakes's way and all disappointments and hate mail to `/dev/null`.

**Comment by gerhardol** [comment]
I have opened separate issues for those reported here (drew had opened some too).
Hope I never have to expand this PR again...

**Comment by regs01** [comment]
New gray window background color is a quite depressive. Default Windows #f0f0f0 is far better, softer and lighter. Light gradient that was there for toolbar is even more better.

**Comment by drewnoakes** [comment]
@regs01 can you provide a screenshot of what you're talking about? Most of the window background is solid white for me.

If you're talking about the dividing areas between panels, they're intended to contrast strongly with the white areas to help guide the eye on where sections are divided without needing 1px lines everywhere.

If you can provide a mockup of what you're talking about, it'd be great. I'd open a new issue, as this has been closed for a long while now. Thanks.

**Comment by regs01** [comment]
I'm talking about background window color. Which is all gray. #f0f0f0 is there for a reason. It's been tweaked by MS through decades.

**Comment by drewnoakes** [comment]
My background is white. Can you please add a screenshot?

**Comment by regs01** [comment]
gitextensions_2018-12-13_03-07-18

**Comment by drewnoakes** [comment]
Are you talking about the colour in the header? I do not feel the need for it to be changed, but if you open a new issue about this people can discuss it there.

Even better would be to make a PR with your proposed change and include before/after screenshots.

**Comment by brianjlacy** [comment]
I'm sorry to say I do not like the new background color for the window (e.g. the header) in 3.0.0. Not even a little. It only makes the icons and text harder to see. The light gray color before was far superior.

Some of the icons on the header -- the submodule/superproject icon for example -- also have degraded in 3.0.0, looking very ambiguous and visually out of place.

I appreciate the efforts, but I think there's some room for improvement.

**Comment by RussKie** [comment]
Feel free to offer a solution

**Comment by drewnoakes** [comment]
@brianjlacy with respect to the submodules icon, I'd like your thoughts on #5717.
