### PR TITLE
fix(RevisionDataGridView): Always select a revision

### LINKED ISSUE #11782: RevisionGrid: Artifacts caused by unintended selection frame if no current checkout
### Environment

- GitExtensions version: vNext

### Issue description

Sometimes after deleting an old branch, nothing is selected - always after creating an orphan branch.
Then the DataGridView (or something else) draws a selection frame around the whole(!) client area of the RevisionGrid.
When scrolling the grid, this frame is partially duplicated and moves with the outer row.
(The graph area seems to be redrawn entirely. Though afterwards, the frame is rendered again on top.)

4. image
5. image
6. image

### Steps to reproduce

1. Open a small test repo
2. Checkout a commit
3. Delete all branches (might be optional)
4. Create an orphan branch
5. Show RefLog
6. Scroll down and up

### Did this work in previous version of GitExtensions?

no, I have seen this for years

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11782

## Proposed changes

- If no selection can be restored, select the first shown real commit or the first row
- Set `CurrentCell` accordingly, which works wonders!

### Before

(after scrolling down and up again)

image

### After

image

## Test methodology 

- manual 

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Review by pmiossec — APPROVED** [review]

File: src/app/GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs [hunk 1]
```diff
@@ -484,7 +484,15 @@ public void LoadingCompleted()
 
                 if (_toBeSelectedGraphIndexesCache.Value.Count == 0)
                 {
-                    // Nothing to select or interrupted
+                    // Nothing to select or interrupted, select the first shown real commit or the first row (which exists here)
```
Comment (gerhardol) [inline src/app/GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs:487]: This check should probably be further below too, should _loadedToBeSelectedRevisionsCount that should be checked too?

**Review by gerhardol — APPROVED** [review]
Very brief usage, but should be fine: It is just an additional selection
