### PR TITLE
#5658 Update node cache to fix quick search

### LINKED ISSUE #5658: RevisionGrid: Quick search is broken
**Do you want to request a *feature* or report a *bug*?**
bug, regression

**What is the current behavior?**
quick search doesn't find commits anymore

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1.
  - check out master and select b7960d7
  - type `b` `c`
  - "bc" is displayed and the non-matching commit e4cd7e9 is selected

2.
  - select a newer commit from a different branch 
  - type `b` `c`
  - "bc" is displayed but the selection doesn't change

**What is the expected behavior?**
quick search finds the first matching commit seaching top down

**Environment you encounter the issue:**

- Git Extensions 3.00.a1
- b7960d79e0f1342064a18546108d21297398df64 
- Git 2.18.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0

**Did this work in previous version of GitExtensions (which)?**
yes, earlier master and 2.5

### PR DESCRIPTION
**Pull request by mstv**
Fixes #5658

Changes proposed in this pull request:
- update the node cache to ensure that the quick search *gets* the revisions
- match the quick search string anywhere in the `revision.Author`
 
Screenshots before and after (if PR changes UI):
- n/a

What did I do to test the code and ensure quality:
- manual testing

Has been tested on (remove any that don't apply):
- Git Extensions 3.00.a1
- 9ba3f7c
- Git 2.18.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0

### CODE REVIEW

File: GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs [hunk 1]
```diff
@@ -371,6 +371,7 @@ public bool RowIsRelative(int rowIndex)
         [CanBeNull]
         public GitRevision GetRevision(int rowIndex)
         {
+            _revisionGraph.CacheTo(rowIndex, /*no update of _orderedRowCache necessary*/ -1)
```
Comment (mstv) [inline GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs]: @spdr870, should we update the cache in chunks? Of which size?

Comment (spdr870) [reply GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs]: No, the cache you update here is only an ordered list of all the revisions. This is really fast to build. Even 200.000 commits are ordered in ~150ms. The second cache is more expensive, because the rows are being build there.

**Comment by spdr870** [comment]
@mstv I rpropose to make sure the revisions are ordered in the revisiongraph class itself. I pushed a commit with this change:
https://github.com/gitextensions/gitextensions/commit/0cd1ba98a136c3697a771a54f16488894d9737b1

File: GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs (hunk 1 above)
Comment (mstv) [reply GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs]: Good.

My idea was that the Cache could cache some more rows when the requested row has not been cached yet. Then the Cache will not need to update everytime the next row is requested.

**Comment by mstv** [comment]
Thank you! It seems to work well.
