### PR TITLE
Option - ask for confirmation on branch checkout

### LINKED ISSUE #11116: Add confirmation for checkout with double click
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.20
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

By default double-clicking on a branch will check it out without warning.
I have found that it often happens when selecting a branch and double-clicking inadvertently.
If you have no uncommitted changes then you can wait for the checkout to complete and checkout back to the branch you were on or abort and clean up the mess in the files.
There should be a confirmation dialog.

### Steps to reproduce

Double-click a branch in the list

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by IlijaQ**
Fixes #11116

## Proposed changes

- In Settings / Advanced / Confirmations / section Branches added `Checkout branch using left panel` checkbox (disabled by default). 
- By checking it, every time a user double-clicks on a branch on left panel, a message box will prompt asking to confirm if the user wants to checkout branch.

## Screenshots

ConfirmationSettingsForm
BranchCheckoutConfirmationMessageBox5

## Test methodology

- Manual with GE repo
- Tried closing and reopening the application. The selected option is saved after closing and reopening.

## Test environment(s)

- Git Extensions 33.33.33
- Build 6a64d95
- Git 2.30.0.windows.2 (recommended: 2.41.0 or later)
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by IlijaQ** [comment]
Hi Team,

I have few issues I want to discuss.

I have that issue while adding checkbox via graphical interface, VS automatically changes the ConfirmationSettingsPage.Designer.cs mostly erasing `this` keyword from all fields in file. I have tried to counteract it by reversing changes in formCommit before committing the file, but some changes in the designer I had to make by hand e.g. in lines 145 to 204 where new row is added for the new checkbox - reversing the changes will remove the room made for checkbox previously. I know that it is not recommended to manually edit the designer. What do you suggest on this?

Since we are adding an option to settings, will this reset the user settings for users updating from older versions? I suppose no, but just in case, I need to ask?

I have used TaskDialogIcon.Warning as a MessageBox icon, Is TaskDialogIcon.Information a more suitable icon?

**Comment by gerhardol** [comment]
Put this with the other confirmations
Add a possibility to deactivate from the dialog if enabled by default, see some other of these popups

image

**Comment by mstv** [comment]
> VS automatically changes the ConfirmationSettingsPage.Designer.cs mostly erasing this keyword from all fields in file.

I use to save the unmodified dialog and commit it separately first.

**Comment by IlijaQ** [comment]
> Put this with the other confirmations

I didn’t understand, I put it under confirmations section. Can you, please, clarify?
ConfirmationSettingsForm2

> Add a possibility to deactivate from the dialog if enabled by default, see some other of these popups

I didn’t include a possibility to deactivate from the dialogue because I made this option disabled by default. If you think that this option should be enabled by default or that the possibility to deactivate from the dialogue should be there anyway, I’ll make the necessary changes.

**Comment by gerhardol** [comment]
> I didn’t understand, I put it under confirmations section. Can you, please, clarify? ConfirmationSettingsForm2

> I didn’t include a possibility to deactivate from the dialogue because I made this option disabled by default. If you think that this option should be enabled by default or that the possibility to deactivate from the dialogue should be there anyway, I’ll make the necessary changes.

Fine I saw some other position for the setting. It was probably too late.

For VS changes, you can make an initial commit with the automatic changes if transferring wanted changes is too much.

Code looks reasonable.

File: GitCommands/Settings/AppSettings.cs [hunk 1]
```diff
@@ -1839,6 +1839,12 @@ public static DiffListSortType DiffListSorting
             set => SetEnum("DiffListSortType", value);
         }
 
+        public static bool DontConfirmBranchCheckout
+        {
+            get => GetBool("DontConfirmBranchCheckout", true);
+            set => SetBool("DontConfirmBranchCheckout", value);
+        }
```
Comment (RussKie) [inline GitCommands/Settings/AppSettings.cs:1846]: I _think_ all other similar settings are grouped together. If so, please put the new settings near those.

File: GitUI/MessageBoxes.cs [hunk 2]
```diff
@@ -127,6 +131,21 @@ public static bool ConfirmUpdateSubmodules(IWin32Window? owner)
...
         }
 
+        public static bool ConfirmBranchCheckout(IWin32Window? owner)
+        {
+            TaskDialogPage page = new()
+            {
+                Text = Instance._confirmBranchCheckout.Text,
+                Heading = Instance._confirmCheckoutHeader.Text,
+                Caption = Instance._confirmCheckout.Text,
+                Icon = TaskDialogIcon.Warning,
```
Comment (RussKie) [inline GitUI/MessageBoxes.cs:141]: Why is it a warnings? We use the info icon in other dialogs.

File: GitCommands/Settings/AppSettings.cs (hunk 1 above)
Comment (mstv) [reply GitCommands/Settings/AppSettings.cs:1846]: For new settings, please use:
```suggestion
        public static readonly ISetting<bool> DontConfirmBranchCheckout= Setting.Create(ConfirmationsSettingsPath , nameof(DontConfirmBranchCheckout), true);
```

Needs to be added to the top of the file:
```
        private static readonly SettingsPath ConfirmationsSettingsPath = new AppSettingsPath("Confirmations");
```

File: GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs [hunk 3]
```diff
@@ -24,6 +24,7 @@ protected override void SettingsToPage()
             chkPushNewBranch.Checked = !AppSettings.DontConfirmPushNewBranch;
             chkAddTrackingRef.Checked = !AppSettings.DontConfirmAddTrackingRef;
             chkBranchDeleteUnmerged.Checked = !AppSettings.DontConfirmDeleteUnmergedBranch;
+            chkBranchCheckoutConformation.CheckState = ToCheckboxStateInverted(AppSettings.DontConfirmBranchCheckout);
```
Comment (mstv) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs:27]:
```suggestion
            chkBranchCheckoutConformation.CheckState = ToCheckboxStateInverted(AppSettings.DontConfirmBranchCheckout.Value);
```

File: GitUI/MessageBoxes.cs (hunk 2 above)
Comment (mstv) [reply GitUI/MessageBoxes.cs:141]: Please use `MessageBoxes.Confirm()`.

Feel free to make `MessageBoxes.Show()` use a `TaskDialog` instead of a `MessageBox` - rather in a separate PR though.

**Comment by IlijaQ** [comment]
Ok, here's what I have changed:

I have reverted my changes to the Designer since it was changed by hand. I added an initial commit with the automatic changes and another commit with changes made in graphical design, as @mstv and @gerhardol suggested.

Applyed code changes to `AppSettings.cs` and `ConfirmationSettingsPage.cs` as @mstv suggested.

> I think all other similar settings are grouped together. If so, please put the new settings near those.

Some of the settings are grouped together, but not all of them. After applying the suggested code changes, I put the new setting near some of the branch settings.

Message box implemented with `MessageBoxes.Confirm()` according to your suggestion.
BranchCheckoutConfirmationMessageBox3
The screenshot in the PR description is updated to represent the new message box.

Text added to English.xlf

File: GitCommands/Settings/AppSettings.cs (hunk 1 above)
Comment (IlijaQ) [reply GitCommands/Settings/AppSettings.cs]: Some of the settings are grouped together, but not all of them. After applying the suggested code changes, I put the new setting near some of the branch settings.

File: GitUI/MessageBoxes.cs [hunk 4]
```diff
@@ -46,6 +46,9 @@ public class MessageBoxes : Translate
         private readonly TranslationString _cannotOpenSubmoduleCaption = new("Cannot open submodule");
         private readonly TranslationString _cannotOpenGitExtensionsCaption = new("Cannot open Git Extensions");
 
+        private readonly TranslationString _confirmBranchCheckoutCaption = new("Confirm checkout");
+        private readonly TranslationString _confirmBranchCheckout = new("Are you sure you want to check out this branch?");
```
Comment (mstv) [inline GitUI/MessageBoxes.cs:50]: ❔ name the branch in the confirmation
```suggestion
        private readonly TranslationString _confirmBranchCheckout = new(@"Are you sure you want to check out branch ""{0}""?");
```

File: GitUI/MessageBoxes.cs [hunk 5]
```diff
@@ -127,6 +130,11 @@ public static bool ConfirmUpdateSubmodules(IWin32Window? owner)
             return result;
         }
 
+        public static bool ConfirmBranchCheckout(IWin32Window? owner)
+        {
+            return Confirm(owner, Instance._confirmBranchCheckout.Text, Instance._confirmBranchCheckoutCaption.Text);
+        }
```
Comment (mstv) [inline GitUI/MessageBoxes.cs:136]:
```suggestion
        => Confirm(owner, string.Format(Instance._confirmBranchCheckout.Text, branchName), Instance._confirmBranchCheckoutCaption.Text);
```
with `branchName` as additional argument

File: GitUI/Translation/English.xlf [hunk 6]
```diff
@@ -1053,6 +1053,10 @@ Please make sure that Git for Windows is installed or set the correct command ma
         <source>Commit when no branch is currently checked out (headless state)</source>
         <target />
       </trans-unit>
+      <trans-unit id="chkBranchCheckoutConformation.Text">
+        <source>Always ask for confirmation on branch checkout</source>
```
Comment (mstv) [inline GitUI/Translation/English.xlf:1057]:
```suggestion
        <source>Checkout branch using left panel</source>
```

File: GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs [hunk 7]
```diff
@@ -28,346 +28,383 @@ protected override void Dispose(bool disposing)
...
-            this.chkBranchDeleteUnmerged.Location = new System.Drawing.Point(3, 220);
-            this.chkBranchDeleteUnmerged.Name = "chkBranchDeleteUnmerged";
-            this.chkBranchDeleteUnmerged.Size = new System.Drawing.Size(168, 19);
-            this.chkBranchDeleteUnmerged.Text = "Delete unmerged branches";
-            this.chkBranchDeleteUnmerged.UseVisualStyleBackColor = true;
+            chkBranchCheckoutConformation.AutoSize = true;
+            chkBranchCheckoutConformation.Location = new Point(3, 245);
+            chkBranchCheckoutConformation.Name = "chkBranchCheckoutConformation";
+            chkBranchCheckoutConformation.Size = new Size(282, 19);
+            chkBranchCheckoutConformation.TabIndex = 22;
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs:389]: TabIndex was added, this is now incorrect.
Also move to the position in the form

**Review by gerhardol — COMMENTED** [review]
A few comments, otherwise fine to me.
As this is a draft, I suggest you fix the comments, squash and rebase on master before removing draft.

File: GitUI/LeftPanel/RepoObjectsTree.cs [hunk 8]
```diff
@@ -632,6 +632,11 @@ private void SelectNode(NodeBase node, bool multiple, bool includingDescendants)
 
         private void OnNodeDoubleClick(object sender, TreeNodeMouseClickEventArgs e)
         {
+            if (!AppSettings.DontConfirmBranchCheckout.Value && !MessageBoxes.ConfirmBranchCheckout(this))
+            {
+                return;
+            }
+
```
Comment (mstv) [inline GitUI/LeftPanel/RepoObjectsTree.cs:639]: This is too early here - definitely not to be done before HitTest.
And it shall affect branches only.
Hence it needs to be moved to both `LocalBranchNode.Checkout` and `RemoteBranchNode.Checkout`.
The check for `AppSettings.DontConfirmBranchCheckout.Value` can be moved to `MessageBoxes.ConfirmBranchCheckout`.

**Review by mstv — COMMENTED** [review]
I have noticed a few more points.

File: GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs [hunk 9]
```diff
@@ -24,6 +24,7 @@ protected override void SettingsToPage()
             chkPushNewBranch.Checked = !AppSettings.DontConfirmPushNewBranch;
             chkAddTrackingRef.Checked = !AppSettings.DontConfirmAddTrackingRef;
             chkBranchDeleteUnmerged.Checked = !AppSettings.DontConfirmDeleteUnmergedBranch;
+            chkBranchCheckoutConformation.CheckState = ToCheckboxStateInverted(AppSettings.DontConfirmBranchCheckout.Value);
```
[the remark this answers is not in the document]
Comment (gerhardol) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs:27]: I think this was intentional, this is a tri-state box

[the remark this answers is not in the document]
Comment (mstv) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs:27]: This is a global settings, i.e. without other sources nor inheritance. Unset `bool` settings make use of the default value given to `Setting.Create`.
(All those other confirmation checkboxes around do not use `ToCheckboxStateInverted`.)

File: GitCommands/Settings/AppSettings.cs [hunk 10]
```diff
@@ -1003,6 +1004,8 @@ public static bool DontConfirmCommitIfNoBranch
             set => SetBool("DontConfirmCommitIfNoBranch", value);
         }
 
+        public static readonly ISetting<bool> DontConfirmBranchCheckout = Setting.Create(ConfirmationsSettingsPath, nameof(DontConfirmBranchCheckout), true);
```
[the remark this answers is not in the document]
Comment (IlijaQ) [reply GitCommands/Settings/AppSettings.cs:1007]: > This will make this setting separate from similar settings though

Yes, almost all settings in AppSettings.cs are named as negative, but ok, I’ll make the changes as you suggested.

**Comment by IlijaQ** [comment]
OK, thanks for the detailed feedback. I’ll update the code as you suggested.

File: GitCommands/Settings/AppSettings.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (mstv) [reply GitCommands/Settings/AppSettings.cs:1007]: Yes, the old settings names have been kept for downward compatibility with existing setting files of the users.

**Comment by pmiossec** [comment]
@IlijaQ Seems good except, please run `update-loc.cmd`. It seems that the translation file is not up to date... (CI is not happy.)
You could also maybe remove the draft state of this PR.

Side note: it seems that the last version of Visual Studio remove the `this.` on the generated `.designer.cs` file making even more a pain to read the diff. Maybe we should do a PR to remove it to all files. What do you think? I maybe could do that if everyone agrees...

**Comment by IlijaQ** [comment]
I ran `update-loc.cmd` it appears to have worked. Thank you.

Removed the draft state of PR.

> Maybe we should do a PR to remove it to all files. What do you think?

I don’t know if the majority of currently active contributors are using the latest version of VS that does this. If so, I think it would be fine.

File: GitCommands/Settings/AppSettings.cs [hunk 11]
```diff
@@ -33,6 +33,7 @@ public static class AppSettings
         public static DistributedSettings SettingsContainer { get; private set; }
 
         private static readonly SettingsPath DetailedSettingsPath = new AppSettingsPath("Detailed");
+        private static readonly SettingsPath ConfirmationsSettingsPath = new AppSettingsPath("Confirmations");
```
Comment (mstv) [inline GitCommands/Settings/AppSettings.cs:36]: Class members of the same category should be sorted alphabetically (when added - although there are lots of deviations from this style rule in the existing code).
```suggestion
        private static readonly SettingsPath ConfirmationsSettingsPath = new AppSettingsPath("Confirmations");
        private static readonly SettingsPath DetailedSettingsPath = new AppSettingsPath("Detailed");
```

File: GitUI/LeftPanel/LocalBranchNode.cs [hunk 12]
```diff
@@ -54,6 +54,11 @@ internal override void OnDelete()
 
         public bool Checkout()
         {
+            if (!MessageBoxes.ConfirmBranchCheckout(null, FullPath))
+            {
+                return false;
+            }
+
             return UICommands.StartCheckoutBranch(ParentWindow(), branch: FullPath, remote: false);
```
Comment (mstv) [inline GitUI/LeftPanel/LocalBranchNode.cs:62]:
```suggestion
            return MessageBoxes.ConfirmBranchCheckout(ParentWindow(), FullPath)
                && UICommands.StartCheckoutBranch(ParentWindow(), branch: FullPath, remote: false);
```

File: GitUI/LeftPanel/RemoteBranchNode.cs [hunk 13]
```diff
@@ -63,6 +63,11 @@ public bool Delete()
 
         public bool Checkout()
         {
+            if (!MessageBoxes.ConfirmBranchCheckout(null, FullPath))
+            {
+                return false;
+            }
+
             return UICommands.StartCheckoutRemoteBranch(TreeViewNode.TreeView, FullPath);
```
Comment (mstv) [inline GitUI/LeftPanel/RemoteBranchNode.cs:71]: ditto

File: GitUI/MessageBoxes.cs [hunk 14]
```diff
@@ -127,6 +130,16 @@ public static bool ConfirmUpdateSubmodules(IWin32Window? owner)
...
 
+        public static bool ConfirmBranchCheckout(IWin32Window? owner, string branchName)
+        {
+            if (AppSettings.ConfirmBranchCheckout.Value)
+            {
+                return Confirm(owner, string.Format(Instance._confirmBranchCheckout.Text, branchName), Instance._confirmBranchCheckoutCaption.Text);
+            }
+
+            return true;
+        }
```
Comment (mstv) [inline GitUI/MessageBoxes.cs:141]:
```suggestion
        => AppSettings.ConfirmBranchCheckout.Value
            ? Confirm(owner, string.Format(Instance._confirmBranchCheckout.Text, branchName), Instance._confirmBranchCheckoutCaption.Text)
            : true;
```

**Review by mstv — COMMENTED** [review]
final nits

**Review by gerhardol — COMMENTED** [review]
+2 after mstv changes

File: GitUI/LeftPanel/LocalBranchNode.cs [hunk 15]
```diff
@@ -54,6 +54,11 @@ internal override void OnDelete()
 
         public bool Checkout()
         {
+            if (!MessageBoxes.ConfirmBranchCheckout(null, FullPath))
```
Comment (RussKie) [inline GitUI/LeftPanel/LocalBranchNode.cs:57]: ❗  Messages must always have a parent

**Review by RussKie — CHANGES_REQUESTED** [review]
As per @mstv reviews

**Comment by RussKie** [comment]
> Side note: it seems that the last version of Visual Studio remove the `this.` on the generated `.designer.cs` file making even more a pain to read the diff. Maybe we should do a PR to remove it to all files. What do you think? I maybe could do that if everyone agrees...

That'd be great, thank you.

/cc: @merriemcgaw FYI

File: GitUI/LeftPanel/LocalBranchNode.cs [hunk 16]
```diff
@@ -1,4 +1,5 @@
 ﻿using System.Diagnostics;
+using GitUI.CommandsDialogs;
```
Comment (mstv) [inline GitUI/LeftPanel/LocalBranchNode.cs:2]: Should be removed
```suggestion
```

File: GitUI/MessageBoxes.cs [hunk 17]
```diff
@@ -127,6 +130,10 @@ public static bool ConfirmUpdateSubmodules(IWin32Window? owner)
             return result;
         }
 
+        public static bool ConfirmBranchCheckout(IWin32Window? owner, string branchName)
+            => AppSettings.ConfirmBranchCheckout.Value
+            ? Confirm(owner, string.Format(Instance._confirmBranchCheckout.Text, branchName), Instance._confirmBranchCheckoutCaption.Text) : true;
```
Comment (mstv) [inline GitUI/MessageBoxes.cs:135]: Support Left Reading, please!
The long one-liners in the `Checkout` methods are at my limit.
But this one should match our code style:
```suggestion
            => AppSettings.ConfirmBranchCheckout.Value
                ? Confirm(owner, string.Format(Instance._confirmBranchCheckout.Text, branchName), Instance._confirmBranchCheckoutCaption.Text)
                : true;
```
or a little mind-bending:
```suggestion
            => !AppSettings.ConfirmBranchCheckout.Value || Confirm(owner, string.Format(Instance._confirmBranchCheckout.Text, branchName), Instance._confirmBranchCheckoutCaption.Text);
```

**Comment by RussKie** [comment]
> Side note: it seems that the last version of Visual Studio remove the `this.` on the generated `.designer.cs` file making even more a pain to read the diff. Maybe we should do a PR to remove it to all files. What do you think? I maybe could do that if everyone agrees...

The designer is now ".editorconfig"-aware, meaning if `this.` is discouraged via the .editorconfig, then the designer will remove `this.` from the designer files.
Perhaps, we could try something like that and see if that'd work:
```
[*.Designer.cs]
dotnet_style_qualification_for_field = true:suggestion
```

File: GitUI/MessageBoxes.cs (hunk 17 above)
Comment (IlijaQ) [reply GitUI/MessageBoxes.cs:135]: Maybe we should break the parameters of the `Confirm` method into separate lines as done by calling `Show` method in the `ShowGitConfigurationExceptionMessage` method in the same file. What do you think?

```suggestion
        public static bool ConfirmBranchCheckout(IWin32Window? owner, string branchName)
            => AppSettings.ConfirmBranchCheckout.Value
                ? Confirm(owner,
                    string.Format(Instance._confirmBranchCheckout.Text, branchName),
                    Instance._confirmBranchCheckoutCaption.Text)
                : true;
```

Comment (mstv) [reply GitUI/MessageBoxes.cs:135]: In principle, yes. 😀 This `string.Format` is of low interest though. And we prefer to use the available screen width for arguments then.

**Review by mstv — APPROVED** [review]

**Review by gerhardol — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you
