### PR TITLE
Present git-diff errors in diffViewer

### LINKED ISSUE #11164: [NBug] Crash on Delta of Excel document while it was Open.
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.3
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.21
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --ignore-all-space --unified=3 -- "Grade_Worksheet.xlsx"
Working directory: C:\Users\goldbishop\OneDrive - Jefferson State Community College\Courses\CIS150_Material\

```
GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at async Task<ExecutionResult> GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action<StreamWriter> writeInput, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes, bool throwOnErrorExit, CancellationToken cancellationToken) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 338
   at async Task<Patch> GitCommands.GitModule.GetSingleDiffAsync(ObjectId firstId, ObjectId secondId, string fileName, string oldFileName, string extraDiffArguments, Encoding encoding, bool cacheResult, bool isTracked) in C:/projects/gitextensions/GitCommands/Git/GitModule.cs:line 2409
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, int? line, string defaultText, Action openWithDiffTool, string additionalCommandInfo)+GetItemPatchAsync(?) in C:/projects/gitextensions/GitUI/GitUIExtensions.cs:line 168
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, int? line, string defaultText, Action openWithDiffTool, string additionalCommandInfo)+GetSelectedPatchAsync(?) in C:/projects/gitextensions/GitUI/GitUIExtensions.cs:line 169
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, int? line, string defaultText, Action openWithDiffTool, string additionalCommandInfo) in C:/projects/gitextensions/GitUI/GitUIExtensions.cs:line 170
   at async void GitUI.CommandsDialogs.FormCommit.ShowChanges(FileStatusItem item, bool staged)+(?) => { } [0] in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCommit.cs:line 1200
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { } in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 41
```

The Commit window was trying to represent a Binary File (XLSX)

### Steps to reproduce
1. With the Excel document opened, attempt to make a commit
2. In my scenario, the Excel document was at the top of the list of changes to be committed.

### Did this work in previous version of GitExtensions?

Yes, it simply showed the Hex-code of the file with the side-bar text typical with a Hex-editor.

### Diagnostics
After review, if the Excel document was closed prior to the Commit Window opening up, the exception did not occur.

Seems the preview window is trying to get a File Lock on the document during the Delta evaluation.  May also be in combination with the Delta Filter Settings.

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #11164 (and probably a few more)

## Proposed changes

Present the error output from git-diff that fail in the diff viewer instead of starting NBug.

git-diff is expected to be Git or user error, no need to show NBug in this scenario.
The error is not suppressed, it can still be reported manually (this could still be a GE issue, as in my error insertion).

This is a hack, especially for the submodule status.

## Screenshots 

Inserted error by editing the code

### Before

NBug popup

### After

image

image

## Test methodology 

manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitCommands/Git/GitModule.cs [hunk 1]
```diff
@@ -2516,7 +2516,7 @@ public IReadOnlyList<GitStash> GetStashes(bool noLocks = false)
             return stashes;
         }
 
-        public async Task<Patch?> GetSingleDiffAsync(
+        public async Task<(Patch? patch, string? errMsg)> GetSingleDiffAsync(
```
Comment (RussKie) [inline GitCommands/Git/GitModule.cs:2519]:
```suggestion
        public async Task<(Patch? patch, string? errorMessage)> GetSingleDiffAsync(
```

Ditto below

**Review by RussKie — APPROVED** [review]
👍 with a small change requested

File: GitCommands/Git/GitModule.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs]: all occurrences updated

File: GitCommands/Git/GitModule.cs [hunk 2]
```diff
@@ -2547,17 +2547,20 @@ public IReadOnlyList<GitStash> GetStashes(bool noLocks = false)
...
-            bool nonZeroGitExitCode = firstId == ObjectId.WorkTreeId && secondId is not null && !isTracked;
             ExecutionResult result = await _gitExecutable.ExecuteAsync(
                 args,
                 cache: cache,
                 outputEncoding: LosslessEncoding,
-                throwOnErrorExit: !nonZeroGitExitCode);
+                throwOnErrorExit: false);
+            if (!result.ExitedSuccessfully)
+            {
+                return (patch: null, errorMessage: $"{result.StandardError}{Environment.NewLine}Git command: {args} ({result.ExitCode}){Environment.NewLine}");
```
Comment (mstv) [inline GitCommands/Git/GitModule.cs:2557]: ❔
```suggestion
                return (patch: null, errorMessage: $"{result.StandardError}{Environment.NewLine}exit code {result.ExitCode} from git {args}{Environment.NewLine}");
```

File: GitUI/GitUIExtensions.cs [hunk 3]
```diff
@@ -145,15 +145,15 @@ void OpenWithDiffTool()
...
 
                 cancellationToken.ThrowIfCancellationRequested();
                 return file.IsSubmodule
-                    ? LocalizationHelpers.ProcessSubmodulePatch(fileViewer.Module, file.Name, patch)
-                    : patch?.Text;
+                    ? LocalizationHelpers.ProcessSubmodulePatch(fileViewer.Module, file.Name, result.Value.patch)
+                    : result.Value.patch?.Text ?? result.Value.errorMessage;
 
-                static async Task<Patch?> GetItemPatchAsync(
+                static async Task<(Patch? patch, string? errorMessage)?> GetItemPatchAsync(
```
Comment (mstv) [inline GitUI/GitUIExtensions.cs:156]:
```suggestion
                static async Task<(Patch? patch, string? errorMessage)> GetItemPatchAsync(
```

File: GitUI/GitUIExtensions.cs [hunk 4]
```diff
@@ -145,15 +145,15 @@ void OpenWithDiffTool()
                         : $"Failed to get status for submodule \"{file.Name}\"";
                 }
 
-                var patch = await GetItemPatchAsync(fileViewer.Module, file, firstId, selectedId,
+                (Patch? patch, string? errorMessage)? result = await GetItemPatchAsync(fileViewer.Module, file, firstId, selectedId,
```
Comment (mstv) [inline GitUI/GitUIExtensions.cs:148]:
```suggestion
                (Patch? patch, string? errorMessage) = await GetItemPatchAsync(fileViewer.Module, file, firstId, selectedId,
```

File: GitUI/GitUIExtensions.cs [hunk 5]
```diff
@@ -145,15 +145,15 @@ void OpenWithDiffTool()
...
                     fileViewer.GetExtraDiffArguments(), fileViewer.Encoding);
 
                 cancellationToken.ThrowIfCancellationRequested();
                 return file.IsSubmodule
-                    ? LocalizationHelpers.ProcessSubmodulePatch(fileViewer.Module, file.Name, patch)
-                    : patch?.Text;
+                    ? LocalizationHelpers.ProcessSubmodulePatch(fileViewer.Module, file.Name, result.Value.patch)
+                    : result.Value.patch?.Text ?? result.Value.errorMessage;
```
Comment (mstv) [inline GitUI/GitUIExtensions.cs:154]:
```suggestion
                    ? LocalizationHelpers.ProcessSubmodulePatch(fileViewer.Module, file.Name, patch)
                    : patch?.Text ?? errorMessage;
```
For submodule, the error is swallowed.

File: GitCommands/Git/GitModule.cs (hunk 2 above)
Comment (gerhardol) [reply GitCommands/Git/GitModule.cs:2557]: I rather see the command first, the error code is not often interesting

File: GitUI/GitUIExtensions.cs (hunk 5 above)
Comment (gerhardol) [reply GitUI/GitUIExtensions.cs:154]: The error message is set as the name, so it is somehow presented. This is a hack, should not occur very often especially for submodules (I considered ignoring them completely)

File: GitCommands/Git/GitModule.cs (hunk 2 above)
Comment (mstv) [reply GitCommands/Git/GitModule.cs:2557]: I like to be able to copy the complete git command including "git".
The meaning of the trailing " (n)" would not be very clear and would break the git command line if not omitted.

Comment (gerhardol) [reply GitCommands/Git/GitModule.cs]: adjusted

**Review by mstv — APPROVED** [review]
