### PR TITLE
Skip LoadHotkeys if the control has not been loaded yet

### LINKED ISSUE #11367: [NBug] The UI Command Source is not available for this control in FileViewer.ReloadHotkeys
### Environment

- Git Extensions 33.33.33
- Build 245952dad3237e6befc12920e36693723c98d0d9
- Git 2.42.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

"The UI Command Source is not available for this control" in `FileViewer.ReloadHotkeys`. Occurred only once after closing the settings dialog. 
```
System.InvalidOperationException: The UI Command Source is not available for this control. Are you calling methods before adding it to the parent control?
   at GitUI.GitModuleControl.get_UICommandsSource() in D:\Build\gitextensions3\GitUI\GitModuleControl.cs:line 56
   at GitUI.GitModuleControl.ResourceManager.IGitModuleControl.get_UICommands() in D:\Build\gitextensions3\GitUI\GitModuleControl.cs:line 76
   at ResourceManager.GitExtensionsControl.TryGetUICommands(IGitUICommands& commands) in D:\Build\gitextensions3\ResourceManager\GitExtensionsControl.cs:line 91
   at ResourceManager.GitExtensionsControl.LoadHotkeys(String hotkeySettingsName) in D:\Build\gitextensions3\ResourceManager\GitExtensionsControl.cs:line 177
   at GitUI.Editor.FileViewer.ReloadHotkeys() in D:\Build\gitextensions3\GitUI\Editor\FileViewer.cs:line 335
   at GitUI.CommandsDialogs.RevisionFileTreeControl.ReloadHotkeys() in D:\Build\gitextensions3\GitUI\CommandsDialogs\RevisionFileTreeControl.cs:line 315
   at GitUI.CommandsDialogs.FormBrowse.HandleSettingsChanged(String oldTranslation, CommitInfoPosition oldCommitInfoPosition) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormBrowse.cs:line 1413
   at GitUI.CommandsDialogs.FormBrowse.OnShowSettingsClick(Object sender, EventArgs e) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormBrowse.cs:line 1394
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.PerformClick()
   at GitUI.CommandsDialogs.FormBrowse.ExecuteCommand(Int32 cmd) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormBrowse.cs:line 2076
   at ResourceManager.GitExtensionsFormBase.ProcessHotkey(Keys keyData) in D:\Build\gitextensions3\ResourceManager\GitExtensionsFormBase.cs:line 56
   at GitUI.CommandsDialogs.FormBrowse.ProcessHotkeyImpl(Keys keyData) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormBrowse.cs:line 2022
   at GitUI.CommandsDialogs.FormBrowse.ProcessHotkey(Keys keyData) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormBrowse.cs:line 2006
   at ResourceManager.GitExtensionsFormBase.ProcessCmdKey(Message& msg, Keys keyData) in D:\Build\gitextensions3\ResourceManager\GitExtensionsFormBase.cs:line 98
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData) in D:\Build\gitextensions3\ResourceManager\GitExtensionsControl.cs:line 189
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

### Steps to reproduce

?

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11367

## Proposed changes

- Skip `LoadHotkeys` if the control has not been loaded yet, e.g. because it is invisible,
  in order to avoid exception about missing UI Command Source
  The hotkeys will be fetched later in `OnRuntimeLoad`.
- Turn `GitExtensionsControl.TryGetUICommands` into property `ServiceProvider`
  because `TryGet` was misleading: It threw an `InvalidOperationException` anyway.
- Factor out base class `TranslatedControl` from `GitExtensionsControl` and
- Use it as base class for `SettingsPageBase` instead - in order to not need to declare its property `ServiceProvider` as `new`

## Screenshots 

N/A

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]
Do we need the same for any other controls (e.g., diff control)?

**Comment by mstv** [comment]
> Do we need the same for any other controls (e.g., diff control)?

Yes, this is safer. Done for all usages of `ReloadHotkeys` / `LoadHotkeys`. All the controls load it in `OnRuntimeLoad`.

**Review by gerhardol — COMMENTED** [review]
+2
I have seen this too.
Not formally approving as I am not sure how this affects key loading. For sure, not crashing reloading is better, the consequence should be to not load hotkeys OnLoad and HandleSettingsChanged. 
Any alternatives?
I agree with merging this now.

File: GitUI/CommandsDialogs/RevisionDiffControl.cs [hunk 1]
```diff
@@ -189,6 +189,11 @@ bool SelectFirstGroupChangesIfFileNotFocused()
 
         public void ReloadHotkeys()
         {
+            if (!Visible)
+            {
+                return;
+            }
+
             LoadHotkeys(HotkeySettingsName);
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionDiffControl.cs:197]: Why not do this inside `LoadHotkeys`?

Comment (mstv) [reply GitUI/CommandsDialogs/RevisionDiffControl.cs]: > Not formally approving as I am not sure how this affects key loading. For sure, not crashing reloading is better, the consequence should be to not load hotkeys OnLoad and HandleSettingsChanged.
Any alternatives?

> Why not do this inside LoadHotkeys?

Done. It took some time because of the misleading `TryGetUICommands`.

File: ResourceManager/GitExtensionsControl.cs [hunk 2]
```diff
@@ -37,6 +39,8 @@ protected override void OnLoad(EventArgs e)
         {
             base.OnLoad(e);
 
+            _loaded = true;
```
Comment (RussKie) [inline ResourceManager/GitExtensionsControl.cs:42]: This should be on line:48.

File: GitUI/GitModuleControl.cs [hunk 3]
```diff
@@ -69,9 +69,11 @@ public IGitUICommandsSource UICommandsSource
             }
         }
 
-        /// <summary>Gets the <see cref="UICommandsSource"/>'s <see cref="GitUICommands"/> reference.</summary>
+        /// <summary>
+        ///  Gets the <see cref="UICommandsSource"/>'s <see cref="GitUICommands"/> reference.
+        /// </summary>
         [Browsable(false)]
-        public GitUICommands UICommands => UICommandsSource.UICommands;
+        public override GitUICommands UICommands => UICommandsSource.UICommands;
```
Comment (RussKie) [inline GitUI/GitModuleControl.cs:76]: This change concerns me, feels like we're now mixing unrelated behaviours here.

What was the problem with the TryGetUiCommands API?

File: ResourceManager/GitExtensionsControl.cs (hunk 2 above)
Comment (gerhardol) [reply ResourceManager/GitExtensionsControl.cs:42]: or be renamed _hotkeysLoaded, that is how the value is used.

**Review by gerhardol — COMMENTED** [review]
+1

File: GitUI/GitModuleControl.cs (hunk 3 above)
Comment (mstv) [reply GitUI/GitModuleControl.cs:76]: > What was the problem with the TryGetUiCommands API?

1. `TryGetUICommands` threw exceptions instead of returning `false`!
2. There is no situation where the ServiceProvider is optional. (Calls depending on this shall be deferred to `OnRuntimeLoad`.)
    `LoadHotkeys` is the only user of `TryGetUICommands`.
    (`Visible` is not a the correct replacement of `_loaded` because `OnRuntimeLoad` is called once when a control is shown for the first time. Later it could be invisible because of switching tabs. Reloading hotkeys in every `OnShow` would not be good.)

This is not mixing unrelated things.
For GitModuleControls, the former `TryGetUICommands` / new `virtual` property `UICommands` is not called but the override in GitModuleControl, which directly returns the instance without the cast.
That's why the implementation can be shortened.
(I kept the full variant for having a smaller changeset in the review, and for avoiding the discussion whether there will be controls which implement `IGitModuleControl` but do not inherit from `GitModuleControl`.)
```
        /// <summary>
        ///  Attempts to find an instance of <see cref="IGitUICommands"/>.
        /// </summary>
        /// <remark>
        ///  The instance of <see cref="IGitUICommands"/>
        ///  either directly assigned to the control (if the control inherits from <see cref="GitModuleControl"/> which overrides this property)
        ///  or to the parent form (if the form implements <see cref="IGitModuleForm"/>).
        /// </remark>>
        /// <returns>
        ///  <see langword="true"/>, if an instance of <see cref="IGitUICommands"/> is found; <see langword="false"/>, otherwise.
        /// </returns>
        /// <exception cref="InvalidOperationException">
        ///  If this control is not a <see cref="GitModuleControl"/>) and is not placed in a <see cref="IGitModuleForm"/>.
        /// </exception>
        public virtual IGitUICommands UICommands
            => FindForm() is IGitModuleForm form ? form.UICommands
                : throw new InvalidOperationException($"no chance to get {nameof(UICommands)}");
```

Comment (mstv) [reply GitUI/GitModuleControl.cs:76]: I have thought about it again.

> feels like we're now mixing unrelated behaviours here.

Yes, you are right.

> What was the problem with the TryGetUiCommands API?

In addition to the above points, also the second part of the identifier and the return type - in the very first place.
Because, if a control needs `UICommands` it shall implement `IGitModuleControl` / inherit from `GitModuleControl`, but not try to downcast to `IGitModuleControl`.
We just need the `ServiceProvider` for `GitExtensionsControl`.
(With this, a better name for `_loaded` became obvious. `_hotkeysLoaded` would not have matched to exact meaning.)

**Review by gerhardol — COMMENTED** [review]
+1

**Comment by RussKie** [comment]
I'm on a road trip atm, will check when I get home.

File: GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs [hunk 4]
```diff
@@ -48,7 +48,7 @@ protected ISettingsPageHost PageHost
 
         public virtual SettingsPageReference PageReference => new SettingsPageReferenceByType(GetType());
 
-        protected internal IServiceProvider ServiceProvider { get; }
+        protected internal new IServiceProvider ServiceProvider { get; }
```
Comment (RussKie) [inline GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs:51]: Why do we need to shadow (i.e., `new`) here?

**Review by RussKie — COMMENTED** [review]
I think this change look good, just want to understand the shadowing aspect.

File: GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs (hunk 4 above)
Comment (mstv) [reply GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs:51]: I was not sure and did not try whether the settings pages would directly work with the new inherited property `GitExtensionsControl.ServiceProvider`, i.e. whether it becomes available early enough.
I have tried to declare the property `virtual` but this has not worked due to `protected internal`. (IMHO there are too many variations of visibility modifiers in C#.)

Comment (RussKie) [reply GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs:51]: Are you able to check if the change in this file can be reverted? And if not, I'd like to be better understand why we need it (and have that documented).
Other than that, :shipit:

Comment (mstv) [reply GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs:57]: > Are you able to check if the change in this file can be reverted? And if not, I'd like to be better understand why we need it (and have that documented).

I have added the xmldoc:
```
        /// <summary>
        ///  Gets the instance of <see cref="IServiceProvider"/> as assigned in the constructor.
        ///  This property replaces the property <see cref="GitExtensionsControl.ServiceProvider"/>,
        ///  which would be available only for controls implementing <see cref="IGitModuleControl"/>
        ///  or for controls placed on a <see cref="IGitModuleForm"/>. Neither is the case for settings pages.
        /// </summary>
```

Alternatively, we could split `GitExtensionsControl` because it deals with two different things:
* translation
* hotkeys

ServiceProvider is only used for hotkeys (currently).
Settings pages do not use hotkeys. They just need translation.

The extraction of `TranslatedControl` seems to be no big deal. So, I am doing it in this PR.

File: ResourceManager/TranslatedControl.cs [hunk 5]
```diff
@@ -0,0 +1,72 @@
+using System.ComponentModel;
+using GitExtUtils.GitUI.Theming;
+
+namespace ResourceManager
```
Comment (RussKie) [inline ResourceManager/TranslatedControl.cs:4]:
```suggestion
namespace ResourceManager;
```

**Review by RussKie — APPROVED** [review]
👍
