### PR TITLE
Branch filter dropdown shown too often

### LINKED ISSUE #9872: Branches filter keyboard input reversed
### Environment

- Git Extensions 33.33.33
- Build 38e700fae4259e71ba2a2f8e8d03ed719abe4392
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.12
- DPI 96dpi (no scaling)

### Issue description

Text typed into the Branch filter ComboBox gets reversed.

### Steps to reproduce

Try to enter "debug":

BranchesFilter

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### LINKED ISSUE #10143: Opens Branch listbox by unrelated actions
### Environment

- GitExtensions version: 4.0 (31f3c27)
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

Opens "Branch filter" listbox by unrelated actions

### Steps to reproduce

- Click inside of the Grid
- Click "Change working directory" listbox
- Both of "Change working directory" and "Branch filter" listboxes are opened

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #10143 
Fixes #9872
(Partial) Regression in #10136 

## Proposed changes

Show dropdown when clicking rather than at focus

also in 4.0

## Test methodology 

manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
I tried to improve the selection handling too, but basically just did some cleanup
The change in PreventToolStripSplitButtonClosing() seem to be a leftover from the refactoring, but it does not seem to be necessary

File: GitUI/UserControls/FilterToolBar.cs [hunk 1]
```diff
@@ -305,6 +282,31 @@ private void UpdateBranchFilterItems()
                 await this.SwitchToMainThreadAsync();
                 BindBranches(branches);
             }).FileAndForget();
+
+            return;
+
+            void BindBranches(string[] branches)
```
Comment (PavelA85) [inline GitUI/UserControls/FilterToolBar.cs:288]:
```suggestion
            private void BindBranches(string[] branches)
```

File: GitUI/UserControls/FilterToolBar.cs [hunk 2]
```diff
@@ -305,6 +282,31 @@ private void UpdateBranchFilterItems()
...
+            {
+                var autoCompleteList = tscboBranchFilter.AutoCompleteCustomSource.Cast<string>();
+                if (!autoCompleteList.SequenceEqual(branches))
+                {
+                    tscboBranchFilter.AutoCompleteCustomSource.Clear();
+                    tscboBranchFilter.AutoCompleteCustomSource.AddRange(branches);
+                }
+
+                string filter = tscboBranchFilter.Items.Count > 0 ? tscboBranchFilter.Text : string.Empty;
```
Comment (PavelA85) [inline GitUI/UserControls/FilterToolBar.cs:297]:
```suggestion
                var filter = tscboBranchFilter.Items.Any() ? tscboBranchFilter.Text : string.Empty;
```

File: GitUI/UserControls/FilterToolBar.cs [hunk 3]
```diff
@@ -305,6 +282,31 @@ private void UpdateBranchFilterItems()
...
+                string[] matches = branches.Where(branch => branch.IndexOf(filter, StringComparison.InvariantCultureIgnoreCase) >= 0).ToArray();
+
+                if (matches.Length == 0)
```
Comment (PavelA85) [inline GitUI/UserControls/FilterToolBar.cs:300]:
```suggestion
                if (!matches.Any())
```

File: GitUI/UserControls/FilterToolBar.cs (hunk 1 above)
Comment (gerhardol) [reply GitUI/UserControls/FilterToolBar.cs:288]: This is a local method always private to the enclosing method

File: GitUI/UserControls/FilterToolBar.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/UserControls/FilterToolBar.cs:297]: The coding guidelines (that are not written down...) recommends explicit types.

File: GitUI/UserControls/FilterToolBar.cs (hunk 3 above)
Comment (gerhardol) [reply GitUI/UserControls/FilterToolBar.cs:300]: Linq is not optimized a well as native code (even if I really hope it makes no difference here) so it is avoided, also suggested by vs. for me length is easier to read.

Comment (RussKie) [reply GitUI/UserControls/FilterToolBar.cs:300]: In .NET Framework linq sufered from perf issues, in .NET some (most?) perf issues got addressed. I personally prefer to avoid linq where possible.

**Review by RussKie — APPROVED** [review]
LGTM
