### PR TITLE
Store view settings on request only

### LINKED ISSUE #10009: Toolbar button `Show Ref Log` does not work on first click
### Environment

- Git Extensions 33.33.33
- Build 56f797126690cd72178c80ee41ec90437147f6e2
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.5
- DPI 96dpi (no scaling)

### Issue description

The button state seems to be correctly initialized.
Though when clicked, it does not really hide the Ref Log on first click.

### Steps to reproduce

- activate `Show Ref Log`
- restart GE
- try to hide the Ref Log by clicking the toolbar button

### Did this work in previous version of GitExtensions?

most likely in 3.5.4

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10009

## Proposed changes

- Store the most important view settings on request only
  (RefLog, CurrentBranchOnly, BranchFilterEnabled, RevisionSortOrder, FileViewer toolbar flags)

## Screenshots 

Before|After
-|-
image|image

## Test methodology 

- manual
- new tests for `RuntimeSetting<T>`

## Please do not squash merge

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
I'm not really fond of this approach, it kind of looks over complicated. 

> * Store the most important view settings on request only
>   (RefLog, FileViewer toolbar flags)

Are we not persisting the FileViewer toolbar flags already?
I was under impression that the reflog is the only settings we're persisting that, perhaps, we shouldn't be persisting - i.e., a setting that's a repo-specific and not a global setting.
Perhaps, a simpler - both from an implementation and user experience - solution could be to add a new tab, say, "Repository specific settings" and place related settings on it. The organisation of this tag could be done in the similar fashion to the "Confirmation" tag - i.e., select only those settings that are to be persisted globally - that is, if a settings isn't ticked it's state will affect only the current app instance and only the current repo until it is switched.

OT: the settings structure is a mess, and I think we should look at them holistically and rework the hierarchy.


> * Add an example of an experimental view setting
>   option to fan out all children lanes directly at parent


When I suggested experimental features I was thinking of adding a new tab under the Advanced tab:
image

**Comment by mstv** [comment]
> Are we not persisting the FileViewer toolbar flags already?

We do, but in an arguable way. I have just turned these settings into View Settings.
`AppSettings.ShowReflogReferences` is only a facade to `_showReflogReferences.Value` in order to not need to adapt all usages. Should I remove this facade?

You have agreed to my definition of View Settings: https://github.com/gitextensions/gitextensions/issues/10009#issuecomment-1272614922
"I prefer a set of default view settings for the DiffViewer and for the RevisionGrid. (Temporary) changes should not be stored. Rather store them on explicit request."

> I was under impression that the reflog is the only settings we're persisting that, perhaps, we shouldn't be persisting - i.e., a setting that's a repo-specific and not a global setting.

Why should one have repo-specific preferences of View Settings? Supporting different setting levels - this would make it complex.
The point is, that I can change a View Setting in one instance not affecting the view in other instances (even if they show the same repo). 

> Perhaps, a simpler - both from an implementation and user experience - solution could be to add a new tab, say, "Repository specific settings" and place related settings on it. The organisation of this tag could be done in the similar fashion to the "Confirmation" tag - i.e., select only those settings that are to be persisted globally - that is, if a settings isn't ticked it's state will affect only the current app instance and only the current repo until it is switched.

Simply incomplete. We should not patronize users with a fixed set of view settings. They need to be able to define their own defaults.

Please elaborate what can be _simplified_ in the UX of my implementation.

Regarding implementation: If you know how to make C# generics distinguish `T` from `T?`, please let me know! I had a hard time trying to make it work for both `bool` and `enum`.

The settings dialog is not really usable for View Settings. It is too slow. I guess that is why we have a `View` menu. I do not deny to create a settings page, particularly for less frequently changed options.

> When I suggested experimental features I was thinking of adding a new tab under the Advanced tab:

I know but: ditto

> OT: the settings structure is a mess, and I think we should look at them holistically and rework the hierarchy.

`AppSettings` is flat. Hierarchy is created by the settings dialog only.

**Comment by mstv** [comment]
copy of a comment in a - previously depended - PR in order to continue the discussion here (*later*):

> I feel this is taking is further away from the [Options pattern](https://learn.microsoft.com/dotnet/core/extensions/options). I vaguely remember ivangrek did (or was working towards) a POC that converted our settings to IOptons<T>...

The only "challenge" I see is that IOption<TOptions> expects TOptions being a class. Our options are of type bool, int, Enum (and string).
IViewSetting is just an additional interface with the specifics of a View Setting.

image

**Comment by mstv** [comment]
If you mean `ISetting<T>`, `ViewSetting<T?>` would not be very different. But basically, I want to use nullable types only if necessary. Though since `ISettings<T>` is used in order to support different settings sources, the generic use of nullable types seems to be an acceptable tradeoff.

image

I am going to let `ViewSetting<T>` implement both interfaces `ISetting<T>` and `IViewSetting`.

**Comment by mstv** [comment]
This bugfix should be merged before the next release.

File: GitCommands/Settings/IRuntimeSetting.cs [hunk 1]
```diff
@@ -0,0 +1,21 @@
+﻿namespace GitCommands.Settings
+{
+    public interface IRuntimeSetting
```
Comment (RussKie) [inline GitCommands/Settings/IRuntimeSetting.cs:3]: Could you please annotate the type itself?

File: GitUI/CommandsDialogs/FormRebase.cs [hunk 2]
```diff
@@ -379,9 +379,9 @@ private void chkUseFromOnto_CheckedChanged(object sender, EventArgs e)
 
         private void btnChooseFromRevision_Click(object sender, EventArgs e)
         {
-            bool previousValueBranchFilterEnabled = AppSettings.BranchFilterEnabled;
-            bool previousValueShowCurrentBranchOnly = AppSettings.ShowCurrentBranchOnly;
-            bool previousValueShowReflogReferences = AppSettings.ShowReflogReferences;
+            bool previousValueBranchFilterEnabled = AppSettings.BranchFilterEnabled.Value;
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormRebase.cs:382]: We need to provide the implicit conversion to/from bool to avoid changes like this one, and will make the changeset much smaller and cleaner.

File: GitCommands/Settings/RuntimeSetting.cs [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+        private readonly ISetting<T> _persistentSetting;
+
+        private bool _loaded;
+        private T _value;
+
+        /// <inheritdoc />
+        public event EventHandler? Updated;
+
+        /// <inheritdoc />
+        public T Default { get => _persistentSetting.Default; }
```
Comment (RussKie) [inline GitCommands/Settings/RuntimeSetting.cs:14]:
```suggestion
        public T Default => _persistentSetting.Default;
```

ditto below

File: GitCommands/Settings/RuntimeSetting.cs [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+    {
+        private readonly ISetting<T> _persistentSetting;
+
+        private bool _loaded;
+        private T _value;
+
+        /// <inheritdoc />
+        public event EventHandler? Updated;
+
+        /// <inheritdoc />
```
Comment (RussKie) [inline GitCommands/Settings/RuntimeSetting.cs:13]: This is unnecessary

File: GitCommands/Settings/RuntimeSetting.cs [hunk 5]
```diff
@@ -0,0 +1,87 @@
+﻿namespace GitCommands.Settings
+{
+    public class RuntimeSetting<T> : ISetting<T>, IRuntimeSetting
```
Comment (RussKie) [inline GitCommands/Settings/RuntimeSetting.cs:3]: Could you please annotate the type as well?

File: GitCommands/Settings/BoolRuntimeSetting.cs [hunk 6]
```diff
@@ -0,0 +1,15 @@
+﻿namespace GitCommands.Settings
+{
+    public sealed class BoolRuntimeSetting : RuntimeSetting<bool>
+    {
+        public BoolRuntimeSetting(SettingsPath settingsSource, string name, bool defaultValue)
+        : base(Setting.Create(settingsSource, name, defaultValue))
```
Comment (RussKie) [inline GitCommands/Settings/BoolRuntimeSetting.cs:6]: [nit] mis-indented
ditto below

File: GitCommands/Settings/BoolRuntimeSetting.cs [hunk 7]
```diff
@@ -0,0 +1,15 @@
+﻿namespace GitCommands.Settings
+{
+    public sealed class BoolRuntimeSetting : RuntimeSetting<bool>
```
Comment (RussKie) [inline GitCommands/Settings/BoolRuntimeSetting.cs:3]: Could you please annotate all new public types and API?

File: GitUI/CommandsDialogs/FormRebase.cs (hunk 2 above)
Comment (mstv) [reply GitUI/CommandsDialogs/FormRebase.cs:382]: Done for "to `T`".
I would say it is impossible for "from `T`" because `operator =` cannot be overloaded (in contrast to C++) and I cannot create full-blown `RuntimeSettings<T>` from a bool or enum value.

File: GitCommands/Settings/IRuntimeSetting.cs [hunk 8]
```diff
@@ -0,0 +1,24 @@
...
+    {
+        /// <summary>
+        /// Reloads the value from the settings file.
+        /// </summary>
+        void Reload();
+
+        /// <summary>
+        /// Resets the value to the hard-coded default value.
+        /// </summary>
+        void ResetToDefault();
```
Comment (RussKie) [inline GitCommands/Settings/IRuntimeSetting.cs:16]:
```suggestion
        void Reset();
```

File: GitCommands/Settings/IRuntimeSetting.cs [hunk 9]
```diff
@@ -0,0 +1,24 @@
...
+    /// </summary>
+    public interface IRuntimeSetting
+    {
+        /// <summary>
+        /// Reloads the value from the settings file.
+        /// </summary>
+        void Reload();
+
+        /// <summary>
+        /// Resets the value to the hard-coded default value.
```
Comment (RussKie) [inline GitCommands/Settings/IRuntimeSetting.cs:14]: hard-coded?

File: GitCommands/Settings/RuntimeSetting.cs [hunk 10]
```diff
@@ -0,0 +1,84 @@
...
+        public RuntimeSetting(ISetting<T> persistentSetting)
+        {
+            _persistentSetting = persistentSetting;
+        }
+
+        /// <summary>
+        /// Optionally calls <cref>Reload</cref> and returns the current value.
+        /// </summary>
+        public T GetValue(bool reload = false)
+        {
```
[the remark this answers is not in the document]
Comment (RussKie) [reply GitCommands/Settings/RuntimeSetting.cs:55]: After some thinking, I don't think we should provide this method here at all. I don't think the FileViewer settings should be changed to the "runtime". 
However, _IF_ you really think they _need to_, then this convenience method should be a part of the FileViewer implementation.

**Comment by mstv** [comment]
A RuntimeSetting has:
1. a hard-coded initial default value for the property in AppSettings.cs
2. a persisted value, which the user has stored as their preferred value (using the menu item "Save current view settings as default")
3. the current runtime value, which may be remembered or not depending on

image

In addition to
a. "Save current view settings as default",
the user might want to
b. "Reload stored view settings"
c. "Reset view settings to factory default"
Should I add them? Where?

These are the type-agnostic operations on a Runtime Setting -> `IRuntimeSetting`, used for the *generic* implementation of these menu items.
The meaning of the short but ambiguous names for the interface methods `Get`, `Set`, `Reset` would not be clear enough to me.
I have added another typed `IRuntimeSetting<T>` which combines `ISetting<T>` with `IRuntimeSetting`. So it has the property `Value` which provides the `Get` / `Set` operation.

(I think this comment resolves all open review comments.)

File: GitCommands/Settings/RuntimeSetting.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (mstv) [reply GitCommands/Settings/RuntimeSetting.cs]: `GetValue` is used for `get` of property `Value`, too.
I have declared it in the new typed interface `IRuntimeSetting<T>`, refer to https://github.com/gitextensions/gitextensions/pull/10851#issuecomment-1762871167.

**Review by gerhardol — APPROVED** [review]
I find it hard to understand what settings that are saved as "runtime" settings and why.
But implementation is fine to me.
I can accept it.

**Comment by mstv** [comment]
> I find it hard to understand what settings that are saved as "runtime" settings and why.

"Why?" might be answered by the issue #10009. All chosen settings are affected the same way.
In this PR, I have chosen the most important settings which are a nuisance if changed in other instances unintended and unexpected, particularly later on refresh.
We can adapt more view settings in a follow-up PR.
All settings are saved using the menu item.

**Review by RussKie — APPROVED** [review]
