### PR TITLE
Browse Diff tab menu alternatives and presentation

### LINKED ISSUE #4387: Browse Diff Reset: Multiple parents are not handled
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Browse Menu reset has incorrect handling for multiple parents (merge commits, as multi selection of more than 2 is ignored). The first parent is always used.

The label in the drop down menu is always describing the first parent too.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
 * Select merge commit
 * Select a file in the second group
 * The reset drop down menu contains correct "B" revision but the first "A" revision

**What is the expected behavior?**
The selected parent is used, not the first parent

**Environment you encounter the issue:**
- GitExtensions version: all

**Did this work in previous version of GitExtensions (which)?**
no

image

### LINKED ISSUE #4396: MenuItems for untracked should be limited for difftool
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Difftool option should not be enabled for untracked

Issue #4031 had several issues that improved the functionality and limited unusable menus, but some checks were not entirely correct or could be simplified to just limit on IsTracked
Some diff-to-parent were not always shown

FileHistory and Blame should be disabled for Untracked
Browse Diff disabled for all artificial revisions but formDiff did not not disable

Browse Diff Cherry-pick completely disabled for artificial

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Visible for file menus in the mentioned menus.

**Environment you encounter the issue:**
- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
no

### LINKED ISSUE #4564: BrowseDiff should show differences to all selected revisions
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The diff tab shows differences to the selected (last clicked) revision from parent (if one selected) or first select (if two). With more than two selected the message was set to "Operation not supported".
For merge commits, all parents are shown though.

**What is the expected behavior?**
Show the differences for all selected versions also for multiple selected versions.
#4562 builds the support for this, a few issues like #4387 and #4396 remains.

Requires #4562 and #4563

Will submit several PRs from this:
- [x] #4565 Browse Diff: Incorrect comparision for multiple parents 
- #4566 Allow compare to several revisions (part of #4569, for review only)
- [x] #4567 minor cleanups
- [x] #4568 Submodule multi selection
- [ ] #4569  A combined PR with #4387 #4396 visual update and tests

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #4564
Fixes #4387
Fixes #4396

Note: Due to the structure of tests in a separate class, it is very difficult to split this issue in several commits. First commit was PR #4566, partly reviewed. (Depended on merged commits #4562 #4563 #4565 #4567 #4568)

Tests:
Rewrote RevisionDiffController to make it possible to have some kind of tests. The tests are retrofitted to the current functionality as they are just testing the menu items and not the actions themselves. (The tests adds may more maintenance than they give benefits but the formal test coverage increases.)

Browse Diff:
Submodules actions available for multi select (#4568)
Presents the Reset options for the correct parent in multi select situations
No longer differ between parent-child and first-second for Reset
Difftool: Describes A and B revisions in the menu
Difftool arguments depends on parent availability
Better detection of parents to A/B for diffs

Commit:
Limit DiffTool and FileHistory to tracked

FormDiff:
Limit FileHistory to Tracked
Use RevisionDiffController to align to Browse-Diff for difftool
 
Screenshots before and after (if PR changes UI):
-
image
image
image

image
image
image

What did I do to test the code and ensure quality:
 - Added tests
 - Manual testing

Has been tested on (remove any that don't apply):
 - Windows 10

### CODE REVIEW

**Comment by gerhardol** [comment]
The first two commits are being reviewed in #4565, the third was mostly reviewed in #4566 (but cannot be merged in isolation). The review is primarily for the last commit - can be done after #4565 is merged.

File: GitUI/CommandsDialogs/FormDiff.cs [hunk 1]
```diff
@@ -240,14 +249,47 @@ private void btnAnotherHeadCommit_Click(object sender, EventArgs e)
...
+
+            openWithDifftoolToolStripMenuItem.Enabled = isAnyTracked;
+            fileHistoryDiffToolstripMenuItem.Enabled = isAnyTracked && isExactlyOneItemSelected;
+            blameToolStripMenuItem.Enabled = fileHistoryDiffToolstripMenuItem.Enabled && !DiffFiles.SelectedItem.IsSubmodule;
+        }
+
+        private ContextMenuDiffToolInfo GetContextMenuDiffToolInfo()
+        {
+            bool firstIsParent = _revisionDiffController.IsFirstParent(DiffFiles.Revision.ParentGuids, DiffFiles.SelectedItemParents.Select(i => i.Guid));
+            bool localExists = _revisionDiffController.LocalExists(DiffFiles.SelectedItemsWithParent, _fullPathResolver);
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormDiff.cs]: this indicates an incorrect use of `IFullPathResolver` - behaviors must be injected via constructors and not passed as parameters

Comment (gerhardol) [reply GitUI/CommandsDialogs/FormDiff.cs]: I see two two solutions for the relative simple LocalExists() function:
 * Add LocalExists() to IFullPathResolver instead
 *  Duplicate LocalExists() where it is used (two or three modules). A separate interface/class for this seem to be overkill.

Comment (RussKie) [reply GitUI/CommandsDialogs/FormDiff.cs]: > Add LocalExists() to IFullPathResolver instead

:+1:

Comment (gerhardol) [reply GitUI/CommandsDialogs/FormDiff.cs]: I duplicated LocalExists() as it deals with GitItemStatusWithParent.
Probably better to move other similar to a separate class (but FullPathResolver.Resolve() will be duplicated instead).

**Comment by RussKie** [comment]
I've pulled your branch down, I'll send a tweak shortly

**Comment by RussKie** [comment]
Sorry, my laptop died on a way to work so I will sent a tweak later tonight

**Comment by RussKie** [comment]
I've have taken liberty and shuffled things around.

Referencing `RevisionDiffController` in places other than `RevisionDiff` is incorrect (I must have missed it when it happened). 

I've extracted the common functionality:
* what I understood was related to testing/checking of `GitRevision` - I moved into `GitRevisionTester`. I'm not 100% settled, but it feels more appropriate than having that logic in `RevisionDiffController` and then referenced it somewhere else.
* shared context menu logic I moved out to `RevisionDiffContextMenuController`. I couldn't come up with a better name, so feel free to suggest alternatives.

Thought? Opinions?

**Comment by gerhardol** [comment]
I am OK with the changes. Will suggest a few name changes, will readd description etc
Testcases are still quite meaningless, but it looks good with increased coverage.

LocalRevisionExists -> AnyLocalFileExists()

IsFirstParent()
It makes more sense to have FileStatusList as an argument here, that is what is being checked.
But then GitRevisionTester is no longer a fit for the method.

> Referencing RevisionDiffController in places other than RevisionDiff is incorrect (I must have missed it when it happened).

That was done here

> shared context menu logic I moved out to RevisionDiffContextMenuController.

FileStatusListController or FileStatusListContextMenuController would be more logical. 
Remaining parts of RevisionDiffController fits there too even if currently only used in RevisionDiff.cs.

**Comment by RussKie** [comment]
> Testcases are still quite meaningless

Disagree. We see a lot of changes coming at a high rate (no one is working here full time). 
Tests help to 
* document design decisions - a good test name spells out requirements (e.g. `MyMethod_should_do_something_in_case_of_bla`), and 
* guard against possible regressions.

Speaking of which, to me the logic in both new methods looked very odd. 


> > shared context menu logic I moved out to RevisionDiffContextMenuController.
> 
> FileStatusListController or FileStatusListContextMenuController would be more logical.

No probs, let's rename. I like `FileStatusListContextMenuController` sightly more.

> Remaining parts of RevisionDiffController fits there too even if currently only used in RevisionDiff.cs.

The reason I created the controller (and other <UI control>Controllers) is to abstract business logic from the UI layer. I have a dream that one day we may be able to use another UI framework, so the UI should do as little as possible.
So I need to think more about this proposal, but generally unless/until it is used in multiple I see no reason to share it.

**Comment by gerhardol** [comment]
Renamed and updated. Did not move more around.
Will need to test a little more myself.

> Disagree. 

We have had this discussion before and try my best to comply to your vision. But in this situation the tests just takes time and decrease my motivation. These tests are just at the "looks" not at the actual contents. The functionality has to broken down considerably different to meaningful, but that is again a lot more effort. I will try to keep quiet.

**Comment by gerhardol** [comment]
@RussKie 
I do not plan to make more changes to this (considering some enhancements, but that is for later)

File: GitCommands/Git/GitRevisionTester.cs [hunk 2]
```diff
@@ -1,15 +1,106 @@
...
+            foreach (var item in firstSelected.Select(r => r.Guid))
+            {
+                if (!selectedRevision.ParentGuids.Contains(item, StringComparer.Ordinal))
+                {
+                    return false;
+                }
+            }
+
+            return true;
+        }
```
Comment (RussKie) [inline GitCommands/Git/GitRevisionTester.cs]: We need to rename the method to `AnyFirstAreParentsToSelected` to match the implementation and the doc "_True if **one of** the first selected is parent_".

Comment (RussKie) [reply GitCommands/Git/GitRevisionTester.cs]: :bulb:  Thinking of it, may be we can change the signature to something like the following? 

```
+        /// <summary>
+        /// Indicates whether any of the provided <param ref="selectedRevision" />'s parents are selected.
+        /// </summary>
+        public bool AnyRevisionParentsSelected(GitRevision selectedRevision, IEnumerable<GitRevision> revisionsSelectedFirst)
```

I think API becomes slightly more readable:

```
bool firstIsParent = _revisionDiffController.AnyRevisionParentsSelected(DiffFiles.Revision, DiffFiles.SelectedItemParents);
 ````



A rough idea, open to discussion...

File: GitCommands/Git/GitRevisionTester.cs [hunk 3]
```diff
@@ -1,15 +1,106 @@
...
+            var items = selectedItemsWithParent as List<GitItemStatus> ?? selectedItemsWithParent.ToList();
+            bool localExists = items.Any(item => !item.IsTracked);
+            if (localExists)
+            {
+                return true;
+            }
+
+            foreach (var item in items)
+            {
+                string filePath = _fullPathResolver?.Resolve(item.Name);
```
Comment (RussKie) [inline GitCommands/Git/GitRevisionTester.cs]: `_fullPathResolver` can't be `null`

File: GitUI/CommandsDialogs/FormDiff.cs [hunk 4]
```diff
@@ -65,6 +71,12 @@ public partial class FormDiff : GitModuleForm
             DiffText.ExtraDiffArgumentsChanged += DiffTextOnExtraDiffArgumentsChanged;
         }
 
+        protected override void OnRuntimeLoad(EventArgs e)
+        {
+            _revisionDiffContextMenuController = new FileStatusListContextMenuController();
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormDiff.cs]: :question:  Can this be moved into constructor? If so, this method an go....

File: GitUI/CommandsDialogs/RevisionDiff.cs [hunk 5]
```diff
@@ -164,21 +155,56 @@ protected override void OnRuntimeLoad(EventArgs e)
 
         private string DescribeRevision(string sha1)
         {
+            return DescribeRevision(sha1, 0);
+        }
+
+        private string DescribeRevision(string sha1, int maxLength)
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionDiff.cs]: we can combine these two methods into one - `private string DescribeRevision(string sha1, int maxLength = 0)`

File: GitUI/CommandsDialogs/RevisionDiff.cs [hunk 6]
```diff
@@ -164,21 +155,56 @@ protected override void OnRuntimeLoad(EventArgs e)
...
+
+        /// <summary>
+        /// Provide a description for the first selected or parent to the "primary" selected last
+        /// </summary>
+        /// <returns>A description of the selected parent</returns>
+        private string DescribeSelectedParentRevision(bool showUnstagedAndCombined)
+        {
+            var parents = DiffFiles.SelectedItemParents
+                .Where(i => showUnstagedAndCombined ||
+                    !(i.Guid.IsNullOrWhiteSpace() || i.Guid == GitRevision.UnstagedGuid || i.Guid == DiffFiles.CombinedDiff.Text))
```
Comment (RussKie) [inline GitUI/CommandsDialogs/RevisionDiff.cs]: what does `i.Guid == DiffFiles.CombinedDiff.Text` mean?
`CombinedDiff.Text` is a localised string "Combined Diff", why are we comparing it to a commit's SHA1?

File: UnitTests/GitCommandsTests/Git/GitRevisionTesterTests.cs [hunk 7]
```diff
@@ -10,12 +11,63 @@ namespace GitCommandsTests.Git
...
+        [Test]
+        public void LocalExists_should_return_true_if_file_exists()
+        {
+            Assert.Inconclusive();
+        }
+
+        [Test]
+        public void LocalExists_should_return_false_if_none_of_locally_tracked_items_have_files()
+        {
+            Assert.Inconclusive();
```
Comment (RussKie) [inline UnitTests/GitCommandsTests/Git/GitRevisionTesterTests.cs]: you've done a great job with tests :+1: 

these tests need finishing too :wink:

File: GitUI/CommandsDialogs/RevisionDiff.cs (hunk 6 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiff.cs]: DiffFiles.CombinedDiff.Text is used both for display and as an ID for a variant of an "artificial commit".

File: GitUI/CommandsDialogs/FormDiff.cs (hunk 4 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormDiff.cs]: Yes, I just followed the pattern you had use in other modules.

File: GitCommands/Git/GitRevisionTester.cs (hunk 2 above)
Comment (gerhardol) [reply GitCommands/Git/GitRevisionTester.cs]: The method checks if "True if all of the first selected are parents" so this would be changed behavior

File: GitUI/CommandsDialogs/FormDiff.cs (hunk 4 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/FormDiff.cs]: I would have used `OnRuntimeLoad` instead of instantiating objects in constructor where would be a dependency on fully set `GitModule`, which isn't available until the control is loaded.
In this case there is no dependency on `GitModule` and I'm pretty sure it is safe to move the instantiation in to the constructor.

File: GitCommands/Git/GitRevisionTester.cs (hunk 2 above)
Comment (RussKie) [reply GitCommands/Git/GitRevisionTester.cs]: My bad, misread the logic.

File: GitUI/CommandsDialogs/RevisionDiff.cs (hunk 6 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/RevisionDiff.cs]: Something doesn't feel right about it.... can't articulate what exactly, but it feels bad

Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiff.cs]: It is not nice, but I preferred to not spread the knowledge about the revision. The proper way would be to add it in GitRevision.cs like:
        public const string IndexGuid = "1111111111111111111111111111111111111111";

File: GitUI/CommandsDialogs/FormDiff.cs (hunk 4 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/FormDiff.cs]: Will move

File: GitCommands/Git/GitRevisionTester.cs (hunk 3 above)
Comment (gerhardol) [reply GitCommands/Git/GitRevisionTester.cs]: fixing

File: GitCommands/Git/GitRevisionTester.cs (hunk 2 above)
Comment (gerhardol) [reply GitCommands/Git/GitRevisionTester.cs]: I will be happy to take a discussion why I have done like I have done and to change it to something better. How should this work? Your comment is a good indication of that. I could give some more background tomorrow. The alternative is to take this in follow-up discussions.

File: GitUI/CommandsDialogs/RevisionDiff.cs (hunk 5 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiff.cs]: changing

File: UnitTests/GitCommandsTests/Git/GitRevisionTesterTests.cs (hunk 7 above)
Comment (gerhardol) [reply UnitTests/GitCommandsTests/Git/GitRevisionTesterTests.cs]: Will finish later, some done

File: GitUI/CommandsDialogs/RevisionDiff.cs (hunk 6 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/RevisionDiff.cs]: we already have it
https://github.com/gitextensions/gitextensions/blob/663036a7fe10d928596580e0c849107b8d00ddf3/GitCommands/Git/GitRevision.cs#L18

File: GitCommands/Git/GitRevisionTester.cs (hunk 2 above)
Comment (RussKie) [reply GitCommands/Git/GitRevisionTester.cs]: That's be good. I'm finding API somewhat confusing.

File: GitUI/CommandsDialogs/RevisionDiff.cs (hunk 6 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiff.cs]: In a similar way:
public const string CombinedDiffGuid = "2222...";
DiffFiles.CombinedDiff.Text will be used in some situations still.

File: GitCommands/Git/GitRevisionTester.cs (hunk 2 above)
Comment (gerhardol) [reply GitCommands/Git/GitRevisionTester.cs]: This PR (including the related PRs) primarily improves the diff and presentation of versions. In this process, the menu logic has been updated, some alternatives were not relevant and other were missing. The logic was also changed so testing could be done (testing is for the display, not for the actions so I do not find the tests useful still but they suck less than they would in my first iterations).

For the alternatives, some kind of rules were used:
 * With one item selected, the menu items must be relevant
 * With multiple items selected, menu items are relevant if at least one item is relevant. For instance if submodules are available if at least one submodule is selected. (There are exceptions to this rule)

In general, the behavior should be the same if the parent-child is selected as if just the "child". It was not like this previously, selecting a parent-child was more limiting. 
In some situations selecting the parent, then the selected will provide more information, like the actual parents to parents, that enables those menu items (in diff menu).
AllFirstAreParentsToSelected() is a helper for these situations, this is similar to just selecting one revision.

There are some special handling for merge commits, to show the combined diff like in e51741dcbf694d937db2c0fbeabf107827562fa7. This selects all parents and adds the artificial DiffFiles.CombinedDiff to compare to the Selected revision. The combined diff is shown if only one of the parents to e517 is shown but would be confusing if a non parent was selected. 
(So combined diff is shown if at least one parent shown, but no other revision than parents).

For staged/unstaged, the availability is available is based on the selected revision but the parent must be staged/Head to be sure a file can be staged/unstaged. This commands breaks the rule to "show if at least one is possible" as it is not possible to determine the availability in a good way for the command.

FirstIsParent is also used to confirm that a parent to parent exists for difftool exists and to prune when parent-to-selected(B) is is the same as first(A).

Pushing a few clarifications related to this.

Not sure if it got any clearer...

**Comment by gerhardol** [comment]
I have not planned to change anything more

File: GitUI/CommandsDialogs/RevisionDiff.cs (hunk 6 above)
Comment (gerhardol) [reply GitUI/CommandsDialogs/RevisionDiff.cs]: Added a CombinedDiffGuid for the artificial diff after all. For instance #4154 seem to enhance the comparison more, so it is better to set the pattern. Not sure if the TranslationApp handles this correctly.
