### PR TITLE
fix: Do not hide tabs for artificial commits

### LINKED ISSUE #4242: Diff tab selected when GE starts up
**Do you want to request a *feature* or report a *bug*?**
regression in master

**What is the current behavior?**
Whenever GE starts up, it consistently selects "Diff" tab instead of "Commit"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- set the head to origin/master
- build and launch in VS
- observe the Diff tab selected

image

**What is the expected behavior?**
- Commit tab is selected

**Environment you encounter the issue:**
Current master branch

**Did this work in previous version of GitExtensions (which)?**
Yes

@gerhardol could you have a look please

### PR DESCRIPTION
**Pull request by RussKie**
Dynamically added/hidden tabs added implementation complexity, reduced UX and caused regressions under Mono.
Tabs now remain visible for artificial commits and provide minimal information.
Closes #4242 
Obsoletes #4254 #4273 
 
Screenshots before and after (if PR changes UI):
image
image
image

Has been tested on (remove any that don't apply):
 - GIT 2.10 and above
 - Windows 10 and above

### CODE REVIEW

**Comment by gerhardol** [comment]
Discussions in the issue on how I would have preferred the change, PR comments here.

FormBrowse line 252, 253: Remove, not needed

FormFileHistory: Remove line 245-255 to have the same handling as in FormBrowse.
Update line 73 to remove artificial check (keep removal for submodules).

File: GitUI/UserControls/RevisionGrid.cs [hunk 1]
```diff
@@ -2761,18 +2762,33 @@ private void CheckUncommitedChanged(string filtredCurrentCheckout)
...
             }
 
-            //Add working directory as virtual commit
+            var userName = Module.GetEffectiveSetting(SettingKeyString.UserName);
+            var userEmail = Module.GetEffectiveSetting(SettingKeyString.UserEmail);
+
+            // Add working directory as virtual commit
             var workingDir = new GitRevision(Module, GitRevision.UnstagedGuid)
             {
+                Author = userName,
```
Comment (gerhardol) [inline GitUI/UserControls/RevisionGrid.cs]: Fake info should be avoided. More in issue comments.

File: GitUI/UserControls/RevisionGrid.cs [hunk 2]
```diff
@@ -2761,18 +2762,33 @@ private void CheckUncommitedChanged(string filtredCurrentCheckout)
...
+                AuthorDate = DateTime.MaxValue,
+                AuthorEmail = userEmail,
+                Committer = userName,
+                CommitDate = DateTime.MaxValue,
+                CommitterEmail = userEmail,
                 SubjectCount = unstageCount,
```
Comment (gerhardol) [inline GitUI/UserControls/RevisionGrid.cs]: SubjectCount is special, separate first or last in the block.

File: GitUI/UserControls/RevisionGrid.cs (hunk 1 above)
Comment (RussKie) [reply GitUI/UserControls/RevisionGrid.cs]: I disagree that it is a fake info - it is the name of the individual making changes. This information comes from the gitconfig. Same applies to the email.

File: GitUI/UserControls/RevisionGrid.cs (hunk 2 above)
Comment (RussKie) [reply GitUI/UserControls/RevisionGrid.cs]: I am afraid I don't understand what you mean.

Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid.cs]: Information for a commit is static, except BuildInfo and SubjectCount (that is merged to Subject). Separate SubjectCount from the static fields.

**Comment by RussKie** [comment]
Ah yes, will optimise
Thanks

File: GitUI/UserControls/RevisionGrid.cs (hunk 2 above)
Comment (RussKie) [reply GitUI/UserControls/RevisionGrid.cs]: Right now `GitRevision` depends on an instance of `GitModule` which isn't static. So the artificial revision instances need to be context aware...
`CheckUncommitedChanged` is called once whenever the graph is refreshed, so performance hit is probably minimal.

Comment (gerhardol) [reply GitUI/UserControls/RevisionGrid.cs]: Yes, I suggest leave it as is. Git revision impact should be low (that the content is not static supports my point, but we already have had this discussion). 

Separate CheckUncommitedChanged is removed (shared with commit button) in #4209
