### PR TITLE
More complete CanBeGitURL

### LINKED ISSUE #7839: New install first repo clone, get error
* New company laptop
* installed 64bit git bash (2.25.1) successfully
* Installed Git Extensions 3.3.1.7897 successfully
* Choose Clone Repository from application, or through right click menu in file explorer, get error.  
* When closing error dialog, clone repo dialog box does successfully show

## Expected behaviour
I expected to not get error box :)

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at GitUI.CommandsDialogs.FormClone.ToTextUpdate(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Text(String value)
   at System.Windows.Forms.TextBoxBase.set_Text(String value)
   at System.Windows.Forms.TextBox.set_Text(String value)
   at GitUI.CommandsDialogs.FormClone.FromTextUpdate(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormClone.OnRuntimeLoad(EventArgs e)
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4018.0
- DPI 144dpi (150% scaling)

### PR DESCRIPTION
**Pull request by mstv**
Fixes #7839

## Proposed changes

- check for a few more git protocols (all I found at the current https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols)
- check for existing git folders, too

## Test methodology 

- manual tests

## Test environment(s) 

- Git Extensions 3.3.0
- Build 9070a525b78e1f1fec9f6b839dafb948673dfd25
- Git 2.24.1.windows.2
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommandsDialogs/FormClone.cs [hunk 1]
```diff
@@ -183,16 +183,20 @@ protected override void OnRuntimeLoad(EventArgs e)
...
             string urlLowered = url.ToLowerInvariant();
 
-            return urlLowered.StartsWith("http") ||
-                urlLowered.StartsWith("git") ||
-                urlLowered.StartsWith("ssh");
+            return urlLowered.StartsWith("http:")
+                || urlLowered.StartsWith("https:")
+                || urlLowered.StartsWith("git:")
+                || urlLowered.StartsWith("ssh:")
+                || urlLowered.StartsWith("file:")
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormClone.cs]: FYI there is `PathUtil.IsUrl` method that covers half of these.

File: GitUI/CommandsDialogs/FormClone.cs [hunk 2]
```diff
@@ -81,7 +81,7 @@ protected override void OnRuntimeLoad(EventArgs e)
 
             _NO_TRANSLATE_To.Text = AppSettings.DefaultCloneDestinationPath;
 
-            if (CanBeGitURL(_url) || GitModule.IsValidGitWorkingDir(_url))
+            if (CanBeGitURL(_url))
```
Comment (RussKie) [inline GitUI/CommandsDialogs/FormClone.cs]: Whilst functionally it may be a correct change, semantically it isn't. `IsValidGitWorkingDir` has nothing to do with checking `URL`, so merging the checks alters the meaning of `CanBeGitURL`.

Comment (mstv) [reply GitUI/CommandsDialogs/FormClone.cs]: You are absolutely right from a generic point of view. But git & GE do name it "URL" also if it is just a plain OS path to a repo.

File: GitCommands/PathUtil.cs [hunk 3]
```diff
@@ -81,10 +81,12 @@ public static bool IsLocalFile([NotNull] string fileName)
...
-            return !string.IsNullOrEmpty(path) &&
-                   (path.StartsWith("http", StringComparison.CurrentCultureIgnoreCase) ||
-                    path.StartsWith("git", StringComparison.CurrentCultureIgnoreCase) ||
-                    path.StartsWith("ssh", StringComparison.CurrentCultureIgnoreCase));
+            return !string.IsNullOrEmpty(path)
+                && (path.StartsWith("http:", StringComparison.CurrentCultureIgnoreCase)
+                 || path.StartsWith("https:", StringComparison.CurrentCultureIgnoreCase)
+                 || path.StartsWith("git:", StringComparison.CurrentCultureIgnoreCase)
+                 || path.StartsWith("ssh:", StringComparison.CurrentCultureIgnoreCase)
+                 || path.StartsWith("file:", StringComparison.CurrentCultureIgnoreCase));
```
Comment (RussKie) [inline GitCommands/PathUtil.cs]: This _may_ affect `LocalRepositoryManager.AddAsMostRecentAsync` behaviour. Largely I would think this would be an edge case, but `file:////c/dev/repo` is technically a valid local path.

Comment (mstv) [reply GitCommands/PathUtil.cs]: > This _may_ affect `LocalRepositoryManager.AddAsMostRecentAsync` behaviour. Largely I would think this would be an edge case, but `file:////c/dev/repo` is technically a valid local path.

I think file URL is not supported by GE -- at least not by `FormOpenDirectory`.

If this really proves to be a problem, then `LocalRepositoryManager` should be adapted because it is not precise:
```patch
-            if (PathUtil.IsUrl(repositoryPath))
+            if (PathUtil.IsUrl(repositoryPath) && !PathUtil.IsFileUrl(repositoryPath))
            {
                // TODO: throw a specific exception
                throw new NotSupportedException();
            }
```
