### PR TITLE
fix(CommitInfo): Avoid NRE

### LINKED ISSUE #12385: [NBug] Value cannot be null. (Parameter 'revision')
### Environment

- Git Extensions 5.2.1.18061
- Build 0d74cfdc312df90114a0cf8d6c8a30ca4213e2ff
- Git 2.47.1.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.16
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.ArgumentNullException: Value cannot be null. (Parameter 'revision')
   at CommitData GitCommands.CommitDataManager.CreateFromRevision(GitRevision revision, IReadOnlyList<ObjectId> children) in C:/projects/gitextensions/src/app/GitCommands/CommitDataManager.cs:line 87
   at async void GitUI.CommitInfo.CommitInfo.ReloadCommitInfo()+UpdateCommitMessageAsync(?) in C:/projects/gitextensions/src/app/GitUI/CommitInfo/CommitInfo.cs:line 353
   at async void GitUI.CommitInfo.CommitInfo.ReloadCommitInfo()+(?) => { } in C:/projects/gitextensions/src/app/GitUI/CommitInfo/CommitInfo.cs:line 410
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/src/app/GitExtUtils/GitUI/TaskManager.cs:line 32
```

### Steps to reproduce

Just switching to a submodule back and forth, then "manage submodules"

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #12385

## Proposed changes

`CommitInfo`: Avoid NRE by cancellation before re-assigning `_revision`

## Screenshots 

N/A

## Test methodology 

- existing tests

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: src/app/GitUI/CommitInfo/CommitInfo.cs [hunk 1]
```diff
@@ -298,6 +300,11 @@ private async Task LoadSortedTagsAsync()
         }
 
         private void ReloadCommitInfo()
```
Comment (RussKie) [inline src/app/GitUI/CommitInfo/CommitInfo.cs:302]: Why do we need this method? Right now, it looks like there are two different ways to initiate info reload sequence, but there's an ambiguity.

Comment (mstv) [reply src/app/GitUI/CommitInfo/CommitInfo.cs:302]: > Why do we need this method? Right now, it looks like there are two different ways to initiate info reload sequence, but there's an ambiguity.

It is used by lots of click handlers which do nothing else but call this function.
The only other usage is where the next CancellationToken needs to be created before setting `_revision`.
(This not a public API.)

Comment (RussKie) [reply src/app/GitUI/CommitInfo/CommitInfo.cs:302]: Any reason not to do this:
```
        private void ReloadCommitInfo(CancellationToken cancellationToken = default)
        {
            if (cancellationToken == default)
            {
                _asyncLoadCancellation.Next();
            }

```

Comment (mstv) [reply src/app/GitUI/CommitInfo/CommitInfo.cs:302]: What shall be the benefit of the slightly less readable and less explicit variant with default argument and extra comparison?
`ReloadCommitInfo` will not be extended with additional arguments. And it is not a public API.
What is unclear with the adjacent overloads?
```
        private void ReloadCommitInfo()
        {
            ReloadCommitInfo(_asyncLoadCancellation.Next());
        }

        private void ReloadCommitInfo(CancellationToken cancellationToken)
        {
```
?
BTW: Your suggestion becomes even longer because the result *must* be assigned to `cancellationToken`.

Comment (RussKie) [reply src/app/GitUI/CommitInfo/CommitInfo.cs:302]: My main/only concern is possible confusion - which method to use.

**Review by RussKie — APPROVED** [review]

File: src/app/GitUI/CommitInfo/CommitInfo.cs (hunk 1 above)
Comment (mstv) [reply src/app/GitUI/CommitInfo/CommitInfo.cs:302]: > My main/only concern is possible confusion - which method to use.

I am going to consider this when extending an API.
