### PR TITLE
fix: Show current branch resets when switch repos

### LINKED ISSUE #9517: After update "View - Show current branch only" no longer filter out branches and reset to "View - Show all branches" every time I switch repository
## Current behavior

Today I updated to a newer version of GIT Extensions and it stopped filtering branches by using the "View - Show current branch only" option.
Also when I switch repositories from the toolbar it resets to "View - Show all branches".

## Steps to reproduce

1. Open Git extensions having 2 repositories and 2 branches in some of in
2. Open repository with 2 branches
3. Go to View and select "Show current branch only"
Expected: Only the current branch head is shown.
Actual: Multiple head branches are shown
4. In the toolbar select second repository
5. In the toolbar select the first repository again
Expected: "View - Show current branch only" option is selected
Actual: It got reset to "View - Show all branches"

## Screenshots

image

## Did this work in the previous version of GitExtensions

Yes, it was. I'm not sure, I wasn't updating it for a few months.

## Environment

- Git Extensions `3.5.3.12551`
- Build `00604a59a673142a3d34a22aa657466a922977f3`
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 120dpi (125% scaling)

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #9517
Relates to https://github.com/gitextensions/gitextensions/pull/9551

A regression introduced in #8489 that resets filters when repos are switched.
However it didn't account for the "Show current branch" setting.

### CODE REVIEW

File: GitUI/CommandsDialogs/FormBrowse.cs [hunk 1]
```diff
@@ -1991,8 +1991,14 @@ private void SetGitModule(object sender, GitModuleEventArgs e)
...
             _submoduleStatusProvider.Init();
-            ToolStripFilters.SetBranchFilter(string.Empty, refresh: false);
-            ToolStripFilters.SetRevisionFilter(string.Empty);
+
+            // If we're applying custom branch or revision filters - reset them
+            ToolStripFilters.ClearFilters();
+            if (AppSettings.BranchFilterEnabled && !AppSettings.ShowCurrentBranchOnly)
+            {
+                AppSettings.BranchFilterEnabled = false;
+            }
```
Comment (ivangrek) [inline GitUI/CommandsDialogs/FormBrowse.cs:2000]: `AppSettings.BranchFilterEnabled = AppSettings.BranchFilterEnabled && AppSettings.ShowCurrentBranchOnly;`

0 0 -> 0
0 1 -> 0
1 0 -> 0
1 1 -> 1

**Comment by RussKie** [comment]
@msftbot merge in 48 hours

**Comment by RussKie** [comment]
The bot is currently unavailable, so I'll merge it in the next few days, unless there objections.

**Review by gerhardol — COMMENTED** [review]
+1
Not really got into all details for the resetting of filters, seem to work. 
Noted a few issues, not changed by this PR:
* Branch filters are synced from the check box to Advanced filter, but not the other way around
* Current branch only in Advanced is not synced at all

Advanced filter is reset when switching repos

**Comment by RussKie** [comment]
> * Branch filters are synced from the check box to Advanced filter, but not the other way around
> * Current branch only in Advanced is not synced at all
> 
> Advanced filter is reset when switching repos

Thank you, I'll work through these.
