### PR TITLE
Fix 8351 - "Araxis does not show up in Mergetool/Difftool dropdown box"

### LINKED ISSUE #8351: Araxis does not show up in Mergetool/Difftool dropdown box
## Current behaviour

Araxis is not an option in Mergetool / Difftool. It used to be there six months ago but I can't recall the gitextension version number.

## Expected behaviour
Araxis shows up in the mergetool/difftool dropdown boxes.

## Steps to reproduce

Git Extensions->tools->settings->Git->config->MergeTool
Git Extensions->tools->settings->Git->config->DiffTool

## Screenshots

noaraxis

## Did this work in previous version of GitExtensions

Yes, i cannot recall the version #.

## Environment

- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

## Diagnostics

1. removal of gitextenision data in users/xx/appdata/local and users/xx/appdata/LocalRoaming
2. reinstallation of git extensions and araxis merge.

### PR DESCRIPTION
**Pull request by hoborm**
Fixes #8351
Added back the Araxis merge/diff tool as requested in #8351 

## Proposed changes

- Created a new class for Araxis.cs in the DiffMergeTools.cs

## Test methodology 

- Extended the existing unit tests
- Manual testing

## Test environment(s) 

- GIT 
2.28.0
- Windows 
Version	10.0.19041 Build 19041

It's my first PR for GitExtensions please let me know if I need to change anything.

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you!

File: GitCommands/DiffMergeTools/Araxis.cs [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+namespace GitCommands.DiffMergeTools
+{
+    internal class Araxis : DiffMergeTool
+    {
+        /// <inheritdoc />
+        public override string ExeFileName => "Compare.exe";
+
+        /// <inheritdoc />
+        public override string MergeCommand => "/merge /wait /a2 /3 \"$LOCAL\" \"$BASE\" \"$REMOTE\" \"$MERGED\"";
```
Comment (gerhardol) [inline GitCommands/DiffMergeTools/Araxis.cs:15]: @hoborm Git uses "$BASE" "$LOCAL" "$REMOTE" "$MERGED"
as default order, even if the support hints say otherwise.
https://www.araxis.com/merge/documentation-windows/integrating-with-other-applications.en#GitExtensions
(seem to be incosistent though)

GE should use the same order as command line, should this be changed?

Comment (hoborm) [reply GitCommands/DiffMergeTools/Araxis.cs:15]: I can definitely say that I have followed the araxis help page resolving this one, should I submit an other PR with the corrected order? Also I would suggest to contact them to correct their documentation as well since it is misleading in this case.
