### PR TITLE
`CommitInfo`: Fix up threading issues

### LINKED ISSUE #9204: Integration Tests: `ObjectDisposedException`
## Current behaviour

Exception thrown by integration test `RunCommandTests.RunCommandBasedOnArgument_blame_line`(?).

## Expected behaviour

tests pass

## Steps to reproduce

run tests in MSVS many times

## Environment

- Git Extensions 33.33.33
- Build e91787fa894037581d678b16fa015c92543e1daf
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 5.0.6
- DPI 96dpi (no scaling)

## Diagnostics

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'RichTextBox'.
   at void System.Windows.Forms.Control.CreateHandle()
   at void System.Windows.Forms.TextBoxBase.CreateHandle()
   at IntPtr System.Windows.Forms.Control.get_Handle()
   at void GitUI.Editor.RichTextBoxExtension.RichTextBoxXhtmlSupportExtension.SetXHTMLText(RichTextBox rtb, string xhtmlText) in D:/Build/gitextensions3_dev/GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs:line 1238
   at void GitUI.CommitInfo.CommitInfo.UpdateRevisionInfo() in D:/Build/gitextensions3_dev/GitUI/CommitInfo/CommitInfo.cs:line 564
   at async Task GitUI.CommitInfo.CommitInfo.LoadSortedTagsAsync() in D:/Build/gitextensions3_dev/GitUI/CommitInfo/CommitInfo.cs:line 260
   at async void GitUI.CommitInfo.CommitInfo.RefreshSortedTags()+(?) => { } in D:/Build/gitextensions3_dev/GitUI/CommitInfo/CommitInfo.cs:line 156
   at void GitUI.ThreadHelper+<>c__DisplayClass13_0+<<FileAndForget>b__0>d.MoveNext() in D:/Build/gitextensions3_dev/GitExtUtils/GitUI/ThreadHelper.cs:line 100
```

### PR DESCRIPTION
**Pull request by mstv**
Fixes #9204

## Proposed changes

- Switch to UI thread before calling `CommitInfo.UpdateRevisionInfo`
  That's why it should go into 3.5.1, too.
- Join async operations before disposing `CommitInfo`
- Speed up tests by `AppSettings.ShowAvailableDiffTools = false`

## Screenshots

N/A

## Test methodology 

- manual
- run unit & integration tests

## Test environment(s) 

- Git Extensions 0.0.0.0
- Build d25e6402326c9a1ddbbe8145b65b34e52843a9dc
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 5.0.6
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/CommitInfo/CommitInfo.cs [hunk 1]
```diff
@@ -144,6 +144,23 @@ public CommitInfo()
...
+        /// <summary>
+        /// Clean up any resources being used.
+        /// </summary>
+        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
+        protected override void Dispose(bool disposing)
+        {
+            if (disposing)
+            {
+                _asyncLoadCancellation.CancelCurrent();
+                ThreadHelper.JoinPendingOperations(); // those run with FileAndForget
```
Comment (gerhardol) [inline GitUI/CommitInfo/CommitInfo.cs:156]: Is this needed in other forms too?

File: UnitTests/CommonTestUtils/TestAppSettingsAttribute.cs [hunk 2]
```diff
@@ -13,6 +13,7 @@ public sealed class TestAppSettingsAttribute : Attribute, ITestAction
         public void BeforeTest(ITest test)
         {
             AppSettings.CheckForUpdates = false;
+            AppSettings.ShowAvailableDiffTools = false;
```
Comment (gerhardol) [inline UnitTests/CommonTestUtils/TestAppSettingsAttribute.cs:16]: Is this needed in other tests too or is TestAppSettingsAttribute used universally?

**Review by gerhardol — COMMENTED** [review]
+1

File: GitUI/CommitInfo/CommitInfo.cs (hunk 1 above)
Comment (mstv) [reply GitUI/CommitInfo/CommitInfo.cs:156]: > Is this needed in other forms too?

Yes, this is very likely: to be handled with #7792.

File: UnitTests/CommonTestUtils/TestAppSettingsAttribute.cs (hunk 2 above)
Comment (mstv) [reply UnitTests/CommonTestUtils/TestAppSettingsAttribute.cs:16]: The `TestAppSettingsAttribute` should affect all tests - is included by the `AssemblyInfo.cs` files.

**Review by RussKie — APPROVED** [review]

**Comment by mstv** [comment]
Cherry-picked to `release/3.5` and added to milestone 3.5.1.

File: GitUI/CommitInfo/CommitInfo.cs (hunk 1 above)
Comment (gerhardol) [inline GitUI/CommitInfo/CommitInfo.cs:156]: Can this be reworked somehow?
This awaits all FileAndForget(), not just those created by this form.

When trying to find a solution for #9440 and add cancellation token that are disposed in REvDiff, RevGrid Dispose(), they are not executed until this has finished. So the tokens are not cancelled.
