### PR TITLE
Quote git-log --pretty options

### LINKED ISSUE #1469: Command line window visible on some operations
In the Settings dialog, on the "Git extensions" tab, I have the "Show Git commandline dialog when executing process" UNchecked. However, a command line window opens when I do various operations such as pushing.

Also note "commandline" should be two words "command line".

### LINKED ISSUE #11469: [NBug] zsh:fg:2: no job control in this shell.zsh:fg:3: no job co...
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: True

### Issue description

Exit code: 1
Command: wsl
Arguments: -d Ubuntu-22.04 git -c log.showSignature=false log --pretty=%ci
%an
%s --max-count=1 main --
Working directory: \\wsl$\Ubuntu-22.04\mnt\wsl\shared\source\repos\naimei-webapp\

```
GitExtUtils.ExternalOperationException: zsh:fg:2: no job control in this shell.
zsh:fg:3: no job control in this shell.
 ---> System.Exception: zsh:fg:2: no job control in this shell.
zsh:fg:3: no job control in this shell.
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 129
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at IEnumerable<Branch> GitExtensions.Plugins.DeleteUnusedBranches.DeleteUnusedBranchesForm.GetObsoleteBranches(RefreshContext context, string curBranch)+MoveNext() in C:/projects/gitextensions/Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs:line 106
   at void System.Collections.Generic.List<T>.InsertRange(int index, IEnumerable<T> collection)
   at void System.Collections.Generic.List<T>.AddRange(IEnumerable<T> collection)
   at void GitUI.SortableBindingList<T>.AddRange(IEnumerable<T> items) in C:/projects/gitextensions/GitUI/SortableBindingList.cs:line 20
   at async Task GitExtensions.Plugins.DeleteUnusedBranches.DeleteUnusedBranchesForm.RefreshObsoleteBranchesAsync() in C:/projects/gitextensions/Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs:line 350
   at async void GitUI.TaskManager.InvokeAndForget(Control control, Func<Task> asyncAction, CancellationToken cancellationToken)+(?) => { } [1] in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 111
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

When executing "Delete obsolete branches", Git Extensions throws this error.

### Steps to reproduce

Use "Delete obsolete branches".

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #11469

## Proposed changes

'%' arguments gives problems in WSL with zsh

## Test methodology 

manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

File: Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs [hunk 1]
```diff
@@ -97,7 +97,7 @@ private IEnumerable<Branch> GetObsoleteBranches(RefreshContext context, string c
 
                 GitArgumentBuilder args = new("log")
                 {
-                    "--pretty=%ci\n%an\n%s",
+                    @"--pretty=""format:%ci\n%an\n%s""",
```
Comment (mstv) [inline Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs:100]: This results in
`"--pretty=\"format:%ci\\n%an\\n%s\""`
in contrast to
`         "--pretty=%ci\n%an\n%s"`
before.
That's why the table is not filled.
