### PR TITLE
Don't load avatars, if network is not available

### LINKED ISSUE #5828: Author's avatar settings are not working correctly in Version 3.00.00 RC2
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Under Settings -> GitExtensions -> Appearance -> Author images 
"No Image Service" is set to "None" and the checkbox "Show author's avatar in the commit info view" ticked off.
But the avatar images get fetched (in wireshark I see GET requests to gravatar.com)
Also the clear cache button seem not properly working.
From some users like Janusz I see his image in every settings combination

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Set the settings as described above and open a repo (for example the gitextensions repo).

**What is the expected behavior?**
If the checkbox "Show author's avatar ..." is not set and Image service is set to none I expect no avatar image (and no outgoing network requests) at all.
In V3 I also find the labeling of the UI problematic, gravatar is not named anymore and the drop down labeled "No Image Service" is kinda confusing.

**Environment you encounter the issue:**
- GitExtensions version: 3.00 RC2
- GIT version: 2.19.2.windows.1
- OS version: Win 10 Pro 64 
- .NET version: 4.7.3190

I use the portable version (GitExtensions.exe.config => IsPortable: True) with GitExtensions.settings in the app folder

**Did this work in previous version of GitExtensions (which)?**
2.51.05

### LINKED ISSUE #6223: Slow startup if never connected to internet
## Current behaviour
With a clean install, accepting all default options of GitExtensions-3.0.1.4933.msi but NO internet connection, after installation the program takes 30+ seconds to startup each time (i.e. double-click icon, 30+ seconds before first window appears) This is before opening any repositories, just starting the program.

If the machine is connected to the internet ONCE and it is started, program takes less than 3 seconds.  Disconnecting from internet again, program always starts up quickly (<3 seconds).

## Expected behaviour
Once installation is complete, program should not require internet connection to 'finish' some final configuration or installation.

## Steps to reproduce
Copy msi file to machine that has no internet connectivity.
Run installation accepting all default settings
After installation, starting always takes 30+ seconds to open.
Close program, connect to internet and then start program.

## Did this work in previous version of GitExtensions
Sorry, don't know, haven't used previous versions.

## Environment

- Git Extensions 3.0.1.4933
- Build a269358b22a5dc1ea36928bb87f9e535de76a058
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.14393.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #5828
Fixes #6223

## Proposed changes

- Check whether a client is connected to Internet before attempting to
fetch avatars.
- Add tooltip to clarify purpose of "No image" dropdown
image
- Add a setting to show author's avatar column
image

## Test methodology 

- manual
----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
(will review tonight, it may be correct as it is, I looked at this some time ago)

**Comment by gerhardol** [comment]
(No time for test tonight.)
Gravatar service None means that no backup service exists, not that there are no icons.
GE first tries GitHub for github addresses, this change should disable that too.

This setting should be clarified, there were some discussions in a previous issue.

**Comment by RussKie** [comment]
Actually you're absolutely correct. I had a mental eclipse last night.
Thank you

We need to use the switch that controls the display of the avatar column.
We also need an extra pivot point inside the code that checks a network
connectivity (this would also address start timing issue if not connected
to a network).

**Comment by RussKie** [comment]
Change of plan.
Avatars got fetched from the internet, if absent locally. And if a client isn't connected to internet, these calls time out, and that causes slowness.

I've tested the fix locally and observed a significant improvement in responsiveness.

**Comment by RussKie** [comment]
@gerhardol  could you please test the settings page at 100% scaling?

File: GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs [hunk 1]
```diff
@@ -104,6 +108,7 @@ protected override void PageToSettings()
             AppSettings.EnableAutoScale = chkEnableAutoScale.Checked;
             AppSettings.TruncatePathMethod = GetTruncatePathMethodString(truncatePathMethod.SelectedIndex);
             AppSettings.ShowCurrentBranchInVisualStudio = chkShowCurrentBranchInVisualStudio.Checked;
+            AppSettings.ShowAuthorAvatarColumn = ShowAuthorAvatarInCommitGraph.Checked;
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs]: Minor: Can we move this setting together with the existing setting? (easier to review)

File: GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs [hunk 2]
```diff
@@ -50,6 +53,7 @@ protected override void SettingsToPage()
             chkShowCurrentBranchInVisualStudio.Checked = AppSettings.ShowCurrentBranchInVisualStudio;
             _NO_TRANSLATE_DaysToCacheImages.Value = AppSettings.AvatarImageCacheDays;
             ShowAuthorAvatar.Checked = AppSettings.ShowAuthorAvatarInCommitInfo;
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs]: This setting should be renamed (not related to this PR)

File: GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs [hunk 3]
```diff
@@ -25,6 +26,8 @@ protected override void OnRuntimeLoad()
         {
             base.OnRuntimeLoad();
 
+            ToolTip.SetToolTip(NoImageService, _noImageServiceTooltip.Text);
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs]: It would be good if the link was clickable, but no obvious good way to do that

File: GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs [hunk 4]
```diff
@@ -12,6 +12,7 @@ public partial class AppearanceSettingsPage : SettingsPageWithHeader
     {
         private readonly TranslationString _noDictFile = new TranslationString("None");
         private readonly TranslationString _noDictFilesFound = new TranslationString("No dictionary files found in: {0}");
+        private readonly TranslationString _noImageServiceTooltip = new TranslationString("A default image, if an email address has no matching Gravatar image.\r\nSee http://en.gravatar.com/site/implement/images/ for more details.");
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs]: Not just gravatar, GitHub (may be) checked first

File: GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs [hunk 5]
```diff
@@ -50,6 +53,7 @@ protected override void SettingsToPage()
             chkShowCurrentBranchInVisualStudio.Checked = AppSettings.ShowCurrentBranchInVisualStudio;
             _NO_TRANSLATE_DaysToCacheImages.Value = AppSettings.AvatarImageCacheDays;
             ShowAuthorAvatar.Checked = AppSettings.ShowAuthorAvatarInCommitInfo;
+            ShowAuthorAvatarInCommitGraph.Checked = AppSettings.ShowAuthorAvatarColumn;
```
Comment (gerhardol) [inline GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs]: I would have preferred that this setting was needed here, but this PR is an improvement. 
A tooltip for the CommitInfo setting is an alternative

File: GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs (hunk 1 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs]: Sure, np

File: GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs (hunk 2 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs]: Sure, np

File: GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs (hunk 4 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs]: The default image comes from Gravatar though, if we can't get an image from GH or GR.

File: GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs (hunk 5 above)
Comment (RussKie) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs]: Apologies, I don't understand what you're saying

Comment (gerhardol) [reply GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs]: Related: This setting should have been called ShowAuthorAvatarInRevisionGraph

The columns in the revision graph is normally not set from settings. The existing (now renamed) ShowAuthorAvatarInCommitInfo should have been moved out of here. A "block all avatars" would have been cleaner.

I do not request changes though

**Comment by RussKie** [comment]
We can look at it as a separate piece of work

**Comment by robot1marvin** [comment]
Tried the zip file you emailed containing Git Exteions 3.1.0.5347 and it is much faster.

However, each time I open it I get a popup with an exception.  I couldn't send that directly, but I screen-shot the dialog along with the stack-trace window.
gitextportexception

**Comment by RussKie** [comment]
That's a different error.
Please see #6093

**Comment by Garreye** [comment]
I'm still having slow loading issue on PCs that have no internet access, but are still connected to a LAN. If I physically pull out the Ethernet connection to my PC then Git Extensions opens in about 2 seconds, but if Ethernet is plugged in it takes about 32 seconds. 

Looks like the check for InternetGetConnectedState method from wininet.dll returns true if there is a LAN connection present, even though there's no internet. From googling around a bit it looks like this method is not very reliable and this behavior is expected.

Is there a setting to turn off avatar loading completely? I have the avatar provider set to 'Author initials' which I though might do it, but didn't fix the issue.

**Comment by Garreye** [comment]
The slow loading issue I'm having is happening on installed version 3.4.3.  I've now checked out the release/3.4 branch and built release binaries from there and run these binaries on one of the PCs where I was seeing this issue it loads in 2 seconds. I overwrote the installed C;/Program Data (x86)/GitExtensions/GitExtensions.exe with the one I built and it works fine from there. The about window for this has the same build number as the installed version, but says versions 3.3 for some reason. 

I don't have VS configure to be able to build the setup, so I'm not able to try installing the build I did, but maybe something related to installing? I built with VS Community 2019 (16.6.4).

**Comment by gerhardol** [comment]
> I overwrote the installed C;/Program Data (x86)/GitExtensions/GitExtensions.exe with the one I built and it works fine from there. 

Just run from the build folder or run in the debugger, you only need to install for registering file extensions and the shell extensions, compare to the portable build

There are other reasons to access internet like update check, telemetry and build server integration.

**Comment by Garreye** [comment]
Ya I'm fine with running from the build I did. I just thought that it was weird that the build I did behaves differently even though it's built from the same code as far as I can tell (same build ID in about window).

Portable build takes the same 32 seconds to open as installed.
