### PR TITLE
SetDocumentationBaseUrl using ProductVersion

### LINKED ISSUE #11338: The User Manual of version 4.1 tries to open the "4.0" document, which does not exist
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.24
- DPI 120dpi (125% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Best regards

### Issue description

When I click on "User Manual", my GIT-Extensions tries to open the following document:
https://git-extensions-documentation.readthedocs.io/en/release-4.0/

This does not exist and it is also not in line with my "4.1" version.

### Steps to reproduce

Click on the "Help" menu, choose "User manual".

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11338
Supersedes #11339

## Proposed changes

- Pass `AppSettings.ProductVersion` to `AppSettings.SetDocumentationBaseUrl` 

## Screenshots 

N/A

## Test methodology 

- adapted tests

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

File: GitCommands/Settings/AppSettings.cs [hunk 1]
```diff
@@ -122,22 +122,22 @@ public static string DocumentationBaseUrl
...
 
             string? docVersion = "en/main/";
-
-            if (!string.IsNullOrWhiteSpace(currentGitBranch))
+            const string defaultDevelopmentVersion = "33.33";
+            if (!string.IsNullOrWhiteSpace(version) && !version.StartsWith(defaultDevelopmentVersion))
             {
-                // We expect current branch to be something line "release/X.Y"
-                Match match = Regex.Match(currentGitBranch, "release/\\d*\\.\\d*");
+                // We expect version to be something starting with "X.Y"
```
Comment (gerhardol) [inline GitCommands/Settings/AppSettings.cs:136]:
```suggestion
                // We expect version to be something starting with "X.Y" (ignore patch versions)
```

**Review by gerhardol — APPROVED** [review]
