### PR TITLE
Symbolic links to .git in WSL

### LINKED ISSUE #11303: Opening a repository created by Google's Repo tool in WSL v2 on Windows causes exception
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.24
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.IO.IOException: The name of the file cannot be resolved by the system. : '\\wsl$\Ubuntu\home\rduff\code\tools\tool_magnet_verify_artifact\.git'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadLines(String path)
   at System.IO.Abstractions.FileWrapper.ReadLines(String path)
   at GitCommands.Git.GitDirectoryResolver.Resolve(String repositoryPath) in C:\projects\gitextensions\GitCommands\Git\GitDirectoryResolver.cs:line 83
   at GitCommands.GitModule..ctor(String workingDir) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 71
   at GitUI.CommandsDialogs.BrowseDialog.FormOpenDirectory.OpenGitRepository(String path, ILocalRepositoryManager localRepositoryManager) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\FormOpenDirectory.cs:line 158
   at GitUI.CommandsDialogs.BrowseDialog.FormOpenDirectory.LoadClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\FormOpenDirectory.cs:line 88
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.PerformClick()
   at GitUI.CommandsDialogs.BrowseDialog.FormOpenDirectory.folderBrowserButton_Click(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\FormOpenDirectory.cs:line 112
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I got this exception when trying to access a WSL (v2) path. The browse button (when navigating to a repository to open) was able to take me to the correct location, but after selecting it, I got this exception. I've been able to open WSL paths before, however this repository was created using Google's repo tool, which creates a symlink of the .git directory to point to another location on disk. The link uses a relative path:  ../../.repo/projects/tools/tool_magnet_verify_artifact.git The combination of WSLv2 plus Google Repo likely caused this situation.

### Steps to reproduce

Create a WSL v2 installation, then clone a repo using Google's Repo tool within that installation. Try to open that repository using the `\\wsl$` path. It should cause this exception. The cause is likely that Google's Repo tool creates a symlink of the `.git` folder. You can likely skip the Google Repo step if you manually move the `.git` folder and create a symlink to the new location.

### Did this work in previous version of GitExtensions?

Not that I'm aware of.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #11303

## Proposed changes

Symbolic links in WSL cannot be accessed from Windows.
This adds some workarounds that makes it possible to open such repos,
that has been created for instance with Google's repo tool.

All access from Windows will fail, only access by WSL native like "wsl git" works.
At least the following do not work:
* Display of branch names for (mostly using .git/HEAD to get the name). wsl git can be used here.
* Git commands using Windows Git (like difftool from submenu with all tools) will fail. (Even listing of tools fail, for instance when closing settings).
* GE Settings cannot be read/write to local repo
* Commands using the local .git config will not work. This includes Commit, rebase etc

You can still view information and compare branches though
All issues will likely not be resolved, unless the filesystem in WSL is updated

I doubt linked git repos will be a common use for GE, so there should not be too many complaints.
WSL support in general is a hack.

## Test methodology 

Manual - basically impossible to test the actual problem

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — COMMENTED** [review]
👍

File: GitCommands/Git/GitDirectoryResolver.cs [hunk 1]
```diff
@@ -75,7 +75,25 @@ public string Resolve(string repositoryPath)
...
+                    // ReadLines() throws on directories that are links.
+                    if ((File.GetAttributes(gitPath) & FileAttributes.ReparsePoint) == 0)
+                    {
+                        // re-throw if it is not a link
+                        throw;
+                    }
+
+                    // This is possibly a WSL link, try as a directory
+                    line = null;
+                }
```
Comment (mstv) [inline GitCommands/Git/GitDirectoryResolver.cs:95]:
```suggestion
                catch (IOException) when ((File.GetAttributes(gitPath) & FileAttributes.ReparsePoint) != 0)
                {
                    // WSL links are not fully supported by the Windows or .NET.
                    // ReadLines() throws on directories that are links.
                    // This is possibly a WSL link, try as a directory.
                    line = null;
                }
```

**Review by mstv — COMMENTED** [review]
+2 have not run

File: GitCommands/Git/GitDirectoryResolver.cs (hunk 1 above)
Comment (gerhardol) [reply GitCommands/Git/GitDirectoryResolver.cs]: Adopted in the update.

**Comment by gerhardol** [comment]
Cleaned up the solution, documented the limitations somehow.

**Review by RussKie — APPROVED** [review]
