### PR TITLE
Diff for initial commit of a file were presented as a diff to local

### LINKED ISSUE #4580: Wrong diff for initial commit
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
gitext05

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Checkout 458ef9d6f76f0d6278c218717b7ce48750124e3d (from jbialobr fork)
2. Open file history for the SearchWindow.cs file
3. Go to the initial commit and see the diff tab.

**What is the expected behavior?**
gitext

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.15.1 
- OS version: win10

**Did this work in previous version of GitExtensions (which)?**

Yes: 2.50

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #4580
Regression from #4313

Non-existing commits are handled with the "revision" null which is mostly handled as a working directory file.
The compare options for working directory files were limited in 2.50. In 2.51 the changes are presented with git-diff if possible and the non-existing parent were incorrectly handled.

Screenshots before and after (if PR changes UI):
- 
image

- 
image

What did I do to test the code and ensure quality:
 - Manual tests of initial commits and to compare to/from working directory for changed/new/deleted files

Has been tested on (remove any that don't apply):
 - GIT 2.16
 - Windows 10

### CODE REVIEW

**Comment by gerhardol** [comment]
A similar fix needed for 2.51

**Comment by RussKie** [comment]
LGTM

File: GitUI/GitUIExtensions.cs [hunk 1]
```diff
@@ -88,6 +88,15 @@ public static Task ViewChanges(this FileViewer diffViewer, string firstRevision,
         {
             return diffViewer.ViewPatch(() =>
             {
+                if (firstRevision == null && secondRevision.IsNotNullOrWhitespace())
```
Comment (jbialobr) [inline GitUI/GitUIExtensions.cs]: This `if` is inside async task of loading a patch. It should be outside of it. I created a PR https://github.com/gerhardol/gitextensions/pull/2 to show how I would see it done.

Also replaced `secondRevision` in `if`  by ensuring it is not empty.

File: GitUI/HelperDialogs/FormCommitDiff.cs [hunk 2]
```diff
@@ -37,24 +38,40 @@ public FormCommitDiff(GitUICommands aCommands, string revisionGuid)
...
                 Cursor.Current = Cursors.WaitCursor;
-                DiffText.ViewChanges(DiffFiles.SelectedItemParent?.Guid, DiffFiles.Revision?.Guid, DiffFiles.SelectedItem, String.Empty);
-                Cursor.Current = Cursors.Default;
+                try
+                {
+                    await DiffText.ViewChanges(DiffFiles.SelectedItemParent?.Guid, DiffFiles.Revision?.Guid, DiffFiles.SelectedItem, String.Empty);
+                }
+                finally
+                {
+                    Cursor.Current = Cursors.Default;
```
Comment (jbialobr) [inline GitUI/HelperDialogs/FormCommitDiff.cs]: I wonder if we should change cursor to the WaitCursor during an async operation.
I think we should not. The "awaiting" status should rather be indicated by the control awaiting the async call.

File: GitUI/GitUIExtensions.cs [hunk 3]
```diff
@@ -86,11 +86,30 @@ public static Task ViewChanges(this FileViewer diffViewer, IList<GitRevision> re
...
             {
-                string selectedPatch = diffViewer.GetSelectedPatch(firstRevision, secondRevision, file);
-                return selectedPatch ?? defaultText;
-            });
+                // The previous commit does not exist, nothing to compare with
+                if (file.TreeGuid.IsNullOrEmpty())
+                {
+                    if (secondRevision.IsNullOrWhiteSpace())
+                    {
+                        throw new ArgumentException(nameof(secondRevision));
```
Comment (gerhardol) [inline GitUI/GitUIExtensions.cs]: For the release/2.51 merge, I propose that defaultText is returned here. Use of null for revisions need to be investigated in #4586

File: GitUI/HelperDialogs/FormCommitDiff.cs (hunk 2 above)
Comment (vbjay) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: I would make it waitcursor. The finally block will handle resetting it.

Comment (RussKie) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: Siding with Jay on this one

File: GitUI/GitUIExtensions.cs (hunk 3 above)
Comment (RussKie) [reply GitUI/GitUIExtensions.cs]: Agree

File: GitUI/HelperDialogs/FormCommitDiff.cs (hunk 2 above)
Comment (jbialobr) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: Cursor is kind of global object if you have to different async actions in progress you are not able to properly use it to indicate you are awaiting an action. I find it weird to see wait cursor that is able to click on controls and making them act.

File: GitUI/GitUIExtensions.cs (hunk 3 above)
Comment (jbialobr) [reply GitUI/GitUIExtensions.cs]: I prefer to fail to showing false data.

File: GitUI/HelperDialogs/FormCommitDiff.cs (hunk 2 above)
Comment (gerhardol) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: Agree with Janusz.
"Only" about 50 places to change.

Comment (vbjay) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: So store an async count using interlocked to modify. If count > 0 leave cursor at wait. If count = 0 default.

Comment (jbialobr) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: Actually changing the cursor does not work with async await, as soon as `await` is reached the cursor is changed accordingly to the pointed control. You can investigate it with
```csharp
Cursor.Current = Cursors.WaitCursor;
await Task.Delay(5000);
Cursor.Current = Cursors.Default;
```
The cursor changes to the wait cursor only for a fraction of second.

Comment (gerhardol) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: So in the current implementation, the cursor is not changed. If async/await is the way forward, this will have to be changed to all callers set a temporary result. Cursor->message change can be done in this PR or in a separate PR taking a bigger grip.

However, what to do in release/2.51? Either the first patch that is similar to the 2.50 solution, skip updated cursor or rewrite callers there too?

Comment (jbialobr) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: I would skip changing the cursor, the load time very short, I see no point in bothering this.

Comment (RussKie) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: I didn't give much though previously. I see a lot of sense in what Janusz and Gerhard are saying.

Comment (vbjay) [reply GitUI/HelperDialogs/FormCommitDiff.cs]:
```c#
            this.Cursor = Cursors.PanSW;
            await Task.Delay(5000);
            Cursor.Current = Cursors.Default;
            MessageBox.Show("Done");
```

Comment (vbjay) [reply GitUI/HelperDialogs/FormCommitDiff.cs]:
```c#
            Application.UseWaitCursor = true;
            await Task.Delay(5000);
            Application.UseWaitCursor = false;
            MessageBox.Show("Done");

Comment (gerhardol) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: I propose that the Cursor is not changed and no changed message is setup.

I tried changing the text to "Waiting..." while getting the text. It is more annoying to see something that just flashes by that you do not have time to read here. Also it is hard to find every place in the forms where to set the text. For instance, the text should not be used when searching.
Also for longer operations (adding a delay), I see no benefit, you kind of know what is going on.

So I propose that Wait Cursor related to this is just removed, both for master and 2.51

**Comment by RussKie** [comment]
+1

File: GitUI/HelperDialogs/FormCommitDiff.cs (hunk 2 above)
Comment (vbjay) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: You don't get it. The delay was test code. Put it  in a form with a button. Make the button click async void. Put either sample in the click event.

Comment (gerhardol) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: > You don't get it.

I get that you want the cursor. _I_ do not want the cursor changed here. I just have an opinion and leave it to @RussKie and @jbialobr to decide what to do.

**Comment by RussKie** [comment]
Let's minimise the change, leave the cursor as is

File: GitUI/HelperDialogs/FormCommitDiff.cs [hunk 4]
```diff
@@ -39,24 +40,34 @@ public FormCommitDiff(GitUICommands aCommands, string revisionGuid)
...
             {
-                Cursor.Current = Cursors.WaitCursor;
-                DiffText.ViewChanges(DiffFiles.SelectedItemParent?.Guid, DiffFiles.Revision?.Guid, DiffFiles.SelectedItem, String.Empty);
-                Cursor.Current = Cursors.Default;
+                await DiffText.ViewChanges(DiffFiles.SelectedItemParent?.Guid, DiffFiles.Revision?.Guid, DiffFiles.SelectedItem, String.Empty);
             }
         }
 
-        void DiffText_ExtraDiffArgumentsChanged(object sender, EventArgs e)
+        async void DiffText_ExtraDiffArgumentsChanged(object sender, EventArgs e)
```
Comment (RussKie) [inline GitUI/HelperDialogs/FormCommitDiff.cs]: I think this will set it off the StyleCop - please add `private` and cause unnecessary pain to @drewnoakes in #4587

Comment (drewnoakes) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: It'll conflict either way but will be easy to fix so don't hold back on my account. Thanks though.

Comment (gerhardol) [reply GitUI/HelperDialogs/FormCommitDiff.cs]: I rebased and applied changes

**Comment by gerhardol** [comment]
@RussKie OK to (squash) merge?
Will apply the same patch to 2.51, except that reporting "Error" instead of raising an exception (despite @jbialobr objecting). As the change is a little larger than I would prefer in a bugfix release, I suggest waiting applying it for a week, to get a little testing in master. (The alternative is the initial patch.)
