### PR TITLE
fix: compare branch check revgrid

### LINKED ISSUE #12484: [NBug] Value must not be null.
### Environment

- Git Extensions 5.2.1.18061
- Build 0d74cfdc312df90114a0cf8d6c8a30ca4213e2ff
- Git 2.47.1.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET 8.0.14
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.Exception: Value must not be null.
   at Microsoft.Validates.Fail(String message) in C:\projects\gitextensions\src\app\GitExtUtils\Validates.cs:line 35
   at Microsoft.Validates.NotNull[T](T value) in C:\projects\gitextensions\src\app\GitExtUtils\Validates.cs:line 20
   at GitUI.RevisionGridControl.CompareToBranchToolStripMenuItem_Click(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 2979
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### Steps to reproduce

Use branch comparison function: 
- Enter any part of branch name.
- Do not select actual branch from dropdown list.
- Press the Enter button.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #12484 

## Proposed changes

In revgrid->compare-Compare branches...
Show popupif no baseid found, if non existing branch written or the branches have no common ancestor.

## Test methodology 

Manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

File: src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs [hunk 1]
```diff
@@ -2997,7 +2997,12 @@ private void CompareToBranchToolStripMenuItem_Click(object sender, EventArgs e)
             {
                 Validates.NotNull(form.BranchName);
                 ObjectId baseCommit = Module.RevParse(form.BranchName);
-                Validates.NotNull(baseCommit);
+                if (baseCommit is null)
+                {
+                    MessageBox.Show(this, _noRevisionFoundError.Text, TranslatedStrings.Error, MessageBoxButtons.OK, MessageBoxIcon.Error);
```
Comment (mstv) [inline src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs]:
```suggestion
                ObjectId? baseCommit = Module.RevParse(form.BranchName);
                if (baseCommit is null)
                {
                    MessageBoxes.ShowError(this, _noRevisionFoundError.Text);
```
