### PR TITLE
Fixup missing graph

### LINKED ISSUE #9223: RevisionGrid not refreshed correctly after interactive rebase operations
## Current behaviour

The RevisionGrid is not refreshed after advanced / interactive rebase operations often.
After `Continue` / `Abort` from the `Rebase is currently in progress` banner, the Revision Graph disappears.

## Expected behaviour

Grid is updated, graph is visible.

## Steps to reproduce

- select the current commit
- navigate to previous
- context menu `Advanced | Edit commit` -> the `Rebase ...` banner appears but the revisions are not updated often 
- `Continue` / `Abort` -> graph disappears

## Screenshots

rows not updated:

grafik

OK after `F5`:

grafik

After `Abort`:

no graph

## Workaround?

Turn off `FileSystemWatcher` for index

grafik

## Did this work in previous version of GitExtensions

at least not for months

## Environment

- Git Extensions 3.6.0.11771
- Build 43a5e53eb416870cd4d1d64e3a56a71c55e9733b (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by mstv**
Fixes missing graph after double refresh within 200-500 ms.
Might fix #9223

## Proposed changes

- Invalidate graph column on width change

### Before

graph column with one lane (often empty)

### After

full graph visible

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

File: GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs [hunk 1]
```diff
@@ -225,7 +225,12 @@ public override void OnVisibleRowsChanged(in VisibleRowRange range)
 
             // Keep an extra page in the cache
             _graphCache.AdjustCapacity((range.Count * 2) + 1);
-            Column.Width = CalculateGraphColumnWidth(range);
+            int width = CalculateGraphColumnWidth(range);
+            if (Column.Width != width)
+            {
+                Column.Width = width;
+                Column.DataGridView.InvalidateColumn(Column.Index);
```
Comment (gerhardol) [inline GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs:232]: I would expect that chagning the width would invalidate, but should not be harmful.

**Review by gerhardol — APPROVED** [review]
I do not see #9223 improvements
There are some artifacts for me (also without this), do not know if this is due to other patches in what I use. Started seeing it around .NET8

File: GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs (hunk 1 above)
Comment (mstv) [reply GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs:232]: > I would expect that changing the width would invalidate

Me too, but it does not.

---

> There are some artifacts.

If you mean missing parts of secondary lanes (when scrolling up), I know that - but not yet how to resolve it.
All other artifacts should be fixed by #11480.

**Review by RussKie — APPROVED** [review]
